### ISSUE TITLE
SPC-m-s-i python-start-or-switch-repl does not start a REPL

### ISSUE THREAD

**Issue by kdheepak** [syl20bnr/spacemacs#2872] opened 2015-09-03 15:52 UTC
`python-start-or-switch-repl` does not start a REPL

> python-shell-get-process-or-error: No inferior Python process running.

If I start a shell with `Ctrl-c Ctrl-p` then `SPC-m-s-i` switches to the REPL

I'm on the `develop` branch

**Comment by geo7** [comment] 2015-09-03 16:29
https://github.com/syl20bnr/spacemacs/issues/1571

**Comment by sooheon** [comment] 2015-09-03 23:03
@geo7 This is a different error from that, I'm experiencing it too. It's not that there some wrong binding, even calling with M-x give the "no inferior python process running" error.

**Comment by cpaulik** [comment] 2015-09-04 06:38
This seems strange to me. Which emacs version are you using?

The function `python-start-or-switch-repl` is only this:
```elisp
      (defun python-start-or-switch-repl ()
        "Start and/or switch to the REPL."
        (interactive)
        (python-shell-switch-to-shell)
        (evil-insert-state))
```

What happens if you call `python-shell-switch-to-shell` ? This should work since it is coming from the built-in `python.el`

**Comment by cpaulik** [comment] 2015-09-04 06:44
What happens if you call `run-python` or do `M-: (python-shell-parse-command)`?

The first one should start a python shell without asking or anything and the second one should give you something like `"/usr/local/bin/ipython -i"`

**Comment by sooheon** [comment] 2015-09-04 09:43
#2360 is more similar to what I'm experiencing, and I am using emacs 25 dev, which I why I hadn't created an issue--it's probably emacs itself thats the problem. FWIW neither of those commands work for me.

**Comment by kdheepak89** [comment] 2015-09-04 17:40
@cpaulik When I run `(python-shell-parse-command)` in the scratch directory with `C-x C-e` I get the following
> `ipython -i`

`run-python` using `SPC :` opens a ipython REPL shell

When I run `run-python` using `SPC :` I get the following
> user-error: Start a Python process first with ‘C-c C-p’ or ‘C-c C-p’.

**Comment by cpaulik** [comment] 2015-09-05 10:36
@kdheepak89 Your last two statements seem to contradict?

Have you also tried `python-shell-switch-to-shell`?

**Comment by kdheepak89** [comment] 2015-09-08 18:49
@cpaulik Sorry about that I've updated the previous comment

**Comment by cpaulik** [comment] 2015-09-08 22:44
hmm, if `run-python` works but `python-shell-switch-to-shell` does not then you have to debug `python-shell-get-or-create-process`. This function basically calls `run-python` so I'm not sure where it goes wrong.

**Comment by dsdshcym** [comment] 2015-10-30 01:55
@kdheepak89 Is this issue still valid? I can't reproduce it on my machine.

**Comment by lukeorland** [comment] 2015-12-07 17:01
> `python-start-or-switch-repl` does not start a REPL

> > `python-shell-get-process-or-error: No inferior Python process running.`

> If I start a shell with Ctrl-c Ctrl-p then SPC-m-s-i switches to the REPL

> I'm on the develop branch

Same situation for me. IPython is installed in the virtualenv that I activated via `SPC m  V`, but not necessarily in the system python environment.

How can I debug? I would rather that the IPython repl is started and opened after `SPC m s i`.

**Comment by a-sk** [comment] 2015-12-08 09:37
I use the following function to switch to the REPL and it works for me:

```lisp
(defun my-python-start-or-switch-repl (&optional msg)
  "Start and/or switch to the REPL."
  (interactive "p")
  (if (python-shell-get-process)
      (python-shell-switch-to-shell)
    (progn
      (run-python)
      (python-shell-switch-to-shell)
      )
    )
  )
```

**Comment by d2207197** [comment] 2016-07-07 07:53
where's the definition of `python-start-or-switch-repl`. I can't find it in `python.el`.

and I found that if we set the optional argument `msg` of `python-shell-switch-to-shell`  to non-nil. It works correctly.

**Comment by d12frosted** [comment] 2016-07-08 05:53
@d2207197  `SPC h d f python-start-or-switch-repl` will help you 😄 Don't find anything by hand - always ask Emacs first. 💃

**Comment by d2207197** [comment] 2016-07-09 11:02
@d12frosted I have checked that before. nothing helps
![image](https://cloud.githubusercontent.com/assets/73888/16707616/9ba15ba0-4607-11e6-9283-dfdfe7dc81df.png)

**Comment by d12frosted** [comment] 2016-07-10 08:14
@d2207197 Sorry, I don't use python layer (and for some reason it errors when I enable it), so I can't check why it's description doesn't have `It's defined in ...` section. For example,

```
dotspacemacs/init is a Lisp function in ‘../../spacemacs.el’.

(dotspacemacs/init)

Initialization function.
This function is called at the very startup of Spacemacs initialization
before layers configuration.
You should not put any user code in there besides modifying the variable
values.
```

But quick search helped me to locate it in [python layer](https://github.com/syl20bnr/spacemacs/blob/master/layers/+lang/python/packages.el#L226).

**Comment by d12frosted** [comment] 2016-09-29 05:25
Forgot to share why it can't be located using describe system. It turns out Emacs can't help with that if the function is defined within another function. That's why we are slowly moving most of the functions to `func.el` file.

There is pending PR for that - #7070. Could someone please verify that it fixes the problem?

**Comment by lukeorland** [comment] 2016-10-13 20:32
This PR is working. However, one issue remains. When the repl opens, the python buffer I called `, s i` from is replaced by a new buffer window with the following contents:

```
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 
```

**Comment by TheBB** [comment] 2016-10-20 09:11
Should be fixed in master.

**Closed by TheBB** 2016-10-20 09:11 UTC
Labels: - Bug tracker -, <=(- UBO -)=>, Fixed in develop, Python
