### ISSUE TITLE
Emacs stuck on "Initializing..." when loading a Haskell file

### ISSUE THREAD

**Issue by mrkgnao** [syl20bnr/spacemacs#2966] opened 2015-09-09 20:17 UTC
Preamble: I am very, very inexperienced when it comes to Emacs. (I'm running 25.0.50 on Ubuntu 14.04.)

So I'm trying to get a little Haskell development environment set up (preferably with stack, but I'm having trouble enough with plain old ghc). 

I enabled the haskell layer. Now, whenever I open a Haskell file, Emacs freezes saying "Initializing...". Ctrl-G stops the freezing and shows me the source, and the error log says "File mode specification error: (error "Process <foldername> not running")". 

How do I stop this from happening and hopefully get completion and structured-haskell-mode set up? There's also a lot of lag when I use any motions like j/k/w/b.

Edit: https://github.com/syl20bnr/spacemacs/issues/2142#issuecomment-140355603
Edit (@StreakyCobra): [Related reddit thread](https://www.reddit.com/r/haskell/comments/3kr6m3/update_i_got_spacemacs_working_using_stack_with/)

**Comment by d12frosted** [comment] 2015-09-09 20:33
Yeah, there is such problem. This is possible duplicate of #2896. It was also briefly discussed in various threads. But that's expectable, since the problem is really annoying.

I understand that this is totally not good solution in general, but you can use my [private layer](https://github.com/d12frosted/environment/tree/master/emacs/d12-haskell) meanwhile. For completion it uses `company-ghci` - which works well with `stack`. 

```lisp
(setq-default dotspacemacs-configuration-layers
   '((d12-haskell :variables haskell-enable-hindent-style "chris-done"
                             haskell-enable-shm-support t
                             haskell-process-type 'stack-ghci)))
```

As for lagging - don't have anything to say, sorry.

**Comment by geo7** [comment] 2015-09-12 22:58
@d12frosted is the lag 25.5 related? I can't remember whether you were running 25.5 or not

**Comment by d12frosted** [comment] 2015-09-13 06:55
@geo7 No. I am running on `24.5`.

**Comment by geo7** [comment] 2015-09-14 12:36
@mrkgnao I think I remember you saying that you had got this sorted in the gitter chat? 

If so it'd be cool to close this issue, and possibly add a note at the end of your original post mentioning what you did :)

**Comment by mrkgnao** [comment] 2015-09-15 17:23
Yup! 
https://github.com/syl20bnr/spacemacs/issues/2142#issuecomment-140355603

**Comment by geo7** [comment] 2015-09-15 23:32
@mrkgnao nice one :+1: maybe include that link in the top post (of this issue) and if all's good this can be closed :)

**Comment by secwang** [comment] 2015-09-29 00:43
@d12froste 👏

**Comment by StreakyCobra** [comment] 2015-11-06 18:30
I've also added the reddit's link to the original post. Everything seems fine as there was no update last 2 months, so I'll close this one :smile: Feel free to reopen it (or to open a new one) in case of problems.

**Closed by StreakyCobra** 2015-11-06 18:30 UTC
Labels: Haskell
