### ISSUE TITLE
No option for global auto-complete

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1043] opened 2015-04-03 14:43 UTC
Since 769d54da026d60cb3d9d3c33e213604c2b6a46af there is no longer a built in way to have auto-complete in almost every mode. As someone who uses umpteen million different programming languages (see `extra-langs` layer) this makes me sad.

I think there should be either a config variable or a layer that enables company-mode's default backend list globally. The most important thing in this list is `company-dabbrev-code` which is just completion just based on other things in the buffer, which is usually what you want in languages without a specific backend.

**Comment by syl20bnr** [comment] 2015-04-04 00:55
This is by design, in the official spacemacs layers the auto-completion engine and backends are enabled by cherry-picking. This is a crucial thing to have if we want our layers to be isolated.

Previously it was a total mess because of the global scope of the auto-completion minor modes. Auto-complete was enabled globally so the company-layer had to exclude auto-complete to take its place, it made it really hard (or even impossible) for a user to use both auto-complete and company (see the history on the gitter chat of nikki93 trying to do so).

**Comment by trishume** [comment] 2015-04-04 01:21
That's why I'm saying it should be an option. Most people won't need it but for people like me who use and learn new and niche languages compulsively global completion even if it is lame buffer-based completion is useful.

I'll probably write this myself and PR it since it's something I need but not everyone else does.

**Comment by syl20bnr** [comment] 2015-04-04 01:47
Ok so you propose to add by default a backend for completion based on the current buffer. It can be added to the macro at the last element of the backend list then.
There is no such thing as global auto-completion in spacemacs, it has to be explicitly setup in the layer and packages. I won't trade the 2 lines of code that give proper isolation for a global mode, not in spacemacs official layers.

**Comment by trishume** [comment] 2015-04-04 20:32
If you mean something like adding a config variable and checking that and adding `company-dabbrev-code` to the back of `spacemacs|enable-company` I think that's a great solution.

But I think there should be a sane default or at least a macro so that layer contributors don't have to add a bunch of boilerplate every time they add a new mode.

Take for example the proposed LLVM layer (#1057), I already think that is a lot of boilerplate to have for just installing a package. However, in order to have that global autocomplete solution work they would also have to copy-paste the 6 lines of boiler plate required just to activate auto-completion for a mode even without adding any backends. 

These same 6 lines would also have to copied for the approximately 30 (my count from grepping and manual counting) little language modes. Maybe it's the DRY rubyist in me but I don't think copy-pasting is the best solution. 

I was trying to get somewhere closer to DRY with my earlier 1 line macro solution but I think ideally it should take 0 lines for modes that don't want to add any backends (e.g LLVM mode) just to get the global autocomplete setting to work. Then ideally a 1 line macro for most other modes.

Still the exact same architecture, I just want to abstract away the boilerplate and then apply a default backend list (empty or `dabbrev` by preference) to major modes that haven't done any setup. I'll have to think about how to do the elisp-ing for this but I'm sure it's doable.

**Comment by TheBB** [comment] 2015-08-25 19:30
Closing, since this appears to have been discussed ad nauseam here and in other places.

**Closed by TheBB** 2015-08-25 19:30 UTC
Labels: discussion

**Comment by xiaohanyu** [comment] 2016-04-08 09:02
@trishume I've seen your discussion and I think there's a simple way to enable auto-completion as follows:

```
  (dolist (mode-hook '(text-mode-hook
                       org-mode-hook
                       prog-mode-hook
                       ruby-mode-hook))
    (add-hook mode-hook
              (lambda ()
                (spacemacs/toggle-auto-completion-on)
```

In Emacs, most major mode for programming languages are derived from `prog-mode-hook`, so just add a hook function which enables auto-completion to `prog-mode-hook`, then you'll get auto-completion enabled for most programming languages.

Hope it helps.
