### ISSUE TITLE
Cycling through TODO workflow joins the next line onto the current one

### ISSUE THREAD

**Issue by blablablerg** [syl20bnr/spacemacs#13901] opened 2020-09-01 10:18 UTC
Hello, I am just starting to learn org mode with spacemacs and I stumbled upon something strange, I don't know if it is a bug or not.
But when I set some tasks to DONE and fold the headings with TAB, then when I cycle back from DONE to TODO it joins the next line with the current one. Does anyone know how to prevent this? Also, I have tested this with emacs Doom, but it doesn't happen there, so thats why I decided to report it here.

Could it be something with the header icons? Because in Doom Emacs they are just stars, and in spacemacs they change in to different symbols. 

 
![org_mode_bug](https://user-images.githubusercontent.com/22841170/91837051-ed877000-ec4b-11ea-9698-151288dcc853.gif)

#### Reproduction guide 🐞 

- Make two TODO headings in org mode
- Cycle both TODO items to DONE
- Fold the headings (so the dots appear, because the timestamp gets folded with the heading)
- Cycle the first DONE heading

*Observed behaviour:* 👀 💔 
The next line gets joined on the current one. 

*Expected behaviour:* ❤️ 😄 
No joining of lines.

#### System Info 💻 
- OS: gnu/linux (WSL2, connected via X410 to Windows)
- Emacs: 28.0.50 (also tested it on 26.1, same behaviour observed)
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a0728abf1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp org themes-megapack treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2

**Comment by blablablerg** [comment] 2020-09-01 19:10
I also see the same behavior under windows (not WSL). And I found out how to disable org-superstar, but still the bug :/

**Comment by smile13241324** [comment] 2020-09-01 21:55
I can reproduce your issue @blablablerg, looks like this is caused by a missing empty line between the two headlines.
If there is at least one additional line added to the task either as sub-header or an empty line it works as expected.

A quick check revealed that this is most likely be caused by `org-todo` when it removes the "CLOSED" keyword. I am not sure if this is not an issue with the latest org version we are using. I will mark this down for a more detailed analysis in the next few days.

Thanks for reporting, and welcome to the Spacemacs community :purple_heart: 

BTW: as a quick workaround, you could add an `outcome` sub-heading to each task, summarising the benefits you have from completing this task. That's a common conception in task management systems like GTD and does not only help to get a clearer focus of your tasks but also should prevents this issue from happening.

**Comment by emacs18** [comment] 2020-09-02 06:00
I too see this problem.  However this seems to be a temporary display problem only.  When two headings are displayed on the same line, just hitting `Shift-TAB` resolves the problem, i.e., the headings are shown on separate lines.

**Comment by blablablerg** [comment] 2020-09-02 07:50
Great help guys, thanks!

**Comment by duianto** [comment] 2020-09-17 10:04
The same thing is observed without Spacemacs, with just `emacs -q`.
Emacs 26.3 (above) and 27.1 (below):

![emacs_2020-09-17_11-59-12](https://user-images.githubusercontent.com/13420573/93456140-92a57800-f8dd-11ea-8c46-7a5530bf72dd.png)

Unrelated, but I'm not sure why only 26.3 has colors, maybe somethings changed in 27.1.

**Comment by smile13241324** [comment] 2020-09-17 20:40
@duianto whoa thanks for the help, care to open the issue upstream?

**Comment by blablablerg** [comment] 2020-09-18 07:00
Ah, sorry for the confusion. Next time i will try emacs -q. I will try to report it upstream.

**Comment by duianto** [comment] 2020-09-19 10:40
>sorry for the confusion

There was no confusion, you found an issue and reported it 👍

That lead to a discovery of an upstream bug.

When it's fixed, then non-Spacemacs users also will benefit from the fix.

@blablablerg The issue can be reported by sending an email to: emacs-orgmode@gnu.org

**Comment by blablablerg** [comment] 2020-09-20 06:39
I reported it!

**Comment by duianto** [comment] 2020-09-23 12:12
I saw that they are wondering how to get the timestamp to appear when cycling to DONE.
https://lists.gnu.org/archive/html/emacs-orgmode/2020-09/msg00909.html

I forgot to mention in my test without Spacemacs, that the timestamp doesn't appear by default in `emacs -q`, because the variable `org-log-done` is set to `nil`, it has to be changed to `'time`:
```elisp
(setq org-log-done 'time)
```

I don't know how to post an answer to that thread.

**Comment by emacs18** [comment] 2020-09-23 13:30
I replied to the email.

**Comment by emacs18** [comment] 2020-09-23 13:50
I also replied to the email thread with the following.  Typing `C-x C-e` with cursor just beyond the last closing parenthesis demonstrated the problem for me. I hpe that this works for others as well.

```elisp
(let ()
  (switch-to-buffer (generate-new-buffer "*demo line joining bug*"))
  (erase-buffer)
  (org-mode)
  (setq org-log-done 'time)
  (insert "* one\n")
  (insert "* two\n")
  (goto-line 1)
  (org-todo)
  (org-todo)
  (org-todo)
  (org-cycle)
  (org-todo)
  (org-todo)
  )
```

**Comment by duianto** [comment] 2020-09-23 14:07
For me that results in:
```
* DONE one
  CLOSED: [2020-09-23 Wed 16:06]
* two
```

**Comment by emacs18** [comment] 2020-09-23 14:11
How about this one?  I tested this one on `emacs -q`.

```elisp

(let ()
  (switch-to-buffer (generate-new-buffer "*demon line joining bug*"))
  (erase-buffer)
  (org-mode)
  (setq org-log-done 'time)
  (insert "* one\n")
  (insert "* two\n")
  (goto-line 2)
  (org-todo)
  (org-todo)
  (org-cycle)
  (goto-line 1)
  (org-todo)
  (org-todo)
  (org-cycle)
  (org-todo)
  )
```

**Comment by duianto** [comment] 2020-09-23 14:18
That seems to demonstrate the issue

![emacs_2020-09-23_16-15-53](https://user-images.githubusercontent.com/13420573/94024947-46b07280-fdb8-11ea-9f4f-d4498b6d464b.png)

**Comment by duianto** [comment] 2020-09-23 14:28
I reduced some of the steps and this also demonstrates the issue:
```elisp
(let ()
  (switch-to-buffer (generate-new-buffer "*demon line joining bug*"))
  (erase-buffer)
  (org-mode)
  (setq org-log-done 'time)
  (insert "* one\n")
  (insert "* two\n")
  (goto-line 1)
  (org-todo)
  (org-todo)
  (org-cycle)
  (org-todo)
  )
```

![emacs_2020-09-23_16-26-55](https://user-images.githubusercontent.com/13420573/94026297-c559df80-fdb9-11ea-8def-ab91380ea8b2.png)

**Comment by emacs18** [comment] 2020-09-23 14:30
Even better.

**Comment by duianto** [comment] 2020-09-23 14:32
```elisp
(buffer-substring (point-min) (point-max))
```
returns:
```
#("* one
* two
" 0 1 (fontified t org-todo-head "TODO" face org-level-1) 1 2 (fontified t org-todo-head "TODO" face org-level-1) 2 5 (fontified t org-todo-head "TODO" face org-level-1) 5 6 (fontified t) 6 7 (fontified t face org-level-1) 7 8 (fontified t face org-level-1) 8 11 (fontified t face org-level-1) 11 12 (fontified t))
```

**Comment by emacs18** [comment] 2020-09-23 14:38
`(buffer-substring-no-properties (point-min) (point-max))` might be better in this case.

**Comment by duianto** [comment] 2020-09-23 14:48
That just copies the text, as can be done with:
`M-<` (`beginning-of-buffer`)
`C-SPC` (`set-mark-command`)
`M->` (`end-of-buffer`)
`M-w` (`kill-ring-save`)

I just thought that the properties might be related to the issue, or is the fontified stuff just about colors?

**Comment by duianto** [comment] 2020-09-23 15:05
A fix was posted:
https://lists.gnu.org/archive/html/emacs-orgmode/2020-09/msg00961.html

It seems to be working, the latest reproduction steps above: https://github.com/syl20bnr/spacemacs/issues/13901#issuecomment-697445561

now results in:

![emacs_2020-09-23_17-03-33](https://user-images.githubusercontent.com/13420573/94031274-fa1c6580-fdbe-11ea-8d7e-07722edcdd47.png)

**Comment by emacs18** [comment] 2020-09-30 03:22
I concur.   I think this issue should be closed now.

**Comment by duianto** [comment] 2020-09-30 09:46
The fix has been applied upstream:
https://code.orgmode.org/bzg/org-mode/commit/5d4c0f59d813e63a1d4eb36496f80ac8fa63007b

Should we close this issue now or wait until the fix has been released?

Possibly in org-mode version 9.5?

I'm guessing that it might take a while, because the fix for a previous issue:
emacs hangs after evil-open-below in org-mode #13684

was applied upstream 2 months ago:
https://code.orgmode.org/bzg/org-mode/commit/07a4a728628776202d58a48436da9f710e11cb8e

the fix was included with 9.4, which was released 14 Sep 2020
https://lists.gnu.org/archive/html/emacs-orgmode/2020-09/msg00603.html

9.3 was released 03 Dec 2019
https://lists.gnu.org/archive/html/emacs-orgmode/2019-12/msg00041.html

**Comment by emacs18** [comment] 2020-09-30 15:05
I think orgmode.org/elpa/ already has updated packages

**Comment by duianto** [comment] 2020-09-30 16:13
I updated the packages before my previous comment, and I already had the latest version:
`org-plus-contrib-20200928`

The fix hasn't been included yet.

The reproduction steps above https://github.com/syl20bnr/spacemacs/issues/13901#issuecomment-697445561 still join the two lines.

**Comment by emacs18** [comment] 2020-09-30 17:05
The fix was checked into master branch of org-mode via 
https://code.orgmode.org/bzg/org-mode/commit/5d4c0f59d813e63a1d4eb36496f80ac8fa63007b
late on Sep 28.  Hence this should be included in the next week's release of org-mode.

**Comment by duianto** [comment] 2020-10-05 09:05
I just updated the packages, and there was a `org-plus-contrib` updateand the fix was included

**Closed** 2021-08-24 02:32 UTC
Labels: Fixed upstream, Org
