### ISSUE TITLE
Eshell doesn't remember history

### ISSUE THREAD

**Issue by bandali0** [syl20bnr/spacemacs#8538] opened 2017-03-16 04:07 UTC
#### Description :octocat:
Eshell doesn't remember history

#### Reproduction guide :beetle:
- Start Emacs
- `M-m a s e` (start Eshell)
- Type out a few commands (e.g. `pwd`, `ls`, `uname`)
- `C-d` (exit the Eshell)
- `M-m a s e` (start Eshell again)
- `M-p`

*Observed behaviour:* :eyes: :broken_heart:
- `M-p` results in displaying _Empty input ring_ in the minibar.
- Eshell doesn't save history (`~/.emacs.d/.cache/eshell/` has no files)

*Expected behaviour:* :heart: :smile:
- `M-p` should go back through the history.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. e624e8f0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(aminb auto-completion
       (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first t)
       bibtex c-c   emacs-lisp git haskell html ivy latex markdown org rust
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       shell-scripts spell-checking syntax-checking version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```

```

**Comment by bmag** [comment] 2017-03-16 19:58
I can confirm that if I open Eshell via `SPC a s e` (`spacemacs/shell-pop-eshell`) then the history isn't saved when exiting the shell. However, if I open the shell via `M-x eshell`, then it does save the history when exiting the shell.

After running `SPC a s e` and closing the Eshell buffer with `C-d`, I invoked `M-x shell-pop` directly to get an Eshell buffer, and its history as well wasn't saved after I exited with `C-d`. (I checked if history was saved by opening a new `M-x eshell` and pressing `M-p`.)

Perhaps a problem with `shell-pop` or with our configuration of `shell-pop`, or perhaps Eshell doesn't work well with the buffer name given by `shell-pop` (a somewhat wild guess). If anyone wants to investigate this, sounds like an interesting bug.

**Comment by thornjad** [comment] 2019-04-16 02:14
@aminb are you still experiencing this on the latest develop branch?

**Comment by Compro-Prasad** [comment] 2019-04-16 04:59
I just tested it. This bug is still there.

**Comment by aminb** [comment] 2019-04-16 05:07
Sorry @thornjad I've long since stopped using spacemacs, and now use my own emacs configuration. For what it's worth, eshell history works fine with vanilla emacs + my configs.

**Comment by Compro-Prasad** [comment] 2019-04-16 05:31
I found the reason. Its the value of `eshell-exit-hook` that is the problem. In the popup buffer its value is:
```
(shell-pop--kill-and-delete-window eshell-write-history eshell-write-last-dir-ring t)
```
While in normal `M-x eshell` its:
```
(eshell-write-history eshell-write-last-dir-ring t)
```

**Comment by natemoseman** [comment] 2020-01-02 22:58
I think I found the problem.  However I am not a elisp programmer, so I am not sure if my solution is the correct one. 

Spacemacs shell layer uses 'shell-pop' extension.

In this file:
https://github.com/kyagi/shell-pop-el/blob/master/shell-pop.el

in the 'shell-pop--set-exit-action' function on line 262... changing:
`(add-hook 'eshell-exit-hook 'shell-pop--kill-and-delete-window nil t)`

to 
`(add-hook 'eshell-exit-hook 'shell-pop--kill-and-delete-window t t)`

This changed it so that add-hook appends the function to the hook list.  So now 'eshell-exit-hook' gets set to:

(eshell-write-history eshell-write-last-dir-ring t shell-pop--kill-and-delete-window)


So I think that what was happening is that the eshell was exiting before it had a chance to write the history.  Changing the order of the hooks now allows eshell to save it's history before the frame is deleted. 

filed https://github.com/kyagi/shell-pop-el/issues/66

**Comment by bcc32** [comment] 2021-01-08 16:07
I am still experiencing this issue but it appears there have been no responses on the issue in the upstream repo.

**Comment by evorion** [comment] 2023-07-13 10:21
I am experiencing this issue today. It's still not resolved.

**Comment by smile13241324** [comment] 2024-09-01 07:57
Still there and not fixed upstream maybe we can find a workaround

**Comment by smile13241324** [comment] 2024-09-03 18:27
I have added a workaround to Spacemacs circumventing the bug in the ticket. The issue is indeed that the window is set before the store history calls in the shutdown hook.

**Closed by smile13241324** 2024-09-03 18:27 UTC
Labels: Bug :-(, Reported upstream, Shells in Emacs, - Bug tracker -
