### ISSUE TITLE
Shortcut keys for ESS mode do not work

### ISSUE THREAD

**Issue by biocyberman** [syl20bnr/spacemacs#13485] opened 2020-04-14 19:00 UTC
#### Description :octocat:
Shortcut keys for ESS mode do not work

#### Reproduction guide :beetle:
- Start Emacs
- Enable ess
- Open and edit an `.R` file

*Observed behaviour:* :eyes: :broken_heart:
 `SPC m` says `SPC m is undefined`. Status bar says `ESS[R]` as major mode. I can use `SPC m` in other modes, for example `Emacs-lisp` mode. 

*Expected behaviour:* :heart: :smile:
`,` (comma) or `SPC m` presents mode specific menu for `ESS` according to manual of ESS layer
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm ess emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GSETTINGS GLIB NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS

**Comment by duianto** [comment] 2020-05-10 17:37
This is a duplicate of this issue:
ESS major mode keybindings are undefined. #12773

There's a workaround for the `master` branch by configuring the key bindings manually from the user config:
https://github.com/syl20bnr/spacemacs/issues/12773#issuecomment-600528158

As stated in a previous comment
https://github.com/syl20bnr/spacemacs/issues/12773#issuecomment-537470044
the `SPC m` key bindings work without having to define them manually on the `develop` branch.

**Closed** 2020-09-24 13:59 UTC
Labels: Duplicate ☝
