### ISSUE TITLE
warnings on spacemacs startup

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#1299] opened 2015-04-21 14:54 UTC
This shows up everytime I start spacemacs:
```
Loading /home/edwin/.emacs.d/contrib/auto-completion/packages.el (source)...done
.emacs.d/elpa/eval-sexp-fu-20131230.1351/eval-sexp-fu.el: `labels' is an obsolete macro (as of 24.3); use `cl-labels' instead.
.emacs.d/elpa/eval-sexp-fu-20131230.1351/eval-sexp-fu.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'. [2 times]
.emacs.d/elpa/eval-sexp-fu-20131230.1351/eval-sexp-fu.el: `dont-compile' is an obsolete macro (as of 24.4).
Loading /home/edwin/.emacs.d/spacemacs/keybindings.el (source)...done
Loading /home/edwin/.emacs.d/.cache/recentf...done
Start checking for new version...
ad-handle-definition: `find-function-search-for-symbol' got redefined
Starting new Ispell process [aspell::english] ...
Spacemacs is ready.
ad-handle-definition: `tramp-read-passwd' got redefined
Helm completion enabled
Spacemacs is up to date.
```

The message about `dont-compile` shows up in the status bar too during startup.

```
(emacs-version)
"GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5)\n of 2015-03-07 on trouble, modified by Debian"
```

**Comment by syl20bnr** [comment] 2015-04-21 16:40
What is the message about `dont-compile` ? I don't see it above.

**Comment by syl20bnr** [comment] 2015-04-21 16:41
related to #192 (I put duplicate even if there is `eval-sexp-fu`)

**Comment by edwintorok** [comment] 2015-04-21 18:14
This is the message about dont-compile:
```
.emacs.d/elpa/eval-sexp-fu-20131230.1351/eval-sexp-fu.el: `dont-compile' is an obsolete macro (as of 24.4).
```

**Comment by syl20bnr** [comment] 2015-09-30 01:14
I cannot reproduce this bug, closing it, feel free to re-open it if it is still present.

**Closed by syl20bnr** 2015-09-30 01:14 UTC
Labels: package
