### ISSUE TITLE
company-tern got pulled from melpa

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#13530] opened 2020-04-27 11:40 UTC
I was just trying out emacs 27 prerelease and there was an error during install. I think the `javascript` layer uses this. 

See also here:
https://www.reddit.com/r/emacs/comments/g8i10n/companytern_on_melpa_pulled/

**Comment by dennismayr** [comment] 2020-04-28 18:39
Yes, `company-tern` is referenced by the `javascript` layer, even if not used.
I'm using `lsp` as `javascript` backend, but `company-tern` is still queued for download.

Any `javascript`-related layer triggers the download: `react`, `typescript`, `vue`...

**Comment by rwanyoike** [comment] 2020-05-05 22:23
Upstream: https://github.com/melpa/melpa/pull/6854

**Comment by steshaw** [comment] 2020-05-06 03:07
Is it safe to ignore the error?

**Comment by jr0cket** [comment] 2020-05-06 09:05
When using `lsp` for JavaScript the `company-tern` package is not required.  Until PR #13533 is merged into `develop` then add the package name to the `dotspacemacs--excluded-packages` list in the `.spacemacs` or `.spacemacs.d/init.el` file.

``` dotspacemacs-excluded-packages '(company-tern)```

**Comment by smile13241324** [comment] 2020-05-11 07:42
@gdkrmr I have merged the fix, can you have a look and close the issue if it is solved?

**Comment by humitos** [comment] 2020-05-29 11:58
Just to say that using `develop` branch, this is not an issue anymore to me :tada:

**Comment by smile13241324** [comment] 2020-05-31 21:59
Great, then I will close it.

**Closed by smile13241324** 2020-05-31 21:59 UTC

**Comment by hyiltiz** [comment] 2020-09-14 23:04
Somehow even with that exclude rule in place (and been using develop for at least two years since ), this managed to bite me again. Now blacklisting any packages that has `tern` in it, and the javascript layer. Maybe also any html or web dev related layers... This simply crashes spacemacs while loading for me, reading to a startup loop (I am using Spacemacs in server mode).

**Comment by smile13241324** [comment] 2020-09-16 18:47
Sorry to hear that, I have not heard that others have similar issues. Care to make an issue with reproduction steps? Maybe someone from the community can help with reproducing the issue.

**Comment by fredrikatmainspringenergy** [comment] 2021-01-25 01:39
I have the same issue.

**Comment by smile13241324** [comment] 2021-02-07 22:30
No idea where this comes from, if you still experience this issue on latest develop please open a new issue with reproduction steps, I will then gladly have a look.
