### ISSUE TITLE
Evil Surround no longer adds surround character

### ISSUE THREAD

**Issue by chriskaukis** [syl20bnr/spacemacs#11019] opened 2018-07-11 03:20 UTC
#### Description :octocat:
Evil surround no longer works. All the Evil Surround commands except adding seem to work on develop branch. It appears to work on master branch.

I tried a completely fresh install also from the main Spacemacs repo removing any and all custom configurations.

#### Reproduction guide :beetle:
- Start Emacs
- Go to any file, for my tests I always used .spacemacs file, `SPC f e d`
- Find any text to add parens or quotes or anything
- Type the add evil surround command, for example `yss)`
- After hitting the second `s` it deletes the current character under the cursor and drops into insert mode

### NOTE
- Disabling and enabling evil-surround-mode fixes the issue
- I have been in Gitter about this and I have been trouleshooting this for days(!!!)

*Observed behaviour:* :eyes: :broken_heart:
- Deletes current character under cursor and drops into insert mode

*Expected behaviour:* :heart: :smile:
- Expect to add the surround character

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c1bde286e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm imenu-list auto-completion better-defaults emacs-lisp git markdown neotree org shell spell-checking syntax-checking version-control unicode-fonts themes-megapack
      (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
      games erc scheme c-c++ asm sql
      (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm ruby-backend 'lsp)
      python ruby-on-rails javascript html lsp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
No errors are reported
```

**Comment by Miciah** [comment] 2018-07-11 06:33
This issue is caused by https://github.com/syl20bnr/spacemacs/commit/03786aa94a334aa1a2a15f95300751a6074dec84.

Workaround: Enter visual mode.  This will trigger lazy loading of evil-surround.  `ys` will then work properly for the remainder of the Spacemacs session.

**Comment by chriskaukis** [comment] 2018-07-11 12:00
Yes, I should add using visual mode then pressing `s)` (or the surround character you want) does work.

**Comment by bmag** [comment] 2018-07-12 08:39
@chriskaukis @dubnde can any of you confirm that adding the following to `dotspacemacs/user-init` fixes the issue?

```elisp
(spacemacs|add-transient-hook evil-operator-state-entry-hook
  (lambda () (require 'evil-surround))
  lazy-load-evil-surround-2)

```

**Comment by dubnde** [comment] 2018-07-12 08:46
@bmag  Yes I can confirm the code snippet you provided works when added to `dotspacemacs/user-init`

**Comment by bmag** [comment] 2018-07-12 08:58
Excellent, thank you. Bug introduced in develop and fixed in develop by https://github.com/syl20bnr/spacemacs/commit/4f70a9abcc091294a34064416d1269eca3b855fd, so closing the issue.

**Closed by bmag** 2018-07-12 08:58 UTC
Labels: - Bug tracker -, Evil, Found work-around, Lazy loading

**Comment by dubnde** [comment] 2018-07-12 09:20
@bmag Great! Synced to tip and works. Thanks as it was doing my head in.
