### ISSUE TITLE
Spacemacs bottom hint become all the same name

### ISSUE THREAD

**Issue by xarthurx** [syl20bnr/spacemacs#7892] opened 2016-12-01 20:12 UTC
Start to happen around 1 week ago, not sure which package update affect this.
The problem is for many commands at bottom, the name become identical.

For instance, the pic below is what is shown when I pressed **SPC(M-m) g**.
The **s** should show magit originally.

![image](https://cloud.githubusercontent.com/assets/1921878/20810569/357a3b92-b7d8-11e6-93a1-470bbdb7ba50.png)

**Comment by nixmaniack** [comment] 2016-12-03 20:02
Duplicate of https://github.com/syl20bnr/spacemacs/issues/7887. It's fixed upstream. Please update packages - specially `which-key`.

**Closed** 2016-12-03 20:03 UTC
