### ISSUE TITLE
haskell-structured-mode

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#1136] opened 2015-04-13 18:37 UTC
Few odd issues with 0.101.1 such as delete in VIM mode i.e. dd gives 

Symbol’s function definition is void : haskell-indentation-disable-show-indentations

**Comment by ublubu** [comment] 2015-04-13 23:14
probably related:

`error in post-command-hook (evil-mode-check-buffers): (void-function haskell-indentation-disable-show-indentations)`

when I try to `:` or open the REPL with `SPC m s s`

**Comment by syl20bnr** [comment] 2015-04-14 01:58
What is the version of your haskell-mode package ? (name of the directory in `elpa` directory).
Does it still occur if you update your packages with the `[Update]` button on the startup page ?

**Comment by chrisbarrett** [comment] 2015-04-14 09:46
I believe the errors relating to `haskell-indentation` are a regression caused by switching from `hi2` to `haskell-indentation`. There are references to members of `haskell-indentation` in `haskell-mode-hook`, which can happen before that feature is loaded.

This can be resolved by autoloading those functions.

**Comment by fatlazycat** [comment] 2015-04-14 11:55
haskell-mode-20150412.1138, I upgraded all the packages after getting the new version and it still happened.

**Comment by codygman** [comment] 2015-04-14 21:40
@chrisbarrett Is there a hotfix you could recommend to autoload stuff?

**Comment by chrisbarrett** [comment] 2015-04-14 21:49
```diff --git a/contrib/lang/haskell/packages.el b/contrib/lang/haskell/packages.el
index 8b079e0..aa42669 100644
--- a/contrib/lang/haskell/packages.el
+++ b/contrib/lang/haskell/packages.el
@@ -93,23 +93,26 @@
             haskell-stylish-on-save nil)
 
       ;; Show indentation guides in insert or emacs state only.
-      (defun spacemacs//haskell-identation-show-guides ()
-        "Show the indent guides."
-        (when (eq 'haskell-mode major-mode)
-          (funcall 'haskell-indentation-enable-show-indentations)))
-      (defun spacemacs//haskell-identation-hide-guides ()
-        "Hide the indent guides."
-        (when (eq 'haskell-mode major-mode)
-          (funcall 'haskell-indentation-disable-show-indentations)))
-      ;; first entry in normal state
-      (add-hook 'evil-normal-state-entry-hook
-                'spacemacs//haskell-identation-hide-guides)
-      (dolist (state '(insert emacs))
-        (eval `(progn
-                 (add-hook ',(intern (format "evil-%S-state-entry-hook" state))
-                           'spacemacs//haskell-identation-show-guides)
-                 (add-hook ',(intern (format "evil-%S-state-exit-hook" state))
-                           'spacemacs//haskell-identation-hide-guides))))
+      (with-eval-after-load 'haskell-indentation
+        (defun spacemacs//haskell-identation-show-guides ()
+          "Show the indent guides."
+          (when (eq 'haskell-mode major-mode)
+            (funcall 'haskell-indentation-enable-show-indentations)))
+        (defun spacemacs//haskell-identation-hide-guides ()
+          "Hide the indent guides."
+          (when (eq 'haskell-mode major-mode)
+            (funcall 'haskell-indentation-disable-show-indentations)))
+
+        ;; first entry in normal state
+        (add-hook 'evil-normal-state-entry-hook
+                  'spacemacs//haskell-identation-hide-guides)
+
+        (dolist (state '(insert emacs))
+          (eval `(progn
+                   (add-hook ',(intern (format "evil-%S-state-entry-hook" state))
+                             'spacemacs//haskell-identation-show-guides)
+                   (add-hook ',(intern (format "evil-%S-state-exit-hook" state))
+                             'spacemacs//haskell-identation-hide-guides)))))
```

**Comment by chrisbarrett** [comment] 2015-04-14 21:52
The following should work.  
```elisp
(autoload 'haskell-indentation-enable-show-indentations 'haskell-indentation)
(autoload 'haskell-indentation-disable-show-indentations 'haskell-indentation)
```

**Comment by codygman** [comment] 2015-04-14 22:04
@chrisbarrett I tried putting it in my dotspacemacs/init and it seemed to mess most stuff up. I also tried putting it in .emacs.d/contrib/lang/haskell/config.el and that messed up spacemacs in interesting ways.

Where should I be putting it? Sorry, new to elisp/spacemacs stuff.

**Comment by chrisbarrett** [comment] 2015-04-15 01:30
@codygman oops, made a mistake with the types. Updated the above snippet.

Inside dotspacemacs/init should be fine.

**Comment by mlacorte** [comment] 2015-04-15 18:29
I'm having all sorts of issues, and I don't know what's related to what, so I'm just going to dump my findings here.

* Ubuntu 14.04
* Emacs 24.3.1
* Spacemacs 0.101.2

When doing pretty much anything in a Haskell file, I'm getting the `Error in post-command-hook (evil-mode-check-buffers): (void-function haskell-indentation-disable-show-indentations)` error.

If I ignore the error and try editing anyway, I get a `You tried to do an indentation command, but an indentation mode has not been enabled yet.` error.

When trying @chrisbarrett's workaround, both errors went away, but the auto-indentation became really wonky.

These issues seem to be interrelated, but I don't know which are the causes and which are the effects. I'm not very familiar with Emacs or Spacemacs, so I can't help out a ton, but I can test things if you need me to.

**Comment by fatlazycat** [comment] 2015-04-15 18:32
I switched back to the other indentation mode and can work with Haskell. 

Will switch back to structured mode when fixed.

**Comment by codygman** [comment] 2015-04-16 01:32
@fatlazycat How did you switch back to the other indentation mode for those of us new to spacemacs?

**Comment by fatlazycat** [comment] 2015-04-16 04:23
Just look at the layer documentation.

**Comment by cies** [comment] 2015-04-16 14:07
@chrisbarrett Your workaround worked for me. Thanks.

**Comment by codygman** [comment] 2015-04-25 06:38
@cies Hm, should this be closed? I mean those of us that applied hotfixes don't have this problem anymore but seeing as no commits were made to fix the issue, what about other/future users?

**Comment by fatlazycat** [comment] 2015-04-25 06:40
Can't it be fixed centrally somehow ? Otherwise new people coming along will have to find this issue ?

**Comment by cies** [comment] 2015-04-25 14:10
@codygman @fatlazycat 
I think obvious issues that need non-obvious workarounds are still issues; I hope we can actually fix it.

Maybe someone with more ELips skill could judge if the workaround code can become part of the layer?

**Comment by chrisbarrett** [comment] 2015-04-25 20:21
I made a PR about Haskell-related issues last week. Can someone please revert their hotfix and post whether this is still a problem.

**Comment by syl20bnr** [comment] 2015-04-25 21:27
The PR should be in develop, I'm also very interested to know if this fixes the issue in order to cherry-pick in maintenance branch and master.

**Comment by fatlazycat** [comment] 2015-04-26 06:15
no still happening for me, just tried off develop.

**Comment by chrisbarrett** [comment] 2015-04-26 08:25
If you are experiencing an issue with the Haskell layer, please clearly describe the symptoms and reproduction steps (possibly in separate GitHub issues where there are clear differences) so we can track the work we need to do.

**Comment by fatlazycat** [comment] 2015-04-26 08:27
Sure but it's still the same as the very first comment. 

Will try and put in more detail when I get back in.

**Comment by x-ji** [comment] 2015-04-26 12:57
Also the `develop` branch seems to be not working for me... Had to put

```elisp
(autoload 'haskell-indentation-enable-show-indentations "haskell-indentation")
(autoload 'haskell-indentation-disable-show-indentations "haskell-indentation")
```

to make `dd` etc. work

**Comment by chrisbarrett** [comment] 2015-04-26 22:57
@x-ji Can you please describe reproduction steps for that error? Specifics, people! ;P

**Comment by fatlazycat** [comment] 2015-04-27 05:51
Have (haskell :variables haskell-enable-shm-support t) as your layer to enable haskell.

Opening a new haskell file x.hs via helm-find-files gives File Mode Specification Error : (void function haskell-indentation-disable-show-indentations)

**Comment by nkpart** [comment] 2015-05-04 11:28
I have the same issues, same reproduction steps as @fatlazycat, and same error messages for the workaround as posted by @x-ji.

I'm running emacs 24.4.1, OS X. I've only just started using spacemacs, my conf file is bog standard other than turning on haskell and trying the workaround. My emacs packages are up to date as of right now.

**Comment by chrisbarrett** [comment] 2015-05-04 21:29
The above PR resolves the main issue. The warnings about an indentation-mode not being configured are kind of trickier.

The issue there is that evil commands for opening lines trigger a major-mode's indentation commands. Haskell-mode provides a couple of indentation modes right now, so the default indentation command is configured to display an annoying message.

SHM isn't designed to be compatible with evil-mode, so I just use haskell-indentation for that reason.

**Comment by nkpart** [comment] 2015-05-04 22:01
I have been using evil mode and SHM together for a while outside of
spacemacs, they work together fine.

When using SHM you need to turn off any Haskell indentation modes, as it
has its own, although I'm not sure how that all fits together.

**Comment by chrisbarrett** [comment] 2015-05-04 22:05
That's where the problem lies: all sorts of normal evil editing commands will trigger the nagging message about needing to select an indentation mode. It's pretty gross.

**Closed** 2015-05-21 03:48 UTC
Labels: Fixed in `develop`, Haskell

**Comment by yogsototh** [comment] 2015-07-10 11:32
I'm still experiencing the same issue.

- Mac OS X 10.10.3
- GNU Emacs 24.4.1 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit 1344.72 of 2015-02-11)

both with

- Spacemacs 104.x (git commit 26c4e2a)
and 
- Spacemacs 103.2 (git 93e3b88)

**Comment by x-ji** [comment] 2015-07-10 11:38
@yogsototh Not sure if that would work, but Maybe try to update packages? The `haskell` packages themselves are also updated IIRC.

**Comment by yogsototh** [comment] 2015-07-19 09:57
I had to disable `haskell` in my layers and enable it again. And it seems to work perfectly.

As a side note, I now use `stack` by following this conversation: 

https://github.com/syl20bnr/spacemacs/issues/2142

To resume:

I had to manually add:

    (add-to-list 'exec-path "~/.local/bin")

in my `dotspacemacs/init`

And to install the required packages:

    stack install stylish-haskell hlint ghc-mod hasktags

**Comment by stites** [comment] 2015-11-12 07:16
This came up for me and I worked through a number of combinations of the above to no avail. I came across @boj's .spacemacs file ([found here](https://gist.github.com/boj/662e334a0beecc8f09df)) and it turned out that all I had to do was add:

    (add-hook 'haskell-mode-hook 'turn-on-haskell-indent)

to user initialization. Thanks @boj!

**Comment by d12frosted** [comment] 2015-11-12 09:19
@stites looks like you haven't updated your packages for a long time, `haskell-mode` now uses `haskell-indentation` as default. Also, `turn-on-*` are deprecated. Also, you probably want to use `haskell-indentation` instead of `haskell-indent`.

**Comment by stites** [comment] 2015-11-12 19:36
Good to know — yeah, I'm on 104.2 and it looks like 104.4 is available. Thanks for the heads up, @d12frosted

**Comment by d12frosted** [comment] 2015-11-12 19:37
@stites yeah, but make sure to also update **packages**, not only spacemacs
