### ISSUE TITLE
Spacemacs is frozen and does not respond when searching a keyword inside a link in Orgmode

### ISSUE THREAD

**Issue by mssun** [syl20bnr/spacemacs#4765] opened 2016-01-23 13:32 UTC
#### Description
When searching a keyword (using Vim keybinding `/` to search) inside a link in Orgmode, Spacemacs will be frozen. 

#### Reproduction guide
- Start Emacs
- create an org file (test.org)
- type `[[http://www.google.com][a link]]` and save
- type `/google` to search `google`
- Spacemacs is frozen when typing `/go`, and use `C-g` to cancel the search

DESCRIPTION OF THE OBSERVED BEHAVIOUR

Spacemacs is frozen.

DESCRIPTION OF THE EXPECTED BEHAVIOUR

Search `g` character and highlight it.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 574dffb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 chinese chrome colors deft
 (elfeed :variables rmh-elfeed-org-files
         (list "~/Dropbox/org/elfeed.org"))
 emacs-lisp
 (geolocation :variables geolocation-enable-weather-forecast t)
 git github gtags html
 (latex :variables latex-build-command "LaTeX")
 markdown org osx python search-engine semantic shell spacemacs-layouts spell-checking syntax-checking swift version-control)
```

#### Backtrace
N/A

**Comment by kccai** [comment] 2016-01-23 13:46
I have this problem too. It seems that emacs gets frozen when I use the command `evil-search-forward` (`/`) to search the invisible text in the `org` mode. Moreover, the `isearch-forward` (`C-s`) does not search the invisible text ...

**Comment by StreakyCobra** [comment] 2016-01-23 14:36
I think it's a duplicate of #3623. I'm closing as a duplicate, if it is not the case let me know, I can reopen it :relaxed:

**Closed by StreakyCobra** 2016-01-23 14:36 UTC
