### ISSUE TITLE
Pasting in evil mode doesn't work (in develop)

### ISSUE THREAD

**Issue by krotton** [syl20bnr/spacemacs#6251] opened 2016-06-07 10:06 UTC
#### Description :octocat:
Pasting in evil mode (using `p` or `P`) doesn't work, failing with: `command-execute: Wrong type argument: commandp, spacemacs/paste-transient-state/evil-paste-after`. If I run `:evil-paste-after`, it works.

Workaround: using `⌘   v`

#### Reproduction guide :beetle:
- Start Emacs
- Open any buffer and insert a line of text
- Yank (`yy`) or delete (`dd`) the line of text
- Try pasting it using `p` or `P`

*Observed behaviour:* :eyes:
No pasted text and a message in the bottom bar saying: `command-execute: Wrong type argument: commandp, spacemacs/paste-transient-state/evil-paste-after`.

*Expected behaviour:* :broken_heart:
The copied/deleted line pasted below or above the current one.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. ea77a5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers (note - the problem occurs even if all are disabled):
```elisp
(csv markdown emacs-lisp osx git org
     (scala :variables scala-auto-insert-asterisk-in-comments t)
     syntax-checking graphviz plantuml ktt-groovy)
```

#### Backtrace :paw_prints:
```
command-execute: Wrong type argument: commandp, spacemacs/paste-transient-state/evil-paste-after
command-execute: Wrong type argument: commandp, spacemacs/paste-transient-state/evil-paste-before
```

**Comment by CharlesHD** [comment] 2016-06-07 15:32
I'm behind the same commit, on gnu/linux . Cannot reproduce (aka it works normally for me), I have not the same layers.
Maybe you could try with a fresh install of spacemacs ?

**Comment by krotton** [comment] 2016-06-08 08:21
I'll try and report back.

**Comment by krotton** [comment] 2016-06-11 10:57
Indeed, reinstallation has fixed it. I don't understand why, but I think that closes the issue ;).

**Comment by alexanderkjeldaas** [comment] 2016-06-19 06:09
I have the same issue.  Switched from master to devel.

**Comment by d12frosted** [comment] 2016-06-19 07:07
@alexanderkjeldaas develop is stable enough to use on a daily basis 😸

**Comment by toupeira** [comment] 2016-07-07 19:53
Please reopen, I keep running into this every now and then, I think it started about 2 weeks ago. With latest develop I can reproduce it as follows:

- kill all running Emacs instances
- start Emacs with `emacs --daemon`
- open a frame with `emacsclient --create-frame`
- pressing `p`/`P` should now trigger the reported error message

If I start up Emacs without `--daemon` everything seems to work fine, though I'm pretty sure I've encountered this issue on my laptop as well where I don't use `--daemon` (but still use `dotspacemacs-persistent-server t` and `emacsclient`). I use `--daemon` on my desktop because I want to have Emacs loaded on startup but not visible, let me know if there's a "Spacemacs way" of doing that.

Digging around the code it seems the `spacemacs-post-user-config-hook` isn't executed when using `--daemon`, `spacemacs-post-user-config-hook-run` is indeed `nil` and `(run-hooks 'spacemacs-post-user-config-hook)` makes pasting work again. I'm not sure how all the startup logic works (in either Emacs or Spacemacs), but hope this helps in tracking down the source of this bug!

**Comment by d12frosted** [comment] 2016-07-08 05:37
@toupeira could you please enable debug on error (`SPC t D`) and then share stack trace when described error happens?

**Comment by toupeira** [comment] 2016-07-08 07:31
Whoops I just realized I actually get a different error: `Symbol's function definition is void: spacemacs/paste-transient-state/evil-paste-after`. Sorry about the confusion!

And because it's an undefined function I guess the stack trace won't be very useful ;-)

```
Debugger entered--Lisp error: (void-function spacemacs/paste-transient-state/evil-paste-after)
  indirect-function(spacemacs/paste-transient-state/evil-paste-after)
  command-execute(spacemacs/paste-transient-state/evil-paste-after)
```

Can you reproduce this behaviour with `emacs --daemon`?

**Comment by toupeira** [comment] 2016-07-18 16:58
I think the original issue can be closed again as it's a different error from mine, which looks like a possible duplicate for #1894 or #6197. There seem to be some general issues when starting Spacemacs with `--daemon`.

**Comment by TheBB** [comment] 2016-07-18 18:57
Okay, I'm always up for closing issues. :-)

**Closed by TheBB** 2016-07-18 18:57 UTC
Labels: - Bug tracker -, Evil, To be reproduced

**Comment by jgmize** [comment] 2016-11-22 16:29
I was running into the exact same error described in https://github.com/syl20bnr/spacemacs/issues/6251#issuecomment-231294281 in both the latest develop branch and in release, and worked around the issue by [setting](https://github.com/jgmize/dotfiles/commit/88b46b824f5003b5be5b9412e0732205c1bc6151) `dotspacemacs-enable-paste-transient-state nil`-- this is disabled by default, so I'm not sure why this was necessary. Not worth re-opening this issue as it still looks like a weird edge case, just commenting here in case someone else runs into the same issue.

**Comment by toupeira** [comment] 2016-11-24 22:10
@jgmize turns out it wasn't actually disabled by default, see the attached PR :)

**Comment by jgmize** [comment] 2016-11-26 17:31
thanks @toupeira!
