### ISSUE TITLE
Update Packages Error, Wrong number of arguments configuration-layer//filter-packages-with-deps

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#9420] opened 2017-08-13 02:31 UTC
#### Description :octocat:
let*: Wrong number of arguments: (lambda (pkg-names) "Return a filtered list of PKG-NAMES to update." (configuration-layer//filter-packages-with-deps pkg-names (quote configuration-layer//new-version-available-p) (quote use-archive))), 2

#### Reproduction guide :beetle:
- Start Emacs
- Clike [Update Packages] in *spacemacs* buffer

*Observed behaviour:* :eyes: :broken_heart:
Error show in minibuffer

*Expected behaviour:* :heart: :smile:
NO Errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 052636d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 asm
 (python :variables python-sort-imports-on-save t)
 semantic
 (go :variables go-tab-width 4 go-use-gometalinter t)
 ranger gtags ibuffer sql
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 graphviz plantuml docker
 (syntax-checking :variables syntax-checking-enable-by-default t)
 liter ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
(Spacemacs) --> refreshing package archive: melpa... [1/3]
Contacting host: melpa.org:443
Importing package-keyring.gpg...done
Contacting host: melpa.org:443 [2 times]
Package refresh done
(Spacemacs) --> refreshing package archive: org... [2/3]
Contacting host: orgmode.org:80
Importing package-keyring.gpg...done
Contacting host: orgmode.org:80
Package refresh done
(Spacemacs) --> refreshing package archive: gnu... [3/3]
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443 [2 times]
Package refresh done
let*: Wrong number of arguments: (lambda (pkg-names) "Return a filtered list of PKG-NAMES to update." (configuration-layer//filter-packages-with-deps pkg-names (quote configuration-layer//new-version-available-p) (quote use-archive))), 2
```

**Comment by bmag** [comment] 2017-08-13 10:12
You did not provide a backtrace (those are just messages). Run `SPC t D` (`spacemacs/toggle-debug-on-error`) before clicking the udpate button, so when the error happens a backtrace will be shown in the *Backtrace* buffer.

**Comment by lsytj0413** [comment] 2017-08-13 10:59
sorry, the *Backtrace* is:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (lambda (pkg-names) "Return a filtered list of PKG-NAMES to update." (configuration-layer//filter-packages-with-deps pkg-names (quote configuration-layer//new-version-available-p) (quote use-archive))) 2)
  configuration-layer//get-packages-to-update((ac-ispell ace-jump-helm-line ace-link ace-window adaptive-wrap aggressive-indent anaconda-mode asm-mode async auto-compile auto-complete auto-highlight-symbol auto-yasnippet avy bind-key bind-map cc-mode clang-format clean-aindent-mode cmake-mode color-identifiers-mode column-enforce-mode company company-anaconda company-c-headers company-go company-statistics company-ycmd cython-mode define-word desktop diminish disaster docker docker-tramp dockerfile-mode dumb-jump editorconfig elisp-slime-nav esh-help eshell-prompt-extras eshell-z eval-sexp-fu evil evil-anzu evil-args evil-ediff evil-escape evil-exchange evil-iedit-state ...) t)
  (let* ((distant-packages (configuration-layer//filter-distant-packages configuration-layer--used-packages t)) (update-packages (configuration-layer//get-packages-to-update distant-packages t)) (skipped-count (length configuration-layer--check-new-version-error-packages)) (date (format-time-string "%y-%m-%d_%H.%M.%S")) (rollback-dir (expand-file-name (concat configuration-layer-rollback-directory (file-name-as-directory date)))) (upgrade-count (length update-packages)) (upgraded-count 0) (update-packages-alist)) (if configuration-layer--check-new-version-error-packages (progn (spacemacs-buffer/append (format (concat "--> Warning: cannot update %s package(s), possibly due" " to a temporary network problem: %s\n") skipped-count (mapconcat (function symbol-name) configuration-layer--check-new-version-error-packages " "))))) (if (> upgrade-count 0) (progn (spacemacs-buffer/append (format (concat "--> Found %s package(s) to update" (if (> skipped-count 0) (format " (skipped %s):\n" skipped-count) ":\n")) upgrade-count) t) (mapc (function (lambda (x) (spacemacs-buffer/append (format ... x) t))) (sort (mapcar (quote symbol-name) update-packages) (quote string<))) (if (and (not no-confirmation) (not (yes-or-no-p (format "Do you want to update %s package(s) ? " upgrade-count)))) (spacemacs-buffer/append "Packages update has been cancelled.\n" t) (spacemacs-buffer/append "--> performing backup of package(s) to update...\n" t) (spacemacs//redisplay) (let ((--dolist-tail-- update-packages) pkg) (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (if (memq pkg dotspacemacs-frozen-packages) nil (let* ... ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs/dump-vars-to-file (quote (update-packages-alist)) (expand-file-name (concat rollback-dir configuration-layer-rollback-info))) (let ((--dolist-tail-- update-packages) pkg) (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (if (memq pkg dotspacemacs-frozen-packages) nil (setq upgraded-count ...) (spacemacs-buffer/replace-last-line ... t) (spacemacs//redisplay) (configuration-layer//package-delete pkg)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append (format "\n--> %s package(s) to be updated.\n" upgraded-count)) (spacemacs-buffer/append (format (concat "\nEmacs has to be restarted to actually install the " "new version of the packages%s.\n") (if (member "restart-emacs" update-packages) "" " (SPC q r)"))) (configuration-layer//cleanup-rollback-directory) (spacemacs//redisplay)))) (if (eq upgrade-count 0) (progn (spacemacs-buffer/append "--> All packages are up to date.\n") (spacemacs//redisplay))))
  configuration-layer/update-packages()
  (lambda (&rest ignore) (configuration-layer/update-packages))((push-button :args nil :value #("Update Packages" 0 15 (face font-lock-keyword-face)) :help-echo "Update all ELPA packages to the latest versions." :action (lambda (&rest ignore) (configuration-layer/update-packages)) :mouse-face highlight :follow-link "
" :button-overlay #<overlay from 349 to 366 in *spacemacs*> :from #<marker (moves after insertion) at 349 in *spacemacs*> :to #<marker at 366 in *spacemacs*>) nil)
  widget-apply((push-button :args nil :value #("Update Packages" 0 15 (face font-lock-keyword-face)) :help-echo "Update all ELPA packages to the latest versions." :action (lambda (&rest ignore) (configuration-layer/update-packages)) :mouse-face highlight :follow-link "
" :button-overlay #<overlay from 349 to 366 in *spacemacs*> :from #<marker (moves after insertion) at 349 in *spacemacs*> :to #<marker at 366 in *spacemacs*>) :action nil)
  widget-apply-action((push-button :args nil :value #("Update Packages" 0 15 (face font-lock-keyword-face)) :help-echo "Update all ELPA packages to the latest versions." :action (lambda (&rest ignore) (configuration-layer/update-packages)) :mouse-face highlight :follow-link "
" :button-overlay #<overlay from 349 to 366 in *spacemacs*> :from #<marker (moves after insertion) at 349 in *spacemacs*> :to #<marker at 366 in *spacemacs*>) nil)
  widget-button-press(353)
  funcall-interactively(widget-button-press 353)
  call-interactively(widget-button-press nil nil)
  command-execute(widget-button-press)

```

**Comment by bmag** [comment] 2017-08-13 11:29
Hmm, [here](https://github.com/syl20bnr/spacemacs/blob/052636d237fd8b653d24076d366c261fbe532e28/core/core-configuration-layer.el#L1810) `configuration-layer//get-packages-to-update` is called with 2 arguments, but it's supposed to receive only 1 argument. This is because of https://github.com/syl20bnr/spacemacs/commit/6afa7538481040e52e96abb40f24e0e776f1121d, so you can move back to an earlier commit until this is resolved. I wasn't able to reproduce the bug myself, so not everyone is affected, but it's there.

@syl20bnr can you look at it?

**Comment by syl20bnr** [comment] 2017-08-13 17:29
Thank you for the report, it is now fixed.

**Closed by syl20bnr** 2017-08-13 17:29 UTC
Labels: - Bug tracker -, Regression :-(, Update
