### ISSUE TITLE
Error with neotree and spacemacs-modeline regarding all-the-icons

### ISSUE THREAD

**Issue by mc10** [syl20bnr/spacemacs#10875] opened 2018-06-13 22:55 UTC
#### Description :octocat:
Error with neotree and spacemacs-modeline regarding all-the-icons

#### Reproduction guide :beetle:
- Start Emacs
- Enable neotree layer and all-the-icons additional package.
- Set dotspacemacs-mode-line-theme to 'all-the-icons.

*Observed behaviour:* :eyes: :broken_heart:
An error occurred while post-configuring neotree in layer spacemacs-modeline (error: (void-function spaceline-all-the-icons--setup-neotree))

*Expected behaviour:* :heart: :smile:
No errors appear.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8754b2450)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((helm :variables helm-enable-auto-resize nil helm-no-header nil helm-position 'bottom helm-use-fuzzy 'always)
 auto-completion better-defaults emacs-lisp git markdown neotree
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control colors osx ivy
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 html javascript yaml ocaml python)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by syl20bnr** [comment] 2018-06-14 14:11
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/10872

**Closed by syl20bnr** 2018-06-14 14:11 UTC
Labels: - Bug tracker -, Duplicate ☝, File browser, Mode Line
