### ISSUE TITLE
Cant switch to last buffer (SPC tab) to spacemacs home buffer

### ISSUE THREAD

**Issue by hicksy994** [syl20bnr/spacemacs#7104] opened 2016-09-13 18:55 UTC
I just switched to the develop branch and found this is a thing. Is this intended?

**Comment by bmag** [comment] 2016-09-13 19:37
It's sort-of intended. You can configure `spacemacs-useful-buffers-regexp` to match the home buffer, so `SPC TAB` doesn't skip it. Or you can use `SPC b h`.

Is there a specific use-case that requires this behavior? I can only think about opening a bunch of recent files from the list on the home buffer.

**Comment by hicksy994** [comment] 2016-09-13 20:33
@bmag Thanks,

I dont really have a specific use case, I just dont like the inconsistency. When I hit switch to last buffer I want it to switch to the last buffer.

**Comment by deb0ch** [comment] 2016-09-14 15:16
Agree, it is a bit disturbing as semantically you would expect it to actually return to the last buffer.

**Comment by bmag** [comment] 2016-09-14 15:31
The motivation for not showing uninteresting buffers comes from #6159. We can probably change the default values for the aforementioned variables.

**Comment by deb0ch** [comment] 2016-09-14 15:36
I guess that in some cases like this one you would not expect uselessness to be taken into account.

**Comment by d12frosted** [comment] 2016-10-03 08:23
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by deb0ch** [comment] 2016-10-03 16:47
Nothing changed regarding this issue, is it considered "not a bug" or is closing it a mistake and it should be fixed ?

It still feels weird to have your previous buffer not coming back when you press the `previous-buffer` command.

**Comment by d12frosted** [comment] 2016-10-03 17:03
Ahem. Looks like I closed this one by accident. Sorry about that. And thanks for noticing it, @deb0ch !

**Comment by syl20bnr** [comment] 2017-01-13 04:31
I'm with @deb0ch on this one, I have in my notes to provide saner defaults for useful buffers. I think we should by default consider almost everything useful except for the obvious unuseful ones.

**Comment by bmag** [comment] 2017-01-13 18:55
@syl20bnr I agree. I also think `SPC TAB` shouldn't care about the useful/useless distinction. (more accurately, it shouldn't filter the buffers from `window-prev-buffers`)

**Comment by syl20bnr** [comment] 2017-02-07 03:08
Honestly the current behavior annoys me everyday but somehow I  always defer the fix. ^_^

Another example is with magit buffers, I have to `SPC b b RET` to switch back to the magit status as `SPC Tab` skips it.

> I also think SPC TAB shouldn't care about the useful/useless distinction.

💯

**Comment by erik-stephens** [comment] 2017-03-01 13:31
+1 for adding magit buffers to the default list of useful ones.  The workaround is elegant enough, but it took me a while to find the recipe.  Chiming in here in case others overlooked [this FAQ](https://spacemacs.org/doc/FAQ.html#change-special-buffer-rules) like I did:

    (push "\\*magit" spacemacs-useful-buffers-regexp)

**Comment by braham-snyder** [comment] 2017-03-18 20:31
Note that--even when designated as "useful" as above--magit buffers won't be added to non-default layouts automatically (i.e., when they are opened from within a non-default layout), which means that `previous-buffer` and `next-buffer` will skip them<sup>1</sup> in those layouts. Adding special buffers to layouts is further discussed in these issues: https://github.com/syl20bnr/spacemacs/issues/5776 and https://github.com/syl20bnr/spacemacs/issues/4956

<sup>1</sup> While true as of writing, https://github.com/syl20bnr/spacemacs/pull/8530 might be merged into develop within a week, which would make `previous-buffer` and `next-buffer` switch to buffers in any layout. At the least, however, the above will apply to the master branch for a while.

Additionally, here's a link to a more general issue regarding useful/useless buffers and better defaults: [(#6683) What's the deal with "useful" and "useless" buffers?](https://github.com/syl20bnr/spacemacs/issues/6683)

**Comment by deb0ch** [comment] 2017-03-18 21:34
@braham-snyder Note that #8530 is only about alternating buffers with `SPC tab`, it will do nothing in regard to `previous-buffer` and `next-buffer`.

**Comment by zzhjerry** [comment] 2017-03-20 08:51
I also found out that `alternate-buffer` doesn't work with buffer switch off from buffer opened by `counsel-projectile-find-file`. Simply speaking, when I open a buffer with `counsel-projectile-find-file`, I can switch back to the previous buffer successfully but I could not switch back. It feels like the buffer opened by projectile never got remembered.

**Comment by colorwin** [comment] 2017-07-24 07:54
@zzhjerry Same here, are you resolve it?

**Comment by colorwin** [comment] 2017-07-24 10:00
@zzhjerry Hei, I just add `(persp-add-buffer)` to the end of  `counsel-projectile-find-file` function, it seem work fine for me. Hope it help.

**Comment by Apakollaps** [comment] 2018-05-30 09:20
Any news on this one? One of few annoying things in spacemacs. I've just set `spacemacs-useless-buffers-regexp` to nil, but I guess that will have some unwanted effects...

**Closed** 2019-01-20 15:42 UTC
Labels: - Forum -, Core, Fixed in develop, Sane defaults
