### ISSUE TITLE
"SPC i K" does not repeat with "."

### ISSUE THREAD

**Issue by dooblad** [syl20bnr/spacemacs#6573] opened 2016-07-13 22:54 UTC
#### Description
After performing `SPC i K` (insert-line-above-no-indent), pressing `.` doesn't insert a line above. Instead, it repeats the last command *before* `SPC i K`

#### Reproduction guide
- Start Emacs
- Open a scratch buffer (or any buffer)
-Type a few lines of text
-Delete a line with `dd` to create a previous command
-Press `SPC i K`
-Press `.`

*Observed behaviour:*
The current line is deleted.

*Expected behaviour:*
A line is inserted above the current line.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp html git themes-megapack syntax-checking)
```

**Comment by vlthr** [comment] 2016-07-15 17:07
I've had the same issue and ended up having a look at the causes today. It seems like whatever the underlying issue is, it is happening during the call to `evil-previous-line` in `spacemacs/insert-line-above-no-ident`. Replacing this call with a call to `previous-line` resulted in normal repeatability for me.

Anyone with more experience that knows why this could be a problem?

**Comment by kdelwat** [comment] 2016-10-23 05:29
This seems to be fixed now on master. @dooblad Is it still broken for you?

**Comment by dooblad** [comment] 2016-10-23 19:36
@kdelwat It seems to be working now!

**Closed** 2016-10-24 18:40 UTC
Labels: - Bug tracker -
