### ISSUE TITLE
emacsclient -nw reuses window layout from another frame

### ISSUE THREAD

**Issue by agriffis** [syl20bnr/spacemacs#4120] opened 2015-12-09 13:10 UTC
This is a problem I'm seeing on develop which I wasn't seeing on master.

Consider two terminals. The first is running `emacsclient -nw` with three files:

![screenshot from 2015-12-09 07-50-44](https://cloud.githubusercontent.com/assets/50637/11686061/e5a5ad00-9e4b-11e5-9e76-3a82ec3e14e6.png)

In the second terminal, we run `emacsclient -nw file4.txt`. We expect this should show *only* the requested file, but instead it shows the same layout as the first frame, substituting the most recently used file with the new one. This is easiest to see in a screencast:

![out](https://cloud.githubusercontent.com/assets/50637/11686090/1ceccdac-9e4c-11e5-844a-0f6420d7d0a7.gif)

This is pretty much driving me nuts!

**Comment by StreakyCobra** [comment] 2015-12-09 18:50
It is due to `spacemacs-layout`. This also happen on GUI mode with emacsclient. In short layouts are used to keep and restore windows positions and buffers. There is a default layout, let's call it `Home`, that contains all buffers and remember the windows positions. When you open one frame with `emacsclient`, the default layout is selected and when you split the screen or open a buffer, the state is stored. When you open a second one with emacsclient, the same layout is **restored** with its positions and buffers, and then it probably replace the first buffer with the file passed as argument.

So I would say it's "as expected", but there is probably some enhancement to do here. @CestDiego @syl20bnr Any idea how to deal with emacsclient and layouts?

**Comment by agriffis** [comment] 2015-12-09 20:27
@StreakyCobra But the problem is that the first emacsclient is still open. There are two things I think we know in this case: (1) If the first emacsclient is still open, we probably don't want to reuse a layout that's still in use. (2) If we explicitly mention file(s) on the command-line, we probably don't want to reuse a previous layout anyway.

(I'm suspicious that I don't want `spacemacs-layout` anyway, but that's a different story.)

**Comment by agriffis** [comment] 2015-12-09 20:52
By the way, I don't have `(setq-default dotspacemacs-configuration-layers '(spacemacs-layouts))` in my `.spacemacs` but it seems to be loading anyway.

**Comment by StreakyCobra** [comment] 2015-12-09 21:11
@agriffis `spacemacs-layout` is part of the `spacemacs` distribution layer, so it is there anyway. Yeah I got it that the problem is when there is a second client opened. As I said it's a normal consequence of `spacemacs-layout` functionalities, and it means it should be improved as it's clearly not the wanted behaviour when using `emacsclient` :-)

**Comment by agriffis** [comment] 2015-12-09 21:19
@StreakyCobra yeah I'm just catching up on what `spacemacs-layout` is and how it works, so my apologies for earlier confusing comments. Probably I don't want to kill it completely. :-)

**Comment by syl20bnr** [comment] 2015-12-10 00:40
Fix PR sent upstream: https://github.com/Bad-ptr/persp-mode.el/pull/25

**Comment by syl20bnr** [comment] 2015-12-11 08:10
I switched to a fork while the bug is being fixed upstream.

**Comment by agriffis** [comment] 2015-12-11 16:22
@syl20bnr Thank you! This is now working the way I'd anticipate, where new emacsclient instances start with a clean slate.

**Comment by TheBB** [comment] 2016-01-03 09:33
According to discussion in https://github.com/Bad-ptr/persp-mode.el/pull/25, the maintainer of persp-mode claims it should be fixed.

**Closed** 2016-01-04 08:34 UTC
Labels: High Priority, Reported upstream, Running as daemon, Spacemacs Layouts

**Comment by lislon** [comment] 2016-02-02 11:43
I have an error `*ERROR*: Symbol’s function definition is void: self` on starting `emacsclient -c` with Emacs 25.1.50.1
Reverting of da2a7b8 does fix this. Can we return to original upstream branch of persp-mode/?

**Comment by syl20bnr** [comment] 2016-04-13 02:10
I reverted to MELPA version since it fixes the crash :-)
