### ISSUE TITLE
evil-tabs, android and java support

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#923] opened 2015-03-23 23:01 UTC
Can you integrate evil-tabs on spacemacs?
How about java/android support. I think sbt can be used for that, but it would be the works of great emacs  hackers to integrate that.

**Comment by syl20bnr** [comment] 2015-03-24 01:28
I agree for all, this is where we can leverage the community.

**Comment by person808** [comment] 2015-03-24 02:56
>android

Have you seen [Android mode](https://github.com/remvee/android-mode)?

**Comment by Funnnny** [comment] 2015-03-24 03:29
evil-tabs is easy to add, but elscreen's theme looks really out of place, I don't know if there's any other solution?

Also evil-tabs seems to be using header bar, so it'll clash with stickyfunc-mode. 
And last, the SPC t is already reserved for toggle, we have to find another keybinding.

**Comment by tuhdo** [comment] 2015-03-24 08:51
Helm has a command `helm-elscreen` to switch between "tabs" and the "tabs" can be disabled. However,There are a few problems with `elscreen`:

- Currently I cannot install `elscreen`. Installing it from `list-package` resulted in a compile error.
- Elscreen seems to have a bug:

1. Suppose you opened two files: `file1` and `file2`, and two workspace: `ws1` and `ws2` (each workspace is created with `elscreen-create`).
2.  Switch buffer to `file1`. Then switch buffer to `file2`, then switch to a random buffer that you can press `q` to quite or just kill that buffer. Elscreen brings your back to buffer `file1` instead of `file2` - the previous buffer of recently killed buffer.

It seems `elscreen` records the first buffer it sees when you create a new workspace and whenever you quit or kill a buffer, it brings you back to that buffer. It's quite annoying.

**Comment by tuhdo** [comment] 2015-03-24 08:56
Or probably `elscreen` tries to make one main buffer attached per "tab" and this is a feature, not a bug. However, I'm not sure if Vim tabs behave this way.

**Comment by Funnnny** [comment] 2015-03-24 09:27
vim tabs always bring you back to the last active buffer.
Also buffer in vim is different than buffer in emacs, so close a buffer in a tab won't really close that buffer, while in emacs close a buffer will close it in all tabs.

If the solution is using helm-elscreen and disable tabs, I think we should just use perspectivesl layer.

**Comment by EDmitry** [comment] 2015-03-30 02:44
I use elscreen for maintaining different buffer layouts and it works great with spacemacs as far as I can tell. The compilation fails, but it still works running uncompiled scripts.

**Comment by nugend** [comment] 2015-04-30 18:09
Apparently one of the problems with elscreen is that it conflicts with powerline.

Another problem is that it's looking for package poe and not finding it. I have no idea what poe is, but if you search for emacs poe, the first hit indicates it is a "Portable Outfit for Emacsen" But Emacsen are emacs implemented in a non-elisp language? WTF?

**Comment by tuhdo** [comment] 2015-04-30 18:12
@nugend you may want to look at [this issue](https://github.com/syl20bnr/spacemacs/issues/1313). The problem is solved by adding the package `eyebrowse` which provides similar functionality like `i3` window manager. If you are curious, you could try on develop branch and add `eyebrowse` layer. After everything is setup properly, press `C-c W` to enter the microstate. and play with it

**Comment by nugend** [comment] 2015-04-30 18:20
@tuhdo Thanks, but one of the things that's really useful about tabs is not just that it lets you switch between files/buffers you care about but that it provides a visual reminder of what you have open at the moment. Like, it is important that there are actually tabs giving an indication of what is inside them.

**Comment by tuhdo** [comment] 2015-04-30 18:27
@nugend the `eyebrowse` package provides a workspace functionality, not just for displaying files/buffers and I heard that Vim people use tab to make it a workspace rather than displaying one buffer at a time like regular editors i.e. each Vim tab can have a window layout in it.

If you just want to see a list of buffer, why not just use `helm-mini`? Even if all the tabs are displayed and there are many of them, you still take time to scan the tabs anyway. And when you open like more than 10 buffers, you don't have enough screen width to display all anyway. And as you already said, `elscreen` has its fair share of bugs.

Currently when `eyebrowse` is activated, it displays the workspace number next to the window number. In the future, when `eyebrowse` add ability to tag the workspace, you will be able to see workspace name next to workspace number.

**Comment by nugend** [comment] 2015-04-30 18:44
It's because simply opening files organizes my workspace for me. I treat my vim sessions as ephemeral. I use tmux to manage workspaces. I don't have to think, "Okay, put *this* buffer in a workspace." I just pop a new tmux open and start using it as a workspace. The tabs let me implicitly think about the files in that workspace.

**Comment by wasamasa** [comment] 2015-06-08 09:11
@tuhdo Tags are implemented now, you can use `eyebrowse-format-slot` for getting the same representation as the modeline indicator and customize two settings to alter the way they're displayed.

**Comment by tuhdo** [comment] 2015-06-08 10:06
@wasamasa Thanks for informing. Good to hear that.

@syl20bnr you can include workspace name to `eyebrowse` now.

**Comment by TheBB** [comment] 2015-08-25 19:24
There is a java layer in develop, and an eyebrowse layer that works more or less like tabs, so I will close this. If there's anything more specific please feel free to report new (and separate) issues.

**Closed by TheBB** 2015-08-25 19:24 UTC
Labels: discussion, enhancement :-D, question
