### ISSUE TITLE
python jump-to-definition got an error "Can't open __builtin__ module"

### ISSUE THREAD

**Issue by binbincong** [syl20bnr/spacemacs#7435] opened 2016-10-17 06:25 UTC
I enabled python layer, and when trying to use jump-to-definition in a python file, I got a message "Can't open __builtin__ module". Not sure if there is something wrong with my configuration or something else.

**Comment by binbincong** [comment] 2016-10-17 07:51
Quick update, [SPC m g a] (anaconda-mode-find-assignments) can work, but [SPC m g g] (jump-to-definition) can not

**Comment by TheBB** [comment] 2016-10-17 08:10
Seems to work fine here, please provide an example file.

**Comment by binbincong** [comment] 2016-10-17 08:24
This is my .spacemacs file
![builtin_module](https://cloud.githubusercontent.com/assets/12336728/19430256/24e39d02-9486-11e6-9c23-eb3291b33a46.png)

And this is my python code where get this problem.
[spacemacs.zip](https://github.com/syl20bnr/spacemacs/files/532704/spacemacs.zip)

**Comment by TheBB** [comment] 2016-10-17 08:33
Yeah I can repro. But should probably report upstream, not sure what we can do about it?

**Comment by TheBB** [comment] 2016-10-17 08:34
Actually I believe anaconda-mode (or jedi) has been unable to deal with `@classmethod` for a long time. Can't remember where I read about this though.

**Comment by binbincong** [comment] 2016-10-17 08:45
Actually, as I just tried, after I remove @classmethod from functions, it still does not work. 
I am not so sure if I recall this correctly, this seemed to work days ago, and it can not work after I upgraded to 0.200.2 today (not sure if it is related).

**Comment by TheBB** [comment] 2016-10-17 08:51
Works fine for me if I remove `@classmethod` and call the first parameter `self` as in regular methods.

**Comment by binbincong** [comment] 2016-10-17 09:04
Sorry, I made a mistake, and yes, if I remove @classmethod, it works fine. But this will make python layer unusable if anaconde-mode does not support @classmethod, since @classmethod is really common for python dev

**Comment by binbincong** [comment] 2016-10-17 09:09
Checked anaconda-mode repo, and did not find issues that are related to classmethod, and no google result for anaconda-mode + classmethod. I am totally lost here.

**Comment by TheBB** [comment] 2016-10-17 09:18
> Checked anaconda-mode repo, and did not find issues that are related to classmethod

Make a new one.

**Comment by binbincong** [comment] 2016-10-17 09:38
@TheBB , thank you for the support and advise. Opened an issue in anaconda-mode repo.

**Comment by proofit404** [comment] 2016-10-17 11:55
Hello everyone. I explained this behavior in the anaconda-mode bug tracker. It is not a bug.

**Comment by d12frosted** [comment] 2016-10-17 11:59
Thanks for the heads up, @proofit404! 

Closing this issue since it's considered not bug in the upstream.

**Closed by d12frosted** 2016-10-17 11:59 UTC
Labels: - Bug tracker -, Python, Reported upstream
