### ISSUE TITLE
LSP is not working on sh-mode with language servers

### ISSUE THREAD

**Issue by breadncup** [syl20bnr/spacemacs#15688] opened 2022-08-07 18:01 UTC
#### Description :octocat:
LSP is not working on sh-mode with language servers

#### Reproduction guide :beetle:
- npm i -g bash-language-server (in a shell as stated in https://develop.spacemacs.org/layers/+tools/shell/README.html)
- Start Emacs
- Open a .zsh file

*Observed behaviour:* :eyes: :broken_heart:
```
LSP :: There are no language servers supporting current mode `sh-mode' registered with `lsp-mode'.
This issue might be caused by:
1. The language you are trying to use does not have built-in support in `lsp-mode'. You must install the required support manually. Examples of this are `lsp-java' or `lsp-metals'.
2. The language server that you expect to run is not configured to run for major mode `sh-mode'. You may check that by checking the `:major-modes' that are passed to `lsp-register-client'.
3. `lsp-mode' doesn't have any integration for the language behind `sh-mode'. Refer to https://emacs-lsp.github.io/lsp-mode/page/languages and https://langserver.org/ .
4. You are over `tramp'. In this case follow https://emacs-lsp.github.io/lsp-mode/page/remote/.
5. You have disabled the `lsp-mode' clients for that file. (Check `lsp-enabled-clients' and `lsp-disabled-clients').
You can customize `lsp-warn-no-matched-clients' to disable this message.
```

*Expected behaviour:* :heart: :smile:
No error or warning and works for the LSP for the sh-mode

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 9acd34111)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((spacemacs-bootstrap :packages
                      (not evil evil-evilified-state holy-mode hybrid-mode))
 (spacemacs-visual :packages ansi-colors)
 (spacemacs-editing :packages persistent-scratch smartparens)
 (spacemacs-modeline :packages
                     (not fancy-battery))
 (spacemacs-layouts)
 (spacemacs-completion)
 (spacemacs-project :variables projectile-indexing-method 'alien)
 (spacemacs-navigation)
 (spacemacs-purpose)
 (helm)
 (syntax-checking)
 (git :packages magit :variables git-magit-status-fullscreen t)
 (version-control :variables version-control-diff-tool 'git-gutter+)
 (lsp :variables lsp-lens-enable t)
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-indent-offset 4 python-indent-guess-indent-offset t)
 (c-c++ :variables c-c++-backend 'lsp-clangd lsp-clients-clangd-executable "/usr/bin/clangd" c-c++-enable-google-style t c-c++-enable-google-newline t)
 (nginx)
 (javascript)
 (html)
 (json)
 (yaml)
 (php :variables php-backend 'lsp)
 (shell-scripts :variables shell-scripts-backend 'lsp)
 (swift)
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-minimum-prefix-length 2 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil auto-completion-use-company-box nil auto-completion-enable-sort-by-usage nil :enabled-for python c-c++ html json yaml php ruby asm latex markdown plantuml shell script swift cmake)
 (ibuffer :variables ibuffer-group-buffers-by nil)
 (bm)
 (ansible)
 (multiple-cursors :variables multiple-cursors-backend 'mc)
 (org :packages
      (not evil-org-mode))
 (osx :variables osx-command-as 'hyper osx-option-as 'meta osx-control-as 'control osx-function-as nil osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left osx-swap-option-and-command nil))
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS ZLIB

#### Backtrace :paw_prints:
Both lsp-enabled-clients and lsp-disabled-clients variables are nil.

**Comment by lebensterben** [comment] 2022-08-07 18:06
bash and zsh are two languages.

**Comment by breadncup** [comment] 2022-08-07 18:32
Okay, so do I need to set up more for distinguishing bash/zsh? I'm on zsh, and could you let me know what I need to do more for it if necessary, please?

**Comment by lebensterben** [comment] 2022-08-07 18:45
if you want to write zsh, there's no lsp.

if you want to write bash, rename it to .bash.

**Comment by lebensterben** [comment] 2022-08-07 18:49
Closing since this is not a bug.

Also see https://github.com/emacs-lsp/lsp-mode/blob/f7be9f26e87aa853d0102e8d45c3d3d9995f7e86/clients/lsp-bash.el#L70

**Closed** 2022-08-07 18:49 UTC

**Comment by breadncup** [comment] 2022-08-08 01:27
Thanks!
