### ISSUE TITLE
Lines aren't rendered with default background color after end of content

### ISSUE THREAD

**Issue by th0br0** [syl20bnr/spacemacs#5428] opened 2016-03-09 19:27 UTC
#### Description
Lines aren't filled with default line background color after the end of the line content. This was observed on pre-emacs-25 as well. Only `manoj-dark` and `wheatgrass` don't seem to have this issue. Background color differs between light/dark themes: either a bright or dark blue color.

#### Reproduction guide
- Start Emacs

*Observed behaviour:*
![bug](https://cloud.githubusercontent.com/assets/30996/13647536/eb424f6c-e634-11e5-80b4-9cca67ff63c0.png)

*Expected behaviour:*
Lines are filled with default line background color.

#### System Info
- OS: gnu/linux, Fedora 25.
- Emacs: 25.0.92.1
- Spacemacs: 0.105.13
- Spacemacs branch: master (rev. 2c3e6b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults git markdown org
                 (colors :variables colors-enable-nyan-cat-progress-bar t)
                 emacs-lisp ess scala rust sql java
                 (python :variables python-enable-yapf-format-on-save t)
                 latex javascript html yaml shell shell-scripts typescript ansible dockerfile vagrant syntax-checking version-control polymode)
```

**Comment by korayal** [comment] 2016-03-21 16:00
This may be directly related to Emacs (or GTK). I'm getting the same issue even if I run `emacs -Q` and manually set the background to `red` the frame background turns `black`. If i set it to `white`, the frame becomes `blue`

**Comment by d12frosted** [comment] 2016-03-21 16:02
@korayal what version of Emacs are you using?

**Comment by th0br0** [comment] 2016-03-21 16:03
As far as I know, that's highly likely (or at least it's one of the reasons). There's an open upstream ticket at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20882

@korayal do you happen to be using xmonad?

**Comment by korayal** [comment] 2016-03-21 16:05
@d12frosted I'm using emacs-24.5.1 but I also tried out emacs-snapshot package in ubuntu xenial and the issue is still there.

@th0br0 I'm on gnome 3.19.90 but I had the same issue on xmonad too.

**Comment by korayal** [comment] 2016-03-28 14:48
UPDATE: I installed `emacs24-lucid` instead  of `emacs24` and it started working alright. I think this issue is about GTK

**Comment by drenninghoff** [comment] 2016-04-02 06:14
I also ran into this issue yesterday on Fedora 24. Todays update to gtk3-3.20.2 has fixed the issue though, so this doesn't seem to be an emacs or a spacemacs bug.

**Comment by StreakyCobra** [comment] 2016-04-03 22:07
@th0br0 Can you also try if updating gtk fixes your issue?

**Comment by korayal** [comment] 2016-04-04 06:49
I switched back to emacs24 again and it seems the gtk update did the trick.

**Comment by Aletheia-Lothlorien** [comment] 2016-04-06 19:31
Had the same issue with OpenSuse Tumbleweed. Upgraded gtk today and now back to normal.

**Comment by StreakyCobra** [comment] 2016-04-10 14:52
Closing as this issue is fixed upstream.

**Closed by StreakyCobra** 2016-04-10 14:52 UTC
Labels: - Bug tracker -, Fixed upstream, Graphics, Themes
