### ISSUE TITLE
Python layer backend always load mypyls

### ISSUE THREAD

**Issue by aiace9** [syl20bnr/spacemacs#15109] opened 2021-10-20 08:05 UTC
#### Description :octocat:

lsp under python when loading ignore the python-lsp-server variable and always
load mspyls.

#### Reproduction guide :beetle:
The exact case where I am observing it but I think it is more general.
- set pylsp as a back end
- install mspyls, global
- install pylsp in a virtual env
- Start Emacs
- open a file with the virtualenv
- check that virtualenv is loaded
- mspyls is loaded instead of pylsp :broken_heart:

*Observations:*

what is happening is pretty clear from the lsp-log: when enrolled different backend
have different priorities and those win on the value of python-lsp-server.

- elpa/27.2/develop/lsp-mode-20211004.1756/lsp-pylsp.el::424
- elpa/27.2/develop/lsp-python-ms-20210513.1019/lsp-python-ms.el::552
- elpa/27.2/develop/lsp-pyright-20210513.1022/lsp-pyright.el::239
  
```txt
    Command "pylsp" i s present on the path.
    Command "pyls" is present on the path.
    Command "pylsp" is present on the path.
    Command "pyls" is present on the path.
    
    Found the following clients for /home/user/path_to_file/projects_code/mdb/setup.py:
    (server-id pylsp, priority -1),
    (server-id pyls, priority -2),
    (server-id mspyls, priority 1)
               
    The following clients were selected based on priority: (server-id mspyls, priority 1)
```

Change the priority values in the elpa files solved the problem, but this is
more like a temporal hack that won't survive next update.

Thanks for the lovely work in maintaining this layer :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 63056ecb5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust ruby restructuredtext ipython-notebook sphinx yaml django html javascript lsp sql csv systemd
      (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow c-c++-enable-organize-includes-on-save nil c-c++-enable-clang-format-on-save t)
      helm
      (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      (python :variables
               python-backend 'lsp
               python-lsp-server 'pylsp
               python-test-runner 'pytest
               python-formatter 'yapf
               python-fill-column 80
               python-enable-yapf-format-on-save t
               python-pipenv-activate t)
      emacs-lisp git docker org markdown graphviz treemacs
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control
      bibtex semantic
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

**Comment by aiace9** [comment] 2021-10-20 09:43
Ok, I took another look at the code base and it seems that the =python-lsp-server= does not force any server (despite what the name suggest) but is just used to set some extra option in the mspyls and pyright cases. Am I right? If so, can we change the documentation to reflect this behavior? 
Because I don't find this very clear :) 
```
Language server to use for lsp backend. Possible values are ‘pylsp’, ‘pyright’
and ‘mspyls’
```

**Comment by lebensterben** [comment] 2021-10-20 10:23
no. that's not right.

**Comment by smile13241324** [comment] 2021-11-18 21:15
@aiace9 please have a look at my comments in  the ticket linked by @roderik33. Normaly this is caused by an auto installed instance of mypls in your .cache directory where lsp fallsback to if there is no better choice.

If this does not help I can have a more detailed look at the weekend.

**Comment by aiace9** [comment] 2021-11-18 21:55
I already checked when the comment was made and it seems like I am in a similar situation, I indeed have a mypls folder in the .cache folder. But before answering I wanted to double check how it ended up there, unfortunately since my hack survived the last two updates I haven't yet done it.

**Comment by smile13241324** [comment] 2021-11-28 08:47
Since there was no answer yet I would like to close this ticket for now. If you still have this issue feel free to reopen it

**Closed** 2021-11-28 08:47 UTC
