### ISSUE TITLE
Named workspaces don't show workspace indicator in modeline

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#6275] opened 2016-06-09 18:13 UTC
#### Description :octocat:
Named workspaces don't show workspace indicator in modeline.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC l w 2`
- `SPC l w R test RET`

*Observed behaviour:* :eyes: :broken_heart:
Workspace indicator at bottom left disappears

*Expected behaviour:* :heart: :smile:
Workspace indicator is still present

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. d07b0aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults gtags ibuffer spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 dash
 (shell :variables shell-default-shell 'shell shell-default-term-shell
        (mir/with-executable "/usr/local/bin/fish" "/usr/bin/fish" "/bin/bash" "/bin/sh")
        shell-default-height 50)
 prodigy restclient version-control git csv html javascript markdown nginx python ruby shell-scripts sql yaml django chef mir-magit-annex mir-pass mir-rc mir-rc-qualia mir-rc-grandbell)
```

**Comment by nixmaniack** [comment] 2016-06-10 08:48
Not able to reproduce. I do use named workspaces and they're still working fine on latest develop.

**Comment by TheBB** [comment] 2016-06-10 09:10
Same, can't repro.

**Comment by darkfeline** [comment] 2016-06-10 16:47
@TheBB I think I found the cause in `spaceline`

https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el#L448

~~~ emacs-lisp
(spaceline-define-segment workspace-number
  "The current workspace name or number. Requires `eyebrowse-mode' to be
enabled."
  (when (bound-and-true-p eyebrowse-mode)
    (let* ((num (eyebrowse--get 'current-slot))
           (tag (when num (nth 2 (assoc num (eyebrowse--get 'window-configs)))))
           (str (if (and tag (< 0 (length tag)))
                    tag
                  (when num (int-to-string num)))))
      (if spaceline-workspace-numbers-unicode
          (spaceline--unicode-number str)
        (propertize str 'face 'bold)))))
~~~

`(spaceline--unicode-number str)` is `nil` because `str` is the workspace name, not an int as a string.

**Comment by TheBB** [comment] 2016-06-10 17:27
Indeed… it only reproduces with unicode turned on. Thanks. :-)

**Comment by TheBB** [comment] 2016-06-10 17:55
Fixed in https://github.com/TheBB/spaceline/commit/a85c61722632755f80ab19412b3cf55cdee6abd4. Should be on MELPA within a few hours.

**Closed by TheBB** 2016-06-10 17:55 UTC
Labels: - Bug tracker -, Fixed upstream, Spacemacs Layouts
