### ISSUE TITLE
Handle per major mode prefix commands in guide-key

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#183] opened 2014-12-01 02:28 UTC
`<SPC> m` is not handled correctly for now, we can try to use local key sequences from `guide-key` to support it but it may be not exactly what we need.
This is also a bug because the bindings from different major modes are merged together in the `guide-key` buffer under `<SPC> m` prefix command.

More info: 
https://github.com/kai2nenobu/guide-key#add-settings-in-a-particular-mode

**Comment by mattly** [comment] 2015-06-28 01:13
Is this issue with guide-key documented anywhere? I didn't see any issues filed with them, and after uncommenting `spacemacs/declare-prefix-for-mode` and setting up some prefixes locally, it seems to work just fine. 

![emacs lluvia home 2015-06-27 18-10-59](https://cloud.githubusercontent.com/assets/891/8394645/e29e66a4-1cf7-11e5-8f7b-9211d43c67b9.png)

![emacs lluvia home 2015-06-27 18-11-36](https://cloud.githubusercontent.com/assets/891/8394649/f5f40812-1cf7-11e5-8a98-ccda41ce466d.png)

**Comment by martinmr** [comment] 2015-07-06 17:57
@mattly @syl20bnr: I also tested declare-for-mode and it is working. It seems like whatever bug was affecting guide-key has been resolved since. Commit https://github.com/martinmr/spacemacs/commit/c17660cecd85758c8a85d4132e8c0f40bfa3e101 uncomments the method.

**Comment by catesandrew** [comment] 2015-07-08 04:40
The [latest commit](https://github.com/kai2nenobu/guide-key/commit/c6eb355f8efe73d68a6e2f994c49df1fe71bcc2a) in guide-key was from feb 8 and is in the dev branch. i think melpa only picks up master branch so one wouldn't see the commit anyways. although the comment of the commit suggests it could be fixed. pretty sure there's other big problems with guide-key though, mainly lack of adding descriptions, cpu cycle loads, etc. belive @syl20bnr is creating an alternative to guide-key.

**Comment by bmag** [comment] 2015-07-08 18:40
@catesandrew an alternative to guide-key is being developed, it's called which-key and can be found [here](https://github.com/justbur/emacs-which-key). It is developed by @justbur and myself (mostly @justbur).

It doesn't use polling timers, so it shouldn't cause cpu cycle loads, and it supports adding descriptions. It also gives you the option to show the keys in the minibuffer or in a separate frame, you're not limited to a side window. Another advantage is that it doesn't use popwin, so it doesn't suffer from popwin-related bugs.

which-key isn't perfect yet, but it's working well enough that I stopped using guide-key. If anyone wants to try it and give some feedback, especially OS X users, it would help.

**Comment by TheBB** [comment] 2015-09-03 18:57
I can't reproduce this with which-key, so marking as fixed in develop.

**Closed** 2015-09-28 06:54 UTC
Labels: bug :-(, enhancement :-D, Fixed in `develop`, Guide-key
