### ISSUE TITLE
[spacemacs.org error] go-layer Pre-requisites document error

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#8443] opened 2017-02-27 02:24 UTC
In the document website page [http://spacemacs.org/layers/+lang/go/README.html](go-layer), the **Pre-requisites** describe that 
```
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/oracle
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/goimports
```

, but go-layer **Pre-requisites** has changed to

```
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/guru
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/goimports
```

**Comment by lupoDharkael** [comment] 2017-03-14 13:05
Please, fix this, it could be very confusing for newcomers.

**Comment by z3t0** [comment] 2017-05-13 06:26
For some reason I am getting "Could not run godef binary" after following these instructions..

**Comment by Miciah** [comment] 2018-07-11 08:02
This issue is a duplicate of #6772.

**Closed** 2019-04-04 09:00 UTC
Labels: - Bug tracker -, Documentation ✏, Fixed in develop, Go
