### ISSUE TITLE
hl-todo issue, files open modified, auto-complete layer causes hangs

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#12143] opened 2019-04-09 18:25 UTC
#### Description :octocat:

There seems to be an issue with the latest version of `hl-todo-20190408.1348`.
None of the below issues occur with the previous version: `hl-todo-20190404.2134`

@tarsius Do you know what could be causing this issue?

When the `auto-complete` layer is installed.
After restarting Emacs.
`SPC f e d` doesn't open `.spacemacs`, the cursor can't be moved, and Emacs ramps up the cpu to `30%` (maybe windows limits Emacs to `30%`).

`C-g` restores the cursor movements, and zeros the cpu usage.

Now `SPC f e d` opens `.spacemacs` but it's opened in a modified state (asterisk in the mode-line).

However when calling `M-x` `diff-buffer-with-file` and choosing `.spacemacs`, then the diff buffer shows:
>Diff finished (no differences).

The messages buffer shows:
>Error during redisplay: (jit-lock-function 1) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 501) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 1001) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 1501) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 2001) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 2501) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 3001) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 3501) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 4001) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 4501) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 5001) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 5501) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 9320) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 7763) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 8263) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 8763) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Error during redisplay: (jit-lock-function 9263) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")

When I try to close the `.spacemacs` buffer `SPC b d`, then the minibuffer shows:
>Buffer .spacemacs modified; kill anyway? (y or n)

Without the `auto-complete` layer, `SPC f e d` opens on the first try, but still in a modified state.

#### It doesn't happen without Spacemacs
It seems to be an issue in Spacemacs, because when I try it without Spacemacs:

- Start `runemacs.exe -q`
- `(setq package-user-dir "~/.emacs.d/elpa/26.1/develop/")`
- `M-x` `global-hl-todo-mode`
- Open `.spacemacs` (`C-h v` `hl-todo-mode` shows `t`)

the buffer opens unmodified (as expected), and there are no `jit-lock` messages in the Messages buffer.

The buffer opening modified, isn't limited to `.spacemacs` it also happens when creating a new file: `issue-hl-todo.el`. It opens modified if it contains at least one character `a`, But if it's empty then it opens unmodified.

*Expected behaviour:* :heart: :smile:

`SPC f e d` shouldn't get stuck when the `auto-complete` layer is installed.
Files shouldn't open in a modified state.
And the `jit-lock-function` error messages shouldn't occur.

#### Notes

The same thing is observed with Emacs 27.0.50 in windows.

In Ubuntu 18.04.2, with Emacs 27.0.50, (virtualbox guest, with win10 as host)
`.spacemacs` doesn't open modified, but the hang with the `auto-complete` layer occurs, and the `jit-lock-function` messages appear in the messages buffer.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f85acca55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by nate** [comment] 2019-04-09 21:05
I'm also seeing the files open modified issue on macos 10.14.4 and emacs 26.1 and haven't been able to track down where it's coming from. Also seeing max-lisp-eval-depth errors in messages.

**Comment by nate** [comment] 2019-04-09 21:07
also, even if I save the file just scrolling around will cause the file to be modified again...

**Comment by nate** [comment] 2019-04-09 21:20
It seems like the error `Error during redisplay: (jit-lock-function 23935) signaled (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")` is exactly when the file is marked as modified, too...

**Comment by nate** [comment] 2019-04-09 21:28
disabling the `hl-todo` package seems to fix it

**Comment by tarsius** [comment] 2019-04-09 21:32
Try if reverting `hl-todo`'s 396d0923602a855fca58f43c98832afb66a479fa fixes the issue. If not, then also revert f7d97056d17ef7fc04f4fa0b65a703d1d1a5a6b8.

**Comment by tarsius** [comment] 2019-04-09 21:45
Before that just update `hl-todo` using `package.el`. I just fixed an irrelevant typo. The reason why this might fix the issue is that I say errors like the above during development too and then force pushed a fix. If Melpa build the package exactly during the short window when `master` was broken, then it might have been stuck on that version. After the typo fix a new version should appear (might take a few hours).

**Comment by nate** [comment] 2019-04-09 21:52
Sorry, I'm not really sure how to do either of those things....

**Comment by nate** [comment] 2019-04-09 21:53
I did package-reinstall of hl-todo and it didn't get the typo fix from here https://github.com/tarsius/hl-todo/commit/ac82d5e2de61833ceee7dea023f76e5fccee4d2e

**Comment by nate** [comment] 2019-04-09 22:02
OK, I think I figured it out. I added this:

```
   dotspacemacs-additional-packages '(
                                      (hl-todo :location (recipe :fetcher github :repo "tarsius/hl-todo" :commit "60797aa364e2ea6f4efead7f408eed9358dce5b5"))
                                      )
```

That makes it use the commit before 396d0923602a855fca58f43c98832afb66a479fa. This seems to fix the issue for me.

**Comment by nate** [comment] 2019-04-09 22:08
I confirmed that if I make it use 396d0923602a855fca58f43c98832afb66a479fa the issue reappears.

**Comment by duianto** [comment] 2019-04-10 08:32
Confirmed as well.
`60797aa` works.
`396d092` broken.

**Comment by tarsius** [comment] 2019-04-10 10:15
Pushed https://github.com/tarsius/hl-todo/commit/b26423b07293d7e47d28544ce0a4c9a76e5d3a6f, which should fix this. While https://github.com/tarsius/hl-todo/commit/396d0923602a855fca58f43c98832afb66a479fa triggered this issue, it isn't really to be blamed. It just happened to push the depth over the edge for many files. The recursive approach added in https://github.com/tarsius/hl-todo/commit/cdc22667f4c7dc3781390c7f9dc8fe2f2c325147 ultimately caused this.

**Comment by duianto** [comment] 2019-04-10 13:10
There's still something not quite right, with the latest version: `hl-todo-20190410.1002`

When I try to open `.spacemacs` with `SPC f e d`, or even the file `issue-hl-todo.el` which only contains the character `a`, then Emacs hangs with ~30% cpu usage in windows and 90% in Ubuntu (running in virtualbox), virtualbox in windows is using ~30% cpu at that point.

The `auto-completion` layer is commented out in both windows and ubuntu. It caused a one time hang with the previous hl-todo version, that could be canceled with `C-g`, but with the latest version `C-g` does nothing.

**Comment by tarsius** [comment] 2019-04-10 13:54
I don't see how `auto-complete` has anything to do with this. Or if it has something to do with that how `hl-todo` would contribute to the issue. There might be two unrelated issues.

Lets look at https://github.com/tarsius/hl-todo/commit/396d0923602a855fca58f43c98832afb66a479fa together.

The new regexp from the second hunk is slightly less efficient, but I don't think that should matter.

The change from the third hunk means instead of N `equal` we now need N `string-match-p`. That's more expensive and might make a difference. N is `(* (length hl-todo-keyword-faces) number-of-todo-items-in-file)`. However when there are no such items, then I don't see how it could make a difference.

**Comment by tarsius** [comment] 2019-04-10 13:57
Maybe you have customized `hl-todo-keyword-faces` and now that the cars of its entries are treated as partial regexps one of them becomes very expensive? Quoting would help in that case.

**Comment by duianto** [comment] 2019-04-10 14:07
The reason for mentioning the Spacemacs `auto-completion` layer, is because in the issue report I said:
>When the auto-complete layer is installed.
After restarting Emacs.
SPC f e d doesn't open .spacemacs, the cursor can't be moved, and Emacs ramps up the cpu to 30% (maybe windows limits Emacs to 30%).
>
>C-g restores the cursor movements, and zeros the cpu usage.

and:
>Without the auto-complete layer, SPC f e d opens on the first try, but still in a modified state.

(I forgot that the layer was called `auto-completion` and not just `auto-complete`)
I just wanted to state that it was disabled when Emacs hung this time.

This is the output of `C-h v` `hl-todo-keyword-faces`:
```
hl-todo-keyword-faces is a variable defined in ‘hl-todo.el’.
Its value is shown below.

Documentation:
Faces used to highlight specific TODO keywords.

Each entry has the form (KEYWORD . COLOR).  KEYWORD is used as
part of a regular expression.  If (regexp-quote KEYWORD) is not
equal to KEYWORD, then it is ignored by ‘hl-todo-insert-keyword’.

The syntax class of the characters at either end has to be ‘word’
in ‘hl-todo--syntax-table’.  That syntax table derives from
‘text-mode-syntax-table’ but uses ‘word’ as the class of "?".

You can customize this variable.

This variable was introduced, or its default value was changed, in
version 2.0.0 of the hl-todo package.


Value:
(("TODO" . #1="#dc752f")
 ("NEXT" . #1#)
 ("THEM" . "#2d9574")
 ("PROG" . #2="#4f97d7")
 ("OKAY" . #2#)
 ("DONT" . #3="#f2241f")
 ("FAIL" . #3#)
 ("DONE" . "#86dc2f")
 ("NOTE" . #4="#b1951d")
 ("KLUDGE" . #4#)
 ("HACK" . #4#)
 ("TEMP" . #4#)
 ("FIXME" . #1#)
 ("XXX" . #1#)
 ("XXXX" . #1#)
 ("???" . #1#))
Original value was 
(("HOLD" . "#d0bf8f")
 ("TODO" . "#cc9393")
 ("NEXT" . "#dca3a3")
 ("THEM" . "#dc8cc3")
 ("PROG" . "#7cb8bb")
 ("OKAY" . "#7cb8bb")
 ("DONT" . "#5f7f5f")
 ("FAIL" . "#8c5353")
 ("DONE" . "#afd8af")
 ("NOTE" . "#d0bf8f")
 ("KLUDGE" . "#d0bf8f")
 ("HACK" . "#d0bf8f")
 ("TEMP" . "#d0bf8f")
 ("FIXME" . "#cc9393")
 ("XXX+" . "#cc9393")
 ("\\?\\?\\?+" . "#cc9393"))

[back]
```

I have not made any modifications to that variable manually.

**Comment by duianto** [comment] 2019-04-10 14:16
The values seem to come from the spacemacs-theme:
https://github.com/nashamri/spacemacs-theme/blob/master/spacemacs-common.el#L945

**Comment by tarsius** [comment] 2019-04-10 14:21
The "???" is the problematic keyword. I have added a kludge in a559895cc7cb8a5b58d89a4d76177b5eef4d2abd, which removes the entry if present.

> The values seem to come from the spacemacs-theme:

Could you please submit a pr that updates the last two entries to use the same keyword regexps as the new default value?

**Comment by duianto** [comment] 2019-04-10 14:39
Just to make sure, the last three regexps in the spacemacs-theme are:
```
"XXX"
"XXXX"
"???"
```
Should the middle "XXXX" one be removed?
And the last two remaining, be changed to match the original values?
```
"XXX+"
"\\?\\?\\?+"
```

**Comment by nate** [comment] 2019-04-10 15:12
confirmed that a559895cc7cb8a5b58d89a4d76177b5eef4d2abd fixes the issue for me

**Comment by tarsius** [comment] 2019-04-10 15:43
Yes.

**Comment by duianto** [comment] 2019-04-10 15:48
Ok, thanks for the help.

I can also confirm that `a559895cc7cb8a5b58d89a4d76177b5eef4d2abd` works.

I'll open a PR on the spacemacs-theme repo.

**Closed** 2019-04-10 15:48 UTC
Labels: Fixed upstream
