### ISSUE TITLE
File mode specification error 

### ISSUE THREAD

**Issue by huypn12** [syl20bnr/spacemacs#13865] opened 2020-08-20 18:24 UTC
Emacs 27.1
Spacemacs, develop branch, HEAD at commit 81d1c9f787d9e61b0779971fedd245e8b1cd5279

Spacemacs shows the following error on opening of any file (tested with .c and .tex). The file is opened without any file mode highlighting. 
```
Package cl is deprecated
Error running timer ‘global-git-gutter+-mode’: (wrong-type-argument stringp evil-mc-enable-bar-cursor)
File mode specification error: (wrong-type-argument stringp evil-mc-enable-bar-cursor)
```

Removing evil-mc package by commenting `multiple-cursors` results in the following error 
```
Package cl is deprecated
Error running timer ‘global-git-gutter+-mode’: (wrong-type-argument stringp spacemacs/vcs-transient-state/params)
File mode specification error: (wrong-type-argument stringp spacemacs/vcs-transient-state/params)
```

Spacemacs layers are configured as follow. The rest of .spacemacs is kept as default.
```
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press `SPC f e R' (Vim style) or
     ;; `M-m f e R' (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     auto-completion
     better-defaults
     emacs-lisp
     ;; git
     helm
     lsp
     markdown
     ;; multiple-cursors
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     version-control
     treemacs
     (lsp :variables
          lsp-ui-flycheck-enable t
          lsp-eldoc-hook '(lsp-hover)
          lsp-signature-auto-activate nil)
     (cmake :variables cmake-enable-cmake-ide-support t)
     (c-c++ :variables
            c-c++-backend 'lsp-clangd
            c-c++-adopt-subprojects t
            c-c++-enable-google-style t
            c++-enable-organize-includes-on-save nil
            c-c++-lsp-enable-semantic-highlight 'rainbow)
     gpu
     (python :variables
             python-backend 'lsp
             python-lsp-server 'pyls
             python-test-runner 'pytest
             python-formatter 'yapf)
     (rust :variables
           rust-backend 'lsp
           lsp-rust-server 'rust-analyzer)
     (go :variables
         go-backend 'lsp)
     (latex :variables
            latex-build-command "LatexMk")
     )
```

Error screenshot:
![grafik](https://user-images.githubusercontent.com/2792821/90811060-468a0680-e324-11ea-9046-4cc7c8317204.png)

**Comment by huypn12** [comment] 2020-08-28 17:20
It turned out that if I started emacs with specific file name, e.g
```
emacs /tmp/test.c
```
the file mode specification works just fine

**Comment by smile13241324** [comment] 2020-08-28 21:51
I have tried this on my linux box with your layer configuration and it seems to be working on my side. I can confirm the "cl-deprecation" warning but thats all. I have tested it with a .tex file which opened just fine.

Do you have any specific user configuration in your dotfile? Does the error also occurs without it?

Here is my system config:
```elisp
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fda75c68)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
(auto-completion better-defaults emacs-lisp helm lsp markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 version-control treemacs
                 (lsp :variables lsp-ui-flycheck-enable t lsp-eldoc-hook
                      '(lsp-hover)
                      lsp-signature-auto-activate nil)
                 (cmake :variables cmake-enable-cmake-ide-support t)
                 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-adopt-subprojects t c-c++-enable-google-style t c++-enable-organize-includes-on-save nil c-c++-lsp-enable-semantic-highlight 'rainbow)
                 gpu
                 (python :variables python-backend 'lsp python-lsp-server 'pyls python-test-runner 'pytest python-formatter 'yapf)
                 (rust :variables rust-backend 'lsp lsp-rust-server 'rust-analyzer)
                 (go :variables go-backend 'lsp)
                 (latex :variables latex-build-command "LatexMk"))
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
```

**Comment by huypn12** [comment] 2020-08-31 13:25
I did a search and put this line on top of init.el
```
(setq debug-on-error t)
```
This is the backtrace that appears when I open an arbitrary .c file 
![image](https://user-images.githubusercontent.com/2792821/91724886-3c76cc00-eb9e-11ea-81d6-05322722d826.png)

**Comment by huypn12** [comment] 2020-08-31 21:50
I tried removing multiple-cursors layer, still the error popped up
![grafik](https://user-images.githubusercontent.com/2792821/91772188-a6b25f80-ebe4-11ea-9ca8-8a14de237293.png)
I think something is wrong with the string-match call?

**Comment by smile13241324** [comment] 2020-09-01 20:50
@huypn12 I have had a look at your stacktrace, there you can see that the error is caused by a package called "elec-pair" which is loaded with `eval-after-load`, as part of this a `string-match` is done, why this is done against `evil-mc-enable-bar-cursor` is completely oblivious to me.

I am not sure where this "elec-pair" call comes from. Have you tested that this error occurs without a custom user config nor a custom init.el? I have made a project search for "elec-pair" as well as a folder search in all my elpa packages and I cannot find the failing line.

Please copy your dotfile and use a clean one on latest develop without custom user config or init.el modifications, just with your layers added and post your results. Also a clean of your emacs cache could help given this is caused by some strange installation/caching bug.

I can still not reproduce this issue and can therefore not fix it. I will add a label help wanted to this issue, maybe someone else has more luck in reproducing your issue.

**Comment by huypn12** [comment] 2020-09-01 21:15
Thank you very much for your support. This weekend I will try with other system to check if this problem is specific to Opensuse Tumbleweed or not. Then I will try to make a repro step guide.

**Comment by Hneuschmidt** [comment] 2020-09-02 08:49
I have the same error message, also running Opensuse Tumbleweed.
Opening the file via `emacs /path/to/file` works for me too.

**Comment by Hneuschmidt** [comment] 2020-09-03 10:30
I copied my .spacemacs file and used a fresh version with only my layers enabled.
The same error persists. Opening a file directly as suggested still works.

I tried adding only a minimal set of layers:
c-c++
syntax-checking
helm
emacs-lisp
![Spacemacs_debug_output](https://user-images.githubusercontent.com/50588502/92104138-39b7e900-ede1-11ea-8165-2524b8d56088.png)

**Comment by huypn12** [comment] 2020-09-03 13:44
@Hneuschmidt  try this:
```
$ emacs-gtk
```
instead of just 
```
$ emacs
```
I tried the idea after reading this [https://stackoverflow.com/questions/63527302/emacs-package-management-failure-in-emacs-27-1](url)

Seems like it is working now, although I have zero idea of how and why it happened like this.

**Comment by smile13241324** [comment] 2020-09-04 15:41
Interesting looks like in openSUSE emacs is a script rather than the plain emacs binary. The way the script handles emacs however seems to have side effects on multiple packages.

Knowing this I would like to close this ticket as being caused by the linux distribution not handling emacs correctly.

@huypn12 @Hneuschmidt maybe you should open a ticket with openSUSE to change the approach on handling emacs. Did you two find the workaround work for you?

**Comment by huypn12** [comment] 2020-09-05 11:27
Confirmed it worked with 
```
$ emacs-gtk
```
oddly enough, the problem disappeared in the latest update of Opensuse Tumbleweed. I found it out when tried to reproduce the case to fill in a bug report to OpenSuse Bugzilla.
@Hneuschmidt in my tumbleweed box now, even this 
```
$ emacs
```
works and emacs shows syntax highlighting as expected.
Could you please try and confirm on your machine?

**Comment by Hneuschmidt** [comment] 2020-09-08 12:16
@huypn12  I updated my OS and can confirm that both 
`emacs` 
and
`emacs-gtk`
work as expected again.
@smile13241324 It seems you are right that it was caused by Opensuse and that the problem disappeared so I think this ticket can be closed as you suggested.

**Closed** 2020-09-08 19:33 UTC
Labels: Should report upstream
