### ISSUE TITLE
Linum-mode creates margins on zoomed-in font

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#9382] opened 2017-08-06 12:09 UTC
#### Description :octocat:
Linum-mode creates margins on zoomed-in font

#### Reproduction guide :beetle:
- Start Emacs
- Load Spacemacs
- Load buffers with linum mode on
- `C-x C-+` a few times
- Start switching buffers

*Observed behaviour:* :eyes: :broken_heart:
See the video: https://streamable.com/wa4xh
![](https://i.imgtc.com/IlsZGMi.png)

*Expected behaviour:* :heart: :smile:
The margins stay immobile when I change buffers.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql html markdown helm auto-completion common-lisp emacs-lisp git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N\_FLT LIBOTF XFT ZLIB TOOLKIT\_SCROLL\_BARS GTK3 X11

#### Backtrace :paw_prints:
None.

**Comment by phoe** [comment] 2017-08-06 12:13
This is crazy. It disappeared after restarting spacemacs. I will try to trigger it again.

**Comment by phoe** [comment] 2017-08-06 12:15
This bug only happens when the same buffer is opened in more than one visible buffer at once. It has to be the same buffer.

**Comment by duianto** [comment] 2017-08-06 12:21
This might be a related issue:
Line number doesn't go back to normal after I increase the font size and reset it. #8481

**Comment by sdwolf** [comment] 2017-08-06 12:48
Does #9209 fix your problem?

**Comment by phoe** [comment] 2017-08-06 13:22
@sdwolf This fixes my problem! Please merge it into mainline.

**Comment by dabro** [comment] 2017-08-31 14:28
I continue to have this problem.  I have `text-scale-mode-step` set at 1.2, and I don't have `window-initial-margins` bound.  Haven't yet retested with no scale mode set.

On - Emacs: 26.0.50, - Spacemacs: 0.200.9, - Spacemacs branch: develop (rev. c1cac55e)
![screen shot 2017-08-30 at 1 39 49 pm](https://user-images.githubusercontent.com/9028933/29928476-ba737872-8e2e-11e7-9def-22240ca4d4c8.png)

**Comment by pawandubey** [comment] 2018-07-13 17:56
I can reproduce this consistently. Emacs 27.0.50, Mac OSX 10.14, Spacemacs v.0.200.13

**Comment by alexryndin** [comment] 2018-08-24 19:41
Same here on ArchLinux with emacs 0.200.13@26.1 (spacemacs)

**Comment by sdwolfz** [comment] 2018-08-28 15:28
While the problem was fixed in develop, it was not released to master yet. You need to either switch to the develop branch or wait for a new release.

**Comment by alexryndin** [comment] 2018-08-31 10:00
I found out that there are actually two line numbering modes, one which is enabled through M-x linum-mode, and second toggled by SPC t n. 
Both behave differently with zoom in develop branch.
![screenshot from 2018-08-31 12-54-09](https://user-images.githubusercontent.com/8342078/44906244-0a1b0580-ad1d-11e8-858d-9b5b34d45af5.png)
So problem was kind of fixed.
I'll test those modes behavior in master branch later.

**Comment by sdwolfz** [comment] 2018-08-31 10:11
@alexryndin On develop, with emacs 26 linum mode is obsolete, you should use the emacs built in `display-line-numbers-mode`.

**Comment by dbrw** [comment] 2019-03-14 07:31
Is there any news on when this fix will be released?

**Comment by alexryndin** [comment] 2019-03-14 07:36
@dbrw don't know about master branch, but linum works well on dev, check it out. Remember to use built-in line numbers mode, not linum.

**Comment by agzam** [comment] 2019-03-15 16:41
everyone using linum, please stop using it. Emacs has native support for line numbers relative and absolute. e.g.: 
```
(setq display-line-numbers ’relative) 
(display-line-numbers-mode t)
```
This should probably need to be in a FAQ

**Comment by duianto** [comment] 2019-04-12 17:02
Here's a possible fix on the master branch:

Add this to the `dotspacemacs/user-config` section of your `.spacemacs`:
```
    (spacemacs/set-leader-keys "tn" 'display-line-numbers-mode)
```
Then the `SPC t n` key binding will toggle the new Emacs built-in line numbers in Emacs 26+.

**Comment by ashrasmun** [comment] 2019-04-30 10:42
> everyone using linum, please stop using it. Emacs has native support for line numbers relative and absolute. e.g.:
> 
> ```
> (setq display-line-numbers ’relative) 
> (display-line-numbers-mode t)
> ```
> 
> This should probably need to be in a FAQ

https://i.imgur.com/iSeq2KU.jpg 
Your attitude is quite hilarious too. Emacs's native support for line numbering is not sufficient. Not to mention that it doesn't work or works randomly.

**Comment by agzam** [comment] 2019-04-30 17:04
@ashrasmun I admit - I don't use line numbers very often (only when I'm pair programming), and I don't know if and why native line numbers don't work or why they are insufficient in certain cases.
The biggest issue with linum-mode - it is slow. Most of the time when people complain about Spacemacs being sluggish, I suggest to try disabling linum-mode and that fixes it for them.
I don't get why you say "Your attitude is quite hilarious", because I believe linum-mode should be deprecated and whatever issues people find with native support, they should be addressed by fixing them in Emacs. That would happen sooner if more people stop using linum-mode.

**Comment by agzam** [comment] 2019-05-06 20:41
@ashrasmun have you tried setting `(setq display-line-numbers 'visual)`

**Comment by agzam** [comment] 2019-05-17 19:26
Related discussion http://lists.gnu.org/archive/html/emacs-devel/2019-05/msg00155.html

**Comment by vitaminace33** [comment] 2020-05-16 17:34
The bug is still alive or is it recurrent? 0.200.13@26.3

**Comment by lebensterben** [comment] 2021-08-24 02:29
This is fixed on develop branch.
If you're on master branch, switch to develop.
If this is still a bug on develop branch, please open a new issue with details.

**Closed by lebensterben** 2021-08-24 02:29 UTC
Labels: Fixed in develop, - Bug tracker -, Line numbers
