### ISSUE TITLE
Smooth-scrolling doesn't work in Chinese(gui)

### ISSUE THREAD

**Issue by S-X-ShaX** [syl20bnr/spacemacs#5637] opened 2016-03-30 09:04 UTC
####Description:
I'm a new-emacser and I love spacemacs very much.I know spacemacs enable the smooth scrolling by default,and when I am reading an English text it works fine,however when I am reading an all Chinese page it fails and always recenter.More strangely,under some special window size it works but most not...Plus it works fine in Terminal.
So where the problem it is?My USE flags(I'm using gentoo,and added some USE to emacs) or spacemacs or smooth-scrolling?
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. 3aff734)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by S-X-ShaX** [comment] 2016-03-30 13:34
Here's my USE flags:
````
>=app-editors/emacs-24.5-r1  alsa gtk gtk3 games gconf gsettings gfile inotify imagemagick sound source toolkit-scroll-bars wide-int xft
>=app-emacs/emacs-common-gentoo-1.5 games
````

**Comment by S-X-ShaX** [comment] 2016-03-31 05:14
Also a strange thing...it only fail when I'm pressing down key(such as Ctrl+n),up key or Ctrl+p works fine...

**Comment by jramapuram** [comment] 2016-04-06 08:47
This happens in English as well as code: https://github.com/syl20bnr/spacemacs/issues/5456

**Comment by TheBB** [comment] 2016-08-29 20:14
Probably a duplicate of #5456 (and probably fixed in develop).

**Closed by TheBB** 2016-08-29 20:14 UTC
Labels: - Bug tracker -, Chinese, Smooth-scrolling, To be reproduced
