### ISSUE TITLE
Vterm does not have the same environment variable as native terminal on Mac OS Big Sur

### ISSUE THREAD

**Issue by XushanLu** [syl20bnr/spacemacs#14803] opened 2021-05-27 15:01 UTC
# Description

The environment variable DYLD_LIBRARY_PATH is different from what I got from using terminal. That variable is unset in vterm but properly set in terminal. This caused my compiled executables not able to find the dynamic library with the following error:
`dyld: Library not loaded: @rpath/libmkl_intel_lp64.1.dylib`. 

The code runs perfectly fine within terminal.

# Reproduction Guide
- Open Emacs
- Open vterm 
- Type `echo $DYLD_LIBRARY_PATH`
- Open terminal
- Type `echo $DYLD_LIBRARY_PATH`

# Observed behavior
- Nothing prints within vterm
- Terminal prints the following
```shell
/opt/intel/oneapi/tbb/latest/env/../lib:/opt/intel/oneapi/mkl/latest/lib:/opt/intel/oneapi/ippcp/2021.2.0/lib:/opt/intel/oneapi/ipp/2021.2.0/lib:/opt/intel/oneapi/dnnl/2021.2.0/cpu_iomp/lib:/opt/intel/oneapi/dal/2021.2.0/lib:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib/intel64_mac:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib
```

# Expected behavior
- Both vterm and terminal return the same thing.

# System info
- OS: Mac OS Big Sur 11.03
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop
- Spacemacs layers:
```lisp
    dotspacemacs-configuration-layers
   '(vimscript javascript auto-completion better-defaults emacs-lisp helm html csv python ipython-notebook
     markdown org spell-checking syntax-checking version-control
     (shell :variables
            shell-default-height 30
            shell-default-shell 'vterm
            shell-default-term-shell "/usr/local/bin/zsh"
            shell-default-position 'bottom)
     (c-c++   :variables
              c-c++-default-mode-for-headers 'c++-mode
              c-c++-enable-clang-support t)
     pandoc ivy bibtex
     (latex :variables latex-build-command "LatexMk")
     eaf pdf
     (java :variables java-backend 'meghanada)
     gtags
     )
```

**Comment by lebensterben** [comment] 2021-05-27 15:31
not our bug.
You should report to upstream.

**Comment by thanhvg** [comment] 2021-05-27 20:50
I'm know nothing about Macs but you can try `SPC e e` to see the list of env variables Spacemacs picks up. `SPC e E` to tell Spacemacs to refresh them or you can add your own variable there.

**Comment by smile13241324** [comment] 2021-05-27 20:51
This is not a bug. When you start Spacemacs the environment variables of your shell will be given to Spacemacs. Spacemacs in turn will give all environment values it will find in  `.spacemacs.env` to your sub shells. You should check the content of this file with `spc f e e` and correct the missing variable. You can also regenerate the file with `SPC f e C-e`, but you should definitely go through there once to make sure that algorithm did not mess up.

**Comment by XushanLu** [comment] 2021-05-27 22:30
Thanks for all your comments. 

`spc f e e` does show a list without DYLD_LIBRARY_PATH. It seems that the content of that file is obtained from running the command 'env' in my shell (zsh). The output of `env` in my zsh seems to be identical to .spacemacs.env except that the rows are reordered in that file based on the initial letter alphabatically. 

But I can see the values of DYLD_LIBRARY_PATH by `echo $DYLD_LIBRARY_PATH`, which is weird. 

I guess it is true that this should not be considered a bug for Spacemacs since it correctly picks up all the stuff given by `env` in my zsh. But why `env` is not able to pick up the value for DYLD_LIBRARY_PATH truly puzzles me. 

Thanks again for all the comments!

**Comment by lebensterben** [comment] 2021-05-28 01:34
> I guess it is true that this should not be considered a bug for Spacemacs since it correctly picks up all the stuff given by `env` in my zsh. But why `env` is not able to pick up the value for DYLD_LIBRARY_PATH truly puzzles me.

False.
If SIP is the cause then vanilla emacs cannot see this variable to. Then this is definitely an upstream bug.

As I said, you should report it to upstream.
A quick fix is to set `vterm-environment`.

**Comment by XushanLu** [comment] 2021-05-28 12:08
I have no idea how to set `vterm-environment` in Emacs, and here is what I did:
![image](https://user-images.githubusercontent.com/7824380/119981561-5cee7e00-bf98-11eb-92f9-8e5a436d8d71.png)
I clicked that `state` button and saved this value (by choosing both 0 and 1). Nothing seems to be working. 

I will report this to the vterm maintainers as well. Thanks.

**Comment by lebensterben** [comment] 2021-05-28 14:07
from what's shown in the screenshot you haven't applied the changes.

**Comment by XushanLu** [comment] 2021-05-28 16:25
I tried again and now I think I have saved it. But when I save it, it says 'Failed: update TAGS(3)', which I have no idea of. Here is what I have now and it still does not work.
![image](https://user-images.githubusercontent.com/7824380/120014235-64c01980-bfbc-11eb-8bec-d6b8179cd7ca.png)

**Comment by lebensterben** [comment] 2021-05-28 16:46
don't use easy-customization

set this variable in you user-conifg

**Comment by XushanLu** [comment] 2021-05-28 18:24
That indeed successfully set the variable and now vterm is aware of the correct value to use. However, this causes another issue: vterm cannot delete typed-in commands anymore. When deleting, the cursor just moves to the right (although it seems to be still deleting things, I cannot see what has been deleted). This happens to me previously when I was running gdb to debug my codes using ansi-term. That was the reason why I switched to vterm. Now it happens even outside gdb!

Any thoughts? Thanks very much!

**Comment by lebensterben** [comment] 2021-05-28 19:56
> this causes another issue: vterm cannot delete typed-in commands anymore. When deleting, the cursor just moves to the right (although it seems to be still deleting things, I cannot see what has been deleted)

What do you mean?
How to reproduce

**Comment by XushanLu** [comment] 2021-05-29 14:30
Like this as shown in the short video. I actually pressed backspace five times but the cursor actually goes to the right five times and you can see actually I am still able to execute the command I wanted `echo $DYLD_LIBRARY_PATH`. This time, it does show that vterm is able to pick up the value I set in the init file.

https://user-images.githubusercontent.com/7824380/120073913-f8edb780-c074-11eb-9373-7ae8962c3aaf.mov

To reproduce, try put the following lines inside `defun dotspacemacs/user-config`:
```lisp
  ;; Set vterm-environment to add the DYLD_LIBRARY_PATH variable
  (setq vterm-environment "DYLD_LIBRARY_PATH=opt/intel/oneapi/tbb/latest/env/../lib:/opt/intel/oneapi/mkl/latest/lib:/opt/intel/oneapi/ippcp/2021.2.0/lib:/opt/intel/oneapi/ipp/2021.2.0/lib:/opt/intel/oneapi/dnnl/2021.2.0/cpu_iomp/lib:/opt/intel/oneapi/dal/2021.2.0/lib:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib/intel64_mac:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib")
```

**Comment by lebensterben** [comment] 2021-05-29 16:40
What shell are you using?
Are you using a input method when you're typing?
Are you using en-US keyboard layout?

**Comment by XushanLu** [comment] 2021-05-29 19:22
zsh.
I used ABC and Canadian English. That U.S. thing added to my keyboard does the same thing. So, I doubt this is a keyboard layout thing.

**Comment by lebensterben** [comment] 2021-05-29 20:31
When you press a key, its keycode is determined by the keyboard layout. 

Backspace is a special control character, and it should delete the last character and move the cursor back, providing that the terminal has the capabiility, as defined in termcap database. In other word, pressing backspace not necessarily does what you expected on very ancient terminal emulator or if termcap is not correct.

In vterm, what do you see for "echo $TERM"

**Comment by XushanLu** [comment] 2021-05-30 00:07
Thanks for the comments!

Nothing pops up when I type ''echo $TERM" (with the configuration taken place). It prints 'xterm-256color' when I comment that line out and restart Emacs.

BTW, each time I activate that line in the init file and run `SPC e f R`, Spacemacs seems to be installing a package called 'tern'. When I remove that line and restart Spacemacs, that package got deleted automatically on startup. What is that package doing and would it be possible for it to cause the problem that I am facing?

**Comment by lebensterben** [comment] 2021-05-30 00:14
Can you attach you .spacemacs here

**Comment by XushanLu** [comment] 2021-05-30 12:23
Sure!

[spacemacs_init.txt](https://github.com/syl20bnr/spacemacs/files/6566192/spacemacs_init.txt)

**Comment by lebensterben** [comment] 2021-05-30 21:57
the end of your . spacemacs is corrupted. there are two custom-set-variables and two custom-set-faces. That should be the cause why setting vterm-environment via easy-customization has no effect.

**Comment by lebensterben** [comment] 2021-05-30 22:01
According to https://github.com/akermu/emacs-libvterm#vterm-term-environment-variable

TERM defaults to xterm-256color and it should work correctly. Can you fix the . dotspacemacs first and try again?

**Comment by XushanLu** [comment] 2021-05-31 01:13
Thanks for pointing that out. I removed the last duplicated definitions and restarted my Spacemacs. I think the problem still persists. Backspace is not working as long as I have the variable `vterm-environment` defined in .spacemacs file.

**Comment by lebensterben** [comment] 2021-05-31 01:14
So you mean `echo $TERM` is still empty?

**Comment by lebensterben** [comment] 2021-05-31 01:17
btw you didn't set vterm-environment right.
(setq vterm-environment '(XXX))

**Comment by XushanLu** [comment] 2021-05-31 11:46
Sorry, I know nothing about Emacs lisp and I don't really know how to set the variables correctly.

You mean like this?
```lisp
  (setq vterm-environment '(DYLD_LIBRARY_PATH=opt/intel/oneapi/tbb/latest/env/../lib:/opt/intel/oneapi/mkl/latest/lib:/opt/intel/oneapi/ippcp/2021.2.0/lib:/opt/intel/oneapi/ipp/2021.2.0/lib:/opt/intel/oneapi/dnnl/2021.2.0/cpu_iomp/lib:/opt/intel/oneapi/dal/2021.2.0/lib:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib/intel64_mac:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib))
```
Or, should I include "" around the actual paths?

Without quotation marks, vterm is aware of the value and `echo $DYLD_LIBRARY_PATH` successfully prints the correct value. But, `echo TERRM` give me nothing.

With quotation marks, vterms does not print anything with `echo $DYLD_LIBRARY_PATH`, but it can give me the correct output for `echo $TERM` (xterm-256color).

**Comment by lebensterben** [comment] 2021-05-31 13:33
(setq vterm-environment '("VAR=VAL"))

**Comment by XushanLu** [comment] 2021-05-31 13:42
Okay, I did the following
```lisp
  (setq vterm-environment '("DYLD_LIBRARY_PATH=opt/intel/oneapi/tbb/latest/env/../lib:/opt/intel/oneapi/mkl/latest/lib:/opt/intel/oneapi/ippcp/2021.2.0/lib:/opt/intel/oneapi/ipp/2021.2.0/lib:/opt/intel/oneapi/dnnl/2021.2.0/cpu_iomp/lib:/opt/intel/oneapi/dal/2021.2.0/lib:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib/intel64_mac:/opt/intel/oneapi/compiler/2021.2.0/mac/compiler/lib"))
```
And when `echo $DYLD_LIBRARY_PATH`, nothing is printed. But, `echo $TERM` gives me xterm-256color.

**Comment by lebensterben** [comment] 2021-05-31 14:06
you didn't even use an absolute path

**Comment by lebensterben** [comment] 2021-05-31 14:10
what do you mean by when you set vterm-environment?

do you set it in .dotspacemacs?

have you started a new vterm buffer?

**Comment by XushanLu** [comment] 2021-05-31 14:47
My bad. Now I used the absolute path and nothing changes. I set it in dotspacemacs. Restarted Spacemacs and started a new vterm buffer. Still do not get the variable when `echo $DYLD_LIBRARY_PATH`. But `echo $TERM` returns the correct thing.

**Comment by lebensterben** [comment] 2021-05-31 14:58
That's impossible. I just tried and vterm can correctly set env variables.
I also read the source code and it LGTM.

Post your .spacemacs again

**Comment by XushanLu** [comment] 2021-05-31 15:06
[dotspacemacs.txt](https://github.com/syl20bnr/spacemacs/files/6571081/dotspacemacs.txt)

I don't think I can get it wrong following what you said. But please check this. Thanks.

**Comment by lebensterben** [comment] 2021-05-31 15:08
you get it very wrong. multiple serious issues.

**Comment by lebensterben** [comment] 2021-05-31 15:47
[dotspacemacs.txt](https://github.com/syl20bnr/spacemacs/files/6571279/dotspacemacs.txt)

**Comment by XushanLu** [comment] 2021-05-31 16:55
Well, I did an ediff comparison and I saw lots of changes you made in that file. Loaded the file with Spacemacs and I think it still works. However, when I try to open a vterm buffer and do `echo $DYLD_LIBRARY_PATH`, still nothing is printed.

I admit that I have not properly updated the dotspacemacs file since the first time I used Spacemacs (lazy enough that I only try to fix problems if the file stops working). Among the many things you changed, I noticed that you moved all the closing ')' back to the last line that it encloses (i.e., you do have ')' standing as a whole line). Is this just a personal preference or is this going to cause serious problems?

And if you don't mind, what was the most deadly problem for my original dotspacemacs file? Just too many modifications and I lost track of which one potentially can be a major issue.

Thanks very much for creating the new file.

**Comment by lebensterben** [comment] 2021-05-31 17:34
you should not have anything outside defun forms.

closing parentheses should not take a new line.

**Comment by lebensterben** [comment] 2021-05-31 17:36
report the issue to upstream.

**Comment by lebensterben** [comment] 2021-05-31 17:38
if the source code doesn't look pretty, it's just bug.

**Comment by XushanLu** [comment] 2021-05-31 17:41
Okay, that's good to know.

I have already did that and someone replied saying it has nothing to do with vterm and suggested using exec-path-from-shell which I believe should not be used if I am using Spacemacs: https://github.com/akermu/emacs-libvterm/issues/528

**Comment by lebensterben** [comment] 2021-05-31 17:51
you should tell them your (setq vterm-environment ...) doesn't work.

**Comment by lebensterben** [comment] 2021-05-31 17:52
you also should mentioned this is related to SIP.

Also you certainly can use exec-path-from-shell

**Closed** 2021-05-31 17:54 UTC
Labels: Not a bug 8-), Should report upstream, macOS
