### ISSUE TITLE
Default Spacemacs Theme No Longer Working in Terminal Emacs

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#8252] opened 2017-01-25 13:31 UTC
I am on another computer and I just updated Spacemacs to the latest develop. In the terminal window the default Spacemacs Dark theme no longer appears anymore by default. (probably it is the default Emacs theme instead) In the GUI app it works as normal, however. I am currently unable to use a bug template at the moment. Also I have set `TERM=xterm-256color` which got me the colors required before.

**Comment by jupl** [comment] 2017-01-25 13:40
Confirmed that at `9ac779a` the issue shows up. `spacemacs-theme` gets deleted.

**Comment by syl20bnr** [comment] 2017-02-02 04:27
@jupl should be fixed in develop, can you test it ?

**Comment by deathmaz** [comment] 2017-02-02 07:42
Works for me

**Comment by jupl** [comment] 2017-02-02 14:28
@syl20bnr Was sleeping. Second for working in develop.

**Comment by syl20bnr** [comment] 2017-02-02 23:31
Great, thank you for the confirmation.
Since this bug was introduced and fixed in develop we can close this issue.

**Closed by syl20bnr** 2017-02-02 23:31 UTC
Labels: - Bug tracker -, Core, Fixed in develop, High Priority, Regression :-(, Running in terminal, Themes

**Comment by lpenz** [comment] 2017-04-03 09:50
I'm seeing this issue, having just upgraded to 0.200.8. Maybe there was a regression of this fix?

**Comment by cweill** [comment] 2017-04-05 06:06
I can also confirm that it worked fine for 0.200.7, but once upgraded to 0.200.8, the default spacemacs theme launched with `emacs -nw` looks like this:


<img width="1440" alt="screen shot 2017-04-05 at 2 05 07 am" src="https://cloud.githubusercontent.com/assets/2343711/24691927/6223d60c-19a4-11e7-908c-56fa8ef40300.png">

**Comment by cweill** [comment] 2017-04-05 06:09
I can also confirm that after upgrading from 0.200.7 to 0.200.8, the default theme in the terminal launched via `emacs -nw` looks like this:

<img width="1440" alt="screen shot 2017-04-05 at 2 08 00 am" src="https://cloud.githubusercontent.com/assets/2343711/24692015/d419eb0c-19a4-11e7-8e86-1afceeaeb107.png">

**Comment by lpenz** [comment] 2017-04-05 13:04
`SPC t n` also doesn't work in terminal. spacemacs is stuck with default theme.

**Comment by cweill** [comment] 2017-04-05 17:04
Turns out, this is fixed on the `develop` branch. 

```sh
cd ~/.emacs.d
git checkout develop
emacs -nw
```
