### ISSUE TITLE
helm-resume binding gone since Ivy/Helm refactoring

### ISSUE THREAD

**Issue by lunaryorn** [syl20bnr/spacemacs#4592] opened 2016-01-13 10:38 UTC
Hello,

since the Ivy/Helm refactoring (https://github.com/syl20bnr/spacemacs/commit/813114efa142674a7109a6b92f66c66e6a37dba5#commitcomment-15419237 apparently, thanks @StreakyCobra) the `helm-resume` binding is gone.  

Would you mind to restore it?  It's a very important binding to me, particularly to resume a code search in the middle of some refactoring.  I very much dependent on this command.

Thank you

**Comment by syl20bnr** [comment] 2016-01-13 12:57
See my reply here: https://github.com/syl20bnr/spacemacs/commit/813114efa142674a7109a6b92f66c66e6a37dba5#commitcomment-15422671

For resume code search, there is better than `SPC h l` which can be replaced by another session, you can use `SPC s l` (or  `SPC r s` for `resume search` I will add soon).

**Comment by lunaryorn** [comment] 2016-01-13 13:22
@syl20bnr  Thank you for pointing me to `SPC s l`, and I'm curious to see and try the new `SPC r s` once it arrives.

Still, I'd love to have a Helm resume binding back.  Not specifically the old one, just anyone ("restore" was really the wrong word).  I don't mind if it's at a different place—my muscles can retrain—but I'd like to see it bound.

I'm using `helm-resume` for all sorts of things that involve Helm, like bringing back narrowly filtered file/buffer lists, or bringing back a previous `SPC i u` to insert the same character again, etc.

Well, I'm not only using `SPC s l` for code search, but also to generally resume sessions.  For instance, a narrowly filtered file/buffer list that I need again.

I

**Comment by tuhdo** [comment] 2016-01-13 13:31
I agree that `helm-resume` is an important command, once you get it and use it outside of text search.

**Comment by syl20bnr** [comment] 2016-01-13 13:35
I pushed the modifications. I attempted to keep the feeling of `SPC h l` by moving it to `SPC r l`, I believe it should be efficient enough for such an important key binding.

The resume of the modifications:

- All helm related key bindings under ~SPC h~ that are not about help have
  moved to different key bindings:
  - ~SPC h b~ for =helm-filetered-bookmarks~is now ~SPC f b~
  - ~SPC h l~ for =helm-resume= is now ~SPC r l~
  - ~SPC h L~ for =helm-locate-library= is now ~SPC s L~

I have yet to move `helm-switch-major-mode` (which I never used, smex is ok enough). Maybe I can just remove it.

**Comment by syl20bnr** [comment] 2016-01-13 13:42
Note that `SPC s l` is still here, I let it because it is a home row sequence so hard to beat in efficiency, but I still added `SPC r s` for resume search.

**Comment by lunaryorn** [comment] 2016-01-13 13:47
@syl20bnr Thank you very much.  `SPC r l` is fine for me.

However, I'd have expected `helm-locate-library` under `SPC f L`, to be honest, since it opens a file, albeit a "library" file.

As for `helm-switch-major-mode`, is that even frequently used?  I didn't even know that it existed until now.  I just used `M-x` to switch major modes, and having tried `helm-switch-major-mode` I don't see it's use over `M-x`, except that it shows less candidates.

**Comment by syl20bnr** [comment] 2016-01-13 14:09
Could be moved to `SPC f C-S-l`, both `f l` and `f L` are taken.

> having tried helm-switch-major-mode I don't see it's use over M-x, except that it shows less candidates.

Same here, I guess I can remove them.

**Comment by lunaryorn** [comment] 2016-01-13 14:13
@syl20bnr Ah, ok.  I didn't know that.

**Comment by StreakyCobra** [comment] 2016-01-13 14:24
`SPC s L` for **s**earch **L**ibrary is fine too and easier than `SPC f C-S-l` IMHO.

**Comment by syl20bnr** [comment] 2016-01-13 21:17
Technically it is for opening a file so it should be under `SPC f`.
Since it is a not very frequent key binding `SPC f C-S l` can be acceptable.
`SPC s` for search is more about searching into files.

What is your locate library frequency ?

Oh I have an idea, `SPC f e l`, it is free !!

**Comment by StreakyCobra** [comment] 2016-01-13 21:32
> What is your locate library frequency ?

Let's say twice a day, to look at packages' code for debugging or information.

> Oh I have an idea, SPC f e l, it is free !!

`SPC f e l` is fine. `SPC f C-S-l` is just too much fingers at the same time. vim's modal editing is nice because it avoid RSI due to this kind of keystrokes, so… if it could be avoided ;-)

**Comment by nixmaniack** [comment] 2016-01-14 05:12
Please no for `SPC f C-S-l`. I use locate library quite often! `SPC f e l` is much better.

**Comment by lunaryorn** [comment] 2016-01-14 10:30
@syl20bnr `SPC f e l` would be fine.

**Comment by StreakyCobra** [comment] 2016-01-26 15:30
`helm-locate-library` is on `SPC f e l` now and `helm-resume` is on `SPC r l`. I think the issue is fixed and can be closed. If this is not the case let me know, I'll reopen.

**Comment by StreakyCobra** [comment] 2016-01-26 15:31
Hum, not sure if this is already in `master`, let me check ^^

**Closed by StreakyCobra** 2016-01-26 15:30 UTC
Labels: Key Bindings, regression :-(
