### ISSUE TITLE
markdown-cycle is shadowed by evil-jumper/forward

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#4487] opened 2016-01-08 02:31 UTC
When writing markdown, the `TAB` key is very useful for hiding the details of a heading, but the `TAB` key is binded to `evil-jumper/forward`.

@justbur

**Comment by justbur** [comment] 2016-01-08 20:37
Use `(evil-define-key 'normal markdown-mode-map (kbd "TAB")
'markdown-cycle)`

**Comment by syl20bnr** [comment] 2016-01-08 20:43
hummm this binding is strange, why `TAB` would be `evil-jumper` ?
Oh.... `C-i` of course... :-)

**Comment by syl20bnr** [comment] 2016-01-08 20:45
This is weird, I believed that this change was an unmerged PR and I don't see it in the recent commits.

**Comment by syl20bnr** [comment] 2016-01-08 20:45
Indeed: https://github.com/syl20bnr/spacemacs/pull/4448

**Comment by syl20bnr** [comment] 2016-01-08 20:46
This PR needs to be merged so ?

cc @TheBB

**Comment by TheBB** [comment] 2016-01-08 20:54
Would #4448 really help with this?

**Comment by TheBB** [comment] 2016-01-08 20:55
In #4448 I bind `<C-i>` but leave `TAB` alone. Should I remove `TAB`?

**Comment by TheBB** [comment] 2016-01-08 21:05
I tried removing the `TAB` binding but it didn't seem to fix this issue for me.

**Comment by justbur** [comment] 2016-01-08 21:18
We demoted evil-jumper to the evil-motion-state-map, so C-i and TAB are used by evil jumper in that map. This map currently has higher priority than the markdown-mode-map, explaining the shadowing here. It's up to you to decide what to do about it. 

In the gui only, `(define-key markdown-mode-map [tab] 'markdown-cycle)` will "promote" the binding. My solution above also works. A little more extreme is to do `(evil-make-overriding-map markdown-mode-map 'normal)`, which will promote all bindings in that map above evil-motion-state-map. There might be a couple of more options.

**Comment by TheBB** [comment] 2016-01-08 21:27
Okay, thanks for the explanation.

There are some people on gitter having the same problem with org-mode, but I can't reproduce. (I can repro the markdown issue.)

**Comment by syl20bnr** [comment] 2016-01-08 21:32
The heart of the issue here is to use `C-i` for a global binding, no matter what we do we won't be able to get a consistent behavior between the GUI, the terminal and even in Spacemacs itself.

We have to remove `C-i` for evil-jumper and find another key binding.

**Comment by justbur** [comment] 2016-01-08 21:34
@syl20bnr That's not right exactly. This is from evil-maps.el
```elisp
(when evil-want-C-i-jump
  (define-key evil-motion-state-map (kbd "C-i") 'evil-jump-forward))
```
and we have that var `t`

**Comment by syl20bnr** [comment] 2016-01-08 21:36
:-)
So we can set it to nil and find another binding for it.

**Comment by justbur** [comment] 2016-01-08 21:37
that will work :smile:

**Comment by TheBB** [comment] 2016-01-08 21:42
`C-S-o`? It's vaguely reminiscent of `n` and `N`.

`C-k` is also pretty close to `C-o` and appears to be free.

**Comment by syl20bnr** [comment] 2016-01-08 21:52
I would go for `C-S-o`

**Closed** 2016-01-09 18:26 UTC
Labels: Git, Key Bindings
