### ISSUE TITLE
mini buffer is hiding other windows

### ISSUE THREAD

**Issue by gopakumar** [syl20bnr/spacemacs#16317] opened 2024-03-21 00:26 UTC
https://github.com/syl20bnr/spacemacs/assets/498116/3d1ff2fa-a95a-407d-9384-e453f7cbb1e5

#### Description :octocat:
minibuffer is hiding all other windows

#### Reproduction guide :beetle:
- Start Emacs
- create 3-4 windows using C-x 3, C-x 3, C-x 3
- invoke mini buffer by M-x
- 

*Observed behaviour:* :eyes: :broken_heart:
you can see, when the minibuffer is open its hiding all the windows except that active one

*Expected behaviour:* :heart: :smile:
mini buffer should open without hiding all the other windows

#### System Info :computer:
- OS: darwin
- Emacs: 29.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 4a227fc94)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bcc32** [comment] 2024-03-21 02:41
I can't reproduce with those layers.  Is there maybe something else in your config that might be responsible?  (For example, do you still get this problem if you move your `.spacemacs` to `.spacemacs.bak` and start with the default settings?)

**Comment by gopakumar** [comment] 2024-03-21 02:52
issue is only there  if we install spacemacs-base. 
I used default settings. no addition packages or configs added/chaged

**Comment by bcc32** [comment] 2024-03-21 03:30
Ah, I see, and I was able to reproduce this.

This is helm's default behavior, and is expected.  If you enable the `spacemacs-completion` layer (which sets the `helm-display-function` variable), it changes this behavior to stop closing the other windows.

**Comment by gopakumar** [comment] 2024-03-21 03:53
Issue resolved after adding the `spacemacs-completion` layer. Thank you very much for the help

**Closed as completed** 2024-03-29 22:54 UTC
