### ISSUE TITLE
Spacemacs gets into bad mode and `d` acts as if `dd` is pressed

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#12664] opened 2019-08-26 17:13 UTC
#### Description :octocat:
Occasionally, spacemacs gets into a state where typing `d` acts as if I'm typing `dd` and `c` acts
as if I'm typing `cc`.

Once in this state, I have to restart to restore the expected behavior.

#### Reproduction guide :beetle:
- Start Emacs
I do not know what causes this behavior.

*Observed behaviour:* :eyes: :broken_heart:
Typing `d` will delete an entire line.
Typing `c` will change an entire line.

If you highlight a block of text with visual mode, typing `d` will just delete the first line.

*Expected behaviour:* :heart: :smile:
Typing `d` should wait for more input. Typing `d` when in visual mode should delete the block.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e2d9e32e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go swift csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown major-modes python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
    (version-control :variables version-control-diff-tool 'diff-hl)
    (c-c++ :variables c-c++-enable-clang-support t)
    (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by tko** [comment] 2019-08-27 11:00
Possible duplicate of https://github.com/syl20bnr/spacemacs/issues/10410 and/or https://github.com/syl20bnr/spacemacs/issues/11536

**Comment by duianto** [comment] 2019-08-29 11:29
`tko`  seems to be correct, it sounds like issue:
Evil search bug breaks Spacemacs #10410

The most up voted workaround can be found in this comment:
#10410 (comment)

**Closed** 2019-12-22 06:46 UTC
Labels: - Bug tracker -, Duplicate ☝, Evil, Mini-buffer
