### ISSUE TITLE
Global keybindings for starting REPLs

### ISSUE THREAD

**Issue by izahn** [syl20bnr/spacemacs#3395] opened 2015-10-14 15:21 UTC
I would like to have global keybindings for starting REPL processes in spacemacs. Currently this exists for shells/terminals, but not for other REPLs. I'm opening this as an issue for discussion because it's not clear to me what the best way forward is. Should this be implemented in each layer providing a REPL and the keybindings coordinated among them so as not to conflict? Or should bindings be implemented in a centralized location to make such coordination easier? What I'm envisioning is something like 

| Key binding   | Description      |
|---------------|------------------|
| ~SPC ‘~  	    | default shell    |
| SPC a s e	    | eshell           |
| SPC a s i	    | shell            |
| SPC a s m	    | multi-term       |
| SPC a s t	    | ansi-term        |
| SPC a s l	    | cidar            |
| SPC a s R	    | R                |
| SPC a s p	    | python           |
| SPC a s j	    | julia            |
| SPC a s E	    | ielm             |
| SCP a s r     | ruby             |

Or perhaps a new category (p for "process")

| Key binding   | Description      |
|---------------|------------------|
| SPC a p e	    | eshell           |
| SPC a p i	    | shell            |
| SPC a p m	    | multi-term       |
| SPC a p t	    | ansi-term        |
| SPC a p l	    | cidar            |
| SPC a p R	    | R                |
| SPC a p p	    | python           |
| SPC a p j	    | julia            |
| SPC a p E	    | ielm             |
| SCP a p r     | ruby             |

Thoughts?

**Comment by syl20bnr** [comment] 2015-10-14 17:32
The spacemacs way is to implement those key bindings in each layer.
But in this case I would go for a unique key bindings that triggers a helm buffer with all the available REPLs. This list is populated by each layer in the appropriate init function.

**Comment by izahn** [comment] 2015-10-14 18:14
Yeah, a helm buffer with the available REPLs would be awesome! I'll take a shot at it and see if I can get something working.

**Comment by AlejandroCatalina** [comment] 2016-01-13 09:15
How could I collect all the available REPLs? I'm trying to address this and I'd appreciate some help and thoughts to face the issue. Thanks!

**Comment by StreakyCobra** [comment] 2016-01-13 09:26
Manually you can search for all `"si"` instances in the code, as it's by [convention](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#send-code) the keybinding to open a REPL. Automatically… I don't know if there is a way.

**Comment by AlejandroCatalina** [comment] 2016-01-13 09:30
So, I'm thinking of checking all keymaps (if they are referenced somehow in evil) looking for "si" keychords. If found, return that REPL. Sounds good?

**Comment by StreakyCobra** [comment] 2016-01-13 09:48
The problem you will have is that the shortcut is `msi`, and it's bound to a major-mode keymap. So you'll need a way to know what are those major-mode keymaps. But probably @justbur has a solution :-)

**Comment by AlejandroCatalina** [comment] 2016-01-13 09:58
Yes, I'll probably need that. I was thinking of something like
```elisp
(mapcar (lambda (keymap)
          (when (mapcar (lambda (binding)
                          (when (string= binding "si")
                             binding))
                       keymap-bindings)
              keymap))
        evil-keymaps)
```
And I would need to figure out how to get `evil-keymaps` and `keymap-bindings` or whatever their names are.

**Comment by AlejandroCatalina** [comment] 2016-01-13 11:41
I have been working on this and I have made some progress.

I am able to inspect the current active keymaps and look for a keybinding that matches `SPC m s i`. The problem is that I need to iterate through all major-modes to inspect every one and collect a list of all REPLs, and this means that every major-mode will load its packages, what will make this a little slow, and I would need to find a list or a way to iterate through all major-modes available.

If you guys know about other way to check the major-modes keymaps please tell me :D.

**Comment by StreakyCobra** [comment] 2016-01-13 11:50
Finally I think the best way would be to create manually the list of REPLs. You'll need to bind the REPLs to keys manually in order to have them documented in any way.

**Comment by AlejandroCatalina** [comment] 2016-01-13 11:57
I agree with that, it'll be a way simpler. I'm going with that approach.

**Comment by justbur** [comment] 2016-01-13 15:15
In case it's useful here's a list of major-modes that have keys bound for them and their associated maps in spacemacs
```elisp
(mapcar
 (lambda (entry)
   (list (cadr entry) (intern (format "spacemacs-%s-map" (cadr entry)))))
 bind-map-major-modes-alist)
```

**Comment by StreakyCobra** [comment] 2016-01-13 15:21
@justbur It only works for activated layers right?

**Comment by AlejandroCatalina** [comment] 2016-01-13 15:23
I'm looking into it. So far I've built the list manually, but I'd like to do it this way. The only thing we are not going to be able to avoid is loading at least the mode of the repl we want to launch.

**Comment by justbur** [comment] 2016-01-13 15:24
@StreakyCobra `spacemacs/set-leader-keys-for-major-mode` adds an entry to this list, so it only includes entries for packages that have used that function already.

**Comment by AlejandroCatalina** [comment] 2016-01-13 16:08
Well, after trying that snippet out, I don't see it useful for this purposes for one reason.
* `spacemacs/set-leader-keys-for-major-mode` is evaluated once the major-mode is initialized, which won't happen until I open a file or a buffer with that mode, so we won't have a truly complete list of REPLs until every mode has been entered. 

This, IMO, is a problem in case I want to open, for instance, an ipython REPL without having entered a python file yet. So I'm going for creating a list where I store a string to show in the helm buffer and a cons containing the major-mode needed and the function to run the REPL, so I basically set up the major-mode before running the repl, if it's not already featured.

That list would be,
```elisp
(setq repls '(("sml" . (sml-mode . run-sml))
              ("ocaml" . (tuareg-mode . utop))
              ("python" . (python-mode . python-start-or-switch-repl))
              ("emacs-lisp" . (emacs-lisp-mode . ielm))
              ("ruby" . (ruby-mode . robe-start))
              ("scheme" . (scheme-mode . geiser-mode-switch-to-repl))
              ("octave" . (octave-mode . run-octave))
              ("elm" . (elm-mode . elm-repl-load))
              ("sql" . (sql-mode . spacemacs/sql-start))
              ("idris" . (idris-mode . idris-ensure-process-and-repl-buffer))
              ("ess-julia" . (ess-julia-mode . julia))
              ("ess" . (inferior-ess-mode . spacemacs/ess-start-repl))
              ("elixir" . (elixir-mode . alchemist-iex-run))
              ("clojure" . (clojure-mode . cider-jack-in))
              ("clojureScript" . (clojure-mode . cider-jack-in-clojurescript))
              ("racket" . (racket-mode . racket-repl))
              ("scala" . (scala-mode . ensime-inf-switch))
              ("fsharp" . (fsharp-mode . fsharp-show-subshell))
              ("common-lisp" . (common-lisp-mode . slime))
              ("purescript" . (purescript-mode . psci))))
```
Does this sound right?

I still need a way to ensure that the package is installed, though it hasn't been loaded yet.

**Comment by justbur** [comment] 2016-01-13 16:12
@AlejandroCatalina How about this? Write a function called something like `spacemacs/register-repl` that is each layer's responsibility to use if you want that layer's repl to show up in your list. Seems simpler than trying to maintain a list manually and/or guess where the repl is bound.

**Comment by AlejandroCatalina** [comment] 2016-01-13 16:16
That sounds cleaner, we'll have to add it to the :init section of the use-package macro to have it executed in load time.

This way we ensure that the package is installed, I like it.

What would be a good keybinding to launch the helm buffer to choose a REPL to run? `SPC h R`?

**Comment by justbur** [comment] 2016-01-13 16:20
> What would be a good keybinding to launch the helm buffer to choose a REPL to run? SPC h R?

Should be under `SPC a` I think

**Comment by AlejandroCatalina** [comment] 2016-01-13 16:23
`SPC a r` sounds good then, it's not used and it's mnemonic of "REPL".

Where would be the right place to define this function `spacemacs/register-repl`? I've thought to define it in config.el in +distribution/spacemacs.

**Comment by StreakyCobra** [comment] 2016-01-13 18:03
I don't like to kill the mood, but… https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/ranger/packages.el#L21

**Comment by AlejandroCatalina** [comment] 2016-01-13 20:24
Okay, let's set it on `SPC a R`

**Comment by AlejandroCatalina** [comment] 2016-01-13 20:29
I'm PRing it, let's discuss any remaining stuff over there. By the way, I didn't register any current REPL in this PR, but I intend to do it after this PR is okay.

**Comment by StreakyCobra** [comment] 2016-01-13 21:21
@AlejandroCatalina Do you want to play a game? :smiley:

https://github.com/syl20bnr/spacemacs/blob/develop/layers/speed-reading/packages.el#L29

Try again :wink:

**Comment by AlejandroCatalina** [comment] 2016-01-13 21:24
Oh god, let's decide which key-binding is best in the PR :joy:

**Comment by nixmaniack** [comment] 2016-01-14 05:19
You know what, we should have something like [`describe-personal-keybindings`](https://github.com/jwiegley/use-package/blob/2a50241538b8ead3d620be33bd8e0087f98f42c5/bind-key.el#L88-L92), `describe-spacemacs-keybindings` sounds good. This would give us much better picture while deciding for new keybindings by listing all used bindings. 

@justbur might have an idea of getting this list.

**Comment by justbur** [comment] 2016-01-14 12:32
@nixmaniack This wouldn't be that hard, because most key bindings are defined in `spacemacs-default-map`. The only difficulty is to decide whether you want to see the bindings from all layers which would (at the moment) require loading all layers.

**Comment by AlejandroCatalina** [comment] 2016-01-14 13:43
Yep, that was the exact problem I encountered while working that approach.

**Comment by syl20bnr** [comment] 2016-01-14 13:45
It is even worth than loading all the layers, to be guaranteed to see all the key bindings reliably all the major modes should be loaded due to lazy loading and due to key bindings being set in `:config` (which is a good thing IMO).


I don't think auto loading in Emacs is adapted for such feature. But this is no big deal because we have a community to review and choose bindings :-)

**Comment by syl20bnr** [comment] 2016-01-14 13:47
A search for the key sequence in the code base is most of the time enough.

**Comment by izahn** [comment] 2016-02-09 17:55
As the person who opened this issue I consider it fixed since I normally run the develop branch. Should I close it or leave it open until this makes it's way into master?

**Comment by syl20bnr** [comment] 2016-02-09 18:31
You can close it :-)

**Closed** 2016-02-09 18:35 UTC
Labels: enhancement :-D, Fixed in develop, Key Bindings, REPL
