### ISSUE TITLE
Several functions produce "Lisp nesting exceeds `max-lisp-eval-depth'" in the mini-buffer

### ISSUE THREAD

**Issue by oantolin** [syl20bnr/spacemacs#3950] opened 2015-11-24 21:01 UTC
I just tried spacemacs for the first time today on GNU Emacs 24.3.1. Installation seemed to go well (I picked the "evil flagship" and "standard distribution" options), and when I restarted Emacs I could open a file and edit using the Evil bindings I remembered from my evil days. But when I tried to see a list of layers (`SPC f e h`) or get a helm buffer with keybindings (`SPC h d b`), all I got was the message "Lisp nesting exceeds `max-lisp-eval-depth'" in the minibuffer.

This happened after initial installation, before I added any layer of my own or configured anything in any way.

Maybe Emacs 24.3 is just too old for spacemacs, if so, ignore this, but otherwise, I have to say I didn't have a very encouraging first experience. :)

What other information might it be useful for me to provide?

**Comment by oantolin** [comment] 2015-11-24 21:12
Just reinstalled, most things still seems broken: trying to look at `.spacemacs` using `SPC f e d` gave me the error message "Variable binding depth exceeds `max-specpdl-size`", but oddly did manage to open the file anyway; scrolling with the mouse-wheel also produces the binding depth message and fails to scroll; `SPC b b` also just gives the "Lisp nesting exceeds `max-lisp-eval-depth'" error message.

**Comment by StreakyCobra** [comment] 2015-11-28 11:59
I remember having seen this once and it was a bug that has been corrected in the meantime. Can you try to update spacemacs to the last release, and update the packages?

**Comment by oantolin** [comment] 2015-11-28 18:28
I'll try again when I'm at that computer again, on Monday. When I installed Spacemacs I ran `git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d`, then started Emacs, let Spacemacs install a bunch of packages, and then restarted Emacs. I thought that would get me the latest version of Spacemacs and up to date packages, is that not the case?

If I'm correct I had what was the latest version of Spacemacs 20 minutes before I opened the issue.

**Comment by StreakyCobra** [comment] 2015-11-28 19:01
Packages are stored in `.emacs.d/elpa`, so when this folder is removed, all packages are reinstalled from the repositories and thus are indeed in their last version. But for updating packages there is a button on the Spacemacs home buffer. It's easier, quicker and safer as it can be rollback'ed.

So if you installed it just before, the problem is indeed probably emacs 24.3.

**Comment by oantolin** [comment] 2015-11-30 23:27
Well, as promised I tried again at the computer I use Emacs 24.3 on. The same thing happened. I again reinstalled completely (removing my `~/.emacs.d` first). Clicking on the Update button in the welcome buffer also gives the "Variable binding depth exceeds `max-specpdl-size`" message, by the way.

**Comment by StreakyCobra** [comment] 2015-11-30 23:49
Ok, so it's probably 24.3 related. Sadly I can't find a way to run this version. Can you try to give a complete backtrace?

Use `emacs --debug-init` to run it and the backtrace should pop up. If it's not at init time, use `SPC t D` to toggle the debug mode then do an action that throws the error. Finally copy/paste here (or on a gist/pastbin/etc.) the content of `*Backtrace*` buffer.

**Comment by justbur** [comment] 2015-11-30 23:53
@StreakyCobra just a side note. In spacemacs `emacs --debug-init` leaves debug-on-error on after init

**Comment by StreakyCobra** [comment] 2015-12-01 00:10
Oh, so no need of `SPC t D` then :-) Thx @justbur :+1:

**Comment by oantolin** [comment] 2015-12-01 03:20
I'm sorry, I failed! I was able to `toggle-debug-on-error` (and got a message in the mini-buffer saying debug-on-error was enabled) but using the commands that result in the error messages I described above did not pop up a `*Backtrace*` buffer.

I thought maybe the buffer was being created but not displayed for some reason and tried switching to it, but I can't use any buffer switching commands! I tried `SPC b b` (which I think runs `helm-mini`), and I tried `C-x b` (which runs `ido-switch-buffer` in spacemacs) and I tried running `ibuffer` and `switch-to-buffer` from the colon prompt and by using `M-x`. All of these methods produced one of the two error messages I mentioned and did not let me switch buffers!

**Comment by StreakyCobra** [comment] 2015-12-01 09:21
Hum, I need to find a way to run emacs 24.3 then :-/

**Comment by syl20bnr** [comment] 2016-06-21 02:43
We dropped support for 24.3 in develop branch so I mark this as "fixed" in develop :-)

**Comment by commit** [comment] 2016-08-31 19:59
This is reproducible on CentOS 7.2 (the current release), which uses emacs-24.3-18.el7.

I'm not sure if CentOS or RHEL is planning to upgrade to a newer version of Emacs anytime soon, so any chance on a backport?

**Comment by TheBB** [comment] 2016-08-31 20:17
Isn't it simpler just to compile a newer version on those operating systems?

**Comment by commit** [comment] 2016-09-01 14:46
Thanks.  You would not believe the @commit spam I get from random Github users.

Compiling Emacs 25.1-rc2 was straightforward, and spacemacs is working fine for me now on CentOS.  I just hate to install things outside the package manager.

**Comment by danieloosthuizen** [comment] 2016-09-03 19:52
With Emacs 24.5.1, I've got the same problem, and I too have isolated it to the `org` layer.

    Variable binding depth exceeds max-specpdl-size

Since Spacemacs doesn't *officially* support Emacs 25 yet (as per the read-me – correct me if I'm wrong), I'd rather not switch, unless Emacs 25 works just as well as 24 with Spacemacs.

**Comment by danieloosthuizen** [comment] 2016-09-10 15:17
Ok, well, I did a reinstall of my system, and it's now working again with Emacs 24.5.1. I'll tell you if anything changes.

**Comment by d12frosted** [comment] 2016-10-03 09:14
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 09:14 UTC
Labels: Bug :-(, Emacs 24.3, Fixed in develop
