### ISSUE TITLE
Quitting `org-present` breaks evil-bindings  

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#3961] opened 2015-11-26 05:46 UTC
to reproduce: 

- open/create a buffer in org-mode with a list of things
- enable `org-present` - `M-x org-present` 
- try navigating between slides - `h` and `l`
- quit `org-present` - `q`
- try to use evil bindings, like `i` or `dd`

re-enabling `org-mode` fixes it. Maybe it should be added/fixed in `org-present-mode-quit-hook`

**Comment by StreakyCobra** [comment] 2015-11-26 09:40
Duplicate of #1874

**Closed** 2016-06-15 22:45 UTC
Labels: Bug :-(, Core, Duplicate ☝, Evilified
