### ISSUE TITLE
SPC s j stops working in org-mode

### ISSUE THREAD

**Issue by deech** [syl20bnr/spacemacs#5444] opened 2016-03-10 19:50 UTC
#### Description
Just made a fresh clone of Spacemacs and SPC s j in an org file whicch used to bring up imenu and allow me to search headlines now gives:
apply: Wrong number of arguments: #[(&optional with-self use-cache) **"~**

#### Reproduction guide
- Start Emacs
- Open an org file with headlines
- SPC s j to search headlines

*Observed behaviour:*
SPC s j does not show a menu of headlines instead I get:
apply: Wrong number of arguments: #[(&optional with-self use-cache) "~

*Expected behaviour:*
SPC s j should show a menu of headlines.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion haskell git scala emacs-lisp shell magit-extras)
```

**Comment by NJBS** [comment] 2016-03-10 21:37
Duplicate of https://github.com/syl20bnr/spacemacs/issues/5441

See https://github.com/emacs-helm/helm/issues/1421 for the issue which was reported upstream

**Comment by StreakyCobra** [comment] 2016-03-10 22:07
Closing as duplicate

**Closed by StreakyCobra** 2016-03-10 22:07 UTC
Labels: Duplicate ☝
