### ISSUE TITLE
spacemacs hangs on boot

### ISSUE THREAD

**Issue by vigilancetech-com** [syl20bnr/spacemacs#8941] opened 2017-05-22 17:22 UTC
#### Description :octocat:
spacemacs hangs on boot
#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
hangs saying "Indexing layers..." with loading auto-layer.el... done in the minibuffer.

After breaking out, spacemacs keys don't work, and ordinary emacs keys do unexpected things.

*Expected behaviour:* :heart: :smile:
boots normally
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm rcirc ranger forth windows-scripts auto-completion better-defaults emacs-lisp git markdown themes-megapack org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control)
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) (arg) "Open a spacemacs/report-issue-mode buffer prepopulated with
   issue report template and system information.

   With prefix arg,include the last keys pressed." (interactive "P") (let ((buf (generate-new-buffer "REPORT_SPACEMACS_ISSUE")) (system-info (spacemacs//describe-system-info-string)) (backtrace (if (get-buffer "*Backtrace*") (save-current-buffer (set-buffer "*Backtrace*") (buffer-substring-no-properties (point-min) (min (point-max) 1000))) "<<BACKTRACE IF RELEVANT>>")) (last-keys (if (and arg (y-or-n-p (concat "Do you really want to " "include your last pressed keys? It " "may include some sensitive data."))) (concat (spacemacs//describe-last-keys-string) "
") ""))) (switch-to-buffer buf) (insert-file-contents-literally (concat configuration-layer-template-directory "REPORTING.template")) (loop for (placeholder replacement) in (list (list "%SYSTEM_INFO%" system-info) (list "%BACKTRACE%" backtrace) (list "(%LA
```

**Comment by tonycai653** [comment] 2017-07-10 04:16
I also have the same issues on spacemacs on kde4.

**Comment by carlosvigil** [comment] 2017-07-26 02:21
same issue on Ubuntu and macOS

**Comment by cpaulik** [comment] 2017-08-08 16:11
I've got the same problem on the latest develop with latest packages. Any ideas on how to debug this?

**Comment by cpaulik** [comment] 2017-08-08 16:21
Ok. The process monitor tells me that emacs is running a subprocess calling `/bin/bash -i -l -c /usr/bin/printf'__RESULT\000%s\000%s\000__RESULT' "${PATH-8404ba553e69055188f963ce51c06f01}" "${MANPATH-8404ba553e69055188f963ce51c06f01}"`

**Comment by d12frosted** [comment] 2017-08-08 16:24
@cpaulik I wonder if it's related to `exec-path-from-shell`?

**Comment by cpaulik** [comment] 2017-08-08 16:31
Yes, I just set `(setq exec-path-from-shell-arguments '("-c"))` in my `dotspacemacs/user-init` and this solved the problem. 

See also https://github.com/purcell/exec-path-from-shell/issues/33
and https://github.com/syl20bnr/spacemacs/issues/3887

**Comment by cpaulik** [comment] 2017-08-08 16:35
But what I find very strange is that everything worked until I updated the lisp packages. So I really doubt that it is an platform or shell configuration issue. Especially since the latest `exec-path-from-shell` package is from the 8th of May.

**Comment by d12frosted** [comment] 2017-08-09 08:24
@cpaulik yeah, that sounds strange. But if it worked before and doesn't work now, then something has changed in your setup. 

Ok, so there are two possible workarounds:

- Exclude `exec-path-from-shell`
- Add `(setq exec-path-from-shell-arguments '("-c"))` to `dotspacemacs/user-init` function.

Anyway, it seems that this is a duplicate of #3887. Closing this one for now.

P. S. Thanks @cpaulik for the links.

**Closed** 2017-08-09 08:25 UTC
Labels: - Bug tracker -, Duplicate ☝, Kills Kittens (=^-^=), Loading, Unresponsive

**Comment by cpaulik** [comment] 2017-08-09 08:56
Thanks. This might be related to `pyenv`. I've updated it in the meantime and everything is back working. Although slower startup since `exec-path-from-shell` seems to be doing its job again.

**Comment by 00krishna** [comment] 2017-10-31 15:26
Hey Folks and @cpaulik , just a bit of caution. So I tried this solution with `(setq exec-path-from-shell-arguments '("-c")) `. That seemed to fix the indexing issue. But when I had to delete and reclone spacemacs, I started getting an error about `Symbol's function definition is void: exec-path-from-shell-copy-env`. 

Turns out that `exec-path-from-shell` is a base package in spacemacs. So the line `(setq exec-path-from-shell-arguments '("-c")) ` added a line to the dotfile that added `exec-path-from-shell` to the list of excluded packages. 

So once I removed that line everything started working in emacs again.

So there are some unintended consequences to this solution--atleast for some users. 

Might want to consider reopening this issue. Just a suggestion, but up to you guys.

**Comment by Martinsos** [comment] 2021-04-27 15:26
I am still experiencing this issue. Sometimes, it gets stuck on "indexing layers...", forever . I quit emacs and re-enter it couple of times and then it works. I am on current develop branch, and I just reinstalled emacs completely recently and problem is still here.
I am on Archlinux.
