### ISSUE TITLE
Spacemacs complains about setting environment variables ("PATH" "MANPATH") in .bashrc or .zshrc eventhough I use .zshenv

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#8201] opened 2017-01-18 12:13 UTC
Does anyone else have this problem?

**Comment by d12frosted** [comment] 2017-01-18 12:34
Are you talking about something like following warning?

```
You appear to be setting environment variables ("PATH" "MANPATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .profile, .bash_profile or .zshenv.  Refer to your shell’s man page for more info.  Customize ‘exec-path-from-shell-arguments’ to remove "-i" when done, or disable ‘exec-path-from-shell-check-startup-files’ to disable this message.
```

If so, it's a duplicate of https://github.com/syl20bnr/spacemacs/issues/3920.

**Comment by deb0ch** [comment] 2017-01-18 12:38
https://github.com/syl20bnr/spacemacs/issues/7780, https://github.com/syl20bnr/spacemacs/pull/6625 as well :smile_cat:

**Comment by adamczykm** [comment] 2017-01-19 00:21
Bump

**Comment by d12frosted** [comment] 2017-01-31 15:32
Closing as duplicate.

**Closed by d12frosted** 2017-01-31 15:32 UTC
