### ISSUE TITLE
Warning (emacs): Unrecognized key: _X_

### ISSUE THREAD

**Issue by zwb-ict** [syl20bnr/spacemacs#7581] opened 2016-10-28 14:41 UTC
#### Description :octocat:
Warning (emacs): Unrecognized key: _X_

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
will see: Warning (emacs): Unrecognized key: _X_

*Expected behaviour:* :heart: :smile:
no warning

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: develop (rev. 4bf8e52)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(erc
 (syntax-checking :variables syntax-checking-enable-tooltips t)
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete)
 helm ivy nginx better-defaults
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (org :variables org-enable-github-support t)
 semantic ruby-on-rails
 (chinese :variables chinese-enable-fcitx t)
 c-c  
 (clojure :variables clojure-enable-fancify-symbols t)
 emacs-lisp erlang
 (go :variables gofmt-command "goimports")
 haskell html
 (javascript :variables javascript-disable-tern-port-files nil)
 latex lua markdown
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm ruby-test-runner 'rspec)
 (rust :variables rust-enable-rustfmt-on-save t)
 scala shell-scripts yaml osx floobits
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
 github
 (version-control :variables version-control-diff-tool 'git-gutter  version-control-global-margin t)
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 cscope
 (gtags :disabled-for go)
 ahei
 (dash :variables helm-dash-docset-newpath "~/Library/Application Support/Dash/DocSets")
 docker fasd imenu-list ranger
 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/local/bin/zsh")
 tmux vagrant
 (ycmd :variables ycmd-server-command
       '("python" "/Users/zwb/.bin/ycmd/ycmd")
       ycmd-force-semantic-completion t)
 evernote blog gtd zwb)
```
- System configuration features: IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by TheBB** [comment] 2016-10-28 14:44
Is this reproducible with default config?

**Comment by 0xkag** [comment] 2016-10-28 20:57
I'm getting this error at startup too:

`
Warning (emacs): Unrecognized key: _X_
`

It happened on develop sometime between 200fb764aa11a1ec44bdd0af9c21dddf60f45ce3 and 4bf8e529b82302c0aa0dfbb6d8feccfe9a4e2606.

Linux.  Emacs 24.5.1.  Layers:

     ansible
     asciidoc
     (auto-completion :variables
                      auto-completion-complete-with-key-sequence nil
                      auto-completion-enable-help-tooltip t
                      auto-completion-return-key-behavior 'complete
                      auto-completion-tab-key-behavior 'cycle
                      company-show-numbers t)
     better-defaults
     c-c++
     (colors :variables
             colors-enable-rainbow-identifiers t)
     elfeed
     emacs-lisp
     eyebrowse
     git
     gtags
     haskell
     helm
     html
     ivy
     javascript
     latex
     markdown
     org
     pandoc
     (python :variables python-test-runner '(pytest nose))
     restclient
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom
            shell-default-shell 'eshell)
     shell-scripts
     speed-reading
     spell-checking
     sql
     syntax-checking
     themes-megapack
     version-control
     xkcd
     yaml

**Comment by 0xkag** [comment] 2016-10-28 21:04
Git bisect shows the problem started in 389d722996f9f9163bf2ba6fab1c6429838db66f.

**Comment by TheBB** [comment] 2016-10-29 07:55
So it's related to helm or ivy I guess, but I can't reproduce this with any of them. Can we get some more specific reproduction steps here?

**Comment by kccai** [comment] 2016-10-29 09:26
This error occurs because both @zwb-ict and @0xkag have `helm` and `ivy` layer enabled at the same time.

**Comment by zwb-ict** [comment] 2016-10-29 13:11
@TheBB @kccai after use ivy only, this issue gone.

**Comment by TheBB** [comment] 2016-10-29 13:27
Added a warning for people like you guys: https://github.com/syl20bnr/spacemacs/commit/721426f75c962adb29b1d7c60d635a828bbd2dd6 ;-)

Closing since I consider this a wontfix that was introduced on develop.

**Closed by TheBB** 2016-10-29 13:27 UTC
Labels: - Bug tracker -, To be reproduced
