### ISSUE TITLE
Error in spray and helm packages (probably submodule packages) 

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1582] opened 2015-05-12 20:53 UTC
I recently installed spacemacs in a new ubuntu machine. And got these errors at startup
```
Error (use-package): helm :init: Symbol's function definition is void: advice-add
Error (use-package): spray :init: Symbol's function definition is void: advice-add
```

This is are my configuration layers:

```elisp
   dotspacemacs-configuration-layers
   '(
     ;; --------------------------------------------------------
     ;; Example of useful layers you may want to use right away
     ;; Uncomment a layer name and press C-c C-c to install it
     ;; --------------------------------------------------------
     auto-completion
     better-defaults
     (git :variables
          git-enable-github-support t
          git-magit-status-fullscreen t
          git-gutter-use-fringe t)
     markdown
     org
     syntax-checking
     ;; Lang
     python
     emacs-lisp
     c-c++
     )
```

**Comment by syl20bnr** [comment] 2015-05-12 21:10
Duplicate of #1573

**Comment by CestDiego** [comment] 2015-05-12 21:16
Yep, confirmed to be duplicate. I had installed emacs 24.5 too but for some reason the icon on the dashboard was still withthe emacs that came with ubuntu 23.x

**Comment by syl20bnr** [comment] 2015-05-13 04:36
Should be fixed now.

**Closed** 2015-06-01 03:44 UTC
Labels: duplicate (-: :-), Fixed in `develop`
