### ISSUE TITLE
Symbol's function definition is void: ranger

### ISSUE THREAD

**Issue by crmne** [syl20bnr/spacemacs#3910] opened 2015-11-22 11:33 UTC
I installed the `ranger` executable and added `ranger` to my layers, but if I try to invoke it with `SPC a r` or `M-x ranger` it returns this error:

    Symbol's function definition is void: ranger

I can reproduce this on my OS X 10.11 and Ubuntu 14.04 machines, both with Emacs 24.5.1

**Comment by StreakyCobra** [comment] 2015-11-22 12:14
`ranger` layer is not using the `ranger` executable, but an elisp alternative: [`ranger.el`](https://github.com/ralesi/ranger.el). There was some changes upstream recently, it's probably the reason of this.

@ralesi Any idea why `ranger` is not autoloaded? We can probably put it in `:commands`, but it's marked as `;;;autoload` so it shouldn't be needed, no?

**Comment by TheBB** [comment] 2015-11-22 12:24
`ranger` is certainly autoloaded. Something must have gone wrong with your installation.

**Comment by crmne** [comment] 2015-11-22 12:51
I rm'd my `.emacs.d` folder and reinstalled Spacemacs again just now but I still get the same error.

This is my config: https://gist.github.com/crmne/866e84dfbadf6b884001

(@TheBB thanks for sharing your config, the comint tweaks there are copied from yours :+1: )

**Comment by aaronjensen** [comment] 2015-11-22 15:47
I just added ranger and am getting the same issue.

**Comment by StreakyCobra** [comment] 2015-11-22 19:59
@TheBB Definitively an autoloading problem. Putting `:commands (ranger)` make it works.

**Comment by StreakyCobra** [comment] 2015-11-22 20:05
I just updated my packages again, and it seems to work now. @aaronjensen @crmne Can you try updating your packages to see if it works?

**Comment by drets** [comment] 2015-11-23 01:05
I updated 3 packages (one of them - range) and got the new issue.

**Steps to reproduce:**
1. Click *Update* link on the startup screen and type "y".
2. Re-load spacemacs.
```
Compiling file /Users/wikia/.emacs.d/elpa/ranger-20151122.532/ranger.el at Mon Nov 23 01:21:18 2015

In end of data:
ranger.el:2196:1:Warning: the following functions are not known to be defined: alist-get,
    w32-shell-execute, diminish
```
Range works by `SPC-a-r`
3. Re-load spacemacs
```
Warning (initialization): An error occurred while loading `/Users/wikia/.emacs.d/init.el':

Symbol's function definition is void: bind-map-evil-define-key
```

So, I did rollback :confused:
I am on os x and stable branch.

**Comment by drets** [comment] 2015-11-23 07:59
Today Update works fine but the issue the same:
```
Symbol's function definition is void: ranger
```

**Comment by TheBB** [comment] 2015-11-23 08:01
I just updated my packages and I can't reproduce this problem. Ranger works fine.

**Comment by drets** [comment] 2015-11-23 08:04
I am on stable branch :wink:

**Comment by TheBB** [comment] 2015-11-23 09:09
Okay, I can reproduce. It's a bug in ranger. Will file upstream.

**Comment by TheBB** [comment] 2015-11-23 09:16
https://github.com/ralesi/ranger.el/pull/83

**Comment by TheBB** [comment] 2015-11-23 15:24
Should be fixed upstream. It'll be on MELPA in a few hours.

**Closed by TheBB** 2015-11-23 15:24 UTC
Labels: bug :-(, File browser, Fixed upstream
