### ISSUE TITLE
Errors on fresh install (treemacs, helm)

### ISSUE THREAD

**Issue by Martinsos** [syl20bnr/spacemacs#13926] opened 2020-09-07 09:47 UTC
#### Description :octocat:
After updating emacs from v26 to v27, I got error `Error (use-package): treemacs-persp/:catch: Given parent class treemacs-scope is not a class` while spacemacs was installing packages (which it started doing automatically on start).

I then run `update-packages` hoping to fix this, saw no errors reported and restarted emacs, thinking that is it, I fixed it.

However, now I was getting different error any time helm was supposed to open: `Symbol’s value as variable is void: helm-buffer-list-reorder-fn`. Note that helm was working ok before I restarted emacs, after updating packages.

I then run `update-packages` again (using SPC f e U since helm did not work) and after this helm started working.

To figure out if this was caused by some weird state I got my emacs/spacemacs into, I deleted the whole spacemacs repo, cloned it again, and again everything happened in the same way.

All this is happening on latest develop branch (59f72709b8c2863bb9182095fbdbc71eba56040f).

#### Reproduction guide :beetle:
- Do a fresh clone of spacemacs repo, check out develop branch.
- Start Emacs.
- Observe `treemacs` error.
- Observe that helm works ok.
- SPC f e U to update packages -> no errors reported (at least I did not see any).
- Observe that helm still works ok.
- Restart emacs.
- Observe that helm now does not work and is throwing error.
- SPC f e U to update packages -> no errors.
- Helm now works.

*Observed behaviour:* :eyes: :broken_heart:
errors on startup

*Expected behaviour:* :heart: :smile:
When freshly installed, there should be no errors.

#### System Info :computer:
- OS: archlinux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 59f72709b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript ruby auto-completion better-defaults emacs-lisp git
           (haskell :variables haskell-completion-backend 'dante dante-tap-type-time 1 haskell-indentation-layout-offset 4 haskell-indentation-starter-offset 4 haskell-indentation-left-offset 4 haskell-indentation-where-pre-offset 2 haskell-indentation-where-post-offset 2)
           helm html
           (javascript :variables js2-mode-show-strict-warnings nil js2-basic-offset 2 js-indent-level 2)
           lsp markdown multiple-cursors org
           (shell :variables shell-default-height 30 shell-default-position 'bottom)
           (syntax-checking :variables syntax-checking-enable-tooltips nil flycheck-display-errors-function #'flycheck-display-error-messages-unless-error-list)
           treemacs version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
N/A

**Comment by emacs18** [comment] 2020-09-12 04:59
Given that 26 to 27 is a major version update, wouldn't it be safe to assume that byte-compiled files cannot be used, i.e., shouldn't you make sure that all `*.elc` files are removed before launching 27?

**Comment by Martinsos** [comment] 2020-09-12 15:25
@emacs18 I wasn't aware of that! But, as I mentioned above, I did remove the whole spacemacs repo and it did not help -> I believe if there were any .elc files, those would be inside it?

**Comment by emacs18** [comment] 2020-09-12 16:34
I think it depends.  Could you check the value of `package-user-dir` for you?  If that points to a sub-directory within spacemacs clone, then you are right that wiping spacemacs repo would also wipe your installed pacakges.  However if `package-user-dir` points to a directory outside of spacemacs clone, then you would need to manually wipe that directory.

**Comment by Martinsos** [comment] 2020-09-13 21:08
@emacs18 thanks for the hint! I check the value of `package-user-dir`, and it is inside my spacemacs repo clone -> it is `<spacemacs-repo>/elpa/27.1/develop`.

**Comment by emacs18** [comment] 2020-09-13 23:39
I was not able to reproduce your failure using my build of emacs 27 on ubuntu 20.04.  My steps were

- `rm ~/.spacemacs`
- create fresh clone of spacesmacs develop branch  at the version that was mentioned above
- define a new chemacs profile  and use it so that `user-emacs-directory` points to this spacemacs clone
- I let emacs start so that `~/.spacemacs` would be created
- exit emacs and edit `~/.spacemacs` to change the layers to exactly the ones mentioned at the top of this page
- `rm -rf spacemacs/elpa/*` to remove all installed packages
- start emacs

Treemacs worked fine.  Helm worked fine.  I saw no treemacs errors in `*Messages*` buffer.

**Comment by Martinsos** [comment] 2020-09-14 09:52
@emacs18 thanks for taking the time! Hmmm, well that poses question as to what is different on my side. Archlinux? But how would that affect it hm. Btw. I merely have a symbolic link from .emacs.d toward spacemacs repo clone dir, that is how I set it up, but I believe that should not be a problem, or could it be?

Btw. you can check out my exact init.el here: https://github.com/Martinsos/dotfiles/blob/master/.spacemacs.d/init.el .

If this is only error on my side, then it certainly doesn't make much sense to pursue this. But I see that @MarcusE1W reacted with thumbs up emoji -> @MarcusE1W, did you have the same issue?

**Comment by MarcusE1W** [comment] 2020-09-14 11:18
Hi, yes. I have freshly installed emacs 27.1 and spacemacs and got a lot of errors for helm. Could it have been a timing problem that something was misaligned only for a while? I have to admit I did not investigate too much as I am using Ivy.

**Comment by emacs18** [comment] 2020-09-14 19:10
@MarcusE1W I tried your `init.el`.  I still don't see any problem, i.e., there is no "error" within `*Messages*` buffer.

One brute force method of debugging could be for you to save away your `~/.spacemacs`, then let emacs recreate it.  If this works, then you can introduce your customizations one by one starting with layer stuff.

I examined the changes you made in your `init.el` file compared with `~/.spacemacs` file that is generated.  Following seems to be the only change that could impact your issue although I don't see any problem either way.

```diff
-   dotspacemacs-use-spacelpa nil
+   dotspacemacs-use-spacelpa t
```

**Comment by smile13241324** [comment] 2020-09-14 20:22
Can't reproduce your issue, I have removed my elpa folder and reinstalled all 500+ packages, apart from some compile warnings all worked well. I am on Manjaro Gnome.

@Martinsos I would suggest the same, try to reproduce the issue with a standard config and report back here. Also make sure you have no OS level packages installed which may be incompatible or would need a recompile.

**Comment by Martinsos** [comment] 2020-09-16 11:14
Ok, so I followed the suggestion and managed to reproduce it in the following manner:
1. I deleted spacemacs repo, cloned it again, checked out develop branch.
2. I deleted my .spacemacs.d.
3. I run emacs, it created new .spacemacs file for me, and it installed all the packages and all was fine.
4. I edited .spacemacs file with just one change: I set `dotspacemacs-use-spacelpa` to `t`.
5. I again deleted spacemacs repo, cloned it again, checked out develop branch.
6. I run emacs, it installed packages (from spacelpa) and then it threw treemacs error, same as before.

So basically, setting spacelpa to `t` and having freshly cloned spacemacs repo (develop branch) -> I get an error.

Interesting: Deleting `elpa` dir from spacemacs repo is not enough to reproduce the error, I have to delete the whole spacemacs repo and clone it again (I could try deleting more stuff though until I figure out which dirs from spacemacs exactly have to be deleted to reproduce the error).

<details>
  <summary>My .spacemacs</summary>

```elisp
;; -*- mode: emacs-lisp; lexical-binding: t -*-
;; This file is loaded by Spacemacs at startup.
;; It must be stored in your home directory.

(defun dotspacemacs/layers ()
  "Layer configuration:
This function should only modify configuration layer settings."
  (setq-default
   ;; Base distribution to use. This is a layer contained in the directory
   ;; `+distribution'. For now available distributions are `spacemacs-base'
   ;; or `spacemacs'. (default 'spacemacs)
   dotspacemacs-distribution 'spacemacs

   ;; Lazy installation of layers (i.e. layers are installed only when a file
   ;; with a supported type is opened). Possible values are `all', `unused'
   ;; and `nil'. `unused' will lazy install only unused layers (i.e. layers
   ;; not listed in variable `dotspacemacs-configuration-layers'), `all' will
   ;; lazy install any layer that support lazy installation even the layers
   ;; listed in `dotspacemacs-configuration-layers'. `nil' disable the lazy
   ;; installation feature and you have to explicitly list a layer in the
   ;; variable `dotspacemacs-configuration-layers' to install it.
   ;; (default 'unused)
   dotspacemacs-enable-lazy-installation 'unused

   ;; If non-nil then Spacemacs will ask for confirmation before installing
   ;; a layer lazily. (default t)
   dotspacemacs-ask-for-lazy-installation t

   ;; List of additional paths where to look for configuration layers.
   ;; Paths must have a trailing slash (i.e. `~/.mycontribs/')
   dotspacemacs-configuration-layer-path '()

   ;; List of configuration layers to load.
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press `SPC f e R' (Vim style) or
     ;; `M-m f e R' (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     ;; auto-completion
     ;; better-defaults
     emacs-lisp
     ;; git
     helm
     ;; lsp
     ;; markdown
     multiple-cursors
     ;; org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     ;; version-control
     treemacs)


   ;; List of additional packages that will be installed without being
   ;; wrapped in a layer. If you need some configuration for these
   ;; packages, then consider creating a layer. You can also put the
   ;; configuration in `dotspacemacs/user-config'.
   ;; To use a local version of a package, use the `:location' property:
   ;; '(your-package :location "~/path/to/your-package/")
   ;; Also include the dependencies as they will not be resolved automatically.
   dotspacemacs-additional-packages '()

   ;; A list of packages that cannot be updated.
   dotspacemacs-frozen-packages '()

   ;; A list of packages that will not be installed and loaded.
   dotspacemacs-excluded-packages '()

   ;; Defines the behaviour of Spacemacs when installing packages.
   ;; Possible values are `used-only', `used-but-keep-unused' and `all'.
   ;; `used-only' installs only explicitly used packages and deletes any unused
   ;; packages as well as their unused dependencies. `used-but-keep-unused'
   ;; installs only the used packages but won't delete unused ones. `all'
   ;; installs *all* packages supported by Spacemacs and never uninstalls them.
   ;; (default is `used-only')
   dotspacemacs-install-packages 'used-only))

(defun dotspacemacs/init ()
  "Initialization:
This function is called at the very beginning of Spacemacs startup,
before layer configuration.
It should only modify the values of Spacemacs settings."
  ;; This setq-default sexp is an exhaustive list of all the supported
  ;; spacemacs settings.
  (setq-default
   ;; If non-nil then enable support for the portable dumper. You'll need
   ;; to compile Emacs 27 from source following the instructions in file
   ;; EXPERIMENTAL.org at to root of the git repository.
   ;; (default nil)
   dotspacemacs-enable-emacs-pdumper nil

   ;; Name of executable file pointing to emacs 27+. This executable must be
   ;; in your PATH.
   ;; (default "emacs")
   dotspacemacs-emacs-pdumper-executable-file "emacs"

   ;; Name of the Spacemacs dump file. This is the file will be created by the
   ;; portable dumper in the cache directory under dumps sub-directory.
   ;; To load it when starting Emacs add the parameter `--dump-file'
   ;; when invoking Emacs 27.1 executable on the command line, for instance:
   ;;   ./emacs --dump-file=$HOME/.emacs.d/.cache/dumps/spacemacs-27.1.pdmp
   ;; (default (format "spacemacs-%s.pdmp" emacs-version))
   dotspacemacs-emacs-dumper-dump-file (format "spacemacs-%s.pdmp" emacs-version)

   ;; If non-nil ELPA repositories are contacted via HTTPS whenever it's
   ;; possible. Set it to nil if you have no way to use HTTPS in your
   ;; environment, otherwise it is strongly recommended to let it set to t.
   ;; This variable has no effect if Emacs is launched with the parameter
   ;; `--insecure' which forces the value of this variable to nil.
   ;; (default t)
   dotspacemacs-elpa-https t

   ;; Maximum allowed time in seconds to contact an ELPA repository.
   ;; (default 5)
   dotspacemacs-elpa-timeout 5

   ;; Set `gc-cons-threshold' and `gc-cons-percentage' when startup finishes.
   ;; This is an advanced option and should not be changed unless you suspect
   ;; performance issues due to garbage collection operations.
   ;; (default '(100000000 0.1))
   dotspacemacs-gc-cons '(100000000 0.1)

   ;; Set `read-process-output-max' when startup finishes.
   ;; This defines how much data is read from a foreign process.
   ;; Setting this >= 1 MB should increase performance for lsp servers
   ;; in emacs 27.
   ;; (default (* 1024 1024))
   dotspacemacs-read-process-output-max (* 1024 1024)

   ;; If non-nil then Spacelpa repository is the primary source to install
   ;; a locked version of packages. If nil then Spacemacs will install the
   ;; latest version of packages from MELPA. (default nil)
   dotspacemacs-use-spacelpa t

   ;; If non-nil then verify the signature for downloaded Spacelpa archives.
   ;; (default t)
   dotspacemacs-verify-spacelpa-archives t

   ;; If non-nil then spacemacs will check for updates at startup
   ;; when the current branch is not `develop'. Note that checking for
   ;; new versions works via git commands, thus it calls GitHub services
   ;; whenever you start Emacs. (default nil)
   dotspacemacs-check-for-update nil

   ;; If non-nil, a form that evaluates to a package directory. For example, to
   ;; use different package directories for different Emacs versions, set this
   ;; to `emacs-version'. (default 'emacs-version)
   dotspacemacs-elpa-subdirectory 'emacs-version

   ;; One of `vim', `emacs' or `hybrid'.
   ;; `hybrid' is like `vim' except that `insert state' is replaced by the
   ;; `hybrid state' with `emacs' key bindings. The value can also be a list
   ;; with `:variables' keyword (similar to layers). Check the editing styles
   ;; section of the documentation for details on available variables.
   ;; (default 'vim)
   dotspacemacs-editing-style 'vim

   ;; If non-nil show the version string in the Spacemacs buffer. It will
   ;; appear as (spacemacs version)@(emacs version)
   ;; (default t)
   dotspacemacs-startup-buffer-show-version t

   ;; Specify the startup banner. Default value is `official', it displays
   ;; the official spacemacs logo. An integer value is the index of text
   ;; banner, `random' chooses a random text banner in `core/banners'
   ;; directory. A string value must be a path to an image format supported
   ;; by your Emacs build.
   ;; If the value is nil then no banner is displayed. (default 'official)
   dotspacemacs-startup-banner 'official

   ;; List of items to show in startup buffer or an association list of
   ;; the form `(list-type . list-size)`. If nil then it is disabled.
   ;; Possible values for list-type are:
   ;; `recents' `bookmarks' `projects' `agenda' `todos'.
   ;; List sizes may be nil, in which case
   ;; `spacemacs-buffer-startup-lists-length' takes effect.
   dotspacemacs-startup-lists '((recents . 5)
                                (projects . 7))

   ;; True if the home buffer should respond to resize events. (default t)
   dotspacemacs-startup-buffer-responsive t

   ;; Default major mode for a new empty buffer. Possible values are mode
   ;; names such as `text-mode'; and `nil' to use Fundamental mode.
   ;; (default `text-mode')
   dotspacemacs-new-empty-buffer-major-mode 'text-mode

   ;; Default major mode of the scratch buffer (default `text-mode')
   dotspacemacs-scratch-mode 'text-mode

   ;; Initial message in the scratch buffer, such as "Welcome to Spacemacs!"
   ;; (default nil)
   dotspacemacs-initial-scratch-message nil

   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press `SPC T n' to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   dotspacemacs-themes '(spacemacs-dark
                         spacemacs-light)

   ;; Set the theme for the Spaceline. Supported themes are `spacemacs',
   ;; `all-the-icons', `custom', `doom', `vim-powerline' and `vanilla'. The
   ;; first three are spaceline themes. `doom' is the doom-emacs mode-line.
   ;; `vanilla' is default Emacs mode-line. `custom' is a user defined themes,
   ;; refer to the DOCUMENTATION.org for more info on how to create your own
   ;; spaceline theme. Value can be a symbol or list with additional properties.
   ;; (default '(spacemacs :separator wave :separator-scale 1.5))
   dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5)

   ;; If non-nil the cursor color matches the state color in GUI Emacs.
   ;; (default t)
   dotspacemacs-colorize-cursor-according-to-state t

   ;; Default font or prioritized list of fonts.
   dotspacemacs-default-font '("Source Code Pro"
                               :size 10.0
                               :weight normal
                               :width normal)

   ;; The leader key (default "SPC")
   dotspacemacs-leader-key "SPC"

   ;; The key used for Emacs commands `M-x' (after pressing on the leader key).
   ;; (default "SPC")
   dotspacemacs-emacs-command-key "SPC"

   ;; The key used for Vim Ex commands (default ":")
   dotspacemacs-ex-command-key ":"

   ;; The leader key accessible in `emacs state' and `insert state'
   ;; (default "M-m")
   dotspacemacs-emacs-leader-key "M-m"

   ;; Major mode leader key is a shortcut key which is the equivalent of
   ;; pressing `<leader> m`. Set it to `nil` to disable it. (default ",")
   dotspacemacs-major-mode-leader-key ","

   ;; Major mode leader key accessible in `emacs state' and `insert state'.
   ;; (default "C-M-m" for terminal mode, "<M-return>" for GUI mode).
   ;; Thus M-RET should work as leader key in both GUI and terminal modes.
   ;; C-M-m also should work in terminal mode, but not in GUI mode.
   dotspacemacs-major-mode-emacs-leader-key (if window-system "<M-return>" "C-M-m")

   ;; These variables control whether separate commands are bound in the GUI to
   ;; the key pairs `C-i', `TAB' and `C-m', `RET'.
   ;; Setting it to a non-nil value, allows for separate commands under `C-i'
   ;; and TAB or `C-m' and `RET'.
   ;; In the terminal, these pairs are generally indistinguishable, so this only
   ;; works in the GUI. (default nil)
   dotspacemacs-distinguish-gui-tab nil

   ;; Name of the default layout (default "Default")
   dotspacemacs-default-layout-name "Default"

   ;; If non-nil the default layout name is displayed in the mode-line.
   ;; (default nil)
   dotspacemacs-display-default-layout nil

   ;; If non-nil then the last auto saved layouts are resumed automatically upon
   ;; start. (default nil)
   dotspacemacs-auto-resume-layouts nil

   ;; If non-nil, auto-generate layout name when creating new layouts. Only has
   ;; effect when using the "jump to layout by number" commands. (default nil)
   dotspacemacs-auto-generate-layout-names nil

   ;; Size (in MB) above which spacemacs will prompt to open the large file
   ;; literally to avoid performance issues. Opening a file literally means that
   ;; no major mode or minor modes are active. (default is 1)
   dotspacemacs-large-file-size 1

   ;; Location where to auto-save files. Possible values are `original' to
   ;; auto-save the file in-place, `cache' to auto-save the file to another
   ;; file stored in the cache directory and `nil' to disable auto-saving.
   ;; (default 'cache)
   dotspacemacs-auto-save-file-location 'cache

   ;; Maximum number of rollback slots to keep in the cache. (default 5)
   dotspacemacs-max-rollback-slots 5

   ;; If non-nil, the paste transient-state is enabled. While enabled, after you
   ;; paste something, pressing `C-j' and `C-k' several times cycles through the
   ;; elements in the `kill-ring'. (default nil)
   dotspacemacs-enable-paste-transient-state nil

   ;; Which-key delay in seconds. The which-key buffer is the popup listing
   ;; the commands bound to the current keystroke sequence. (default 0.4)
   dotspacemacs-which-key-delay 0.4

   ;; Which-key frame position. Possible values are `right', `bottom' and
   ;; `right-then-bottom'. right-then-bottom tries to display the frame to the
   ;; right; if there is insufficient space it displays it at the bottom.
   ;; (default 'bottom)
   dotspacemacs-which-key-position 'bottom

   ;; Control where `switch-to-buffer' displays the buffer. If nil,
   ;; `switch-to-buffer' displays the buffer in the current window even if
   ;; another same-purpose window is available. If non-nil, `switch-to-buffer'
   ;; displays the buffer in a same-purpose window even if the buffer can be
   ;; displayed in the current window. (default nil)
   dotspacemacs-switch-to-buffer-prefers-purpose nil

   ;; If non-nil a progress bar is displayed when spacemacs is loading. This
   ;; may increase the boot time on some systems and emacs builds, set it to
   ;; nil to boost the loading time. (default t)
   dotspacemacs-loading-progress-bar t

   ;; If non-nil the frame is fullscreen when Emacs starts up. (default nil)
   ;; (Emacs 24.4+ only)
   dotspacemacs-fullscreen-at-startup nil

   ;; If non-nil `spacemacs/toggle-fullscreen' will not use native fullscreen.
   ;; Use to disable fullscreen animations in OSX. (default nil)
   dotspacemacs-fullscreen-use-non-native nil

   ;; If non-nil the frame is maximized when Emacs starts up.
   ;; Takes effect only if `dotspacemacs-fullscreen-at-startup' is nil.
   ;; (default nil) (Emacs 24.4+ only)
   dotspacemacs-maximized-at-startup nil

   ;; If non-nil the frame is undecorated when Emacs starts up. Combine this
   ;; variable with `dotspacemacs-maximized-at-startup' in OSX to obtain
   ;; borderless fullscreen. (default nil)
   dotspacemacs-undecorated-at-startup nil

   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's active or selected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-active-transparency 90

   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's inactive or deselected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-inactive-transparency 90

   ;; If non-nil show the titles of transient states. (default t)
   dotspacemacs-show-transient-state-title t

   ;; If non-nil show the color guide hint for transient state keys. (default t)
   dotspacemacs-show-transient-state-color-guide t

   ;; If non-nil unicode symbols are displayed in the mode line.
   ;; If you use Emacs as a daemon and wants unicode characters only in GUI set
   ;; the value to quoted `display-graphic-p'. (default t)
   dotspacemacs-mode-line-unicode-symbols t

   ;; If non-nil smooth scrolling (native-scrolling) is enabled. Smooth
   ;; scrolling overrides the default behavior of Emacs which recenters point
   ;; when it reaches the top or bottom of the screen. (default t)
   dotspacemacs-smooth-scrolling t

   ;; Control line numbers activation.
   ;; If set to `t', `relative' or `visual' then line numbers are enabled in all
   ;; `prog-mode' and `text-mode' derivatives. If set to `relative', line
   ;; numbers are relative. If set to `visual', line numbers are also relative,
   ;; but lines are only visual lines are counted. For example, folded lines
   ;; will not be counted and wrapped lines are counted as multiple lines.
   ;; This variable can also be set to a property list for finer control:
   ;; '(:relative nil
   ;;   :visual nil
   ;;   :disabled-for-modes dired-mode
   ;;                       doc-view-mode
   ;;                       markdown-mode
   ;;                       org-mode
   ;;                       pdf-view-mode
   ;;                       text-mode
   ;;   :size-limit-kb 1000)
   ;; When used in a plist, `visual' takes precedence over `relative'.
   ;; (default nil)
   dotspacemacs-line-numbers nil

   ;; Code folding method. Possible values are `evil' and `origami'.
   ;; (default 'evil)
   dotspacemacs-folding-method 'evil

   ;; If non-nil `smartparens-strict-mode' will be enabled in programming modes.
   ;; (default nil)
   dotspacemacs-smartparens-strict-mode nil

   ;; If non-nil pressing the closing parenthesis `)' key in insert mode passes
   ;; over any automatically added closing parenthesis, bracket, quote, etc...
   ;; This can be temporary disabled by pressing `C-q' before `)'. (default nil)
   dotspacemacs-smart-closing-parenthesis nil

   ;; Select a scope to highlight delimiters. Possible values are `any',
   ;; `current', `all' or `nil'. Default is `all' (highlight any scope and
   ;; emphasis the current one). (default 'all)
   dotspacemacs-highlight-delimiters 'all

   ;; If non-nil, start an Emacs server if one is not already running.
   ;; (default nil)
   dotspacemacs-enable-server nil

   ;; Set the emacs server socket location.
   ;; If nil, uses whatever the Emacs default is, otherwise a directory path
   ;; like \"~/.emacs.d/server\". It has no effect if
   ;; `dotspacemacs-enable-server' is nil.
   ;; (default nil)
   dotspacemacs-server-socket-dir nil

   ;; If non-nil, advise quit functions to keep server open when quitting.
   ;; (default nil)
   dotspacemacs-persistent-server nil

   ;; List of search tool executable names. Spacemacs uses the first installed
   ;; tool of the list. Supported tools are `rg', `ag', `pt', `ack' and `grep'.
   ;; (default '("rg" "ag" "pt" "ack" "grep"))
   dotspacemacs-search-tools '("rg" "ag" "pt" "ack" "grep")

   ;; Format specification for setting the frame title.
   ;; %a - the `abbreviated-file-name', or `buffer-name'
   ;; %t - `projectile-project-name'
   ;; %I - `invocation-name'
   ;; %S - `system-name'
   ;; %U - contents of $USER
   ;; %b - buffer name
   ;; %f - visited file name
   ;; %F - frame name
   ;; %s - process status
   ;; %p - percent of buffer above top of window, or Top, Bot or All
   ;; %P - percent of buffer above bottom of window, perhaps plus Top, or Bot or All
   ;; %m - mode name
   ;; %n - Narrow if appropriate
   ;; %z - mnemonics of buffer, terminal, and keyboard coding systems
   ;; %Z - like %z, but including the end-of-line format
   ;; (default "%I@%S")
   dotspacemacs-frame-title-format "%I@%S"

   ;; Format specification for setting the icon title format
   ;; (default nil - same as frame-title-format)
   dotspacemacs-icon-title-format nil

   ;; Delete whitespace while saving buffer. Possible values are `all'
   ;; to aggressively delete empty line and long sequences of whitespace,
   ;; `trailing' to delete only the whitespace at end of lines, `changed' to
   ;; delete only whitespace for changed lines or `nil' to disable cleanup.
   ;; (default nil)
   dotspacemacs-whitespace-cleanup nil

   ;; If non nil activate `clean-aindent-mode' which tries to correct
   ;; virtual indentation of simple modes. This can interfer with mode specific
   ;; indent handling like has been reported for `go-mode'.
   ;; If it does deactivate it here.
   ;; (default t)
   dotspacemacs-use-clean-aindent-mode t

   ;; If non-nil shift your number row to match the entered keyboard layout
   ;; (only in insert state). Currently supported keyboard layouts are:
   ;; `qwerty-us', `qwertz-de' and `querty-ca-fr'.
   ;; New layouts can be added in `spacemacs-editing' layer.
   ;; (default nil)
   dotspacemacs-swap-number-row nil

   ;; Either nil or a number of seconds. If non-nil zone out after the specified
   ;; number of seconds. (default nil)
   dotspacemacs-zone-out-when-idle nil

   ;; Run `spacemacs/prettify-org-buffer' when
   ;; visiting README.org files of Spacemacs.
   ;; (default nil)
   dotspacemacs-pretty-docs nil

   ;; If nil the home buffer shows the full path of agenda items
   ;; and todos. If non nil only the file name is shown.
   dotspacemacs-home-shorten-agenda-source nil))

(defun dotspacemacs/user-env ()
  "Environment variables setup.
This function defines the environment variables for your Emacs session. By
default it calls `spacemacs/load-spacemacs-env' which loads the environment
variables declared in `~/.spacemacs.env' or `~/.spacemacs.d/.spacemacs.env'.
See the header of this file for more information."
  (spacemacs/load-spacemacs-env))

(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after `dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first."
  )

(defun dotspacemacs/user-load ()
  "Library to load while dumping.
This function is called only while dumping Spacemacs configuration. You can
`require' or `load' the libraries of your choice that will be included in the
dump."
  )

(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
  )

;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
```
</details>

**Comment by emacs18** [comment] 2020-09-16 17:13
I retested.  I see no problem with freshly generated ~/.spacemacs file whose only change was to set dotspacemacs-use-spacelpa to t.  I also used freshly cloned spacemacs repo.

**Comment by emacs18** [comment] 2020-09-16 17:50
I did run into startup problem where a stack trace was thrown with "unknown symbol This" while loading org-loaddefs.el.
However exiting emacs and then restarting seemed to get over this problem even if I had to try 3 or 4 times.
Other than this problem I observed no other problem.  Treemacs started up fine. Helm seem to work fine as well.

**Comment by emacs18** [comment] 2020-09-17 06:00
I was able to duplicate the problem with the following shell script:

```shell
#!/bin/bash

cd
rm -f ~/.spacemacs
rm -rf ~/.emacs.d

# Clone spacemacs develop branch into ~/.emacs.d
git clone -b develop --depth 50 https://github.com/syl20bnr/spacemacs .emacs.d

# Create a default ~/.spacemacs but set dotspacemacs-use-spacelpa as t
sed 's/dotspacemacs-use-spacelpa nil/dotspacemacs-use-spacelpa t/' \
    ~/.emacs.d/core/templates/.spacemacs.template > ~/.spacemacs

# Launch emacs 27
~/emacs27/bin/emacs -q --eval '(progn (setq user-emacs-directory "~/.emacs.d/") (load "~/.emacs.d/init.el"))'
```

**Comment by Martinsos** [comment] 2020-09-17 09:57
@emacs18 Yes that is it! It is obviously important that some cache from spacemacs is removed, probably both elpa/ and .cache/.

Btw I don't remember personally setting dotspacemacs-use-spacelpa to `t`, I wonder how that got set to that value in my settings hm.

**Comment by emacs18** [comment] 2020-09-17 13:09
The default value of this variable is nil, and it appears have been nil since it was created in 2017.
So my guess is that you changed it in your own file at some point.

**Comment by emacs18** [comment] 2020-09-17 13:13
I'm not sure what to do with this problem.  It indeed seems to be a problem.  However it seems to be a problem that only those 
who changed `dotspacemacs-use-spacelpa` to `t` would face.  My guess is that there is some package version compatibility problem among packages in this spacelpa repository wherever this may be located.  Since I have never used this spacelpa repo, and I don't even know where it is located, I'm not so inclined to look into this any further.

**Comment by Martinsos** [comment] 2020-09-17 20:22
@emacs18 thanks for taking the time to look into this. I have to admit I also don't know much about spacelpa, and wonder why I put that to `t`. I guess this is not really a big problem since situation in which it does reproduce seems pretty unique. However, maybe it hides some serious cause? I wouldn't know. Let's see, maybe somebody else will have more interest in this, if not I am ok with closing it.

**Comment by smile13241324** [comment] 2020-09-17 20:36
I was just watching from afar guys, still being interested. 

Basically Spacelpa is an open project of @syl20bnr where you fetch a tar of packages which you can then install offline. The idea is to be less dependent on external package sources like elpa. However I am not sure what the status of this package repo is right now, maybe it is still in test and has not been updated so that simply packages are missing or the version is too old for emacs 27.

:thinking: I will push a message to the maintainers thread lets see if we can update package lists there. If not we may have to remove the variable form the dotfile or add a more meaningful message to the var something among the lines of "only use for testing".

Please keep the ticket open, I'll assign it to me and post more information when I have it.

**Comment by smile13241324** [comment] 2020-09-18 20:13
@Martinsos it looks like the packages are pretty outdated, I have added a warning to the dotfile to avoid others using this in production for now. There is an open ticket #12656 which is about implementing this feature which is not yet finished.

**Comment by smile13241324** [comment] 2020-09-18 20:31
I think we can close this ticket now, questions about spacelpa can be moved to the related ticket.

**Closed by smile13241324** 2020-09-18 20:31 UTC
Labels: Bug :-(, Spacelpa
