### ISSUE TITLE
SPC-f-e-R delete fill-column-indicator package

### ISSUE THREAD

**Issue by tshu-w** [syl20bnr/spacemacs#13168] opened 2020-01-08 02:39 UTC
#### Description :octocat:
dotspacemacs/sync-configuration-layers delete fill-column-indicator package

#### Reproduction guide :beetle:
- Start Emacs
- SPC-f-e-R
- fill-column-indicator deleted
- restart Emacs
- install fill-column-indicator again

*Observed behaviour:* :eyes: :broken_heart:
fill-column-indicator deleted after every sync-configuration-layers
~~BTW, this issue also happened on a default fresh installed config.~~

*Expected behaviour:* :heart: :smile:
fill-column-indicator stay there after sync-configuration-layers

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7636811b7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-enable-advanced-buffer-information t ivy-initial-inputs-alist nil)
 osx
 (chinese :variables chinese-enable-fcitx t)
 dash
 (version-control :variables version-control-diff-tool 'diff-hl)
 git
 (github :variables forge-topic-list-limit
         '(60 . 5))
 (pandoc :variables pandoc-data-dir "~/.spacemacs.d/pandoc-mode")
 lsp dap
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c++-enable-organize-includes-on-save t)
 emacs-lisp
 (python :variables python-shell-interpreter "/usr/local/anaconda3/bin/python" org-babel-python-command "/usr/local/anaconda3/bin/python" python-backend 'anaconda python-sort-imports-on-save t python-test-runner
         '(pytest nose)
         python-formatter 'black python-format-on-save nil blacken-fast-unsafe t python-fill-column 88)
 (conda :variables conda-anaconda-home "/usr/local/anaconda3")
 (markdown :variables markdown-command "pandoc -f markdown+smart -t html5 --mathjax --highlight-style=pygments --toc --toc-depth 3 --template github.html5 --shift-heading-level-by=-1 --quiet" markdown-live-preview-engine 'pandoc)
 (org :variables org-agenda-files
      '("~/Documents/Org")
      org-directory '"~/Documents/Org" org-projectile-file "TODOs.org" org-want-todo-bindings t org-enable-hugo-support nil org-enable-reveal-js-support nil org-enable-org-journal-support t org-journal-dir "~/Documents/Org/Journals/")
 (latex :variables latex-enable-auto-fill nil latex-enable-folding t latex-enable-magic nil)
 (bibtex :variables org-ref-default-bibliography
         '("~/Dropbox/Documents/Zotero/refs.bib")
         org-ref-pdf-directory "~/Dropbox/Documents/Zotero/" org-ref-bibliography-notes "~/Dropbox/Documents/Zotero/notes.org")
 (deft :variables deft-directory "~/Documents/Org/Notes" deft-recursive t deft-extensions
   '("org" "md" "txt")
   deft-org-mode-title-prefix t deft-use-filename-as-title nil deft-use-filter-string-for-filename t deft-auto-save-interval 0 deft-file-naming-rules
   '((noslash . "-")
     (nospace . "-")
     (case-fn . downcase))
   deft-strip-summary-regexp
   (concat "\\(" "[\n	]" "\\|^#\\+[[:upper:]_]+:.*$" "\\|^#\\+[[:alnum:]_]+:.*$" "\\)"))
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-use-company-box t auto-completion-enable-snippets-in-popup nil auto-completion-enable-sort-by-usage t)
 (templates :variables templates-private-directory "~/.spacemacs.d/templates")
 (syntax-checking :variables syntax-checking-enable-by-default t)
 (pdf :variables pdf-view-use-scaling t)
 (wakatime :variables wakatime-cli-path "/usr/local/bin/wakatime")
 (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t)
 evil-commentary helpful unicode-fonts cfg)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment] 2020-01-14 20:30
The `fill-column-indicator` package is not removed with either the current setup or with a fresh clone.

But with my current setup these 8 packages are removed on startup:
```
(Spacemacs) --> deleting lsp-ui... [1/8]
Package ‘lsp-ui-20200106.1152’ deleted.
(Spacemacs) --> deleting lsp-treemacs... [2/8]
Package ‘lsp-treemacs-20200109.1509’ deleted.
(Spacemacs) --> deleting lsp-python-ms... [3/8]
Package ‘lsp-python-ms-20200114.1228’ deleted.
(Spacemacs) --> deleting lsp-mode... [4/8]
Package ‘lsp-mode-20200111.839’ deleted.
(Spacemacs) --> deleting helm-lsp... [5/8]
Package ‘helm-lsp-20200103.1659’ deleted.
(Spacemacs) --> deleting dap-mode... [6/8]
Package ‘dap-mode-20200114.1604’ deleted.
(Spacemacs) --> deleting company-lsp... [7/8]
Package ‘company-lsp-20190612.1553’ deleted.
(Spacemacs) --> deleting bui... [8/8]
Package ‘bui-20181218.1830’ deleted.
```
and they are reinstalled when `SPC f e R` is pressed.


<details><summary>
Current setup
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3d39b98e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html imenu-list javascript markdown
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            python
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>


<details><summary>
A fresh clone.
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3d39b98e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by duianto** [comment] 2020-01-14 20:46
It seems to be caused by the `python` layer. When I disable it then it doesn't happen anymore.

**Comment by tshu-w** [comment] 2020-01-15 00:52
@duianto Yes, it seems to be caused by the `python` layer on my side too.

**Comment by duianto** [comment] 2020-01-19 12:46
There's another issue about `python` and `auto-completion` also causing packages to be installed/deleted when `SPC f e R` synchronizing.
Enabling python layer without auto-completion leads to install/delete loop #13162

I don't know if these issues should be merged, they might have the same underlying cause.

**Comment by tshu-w** [comment] 2020-01-20 00:52
Sometimes, I also meet this similar issue that some needless packages installed/deleted when `SPC f e R` synchronizing after change some layer variable in `dotspacemacs-configuration-layers`. However, only `fill-column-indicator` happens all the time. I don't know whether this issue has the same underlying cause with #13162.

**Comment by sorawee** [comment] 2020-03-02 16:59
For the sake of completeness, here's a conversation from Gitter. And yes, `fill-column-indicator` was affected too. I just forgot to include it.

> sorawee @sorawee Jan 01 20:26
> I seem to encounter a weird bug where, everytime I SPC-f-e-R, the packages bui and dapwill be installed, and everytime I restart Emacs, these packages will be uninstalled. Anyone knows what's going on? Note that I didn't have the layer dap on my .spacemacs
I will add these to dotspacemacs-excluded-packages if there's no better way to deal with them
But I still want to know what's going on.

> duianto @duianto Jan 02 04:10
> @sorawee The following layers have calls to *-setup-dap functions: c-c++, elixir, java, javascript, python, ruby and rust.

> One of them might be misbehaving.
You could try commenting out any of those that you have in your config and trying SPC f e R in between to narrow down the source.

**Comment by smile13241324** [comment] 2020-03-17 21:41
Hi @tshu-w,
I have had a look in the related issue #13162, which was about a similiar install/delete loop caused by the python layer. I have tried to reproduce the install/delete loop in your case but when I copy your config it doesn't occur anymore on my side.

Can you double check that this is still happening for you on latest develop?

Here is the config I have used:
```elisp
     (ivy :variables ivy-enable-advanced-buffer-information t ivy-initial-inputs-alist nil)
     osx
     ;; (chinese :variables chinese-enable-fcitx t)
     dash
     (version-control :variables version-control-diff-tool 'diff-hl)
     git
     (github :variables forge-topic-list-limit
             '(60 . 5))
     (pandoc :variables pandoc-data-dir "~/.spacemacs.d/pandoc-mode")
     lsp dap
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c++-enable-organize-includes-on-save t)
     emacs-lisp
     (python :variables python-shell-interpreter "/usr/local/anaconda3/bin/python" org-babel-python-command "/usr/local/anaconda3/bin/python" python-backend 'anaconda python-sort-imports-on-save t python-test-runner
             '(pytest nose)
             python-formatter 'black python-format-on-save nil blacken-fast-unsafe t python-fill-column 88)
     (conda :variables conda-anaconda-home "/usr/local/anaconda3")
     (markdown :variables markdown-command "pandoc -f markdown+smart -t html5 --mathjax --highlight-style=pygments --toc --toc-depth 3 --template github.html5 --shift-heading-level-by=-1 --quiet" markdown-live-preview-engine 'pandoc)
     ;; (org :variables org-agenda-files
     ;;      '("~/Documents/Org")
     ;;      org-directory '"~/Documents/Org" org-projectile-file "TODOs.org" org-want-todo-bindings t org-enable-hugo-support nil org-enable-reveal-js-support nil org-enable-org-journal-support t org-journal-dir "~/Documents/Org/Journals/")
     (latex :variables latex-enable-auto-fill nil latex-enable-folding t latex-enable-magic nil)
     ;; (bibtex :variables org-ref-default-bibliography
     ;;         '("~/Dropbox/Documents/Zotero/refs.bib")
     ;;         org-ref-pdf-directory "~/Dropbox/Documents/Zotero/" org-ref-bibliography-notes "~/Dropbox/Documents/Zotero/notes.org")
     (deft :variables deft-directory "~/Documents/Org/Notes" deft-recursive t deft-extensions
       '("org" "md" "txt")
       deft-org-mode-title-prefix t deft-use-filename-as-title nil deft-use-filter-string-for-filename t deft-auto-save-interval 0 deft-file-naming-rules
       '((noslash . "-")
         (nospace . "-")
         (case-fn . downcase))
       deft-strip-summary-regexp
       (concat "\\(" "[\n	]" "\\|^#\\+[[:upper:]_]+:.*$" "\\|^#\\+[[:alnum:]_]+:.*$" "\\)"))
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-use-company-box t auto-completion-enable-snippets-in-popup nil auto-completion-enable-sort-by-usage t)
     (templates :variables templates-private-directory "~/.spacemacs.d/templates")
     (syntax-checking :variables syntax-checking-enable-by-default t)
     (pdf :variables pdf-view-use-scaling t)
     ;; (wakatime :variables wakatime-cli-path "/usr/local/bin/wakatime")
     ;; (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t)
     evil-commentary helpful unicode-fonts
```

**Comment by tshu-w** [comment] 2020-03-17 23:42
@smile13241324 this doesn't happen currently on the latest develop on my side. I don't know whether others still have this issue. feel free if you want to close it.

**Comment by duianto** [comment] 2020-03-19 12:25
It's fine to close your own issues if your unable to reproduce them. They can be reopened by you or a maintainer if the issue reappears.
I'll close it this time.

**Closed by duianto** 2020-03-19 12:25 UTC
Labels: - Bug tracker -, Install, Python

**Comment by J0ns4** [comment] 2020-06-04 12:09
Hi, I'm seeing the same issue on a fairly recent develop from ~a month ago. 
Here's my layer config:
```
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press `SPC f e R' (Vim style) or
     ;; `M-m f e R' (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     auto-completion
     better-defaults
     emacs-lisp
     git
     helm
     ;; lsp
     (org :variables
          org-enable-org-journal-support t)
     org-roam
     ipython-notebook
     (python :variables
             python-backend 'lsp)
     (shell :variables
            shell-default-height 30
            shell-default-shell 'vterm
            shell-default-position 'bottom)
     spell-checking
     syntax-checking
     pdf
     treemacs
     multiple-cursors
     )
```

**Comment by smile13241324** [comment] 2020-06-20 20:17
@J0ns4 I have just checked this with emacs 26.3 and the current dev branch, and it seems to work it should. By the way you have a not existing layer in your config `org-roam` maybe the issue is caused by this?

**Comment by J0ns4** [comment] 2020-06-21 15:25
Hi,
It's not affected by removing it, but thanks for catching it :)
There is something I forgot to mention, and I apologize - I'm working on windows and emacs is installed on an Ubuntu installed as a WSL.
