### ISSUE TITLE
Links at the top of the FAQ are broken

### ISSUE THREAD

**Issue by togakangaroo** [syl20bnr/spacemacs#6824] opened 2016-08-14 18:54 UTC
The quick links at the top of [the FAQ](https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org) seem to point to a new page (and therefore 404) rather than intra-page

**Comment by TheBB** [comment] 2016-08-14 19:10
Duplicate of https://github.com/syl20bnr/spacemacs/issues/4399 (fixed in develop)

**Closed by TheBB** 2016-08-14 19:10 UTC
Labels: Duplicate ☝
