### ISSUE TITLE
helm-resume not working for me on develop

### ISSUE THREAD

**Issue by YayConnolly** [syl20bnr/spacemacs#7223] opened 2016-09-29 23:00 UTC
#### Description :octocat:
`helm-resume` is not working for me on the develop branch. I get `helm-resume: No helm buffers found to resume` Any help debugging this would be much appreciated.

`C-x C-b` (`list-buffers`) shows some helm buffers like:

```
* *helm-mode-descr...     579 Hmm              
```

#### Reproduction guide :beetle:
- Start Emacs (evil, develop branch)
- `C-h f RET q` to open and quit helm
- `SPC r l`

*Observed behaviour:* :eyes: :broken_heart:
Error:  `helm-resume: No helm buffers found to resume`

*Expected behaviour:* :heart: :smile:
Helm reopens ready to filter functions

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(org auto-completion helm emacs-lisp evil-cleverparens unimpaired sql elixir
     (ruby :variables ruby-version-manager 'rvm ruby-enable-enh-ruby-mode t)
     ruby-on-rails dash git markdown vinegar)
```

**Comment by TheBB** [comment] 2016-10-09 07:41
helm-resume doesn't resume any helm session, just search-type ones (`SPC /`, `SPC ss` and such).

**Comment by TheBB** [comment] 2016-10-09 07:42
This easily reproduces in emacs -q so it's certainly a helm issue.

**Comment by YayConnolly** [comment] 2016-10-20 18:52
This is working for me now on develop-- `SPC r l`

As a separate question, is it possible to resume `describe-function`? For example was exploring the `evil-avy-*` functions, would be awesome to hop back to the list without filtering again.

**Comment by TheBB** [comment] 2016-10-21 06:56
No, you can't resume all kinds of helm sessions. (For whatever reason.) For that please consider following the original label and report upstream. :-)

**Comment by TheBB** [comment] 2016-10-21 06:56
Closing since fixed.

**Closed by TheBB** 2016-10-21 06:56 UTC
Labels: - Forum -, Should report upstream
