### ISSUE TITLE
`SPC t w` twice in magit buffer kills colors

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#4940] opened 2016-02-02 23:27 UTC
As title. Expected behavior is that the previous colors in the window would return after toggling whitespace display back off, which is what usually happens in other modes.

**Comment by TheBB** [comment] 2016-02-03 09:31
If this is reproducible in stock Emacs (+ magit) it should be reported to magit.

**Comment by lazywithclass** [comment] 2016-10-11 22:45
Reproduced in stock Emacs + magit, colors killed. I've opened an issue in magit.

**Comment by d12frosted** [comment] 2016-10-25 12:09
@lazywithclass thanks for reporting it upstream! Closing since already fixed there.

**Closed by d12frosted** 2016-10-25 12:09 UTC
Labels: Bug :-(, Git
