### ISSUE TITLE
Js syntax check error (Symbol’s function definition is void: flycheck-pos-tip-mode)

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#5973] opened 2016-05-04 09:20 UTC
#### Description
Javascript syntax checking wont work.

#### Reproduction guide
- Start Emacs
- Edit any .js file (with syntax checking enabled)

*Observed behaviour:*
Error message: Symbol’s function definition is void: flycheck-pos-tip-mode

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git syntax-checking version-control javascript php evil-commentary evil-snipe)
```

**Comment by stormpat** [comment] 2016-05-04 12:28
A workaround for this is simply to disable the tooltips.

```lisp
     (syntax-checking
       :variables
       syntax-checking-enable-tooltips nil)
```

**Comment by StreakyCobra** [comment] 2016-05-04 12:46
Do you have a `.emacs.d/elpa/flycheck-pos-tip…` folder? If no it's probably the cause. If yes try to remove it and restart.

**Comment by syl20bnr** [comment] 2016-05-04 12:56
Maybe MELPA issues again. Also try deleting the archives directory in elpa folder.

**Comment by stormpat** [comment] 2016-05-04 13:22
Yeah i tried to nuke the elpa dir a few times, and the package seems to be there after pulling all spacemacs deps.

```bash
~/.emacs.d/elpa                                                                                                                                         15d
> ls | grep pos-tip

flycheck-pos-tip-20160323.129
pos-tip-20150318.813
```

**Comment by StreakyCobra** [comment] 2016-05-04 14:08
can you put the output of  `ls -al` from within `flycheck-pos-tip-20160323.129` ?

**Comment by stormpat** [comment] 2016-05-05 08:32
Sure. Heres the output.

```bash
> ls -al flycheck-pos-tip-20160323.129

total 48

drwxr-xr-x    6 stormpat  staff   204 May  4 15:26 .
drwxr-xr-x  173 stormpat  staff  5882 May  4 15:34 ..
-rw-r--r--    1 stormpat  staff  1487 May  4 15:26 flycheck-pos-tip-autoloads.el
-rw-r--r--    1 stormpat  staff   264 May  4 15:26 flycheck-pos-tip-pkg.el
-rw-r--r--    1 stormpat  staff  4707 May  4 15:26 flycheck-pos-tip.el
-rw-r--r--    1 stormpat  staff  4654 May  4 15:26 flycheck-pos-tip.elc
```

**Comment by StreakyCobra** [comment] 2016-05-06 11:51
I have the same version, but files size are different. I don't know if it is normal or not:

```text
total 28
drwxr-xr-x 1 fabien fabien   230 28 mar 21:56 .
drwxr-xr-x 1 fabien fabien 22780  6 mai 13:05 ..
-rw-r--r-- 1 fabien fabien  1474 28 mar 21:56 flycheck-pos-tip-autoloads.el
-rw-r--r-- 1 fabien fabien   233 28 mar 21:56 flycheck-pos-tip-pkg.el
-rw-r--r-- 1 fabien fabien   638 28 mar 21:56 flycheck-pos-tip-pkg.elc
-rw-r--r-- 1 fabien fabien  4707 28 mar 21:56 flycheck-pos-tip.el
-rw-r--r-- 1 fabien fabien  4595 28 mar 21:56 flycheck-pos-tip.elc
```

How does your `flycheck-pos-tip-pkg.el` compare to mine?

```elisp
(define-package "flycheck-pos-tip" "20160323.129" "Display Flycheck errors in GUI tooltips" '((dash "2.12") (flycheck "0.22") (pos-tip "0.4.6")) :url "https://github.com/flycheck/flycheck-pos-tip" :keywords '("tools" "convenience"))
```

**Comment by stormpat** [comment] 2016-05-06 12:02
Hmm. Thats weird.

```lisp
;;; -*- no-byte-compile: t -*-
(define-package "flycheck-pos-tip" "20160323.129" "Display Flycheck errors in GUI tooltips" '((dash "2.12") (flycheck "0.22") (pos-tip "0.4.6")) :url "https://github.com/flycheck/flycheck-pos-tip" :keywords '("tools" "convenience"))

**Comment by StreakyCobra** [comment] 2016-05-06 12:21
Nothing that should prevent it from working I think. I'm not on OS X, nor emacs 25, maybe the issue is coming from this. Let's see if someone with a closer config to yours can help.

**Comment by rakkesh** [comment] 2016-05-09 11:05
I have a pretty similar configuration but I am not experiencing the reported problem with Spacemacs. For me the tooltip doesn't show at point, syntax checking shows messages in the `mini-buffer`.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git go javascript markdown org spell-checking syntax-checking version-control)
```
```sh
> ls -l ~/.emacs.d-24.5.1/elpa/flycheck-pos-tip-20160323.129/
total 56
-rw-r--r--  1 rakkesh  staff  1465 May  6 16:16 flycheck-pos-tip-autoloads.el
-rw-r--r--  1 rakkesh  staff   233 May  6 16:16 flycheck-pos-tip-pkg.el
-rw-r--r--  1 rakkesh  staff   638 May  6 16:16 flycheck-pos-tip-pkg.elc
-rw-r--r--  1 rakkesh  staff  4707 May  6 16:16 flycheck-pos-tip.el
-rw-r--r--  1 rakkesh  staff  4595 May  6 16:16 flycheck-pos-tip.elc
```

#### Alternate System Info
- OS: darwin
- Emacs: 25.0.93.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults dash emacs-lisp emoji erc git github javascript markdown org python restclient go spell-checking sql syntax-checking version-control)
```
```sh
> ls -l ~/.emacs.d-25.0.93.1/elpa/flycheck-pos-tip-20160323.129/
total 56
-rw-r--r--  1 rakkesh  staff  1465 Apr 11 17:02 flycheck-pos-tip-autoloads.el
-rw-r--r--  1 rakkesh  staff   233 Apr 11 17:02 flycheck-pos-tip-pkg.el
-rw-r--r--  1 rakkesh  staff   638 Apr 11 17:02 flycheck-pos-tip-pkg.elc
-rw-r--r--  1 rakkesh  staff  4707 Apr 11 17:02 flycheck-pos-tip.el
-rw-r--r--  1 rakkesh  staff  4595 Apr 11 17:02 flycheck-pos-tip.elc
```

**Comment by d12frosted** [comment] 2016-10-17 19:26
I was able to reproduce it earlier, but the problem gone with packages / Spacemacs update. Closing this. Let me know if you still have the problem.

**Closed by d12frosted** 2016-10-17 19:26 UTC
Labels: - Bug tracker -, JavaScript, To be reproduced
