### ISSUE TITLE
Bind the default describe key to its default Emacs bindings

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1117] opened 2015-04-12 07:39 UTC
Currently the default help key bindings do not have Helm activated, such as `C-h f` or `C-h v`. We should give it the same ones in `SPC h d`.

**Comment by syl20bnr** [comment] 2015-04-14 01:43
oh really ? I think they do but one has to lazy-load helm before it works.
So you propose to rebind them to a wrapper like this ? https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/keybindings.el#L74

**Comment by tuhdo** [comment] 2015-04-14 02:07
Yes.

**Comment by TheBB** [comment] 2015-08-25 19:38
I can't reproduce this, so I assume it has been fixed in the meantime. Feel free to reopen if not.

**Closed by TheBB** 2015-08-25 19:38 UTC
Labels: enhancement :-D, Helm, Key Bindings
