### ISSUE TITLE
<g> no longer works in Magit status screen

### ISSUE THREAD

**Issue by hansbogert** [syl20bnr/spacemacs#14181] opened 2020-12-01 11:41 UTC
#### Description :octocat:
\<g\> no longer works in Magit status screen

#### Reproduction guide :beetle:
- Start Emacs
- Start magit-status on a directory
- Press \<g\>

*Observed behaviour:* :eyes: :broken_heart:
Mini-buffer says "g- which-key: There are no keys to show"

*Expected behaviour:* :heart: :smile:
The buffer refreshes with magit's `magit-refresh`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. c62953401)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm go lsp javascript python html sql php markdown multiple-cursors yaml git neotree
                 (org :variables org-enable-reveal-js-support t)
                 plantuml
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment] 2020-12-01 11:58
Confirmed.

It seems to have been introduced in this commit:
syl20bnr/spacemacs@be90887 @ Change newly added which-key bindings to use keymap api

Possibly by this expression:
```elisp
(which-key-add-keymap-based-replacements magit-mode-map
    "<normal-state> g r" nil
    "<visual-state> g r" nil
    "<normal-state> g s" nil
    "<visual-state> g s" nil)
```

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6f830c149)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python shell spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by duianto** [comment] 2020-12-01 12:06
Maybe not, I tried limiting the expression to the `vim` and `hybrid` editing style.
```elisp
(when (memq dotspacemacs-editing-style '(vim hybrid))
      (which-key-add-keymap-based-replacements magit-mode-map
        "<normal-state> g r" nil
        "<visual-state> g r" nil
        "<normal-state> g s" nil
        "<visual-state> g s" nil))
```
But the which-key message is still shown:
>g-  which-key: There are no keys to show

**Comment by duianto** [comment] 2020-12-01 12:27
It was the other expression in the same commit.

A possible fix has been applied, pull the latest `develop` branch.

**Closed** 2020-12-02 07:43 UTC
Labels: Fixed in develop, Key Bindings, Which-key

**Comment by hansbogert** [comment] 2020-12-02 10:26
Oof those different editing styles make code very difficult doesn't it. Will try asap

**Comment by hansbogert** [comment] 2020-12-02 13:52
Works like a charm now, thanks @duianto

**Comment by marienz** [comment] 2020-12-05 13:30
I'm still seeing this. I'm using hybrid editing style with `hybrid-style-enable-evilified-state nil`, and it looks like that means I need the "emacs" behavior from this code.

I tried replacing the `memq` with `(spacemacs//support-evilified-buffer-p dotspacemacs-editing-style)` and that works for me (although that probably still doesn't handle changing the editing style on the fly... there's a `spacemacs-editing-style-hook` for that but I haven't tried to get that hooked up).

**Comment by duianto** [comment] 2020-12-06 16:11
>I'm still seeing this. I'm using hybrid editing style with hybrid-style-enable-evilified-state nil, and it looks like that means I need the "emacs" behavior from this code.

Confirmed.

@marienz Thanks for reporting this, and for the suggestion to check if the editing style supports evil navigation.

Your right it should also work when switching editing style in the current session
(a PR would be welcome).

For now, a fix for the hybrid without evil navigation, has been pushed to the `develop` branch.

**Comment by lebensterben** [comment] 2020-12-06 19:19
I'm using `evil` style editing, in the magit status screen,
- Pressing `g` alone shows `which-key`
- But, pressing `?` then `g` will do the refresh
