### ISSUE TITLE
d{motion} broken in all modes on recent develop branch

### ISSUE THREAD

**Issue by apahne** [syl20bnr/spacemacs#11536] opened 2018-11-01 08:44 UTC
I just switched to the development branch cb4a15608 and I'm using emacs 26.1 on Linux

In evil normal mode, `d` deletes the entire line. So combining a motion like `d3w`is just not possible.

This happens in all major modes I tried (Org, Lisp, Markdown)

**Comment by ljupchokotev** [comment] 2018-11-01 08:52
I can't reproduce this on the latest commit of the develop branch.

Can you share your `.spacemacs` file?

**Comment by apahne** [comment] 2018-11-01 09:41
Sorry for the messy config file, but here it is:

[spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/2537972/spacemacs.txt)

**Comment by tko** [comment] 2018-11-04 18:51
FWIW I've seen something similar happening randomly in different modes on (somewhat older) develop branch. That is, some keys (`d`, `c`, maybe others) stop expecting motions but feel more like as if they were capitalized. Haven't figured out a way to reproduce it. Can't recall if killing the buffer and reopening is sufficient to fix it, or if it takes emacs restart.

**Comment by ljupchokotev** [comment] 2018-11-04 18:54
Could it be https://github.com/syl20bnr/spacemacs/issues/10410 that is causing it? Try to reproduce it.

**Comment by apahne** [comment] 2018-11-08 20:01
Yes, I can reproduce #10410

**Comment by dijonkitchen** [comment] 2018-12-18 23:58
I've gotten this problem too and I think it's from searching with `/` as in #10410. The workaround of switching to the mini buffer and `ESC`'ing or fully restarting Spacemacs work, but are no fun.

**Comment by williamconnolly** [comment] 2018-12-21 04:32
Agreed - it retains the last-typed `/` search in the modeline, but grayed out. And every `d` press deletes an entire line. Only solution I've found is to restart Spacemacs. I'll try the mini-buffer escaping too.

**Comment by duianto** [comment] 2019-08-29 11:26
As `ljupchokotev` mentioned, this seems to be a duplicate of issue:
Evil search bug breaks Spacemacs #10410

The most up voted workaround can be found in this comment:
https://github.com/syl20bnr/spacemacs/issues/10410#issuecomment-391641439

**Closed** 2019-12-22 06:46 UTC
Labels: - Bug tracker -, Duplicate ☝, Evil, Mini-buffer
