### ISSUE TITLE
Unable to use some themes (e.g. darktooth and gruvbox)

### ISSUE THREAD

**Issue by wedens** [syl20bnr/spacemacs#8090] opened 2017-01-01 12:46 UTC
#### Description :octocat:
`darktooth` theme works only on first emacs launch after adding it.
Some other themes like `gruvbox` doesn't work with the same error.
Themes like `solarized-dark`, `leuven` work fine.
I suppose it has something to do with `autothemer`, but I'm not sure if it's upstream or spacemacs problem.

#### Reproduction guide :beetle:
- prepend `darktooth` to `dotspacemacs-themes` list in `.spacemacs`
- start emacs
- theme is installed and successfully applied
- restart emacs
- theme is not applied

*Observed behaviour:* :eyes: :broken_heart:
Theme is not applied with the warning:
```
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (file-error Cannot open load file No such file or directory autothemer))
```
No `darktooth` in `load-theme`.

*Expected behaviour:* :heart: :smile:
theme is applied on each emacs launch

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: nil (rev. 4289a496)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
 purescript javascript react sql emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 org myorg
 (scala :variables scala-auto-start-ensime nil)
 syntax-checking markdown yaml
 (spell-checking :variables spell-checking-enable-by-default nil)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 jabber)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "autothemer")
  require(autothemer)
  byte-code(I deleted it)
  require(darktooth-theme nil noerror)
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)
  (if (require pkg nil (quote noerror)) nil (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir))
  (let ((warning-minimum-level :error)) (if (require pkg nil (quote noerror)) nil (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)))
  configuration-layer/load-or-install-package(darktooth-theme)
  (let ((pkg (spacemacs//get-theme-package theme))) (configuration-layer/load-or-install-package pkg))
  (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (configuration-layer/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (configuration-layer/load-or-install-package pkg))))
  (if (or (memq theme (custom-available-themes)) (eq (quote default) theme)) nil (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (configuration-layer/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (configuration-layer/load-or-install-package pkg)))))
  (progn (if (or (memq theme (quote (zonokai-blue zonokai-red solarized-light solarized-dark doom-one doom-molokai)))) (progn (configuration-layer/load-or-install-package (quote dash)))) (if (or (memq theme (custom-available-themes)) (eq (quote default) theme)) nil (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (configuration-layer/load-or-install-package pkg))) (if (or (eq ... theme) (eq ... theme)) (progn (load-file ...) (load-file ...))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (configuration-layer/load-or-install-package pkg))))))
  (condition-case err (progn (if (or (memq theme (quote (zonokai-blue zonokai-red solarized-light solarized-dark doom-one doom-molokai)))) (progn (configuration-layer/load-or-install-package (quote dash)))) (if (or (memq theme (custom-available-themes)) (eq (quote default) theme)) nil (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg ...) (pkg-dir ...)) (if (or ... ...) (progn ... ...)) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg ...)) (configuration-layer/load-or-install-package pkg)))))) ((debug quote error) (setq theme (quote default)) (display-warning (quote spacemacs) (format (concat "An error occurred while retrieving the " "theme, using default theme. (error: %s)") err) :warning)))
  spacemacs/load-theme(darktooth)
  (let ((default-theme (car dotspacemacs-themes))) (spacemacs/load-theme default-theme) (setq configuration-layer--protected-packages (append (delq nil (mapcar (quote spacemacs//get-theme-package) dotspacemacs-themes)) configuration-layer--protected-packages)) (setq-default spacemacs--cur-theme default-theme) (setq-default spacemacs--cycle-themes (cdr dotspacemacs-themes)))
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/wedens/.emacs.d/init.el" nil t)  ; Reading at buffer position 1270
  load-with-code-conversion("/home/wedens/.emacs.d/init.el" "/home/wedens/.emacs.d/init.el" t t)
  load("/home/wedens/.emacs.d/init" t t)
  #[0 "\205\266

**Comment by ggarlic** [comment] 2017-01-03 06:34
this issue has been here for 2 days
i also have this problem with theme gruvbox

**Comment by gilbertw1** [comment] 2017-01-03 17:32
I've experienced this exact problem with gruvbox as well.

Version: 0.200.6
All packages up to date.

**Comment by gilbertw1** [comment] 2017-01-03 17:47
As a non-ideal temporary workaround you can make the themes work by manually loading autothemer.el and dash.el:

    wget https://raw.githubusercontent.com/magnars/dash.el/master/dash.el
    wget https://raw.githubusercontent.com/sebastiansturm/autothemer/master/autothemer.el

    ;; user-init
    (load-file "~/spacemacs/dash.el")
    (load-file "~/spacemacs/autothemer.el")

**Comment by capdevc** [comment] 2017-01-04 13:09
Looks like this is related to #7373 

Both darktooth and gruvbox want autothemer to be present.

**Comment by d12frosted** [comment] 2017-01-04 17:58
I am able to use `gruvbox` theme by setting `gruvbox` as first element of `dotspacemacs-themes`. The same goes to `darktooth`. That's probably because something else pulled `autothemer`. 

Meanwhile you can add both `dash` and `autothemer` to list of additional packages in your `.spacemacs` file.

I am closing this issue as it's a duplicate of #7373.

**Closed by d12frosted** 2017-01-04 17:58 UTC

**Comment by gilbertw1** [comment] 2017-01-04 23:20
This is definitely a duplicate of #7373 ... one thing I will mention though is that the themes are loaded before the packages are, so simply adding ```dash``` and ```autothemer``` to the list of additional packages won't fix the problem.

You actually need to load both packages somewhere like the ```user-init``` function, or manually load the theme yourself after emacs has loaded it's packages.

**Comment by d12frosted** [comment] 2017-01-05 07:01
> so simply adding dash and autothemer to the list of additional packages won't fix the problem

Oh, right.

**Comment by wedens** [comment] 2017-01-05 08:03
@d12frosted does it work for you after emacs restart?

**Comment by d12frosted** [comment] 2017-01-05 08:06
Using `gruvbox` and `darktooth` works for me by setting one of them as first element of `dotspacemacs-themes` list and starting new Emacs session. 😸 

Since it works as is, I haven't tried to fix it by adding `dash` and `autothemer` to list of additional packages. So this part was more like a shot in the sky and as @gilbertw1 elaborated, it should not help 😸

**Comment by wedens** [comment] 2017-01-09 03:02
@d12frosted can you try prepending `darktooth` to `dotspacemacs-themes`, start emacs (theme will be installed and applied) and then restart emacs? 😄

**Comment by gilbertw1** [comment] 2017-01-09 16:09
@wedens both themes were updated to use autothemer within the passed couple weeks, so this is a new issue caused by the themes themselved, not by anything changed with spacemacs. 

That being said, it looks like autothemer is getting to be pretty popular among emacs themes, so I'm guessing we'll want to figure out a way to support them.

**Comment by FryJay** [comment] 2018-04-20 00:01
I'm running into this on the latest version still but I noticed that autothemer and dash were now appearing in the elpa folder so I updated @gilbertw1's solution to load those versions like so:

  (mapc 'load (file-expand-wildcards "~/.emacs.d/elpa/dash-*/dash.el"))
  (mapc 'load (file-expand-wildcards "~/.emacs.d/elpa/autothemer-*/autothemer.el"))

**Comment by Enderguy58** [comment] 2018-07-01 04:19
@FryJay Where exactly did you put these functions for it to work?

**Comment by FryJay** [comment] 2018-07-09 01:46
Hi @Enderguy58 @sulami answered your question but I'll mention that I no longer find the lines to be necessary in the develop branch.  I removed the lines and both themes are working fine for me.

**Comment by tomsaleeba** [comment] 2020-04-12 11:48
On spacemacs master (commit d46eacd83842815b24afcb2e1fee5c80c38187c5), I managed to get gruvbox working with minimal hacking by making these two changes to `.spacemacs`

```
...
   dotspacemacs-additional-packages '(gruvbox-theme)
...
(defun dotspacemacs/user-config ()
...
  (load-theme 'gruvbox-dark-hard t)
)
```
It doesn't look exactly the same as what I'm used to in vim, but I compared it to the version from the megathemes pack and it looks the same, so I'm assuming everything is working. The only thing that doesn't seem the same is on the welcome screen, the horizontal separators stay spacemacs purple and don't change to gruvbox grey like they do on the megathemes version.
