### ISSUE TITLE
hydra/ivy package update error

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5948] opened 2016-04-30 21:50 UTC
#### Description

When updating packages, on restart Emacs report the following error:

    Error (use-package): ivy :config: Symbol's value as variable is void: hydra-ivy
    
To fix, you need to manually remove `hydra`, `ivy`, `counsel` and `swiper` and restart Emacs.  I'm not familiar with the details upstream, but it'd be nice if we could avoid handling this manually every time.
    
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b772734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(spacemacs-ivy spacemacs-layouts
               (auto-completion :variables auto-completion-enable-sort-by-usage t)
               better-defaults gtags ibuffer spell-checking syntax-checking semantic typography
               (chrome :variables edit-server-new-frame nil)
               dash elfeed finance mu4e org
               (shell :variables shell-default-shell 'shell shell-default-term-shell
                      (mir|with-executable "/usr/local/bin/fish" "/usr/bin/fish" "/usr/local/bin/zsh" "/usr/bin/zsh" "/bin/bash" "/bin/sh")
                      shell-default-height 50)
               prodigy restclient version-control git c-c   common-lisp csv emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml django mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-rc mir-rc-org mir-rc-qualia mir-rc-mu4e mir-rc-mail)
```

**Comment by darkfeline** [comment] 2016-04-30 21:55
https://github.com/abo-abo/swiper/issues/464

**Comment by zhexuany** [comment] 2016-05-01 01:56
Empty `elpa` in `~/.emacs.d` should fix this.

**Comment by darkfeline** [comment] 2016-05-01 04:56
I don't think redownloading 200+ packages every time to update 10 packages is a sustainable solution...

**Comment by sooheon** [comment] 2016-05-01 10:29
Yeah it has something to do with the order that the packages are installed. Can we try adding the `:ensure t` that abo-abo recommends in that linked thread?

**Comment by zilongshanren** [comment] 2016-05-01 12:52
@darkfeline 

Try to call `byte-compile` `elpa/ivy/ivy-hydra.el` could solve this issue.

**Comment by sooheon** [comment] 2016-05-01 13:15
@zilongshanren It does fix the issue. The question now is how can this be automated without needless overhead.

**Comment by syl20bnr** [comment] 2016-05-01 13:27
The issue is not Spacemacs, the issue is that dependencies are not set right in the package. The user should never have to guess the installation order of packages!!!

**Comment by nbecker** [comment] 2016-05-05 11:33
This morning rm -rf elpa did NOT fix it.
manually remove hydra, ivy, counsel and swiper and restart Emacs
did work, but you don't define "manually remove".  I did
rm -rf
of each of the elpa directories

**Comment by d12frosted** [comment] 2016-05-11 05:02
FYI, The problem still exists 😸

**Comment by d12frosted** [comment] 2016-05-14 10:37
Ah well. The problem exists and hurts so much. Removing all ivy related packages doesn't help at all.

**Comment by d12frosted** [comment] 2016-05-14 10:58
Somehow `(require 'ivy-hydra)` doesn't work and throws error. What really works -

1. start emacs and ignore the error
2. open `ivy-hydra.el` inside of `elpa/ivy` 
3. call `byte-compile-file` on `ivy-hydra.el`
4. restart

That's what was said in https://github.com/abo-abo/swiper/issues/464#issuecomment-206449056

**Comment by syl20bnr** [comment] 2016-05-14 12:43
This issue should be fixed upstream, there is an unhealthy declaration of dependencies somewhere, there is nothing we can do on the Spacemacs side, or more precisely we won't implement counter measures for bad dependencies in packages, it has to be fixed at the package level.

**Comment by syl20bnr** [comment] 2016-05-15 15:57
I'm on it. I think we can leverage the layer system to circumvent this behavior.

**Comment by syl20bnr** [comment] 2016-05-15 23:38
Actually I proposed another approach upstream. For now I deactivated `ivy-hydra` in Spacemacs (commit coming soon this evening).

**Comment by sooheon** [comment] 2016-05-20 07:58
@syl20bnr can we leave ivy-hydra in? I'd rather have to deal with a non-terminal warning than not have the functionality at all.

**Comment by d12frosted** [comment] 2016-05-20 08:01
AFAIK, It's not a warning, but error that doesn't allow to properly load all configurations.

**Comment by zilongshanren** [comment] 2016-05-20 08:10
@d12frosted 
now a new package named ivy-hydra has been published on melpa, the spacemacs-ivy should be refactor a little bit now.

**Comment by d12frosted** [comment] 2016-05-20 08:14
@zilongshanren ah, I missed that it's already separate package. So ya, better to refactor and roll it in 😄

**Comment by syl20bnr** [comment] 2016-06-02 03:15
Should be fixed in develop, anyone can confirm ?

**Comment by darkfeline** [comment] 2016-06-02 08:18
`ivy-hydra` seems to be broken: `C-o` in ivy reports `Symbol's function definition is void: ivy--matcher-desc`

**Comment by zilongshanren** [comment] 2016-06-02 08:30
@darkfeline  
You should upgrade Spacemacs to the latest develop branch and reboot your Emacs, it will get ivy-hydra installed, then the error `Symbol's function definition is void: ivy--matcher-desc` disappeared.

**Comment by darkfeline** [comment] 2016-06-02 16:12
@zilongshanren Of course, I forgot about that since I usually keep Spacemacs up to date.

@syl20bnr Looks good here.

**Comment by syl20bnr** [comment] 2016-08-26 02:37
Closing it as it is a 0.200 milestone issue.

**Closed by syl20bnr** 2016-08-26 02:37 UTC
Labels: - Bug tracker -, Fixed in develop, Ivy, Reported upstream
