### ISSUE TITLE
dotspacemacs-fullscreen-at-startup malfunctions on reload

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#3205] opened 2015-09-30 04:49 UTC
when `dotspacemacs-fullscreen-at-startup t`, reloading config (`SPC f e R`) toggles the fullscreen state (full -> not full, not full -> full). Expected behavior: fullscreen state should not change on reload, only at startup, and it certainly shouldn't toggle full -> not full. See #277

**Comment by TheBB** [comment] 2015-09-30 07:31
Unfortunately, there is no variable that holds the current full-screen or maximized status, so these toggles are somewhat defective. We have to write a bit of a hack to make it work. :-)

I'm closing this is a duplicate of #1088. I think I know how to do it, though... I should have a PR soonish.

**Closed by TheBB** 2015-09-30 07:31 UTC

**Comment by TheBB** [comment] 2015-09-30 13:06
#3211
