### ISSUE TITLE
mu4e layer

### ISSUE THREAD

**Issue by kostajh** [syl20bnr/spacemacs#1177] opened 2015-04-15 14:52 UTC
Hi @syl20bnr,

Any interest in a mu4e layer? It would need additional setup outside of just specifing `mu4e` in one's configuration layer, because installing `mu` and `mu4e` is a bit of a manual process.

**Comment by darkfeline** [comment] 2015-04-17 01:24
I maintain a personal layer for mu4e that I've configured for sending email using multiple SMTP accounts.  I'm not sure if spacemacs needs one though at setting up email is very user-specific.

**Comment by kostajh** [comment] 2015-04-17 01:31
@darkfeline I agree. The impetus for me is that company-mode is no longer enabled by default. I guess that's easy enough to fix in my private layer, but might as well add a global one with some keybindings, on?

**Comment by darkfeline** [comment] 2015-04-17 01:50
Now that you mention it, company stopped autocompleting mu4e contacts for me recently, instead helm is handling it now.

**Comment by jtmoulia** [comment] 2015-04-17 17:31
I'd love more people to find mu4e -- it's the best email client I've used in Emacs or anywhere for that matter. But, like @kostajh was saying, there's some leg-work to get it set up. By providing a layer with a readme and spacemacs-esque keybindings we'd help at least spacemacs people discover and get started with it. Plus, it sounds like spacemacs is unexpectedly interacting with mu4e :)

@darkfeline re the fact that much of the config is user-specific -- totally agree. I tend to think a separate file for user-specific config similar to gnus' `~/gnus.el` would be a good way to handle those settings. Said by @syl20bnr in #386 re gnus:

> I would let the user provide the configuration file and define a layer variable to point to it. The layer would then load this file.

Farther down the line, I think providing some code to help work with multiple accounts could be useful. For example, neyond hardwiring the folders in a search, mu4e doesn't give much help for getting messages across multiple accounts' inboxes.

I also have a very basic private mu4e layer, and would be happy to contribute.

Potentially we can take notes or coordinate with #1017 to provide a somewhat consistent interface across mail readers.

**Comment by leonbaum** [comment] 2015-04-17 18:21
+1 for anything that makes mu4e easier to use with spacemacs.

As someone who doesn't really know elisp and just started using spacemacs, I'm dreading getting my mailboxes set up again when I switch to spacemacs on my machine where I read mail.

**Comment by moesasji** [comment] 2015-04-18 07:40
+1 from me as well as I find it hard to see how to integrate mu4e as a layer and gnus appears to alien. Making this easier would be attractive for those vim-users like myself that are attracted to spacemacs because it gives access to org-mode.

**Comment by andreas-h** [comment] 2015-07-30 21:51
+1

any news on this idea? I think it would be great to have mu4e properly integrated, with consistent keybindings and all.

**Comment by robbyoconnor** [comment] 2015-07-30 22:12
Just make it and do a PR -- worst he can do is not merge it and it becomes a private layer for you.

**Comment by numkem** [comment] 2015-07-31 21:14
@darkfeline would you mind sharing your private layer? Could be a starting block or at least something to work with?

**Comment by jtmoulia** [comment] 2015-08-01 21:54
I've been using this: https://github.com/jtmoulia/spacemacs/commit/c0efd47be545883d2bc6e1be76db4e3a7aa7eb7c. Some of the layer's holes are listed in the commit description, but people are welcome to it -- I'm not going to have time to wrap it up in the next month.

**Comment by darkfeline** [comment] 2015-08-02 05:40
Seems like there's demand for it, so I made a branch/pull request using my private layer as a base.  Feel free to improve upon it.

https://github.com/syl20bnr/spacemacs/pull/2514

**Comment by kepi** [comment] 2015-08-13 21:50
I got `Wrong number of arguments: (2 . 2), 3` any time I switch to visual mode in `mu4e-view` mode. I guess its what @jtmoulia referring as outstanding issue "fix mu4e-view copy/paste keybindings"

Also it seams that no matter how I'm trying, I'm not able to add major mode "menu" for mu4e. I tried this:

```lisp
      (evil-leader/set-key-for-mode 'mu4e-headers-mode
        "mo" 'mu4e-headers-change-sorting)
```

but `SPC m o` or `, o` giving me `undefined`.

Thanks for ideas.

**Comment by darkfeline** [comment] 2015-08-14 00:10
> any time I switch to visual mode in `mu4e-mode`

Cannot reproduce, works for me.

> I'm not able to add major mode "menu" for mu4e

Try playing with the quoting?

      (evil-leader/set-key-for-mode 'mu4e-headers-mode
        "mo" mu4e-headers-change-sorting)

**Comment by jtmoulia** [comment] 2015-08-14 11:37
Hey @kepi -- "fix mu4e-view copy/paste keybindings" referred more to the fact that in `mu4e-view` mode <kbd>y</kbd> switches to the `mu4e-headers` buffer instead of yanking.

**Comment by kepi** [comment] 2015-08-14 11:54
@jtmoulia yes, I thought this two things are related that because of wrong number of arguments, evilify doesnt change y to yank but I'm maybe wrong.

@darkfeline thanks, I'll try it

**Comment by kepi** [comment] 2015-08-14 22:35
@darkfeline playing with quotes - It actually probably doesnt make sense. I'm not much elisp guy but I believe I have it right. It is working in different layers/modes, just not in mu4e

Anyway I don't understand from where this error (wrong number of arguments) is coming from. Friend tried to make new mu4e layer and he have same problem :/

**Comment by kepi** [comment] 2015-08-25 22:12
I found where the problem with wrong number of arguments and not working yanking is. There is bug in evilified states which causes this. Fortunately it is fixed in develop branch of spacemacs.

**Comment by sindikat** [comment] 2015-09-13 14:30
What's the status on mu4e layer PR? Is it going to be merged?

**Comment by kostajh** [comment] 2015-11-24 17:58
I'm using it in `develop`. Works well! Thanks everyone who worked on it.

**Comment by kshmelkov** [comment] 2015-12-05 12:15
Might be a wrong issue, but does this layer include sane keybindings in message compose mode? `SPC m` doesn't exist here :(

**Comment by StreakyCobra** [comment] 2015-12-05 13:34
@kshmelkov Your question will have more visibility and help if you open a new issue and give a reproduction step (even if it's trivial) :-)

**Comment by kshmelkov** [comment] 2015-12-05 13:48
@StreakyCobra ok. I thought that this issue was intentionally left open for the feedback.

**Comment by StreakyCobra** [comment] 2015-12-05 13:52
No, we keep issues open (except if original posters want to close them) and mark them as `Fixed in develop` until the next release :relaxed:

**Closed** 2016-01-04 08:43 UTC
Labels: discussion, Email, Fixed in develop, New Layer
