### ISSUE TITLE
Emacs keeps asking "perspective names to save" when trying to do `kill-emacs`

### ISSUE THREAD

**Issue by Sorrow17** [syl20bnr/spacemacs#7434] opened 2016-10-17 05:44 UTC
#### Description :octocat:
Emacs keeps asking "perspective names to save" when I try to do `kill-emacs`

#### Reproduction guide :beetle:
- Start Emacs
- Run `kill-emacs`

*Observed behaviour:* :eyes: :broken_heart:
Emacs keeps asking "perspective names to save" in minibuffer.

*Expected behaviour:* :heart: :smile:
Emacs process closes.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: develop (rev. 22809a8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp python
     (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
     git latex java markdown org shell)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```

```

**Comment by robbyoconnor** [comment] 2016-10-17 05:52
Duplicate of #7409

**Comment by robbyoconnor** [comment] 2016-10-17 05:53
Close this.

**Closed** 2016-10-17 08:10 UTC
Labels: Duplicate ☝

**Comment by Sorrow17** [comment] 2016-10-17 16:33
My bad... I only search the google but forgot I can search the issues themselves...

**Comment by robbyoconnor** [comment] 2016-10-17 18:40
You have to search the issues themselves...or visit the Gitter chat...we talked about it
