### ISSUE TITLE
Can't run magit-commit when running with daemon mode

### ISSUE THREAD

**Issue by kangjianbin** [syl20bnr/spacemacs#6777] opened 2016-08-06 10:00 UTC
#### Description :octocat:
Can't run magit-commit when running with daemon mode
It works if run emacs with only magit:
```sh
cd /path/to/magit
emacs --daemon -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-20160510.1127/ -L ../with-editor-20160408.201/ -L lisp -L ../git-commit-20160519.950 -L ../magit-popup-20160519.950/ -L . -l magit
```

#### Reproduction guide :beetle:
- Start Emacs in daemon mode
  emacs --daemon
- Open an new frame with emacsclient (need '-n' to reproduce the issue)
  emacsclient -n -c
- run magit-status and commit some change.

*Observed behaviour:* :eyes: :broken_heart:
magit git process buffer report:
>  1 git … commit --
Waiting for Emacs...
*ERROR*: Wrong type argument: processp, nowait
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.

*Expected behaviour:* :heart: :smile:
Open the commit buffer to write git comments.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. e51a89a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(org html javascript python markdown c-c   auto-completion go git better-defaults csharp ivy syntax-checking emacs-lisp)
```

**Comment by TheBB** [comment] 2016-08-06 12:43
I'm unable to reproduce this.

**Comment by kangjianbin** [comment] 2016-08-08 05:28
I can reproduce it in another computer running debian sid.
I also tried to comment out all my own configurations (leaving 'dotspacemacs/user-init' and 'dotspacemacs/user-config' empty), still hit this problem.

**Comment by Bad-ptr** [comment] 2016-08-08 09:58
Just in case... try removing `persp-init-new-frame` from the `after-make-frame-functions`:
`(remove-hook 'after-make-frame-functions 'persp-init-new-frame)`.
Let us know if it helps(I will ask you to test a fix).

**Comment by kangjianbin** [comment] 2016-08-08 12:58
No, it doesn't work. 
I commented out the add-hook 'after-make-frame-functions in persp-mode.el, still have problem.

**Comment by kangjianbin** [comment] 2016-08-08 14:50
The issue is not magit related. Reproduce in shell:
[~]$ emacs --daemon
[~]$ emacsclient -n -c
[~]$ /usr/bin/emacsclient --socket-name=/tmp/emacs1000/server .bashrc
Waiting for Emacs...
*ERROR*: Wrong type argument: processp, nowait

if run with -Q, everything works
[~]$ emacs --daemon -Q
[~]$ emacsclient -n -c
[~]$ /usr/bin/emacsclient --socket-name=/tmp/emacs1000/server .bashrc
Waiting for Emacs...

**Comment by Bad-ptr** [comment] 2016-08-08 15:06
> I commented out the add-hook 'after-make-frame-functions in persp-mode.el, still have problem.

Did you made `M-x byte-recompile-file RET persp-mode.el RET`?

Anyway try this:
```bash
emacs --daemon
emacsclient --eval after-make-frame-functions
emacsclient --eval "(remove-hook 'after-make-frame-functions 'persp-init-new-frame)"
emacsclient -n -c
/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server .bashrc
```
If it didn't help try removing elements from `after-make-frame-functions` one by one:
`emacsclient --eval "(pop after-make-frame-functions)"` (https://github.com/syl20bnr/spacemacs/issues/5219#issuecomment-189233077)
Also check out `before-make-frame-hook` and `server-switch-hook`.

**Comment by kangjianbin** [comment] 2016-08-08 15:15
After eval (pop server-switch-hook), emacsclient works. server-switch-hook is (before pop):
>server-switch-hook is a variable defined in `server.el'.
Its value is (persp-server-switch)

**Comment by Bad-ptr** [comment] 2016-08-08 15:46
Ok, then I think this should fix it(please test):
(eval before creating a frame)
```elisp
(defun persp-generate-frame-server-switch-hook (opt)
  (if opt
      (eval
       `(lambda (frame)
          ,(if (functionp opt)
               `(funcall ,opt frame)
             `(let* ((frame-client (frame-parameter frame 'client))
                     (frame-client-bl (when (processp frame-client)
                                        (process-get frame-client 'buffers))))
                ,(case opt
                   (only-file-windows
                    `(if frame-client
                         (when frame-client-bl
                           (mapc #'(lambda (w)
                                     (unless (memq (window-buffer w) frame-client-bl)
                                       (delete-window w)))
                                 (window-list frame 'no-minibuf)))
                       (let (frame-server-bl)
                         (mapc #'(lambda (proc)
                                   (setq frame-server-bl (append frame-server-bl (process-get proc 'buffers))))
                               (server-clients-with 'frame nil))
                         (when frame-server-bl
                           (mapc #'(lambda (w)
                                     (unless (memq (window-buffer w) frame-server-bl)
                                       (delete-window w)))
                                 (window-list frame 'no-minibuf))))))
                   (only-file-windows-for-client-frame
                    `(when frame-client-bl
                       (mapc #'(lambda (w)
                                 (unless (memq (window-buffer w) frame-client-bl)
                                   (delete-window w)))
                             (window-list frame 'no-minibuf))))
                   (t nil))))))
    nil))
```

Optionally it would be interesting to know, what is the value of the `last-command` in server-switch-hook for your case. Eval this:
```elisp
(defun persp-server-switch ()
  (message "TEST-PERSP-SERVER-SWITCH: %s" last-command))
```
Then create a frame with magit-commit, and post here what you will get in *Messages* buffer.

**Comment by kangjianbin** [comment] 2016-08-08 15:58
The fix doesn't work. I created a  frame, ran the fix,  closed the frame then created a new frame with 'emacsclient -n -c', still got the issue.

For the new persp-server-swith, the output of Message buffer is:
>Running git commit --
(No files need saving)
Running git commit --
Diffing changes to be committed (C-g to abort diffing)
(No files need saving)
Diffing changes to be committed (C-g to abort diffing)
TEST-PERSP-SERVER-SWITCH: magit-commit
When done with a buffer, type m c
Type m c to finish, or m k to cancel

**Comment by kangjianbin** [comment] 2016-08-08 16:00
I 'persp-generate-frame-server-switch-hook' in my startup files  (loaded by 'dotspacemacs/user-config'), didn't work either.

**Comment by kangjianbin** [comment] 2016-08-08 16:29
When run with 'emacsclient -c', (frame-parameter (selected-frame) 'client) returns something like '#<process server <17>>',
when run with 'emacsclient -n -c', it returns 'nowait'.

**Comment by Bad-ptr** [comment] 2016-08-08 17:36
Hmmm... Very strange.
Let's try this then:
Start emacs, eval this code:
```elisp
(defvar persp-server-switch-debug-list nil)

  (defun persp-server-switch ()
    (push "1-1 Enter persp-server-switch" persp-server-switch-debug-list)
    (let* ((frame (selected-frame))
           (persp-server-switch-hook (frame-parameter frame 'persp-server-switch-hook)))
      (push (format "1-2 Inside let* in persp-server-switch: %s %s"
                    frame persp-server-switch-hook)
            persp-server-switch-debug-list)
      (when persp-server-switch-hook
        (push "1-3 persp-server-switch-hook is not nil in persp-server-switch"
              persp-server-switch-debug-list)
        (unless (string-match-p "^.*magit.*$" (symbol-name last-command))
          (push "1-4 last-command is not a magit command in persp-server-switch:"
                persp-server-switch-debug-list)
          (funcall persp-server-switch-hook frame))
        (push "1-666 set frame's persp-server-switch-hook to nil"
              persp-server-switch-debug-list)
        (set-frame-parameter frame 'persp-server-switch-hook nil)
        (push "1-999 exit from persp-server-switch"
              persp-server-switch-debug-list))))

  (defun persp-generate-frame-server-switch-hook (opt)
    (if opt
        (eval
         `(lambda (frame)
            ,(if (functionp opt)
                 `(funcall ,opt frame)
               `(let* ((frame-client (frame-parameter frame 'client))
                       (frame-client-bl (when (processp frame-client)
                                          (process-get frame-client 'buffers))))
                  (push (format "2-1 persp-server-switch-hook %s %s %s" frame frame-client frame-client-bl)
                        persp-server-switch-debug-list)
                  ,(case opt
                     (only-file-windows
                      `(if frame-client
                           (when frame-client-bl
                             (mapc #'(lambda (w)
                                       (unless (memq (window-buffer w) frame-client-bl)
                                         (delete-window w)))
                                   (window-list frame 'no-minibuf)))
                         (let (frame-server-bl)
                           (mapc #'(lambda (proc)
                                     (setq frame-server-bl (append frame-server-bl (process-get proc 'buffers))))
                                 (server-clients-with 'frame nil))
                           (when frame-server-bl
                             (mapc #'(lambda (w)
                                       (unless (memq (window-buffer w) frame-server-bl)
                                         (delete-window w)))
                                   (window-list frame 'no-minibuf))))))
                     (only-file-windows-for-client-frame
                      `(when frame-client-bl
                         (mapc #'(lambda (w)
                                   (push (format "2-2 window loop: %s" w)
                                         persp-server-switch-debug-list)
                                   (unless (memq (window-buffer w) frame-client-bl)
                                     (push "2-3 delete window"
                                           persp-server-switch-debug-list)
                                     (delete-window w)))
                               (window-list frame 'no-minibuf))
                         (push "2-4 exit from persp-server-switch-hook"
                               persp-server-switch-debug-list)))
                     (t nil))))))
      nil))
```
then try creating frame
then eval `(message "%s" (mapconcat #'identity (reverse persp-server-switch-debug-list) "\n"))`
and post results here

**Comment by Bad-ptr** [comment] 2016-08-08 17:46
ah, after redefining the `persp-generate-frame-server-switch-hook`, run `M-: (persp-set-frame-server-switch-hook (selected-frame)) RET`

**Comment by kangjianbin** [comment] 2016-08-09 01:16
Do you mean M-: (persp-generate-frame-server-switch-hook (selected-frame))?
Evaluating (persp-generate-frame-server-switch-hook (selected-frame)) fixed the issue. 
Thanks a  lot!

**Comment by Bad-ptr** [comment] 2016-08-09 11:12
> Do you mean M-: (persp-generate-frame-server-switch-hook (selected-frame))?

Actually no, but may be it is needed too, but it should be called with a `persp-server-switch-behaviour` as the argument (not the selected-frame). You can set the `persp-server-switch-behaviour` to `nil` for the same result.

Anyway I just committed a change that possibly fixes this bug, so try to update the persp-mode.

**Comment by kangjianbin** [comment] 2016-08-09 13:25
I applied the commit '92daf414c57bb7e8d48483bd6e5176ba63d3ab31' and the issue is fixed.
Thanks.

**Comment by TheBB** [comment] 2016-08-09 13:33
I'll take the liberty to close then. Thank you @kangjianbin and @Bad-ptr.

**Closed by TheBB** 2016-08-09 13:33 UTC
Labels: - Bug tracker -, Fixed upstream
