### ISSUE TITLE
`SPC k` has nothing bound to it in emacs-lisp mode

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#4151] opened 2015-12-11 17:09 UTC
When I hit `SPC k` within my spacemacs file I get 

```
SPC k-  which-key: There are no keys to show
```

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. fc72c37)
- Distribution: spacemacs
- Layers:
```elisp
(better-defaults emacs-lisp markdown syntax-checking
                 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle)
                 erlang elixir git dash html org colors spacemacs-layouts osx github javascript react deft floobits ruby semantic unimpaired
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking ranger)
```

**Comment by justbur** [comment] 2015-12-11 18:16
Yep, you're right. It's a bug in evil-lisp-state. See https://github.com/syl20bnr/evil-lisp-state/pull/19

**Comment by justbur** [comment] 2015-12-11 18:16
@syl20bnr

**Comment by syl20bnr** [comment] 2015-12-11 22:40
mmmmhh I'm full up to date and I cannot reproduce this bug  :-(

**Comment by aaronjensen** [comment] 2015-12-12 05:34
@syl20bnr I just updated again and it's still broken. Here's my `.spacemacs`: https://github.com/aaronjensen/dotfiles/blob/master/spacemacs

**Comment by aaronjensen** [comment] 2015-12-12 05:38
@syl20bnr https://github.com/syl20bnr/evil-lisp-state/pull/19 fixes it for me.

**Comment by justbur** [comment] 2015-12-12 13:00
@syl20bnr to properly test this you need to remove evil-lisp-state.elc since any macros would be expanded already inside.

**Comment by justbur** [comment] 2015-12-12 15:59
I have a much simpler fix for this. When I get a chance today I'll make a new pr

**Comment by syl20bnr** [comment] 2015-12-13 03:43
I still cannot reproduce it, I removed evil-lisp-state from elpa directory and restarted, evil-lisp is installed and work.

**Comment by syl20bnr** [comment] 2015-12-13 03:49
No matter how hard I try I cannot hit this bug, that's so strange.
cc @TheBB @StreakyCobra

**Comment by aaronjensen** [comment] 2015-12-13 07:45
@syl20bnr It is probably because I have this:

```
  (with-eval-after-load 'smartparens
    (show-smartparens-global-mode -1))
```

**Comment by StreakyCobra** [comment] 2015-12-13 11:01
I had twice a problem with `SPC k` recently. The first time ([November 30, 2015 11:18 AM](https://gitter.im/syl20bnr/spacemacs?at=565c225b2753fafb4af61660)) it was weird, I had to wipe the `elpa` dir totally. The second time just wiping `evil-lisp-state` was enough, but I was not having time to debug sadly.

I just tried emacs 24.5.1 (ubuntu 15.10 version, I don't have OS X), on last develop, with the provided `.spacemacs` and a clean `.emacs.d`: I can't reproduce it :pensive:

**Comment by justbur** [comment] 2015-12-13 12:55
I can't explain the inconsistent behavior between people's machines, but I think the source of the problem is [here](https://github.com/syl20bnr/evil-lisp-state/blob/master/evil-lisp-state.el#L173-L181), where `SPC k` is being bound to two different keymaps at the same time one of which is empty (`evil-lisp-state-major-mode-map`). I think the `SPC k` keys are missing problem is just that emacs sees an empty keymap bound to `SPC k`.

There's a really simple way to avoid this issue entirely and that's to only bind `SPC k` once, as in #4159. I could try to investigate exactly why the behavior is inconsistent, but I don't think it's worth it in this case.

**Comment by StreakyCobra** [comment] 2015-12-13 15:09
I have it just now. @justbur do you want me to try something? If yes I am on gitter.

**Comment by StreakyCobra** [comment] 2015-12-13 15:39
A few information that I looked for in `emacs-lisp-mode` (editing my `.spacemacs`):

`SPC ?` says that `SPC k` is bound to `evil-lisp-state-major-mode-map-prefix` in `evil-lisp-state-major-mode-map-activate` minor mode. It appears twice in the list :eyes:

After pressing `SPC`, `which-key` lists `k -> +lisp`.
After pressing `SPC k`, `which-key` print `which-key: There are no keys to show`. The key guide stays open and wait for another key.
After pressing `SPC k X` where `X` is any letter, emacs says: `SPC k X is undefined`.

I noticed completion is not working either.

**Comment by StreakyCobra** [comment] 2015-12-13 16:01
Restarting Emacs doesn't solve the issue. I took this opportunity to test @justbur PR and… it works.

I switched a few time between `develop` and https://github.com/syl20bnr/spacemacs/pull/4159, and the bug is there when not applied, and disappear when it is.

**Comment by syl20bnr** [comment] 2015-12-13 18:34
@StreakyCobra Do you have any repro step to trigger the bug ?

It may be annoying but I won't apply the fix until we know exactly what's going on, if there is a lurking bug given a certain kind of setup we must unveil it and be sure to correct it.

> evil-lisp-state-major-mode-map-activate minor mode. It appears twice in the list

What is this minor mode and why is it listed twice ?

**Comment by StreakyCobra** [comment] 2015-12-13 19:01
Nope, I'm not even sure when the bug appeared. I don't use this really often, but I'll try to be more careful now.

**Comment by justbur** [comment] 2015-12-13 19:34
I'm not able to reproduce this anymore but for anyone running into this. This should resolve the problem

`M-: (setq evil-lisp-state-major-mode-map-prefix evil-lisp-state-map-prefix)`

**Comment by syl20bnr** [comment] 2015-12-14 02:15
This bug is going to drive me nuts... if only I could trigger.
@aaronjensen can you prodive your whole dotfile removed from any personal info ?

**Comment by aaronjensen** [comment] 2015-12-14 02:32
@syl20bnr it's just https://github.com/aaronjensen/dotfiles/blob/master/spacemacs you don't need anything else in my dotfiles. If you want to use my whole environment, my dotfiles at https://github.com/aaronjensen/dotfiles are actually stripped of personal info as other people use them as well.

**Comment by justbur** [comment] 2015-12-14 02:34
Let me give some more background on how bind-map works and maybe this will help (for the record the bug showed up once for me, but I can't reproduce it anymore). 

evil-lisp-state is using bind-map twice as I said, once to bind evil-lisp-state-map, which holds all of the bindings, and once to bind evil-lisp-state-major-mode-map, which is completely empty at the moment.

1. `evil-lisp-state-map` should sit highest in priority do the `:evil-use-local` option (2(iii) referring to   https://github.com/syl20bnr/spacemacs/wiki/Keymaps-guide). This puts it in `evil-normal-state-local-map` every time `evil-local-mode` is activated in a buffer. 

2. `evil-lisp-state-major-mode-map` (remember this is empty) sits at the next highest priority (2(iv) in the guide), and is activated each time `evil-normalize-keymaps` is called in normal state (on state changes primarily), but since it has lower priority it should be shadowed by `evil-lisp-state-map`. 

For this bug to occur it must somehow be that the priority is flipped. I don't know how this could occur, and I don't have any guesses really. **However**, this situation is avoidable by just not binding the `evil-lisp-state-major-mode-map` in the first place **or** filling it with the same keybindings. The simplest solution in my opinion is to not make a separate call to `bind-map` in the evil-lisp-state code (since the major-mode functionality is not being used bind-map is overkill in this case) and just bind the map to the `spacemacs-default-map` which already has the same priority. This is the solution given in #4151.

I understand the sentiment that we'd like to be able to reproduce this, but in this case I'd rather just simplify the clearly strange code (binding an empty map to the same key as the map you want) and see if it reoccurs after that (it really really shouldn't).

**Comment by StreakyCobra** [comment] 2015-12-14 22:23
I don't know if it's related (probably not) but there is a warning when compiling `evil-lisp-state` after deleting it from `elpa/`:

```text
evil-lisp-state.el:344:1:Warning: the following functions are not known to be defined:
    evil-lisp-state-map-override-mode,
    global-evil-lisp-state-map-override-mode
```

**Comment by justbur** [comment] 2015-12-14 23:25
@StreakyCobra I pushed an update to bind-map to get rid of those warnings, but this shouldn't have caused any problems

**Comment by StreakyCobra** [comment] 2015-12-14 23:28
Ok. As I don't know how to reproduce the bug I can't test anyway.

**Comment by rcanepa** [comment] 2015-12-15 00:59
Has anyone one found a workaround to fix it temporarily?. I have been bouncing between issues trying to find a fix but nothing that I tried has solved the problem. Could be this solved reinstalling spacemacs?

**Comment by aaronjensen** [comment] 2015-12-15 01:28
@rcanepa https://github.com/syl20bnr/evil-lisp-state/pull/19 fixes it, you may need to delete the .elc file after installing the patch, however.

**Comment by StreakyCobra** [comment] 2015-12-15 10:33
Another workaround that could work is to delete the `~/.emacs.d/elpa/evil-lisp-state…` and restart emacs.

**Comment by rcanepa** [comment] 2015-12-15 13:09
I tried both solutions and nothing happened. Thanks anyway!

**Comment by synic** [comment] 2015-12-18 14:11
Reinstalling also did it for me.

**Comment by syl20bnr** [comment] 2015-12-21 07:03
Time to dig this bug very deep :-)
@justbur Do you confirm that merging #4159 is sufficient or do I need the change in evil lisp state repo ? (anyway I will merge the PR in evil lisp state repo as well)

**Comment by justbur** [comment] 2015-12-21 14:40
@syl20bnr For the evil-lisp-state code, if it were me I would provide clear instructions for the user bind the keys themselves. That way you can just focus on filling up the map (a single one not two of them) and not worry about how it's used. Here's some sample instructions (of course you could provide convenience functions if you want). 

```elisp
;; if you want evil-lisp-state-map to be available from normal state globally
(define-key evil-normal-state-map (kbd "<KEY>") evil-lisp-state-map)

;; if you want evil-lisp-state-map to be available when certain major-modes are active, you can use the bind-map macro from the bind-map package on MELPA like this
(bind-map evil-lisp-state-map
  :major-modes (emacs-lisp-mode lisp-mode) ;; add or remove modes here
  :evil-keys ("<KEY>")
  :evil-states (normal))
```

**Closed** 2016-01-04 08:33 UTC
Labels: bug :-(, Evil-lisp-state, Key Bindings
