### ISSUE TITLE
Unable to quit from some transient states in some cases

### ISSUE THREAD

**Issue by dvzubarev** [syl20bnr/spacemacs#9196] opened 2017-07-06 21:09 UTC
#### Description :octocat:
Unable to quit from some transient states when the flycheck tooltips are enabled and the point is on an error.

#### Reproduction guide :beetle:
- Start Emacs
- Create some elisp file
- Paste there `(setq t 1)` 
- Enable flycheck `SPC-t-s`
- Place the point on the error
- Wait for a tooltip to appear
- Enter a transient state, e.g.  Code Folding `SPC-z-.` 
- Quit (`q`) and type `a`

*Observed behaviour:* :eyes: :broken_heart:
The Code Folding transient state is opened

*Expected behaviour:* :heart: :smile:
Evil should enter the insert state

I have found that disabling of `flycheck-pos-tip` package fixes this bug.
It may be done via the variable:
```
(setq-default dotspacemacs-configuration-layers
  '((syntax-checking :variables syntax-checking-enable-tooltips nil)))
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. efef390)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (syntax-checking :variables syntax-checking-enable-tooltips nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by nixmaniack** [comment] 2017-07-07 12:43
Unable to reproduce. 

![repro](https://user-images.githubusercontent.com/542810/27958252-d0dae826-633f-11e7-9e7c-0a1f65ce2c3f.gif)

**Comment by dvzubarev** [comment] 2017-07-07 14:12
@nixmaniack What is your value of `flycheck-display-errors-delay` variable?
I increased it from 0.9 (default) to 3.0 and this fixed the issue.

**Comment by dvzubarev** [comment] 2017-07-07 14:31
Actually the increasing a value of `flycheck-display-errors-delay` does not solve the issue. I see now that you need to open a transient state, wait for a tooltip to appear, quit transient state and the problem is reproduced for me.

**Comment by nixmaniack** [comment] 2017-07-08 12:15
The tooltip does appear but it's out of screen which is un-related to this. 
Still not able to reproduce. 
Opened transient state, waited for tooltip to appear, quit transient state and was able to get into insert state when pressed `a`

![repro](https://user-images.githubusercontent.com/542810/27985234-34935824-6405-11e7-9760-56ce4e1a2cfe.gif)

**Comment by duianto** [comment] 2020-02-08 12:25
I'm not able to reproduce this issue either.
The code folding transient state always closes and the cursor changes to evil insert state.

We'll close this, it can be reopened if reproducable reproduction steps are discovered.

<details><summary>
PopOS 1910
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c1a518439)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git github helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c1a518439)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git github helm imenu-list ipython-notebook markdown multiple-cursors org
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Closed by duianto** 2020-02-08 12:25 UTC
Labels: Syntax-checking, To be reproduced, Transient-state
