### ISSUE TITLE
ac-ispell could not be found, zone-leave-alone is void

### ISSUE THREAD

**Issue by EMayej** [syl20bnr/spacemacs#11102] opened 2018-07-29 02:50 UTC
#### Description :octocat:
1. package ac-ispell could not be found,  magit-define-popup is void
2. Error (use-package): zone/:init: Symbol’s function definition is void: zone-leave-me-alone

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
--> installing package: ac-ispell@auto-completion... [4/14]
Package ac-ispell is unavailable. Is the package name misspelled?

(Spacemacs) --> installing package: ac-ispell@auto-completion... [1/1]
Error loading autoloads: (void-function magit-define-popup)

*Expected behaviour:* :heart: :smile:
ac-ispell installed
zone-leave-alone gets called

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 026ba1469)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((helm :variables helm-enable-auto-resize t helm-no-header t)
 (colors :variables colors-colorize-identifiers 'all)
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 parinfer protobuf clojure typescript emacs-lisp
 (go :variables godoc-at-point-function 'godoc-gogetdoc gofmt-command "goimports")
 html
 (javascript :variables javascript-disable-tern-port-files nil)
 lua
 (python :variables python-enable-yapf-format-on-save t)
 ruby
 (rust :variables rust-format-on-save t)
 ansible docker nginx yaml sql fasd dash
 (templates :variables templates-use-default-templates nil)
 markdown graphviz plantuml osx
 (org :variables org-enable-reveal-js-support t org-enable-github-support t)
 spacemacs-org shell-scripts search-engine git spell-checking syntax-checking version-control
 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by EMayej** [comment] 2018-07-29 02:55
Duplicate:
#11095 #11096 #11101

**Comment by Miciah** [comment] 2018-07-30 07:17
Upstream issue: https://github.com/melpa/melpa/issues/5657

**Comment by EMayej** [comment] 2018-07-30 08:57
Is github fetcher working? If so we won't have to wait for melpa to add the package.
```
$ cat ~/.emacs.d/.cache/quelpa/melpa/recipes/ac-ispell
(ac-ispell :fetcher github :repo "syohex/emacs-ac-ispell")
```

Hi @syohex, do you know why ac-ispell got removed from melpa?

**Comment by syl20bnr** [comment] 2018-08-02 04:07
Zone issue should be fixed.

Closed as duplicate of https://github.com/syl20bnr/spacemacs/issues/11096

**Closed by syl20bnr** 2018-08-02 04:07 UTC
