### ISSUE TITLE
Exiting insert mode with ctrl+C exits vim mode

### ISSUE THREAD

**Issue by andrewthad** [syl20bnr/spacemacs#2607] opened 2015-08-10 19:43 UTC
If I'm in insert mode in spacemacs and I hit Ctrl+C, all of my vim commands quit working. This does not seem like a sensible default.

**Comment by TheBB** [comment] 2015-08-10 20:23
Have you made any customizations to have `C-c` exit insert state? Because that's not default behaviour. Check what `C-c` is bound to in insert state by using `C-h k C-c`.

**Comment by andrewthad** [comment] 2015-08-10 20:53
Thanks. It looks like it's a prefix for several agda-mode commands (and also winner-undo, winner-redo, and projectile-command-map). If I recall correctly, I was also having this problem before turning on agda mode. Is there a way to not let emacs plugins bind to keys when I'm in vim mode?

**Comment by TheBB** [comment] 2015-08-10 20:56
Well, you can bind `C-c` to nil if you like. I'm guessing that what you experience is just that Emacs is waiting for more input so that's why your commands "don't work" after `C-c`. If you finish the command or cancel it with `C-g` it should be back to normal.

**Comment by TheBB** [comment] 2015-08-30 19:35
Any motion on this?

**Comment by TheBB** [comment] 2015-09-02 09:26
Nobody has been able to reproduce and OP isn't responding. I'm closing this for now. Please reopen if you have more specific repro steps.

**Closed by TheBB** 2015-09-02 09:26 UTC
Labels: Key Bindings, question
