### ISSUE TITLE
SPC key will be translated into two when pressed on top of a flycheck errors

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#2110] opened 2015-06-25 03:45 UTC
- How to reproduce, open a file which flycheck turn on
- press `SPC e n` move to the next error
- press `SPC`

Then you will see two `SPC` was sent.
Wired~

**Comment by andyque** [comment] 2015-06-25 03:46
I'm using emacs-mac port and the version is 24.5.1.
I have tested on Linux, there is no such a problem.

**Comment by d12frosted** [comment] 2015-10-26 18:01
Can't reproduce it. Does it still happening to you, @zilongshanren ?

**Comment by zilongshanren** [comment] 2015-11-09 07:02
@d12frosted 
Sometimes it will happens, but sometimes the which-key pop windows can't be shown when cursor is on top of a flycheck warning or error.

**Comment by StreakyCobra** [comment] 2015-11-09 17:52
I can reproduce this:

- The `which-key` not showing problem can be reproduced by:
  - Open your `dotspacemacs` file: `SPC f e d`
  - Enable `flycheck`: `SPC t s`
  - Go one line above `(defun dotspacemacs/layers ()`
  - Go down one line (to the error), and press `SPC` between 0.5 and 0.9 seconds after being on it:
    
    ```
[0s] On the line
[0.5s < t1 < 0.9s] SPC pressed
[0.9s] Flycheck tooltip shown 
[t1 + 0.4s] which-key should appear, but doesn't
```
  - Notice `which-key` is not showing up

- The two `SPC` in the message-area appear when the error tooltip is already shown and you press `SPC`  (shown only for a brief amount of time)

@justbur @lunaryorn Any idea how to make them play well together?

**Comment by justbur** [comment] 2015-11-09 17:58
Looks like an issue with popup.el, specifically these lines https://github.com/auto-complete/popup-el/blob/master/popup.el#L1075-L1076 are screwing with `this-command` which is something which-key uses to decide whether to show or not

**Comment by lunaryorn** [comment] 2015-11-09 18:16
@StreakyCobra These are not Flycheck's tooltips.  You're using a [3rd party extension](https://github.com/flycheck/flycheck-pos-tip) for these that I neither wrote nor maintain.  I'm surprised that it uses `popup` now, it didn't when this project became part of the Flycheck org.  popup is a horrible library, known for many display issues and faulty interactions with other packages.

I'd recommend you to file an issue on `flycheck-pos-tip` to make it use `pos-tip` again.  I do have commit access to the project, in case all else fails.

**Comment by StreakyCobra** [comment] 2015-11-09 18:25
Thanks @justbur and @lunaryorn for the explanations :+1:

**Comment by lunaryorn** [comment] 2015-11-09 19:00
@StreakyCobra @syl20bnr I noticed that the original author of `flycheck-pos-tip` has apparently left Github, so I've taken over maintenance of that extension.

I've reverted the change to popup and made the library use pos-tip again.  I hope that this should fix some, if not all, of the issues regarding these tooltips.  The changes should make it into the next MELPA build of `flycheck-pos-tip`, so be prepared for changes to the appearance, behaviour and contents of those tooltips.  Please report any issues you discover to the tracker of https://github.com/flycheck/flycheck-pos-tip.

**Comment by StreakyCobra** [comment] 2015-11-09 19:10
@lunaryorn Amazing :smiley: Thanks a lot.

Possibly related bugs, for the record:
- #2316
- #2033
- #2575

**Comment by StreakyCobra** [comment] 2015-11-09 22:32
@lunaryorn The changes didn't went well on my side :confused:. I'll open an issue on `flycheck-pos-tip`.

**Comment by StreakyCobra** [comment] 2015-11-11 23:02
All problems are now resolved thanks to @lunaryorn's  work on `flyspell-pos-tip`. I'm closing it.

**Closed by StreakyCobra** 2015-11-11 23:02 UTC
Labels: bug :-(, Key Bindings
