### ISSUE TITLE
VIsual selection via `vit` -- works differently from VIM

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#5204] opened 2016-02-23 19:57 UTC
**Emacs:** 24.5.1 (OSX).
**Spacemacs:** latest `develop`, fresh install.

How to reproduce:
```
<a>foo</a>
```
- Place cursor at the first `<`
- `vit`

By doing this, VIM selects `foo`, but `evil` complains "No surrounding delimiters found". I couldn't find a similar issue on evil's issue tracker, is this a known `evil` quirk?

// same problem with `cit`, `dit`, etc; however things like `vi(`, `ci'``, etc work as expected.

**Comment by StreakyCobra** [comment] 2016-02-23 23:25
It's a duplicate, I just have to find the original one :wink:

**Comment by StreakyCobra** [comment] 2016-02-23 23:56
Found it, I closed it two days ago: https://github.com/syl20bnr/spacemacs/issues/702

It's an evil bug probably, as it can be reproduced with:

- `SPC q D evil RET` (this will restart emacs without Spacemacs and just `evil` enabled)
- On the scratch buffer of the new Emacs instance: `M-x evil-mode` to activate `evil`
- `i` to insert the content `<a>foo</a>`
- With the cursor on the first `a` the `vit` binding work
- With the cursor on the ferst `<` the `vit` binding doesn't work

So for me it seems to be an `evil` bug. If you want to report it upstream please do so and put back the link to it here so people can find and follow it. Usually we keep issue reported to upstream open for a while, but if you don't want to report it upstream then we will close it, as we can't do anything here :-)

**Comment by aldanor** [comment] 2016-02-24 01:10
Reported https://bitbucket.org/lyro/evil/issues/625/evil-inner-tag-fails-if-positioned-at-the

**Comment by StreakyCobra** [comment] 2016-02-24 08:48
:+1: Nice, let's see what they will say :-)

**Comment by aldanor** [comment] 2016-02-27 15:57
Fixed upstream: https://bitbucket.org/lyro/evil/issues/625

**Closed** 2016-02-28 10:39 UTC
Labels: - Bug tracker -, Evil, Fixed upstream
