### ISSUE TITLE
Theme mega-pack broken 

### ISSUE THREAD

**Issue by huyhoang8398** [syl20bnr/spacemacs#12400] opened 2019-06-03 09:25 UTC
**Description**
Cannot set theme from mega-pack with stable Spacemacs
System Info
* OS: darwin
* GNU Emacs 26.2
* Spacemacs branch stable
* Editing style: vim
* Completion: helm
* Layers:
  * added theme-mega spacemacs
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (file-error Cannot open load file No such file or directory autothemer))

**Comment by duianto** [comment] 2019-06-03 14:53
If the theme your trying to set is:  `darktooth` or `gruvbox`

Then this is a duplicate of this issue:
Some themes from the themes-megapack cannot be set as default #11380

That issue seems to have been solved on the Spacemacs `develop` branch.

**Closed** 2019-06-03 15:36 UTC
