### ISSUE TITLE
Error when opening ansi-term in zsh

### ISSUE THREAD

**Issue by domi91c** [syl20bnr/spacemacs#5256] opened 2016-02-26 03:56 UTC
#### Description

When I open `ansi-term`, I get these errors: 
`error in process filter: face-attribute: Invalid face: unspecified`
`error in process filter: Invalid face: unspecified`

Instead of my zsh prompt, I see some random letters and I'm unable to type anything. It was working at one point in terminal Emacs, but now it's not working in either the GUI or the terminal.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 6689699)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(themes-megapack react better-defaults github
                 (version-control :variables version-control-diff-tool 'git-gutter  version-control-global-margin t)
                 osx markdown
                 (vinegar :variables vinegar-reuse-dired-buffer t)
                 org prodigy search-engine
                 (syntax-checking :variables syntax-checking-enable-by-default nil)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 yaml
                 (ruby :variables ruby-version-manager 'rvm)
                 ruby-on-rails python lua html command-log javascript emacs-lisp common-lisp
                 (clojure :variables clojure-enable-fancify-symbols t)
                 ranger gtags
                 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
                 eyebrowse colors
                 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
                 (ibuffer :variables ibuffer-group-buffers-by 'projects)
                 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
                 auto-completion
                 (shell :variables shell-default-position 'full shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh"))
```

**Comment by sooheon** [comment] 2016-02-26 14:13
Seeing the same thing with fish. Bash works.

**Comment by portOdin** [comment] 2016-03-07 03:09
What reproduction steps are needed for this?

**Comment by StreakyCobra** [comment] 2016-03-07 07:22
What command do you use for running the `ansi-term`, and your ZSH prompt, or a fish config… something allowing to reproduce, because even with zsh and the agnoster prompt I can't reproduce :-(

**Comment by sooheon** [comment] 2016-03-07 08:08
I have found the source of the problem, at least for me. Some of the themes installed by themes-megapack must touch `custom-set-faces`, there were various term/ansi-term colors set in there which caused the errors. Deleting these customizations resolved the issue for me.

**Comment by syohex** [comment] 2016-03-07 09:14
This issue is similar to https://github.com/bbatsov/zenburn-emacs/issues/87. Your theme has same issue same as it(zenburn already fixed).

@portOdin Which theme did you use ?

**Comment by t3chnoboy** [comment] 2016-05-08 11:13
I have the same issue with fish. It was working before.
Now I get those errors in terminal and gui emacs regardless of the emacs theme 😞

**Comment by brenogil** [comment] 2016-10-31 12:47
Im on 0.200.4@25.1.1 and I get `error in process filter: face-attribute: Invalid face: unspecified error in process filter: Invalid face: unspecified` when opening ansi-term.
Nothing new has changed over my side. 
Everything was fine a couple of days ago

**Comment by erebe** [comment] 2016-11-02 13:31
Same as @brenogil. ansi-term was working fine with zsh previously, but after an update I cannot open it anymore

**Comment by brenogil** [comment] 2016-11-02 15:32
After being unable to find/craft as solution after some poking around, I deleted my .spacemacs and started another from scratch. All is fine now.

**Comment by erebe** [comment] 2016-11-02 15:44
@brenogil I can confirm
I upgraded all packages (SPC T m -> options -> manage packages -> U -> x) and now I can spawn a zsh shell correctly

**Comment by d12frosted** [comment] 2016-11-02 19:32
Ok, so it looks like you just need to update all packages (might be upstream issue with theme or anything else) and Spacemacs. 

Closing this for now. Let us know if it's and issue.

**Closed by d12frosted** 2016-11-02 19:32 UTC
Labels: - Forum -, Need repro steps, Terminals

**Comment by asok** [comment] 2016-12-07 12:43
I had the same issue. What I did I commented out a line in spacemacs file that was setting variable `ansi-term-color-vector`:

```el
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default bold shadow italic underline bold bold-italic bold])
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; '(ansi-term-color-vector
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;   [unspecified "#FFFFFF" "#d15120" "#5f9411" "#d2ad00" "#6b82a7" "#a66bab" "#6b82a7" "#505050"] t)
```

This is auto generated by custom so I'm not sure if after some time this setting will be added.

In the meantime this seems like a related problem: https://github.com/belak/base16-emacs/issues/4

**Comment by t3chnoboy** [comment] 2016-12-07 13:06
@asok Thank you!!!
It resolved the issue for me ☺️

**Comment by Lord-Guckavin** [comment] 2019-05-17 10:39
@asok remind me if we ever meet in real life I gotta suck your dick because it worked perfectly.

**Comment by JAremko** [comment] 2019-05-17 20:10
@Lord-Guckavin  Sorry but we aren't a dating portal.

**Comment by asok** [comment] 2019-05-20 04:38
@Lord-Guckavin I'd prefer if you just buy a beer.

**Comment by vv111y** [comment] 2020-02-28 23:01
I had this problem this week; not resolved. Thanks @asok
