### ISSUE TITLE
When running emacs to open a specified file, spacemacs simply opens up to the main page. 

### ISSUE THREAD

**Issue by davenull** [syl20bnr/spacemacs#4462] opened 2016-01-06 19:28 UTC
Brand new install on Gentoo's emacs 24 package.

**Comment by TheBB** [comment] 2016-01-06 19:29
Thanks, but this is (another) duplicate of #4057 .

**Closed by TheBB** 2016-01-06 19:29 UTC
Labels: duplicate (-: :-)

**Comment by davenull** [comment] 2016-01-06 21:21
So it has taken a month and more to fix this documented and reported bug that can be fixed with a single line change in the configs?

**Comment by TheBB** [comment] 2016-01-06 21:25
There are four hundred other open issues, and none of us work on Spacemacs full time. I'm not sure what this single line is, but if it's that simple, please PR your suggested fix.
