### ISSUE TITLE
a strange space on the number line gutter

### ISSUE THREAD

**Issue by winsphinx** [syl20bnr/spacemacs#16314] opened 2024-03-18 01:08 UTC
On line is <= 31, there's no space before gutter, but when line number is >= 32, a space appears. It's strange, what happens on line 32?

![image](https://github.com/syl20bnr/spacemacs/assets/5674054/ba5ed353-9381-4db4-b8f0-c800618631cb)

**Comment by bcc32** [comment] 2024-03-21 05:41
Spacemacs is just enabling the built-in line numbering logic in Emacs, like so:

```
(prog1 (display-line-numbers-mode)
            (setq display-line-numbers 'relative))
```

I suspect this is a bug in Emacs itself.  Are you able to reproduce this using `emacs -q` (and with the above Elisp snippet)?

**Comment by winsphinx** [comment] 2024-03-23 02:09
On original `emacs -q` mode, there is NOT the bug: BOTH have the space ahead.

![image](https://github.com/syl20bnr/spacemacs/assets/5674054/789d6870-4ad6-4b6f-9b8b-a896e035694f)

**Comment by smile13241324** [comment] 2024-03-30 12:59
I am sorry but I am completely at a loss what you mean, can you provide some more detailed instructions on what is wrong and how to reproduce it? Also please post your system details which you can obtain via `spacemacs/report-issue`.

Given from what you have written I assume there is an issue with automatically added blanks, this could be caused by `dotspacemacs-use-clean-aindent-mode` being non-nil in your dotfile. The package this setting refers to is very old and can cause such issues in more modern modes, please disable it in your dotfile and post if the issue persist.

Thanks.

**Comment by winsphinx** [comment] 2024-03-31 00:58
Thanks.

I tried to set `dotspacemacs-use-clean-aindent-mode` to nil (according to the `.spacemacs.template`, default is t) and reomve the package `clean-aindent-mode`, but it still shows the bug:

repoducing steps:
1. set line number mode to **visual-line-mode**;
2. move the cursor to the line < 30L, it seems correctly: no blank before the line number;
3. move down the cursor to > line 30+, obviously a space appears. Move up and down, the blank goes away  and comes back;

Then according to @bcc32's post, I tried his code in `emacs -q`, i saw a leading blank appears on every line.

no matter if there are blanks or not, I wish it remains consistent when moving up and down.

**Comment by bcc32** [comment] 2024-03-31 02:04
@smile13241324, the spaces appear visually (that is to say, not in the buffer itself) in the left margin, just left of the line numbers.  Basically, the width of the numbers is inconsistent when scrolling through the buffer, which is pretty weird.  I haven't figured out what causes this, yet.

**Comment by bcc32** [comment] 2024-03-31 03:31
I was able to get Emacs to display more spaces than necessary, even when using `emacs -Q`.  It attempts to set the width based on the widest line number it might have to show in the window, and this involves some heuristics, which may occasionally have errors.  If this behavior bothers you, I would advise customizing the variables in the "Display Line Numbers" group (`SPC SPC customize-group RET display-line-numbers RET`

For example, setting `display-line-numbers-width-start` to `t` ("Minimum width for buffer's line count: on") will cause it to be computed once, up front, for each buffer, and never resized.

**Comment by smile13241324** [comment] 2024-03-31 20:57
Then this is an emacs issue. I am going to close this ticket.

**Closed as completed** 2024-03-31 20:57 UTC
