### ISSUE TITLE
flycheck c-c++ mode line error

### ISSUE THREAD

**Issue by qqldd** [syl20bnr/spacemacs#1869] opened 2015-06-06 02:21 UTC
I use c-c++ layer. When editing the cpp file, the mode line disappears with following error in *Message*:

 Error during redisplay: (eval (spacemacs/mode-line-prepare)) signaled (void-function spacemacs|custom-flycheck-lighter) [10 times]

**Comment by TheBB** [comment] 2015-06-06 09:04
This is a duplicate of #1743.

**Comment by qqldd** [comment] 2015-06-30 22:18
@TheBB  I use irony with flycheck. I use configuration from here: https://github.com/nikki93/spacemacs-private/blob/master/irony-mode/packages.el

If I comment out the flycheck part, the problem will not occur so frequently. Otherwise, it will constantly occur.

**Comment by d12frosted** [comment] 2015-11-09 18:48
@qqldd Is it still happening?

**Comment by TheBB** [comment] 2015-11-09 18:50
Ah this one. I would be surprised if it's still happening. The modeline code has been through the wringer and doesn't look anything like it used to.

If it does still happen, it's a Spaceline bug and not a Spacemacs bug.

**Comment by qqldd** [comment] 2015-11-11 01:45
@TheBB  I will try and let you know later

**Comment by StreakyCobra** [comment] 2015-12-23 22:30
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.

**Closed by StreakyCobra** 2015-12-23 22:30 UTC
Labels: bug :-(, C/C++, Syntax-checking, Waiting for response
