### ISSUE TITLE
Layout mess up buffers when files are named the same

### ISSUE THREAD

**Issue by cserb** [syl20bnr/spacemacs#8152] opened 2017-01-12 11:34 UTC
#### Description :octocat:
When using layouts and switching between layouts buffers are mixed up if the current files naming are the same

#### Reproduction guide :beetle:
- Start Emacs
- SPC p l and open (e.g.) server.rb after chosing a project
- SPC p l and open from a different project a file named the same: server.rb
- now SPC l 2 (to go to the first porject) and the file show is the own from the second project

*Observed behaviour:* :eyes: :broken_heart:
See above

*Expected behaviour:* :heart: :smile:
Layouts should show buffer based on project and not filename alone

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts auto-completion emacs-lisp git syntax-checking haskell elixir html rust go erlang ruby vinegar restclient gtags docker markdown org yaml crystal racket)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by bmag** [comment] 2017-01-13 21:19
Thanks for the report, but I'm closing it as a duplicate of #7903.

**Closed by bmag** 2017-01-13 21:19 UTC
