### ISSUE TITLE
find-library is broken on the "develop" branch

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#6960] opened 2016-08-29 17:19 UTC
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-C C-C` TO SUBMIT>>
#### Description :octocat:
`find-library` feature is broken

#### Reproduction guide :beetle:
- Start Emacs in the `develop` branch
- Type `M-x find-library`
- Type the name of a library, for example, `helm`

*Observed behaviour:* :eyes: :broken_heart:
- The library `helm` is not selected, but random libraries appear as in attached picture:

![captura de pantalla de 2016-08-30 01 14 41](https://cloud.githubusercontent.com/assets/20593743/18060199/ace177d6-6e4f-11e6-8eb3-783d16b08d0c.png)

*Expected behaviour:* :heart: :smile:
- The library `helm` should appear, anyway...

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 64a0cc2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control semantic latex ocaml haskell tddsg)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment] 2016-08-29 18:39
Can't reproduce this. helm does appear (after a second or so). `SPC fel` is faster.

**Comment by TheBB** [comment] 2016-08-29 18:45
With `SPC q D`, try restarting with only helm, then do `(require 'helm)` and invoke `M-x find-library`. Can you reproduce then?

**Comment by tddsg** [comment] 2016-08-30 02:46
I tried `SPC fel` and it worked! However, the option `M-x find-library` still doesn't work, even for other libraries like `smartparens` ... 

I tried it on 3 computer: my laptop, my PC at work, at home and the problem is still the same with `M-x find-library`, but `SPC fel` works!

**Comment by bmag** [comment] 2016-08-30 06:23
I tried the repro steps by @tddsg. The completion for `find-library` is so slow that it's not usable. After typing helm, it took 10-30 seconds for the candidate list to update. I suspect (but didn't confirm) the cause is that `find-library` scans every directory in `load-path`, which can be quite large with Spacemacs. `SPC f e l` (`spacemacs/helm-locate-library`) indeed is a fast alternative.

I tested also with Ivy, and `find-library` completion is fast with Ivy. Unless this bug also slows down `require` and `load`, I think we can mark it as wontfix, because of the better alternatives and a probably non-obvious fix. A warning, though: I only did a quick research, so I can't guarantee that my claims are 100% correct. (but I'm pretty sure I'm right)

**Comment by tddsg** [comment] 2016-08-30 07:49
I confirmed with you about the so-slow loading time of `helm` when finding the library. I tried again and it took about 10 seconds or more to find the library (see the attached gif file). 

Sorry, last time, I didn't have enough patience to wait for it to be fully loaded. However, I think this is still quite a problem since I was using Emacs Prelude before, and in Prelude `M-x find-library` with helm enabled load instantly.

![optimised](https://cloud.githubusercontent.com/assets/20593743/18080605/d622cdce-6ec8-11e6-8d07-fecb23184152.gif)

**Comment by TheBB** [comment] 2016-08-30 07:54
Is it better if you exclude helm-flx?

**Comment by tddsg** [comment] 2016-08-30 08:00
`helm-flx` is not enabled in my Emacs. 
I just tried to both enable and disable it, the loading time in both cases are almost the same (both are slow)

**Comment by tddsg** [comment] 2016-08-30 08:17
I also encountering another issue of very slow-loading when locating for error position in `compilation` mode (by pressing Enter at the error message in the compilation buffer). 

When trying with `emacs -q`, Emacs can locate error instantly. I think there is something wrong with `helm` or some of the library integration. 

Should I report it as a new issue?

**Comment by deb0ch** [comment] 2016-10-16 17:53
Autumnal cleanup: what is the status on this ? Can you still reproduce ? On latest develop ?

Just tried `M-x find-library helm` and it found it almost instantly. Same for company-semantic and other stuff.

Let us know so we can close this or not.

**Comment by tddsg** [comment] 2016-10-16 21:18
I am using the Spacemacs 0.200.2 and this problem doesn't occur anymore. Perhaps, it is almost fixed. Please close it. Thank you all for the ultimate efforts to make Spacemacs wonderfull!

**Comment by deb0ch** [comment] 2016-10-16 21:50
What do you mean, "almost" ? Anyways, I'm reporting this as fixed for now. Don't hesitate to open again or open a new one if that happens again.

**Closed** 2016-10-17 05:14 UTC
Labels: - Bug tracker -, Helm
