### ISSUE TITLE
HOWTOs.org link broken at the end of quick start

### ISSUE THREAD

**Issue by gilch** [syl20bnr/spacemacs#5690] opened 2016-04-05 16:36 UTC
See the [quick start](http://spacemacs.org/doc/QUICK_START.html#orgheadline12), and try to follow the link under the last header. I get a 404.

**Comment by StreakyCobra** [comment] 2016-04-05 17:47
This has already been fixed on develop: http://develop.spacemacs.org/doc/QUICK_START.html Duplicate of https://github.com/syl20bnr/spacemacs/issues/4853 :-)

**Closed by StreakyCobra** 2016-04-05 17:47 UTC
Labels: - Bug tracker -, Documentation ✏
