### ISSUE TITLE
Symbol's function definition is void: projectile-project-p

### ISSUE THREAD

**Issue by bixuanzju** [syl20bnr/spacemacs#5388] opened 2016-03-07 06:57 UTC
#### Description
After emacs first start up, press `SPC p l` (`spacemacs/helm-persp-switch-project`), emacs throws error `Symbol's function definition is void: projectile-project-p`. To workaround, I have to press `SPC p p` (`helm-projectile-switch-project`) then `SPC p l` works fine. 

#### Reproduction guide
- Start Emacs
- Press `SPC p l`

*Observed behaviour:*
Minibuffer shows `Symbol's function definition is void: projectile-project-p`

*Expected behaviour:*
Helm window pops up for me to choose a project

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.12
- Spacemacs branch: develop (rev. 9026652)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion emacs-lisp
                (git :variables git-magit-status-fullscreen t)
                markdown org spell-checking syntax-checking version-control osx colors idris haskell latex evil-snipe ocaml proof-general)
```

#### Backtrace
```
Debugger entered--Lisp error: (void-function projectile-project-p)
  (projectile-project-p)
  (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)
  (lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects))()
  #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]()
  apply(#[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"] nil)
  helm-funcall-with-source(((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name ...) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) (#[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]))
  helm-funcall-foreach(init nil)
  helm-initial-setup(nil)
  helm-initialize(nil nil nil ((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name ...) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)))
  #[0 "\311\211\211\211\305\206\n&&'()*\312\313+\"\314\315\316\317\320\321!\322\"\323\324%DC\216\325\303\301\307\300$\210\326&!\210,\203?\327\330!\210\331\332\333\"\210\331\332\334\"\210\335\336!\210\314\337DC\216\340\302\301\304\303\306\307\310&\210*\210'?\205g\341 \335\342\343\344\345\"P!\210-\207" [((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if ... ... projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let (...) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) nil nil nil nil "*Helm Projectile Layouts*" nil nil nil nil mapcar #[257 "\211JB\207" [] 3 "\n\n(fn V)"] funcall make-byte-code 0 "\300\301\211:\203@\262\211A\262\242\262\211L\210A\262\202\266\302\303!\207" vconcat vector [nil helm-log "restore variables"] 5 "\n\n(fn)" helm-initialize helm-display-buffer helm--remap-mouse-mode 1 add-hook post-command-hook helm--maybe-update-keymap helm--update-header-line helm-log "show prompt" #[0 "\300 \207" [helm-cleanup] 1 "\n\n(fn)"] helm-read-pattern-maybe helm-execute-selection-action "[End session] " make-string 41 45 helm-buffer helm-quit helm-in-persistent-action helm-current-source helm-source-name helm-restored-variables helm-prevent-escaping-from-minibuffer] 9 "\n\n(fn)"]()
  funcall(#[0 "\311\211\211\211\305\206\n&&'()*\312\313+\"\314\315\316\317\320\321!\322\"\323\324%DC\216\325\303\301\307\300$\210\326&!\210,\203?\327\330!\210\331\332\333\"\210\331\332\334\"\210\335\336!\210\314\337DC\216\340\302\301\304\303\306\307\310&\210*\210'?\205g\341 \335\342\343\344\345\"P!\210-\207" [((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if ... ... projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let (...) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) nil nil nil nil "*Helm Projectile Layouts*" nil nil nil nil mapcar #[257 "\211JB\207" [] 3 "\n\n(fn V)"] funcall make-byte-code 0 "\300\301\211:\203@\262\211A\262\242\262\211L\210A\262\202\266\302\303!\207" vconcat vector [nil helm-log "restore variables"] 5 "\n\n(fn)" helm-initialize helm-display-buffer helm--remap-mouse-mode 1 add-hook post-command-hook helm--maybe-update-keymap helm--update-header-line helm-log "show prompt" #[0 "\300 \207" [helm-cleanup] 1 "\n\n(fn)"] helm-read-pattern-maybe helm-execute-selection-action "[End session] " make-string 41 45 helm-buffer helm-quit helm-in-persistent-action helm-current-source helm-source-name helm-restored-variables helm-prevent-escaping-from-minibuffer] 9 "\n\n(fn)"])
  helm-internal(((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name ...) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) nil nil nil nil "*Helm Projectile Layouts*" nil nil nil)
  apply(helm-internal (((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons ... ...) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let ((projectile-completion-system ...)) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) nil nil nil nil "*Helm Projectile Layouts*" nil nil nil))
  helm(((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name ...) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) nil nil nil nil "*Helm Projectile Layouts*" nil nil nil)
  apply(helm (((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons ... ...) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let ((projectile-completion-system ...)) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) nil nil nil nil "*Helm Projectile Layouts*" nil nil nil))
  helm(:sources ((name . "*Helm Switch Project Layout*") (init #[0 "\301\302\303\300!\203
\300 \202\300\"\207" [(lambda nil (if (projectile-project-p) (cons (abbreviate-file-name ...) (projectile-relevant-known-projects)) projectile-known-projects)) helm-init-candidates-in-buffer global functionp] 4 "\n\n(fn)"]) (candidates . helm-candidates-in-buffer) (action ("Switch to Project Perspective" lambda (project) (let ((persp-reset-windows-on-nil-window-conf t)) (persp-switch project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))))) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-read-file-map>\\[helm-help]:Help C/\\[helm-cr-empty-string]:Empty \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Switch to Project Perspective (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin) (data lambda nil (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) :buffer "*Helm Projectile Layouts*")
  spacemacs/helm-persp-switch-project(nil)
  call-interactively(spacemacs/helm-persp-switch-project nil nil)
  command-execute(spacemacs/helm-persp-switch-project)
```

**Comment by StreakyCobra** [comment] 2016-03-07 07:31
I think this is a duplicate of https://github.com/syl20bnr/spacemacs/issues/5127, so I'm closing it. Let me know if this is not the case.

**Closed by StreakyCobra** 2016-03-07 07:31 UTC
Labels: - Bug tracker -, Duplicate ☝
