### ISSUE TITLE
Spacemacs-layouts - buffer isolation issue

### ISSUE THREAD

**Issue by pavkum** [syl20bnr/spacemacs#6266] opened 2016-06-08 18:21 UTC
#### Description
Buffers among the layouts are overlapping. I was redirected to [here](http://develop.spacemacs.org/doc/DOCUMENTATION.html#layouts-and-workspaces) from gitter chat which says layouts provide buffer isolation.

#### Reproduction guide
- Start Emacs
- Create a new layout by SPC l 2
- Create your custom window setup (split horizontally / vertically as per your choice)
- Save configuration by SPC l s
- Restart emacs
- Load layout by SPC l L
- switch to new layout SPC l 2
- open some random buffer
- switch to default layout 
- open buffer list for switch - C-x b (opens Helm buffers in my case)

*Observed behaviour:*
Buffer opened in 2nd layout is seen in 1st layout

*Expected behaviour:*
Buffer opened in 2nd layout shouldn't be visible in 1st layout

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp html git typescript javascript eyebrowse org)
```

**Comment by NJBS** [comment] 2016-06-08 18:26
Can you still reproduce this when not using the default layout?

From http://develop.spacemacs.org/doc/DOCUMENTATION.html#the-default-layout :

The default layout is special because it has a global scope which means that all the opened buffers belong to it. So using only the default layout feels like not using layouts at all.

**Comment by pavkum** [comment] 2016-06-08 18:31
@NJBS Yes I can.

- created new layout at 3.
- Opened a random buffer 
- switched to 2nd layout
- Helm buffer shows the buffer created in 3

**Comment by syl20bnr** [comment] 2016-06-08 20:26
@pavkum I cannot reproduce it, maybe we need to backport a fix in master. Can you try with develop ?

**Comment by pavkum** [comment] 2016-06-09 11:37
@syl20bnr I got the cause.

I had added `ido` to exclude packages. This causes the issue. 
If I remove `ido` from exclude packages I cannot reproduce the issue.

**Comment by pavkum** [comment] 2016-06-09 17:41
@syl20bnr Basically I wanted kill buffer list to be same as `Helm`, by default I guess it shows `ido-buffers`. Instead of adding `ido` to exclude packages I disabled ido. Now in layers if I press kill switch `C-x k` helm buffers list all the buffers but if I enable ido and try I get only the buffers of that particular layout.

I have Helm enabled everywhere. How do I enable helm for kill buffer list also and get around this issue as well.

**Comment by dlukes** [comment] 2016-07-09 19:50
I'm also experiencing this on OS X 10.11.5, Emacs 24.5.1, Spacemacs 0.105.21. FWIW:

1. I didn't have `ido` in exclude packages
2. I wiped `.emacs.d` and reinstalled and the issue persisted
3. I re-wiped `.emacs.d` and reinstalled with the `devel` branch and the issue is gone

**Comment by d12frosted** [comment] 2016-10-03 08:17
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 08:17 UTC
Labels: - Bug tracker -, Fixed in develop, Spacemacs Layouts, To be reproduced
