### ISSUE TITLE
File error: Cannot open load file, No such file or directory, up-core

### ISSUE THREAD

**Issue by howdoicomputer** [syl20bnr/spacemacs#9948] opened 2017-12-04 00:32 UTC
#### Description :octocat:
On fresh clone, Spacemacs fails to install.

#### Reproduction guide :beetle:
```
dropsquads-vue:master* λ cp ~/.spacemacs ~/Documents/spacemacs-back
dropsquads-vue:master* λ rm ~/.spacemacs
dropsquads-vue:master* λ rm -rf ~/.emacs.d/
dropsquads-vue:master* λ git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
Cloning into '/home/howdoicomputer/.emacs.d'...
remote: Counting objects: 60214, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 60214 (delta 6), reused 16 (delta 6), pack-reused 60191
Receiving objects: 100% (60214/60214), 35.70 MiB | 11.01 MiB/s, done.
Resolving deltas: 100% (38594/38594), done.
```

Start Spacemacs, get this:

```
Warning (initialization): An error occurred while loading ‘/home/howdoicomputer/.emacs.d/init.el’:

File error: Cannot open load file, No such file or directory, up-core

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

This seems to be a bug with `use-package`: https://github.com/jwiegley/use-package/issues/533

**Comment by davidkern** [comment] 2017-12-04 00:38
I have also received exactly same error a moment ago on a fresh install of Emacs 24.5.1 under Debian 9.2. Also tried under Emacs 25.1.1 and had the same result.

**Comment by everedifice** [comment] 2017-12-04 00:55
I have same issue. is there any way to rollback use-package version?

**Comment by howdoicomputer** [comment] 2017-12-04 01:47
Okay, so the workaround is to force Spacemacs to use melpa-stable rather than plain melpa. The stable repository has version 2.3 of `use-package` and I was able to get that to work.

Add the following lines to your user-init block in Spacemacs:

```
  (push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer--elpa-archives)
  (push '(use-package . "melpa-stable") package-pinned-packages)
```

My block looks like this:

```
(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init', before layer configuration
executes.
 This function is mostly useful for variables that need to be set
before packages are loaded. If you are unsure, you should try in setting them in
`dotspacemacs/user-config' first."
  (push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer--elpa-archives)
  (push '(use-package . "melpa-stable") package-pinned-packages)
  )
```

This should do until the maintainer of `use-package` updates their melpa recipe for their new version.

**Comment by duianto** [comment] 2017-12-04 02:15
The broken `use-package` needs to be removed from the `.emacs.d/elpa` directory first.
The stable version is called: `use-package-2.3`

**Comment by davidkern** [comment] 2017-12-04 02:22
Beautiful.  Switching to melpa-stable as suggested by @howdoicomputer and removing the stale use-package from elpa directory per @duianto fixes the issue.

For completeness sake: building a new package for use-package by cloning melpa, adjusting the recipe for use-package (and bind-keys), building it and then installing that new package does not work at all.  It leads to strange errors regarding key bindings.  Pinning to version 2.3 of use-package also doesn't work, surprisingly, even though it should be the same package in melpa-stable.  Perhaps I was missing a step...  Moot point now though.

**Comment by howdoicomputer** [comment] 2017-12-04 02:33
Ah, right, yeah, you need to clear out stale packages. I had nuked my `~/.emacs.d` directory and just kept my dotfile.

**Comment by jkw** [comment] 2017-12-04 02:54
1. Follow instructions in @duiantos post.
2. Follow instructions in @howdoicompuer post. 
3. Restart Emacs. 
4. Continue do whatever you did before Spacemacs broke due to package updates.

**Comment by everedifice** [comment] 2017-12-04 04:23
**`configuration-layer--elpa-archives` is in `~/.spacemacs`**

**Comment by Novite5** [comment] 2017-12-04 04:35
replace _use-package-20171203.1313_ with the older version, things ok.

**Comment by duianto** [comment] 2017-12-04 04:49
I don't know which version is the most recent that works, but the previous version that I had installed before `use-package-20171203.1313`, was `use-package-20171203.1144`, but it causes this issue with the `emacs` editing style: Spacemacs startup error - void-function holy-mode #9945

The version that I had installed before that: `use-package-20171129.2308`, seems to be working, it doesn't show any errors on startup.

**Comment by jimmyhuco** [comment] 2017-12-04 08:50
Add the code below to `dotspacemacs/user-init` block, but check your branch first.

For master branch:  

```
  (push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer--elpa-archives)
  (push '(use-package . "melpa-stable") package-pinned-packages)
```

For develop branch:

```
  (push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer-elpa-archives)
  (push '(use-package . "melpa-stable") package-pinned-packages)
```
`

**Comment by korayal** [comment] 2017-12-04 12:46
My solution was to copy all `.el` files from the [package's repo](https://github.com/jwiegley/use-package) into `~/.emacs.d/elpa/25.3/develop/use-package-20171203.1313` folder. This issue was caused by MELPA containing a revision that's in-between a major change in the code. MELPA has `2f4d48` while the [latest revision](https://github.com/jwiegley/use-package/commits/master) is `a04be2`. I suppose this'll be fixed on the next update

**Comment by bapcyk** [comment] 2017-12-04 19:50
this workaround does not help me. 

```
Warning (initialization): An error occurred while loading ‘c:/Users/Pavel/AppData/Roaming/.emacs.d/init.el’:

File error: Cannot open load file, No such file or directory, bind-map

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by howdoicomputer** [comment] 2017-12-05 01:15
The upstream issue with `use-package` has been resolved. I removed the pin against melpa-stable, nuked my `~/.emacs.d`, and reinstalled off my dotfile.

**Comment by duianto** [comment] 2017-12-05 01:30
Confirmed, there's no error message on startup for me, with `use-package-20171204.1321`.

**Comment by a13ph** [comment] 2017-12-06 06:40
@howdoicomputer @d12frosted I suppose this calls for closing this issue?

**Closed** 2017-12-06 07:38 UTC
