### ISSUE TITLE
 pop-up-frames functionality is broken

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10384] opened 2018-02-23 18:05 UTC
#### Description :octocat:
The pop-up-frames functionality is broken.

#### Reproduction guide :beetle:
- Set pop-up-frames to 't.
- Start Emacs
- Start a shell.

*Observed behaviour:* :eyes: :broken_heart:
Shell special buffer opens in the current frame.

*Expected behaviour:* :heart: :smile:
It should have opened a new frame.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 93ec4217)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(crystal html python
         (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
         autohotkey helm auto-completion emacs-lisp
         (ibuffer :variables ibuffer-group-buffers-by 'modes)
         coq emoji
         (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
         git
         (java :variables java-backend 'ensime)
         markdown org
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         spell-checking syntax-checking version-control osx racket clojure)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment] 2018-02-24 09:58
1) "Start a shell" is too vague, there are several ways to do that. I guess you meant `M-x shell`

2) managed to repro, caused by `purpose-mode`

3) as work-around tried either one of:

3.1) `(purpose-mode -1)` in `user-config` to disable purpose-mode completely

3.2) run this code in `user-config` so purpose-mode tries new frames before new windows (as stock Emacs 25.3 does):
```elisp
;; out-of-the-box `other-window' and `pop-up-window' come before `other-frame' and `pop-up-frame', here we swap the order
(setcdr (assq 'prefer-other-window purpose-action-sequences)
        '(purpose-display-reuse-window-buffer
          purpose-display-reuse-window-purpose
          purpose-display-maybe-other-frame
          purpose-display-maybe-pop-up-frame
          purpose-display-maybe-other-window
          purpose-display-maybe-pop-up-window
          purpose-display-maybe-same-window))
```

4) please try 3.2 and tell me if it worked

5) I will fix it upstream in a few days, but first I need to check the behavior in other versions of Emacs

**Comment by NightMachinary** [comment] 2018-02-24 18:09
Thanks! (purpose-mode -1) seems to work well (it worked weirdly when I tried in my already open emacs session, restoring a particular frame layout with 3 windows each time it opened the new frame, but I don't know how to reproduce that). But the other snippet is buggy: First do M-x shell, a new frame is opened, do SPC w /, the frame is split to 2 windows, change the buffers for these two with '[ b' (so that no *shell* buffer is open), go back to the previous frame, do M-x shell; The shell is opened again at the first window in the already open two-window frame, instead of opening a new frame.

**Comment by bmag** [comment] 2018-08-09 12:44
It took half a year, rather than a few days, but it's fixed now.

**Closed by bmag** 2018-08-09 12:44 UTC
Labels: - Bug tracker -, Reported upstream, Windows layout
