### ISSUE TITLE
Cannot install and use package esc-sql with spacemacs

### ISSUE THREAD

**Issue by tutysara** [syl20bnr/spacemacs#6859] opened 2016-08-18 12:57 UTC
#### Description
Cannot install and use package ejc-sql, the package throws an error while installing and installs partially. Some of the functions like ```ejc-sql-mode``` are available in the ```Helm Mx``` window, but doesn't work when called. Some functions like ```ejc-connect``` doesn't show up in the list at all. The package is not usable.

#### Reproduction guide
- Start Emacs
- Open .spacemacs file
- add ejc-sql to the list of additional packages - ```dotspacemacs-additional-packages '(ejc-sql)```
- Refresh using ```M-m f e R```

*Observed behaviour:*
Installation throws an error and the mode is not installed properly. Error thrown
```ejc-sql.el:41:1:Error: Symbol's value as variable is void: clomacs--doc
```

*Expected behaviour:*
Package is installed and all functions are available. This works when installed with Prelude starter kit

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp markdown org)

```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment] 2016-08-18 13:03
We can't help if third party packages are broken. Especially not ones that are not included in a Spacemacs layer. You'll have to take that up with the ejc-sql developers.

**Comment by TheBB** [comment] 2016-08-18 13:10
I can reproduce though. It originates from clomacs and it goes away if I delete the byte-compiled clomacs files. Possibly it's due to over-eager macro expansion during byte-compilation.

**Comment by tutysara** [comment] 2016-08-18 13:15
It works when installed on top of Prelude, that is the reason I opened it here. Thank you, let me delete the .elc file and check

**Comment by tutysara** [comment] 2016-08-18 14:11
I went into clomacs dir and deleted all the byte compiled files
```bash 
cd ~/.emacs.d/elpa/clomacs-20160720.845
rm *.elc
```
then executed ```M-m f e R``` in the .spacemacs file nothing happens. I restarted spacemacs and i can see all the functions from ejc-sql in ```Helm M-x``` and it works, thank you. ejc-sql used to have a menu, but I don't see the menu with spacemacs yet. Should I have to do any additional configuration to get the menu.

**Comment by tutysara** [comment] 2016-08-18 14:41
I was looking through the sources, i found a function ejc-create-menu, evaluating ```(ejc-create-menu)``` from scratch buffer produces the menu.

**Comment by TheBB** [comment] 2016-08-19 07:03
I assume I can close this, then.

By the way, `ejc-create-menu` is run as part of the `ejc-sql` minor mode. [Link](https://github.com/kostafey/ejc-sql/blob/master/ejc-sql.el#L90).

**Closed by TheBB** 2016-08-19 07:03 UTC

**Comment by tutysara** [comment] 2016-09-16 12:04
Yes, it worked after the workaround you gave on gitter. I worked with the original author or ejc-sql and he had fixed it and now it works without the workaround (delete the .elc files in clomacs). ty.
