### ISSUE TITLE
helm-mode gets stuck and confused

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1971] opened 2015-06-12 18:22 UTC
Using vim style
1. hit <kbd>SPC :</kbd> for `helm-M-x`
2. click mouse-1 anywhere

As a result there's a `<mouse-1> is undefined` error, the minibuffer gets stuck in some weird mode showing `M-x` all the time, and <kbd>Esc</kbd> or <kbd>Ctrl+G</kbd> or <kbd>fd</kbd> don't seem to have any effect. So far the only way to reset the situation seems to be to close the helm window with `<mouse-3>` on the divider.

I'm not entirely sure what to expect in such case, selecting the clicked item perhaps (if in helm window) or quitting it (if clicked outside) -- in any case not being stuck in a disorienting state would be good.

(I've seen spacemacs randomly get stuck and confused and forget keybindings in similar fashion in other modes and interactions as well, in worst case having to resort to restarting emacs, but this is the only case I'm able to describe coherently.)

**Comment by bmag** [comment] 2015-06-13 06:00
I think I was able to reproduce your problem, and there is a simple solution: hit <kbd>C-x o</kbd> until the minibuffer gets back to normal.

The reason that emacs gets "stuck and confused and forget keybindings" is that clicking the mouse shifts the focus from the minibuffer to another window. <kbd>C-x o</kbd> (command `other-window`) changes the "selected window". Once the minibuffer becomes the selected window again, everything is back to normal.
By the way, if I click mouse-1 inside the minibuffer window, then emacs doesn't get stuck.

I also get this issue from time to time in other modes and interactions. Probably something changes the selected window in those situations as well, but I don't know what thing exactly. I guess its some code in spacemacs, maybe several unrelated pieces of code, but that's a guess.
However, I think that <kbd>C-x o</kbd> should work for you also in the other similar situations. Can you confirm?

I think the technical description of the problem is "other window selected when minibuffer is active, during a helm session."

**Comment by moesasji** [comment] 2015-06-19 21:19
I experience this same behavior as highlighted by tko. The only way to get out is using the key-sequence `C-x o` `Esc`; just clicking mouse-1 inside the minibuffer window doesn't work for me. 

To reproduce
1. Hit `spc` `:` 
2. click mouse-1 anywhere
....no way to exit the minibuffer with `Esc`, `CTRL` + `G`, clicking with mouse-1, etc..
*) It is indeed possible to get out using `C-x o` `Esc` seeing the hint by bmag

Before reading this bugreport the only way I found was closing emacs and restart. This is a pretty serious bug imho.

**Comment by robbyoconnor** [comment] 2015-06-19 21:48
make a note about this in the documentation maybe?

**Comment by syl20bnr** [comment] 2015-06-21 02:19
@robbyoconnor you are right, this is an important thing to document

**Comment by moesasji** [comment] 2015-06-21 06:38
@syl20bnr I politely disagree that this is a documentation issue. 

This is very confusing behavior and moreover it makes no sense that a key-binding that represents "close other window" that sometimes needs escape added gets you out of what is an undefined state. Note that this work-around doesn't work if you are in the other window. The `C-o Esc` work-around only works if you have first clicked with the mouse on the helm popup. 

I'm not sure what the expected behavior would be, but as a minimum I would expect that hitting `esc` when returning to the helm-window with the mouse would allow one to close the helm-window.

**Comment by emmanueltouzery** [comment] 2015-06-21 06:58
maybe this should be reported upstream? someone would have to check whether this also occurs without spacemacs installed. Unfortunately personally I'm practically unable to use emacs without spacemacs.

**Comment by TheBB** [comment] 2015-10-02 17:48
The commonly accepted solution, as far as #2851 is concerned, is `SPC w b`. It will be documented and that issue marked fixed when #3209 is merged. I agree that this behaviour is undesirable, however.

Closing this as a duplicate of #2851. I know this one came first but...

**Closed by TheBB** 2015-10-02 17:48 UTC
Labels: documentation :->
