### ISSUE TITLE
connection error while installing the org layer

### ISSUE THREAD

**Issue by pup** [syl20bnr/spacemacs#8819] opened 2017-04-28 17:26 UTC
#### Description :octocat:
when trying to install the `org` layer, spacemacs is unable to install the `org-present` package, which leads to it crashing and consuming a whole lot of memory

#### Reproduction guide :beetle:
- Start Emacs
- Add `org` to the layers list in `.spacemacs`
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:

<img width="1297" alt="screen shot 2017-04-28 at 19 24 29" src="https://cloud.githubusercontent.com/assets/6078550/25539628/564d609e-2c48-11e7-92a8-212134bfc21d.png">

*Expected behaviour:* :heart: :smile:

emacs installs all packages and starts normally

tested on `0.200.9@25.1.1 (spacemacs-base)` on macos sierra

**Comment by JAremko** [comment] 2017-05-24 15:39
@pup  Do you still experience this problem?

**Comment by shadyproject** [comment] 2017-06-15 21:00
I just ran into this issue today.  Is it a transient issue?

**Comment by JAremko** [comment] 2017-06-19 09:48
#8890 was fixed.  How about this one?

**Comment by d12frosted** [comment] 2017-06-19 13:18
This one is not fixed yet I think. I'll take a look.

**Comment by d12frosted** [comment] 2017-06-19 17:56
I can't reproduce this problem even without my commit.

@pup, @shadyproject could you please share the result of `SPS h d s`?

**Comment by pup** [comment] 2017-06-19 18:58
@d12frosted oh bother, i'm not even using emacs anymore 😢 sorry, can't help you out here

**Comment by d12frosted** [comment] 2017-06-20 04:58
@pup that's a shame! hope you are alright without Emacs 😸

**Comment by d12frosted** [comment] 2017-07-26 08:55
Closing this issue as original author doesn't use Spacemacs anymore and other reporters have fixed it.

**Closed by d12frosted** 2017-07-26 08:55 UTC
