### ISSUE TITLE
Package Unavailable: ac-ispell

### ISSUE THREAD

**Issue by rieonke** [syl20bnr/spacemacs#11095] opened 2018-07-28 09:12 UTC
hello,
`ac-ispell` is unavailable now https://stable.melpa.org/#/ac-ispell

**Comment by Miciah** [comment] 2018-07-30 07:17
I don't really know the process for reporting a missing package, but I filed an issue upstream: https://github.com/melpa/melpa/issues/5657

**Comment by rieonke** [comment] 2018-07-30 12:53
@Miciah just download the package from github and use `package-install-file` to install to

**Comment by semsturgut** [comment] 2018-07-31 07:25
@rieonke that works. Thanks.

**Comment by syl20bnr** [comment] 2018-08-02 04:06
closed as duplicate of https://github.com/syl20bnr/spacemacs/issues/11096

**Closed by syl20bnr** 2018-08-02 04:06 UTC
