### ISSUE TITLE
Can't insert the pipe character with a Spanish keyboard on OS X

### ISSUE THREAD

**Issue by kedare** [syl20bnr/spacemacs#8047] opened 2016-12-24 12:19 UTC
#### Description :octocat:
The pipe character can't be inserted correctly from OSX with a Spanish keyboard

#### Reproduction guide :beetle:
- Start Emacs on OS X with a Spanish keyboard
- Try to insert the pipe character using the standard key (ALT 1)

*Observed behaviour:* :eyes: :broken_heart:
Nothing happen

*Expected behaviour:* :heart: :smile:
The pipe character should be inserted

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking version-control python csharp javascript sql yaml html shell-scripts windows-scripts react elixir)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by vic** [comment] 2016-12-26 08:08
Hi, 

Is this issue still present if you add the `osx` layer to your config? I guess it'd be needed for handling the `ALT` key correctly on osx, could you give it a try?

**Comment by kedare** [comment] 2016-12-26 11:27
Hello,

I just tried, but it didn't change anything.

**Comment by d12frosted** [comment] 2017-01-03 09:12
If `option` key is meta key, then this is as expected. And duplicate of other similar issues. See newly created similar question that has links to other threads: https://github.com/syl20bnr/spacemacs/issues/8095.

**Comment by d12frosted** [comment] 2017-01-03 09:13
Ultimately: this issue looks very much like this one: https://github.com/syl20bnr/spacemacs/issues/1435.

**Closed by d12frosted** 2017-01-03 09:12 UTC
Labels: - Bug tracker -, Key Bindings, macOS
