### ISSUE TITLE
Automatic refresh renders buffer-menu unusable

### ISSUE THREAD

**Issue by bgamari** [syl20bnr/spacemacs#7661] opened 2016-11-04 16:23 UTC
#### Description :octocat:
The buffer list shown by `C-x C-b` appears to periodically automatic refresh,
making it very difficult to use. Namely, the point returns to the beginning of
the buffer and any buffer marks are cleared.

#### Reproduction guide :beetle:
- Start Emacs
- Open a few buffers
- Press `C-x C-b`
- Select a few buffers for deletion by pressing `d`, move the point somewhere
- Wait a second or so

*Observed behaviour:* :eyes: :broken_heart:
After a second or so the point is returned to the top of the buffer and the deletion marks disappear.

*Expected behaviour:* :heart: :smile:
The buffer remains unchanged.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.0.92.1
- Spacemacs: 0.200.2
- Spacemacs branch: nil (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql yaml auto-completion syntax-checking latex notmuch python extra-langs c-c   html javascript markdown git github emacs-lisp shell idris asciidoc rust purescript tracwiki-mode nixos-mode
     (haskell :variables haskell-enable-ghc-mod-support nil))
```

**Comment by bmag** [comment] 2016-11-04 16:35
I can reproduce this with latest develop and Emacs 25.1. This is because Spacemacs enables `global-auto-revert-mode` and sets `global-auto-revert-non-file-buffers` to `t`. The fix is to add `Buffer-menu-mode` to `global-auto-revert-ignore-modes`. PR welcome.

**Comment by TheBB** [comment] 2016-11-04 16:39
Previous issues about this: https://github.com/syl20bnr/spacemacs/issues/2667 and https://github.com/syl20bnr/spacemacs/issues/6844.

**Comment by TheBB** [comment] 2016-11-04 16:40
As you can see this was already deemed wontfix due to being a very specific workflow, but PRs were and still are welcome.

**Comment by cubranic** [comment] 2017-03-01 12:59
@TheBB #2667 was closed because `:ls` used `helm-buffers`at the time. But that doesn't happen any more if `ivy` is used as the completion framework. @bgamari 's fix works for me with Ivy.

**Closed** 2017-04-02 06:00 UTC
Labels: - Bug tracker -, Beginner friendly, Bug :-(, Duplicate ☝, Fixed in develop, Ready for work
