### ISSUE TITLE
Org export issue: unable to resolve link "configuring-spacemacs"

### ISSUE THREAD

**Issue by ztlevi** [syl20bnr/spacemacs#8054] opened 2016-12-25 07:20 UTC
I got an issue when I try to export org to other formats. 
![](https://ww3.sinaimg.cn/large/006tNc79gw1fb32a09augj30wo03wdh6.jpg)
Does anybody know this issue?
Thanks.

**Comment by d12frosted** [comment] 2016-12-25 08:27
I just tried to export to `html` and everything worked as expected. Could you please provide more clear reproduction steps? Also, having output of `SPC h d s` would be helpful.

**Comment by ztlevi** [comment] 2016-12-25 08:35
This is my config: https://github.com/ztlevi/Spacemacs-config
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 703733b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(php ivy better-defaults github ranger colors prodigy search-engine graphviz
     (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
     (spell-checking :variables spell-checking-enable-by-default nil)
     (vinegar :variables vinegar-reuse-dired-buffer t)
     (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
     (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org markdown)
     (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English")
     restclient
     (gtags :disabled-for clojure emacs-lisp javascript latex python shell-scripts)
     (shell :variables shell-default-shell 'eshell)
     docker deft markdown org shaders yaml react
     (python :variables python-test-runner
             '(nose pytest))
     (ruby :variables ruby-version-manager 'chruby)
     ruby-on-rails lua html javascript
     (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
     emacs-lisp
     (clojure :variables clojure-enable-fancify-symbols t)
     racket
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     zilongshanren
     (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx nil chinese-enable-youdao-dict t)
     dash)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES
Thanks.

**Comment by nikolaiam** [comment] 2017-01-07 13:41
I can reproduce this. The problem is related to the links in Org files referencing other parts of the same documents, such as the link on line 9 in CONTRIBUTING.org. Once these links are removed the file exports perfectly.

Reproduction steps:
- Do a clean Spacemacs install, enable org layer
- Open CONTRIBUTING.org
- Press `, e h H`
- Result: `user-error: Unable to resolve link: "asking-for-help"`
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org)
```

**Comment by smile13241324** [comment] 2017-01-08 15:40
Since org 9 internal links must be declared either as #customID or textTargetOrFullTextSearch. Relative path links must be either file:relative/path or ./relative/path. Many links are using the #customID form to trigger a full text search which is not defined as to the org documentation. In addition relative file paths are declared as relative/path which is also not defined. If this is done the html export can fail. Therefore the links must be corrected for the affected files.

See http://orgmode.org/manual/External-links.html#External-links and http://orgmode.org/manual/Internal-links.html#Internal-links

**Comment by smile13241324** [comment] 2017-01-08 15:41
I will have a look at the affected documentation files and correct the links if necessary.

**Comment by ztlevi** [comment] 2017-01-08 16:38
All right. Thanks.

**Comment by deb0ch** [comment] 2017-01-08 19:05
Just updated to latest develop and updated packages, and I am still experiencing a similar bug.

More importantly, this bug happens with auto-generated table of contents, so even if it's related to something changed in org-mode 9 API this should not happen and is definitely a bug.

Repro steps:

- write an org file with some headings
- insert an auto-generated table of contents
- try to export to html using `org-dispatch`
- `user-error: Unable to resolve link: "firstheading"`

**Comment by smile13241324** [comment] 2017-01-08 21:17
This is becoming even stranger, when I do as you say the links generated in my TOC are invalid when I try to follow them in org-mode. However when I export the document as html it works as expected.

I agree with you this really looks now like a bug in org mode. 

Anyway in the meantime I have went through the spacemacs documentation files and corrected some relative links as well as adding Custom_IDs for some headlines which org failed to find during export, so that on my branch I am able to export all the org files in the project root as well as the doc folder again.

Maybe we can use this to kill the symptoms of the issue until it is solved.

**Comment by syl20bnr** [comment] 2017-01-13 04:29
Does it still happen on current develop ?

**Comment by deb0ch** [comment] 2017-01-13 14:00
Just rebased current develop and updated packages, still happens.

When I try to export to html an org file that I wrote myself (with `, e e h o` in org-mode), it fails saying that it was unable to resolve the first link of my table of contents.

**Comment by deb0ch** [comment] 2017-01-13 14:03
Although it doesn't happen anymore in `CONTRIBUTING.org` :smile_cat:

**Comment by nikolaiam** [comment] 2017-01-13 16:05
At my end the TOC links export normally. @deb0ch, might there be something in particular in your `.org` file that breaks the export? In particular, how do you declare the `TOC`? In my case, the line has to be `:TOC:noexport:` to work.

**Comment by deb0ch** [comment] 2017-01-13 16:38
I'm just using `:TOC:`. Indeed, I just tried with `:TOD:noexport:` and it works :open_mouth: 

This is so fucked up, since `:noexport:` is [documented](http://orgmode.org/manual/Export-settings.html) as being for excluding the concerned item from any export (*unconditionally* sic), and my table still got exported...

I don't understand that thing. Is it a bug ? Or is it intentional ? :confused:

**Comment by nikolaiam** [comment] 2017-01-14 08:22
I dunno, just found out about this when trying to reproduce your behaviour :smile:. But I guess it might be a bug in [toc-org](https://github.com/snosov1/toc-org).

**Comment by deb0ch** [comment] 2017-01-14 10:17
@nikolaiam Reporting, thanks for the link :smile_cat:

**Comment by smile13241324** [comment] 2017-02-02 06:00
Just wanted to start the discussion again what to do next after snosov1 answered to our issue. 

The bottom line seems to be that the org html export is not compatible with the link style generated by toc-org.

I have tried the proposed solution of using the org hrefify function by using the alternative toc tag but this only works if we generate a toc for the two headline levels only.

The noexport tag is actually fixing the issue because this triggers toc-org to remove the toc for the html export which then creates its own toc.

So should we now try to raise a bug for the org html export or provide our own hrefify function or simply ensure that all tocs are also having the noexport flag?

Independent of the outcome of this discussion I think we should write a test to ensure that all org files can be generated to html and that all links are valid.

**Comment by syl20bnr** [comment] 2017-02-03 22:57
@smile13241324 
Not sure it is relevant for this discussion, I'm not 100% sure to understand documentation generation in Spacemacs, maybe @JAremko can provide more info.

In order to support links generated by both GitHub org renderer and org html renderer we use the GitHub format in org files written for Spacemacs, to be able to export to html files using org for spacemacs.org hosted documentation we unhrefify the links first, this may be the same kind of strategy you propose. You can find the functions there: https://github.com/syl20bnr/spacemacs/blob/develop/core/tools/spacefmt/toc-org.el#L156-L252

Hope this help :-)

**Comment by JAremko** [comment] 2017-02-04 04:57
@syl20bnr  We attach org-mode `CUSTOM_ID` property annotation to each headline. It makes org-mode export use `CUSTOM_ID:` value in URL's   Then we export and mark buffer as unmodified (to avoid saving properties)

**Comment by smile13241324** [comment] 2017-03-03 22:13
Finished the test for the org html export. It ensures that all documentation org files can be converted to html and that all contained external links are valid. 

See merge request: #8431

**Comment by JAremko** [comment] 2017-03-04 01:00
@smile13241324    You'll need advices from  [` spacemacs/publish-doc`](https://github.com/syl20bnr/spacemacs/blob/master/core/core-documentation.el#L179)   

Maybe we can move them from this function and use globally for org files marked as Spacemacs documentation.

**Comment by smile13241324** [comment] 2017-03-05 09:21
@JAremko This may not be necessary, I will simply execute `spacemacs/publish-doc` and then direct the html check code against all html files in the `export` directory.

**Comment by smile13241324** [comment] 2017-03-14 21:26
Finished the test, related PR: #8431

For travisCI I have deactivated the external link check for now as this seems to exceed a bandwith limit which will cause the job to stop following links. Needs to be executed locally.

**Closed** 2017-04-02 06:00 UTC
Labels: - Bug tracker -, Core, High Priority, Org
