### ISSUE TITLE
Cannot insert space after C-rx in insert mode

### ISSUE THREAD

**Issue by duerrp** [syl20bnr/spacemacs#1983] opened 2015-06-14 05:59 UTC
After pasting a register in insert mode via C-r, typing space triggers the leader command instead of inserting a space. Any other character works fine.

Any idea how to debug this?

Best
Peter

P.S. keep up the awesome work, I love spacemacs!

**Comment by syl20bnr** [comment] 2015-06-21 03:05
Thank you for the report, was caused by the paste micro-state which was triggered after the paste. Should be fixed in develop.

**Closed** 2015-07-02 12:25 UTC
Labels: bug :-(, Evil, Fixed in `develop`, Micro-state
