### ISSUE TITLE
Spacemacs doesn't recognize theme belongs to a package

### ISSUE THREAD

**Issue by tidux** [syl20bnr/spacemacs#15538] opened 2022-05-22 02:19 UTC
I have the package `color-theme-modern` installed and have added `word-perfect-theme` from that package to my rotation of default Spacemacs themes.  Unlike the `themes-megapack` layer, `color-theme-modern` is a monolithic package that supports multiple themes.  Spacemacs keeps searching for a package named `word-perfect-theme` at startup, apparently because it thinks each theme must be individually packaged.  Can I suppress this behavior?

**Comment by hem1t** [comment] 2023-07-07 18:39
I was having this issue with 'doom-old-hope', I checked out and saw that 'spacemacs-theme-name-to-package' is a list which holds the themes and its location(? Not sure), I'm not good with elisp. That's why I didn't think much and manually added 'doom-old-hope' to the list, instead of finding an actual solution.

**Comment by smile13241324** [comment] 2024-09-14 10:18
Currently this is not officially supported, I will see if I can add a solution

**Comment by bryce-carson** [comment] 2024-09-27 06:30
I believe I have previously ran into this issue with the **modus-themes** package. The modus themes themselves are _built-in_ to Emacs now (28+), but if a user installs the **modus-themes** package on Emacs 27.X  and includes the theme in their theme rotation they can experience it.

**Comment by bryce-carson** [comment] 2024-09-27 06:31
> I was having this issue with 'doom-old-hope', I checked out and saw that 'spacemacs-theme-name-to-package' is a list which holds the themes and its location(? Not sure), I'm not good with elisp. That's why I didn't think much and manually added 'doom-old-hope' to the list, instead of finding an actual solution.

Indeed, that's the culprit. I had a conversation with @lebensterben about it once in another PR but that wasn't merged if I recall.

**Comment by bryce-carson** [comment] 2024-09-27 06:35
#15453 was the PR. It was merged, but that just added to the alist. There was discussion about a different solution using a hash table.

**Comment by sunlin7** [comment] 2024-11-22 01:56
Why not just let user add the customer theme package into the `dotspacemacs-additional-packages`? The themes are variant, and a package may provide several themes... 

I'm worry about that, the map for (theme, package) will growth again and again until no one can maintenance it. 

We should write the document for customer who want use an specific theme should add the package into `dotspacemacs-additional-packages`, instead of growth the table.

**Comment by bryce-carson** [comment] 2024-11-22 02:51
The problem is these themes are usually a part of the themes-megapack
layer. It's a bug and we should analyze it further.

**Comment by sunlin7** [comment] 2024-11-23 03:44
If a multiple-theme-included package adding/removing a theme in its package, Spacemacs has to change `spacemacs-theme-name-to-package` to correct the map.

Actually after the PR #16650, we can extent the `dotspacemacs-themes` to support themes in a specific package. 

Here are the PR #16684.

No more maintenance required for  `spacemacs-theme-name-to-package`, user just add theme with its package name, example:
```
    dotspacemacs-themes '((humanoid-light :package humanoid-themes)
                                           spacemacs-dark)
```

**Comment by sunlin7** [comment] 2024-11-27 14:27
Look forward your comments @bryce-carson @tidux @smile13241324 @hem1t

**Closed** 2024-11-28 20:05 UTC
Labels: Feature request

**Comment by tidux** [comment] 2024-12-01 01:27
I ended up switching to LazyVim as primary but I'll give this another try to validate.
