### ISSUE TITLE
cl-ecase failed after pressing enter inside helm-find-files

### ISSUE THREAD

**Issue by benjfisk** [syl20bnr/spacemacs#13733] opened 2020-06-30 06:01 UTC
#### Description :octocat:
After pressing enter to open a file inside helm-find-files, I get the error:
cl-ecase failed : nil, (t local remote)

#### Reproduction guide :beetle:
- Start Emacs
- <spc ff>
- Press enter to open a file

*Observed behaviour:* :eyes: :broken_heart:
I get the error: cl-ecase failed : nil, (t local remote)
*Expected behaviour:* :heart: :smile:
Helm-find-files closes the helm-find-files window and opens the file.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: nil (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

**Comment by benjfisk** [comment] 2020-07-01 09:09
If i delete the code body of helm-ff--cleanup-cache I no longer get this error and Spacemacs opens the file as expected.

**Comment by smile13241324** [comment] 2020-07-02 22:54
@benjfisk I am not sure on which branch you are, please switch to latest develop and confirm that the issue is still there.
If not please close this ticket.

**Closed** 2020-07-03 02:32 UTC

**Comment by christophe-riolo** [comment] 2020-07-15 19:41
For anyone coming here, I struggled with that also, only to find that I had to update the helm package simply.
