### ISSUE TITLE
literate-haskell-mode doesn't have haskell-mode bindings

### ISSUE THREAD

**Issue by jb55** [syl20bnr/spacemacs#4974] opened 2016-02-05 21:38 UTC
Tried to update the layer by adding `literate-haskell-mode-hook` in a few places but couldn't get it working :[

**Comment by StreakyCobra** [comment] 2016-02-06 10:25
@d12frosted I think this can be nice to have. Do you have any information why this is currently not done?

**Comment by d12frosted** [comment] 2016-02-07 07:53
Dunno honestly. I don't use literate haskell mode, so I never bothered myself with making configs for it. But we already have pending PR for it: https://github.com/syl20bnr/spacemacs/pull/3459.

**Comment by d12frosted** [comment] 2016-02-07 07:54
So if that PR is abandoned we should create a new one :D

**Comment by jb55** [comment] 2016-02-07 07:57
Didn't see that PR, will try to get it working in a bit

**Comment by StreakyCobra** [comment] 2016-02-07 12:23
Oh, right there is already an issue about this. Closing this one as duplicate of #3458.

**Closed by StreakyCobra** 2016-02-07 12:23 UTC
Labels: Haskell, question
