### ISSUE TITLE
how to change the line spacing for the kbd help buffer after entering C+x?

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#6926] opened 2016-08-27 04:57 UTC
the line spacing is too large, I am wondering if there is a way to make it smaller.

<img width="1093" alt="screenshot 2016-08-26 16 11 54" src="https://cloud.githubusercontent.com/assets/11595258/18025231/067ef9dc-6bd8-11e6-85b4-68efaa93e56f.png">

**Comment by TheBB** [comment] 2016-08-27 13:30
Duplicate of https://github.com/syl20bnr/spacemacs/issues/6935

Please only open one issue (and please, report this to which-key, where it belongs.)

**Closed by TheBB** 2016-08-27 13:30 UTC
