### ISSUE TITLE
Transient state prompt for perspective is not rendering properly

### ISSUE THREAD

**Issue by shivamkalra** [syl20bnr/spacemacs#4876] opened 2016-01-30 06:59 UTC
#### Description
This issue is only on *develop* branch.
Switching between perspectives used to show all the perspective's names in transient state prompt, but with recent update it is only showing [1:Default]. 

#### Reproduction guide
- Use `perspective` layer 
- Start Emacs
- Create some perspectives by pressing `SPC + l + 2`
- Now try to switch between perspectives `SPC + l`
- You will not see new perspectives you created and only *[1:Default]*

*Observed*
You do not see all the perspectives instead only *[1:Default]*
![2016-01-30-015001_564x141_scrot](https://cloud.githubusercontent.com/assets/1386352/12694238/7e4b11d2-c6f4-11e5-9d1e-362e02d07f37.png)

*Expected*
You should see all the perspective names.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 33fd71d)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp gtags c-c++ version-control git markdown org gnus shell syntax-checking csharp sql csharp lua elpy elfeed xkcd haskell extra-langs spell-checking ipython-notebook
 (erc :variables erc-sasl-server-regexp-list
      '("irc\\.freenode\\.net"))
 shell-scripts theming javascript html colors ibuffer smex github themes-megapack fasd wakatime notmuch mu4e
 (latex :variables latex-enable-auto-fill t))
```

**Comment by bmag** [comment] 2016-01-30 07:38
duplicate of issue #4822, fixed by pending PR #4823

**Comment by robbyoconnor** [comment] 2016-01-30 07:41
@bmag how are you not on the core team as well?!

**Comment by StreakyCobra** [comment] 2016-01-30 23:55
Closing as duplicate (see @bmag comment for details). But thx for your nice reporting @shivamkalra :-) (btw you can use `SPC h I` on `develop` to open an issue with the template pre-filled ;-) )

**Closed by StreakyCobra** 2016-01-30 23:55 UTC
