### ISSUE TITLE
Does not quit... requires force quit.

### ISSUE THREAD

**Issue by EdmundsEcho** [syl20bnr/spacemacs#6132] opened 2016-05-25 22:19 UTC
#### Description
I close my windows using :q   However, spacemacs does not quit.  This bug is present regardless if I launch spacemacs from terminal or applications.

#### Reproduction guide
- Start Emacs
- :q

*Observed behaviour:*
The window closes but emacs remains active in the finder.

Note: The packages have been updated.  However, spacemacs does not update: emacs directory is not clean.  Related?

*Expected behaviour:*
Expected to close all processes.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
 emacs-lisp markdown
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control osx
 (haskell :variables haskell-enable-hindent-style "chris-done"))
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment] 2016-05-30 13:47
What is your setting of `dotspacemacs-persistent-server`?

**Comment by EdmundsEcho** [comment] 2016-06-18 12:09
it was set to `dotspacemacs-persistent-server t`  Setting it to `nil` fixed the problem.  Thank you.  Where is there a list of all of the settings and definitions?

**Comment by TheBB** [comment] 2016-06-18 12:56
The dotfile variables are all in your dotfile. We sometimes add new ones, in which case the updated list is in ~/.emacs.d/core/templates/.spacemacs.template. You can diff it with your actual dotfile using `SPC f e D` although I like to just read it and compare manually (since I removed the comments, the diff is really noisy).

Since the problem is fixed for you, I'll close this issue. :-)

**Closed by TheBB** 2016-06-18 12:56 UTC
Labels: - Bug tracker -, OS X, To be reproduced
