### ISSUE TITLE
evil-escape issues on develop

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3033] opened 2015-09-14 19:43 UTC
I am having constant problems exiting the various vim modes in spacemacs.

The issue is that, while the escape key sequence works *most* of the time, there are times where it'll just stop working until you restart emacs.

At first, I was using `C-[`.  I'd used it in vim for years, but it would not consistently exit insert mode in python-mode.  So, I decided to switch to spacemacs recommended key combination (`fd`, which, as you know, isn't the simplest thing in the world, after 9 years of using `C-[`).

Unfortunately, `fd` does the same thing.  Eventually, it'll just stop working while I'm editing python files.  Other escape sequences like actual `ESC` and `C-[` work at this point, so it doesn't seem like one breaks the others.

To me, this is one of the very most important features of spacemacs, but still one of the features I have the most trouble with.  If you can enter and exit modes consistently, it's going to get very frustrating very quickly.

**Comment by syl20bnr** [comment] 2015-09-14 20:41
When you encounter the issue, open the Messages buffer and paste the error you get. Evil-escape stops to work because there is an error in its hook so Emacs automatically removes it.

As a work around, disabling and reenabling evil-escape should work.

**Comment by synic** [comment] 2015-09-14 20:42
Ok, next time it happens I will post the message here.

**Comment by synic** [comment] 2015-09-15 02:32
There are times when it happens, but only for a moment.  It seems to be related to flycheck, but I'm really just guessing there.  

This is all I see in messages:

```
Mark saved where search started [2 times]
Skip anaconda-mode complete response
```

It's almost like I'm trying to press `fd` too quickly after I am done typing.

**Comment by reed1** [comment] 2015-09-17 11:43
Hi, I have this issue also. Editing python files made `fd` doesn't work anymore.I tried to disabling then enabling evil-escape with `SPC : evil-escape-mode` twice, but still doesn't work after that. I guess this is related to anaconda-mode. Message Buffers doesn't seem to report any error :

```
Skip anaconda-mode complete response
python-completion-complete-at-point: Completion needs an inferior Python process running
ad-handle-definition: `eval-defun' got redefined
Evil-Escape mode disabled
Evil-Escape mode enabled
```

**Comment by synic** [comment] 2015-09-17 15:32
Yeah, it definitely seems to have something to do with either anaconda or flycheck.  When you stop typing, flycheck runs, and if you type `fd` during that time fast enough, it gets you into a weird state.

**Comment by synic** [comment] 2015-09-20 00:30
Ok, just happened to me.  This is not the same thing that happened before, but it'll do.

I was trying to type `fd` really fast in the dialog where you modify custom faces.  After that, `fd` wouldn't work at all.

In `*Messages*`:

```
scroll-up-command: End of buffer
Error in pre-command-hook (evil-escape-pre-command-hook): (text-read-only "Attempt to change text outside editable field")
Custom-no-edit: You can't edit this part of the Custom buffer [3 times]
~/.spacemacs and /Users/synic/.dotfiles/.spacemacs are the same file
```

**Comment by mclearc** [comment] 2015-09-21 05:41
I'm getting this as well. The error message is:

```````````
Error in pre-command-hook (evil-escape-pre-command-hook): (wrong-number-of-arguments #[(x y) "\206	\207" [x y] 1] 0)
``````````

I'm just editing my `.spacemacs` file when this happens.

**Comment by bmag** [comment] 2015-09-21 12:32
I'm also getting this error, it's probably the same as this one: https://github.com/syl20bnr/evil-escape/issues/43

**Comment by jakub-wojciech** [comment] 2015-09-21 16:25
I have got this line in my .spacemacs file:
```evil-escape-key-sequence (kbd "jk")```
And this stopped working after updating repositories today. Previously I had a development version from last week.

**Comment by synic** [comment] 2015-09-21 16:26
@mclearc, @bmag, @jakub-wojciech:

I think what you are experiencing is a different bug introduced last night.  It should be fixed now and up on melpa.

I don't think the two issues are related, but I don't know for sure.

**Comment by mclearc** [comment] 2015-09-21 17:59
@synic The melpa update seems to have fixed my issue -- thanks!

**Comment by bmag** [comment] 2015-09-21 18:32
@synic you're correct, the melpa update fixed one bug, but I am able to reproduce the text-read-only error in Customize buffers.

**Comment by syl20bnr** [comment] 2015-09-22 13:15
The version 3.09 of today should be more resilient to errors and it should be now possible to escape in read-only buffers.

**Comment by syl20bnr** [comment] 2015-09-22 13:16
The version has not yet been processed by MELPA, be patient :-)

**Comment by synic** [comment] 2015-09-22 14:59
Yay!

**Comment by jakub-wojciech** [comment] 2015-09-22 15:37
It's fixed for me now :)

**Comment by TheBB** [comment] 2015-09-29 13:02
Closing this since it seems to be fixed. If I'm mistaken please reopen. :-)

**Closed by TheBB** 2015-09-29 13:02 UTC
Labels: bug :-(, Evil-escape, package, to be reproduced
