### ISSUE TITLE
Navigation is borked

### ISSUE THREAD

**Issue by yungstorm** [syl20bnr/spacemacs#2964] opened 2015-09-09 17:49 UTC
Everytime I try and navigate in spacemacs It  adds >[2 q to the lines..This really annoying because it doesn't allow me to navigate. 
![2015-09-09-134623_598x374_scrot](https://cloud.githubusercontent.com/assets/12653273/9769674/90bf909c-56f9-11e5-86a3-19991fa2d35c.png)

**Comment by cmccloud** [comment] 2015-09-09 18:02
@yungstorm are you running in terminal?

**Comment by yungstorm** [comment] 2015-09-09 18:14
@cmccloud yes I'm running it in terminal.

**Comment by cpaulik** [comment] 2015-09-09 18:18
Probably a  duplicate of https://github.com/syl20bnr/spacemacs/issues/2707 and https://github.com/syl20bnr/spacemacs/issues/2940 . 

Try adding `evil-terminal-cursor-changer` to your `dotspacemacs-exlude-packages`

**Comment by Tritlo** [comment] 2015-09-09 22:30
I had the same issue in terminal, and @cpaulik's suggestion worked for me.

**Comment by syl20bnr** [comment] 2015-09-10 12:56
Maybe we should remove this package ?

**Comment by TheBB** [comment] 2015-09-10 13:06
I think so.

**Comment by dzhwinter** [comment] 2015-09-11 14:00
same problem+1. It seems no benefits in my opinion. Make cursor become block when browse file and bar edit file.is enough.  .

**Closed** 2015-09-28 06:53 UTC
Labels: Fixed in `develop`, Terminals
