### ISSUE TITLE
ein fails to build 

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#7181] opened 2016-09-24 00:27 UTC
#### Description :octocat:
Ein fails to build. I reported upstream millejoh/emacs-ipython-notebook#119 

#### Reproduction guide :beetle:
- Delete `ein` package from your `elpa` directory
- Start emacs

*Observed behaviour:* :eyes: :broken_heart:

Errors out 

*Expected behaviour:* :heart: :smile:

Should build correctly. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(bibtex rebox nginx twitter graphviz ivy helm asciidoc elfeed speed-reading swift plantuml
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
        better-defaults emacs-lisp
        (git :variables git-magit-status-fullscreen t)
        github gnus version-control markdown syntax-checking
        (latex :variables latex-enable-auto-fill t)
        (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
        docker ansible puppet evil-commentary
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        fasd finance floobits xkcd autohotkey csv nlinum
        (c-c++ :variables c-c++-enable-clang-support t)
        (clojure :variables clojure-enable-fancify-symbols t)
        extra-langs go
        (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
        html java
        (javascript :variables javascript-disable-tern-port-files t)
        (python :variables python-enable-yapf-format-on-save t python-test-runner
                '(nose pytest))
        racket
        (ruby :variables ruby-version-manager `rvm)
        ruby-on-rails
        (rust :variables rust-enable-rustfmt-on-save t)
        scala shell-scripts restclient themes-megapack tmux vim-empty-lines spotify pandoc vagrant
        (ibuffer :variables ibuffer-group-buffers-by 'projects)
        semantic deft
        (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
        erc chrome d emoji gtags prodigy evernote
        (org :variables org-enable-github-support t org-enable-reveal-js-support t)
        search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger wakatime dash spell-checking jabber cscope vinegar rcirc games react php vimscript geolocation idris
        (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
        elixir
        (typography :variables typography-enable-typographic-editing nil)
        evil-cleverparens pdf-tools imenu-list slack systemd command-log)
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "zeroein.el:0:0: error: wrong-type-argument: (listp emacs-lisp-mode)")
  signal(error ("zeroein.el:0:0: error: wrong-type-argument: (listp emacs-lisp-mode)"))
  error("%s:0:0: error: %s: %s" "zeroein.el" wrong-type-argument (listp emacs-lisp-mode))
  autoload-generate-file-autoloads("zeroein.el" nil "/home/rob/.emacs.d/elpa/ein-20160923.837/ein-autoloads.el")
  update-directory-autoloads("/home/rob/.emacs.d/elpa/ein-20160923.837")
  package-generate-autoloads(ein "/home/rob/.emacs.d/elpa/ein-20160923.837")
  package--make-autoloads-and-stuff([cl-struct-package-desc ein (20160923 837) "Emacs IPython Notebook" ((websocket (1 5)) (request (0 2)) (cl-generic (0 2))) tar "melpa" nil nil nil] "/home/rob/.emacs.d/elpa/ein-20160923.837")
  package-unpack([cl-struct-package-desc ein (20160923 837) "Emacs IPython Notebook" ((websocket (1 5)) (request (0 2)) (cl-generic (0 2))) tar "melpa" nil nil nil])
  #[256 "\306\307!r\211q\210\310\311\312\313\314!\315\"
```

**Comment by millejoh** [comment] 2016-09-24 16:27
Looks like `autoload-generate-file-autoloads` is having a hard time parsing zeroein.el. Note that zeroein.el looks a bit different from your usual elisp file because it can be called from the bash prompt. Does everything work if you delete the top two lines of the file? The lines in question look like this:

```elisp
#! /bin/sh
":"; exec ${EMACS:-emacs} --no-init -Q -l "$0" "$@" # -*-emacs-lisp-*-
```

I will be surprised if this works, since zeroein.el has looked this way for a long, long time and it is odd that it would suddenly start causing problems now, but honestly I'm not sure what else to try. Unfortunately I cannot reproduce on my system (which is spacemacs-base-0.105.22), so I will need some additional help troubleshooting.

**Comment by millejoh** [comment] 2016-09-24 17:00
Also note that ein will still work quite happily if you completely delete zeroein.el. Maybe that works for you? Given this, I think I will update the melpa recipe to exclude this file in future builds.

**Comment by robbyoconnor** [comment] 2016-09-25 08:57
Maybe update it to exclude this file?

**Comment by millejoh** [comment] 2016-09-30 12:29
Before I do that, could you confirm if deleting zeroein.el fixed your problem?

**Comment by robbyoconnor** [comment] 2016-09-30 18:09
For some reason the issue went away...not sure why..

**Comment by deb0ch** [comment] 2016-10-16 17:58
Autumnal clean up: by "the issue went away", do you mean that it is not reproductible anymore and that we can close this ? :smile:

**Comment by robbyoconnor** [comment] 2016-10-17 01:52
Not so fast @deb0ch

**Comment by robbyoconnor** [comment] 2016-10-17 02:34
Soon as @millejoh merges millejoh/emacs-ipython-notebook#125 -- we should be good -- but this is still an issue -- I tracked down the issue.

**Comment by d12frosted** [comment] 2016-10-21 10:00
PR was merged upstream, so closing this issue.

**Closed by d12frosted** 2016-10-21 10:00 UTC
Labels: - Bug tracker -, Fixed upstream, Reported upstream

**Comment by robbyoconnor** [comment] 2016-10-22 01:12
I meant to close this
