### ISSUE TITLE
Restart fails

### ISSUE THREAD

**Issue by agenbite** [syl20bnr/spacemacs#15505] opened 2022-05-10 08:18 UTC
#### Description :octocat:
Restart with layout resume fails

#### Reproduction guide :beetle:
- Start Emacs
- Hit `SPC q r`

*Observed behaviour:* :eyes: :broken_heart:
The following error appears: "spacemacs/restart-emacs: Wrong number of arguments: restart-emacs, 1"

*Expected behaviour:* :heart: :smile:
Spacemacs should restart and restore layouts.

The problem is that `spacemacs/restart-emacs` tries to pass an argument to `restart-emacs`, which does not accept any arguments.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c6c17748f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: selectrum
- Layers:
```elisp
(csv python go org notmuch evil-snipe
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-override-mode t)
     latex bibtex git pdf emacs-lisp compleseus
     (compleseus :variables compleseus-engine 'selectrum)
     ranger)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBSELINUX LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS XIM GTK3 ZLIB

**Comment by practicalli-john** [comment] 2022-05-11 09:16
I cannot replicate this issue on Emacs 28.1 on gnu/linux

* `SPC q r` restarts emacs and loads existing layouts
* `SPC q R` restarts emacs and loads existing layouts too...

Spacemacs seems to be using the restart-emacs package which includes a function called `restart-emacs` that takes optional arguments
https://github.com/iqbalansari/restart-emacs/blob/master/restart-emacs.el#L396

Searching through the code of Spacemacs 0.999 (latest develop commit) the `restart-emacs` function definition is found in `~/.config/emacs/elpa/28.1/develop/restart-emacs-20201127.1425/restart-emacs.el`

Has Emacs 29.0.50 introduced its own `restart-emacs` function?

Otherwise, the restart-emacs package has not changed in a considerable time.
Try removing the .elc file for this package (or the package itself) from the elpa directory and restart Emacs to update / download the code again.

**Comment by agenbite** [comment] 2022-05-11 11:11
I'm a total noob in emacs development, but apparently 3 weeks ago there was a commit series related to `restart-emacs` (starting in [5be9a9cacf](https://github.com/emacs-mirror/emacs/commit/5be9a9cacfaae1959c4b95c45c146044a181ad20)). I'll try to dig a bit deeper in that place.

**Comment by drewverlee** [comment] 2022-05-11 23:19
I can replicate this. Here is the output from emacs version:

`GNU Emacs 29.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-05-06`

Where would i look to remove the .elc file?

**Comment by BenedictHW** [comment] 2022-05-12 00:40
/home/$USER/.emacs.d/elpa/29.0/develop/restart-emacs-20201127.1425/restart-emacs.elc

**Comment by edwinclement08** [comment] 2022-05-16 05:56
Facing the same issue. Thanks for the reporting

**Comment by dalanicolai** [comment] 2022-05-17 12:19
FYI, a simple quick-fix is to press `SPC h SPC restart-emacs` and replace the `:defer t` for `:after files`.

**Comment by agenbite** [comment] 2022-05-18 14:58
Thanks, @dalanicolai, that solves it for the moment.

**Comment by smile13241324** [comment] 2022-06-11 12:31
@agenbite Please have a try with latest develop and close this ticket when it works, thanks.

**Comment by magthe** [comment] 2022-06-12 05:21
The issue above, [Try to fix name clash in emacs 29](https://github.com/syl20bnr/spacemacs/commit/c41bb1406bf89026c34875df73e31aa4434c117e), doesn't fix things. What @dalanicolai suggests, and what I just confirmed works for me, is to _replace_ `:defer t` with `:after files`. That is, what I did to make it work after the change above is

```
diff --git a/layers/+spacemacs/spacemacs-navigation/packages.el b/layers/+spacemacs/spacemacs-navigation/packages.el
index 075485405..4c04f1bb1 100644
--- a/layers/+spacemacs/spacemacs-navigation/packages.el
+++ b/layers/+spacemacs/spacemacs-navigation/packages.el
@@ -367,7 +367,6 @@
 
 (defun spacemacs-navigation/init-restart-emacs ()
   (use-package restart-emacs
-    :defer t
     :after files
     :init
     (spacemacs/set-leader-keys
```

**Comment by dalanicolai** [comment] 2022-06-12 06:58
@smile13241324 @magthe I did not think about keeping, the `defer`, although that looks better indeed. However, apparently when a function with a name is already loaded, then the `autoload` for some other function with the same name does not seem to work (just tested it).

So indeed I think it really is necessary to remove the `:defer t` (or check and 'fix' the autoload mechanism) as in @magthe his PR.

**Comment by smile13241324** [comment] 2022-06-12 07:27
Ahh crap :(, I have removed the defer keyword now, please give it another try. Maybe a better solution would be to not use this package at all when emacs 29 is available however I am not sure how stable the api already is and whether we would loose features there. Anyway this would be a good topic for a following PR if somebody wants to invest the time :). For now this fix would at least make it working again.

Can you have another go @magthe and confirm when its working? I am still stuck on emacs 28.1 without native compilation, need to change my IDE setup to build emacs from source again...

**Comment by magthe** [comment] 2022-06-28 04:19
It works fine now @smile13241324

**Closed** 2022-06-28 13:44 UTC

**Comment by vitaminace33** [comment] 2023-11-07 22:00
Is anybody experiencing a bug regression?

**Comment by smile13241324** [comment] 2023-11-08 07:04
@sunlin7 can you double check? This could be caused by lazy loading emacs restart.

**Comment by agenbite** [comment] 2023-11-08 08:29
I haven't experienced that issue since. Thanks for your work!

**Comment by sunlin7** [comment] 2023-11-08 17:30
Hi @agenbite 
Please help verify the change in https://github.com/syl20bnr/spacemacs/pull/16186 for the issue. I had verified on emacs-29.1. 
Thanks

**Comment by vitaminace33** [comment] 2023-11-09 19:04
I updated this morning and `SPC-m q r`/`SPC-m q R` works just fine. Thx!

**Comment by sunlin7** [comment] 2023-11-10 00:14
Thanks for the information!
