### ISSUE TITLE
Can't use compose key on OSX with spacemacs

### ISSUE THREAD

**Issue by nolith** [syl20bnr/spacemacs#8095] opened 2017-01-02 11:32 UTC
#### Description :octocat:
Can't use compose key on OSX with spacemacs

OSX keyboard uses composition based on `alt` key.

Here are just a couple of examples that works on every input in the OS except on spacemacs.

 ``alt  + `  e => è``
 ``alt  + e e => é``
 ``alt  + ` a => à``

#### Reproduction guide :beetle:
- Start Emacs
- visit a buffer
- enter editing mode
- press ``alt  + ` ``
*Observed behaviour:* :eyes: :broken_heart:
The buffer lost focus and the minibar prompt "Menu bar ..."

*Expected behaviour:* :heart: :smile:
This should start a compose mode, now pressing a key should compose it with the `

``alt +  ` e``  should write è

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(graphviz erc sql javascript html ruby python osx helm auto-completion better-defaults emacs-lisp git markdown org spell-checking ruby-on-rails ansible docker terraform xkcd emoji shell-scripts spotify systemd)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by d12frosted** [comment] 2017-01-03 09:12
Hey, 

This is behaviour is expected. If you wish another behaviour, you have to configure meta key. Also note that this is a duplicate of following topics:

- https://github.com/syl20bnr/spacemacs/issues/5188 (I use solution described there - `CMD` for `META` and `option` as is. 
- https://github.com/syl20bnr/spacemacs/issues/7599 (shows yet another possible solution).
- https://github.com/syl20bnr/spacemacs/issues/1435.

Also you could just use `osx` layer that [exposes similar configuration](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bos/osx#use-with-non-us-keyboard-layouts). 

Another solution might be using `input-method` (where you can define all special characters). I use `input-method` to type in non-latin languages. 

In the end it's up to you how to configure it, because what works to one person might not work for the other. 

P. S. Closing this issue as it's a) as expected and b) is a duplicate.

**Closed by d12frosted** 2017-01-03 09:12 UTC
