### ISSUE TITLE
Shell layer shell buffer doesn't obey location property

### ISSUE THREAD

**Issue by MRFaria** [syl20bnr/spacemacs#8381] opened 2017-02-16 10:20 UTC
**Description:**
Shell layer shell buffer doesn't obey location property when the default shell is 'shell

**Reproduction guide:** 
- Start Emacs
- run <SPC '>

**Observed behaviour:**
Starting the shell buffer by pressin <SPC '> brings it up at the top of the frame, or in an already created split window. Not the bottom as requested by setting 'shell-default-position to 'bottom

**Expected behaviour:**
Shell buffer should appear at the bottom. Note, this works if I set 'shell-default-shell to 'ansi-term; but I prefer using 'shell.

**System Info:**
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. 57e653a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python ibuffer helm auto-completion better-defaults emacs-lisp c-c++ semantic d gnus
        (gtags :variables gtags-enable-by-default t)
        (shell :variables shell-default-shell 'shell shell-default-position 'bottom)
        (org))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by MRFaria** [comment] 2017-02-16 10:20
C-c C-c to submit the issue didn't work for me from emacs, so I just copies and pasted the text in the buffer

**Comment by bmag** [comment] 2017-02-19 10:30
Sounds like either #7691 (upstream bug in shell-pop, reproducible in stock Emacs) or #8171 (some clash between window-purpose and shell-pop). @MRFaria can you verify that your problem either reproduces with stock Emacs, or disappears if you disable `purpose-mode`?

**Comment by MRFaria** [comment] 2017-02-19 11:36
Disabling purpose-mode doesn't do anything, but it looks like it still happens in stock emacs.
I installed shell-pop through marmalade:
`M-: (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
M-x package-refresh-contents
M-x package-install [RET] shell-pop`

Then I customised shell-pop to appear on the bottom:
`M-: require  
M-x customize-set-variable RET  shell-pop-window-position RET bottom`

The when running shell-pop it appears on the top of the frame anyway

**Comment by bmag** [comment] 2017-02-19 11:42
@MRFaria thanks, I'm closing this as a duplicate of #7691. We're waiting for the issue to be resolved upstream. Judging from the activity in https://github.com/kyagi/shell-pop-el/commits/master, it seems it won't be fixed unless someone submits a patch.

**Closed by bmag** 2017-02-19 11:42 UTC
Labels: - Bug tracker -, Shells in Emacs
