### ISSUE TITLE
Creating a new zoomed frame results in half-zoomed new frame

### ISSUE THREAD

**Issue by hexagonal-sun** [syl20bnr/spacemacs#12731] opened 2019-09-15 16:22 UTC
##### Description :octocat:
Creating new frame when zoomed results in a half-zoomed frame

#### Reproduction guide :beetle:
- Start Emacs
- Zoom in the current frame `SPC z f      `
- Create a new frame `SPC w F`

*Observed behaviour:* :eyes: :broken_heart:
The mode line has the thickness of the zoomed frame however all text doesn't
appear to be zoomed.

*Expected behaviour:* :heart: :smile:
The new frame should either be zoomed out at the default level or have the same
zoom as the existing frame.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 40024fedb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(yaml helm emacs-lisp git python gnus javascript react latex
      (c-c   :variables c-c  -enable-clang-support t)
      (auto-completion :variables auto-completion-complete-with-key-sequence "jk")
      (erc :variables erc-server-list
           '(("irc.freenode.net" :nick "ixlun" :ssl t :port "6697"))
           erc-autojoin-channels-alist
           '(("freenode.net" "#emacs" "##hamradio" "##chessprogramming"))
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
N/A
```

**Comment by duianto** [comment] 2019-09-15 19:52
This sounds like it might be a duplicate of this issue:
frame-local zoom affects some parts of powerline globally #820

**Comment by hexagonal-sun** [comment] 2019-09-16 16:15
duianto <notifications@github.com> writes:

> This sounds like it might be a duplicate of this issue:
> frame-local zoom affects some parts of powerline globally #820

Agreed.  If this is fixed then presumably when making a new frame the
zoom level would reset.
-- 
Matt

**Closed** 2019-12-22 06:45 UTC
Labels: Duplicate ☝
