### ISSUE TITLE
Updating spacemacs breaks org-mode. How to find the causing package/error?

### ISSUE THREAD

**Issue by moritzschaefer** [syl20bnr/spacemacs#16118] opened 2023-08-11 15:50 UTC
#### Description :octocat:
When updating my spacemacs (through `git pull`) more often than not, I get into trouble with org. 

As recommended by others in similar situations, I tried to `find ~/.emacs.d/elpa -name '*.elc' -delete` but without success, unfortunately.
Also, I am aware that this might be due to the "builtin org version loading", but I have unfortunately no clue at which point of my init loading, the wrong org-mode is loaded (I wrapped all my org-mode related init code within eval-after-load). The error also only pops up, when loading my org-related code. I can't even use the debugger/backtrace because within the eval-after-load  block, it does not show which line of code caused the error. 

Do you have any advice on how to find the causing package/error?

#### Reproduction guide :beetle:
- Update spacemacs in develop branch (git pull)
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
org-mode always has issues loading. Most common exception: (Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: org-link-set-parameters

*Expected behaviour:* :heart: :smile:
org-mode should

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 4dd439a93)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(graphviz shell-scripts conda systemd c-c++ dap lsp ruby nginx nixos clojure latex rust
          (elfeed :variables rmh-elfeed-org-files
                  (list "~/wiki/elfeed.org"))
          (exwm :variables exwm-enable-systray t exwm-autostart-xdg-applications nil exwm-workspace-number 8)
          csv yaml react typescript javascript html themes-megapack
          (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-format-on-save t python-sort-imports-on-save nil)
          helm
          (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
          pdf better-defaults latex emacs-lisp git ipython-notebook ess markdown syntax-checking
          (org :variables org-projectile-file "TODOs.org" org-enable-roam-support t org-enable-hugo-support t org-enable-roam-ui t org-enable-sticky-header t org-persp-start-with-default "a" org-enable-appear-support t org-src-tab-acts-natively nil)
          bibtex
          (shell :variables shell-default-term-shell "/run/current-system/sw/bin/fish" shell-default-height 30 shell-default-position 'bottom)
          spell-checking pass emacs-conflict)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XAW3D XDBE XIM XPM LUCID ZLIB

#### Backtrace :paw_prints:
```

```

**Comment by sunlin7** [comment] 2023-08-14 15:51
Maybe related to the https://github.com/syl20bnr/spacemacs/issues/15896

**Comment by smile13241324** [comment] 2023-08-15 06:41
Duplicate of the above mentioned ticket

**Comment by smile13241324** [comment] 2023-08-15 06:42
Please check the workarounds there or ugrade to emacs 29.1

**Closed as not planned** 2023-08-15 06:41 UTC

**Comment by nicolasshu** [comment] 2023-08-15 19:00
Upgrading to 29.1 does not work. I'll see if I can find a workaround, but currently, from the ones I've tried listed there do not work

**Comment by moritzschaefer** [comment] 2023-08-16 05:36
Upgrading to 29.0 worked for me but only when freeing my org mode code from the with-eval-after-load 'org block
