### ISSUE TITLE
`SPC a k` is broken, showing message `selecting deleted buffer` in the minibuffer

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#7963] opened 2016-12-14 06:00 UTC
#### Description :octocat:
`SPC a k` is broken, showing message `selecting deleted buffer` in the minibuffer

#### Reproduction guide :beetle:

- **Updated:** Make sure your `dotspacemacs/emacs-custom-settings` is _**not**_ the same as settings in file `.cache/.custom-settings`. You can delete the whole `(defun dotspacemacs/emacs-custom-settings ...)` or just delete the code block wrapped by `custom-set-variables`
- Start Emacs
- `SPC a k` to run `spacemacs/paradox-list-packages`

*Observed behaviour:* :eyes: :broken_heart:
Packages list buffer is not shown as expected, instead, a message `selecting deleted buffer` echoes in the minibuffer.

*Expected behaviour:* :heart: :smile:
`SPC a k` gives ELPA package list

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: nil (rev. afa2226)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :disabled-for org)
 better-defaults c-c++ emacs-lisp evil-snipe games git github latex bibtex markdown
 (org :variables org-projectile-file "TODOs.org" org-enable-reveal-js-support t org-reveal-js "file:///home/neoarch/git/reveal")
 org-config
 (han :variables han-enable-youdao-dict t han-enable-fcitx t han-org-line-spacing 0.2)
 html pandoc pdf-tools python pfc-fish
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking syntax-checking version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by et2010** [comment] 2016-12-14 06:02
Note that this issue will not reproduce with Emacs 24.5.1

**Comment by d12frosted** [comment] 2016-12-14 18:33
This works for me nice. I have the same version of Emacs as you do. Could you please try updating your packages?

**Comment by et2010** [comment] 2016-12-16 02:09
I think I got the same issue as @ksjogo described in #5170

**Comment by et2010** [comment] 2016-12-16 02:12
I tried updating my packages but the issue persists. @d12frosted

**Comment by et2010** [comment] 2016-12-16 04:26
I've updated the repro guide.

**Comment by et2010** [comment] 2016-12-16 06:48
Eval `(spacemacs/write-custom-settings-to-dotfile)` after emacs started manually or add the sexp to `dotspacemacs/user-config` could fix this type of issues.

**Comment by d12frosted** [comment] 2016-12-16 07:53
Indeed, looks like #7898. Closing this issue in favour of #7898.

**Comment by syl20bnr** [comment] 2016-12-18 03:12
I cannot reproduce it, even with the updated repro step. I have the same Emacs version. I'm starting to believe that something in @et2010 and @ksjogo dotfile is responsible for this, now what ? :-)

**Comment by syl20bnr** [comment] 2016-12-18 03:12
I reopen it even if is a duplicate as the repo steps are different.

**Comment by syl20bnr** [comment] 2016-12-18 07:11
Should be fixed now, more info here: https://github.com/syl20bnr/spacemacs/issues/7898#issuecomment-267807191

**Closed by syl20bnr** 2016-12-18 07:11 UTC
Labels: - Bug tracker -, Core, Customize, Duplicate ☝, High Priority, To be reproduced

**Comment by et2010** [comment] 2016-12-18 13:38
Thanks for fixing. It works like a charm.
