### ISSUE TITLE
spacemacs/jump-in-buffer is not longer available, but still used in Helm layer

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#7089] opened 2016-09-11 10:33 UTC
#### Description :octocat:
Command bound to `C-c s j` is not updated.

#### Reproduction guide :beetle:
- Start Emacs
- Press `C-c s j`.

*Observed behaviour:* :eyes: :broken_heart:
- Error occurs:

`command-execute: Wrong type argument: commandp, spacemacs/jump-in-buffer`

The reason for this is that the new command is the command name is changed to
`spacemacs/helm-jump-in-buffer`, but haven't updated yet in Helm layer for its key binding.

*Expected behaviour:* :heart: :smile:
Display the list of tags in buffer for jumping to.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: nil (rev. 6efcef1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(asm auto-completion
     (git :variables git-use-magit-next t git-enable-github-support t)
     nil
     (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
     latex dash better-defaults syntax-checking emacs-lisp semantic tuhdo
     (c-c++ :variables c-c++-enable-clang-support t)
     gtags eyebrowse
     (colors :variables colors-enable-nyan-cat-progress-bar t)
     themes-megapack common-lisp ruby csharp xwidget org lua finance)
```

**Comment by bmag** [comment] 2016-09-11 10:48
Fixed 4 days ago by https://github.com/syl20bnr/spacemacs/commit/d5baec4b44270e52406a6b646b4a9b08fce2d64f, is your branch up-to-date?

**Comment by TheBB** [comment] 2016-09-11 12:01
Duplicate of https://github.com/syl20bnr/spacemacs/issues/6929, which by the way is also fixed.

`C-c s j` must be your own binding. Spacemacs doesn't set it.

**Closed by TheBB** 2016-09-11 12:01 UTC

**Comment by tuhdo** [comment] 2016-09-11 12:47
Ok my branch was outdated. Update and that fixed it. 

> C-c s j must be your own binding. Spacemacs doesn't set it.

No, it's Spacemacs's binding. I use `C-c` as my leader key.

**Comment by TheBB** [comment] 2016-09-11 13:09
Would be helpful if you mentioned that, then.
