### ISSUE TITLE
Multicursors and `fd`

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#14765] opened 2021-05-11 07:09 UTC
Typing `fd` gets you out of whatever mode you are in. This is nice if you work in the terminal and there is a delay when typing `[ESC]`. When having multiple cursors, this does not work as intended, you actually get out of insert mode but on all secondary cursors "fd" is being inserted. Where do I start looking to fix this?

**Comment by lebensterben** [comment] 2021-05-11 07:20
https://develop.spacemacs.org/doc/DOCUMENTATION.html#escaping

**Comment by lebensterben** [comment] 2021-05-11 07:23
> According to Lewand, arranged from most to least common in appearance, the letters are: etaoinshrdlcumwfgypbvkjxqz

xz is a good choice

**Comment by gdkrmr** [comment] 2021-05-11 07:48
the issue is not the choice of "fd" the issue is that if I use multiple cursors in insert mode and press "fd", the letters fd get inserted into the document at the secondary cursors.

**Comment by lebensterben** [comment] 2021-05-11 08:20
Do you use evil-mc or multiple-cursor?
How to reproduce this?

**Comment by lebensterben** [comment] 2021-05-11 20:35
Not reproducible
After following the first three steps, I tried to press `C-n` but it's bounded to `evil-paste-pop-next`.

**Comment by lebensterben** [comment] 2021-05-11 21:03
Try
```elisp
(setq evil-escape-inhibit-functions '((lambda () evil-mc-cursor-state)))
```

**Comment by gdkrmr** [comment] 2021-05-12 07:46
If you use the `multiple-cursors` layer, then `C-n` should be bound to `evil-mc-make-and-goto-next-match` [1]. `evil-paste-pop-next` should be bound to `C-k` [2].

[1] https://github.com/syl20bnr/spacemacs/blob/bc51b6a5eab58883ad51fcdd12c8cdfbdb74170d/layers/%2Bmisc/multiple-cursors/README.org#L80
[2] https://github.com/syl20bnr/spacemacs/blob/95280d15a8612b1edd519d1f0e9472cfd8fa7e27/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L235

**Comment by lebensterben** [comment] 2021-05-12 13:42
> If you use the `multiple-cursors` layer, then `C-n` should be bound to `evil-mc-make-and-goto-next-match` [1]. `evil-paste-pop-next` should be bound to `C-k` [2].
> 
> [1]
> 
> https://github.com/syl20bnr/spacemacs/blob/bc51b6a5eab58883ad51fcdd12c8cdfbdb74170d/layers/%2Bmisc/multiple-cursors/README.org#L80
> 
> 
> [2]
> https://github.com/syl20bnr/spacemacs/blob/95280d15a8612b1edd519d1f0e9472cfd8fa7e27/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L235

it was shadowed by another package. dear my new reply

**Comment by gdkrmr** [comment] 2021-06-04 07:44
This is actually a known problem https://github.com/gabesoft/evil-mc/issues/41 and people tried to fix it https://github.com/syl20bnr/spacemacs/pull/12159

**Comment by lebensterben** [comment] 2021-06-04 12:13
> Try
> 
> ```elisp
> 
> (setq evil-escape-inhibit-functions '((lambda () evil-mc-cursor-state)))
> 
> ```

@gdkrmr 

Does this fix it?

**Comment by gdkrmr** [comment] 2021-06-07 10:55
This disables `evil-escape` when having multiple cursors, right? It works, but is not what I want.

**Comment by lebensterben** [comment] 2021-06-07 13:48
you haven't tried it.
Evil-escape is still working

**Comment by lebensterben** [comment] 2021-06-07 14:25
to be clear, this is not a bug of Spacemacs,
and a workaround is provided.
so I'm closing this.

**Closed by lebensterben** 2021-06-07 14:25 UTC
Labels: Evil-escape, Multiple cursors, Not a bug 8-)

**Comment by gdkrmr** [comment] 2021-06-09 06:05
> to be clear, this is not a bug of Spacemacs,

agreed

> and a workaround is provided.

the workaround doesn't work for me. `fd` is supposed to switch out of insert mode with multiple cursors, the workaround disables `evil-escape` instead.
