### ISSUE TITLE
evil-avy-goto-char-timer freezes auto-highlight-symbol-mode

### ISSUE THREAD

**Issue by Technologicat** [syl20bnr/spacemacs#12620] opened 2019-08-14 06:35 UTC
#### Description :octocat:

Using `evil-avy-goto-char-timer` freezes `auto-highlight-symbol-mode`.

#### Reproduction guide :beetle:
- Start Emacs
- Open an existing file: text, program source code, whatever
- If AHS is not enabled, `M-x auto-highlight-symbol-mode` to enable it
- Place point on a word, observe AHS highlights all visible occurrences of it
- `M-m j j` to invoke `evil-avy-goto-char-timer`
- Enter a fragment of **some other word**, to have avy jump the point to it

*Observed behaviour:* :eyes: :broken_heart:

The AHS highlight remains frozen at the word that was highlighted when `evil-avy-goto-char-timer` was invoked. The highlight no longer updates when point is moved to a different word.

Toggling AHS off and back on again restores the highlight into a working state.

*Expected behaviour:* :heart: :smile:

AHS highlight remains working even after using `evil-avy-goto-char-timer`.

*Notes:*

Possibly related to #3475.

*Workaround:*

Add this snippet to your `dotspacemacs/user-config` function:

```elisp
  (defadvice evil-avy-goto-char-timer (before my-avy-disable-ahs last activate)
    (setq my-had-ahs auto-highlight-symbol-mode)
    (when my-had-ahs
      (auto-highlight-symbol-mode 0)))
  (defadvice evil-avy-goto-char-timer (after my-avy-reenable-ahs first activate)
    (when my-had-ahs
      (auto-highlight-symbol-mode 1)))
```

This will temporarily disable AHS while `evil-avy-goto-char-timer` runs, and if it was originally enabled, re-enable it afterwards. The solution is obviously not thread-safe, but that's likely not a concern in EMACS UI code anyway. :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9637ceb38)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(javascript html csv yaml graphviz racket python julia c-c++ cscope helm
            (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
            emacs-lisp multiple-cursors treemacs git latex markdown
            (shell :variables shell-default-width 40 shell-default-position 'right)
            spell-checking syntax-checking themes-megapack pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Technologicat** [comment] 2019-08-14 06:43
Ah, right, forgot to mention, this happens at least in `python-mode`.

If needed, my complete spacemacs.d is [here](https://github.com/Technologicat/spacemacs.d), but `init.el` is getting a bit long, and most of it is probably not relevant to the issue.

(Opening a new issue, as #3475 was reported in 2015, so things may have changed in the meantime.)

**Comment by duianto** [comment] 2019-08-14 11:16
Confirmed, the highlight stays at it's previous location and stops updating after calling at least some avy commands.

`M-x auto-highlight-symbol-mode RET` doesn't start highlighting words for me, but as described in issue #3475 `SPC t h a` which calls `(spacemacs/toggle-automatic-symbol-highlight)` works.

**Comment by duianto** [comment] 2021-09-15 12:16
I'm unable to reproduce this issue.

The symbol highlighting does not freeze after calling an avy command.
Tested in the scratch buffer, `.spacemacs` and a `.py` file.

It might have been fixed upstream,
or as a side effect of the recent (jul, aug 2021),
symbol highlighting related Spacemacs commits:
https://github.com/syl20bnr/spacemacs/commits/develop/layers/%2Bspacemacs/spacemacs-navigation

<details>
<summary>System Info</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 663cfc5ba)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey helm emacs-lisp git html javascript markdown multiple-cursors
                 (org :variables org-enable-roam-support t)
                 pdf python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

@Technologicat If you're able to confirm that it isn't reoccurring, then you can close this.

**Closed** 2022-09-15 17:06 UTC
Labels: Fixed in develop
