### ISSUE TITLE
:depends keyword seems to break things during layer indexing

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#9175] opened 2017-07-02 06:38 UTC
#### Description :octocat:
It would seem that #9127 introduced a regression in layer indexing. I managed to get my system into a working state by deleting https://github.com/syl20bnr/spacemacs/commit/08561d8631153cee93c7348adb515aa217b5df7f -- so something is wonky...I saw an #9134 -- but I'm certain that is not the same issue -- or perhaps it is? I'm not entirely sure...

I also see #9136 -- not sure if this fixes the regression but this specific issue isn't precisely tracked down...just reporting anyways. 

#### Reproduction guide :beetle:
- Start Emacs
- Crashy 

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs shits the bed. 

*Expected behaviour:* :heart: :smile:
It should start up and work. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. c1a0a23)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(bibtex nginx twitter graphviz ivy asciidoc elfeed speed-reading swift plantuml
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
        better-defaults emacs-lisp
        (git :variables git-magit-status-fullscreen t)
        github gnus version-control
        (markdown :variables markdown-live-preview-engine 'vmd)
        syntax-checking
        (latex :variables latex-enable-auto-fill t)
        (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
        docker ansible puppet evil-commentary
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        fasd finance floobits xkcd autohotkey csv nlinum
        (c-c++ :variables c-c++-enable-clang-support t)
        (clojure :variables clojure-enable-fancify-symbols t)
        major-modes go
        (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
        html java
        (javascript :variables javascript-disable-tern-port-files t)
        (python :variables python-enable-yapf-format-on-save t python-fill-column 80 python-auto-set-local-pyenv-version 'on-visit python-auto-set-local-pyvenv-virtualenv 'on-visit python-sort-imports-on-save t python-test-runner
                '(nose pytest))
        racket
        (ruby :variables ruby-version-manager `rvm)
        ruby-on-rails
        (rust :variables rust-enable-rustfmt-on-save t)
        scala shell-scripts
        (restclient :variables restclient-use-org t)
        themes-megapack tmux vim-empty-lines spotify pandoc vagrant
        (ibuffer :variables ibuffer-group-buffers-by 'projects)
        semantic deft
        (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
        erc chrome d emoji gtags prodigy evernote
        (org :variables org-enable-github-support t org-enable-reveal-js-support t)
        search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger dash spell-checking jabber cscope vinegar rcirc games react php vimscript geolocation idris
        (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
        elixir
        (typography :variables typography-enable-typographic-editing nil)
        evil-cleverparens pdf-tools imenu-list slack systemd command-log
        (terraform :variables terraform-auto-format-on-save t)
        pass parinfer)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  eieio-oref(nil :disabled-for)
  (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (disabled (eieio-oref owner ':disabled-for)) (enabled (eieio-oref owner ':enabled-for))) (and (not (memq nil (mapcar (function (lambda (dep-pkg) (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer)))))) (eieio-oref pkg ':depends)))) (if (not (eq 'unspecified enabled)) (memq layer enabled) (not (memq layer disabled)))))
  configuration-layer//package-enabled-p(#<cfgl-package cfgl-package> python)
  (progn (configuration-layer//package-enabled-p pkg-obj layer))
  (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer)))
  (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer))))
  (lambda (dep-pkg) (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer)))))(helm)
  mapcar((lambda (dep-pkg) (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer))))) (helm))
  (memq nil (mapcar (function (lambda (dep-pkg) (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer)))))) (eieio-oref pkg ':depends)))
  (not (memq nil (mapcar (function (lambda (dep-pkg) (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer)))))) (eieio-oref pkg ':depends))))
  (and (not (memq nil (mapcar (function (lambda (dep-pkg) (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer)))))) (eieio-oref pkg ':depends)))) (if (not (eq 'unspecified enabled)) (memq layer enabled) (not (memq layer disabled))))
  (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (disabled (eieio-oref owner ':disabled-for)) (enabled (eieio-oref owner ':enabled-for))) (and (not (memq nil (mapcar (function (lambda (dep-pkg) (let ((pkg-obj (configuration-layer/get-package dep-pkg))) (if pkg-obj (progn (configuration-layer//package-enabled-p pkg-obj layer)))))) (eieio-oref pkg ':depends)))) (if (not (eq 'unspecified enabled)) (memq layer enabled) (not (memq layer disabled)))))
  configuration-layer//package-enabled-p(#<cfgl-package cfgl-package> python)
  (not (configuration-layer//package-enabled-p pkg layer))
  (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err)))))
  (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))
  (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err)))))))
  (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))))(python)
  mapc((lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err)))))))) (python c-c++))
  (let* ((pkg-name (eieio-oref pkg ':name)) (owner (car (eieio-oref pkg ':owners)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))))) (eieio-oref pkg ':pre-layers)) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored post-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> post-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/post-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while post-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))))) (eieio-oref pkg ':post-layers)))
  configuration-layer//configure-package(#<cfgl-package cfgl-package>)
  (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))
  (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabled-p pkg)) (spacemacs-buffer/message (format "%S is disabled." pkg-name))) (t (let ((dir (configuration-layer/get-location-directory pkg-name (eieio-oref pkg ':location) (car (eieio-oref pkg ':owners))))) (if dir (progn (add-to-list 'load-path dir)))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))
  (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabled-p pkg)) (spacemacs-buffer/message (format "%S is disabled." pkg-name))) (t (let ((dir (configuration-layer/get-location-directory pkg-name (eieio-oref pkg ':location) (car (eieio-oref pkg ':owners))))) (if dir (progn (add-to-list 'load-path dir)))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg))))))
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabled-p pkg)) (spacemacs-buffer/message (format "%S is disabled." pkg-name))) (t (let ((dir (configuration-layer/get-location-directory pkg-name (eieio-oref pkg ':location) (car (eieio-oref pkg ':owners))))) (if dir (progn (add-to-list 'load-path dir)))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabled-p pkg)) (spacemacs-buffer/message (format "%S is disabled." pkg-name))) (t (let ((dir (configuration-layer/get-location-directory pkg-name (eieio-oref pkg ':location) (car (eieio-oref pkg ':owners))))) (if dir (progn (add-to-list 'load-path dir)))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2((2048-game abbrev ac-ispell ace-link ace-window adaptive-wrap add-node-modules-path adoc-mode afternoon-theme aggressive-indent ahk-mode alchemist alect-themes alert ample-theme ample-zen-theme anaconda-mode ansi-colors ansible ansible-doc anti-zenburn-theme apropospriate-theme archive-mode arduino-mode auctex auctex-latexmk auto-compile auto-complete auto-dictionary auto-highlight-symbol auto-yasnippet avy badwolf-theme biblio biblio-core birds-of-paradise-plus-theme bookmark bracketed-paste browse-at-remote bubbleberry-theme bundler busybee-theme cargo cc-mode centered-buffer-mode centered-cursor cherry-blossom-theme chruby cider cider-eval-sexp-fu clang-format clean-aindent-mode clj-refactor clojure-mode clojure-snippets clues-theme cmake-mode cmm-mode coffee-mode color-identifiers-mode color-theme-sanityinc-solarized color-theme-sanityinc-tomorrow column-enforce-mode comint command-log-mode common-lisp-snippets company company-anaconda company-ansible company-auctex company-c-headers company-cabal company-dcd company-emacs-eclim company-emoji company-ghc company-ghci company-go company-lua company-php company-quickhelp company-restclient company-shell company-statistics company-tern company-web conf-mode counsel counsel-dash counsel-projectile css-mode csv-mode cyberpunk-theme cython-mode d-mode dactyl-mode dakrone-theme dante darkburn-theme darkmine-theme darkokai-theme darktooth-theme dash-at-point debug default-helm-config default-ivy-config default-org-config define-word deft desktop diff-hl diff-mode dired dired-x disaster django-theme doc-view docker docker-tramp dockerfile-mode dracula-theme drupal-mode dumb-jump ebuild-mode eclim edebug ediff edit-server editorconfig ein eldoc electric-indent-mode elfeed elfeed-goodies elfeed-org elfeed-web elisp-slime-nav elixir-mode elm-mode emacs-lisp emmet-mode emoji-cheat-sheet-plus emojify engine-mode enh-ruby-mode ensime erc erc-gitter erc-hl-nicks erc-image erc-sasl erc-social-graph erc-tex erc-view-log erc-yank erc-yt esh-help eshell eshell-prompt-extras eshell-z espresso-theme eval-sexp-fu evil-anzu evil-args evil-cleverparens evil-commentary evil-ediff evil-escape evil-exchange evil-iedit-state evil-indent-plus evil-lion evil-lisp-state evil-magit evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-org evil-search-highlight-persist evil-snipe evil-surround evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar expand-region eyebrowse fancy-battery farmhouse-theme fasd feature-mode fill-column-indicator firebelly-theme fish-mode flatland-theme flatui-theme floobits flx flx-ido flycheck flycheck-bashate flycheck-credo flycheck-dmd-dub flycheck-eclim flycheck-elm flycheck-gometalinter flycheck-haskell flycheck-ledger flycheck-mix flycheck-nim flycheck-pos-tip flycheck-rust flymd flyspell flyspell-correct flyspell-correct-helm flyspell-correct-ivy flyspell-correct-popup flyspell-popup fuzzy gandalf-theme gdb-mi geeknote geiser ggtags gh-md ghc gist git-commit git-gutter git-gutter+ git-gutter-fringe git-gutter-fringe+ git-link git-messenger git-timemachine gitattributes-mode gitconfig-mode github-clone github-search gitignore-mode gmail-message-mode gnuplot gnus go-eldoc go-guru go-mode go-rename godoctor golden-ratio google-translate gotham-theme gradle-mode grandshell-theme graphviz-dot-mode groovy-imports groovy-mode gruber-darker-theme gruvbox-theme haml-mode haskell-mode haskell-snippets hc-zenburn-theme helm-bibtex helm-c-yasnippet helm-company helm-cscope helm-css-scss helm-dash helm-flycheck helm-games helm-gitignore helm-gtags helm-hoogle helm-make helm-purpose helm-pydoc helm-rcirc helm-spotify help-fns+ hemisu-theme heroku-theme hexl hi-lock hide-comnt highlight-indentation highlight-numbers highlight-parentheses hindent hippie-exp hl-anything hl-todo hlint-refactor hoon-mode hs-minor-mode htmlize hungry-delete hy-mode ibuffer ibuffer-projectile ido ido-vertical-mode idris-mode ielm image-mode imenu imenu-list impatient-mode indent-guide info+ inkpot-theme insert-shebang intero ir-black-theme ivy ivy-hydra ivy-purpose ivy-spacemacs-help jabber java-mode jazz-theme jbeans-theme jinja2-mode js-doc js2-mode js2-refactor json-mode json-snatcher julia-mode kivy-mode ledger-mode less-css-mode light-soap-theme link-hint linum linum-relative live-py-mode livid-mode logcat lorem-ipsum lua-mode lush-theme macrostep madhat2r-theme magic-latex-buffer magit magit-gh-pulls magit-gitflow magithub majapahit-theme marcopolo markdown-mode markdown-toc material-theme matlab-mode meghanada minimal-theme minitest mmm-mode moe-theme molokai-theme monochrome-theme monokai-theme move-text multi-term mustang-theme mwim naquadah-theme neotree nginx-mode niflheim-theme nim-mode nlinum nlinum-relative noctilux-theme noflet nose nvm nyan-mode ob ob-elixir ob-http ob-ipython ob-restclient ob-sml obsidian-theme occidental-theme occur-mode oldlace-theme omtose-phellack-theme open-junk-file org org-agenda org-brain org-bullets org-download org-expiry org-journal org-mime org-pomodoro org-present org-projectile org-ref organic-green-theme orgit origami osx-location ox-gfm ox-pandoc ox-reveal ox-twbs package-menu pacmacs page-break-lines pandoc-mode paradox parinfer password-generator password-store pastels-on-dark-theme pcre2el pdf-tools persp-mode phoenix-dark-mono-theme phoenix-dark-pink-theme php-auto-yasnippets php-extras php-mode phpcbf phpunit pip-requirements pkgbuild-mode planet-theme plantuml-mode popup popwin process-menu prodigy professional-theme projectile projectile-rails psc-ide psci pug-mode puppet-mode purescript-mode purple-haze-theme py-isort pyenv-mode pylookup pytest python pyvenv qml-mode racer racket-mode railscasts-theme rainbow-delimiters rainbow-identifiers rainbow-mode rake ranger rase rbenv rcirc rcirc-color rcirc-notify realgud rebecca-theme recentf reftex request restart-emacs restclient restclient-helm reverse-theme robe rspec-mode rubocop ruby-mode ruby-refactor ruby-test-mode ruby-tools rust-mode rvm sass-mode savehist saveplace sayid sbt-mode scad-mode scala-mode scss-mode semantic seti-theme sh-script shell shell-pop skewer-mode slack slim-mode slime slime-company smali-mode smartparens smeargle smerge-mode smex sml-mode smooth-scrolling smyx-theme soft-charcoal-theme soft-morning-theme soft-stone-theme solarized-theme soothe-theme space-doc spacegray-theme spaceline spacemacs-github spacemacs-purpose-popwin spacemacs-theme spacemacs-whitespace-cleanup spotify spray sql sql-indent sqlup-mode srefactor stan-mode stickyfunc-enhance string-inflection subatomic-theme subatomic256-theme sublime-themes subword sudoku sunny-day-theme sunshine swift-mode swiper symon systemd tagedit tango-2-theme tango-plus-theme tangotango-theme tao-theme tar-mode term tern terraform-mode tetris theme-changer thrift tildify tmux toc-org toml-mode toxi-theme tronesque-theme twilight-anti-bright-theme twilight-bright-theme twilight-theme twittering-mode typit typo ujelly-theme underwater-theme undo-tree unfill uniquify url uuidgen vagrant vagrant-tramp vala-mode vala-snippets vi-tilde-fringe vim-empty-lines-mode vimrc-mode visual-line-mode vmd-mode volatile-highlights web-beautify web-mode wgrep white-sand-theme whitespace window-purpose winner winum wolfram-mode ws-butler xcscope xkcd xterm-color yaml-mode yapfify yasnippet zeal-at-point zen-and-art-theme zenburn-theme zone zonokai-theme zoom-frm))
  configuration-layer//configure-packages((2048-game abbrev ac-ispell ace-link ace-window adaptive-wrap add-node-modules-path adoc-mode afternoon-theme aggressive-indent ahk-mode alchemist alect-themes alert ample-theme ample-zen-theme anaconda-mode ansi-colors ansible ansible-doc anti-zenburn-theme apropospriate-theme archive-mode arduino-mode async auctex auctex-latexmk auto-compile auto-complete auto-dictionary auto-highlight-symbol auto-yasnippet avy badwolf-theme biblio biblio-core bind-key bind-map birds-of-paradise-plus-theme bookmark bracketed-paste browse-at-remote bubbleberry-theme bundler busybee-theme cargo cc-mode centered-buffer-mode centered-cursor cherry-blossom-theme chruby cider cider-eval-sexp-fu clang-format clean-aindent-mode clj-refactor clojure-mode clojure-snippets clues-theme cmake-mode cmm-mode coffee-mode color-identifiers-mode color-theme-sanityinc-solarized color-theme-sanityinc-tomorrow column-enforce-mode comint command-log-mode common-lisp-snippets company company-anaconda company-ansible company-auctex company-c-headers company-cabal company-dcd company-emacs-eclim company-emoji company-ghc company-ghci company-go company-lua company-php company-quickhelp company-restclient company-shell company-statistics company-tern company-web conf-mode counsel counsel-dash counsel-projectile css-mode csv-mode cyberpunk-theme cython-mode d-mode dactyl-mode dakrone-theme dante darkburn-theme darkmine-theme darkokai-theme darktooth-theme dash-at-point debug default-helm-config default-ivy-config default-org-config define-word deft desktop diff-hl diff-mode diminish dired dired-x disaster django-theme doc-view docker docker-tramp dockerfile-mode dracula-theme drupal-mode dumb-jump ebuild-mode eclim edebug ediff edit-server editorconfig ein eldoc electric-indent-mode elfeed elfeed-goodies elfeed-org elfeed-web elisp-slime-nav elixir-mode elm-mode emacs-lisp emmet-mode emoji-cheat-sheet-plus emojify engine-mode enh-ruby-mode ensime erc erc-gitter erc-hl-nicks erc-image erc-sasl erc-social-graph erc-tex erc-view-log erc-yank erc-yt esh-help eshell eshell-prompt-extras eshell-z espresso-theme eval-sexp-fu evil evil-anzu evil-args evil-cleverparens evil-commentary evil-ediff evil-escape evil-evilified-state evil-exchange evil-iedit-state evil-indent-plus evil-lion evil-lisp-state evil-magit evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-org evil-search-highlight-persist evil-snipe evil-surround evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar exec-path-from-shell expand-region eyebrowse fancy-battery farmhouse-theme fasd feature-mode fill-column-indicator firebelly-theme fish-mode flatland-theme flatui-theme floobits flx flx-ido flycheck flycheck-bashate flycheck-credo flycheck-dmd-dub flycheck-eclim flycheck-elm flycheck-gometalinter flycheck-haskell flycheck-ledger flycheck-mix flycheck-nim flycheck-pos-tip flycheck-rust flymd flyspell flyspell-correct flyspell-correct-helm flyspell-correct-ivy flyspell-correct-popup flyspell-popup fuzzy gandalf-theme gdb-mi geeknote geiser ggtags gh-md ghc gist git-commit git-gutter git-gutter+ git-gutter-fringe git-gutter-fringe+ git-link git-messenger git-timemachine gitattributes-mode gitconfig-mode github-clone github-search gitignore-mode gmail-message-mode gnuplot gnus go-eldoc go-guru go-mode go-rename godoctor golden-ratio google-translate gotham-theme gradle-mode grandshell-theme graphviz-dot-mode groovy-imports groovy-mode gruber-darker-theme gruvbox-theme haml-mode haskell-mode haskell-snippets hc-zenburn-theme helm-bibtex helm-c-yasnippet helm-company helm-cscope helm-css-scss helm-dash helm-flycheck helm-games helm-gitignore helm-gtags helm-hoogle helm-make helm-purpose helm-pydoc helm-rcirc helm-spotify help-fns+ hemisu-theme heroku-theme hexl hi-lock hide-comnt highlight-indentation highlight-numbers highlight-parentheses hindent hippie-exp hl-anything hl-todo hlint-refactor holy-mode hoon-mode hs-minor-mode htmlize hungry-delete hy-mode hybrid-mode hydra ibuffer ibuffer-projectile ido ido-vertical-mode idris-mode ielm image-mode imenu imenu-list impatient-mode indent-guide info+ inkpot-theme insert-shebang intero ir-black-theme ivy ivy-hydra ivy-purpose ivy-spacemacs-help jabber java-mode jazz-theme jbeans-theme jinja2-mode js-doc js2-mode js2-refactor json-mode json-snatcher julia-mode kivy-mode ledger-mode less-css-mode light-soap-theme link-hint linum linum-relative live-py-mode livid-mode logcat lorem-ipsum lua-mode lush-theme macrostep madhat2r-theme magic-latex-buffer magit magit-gh-pulls magit-gitflow magithub majapahit-theme marcopolo markdown-mode markdown-toc material-theme matlab-mode meghanada minimal-theme minitest mmm-mode moe-theme molokai-theme monochrome-theme monokai-theme move-text multi-term mustang-theme mwim naquadah-theme neotree nginx-mode niflheim-theme nim-mode nlinum nlinum-relative noctilux-theme noflet nose nvm nyan-mode ob ob-elixir ob-http ob-ipython ob-restclient ob-sml obsidian-theme occidental-theme occur-mode oldlace-theme omtose-phellack-theme open-junk-file org org-agenda org-brain org-bullets org-download org-expiry org-journal org-mime org-plus-contrib org-pomodoro org-present org-projectile org-ref organic-green-theme orgit origami osx-location ox-gfm ox-pandoc ox-reveal ox-twbs package-menu pacmacs page-break-lines pandoc-mode paradox parinfer password-generator password-store pastels-on-dark-theme pcre2el pdf-tools persp-mode phoenix-dark-mono-theme phoenix-dark-pink-theme php-auto-yasnippets php-extras php-mode phpcbf phpunit pip-requirements pkgbuild-mode planet-theme plantuml-mode popup popwin process-menu prodigy professional-theme projectile projectile-rails psc-ide psci pug-mode puppet-mode purescript-mode purple-haze-theme py-isort pyenv-mode pylookup pytest python pyvenv qml-mode racer racket-mode railscasts-theme rainbow-delimiters rainbow-identifiers rainbow-mode rake ranger rase rbenv rcirc rcirc-color rcirc-notify realgud rebecca-theme recentf reftex request restart-emacs restclient restclient-helm reverse-theme robe rspec-mode rubocop ruby-mode ruby-refactor ruby-test-mode ruby-tools rust-mode rvm sass-mode savehist saveplace sayid sbt-mode scad-mode scala-mode scss-mode semantic seti-theme sh-script shell shell-pop skewer-mode slack slim-mode slime slime-company smali-mode smartparens smeargle smerge-mode smex sml-mode smooth-scrolling smyx-theme soft-charcoal-theme soft-morning-theme soft-stone-theme solarized-theme soothe-theme space-doc spacegray-theme spaceline spacemacs-github spacemacs-purpose-popwin spacemacs-theme spacemacs-whitespace-cleanup spotify spray sql sql-indent sqlup-mode srefactor stan-mode stickyfunc-enhance string-inflection subatomic-theme subatomic256-theme sublime-themes subword sudoku sunny-day-theme sunshine swift-mode swiper symon systemd tagedit tango-2-theme tango-plus-theme tangotango-theme tao-theme tar-mode term tern terraform-mode tetris theme-changer thrift tildify tmux toc-org toml-mode toxi-theme tronesque-theme twilight-anti-bright-theme twilight-bright-theme twilight-theme twittering-mode typit typo ujelly-theme underwater-theme undo-tree unfill uniquify url use-package uuidgen vagrant vagrant-tramp vala-mode vala-snippets vi-tilde-fringe vim-empty-lines-mode vimrc-mode visual-line-mode vmd-mode volatile-highlights web-beautify web-mode wgrep which-key white-sand-theme whitespace window-purpose winner winum wolfram-mode ws-butler xcscope xkcd xterm-color yaml-mode yapfify yasnippet zeal-at-point zen-and-art-theme zenburn-theme zone zonokai-theme zoom-frm))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require 'core-spacemacs) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require 'server) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/rob/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/home/rob/.emacs.d/init.el" "/home/rob/.emacs.d/init.el" t t)
  load("/home/rob/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode>)()
  command-line()
  normal-top-level()
```

**Comment by robbyoconnor** [comment] 2017-07-02 07:20
#9136 fixes this.

**Comment by TheBB** [comment] 2017-07-02 08:12
Duplicate of https://github.com/syl20bnr/spacemacs/issues/9142, we are discussing this and related issues in https://github.com/syl20bnr/spacemacs/issues/9134

**Comment by TheBB** [comment] 2017-07-02 08:13
Thanks for checking though!

**Closed by TheBB** 2017-07-02 08:13 UTC

**Comment by robbyoconnor** [comment] 2017-07-02 08:21
Oh jesus -- I guess I missed #9142 -- how?!

**Comment by TheBB** [comment] 2017-07-02 08:22
Probably because I closed it earlier. Not so easy to find. :-P

**Comment by robbyoconnor** [comment] 2017-07-02 09:09
Yeah, I don't search old discussions...
