### ISSUE TITLE
Haskell: problems with 'mht' and 'mhi'

### ISSUE THREAD

**Issue by ilyagr** [syl20bnr/spacemacs#4770] opened 2016-01-23 23:05 UTC
I think that the resolution of PR #3197 in commit b27d6bd94e83e93b23c92c0b9ce19a387fdd8bd2 is causing problems on my system. After a fresh install (no haskell-specific configuration in .spacemacs) and opening a .hs file, both `<SPC> mht` and `<SPC> mhi` are bound to the function `haskell-mode-enable-process-minor-mode`, which simply prints a (rather unhelpful) error message.

It seems that for the keybindings to work, one must enable the "process-minor-mode" in such a way that it happens before the keybinding of `<SPC> mht` happens. I'm not sufficiently versed in (space)macs to know how to do it in my .spacemacs, exactly. Also, it seems that if I ever changed the "process-minor-mode", the keybindings would not get updated as they should.

**Comment by d12frosted** [comment] 2016-01-24 11:20
Please, share you configuration for haskell layer. If you are using `ghci-ng` or not using `ghc-mod` then it makes sense. In order to use `mhi` or `mht` you need an associated interactive session.

**Comment by ilyagr** [comment] 2016-01-24 17:05
I do not have any Haskell-specific config for spacemacs, beyond adding the Haskell layer. I have stack and latest ghc-mod in my path, no ghci-ng.

The main problem is that creating an interactive session does not rebind 'mht' to a useful function, it keeps just printing the same error message. A workaround would be to setup ghc-mod or an interactive session before the lines in the linked commit are executed, but I'm not sure what the proper way to do that is.

**Comment by nebtrx** [comment] 2016-01-25 02:16
I'm having the same issue. So far now I've found a workaround but it's kind of annoying: After open a hs buffer resync dotspacemacs config (M-m fe R) and that's it, all comes back to normal.

I'm using ghc-mod and this is my spacemacs haskell related config:

...
 (haskell :variables
              ;;haskell-enable-hindent-style "chris-done"

              haskell-enable-ghci-ng-support nil
              ;;haskell-process-type 'ghci
              haskell-enable-shm-support t)

...
...
(defun dotspacemacs/user-config ()
  (spacemacs/set-leader-keys-for-major-mode 'haskell-mode "mht"  'ghc-show-type)

  ;; always delete trailing space automatically on save
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
  ;; automatic file reloading if it changes externally
  (global-auto-revert-mode t)
  (add-hook 'haskell-mode-hook 'haskell-indent-mode)
  (add-hook 'haskell-mode-hook 'interactive-haskell-mode)
...

**Comment by ilyagr** [comment] 2016-01-25 02:55
My workaround just forces the use of `ghc-mod`: in `dotspacemacs/user-config`, I have:

```
  (spacemacs/set-leader-keys-for-major-mode 'haskell-mode
    "ht"  'ghc-show-type
    "hi"  'ghc-show-info)
```

It is important (and may help @nebtrx) to have "ht" and "hi" there instead of "mht" or "mhi". The "m" is assumed, so writing "mht" makes the actual key combination be `<SPC> m m h t`.

**Comment by nebtrx** [comment] 2016-01-25 03:17
Thanks @ilyagr, I tried what you suggest but the problem persist.  It sends me to Run C - h f 'haskell-mode'. Thanks for the heads up on the leader keys,  it turned confusing to me as new emac user, but it totally make sense as "m" is leader key  for major mode option :+1:

**Comment by ilyagr** [comment] 2016-01-25 05:19
@nebtrx You are right: this expression works when evaluated, but not if it's just in .spacemacs.

Try changing "ht" to "et" (or something else that's not already bound). Then, it works for me.

**Comment by nebtrx** [comment] 2016-01-25 05:31
@ilyagr dude, grab a beer on me. Thx it worked!

**Comment by d12frosted** [comment] 2016-01-25 05:47
Interesting. Thanks for all details. I'll try to find the problem and fix it.

```
(spacemacs/set-leader-keys-for-major-mode 'haskell-mode
    "ht"  'ghc-show-type
    "hi"  'ghc-show-info)
```

This isn't working because key bindings from haskell layer are lazily evaluated on visiting file (actually on running `haskell-mode`). So this needs to be set in `haskell-mode-hook`, otherwise your settings are overridden.

**Comment by d12frosted** [comment] 2016-01-29 07:22
Tried to reproduce but with no luck. Are you sure that you didn't miss anything in your setup? For example, since you are using `stack` and `ghc-mod` you should make sure that there is no `dist` folder in your project's root.

**Comment by nebtrx** [comment] 2016-01-29 15:24
Not in my case..no `dist` directory in all the project

**Comment by d12frosted** [comment] 2016-01-29 15:30
@nebtrx ok, you just have some configurations that break `ghc-mod` integration.

```
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
```

Enabling `interactive-haskell-mode` also rebinds `, h t` and `, h i`. In case you want to have `interactive-haskell-mode` - you have to manually bind `, h t` and `,h i` to whatever you want. 

Also, `(add-hook 'haskell-mode-hook 'haskell-indent-mode)` is redundant since it's enabled by default. 

So, @nebtrx your situation is slightly different, since you have some additional configurations for haskell-layer. 

As for clean setup - I couldn't reproduce this problem. :(

**Comment by nebtrx** [comment] 2016-01-29 15:31
ok, fixing that, thanks @d12frosted

**Comment by d12frosted** [comment] 2016-04-06 16:11
@ilyagr Do you still have problem with these bindings? If no, please close this issue :) 

@StreakyCobra, please place waiting for response label :)

**Comment by d12frosted** [comment] 2016-10-03 09:12
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 09:12 UTC
Labels: Fixed in develop, Haskell, Question

**Comment by kindlychung** [comment] 2016-12-26 20:44
I have got the same problem with the latest version of spacemacs. My config is here:
https://gist.github.com/kindlychung/34f1766655dcc7a1aa444aa6a604a405
Nothing complex, I just added osx and haskell layers.
Whenever I try SPC m h t, I got the error "No session associated with this buffer, try m-x haskell-session-change or report this bug". If I exec haskell-session-change, I got "the haskell process has died, restart? (y, n, l)", and if I press y or n, it's a dead loop. 

Any suggestions?

**Comment by kindlychung** [comment] 2016-12-27 15:28
Never mind. I have found the workaround. Just add this line under `dotspacemacs/user-config` in the `.spacemacs` file:

    (setq haskell-process-args-stack-ghci '("--ghci-options=-ferror-spans"))

Will this be fixed in the next release?

**Comment by d12frosted** [comment] 2016-12-27 20:14
@kindlychung 

> No session associated with this buffer, try m-x haskell-session-change or report this bug

It says what it needs - [a session associated with this buffer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/haskell#haskell-mode-commands-dont-work). So just `, s b` to start interactive session and load current buffer.

**Comment by d12frosted** [comment] 2016-12-29 10:43
This is an upstream issue that should be reported to `haskell-mode`.
