### ISSUE TITLE
guide-key: Polling behavior kills kittens

### ISSUE THREAD

**Issue by bgamari** [syl20bnr/spacemacs#1263] opened 2015-04-19 17:37 UTC
Recently I noticed that each of the dozen-or-so emacs processes running on my laptop were waking up 10 times a second, severely impacting my laptop's battery life. `helm-timers` revealed that the culprit is `guide-key/polling-function`. I haven't get investigated whether this is due to spacemacs' configuration or inherent to the package but surely there is a better way to accomplish the goal of this timer than polling at 10 Hz.

**Comment by bgamari** [comment] 2015-04-19 17:41
I've also opened a bug against [guide-key](https://github.com/kai2nenobu/guide-key/issues/39)

**Comment by trishume** [comment] 2015-04-19 17:58
Oh god, that's blech.

**Comment by syl20bnr** [comment] 2015-04-19 18:15
I noticed this timer since the addition of guide-key but did not see an impact on my MacBook Air. I remember finding it silly too and I watched a bit how I could fix it but did not find something that works.

I have the plan to make a custom guide-key for Spacemacs if guide-key does not allow to handle major-mode specific key bindings. I would also like to be able to put a short description for each binding (huge work but I don't fear this :-)).

**Comment by trishume** [comment] 2015-04-19 21:56
@syl20bnr or just fork guide-key and start from there. Or start from scratch but copy-past liberally.

**Comment by syl20bnr** [comment] 2015-04-19 22:42
I was more for the second option and code just what we need for Spacemacs.

**Comment by bgamari** [comment] 2015-08-10 11:33
@syl20bnr is there a reasonably straightforward way to disable `guide-key` until this is resolved? The problem may not be visible with a single emacs session but the duration the processor can remain in a low-power states scales non-linearly with the number of wake requests due to transition latency. I tend to have several emacs sessions open at once so the effect is quite pronounced.

One approach to reduce the effect of these wake-ups is to ensure the timers fire at the same time that other timers fire (typically on the second). This is the reason why `glib` provides its [`timeout_add_seconds`](https://developer.gnome.org/pygobject/stable/glib-functions.html#function-glib--timeout-add-seconds) function, for instance.

**Comment by TheBB** [comment] 2015-08-10 11:40
Guide-key has been removed in the develop branch, and is replaced by which-key in the upcoming release. Presumably this issue will be fixed and closed then. You may consider moving to develop or excluding `guide-key` by adding it to the list `dotspacemacs-excluded-packages`.

**Comment by bgamari** [comment] 2015-08-10 11:54
@TheBB great, thanks!

**Comment by justbur** [comment] 2015-08-10 12:10
@bgamari which-key makes a couple of changes to the polling mechanism that should help. For example it disables any timers on the frame losing focus which should fix any issues with multiple sessions all simultaneously running their own timers. 

Your suggestion about synchronizing the timers is interesting. I don't think it's possible to run multiple timers at once in which-key anyway but I'll see if maybe it's possible to take advantage of that idea.

**Comment by justbur** [comment] 2015-08-10 12:15
I should say that it's also possible to run which-key with essentially no timer (or a timer with a very long delay) and triggering the popup through a key press.

**Comment by bgamari** [comment] 2015-08-10 12:29
@justbur indeed disabling the timers on loss of focus sounds like it should be a great improvement.

About synchronizing timers: note that it's not multiple timers within `which-key` that you try to synchronize; you are trying to ensure that `which-key`'s timer fires at the same time as other timers on the system. In the optimal case, the CPU would only have to wake up once per second, service the relevant timers, and spend the rest of that second sleeping.

The worst possible case is timer events being randomly distributed throughout the second, preventing the CPU from ever sleeping long enough to reach the states where it can shut off large chunks of itself.

**Comment by justbur** [comment] 2015-08-10 12:34
That sounds even better but certainly having just four timers spread evenly across a second contributes to the problem, no?

Anyway off the top of my head I don't see a way for which-key to have multiple timers running at once.

**Comment by bgamari** [comment] 2015-08-10 13:19
@justbur well, four timings distributed across a second is certainly worse than four timers all firing at the beginning of that second. However, if the application needs to be notified four evenly-spaced times a second then you can't do much about that. Ultimately there is nothing special about the timescale of "one second"; placing timers evenly on the second is a  convention which a few libraries use because it is a reasonable period for idle-task-like-things.

If you need to fire more often then ideally you would setup your timer such that at least one of your _n_ events will occur on the second. this way the CPU will only need to do _n-1_ more wakeups than it would otherwise need to.

**Comment by syl20bnr** [comment] 2015-08-10 14:08
I may be totally wrong but I believed that which-key does not poll anything, instead it triggers a timer when a key is pressed. If those reasoning is correct then no timer should be active when the computer does not process any keyboard input on a focused emacs instance.

**Comment by justbur** [comment] 2015-08-10 14:39
@syl20bnr That's not true exactly, and I think trying to hook into a key press like that would be more intensive than what I'm doing with which-key right now. There are two ways to trigger which-key. The first is analogous to but less resource intensive than what guide-key does. The second doesn't require timers. 

1. guide-key uses `run-at-time` to check if you are in the middle of a key sequence (you've only pressed `C-x` for example), which will then trigger the popup. `run-at-time` is unnecessary because there's no reason to be checking IMO when emacs is not idle, so which-key uses `run-with-idle-timer` to trigger the check (in both cases the check I'm referring to is very simple and uses C-based functions), so it only kicks in if you are idle for the given amount of time (e.g., you are thinking of which key you wanted to press next). The second significant change in which-key is to turn the timer off at appropriate times, mainly when the frame loses focus, so that the timers are not running in the background when they make no sense to run. There might be some other minor differences, but those are the two main improvements, and should address this issue btw.

2. The second is to use a key binding directly. So `C-x C-h` will by default popup the which-key buffer for the prefix `C-x` and pretend that only `C-x` has been pressed (use can change to another trigger key of course). So you can do something like `C-x C-h C-h C-x` which will call what you have bound to `C-x C-x`. This method doesn't require idle timers, so if you use it exclusively you can set `which-key-idle-delay` to a large number to effectively disable the timer (if there's interest in not having the timer run at all, file an issue at which-key and I'll add the option). 

It's not perfect, but this is the best I could come up with in designing which-key. I'm always happy to hear from someone who has a better method of triggering which-key when the current key sequence is a [Prefix Key](https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Keys.html#Prefix-Keys), which is the basic problem to be solved. 

@bgamari Do you have an example of an elisp library that ties a function to run exactly on the second? That is, if I understand you correctly.

**Comment by syl20bnr** [comment] 2015-08-10 14:48
@justbur very cool, and to me this is just fine.

A `pre-command-hook` to check for the pressed key and trigger a timer appropriatly should not impact the perfomance though, this is a just a `cond` form. But then you should ask the user for a list of prefixes to watch which feels like a regression to me, I really like the `work out of the box` feeling of which-key.

**Comment by syl20bnr** [comment] 2015-08-10 14:50
@justbur BTW, thank you for the explanation, I was really wrong :-)

**Comment by justbur** [comment] 2015-08-10 14:54
@syl20bnr I looked into `pre-command-hook`, but it won't work. It fires after a key sequence is completed (points to a command instead of a keymap) but before the command is executed. So this is too late because the which-key buffer needs to show before the key sequence is complete to be useful.

**Comment by syl20bnr** [comment] 2015-08-10 15:36
oh indeed, thank you for the info.

**Comment by TheBB** [comment] 2015-08-25 19:49
Labeling this as fixed since we've swapped out this package. Please report issues with which-key separately.

**Closed** 2015-09-28 06:54 UTC
Labels: bug :-(, Fixed in `develop`, Guide-key, Kills Kittens (=^-^=)
