### ISSUE TITLE
REGRESSION: "elixir: fix smartparens setup" broke smartparens for elixir

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#6660] opened 2016-07-23 15:47 UTC
#### Description :octocat:
Elixir smartparens broken by commit ironically titled ["elixir: fix smartparens setup"](https://github.com/syl20bnr/spacemacs/commit/5af1e453c6725241681dcd4130b65d37c6257552).

If you eval smartparens.el, it will get fixed, which makes me think that the
hook being added is not firing on startup. 

#### Reproduction guide :beetle:
- Start Emacs
- Open an elixir file
- Type `defmodule Foo do` and press RET

*Observed behaviour:* :eyes: :broken_heart:
- `end` is not inserted automatically

*Expected behaviour:* :heart: :smile:
- `end` is inserted automatically

#### System Info :computer:
- OS: darwin
- Emacs: 25.0.95.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 1b5bc13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults spacemacs-layouts helm emacs-lisp markdown
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil)
                 erlang elixir git dash html clojure
                 (org :variables org-enable-github-support t)
                 colors osx github javascript react deft floobits ruby
                 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking ranger version-control rcirc tmux yaml docker elm evil-little-word auto-correct frame-geometry cleverparens-lispy)
```

**Comment by bmag** [comment] 2016-07-24 08:00
You're link is broken, should be: https://github.com/syl20bnr/spacemacs/commit/5af1e453c6725241681dcd4130b65d37c6257552

**Comment by bmag** [comment] 2016-07-24 08:10
Can you rename `elixir/post-init-smartparens` to `elixir/pre-init-smartparens` in your local spacemacs installation and test if that fixes the problem? Normally `spacemacs|use-package-add-hook` should be called from pre-init functions, not post-init functions.

**Comment by aaronjensen** [comment] 2016-07-25 05:39
Indeed it does @bmag, thank you: #6667

**Comment by TheBB** [comment] 2016-07-25 10:37
The fix is in and I presume the problem is not in master, so closing this. Thanks you two!

**Closed by TheBB** 2016-07-25 10:37 UTC
Labels: - Bug tracker -
