### ISSUE TITLE
Spacemacs-layout is reset after sync-configuration-layers

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#3875] opened 2015-11-19 08:56 UTC
After `sync-configuration-layers`, the current layout configuration will lost.
And there only left one `Default` layout.

I don't know if this is a feature or a bug. But I think it's better if we can keep the opening layouts.

**Comment by bmag** [comment] 2015-12-05 09:11
I can reproduce this with latest develop, with these 3 simple steps:
1. start spacemacs: I now have one layout - the default one.
2. open a new layout with `SPC l 2`: I now have two layouts.
3. reload config with `SPC f e R`: I now have only one layout again - the default one.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 8191a66)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup t)
 (git :variables git-magit-status-fullscreen t)
 version-control markdown org
 (syntax-checking :variables flycheck-check-syntax-automatically
                  '(save mode-enabled))
 evil-cleverparens c-c++
 (clojure :variables clojure-enable-fancify-symbols t)
 emacs-lisp python
 (shell :variables shell-default-shell 'shell)
 search-engine ibuffer smex themes-megapack theming eyebrowse window-purpose colors)
```

**Comment by d12frosted** [comment] 2015-12-30 08:34
The same here. Repo steps are really easy. Just as @bmag noticed.

**Comment by AlejandroCatalina** [comment] 2016-02-09 21:29
I'm looking at this and so far I think we could add some variable that will be bound to `nil` if a restart is needed and `t` if we want to preserve the current perspectives after syncing. 

The thing is to know where this variable should take effect (obviously not when an actual emacs restart is hapennig). At first sight, I thought this variable would be defined and set in the layer, and *somehow* look at it before resetting. 

I'm digging into the syncing process to see how exactly it goes, but I'm not sure if it is possible to check variables and perform alternative actions at syncing time or if we should change the current core behavior on this thing.

Any thoughts and points welcome.

**Comment by syl20bnr** [comment] 2016-05-01 15:54
Close it since it is part of a milestone.

**Closed by syl20bnr** 2016-05-01 15:54 UTC
Labels: Bug :-(, Fixed in develop, Ready for work, Spacemacs Layouts
