### ISSUE TITLE
Line number column abormally wide after a few font-size increase steps

### ISSUE THREAD

**Issue by GroundBreakingItem0** [syl20bnr/spacemacs#14011] opened 2020-10-03 12:49 UTC
#### Description :octocat:

When changing the font-size with toggle-line-numbers enabled for the buffer, after a few font-size increase steps, the line-number column suddenly gets abnormally wide.

Then once in the problem situation, reducing the font-size keeps making the line-number column wider.
It only recovers after several decrement of the font-size

Video of the behavior : https://imgur.com/a/5Anf3X4

#### Reproduction guide :beetle:
- Start Emacs
- toggle-line-numbers enabled inside a buffer
- Increase font-size (using Darwin s-+) - repeat up to 10 times
- Decrease font-size (using Darwin s--) - repeat multiple times

*Observed behaviour:* :eyes: :broken_heart:
The line-number margin gets abnormally wide (taking most of the window width.

*Expected behaviour:* :heart: :smile:
The line-number margin should remain small

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER

#### Backtrace :paw_prints:
None

**Comment by da-edra** [comment] 2020-10-08 02:10
I'm also having this issue.

**Comment by duianto** [comment] 2020-10-10 05:32
This is a duplicate of:
Linum-mode creates margins on zoomed-in font #9382

Emacs 26+ comes with built-in line numbers, which the Spacemacs `develop` branch uses.

The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Closed by duianto** 2020-10-10 05:32 UTC

**Comment by duianto** [comment] 2020-10-10 05:34
If you don't want to switch to the `develop` branch right now,
then it's possible to use the built in line numbers by rebinding the line number toggle key:
https://github.com/syl20bnr/spacemacs/issues/9382#issuecomment-482649153

Add this to the `dotspacemacs/user-config` section of your `.spacemacs`:

    (spacemacs/set-leader-keys "tn" 'display-line-numbers-mode)
Then the `SPC t n` key binding will toggle the new Emacs built-in line numbers in Emacs 26+.
