### ISSUE TITLE
no tildes in the fringe after EOF when using emacs-client

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#1303] opened 2015-04-21 18:51 UTC
when using emacs-client instead of emacs there are no tildes in the fringe after the end of file. That's with everything else configured exactly the same.

**Comment by syl20bnr** [comment] 2015-04-24 01:52
Thank you for the report.
Can you enable the layer `vim-empty-lines` and tell me if this still happens ?

**Comment by emmanueltouzery** [comment] 2015-04-24 18:28
yes, with `vim-empty-lines` that problem is gone, however to be honest I prefer the other way, because with the (currently) standard way, the tildes go in the fringe which looks better I think, and also with `vim-empty-lines` now the tildes appeared one line too low => it looked as though there was a blank line at the end of the file but it was not true. With the standard way the tildes appear at the correct line.

I have the feeling in general that `emacs-client`, though handy (cut down the startup time) has several bugs (sometimes the window comes up unfocused, sometimes it can't be focused until you kill emacs), and then also this tildes issue, so maybe I'll give it up.

**Comment by TheBB** [comment] 2016-01-26 15:50
I can't reproduce this. Update?

**Comment by emmanueltouzery** [comment] 2016-01-27 16:01
yes it still happens with the 0.105.9 & 24.5.1.
I get no more tildes after end of file unless I enable `vim-empty-lines`, with my normal setup of emacs-client. With the real emacs, I get the tildes.

**Comment by rski** [comment] 2016-08-01 07:07
I'm still getting this with spacemacs 0.105.21 and emacs 24.5.1 (compiled from source) on CentOS 7 and emacs 24.5 on arch linux.
One workaround is to reload the config, which makes the tildes appear. It also makes some other things work properly, like linum mode and git indications in the fringe and a hook to disable smartparens mode that I used to have, for which I should probably open another issue(?).
My spacemacs config can be found on [gitlab](https://gitlab.com/rski/dotfiles/blob/master/spacemacs)

**Comment by d12frosted** [comment] 2016-10-03 09:16
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 09:16 UTC
Labels: Bug :-(, Fixed in develop, Running as daemon, Visual
