### ISSUE TITLE
Strange nameless buffer, Spacemacs keybindings do not work

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2665] opened 2015-08-15 13:10 UTC
I was trying to kill the buffers one by one and landed on the following buffer -

![spacemacs-bug](https://cloud.githubusercontent.com/assets/4531751/9288942/d9474534-437c-11e5-802f-098fbbb3461b.png)

Spacemacs keybindings stopped working in this nameless buffer. Pressing `space` is of absolutely no use. I can use emacs keybindings though. I typed `C-x C-c` to close emacs and it worked.

**Comment by TheBB** [comment] 2015-08-15 13:37
It's not nameless, that's the anaconda mode buffer. For whatever reason the modeline is broken.

**Comment by bmag** [comment] 2015-08-15 14:18
Oh yeah, I also noticed something like this several times in the past. Reproducible by typing <kbd>M-: (set-window-buffer (selected-window) (get-buffer-create "new-buffer"))</kbd>. My work around is to toggle `evil-mode` off and on by typing <kbd>M-x evil-mode</kbd> twice. I never got around to finding the culprit and reporting an issue, though.

**Comment by bmag** [comment] 2015-08-15 15:57
@aviralg I opened an issue upstream: https://bitbucket.org/lyro/evil/issues/558/consider-advising-set-window-buffer.

**Comment by bmag** [comment] 2015-08-18 19:29
Should be fixed now in Evil. Please update your packages and see if your problem is solved.

**Comment by syl20bnr** [comment] 2015-08-19 01:18
:+1:

**Comment by TheBB** [comment] 2015-08-22 12:48
I haven't tested this since the repro steps are vague at best, but #2674 is fixed and gut feeling says they're the same problem.

**Comment by TheBB** [comment] 2015-08-30 19:29
No reply, so I'm closing.

**Closed by TheBB** 2015-08-30 19:29 UTC
Labels: bug :-(, Evil, Fixed upstream, package, Reported upstream
