### ISSUE TITLE
Racket layer question

### ISSUE THREAD

**Issue by Cifer-Y** [syl20bnr/spacemacs#4743] opened 2016-01-22 08:29 UTC
Recently, I met a very strange problem with racket layer.
I config like this:
` (setq geiser-racket-binary "/Applications/racket6.3/bin/racket")`

And in emcas, I open a `.rkt` file, run `run-geiser`, there is a racket repl.
Then, I run `SPC-m-s-B`, I want to send the file to repl, but I got: 
`Searching for program: no such file or directory, racket`

And company-mode's autocomplete also report racket not found.

It's weird, please help.

**Comment by duerrp** [comment] 2016-01-25 02:33
I don't think this has anything to do with JavaScript.

As for the original issue, I cannot reproduce the problem here (i.e., `SPC-m-s-B` works for me). I have `geiser-racket-binary` set to 'racket' though.

**Comment by robbyoconnor** [comment] 2016-01-25 02:37
Racket is a lisp dialect

**Comment by Cifer-Y** [comment] 2016-01-25 03:09
@duerrp So, that was what I'm talking about weird... I just set `geiser-racket-binary`, and something can work well, some didn't. I'm very confused

**Comment by StreakyCobra** [comment] 2016-01-25 08:29
I was probably tired, I had read `React` ;-) Corrected, there is a Racket label already.

**Comment by jalehman** [comment] 2016-01-25 19:25
I had the same problem recently -- it was fixed by ensuring that the Racket binaries were on my `PATH` (`.zshenv` for me, depends on your shell).

If you type `racket` at a terminal and get `command not found: racket`, this is likely the issue.

**Comment by tonylotts** [comment] 2016-01-28 13:01
FWIW, the Scheme layer works well with Racket and is more feature-rich.

**Comment by Cifer-Y** [comment] 2016-01-28 14:22
@jalehman `racket` command is in my path, in terminal I typed `racket` would run the racket repl.

**Closed** 2016-04-12 15:12 UTC
Labels: Question, Racket
