### ISSUE TITLE
Error message for `SPC` completion pop up

### ISSUE THREAD

**Issue by JustAPerson** [syl20bnr/spacemacs#10284] opened 2018-01-31 08:22 UTC
#### Description :octocat:
Error after pressing `SPC`

This began after running `git pull` in my develop branch. I have since done a clean reinstall (delete `~/.spacemacs` and `~/.emacs.d/`) of the master branch but the problem persists.

#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC` and nothing else

*Observed behaviour:* :eyes: :broken_heart:
- Message: Error running timer ‘which-key--update’: (wrong-type-argument stringp nil)

*Expected behaviour:* :heart: :smile:
- Expected the useful dialogue that shows next available command sequences

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by Alexander-Miller** [comment] 2018-01-31 12:18
Try `M-x spacemacs/toggle-debug-on-error-on` so you can share a proper stacktrace.

**Comment by dewaka** [comment] 2018-01-31 13:01
I'm facing the same issue and my stacktrace is as follows,

`
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^group:" nil nil)
  which-key--propertize-description(nil nil nil nil "winum-select-window-1")
  which-key--format-and-replace((("SPC" . "helm-M-x") ("TAB" . "spacemacs/alternate-buffer") ("!" . "shell-command") ("'" . "spacemacs/default-pop-shell") ("*" . "spacemacs/helm-project-smart-do-search-region-or-symbol") ("/" . "spacemacs/helm-project-smart-do-search") ("0" . "winum-select-window-0-or-10") ("1" . "winum-select-window-1") ("2" . "winum-select-window-2") ("3" . "winum-select-window-3") ("4" . "winum-select-window-4") ("5" . "winum-select-window-5") ("6" . "winum-select-window-6") ("7" . "winum-select-window-7") ("8" . "winum-select-window-8") ("9" . "winum-select-window-9") (";" . "evilnc-comment-operator") ("?" . "helm-descbinds") ("`" . "winum-select-window-by-number") ("a" . "Prefix Command") ("B" . "Prefix Command") ("b" . "Prefix Command") ("C" . "Prefix Command") ("c" . "Prefix Command") ("D" . "Prefix Command") ("e" . "Prefix Command") ("f" . "Prefix Command") ("g" . "Prefix Command") ("h" . "Prefix Command") ("i" . "Prefix Command") ("j" . "Prefix Command") ("k" . "Prefix Command") ("l" . "spacemacs/layouts-transient-state/body") ("n" . "Prefix Command") ("p" . "Prefix Command") ("q" . "Prefix Command") ("r" . "Prefix Command") ("S" . "Prefix Command") ("s" . "Prefix Command") ("T" . "Prefix Command") ("t" . "Prefix Command") ("u" . "universal-argument") ("v" . "er/expand-region") ("w" . "Prefix Command") ("x" . "Prefix Command") ("z" . "Prefix Command") ("²" . "winum-select-window-by-number") ("<f1>" . "helm-apropos")))
  which-key--get-formatted-key-bindings(nil nil)
  which-key--create-buffer-and-show([32])
  which-key--update()
  apply(which-key--update nil)
  timer-event-handler([t 0 0 400000 t which-key--update nil idle 0])
`

**Comment by matthjes** [comment] 2018-01-31 13:15
Hi,
I'm having the same problem with a fresh install of spacemacs. Version is master v0.200.13

**Comment by bojov** [comment] 2018-01-31 13:23
#### Description
Error after pressing SPC
Clean reinstall of develop branch (deleted .spacemacs .spacemacs.d and .emacs.d)

#### Reproduction guide
After starting the emacs press SPC and nothing else

##### Observed behaviour:
- Message: Error running timer ‘which-key--update’: (wrong-type-argument stringp nil)

#### Expected behaviour:
- Expected the dialogue that shows available command sequences

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 64cf9f56)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS


#### Backtrace:
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^group:" nil nil)
  which-key--propertize-description(nil nil nil nil "winum-select-window-2")
  which-key--format-and-replace((("SPC" . "helm-M-x") ("TAB" . "spacemacs/alternate-buffer") ("!" . "shell-command") ("*" . "spacemacs/helm-project-smart-do-search-region-or-symbol") ("/" . "spacemacs/helm-project-smart-do-search") ("0" . #("neotree-show" 0 12 (button (t) category default-button face which-key-command-description-face help-echo "Show the NeoTree window.  (fn)"))) ("1" . "winum-select-window-1") ("2" . "winum-select-window-2") ("3" . "winum-select-window-3") ("4" . "winum-select-window-4") ("5" . "winum-select-window-5") ("6" . "winum-select-window-6") ("7" . "winum-select-window-7") ("8" . "winum-select-window-8") ("9" . "winum-select-window-9") (";" . "evilnc-comment-operator") ("?" . "helm-descbinds") ("`" . "winum-select-window-by-number") ("a" . "Prefix Command") ("b" . "Prefix Command") ("C" . "Prefix Command") ("c" . "Prefix Command") ("e" . "Prefix Command") ("F" . "Prefix Command") ("f" . "Prefix Command") ("h" . "Prefix Command") ("i" . "Prefix Command") ("j" . "Prefix Command") ("k" . "Prefix Command") ("l" . "spacemacs/layouts-transient-state/body") ("N" . "Prefix Command") ("n" . "Prefix Command") ("p" . "Prefix Command") ("q" . "Prefix Command") ("r" . "Prefix Command") ("s" . "Prefix Command") ("T" . "Prefix Command") ("t" . "Prefix Command") ("u" . "universal-argument") ("v" . "er/expand-region") ("w" . "Prefix Command") ("x" . "Prefix Command") ("z" . "Prefix Command") ("²" . "winum-select-window-by-number") ("<f1>" . "helm-apropos")))
  which-key--get-formatted-key-bindings(nil nil)
  which-key--create-buffer-and-show([32])
  which-key--update()
  apply(which-key--update nil)
  timer-event-handler([t 0 0 400000 t which-key--update nil idle 0])

**Comment by Alexander-Miller** [comment] 2018-01-31 13:26
Stopgap solution: `(which-key-mode -1)`.

CC @justbur Any thoughts on what's going on?

**Comment by Apakollaps** [comment] 2018-01-31 13:30
Rolling back packages and adding which-key to the dotspacemacs-frozen-packages is another workaround. which-key-20180108.1930 works.

**Comment by MoneySail** [comment] 2018-01-31 13:46
I hava the same problem after I update spacemacs today.

**Comment by bmag** [comment] 2018-01-31 13:51
This is an upstream issue, reported (just now) in https://github.com/justbur/emacs-which-key/issues/186. Likely caused by https://github.com/justbur/emacs-which-key/commit/c71fbbbc3ec49bac4b73fe2700d633e3037c7ae4 (the backtraces support it).

As @Apakollaps wrote, those affected should roll back their packages and add `which-key` to `dotspacemacs-frozen-packages`. Once `which-key` is frozen, restart Spacemacs and then you can update all the other packages safely.

To those about to update packages, make sure you freeze `which-key` beforehand.

**Comment by vidyu** [comment] 2018-01-31 14:31
For these that cannot rollback:
I replaced the `which-key.el` with this version https://raw.githubusercontent.com/syl20bnr/spacemacs-elpa-mirror/0a795de514d296569bbb571a9f1865832973ea1d/stable-melpa/which-key-3.1.0.el and removed the `which-key.elc`
The popup is working again.

**Comment by duianto** [comment] 2018-01-31 19:03
This might be fixed now.

I hadn't updated to the which-key version with this issue, so I never saw the error message. But I just updated the packages, and the `SPC` which-key popup opens without any issues.

Szunti that reported the issue upstream: 
(wrong type argument strinp nil) if binding is removed by replacement https://github.com/justbur/emacs-which-key/issues/186

Has tested the latest version and said:
>Thank you, works now without problems.

**Comment by bmag** [comment] 2018-02-01 06:37
The issue should be resolved upstream now. Everyone can unfreeze `which-key` and update normally again. Thank you all for the reports.

**Closed by bmag** 2018-02-01 06:37 UTC
Labels: - Bug tracker -, Reported upstream, Which-key
