### ISSUE TITLE
C-C++ mode. Yas can not expand correctly.

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#2907] opened 2015-09-06 15:57 UTC
I want to insert c-header file in cpp, for example, #include<stdio.h>. Firstly, I typed "inc" and used yas to expand it into "#include<>". Then I failed to expanded it into "#include<stdio.h>" by using yas. It returned "#include >". Do I need add hook or something else? Please help me out. Thank in advance.

**Comment by TheBB** [comment] 2015-09-10 16:08
I can't reproduce any problems here. Can you tell me the exact key sequence you are using?

**Comment by zhexuany** [comment] 2015-09-16 21:06
@TheBB Sorry about the delay. Actually, this mistake  maybe cause by auto-completion. I still have this problem.

**Comment by louy2** [comment] 2015-09-24 17:57
Could you reproduce this with a fresh install?

**Comment by zhexuany** [comment] 2015-09-24 21:55
@louy2 I got this error menages.  yas--on-field-overlay-modification: Wrong type argument: number-or-marker-p, (610 . #<marker in no buffer>)yas--on-field-overlay-modification: Wrong type argument: number-or-marker-p, (610 . #<marker in no buffer>)

**Comment by louy2** [comment] 2015-09-25 16:22
That function is called when you start to modify a field in the expanded snippet, and it clears the tips in the field for you. I don't know why it is passed wrong type argument though. Maybe you need to do an update? Just click the "Update" in the nav in the home buffer.

**Comment by zhexuany** [comment] 2015-09-29 05:12
@louy2  Yeah. I updated all packages but still have the same problem.

**Comment by louy2** [comment] 2015-09-29 12:59
Well... Could you back up your `.emacs.d` and do a minimal test on this? I mean using vanilla Emacs, installing only YASnippet and enabling it. That would determine whether it's an upstream bug.

**Comment by zhexuany** [comment] 2015-09-29 13:34
Sounds great. I will test it tonight. Let's see what is going on. In addition, can you give some reference about how to test Yasnippets?

**Comment by zhexuany** [comment] 2015-09-29 22:19
It worked now. But I had new issue - -. AC and syntax checking is not default enable when I open .c file. Any idea?

**Comment by louy2** [comment] 2015-09-30 05:04
> It worked now.

Do you mean YASnippet worked inside Spacemacs or you tested it individually and it worked outside Spacemacs?

Btw, if you need a more detailed guide:

1. Backup your `.emacs.d` to another place and delete everything inside it
1. Add `init.el` to your now empty `.emacs.d`, and add following content to it
```
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
```
1. Open emacs, and use `list-packages` to open package list buffer
1. Find `yasnippet` and install it.
1. Add to your `init.el` 
```
(require 'yasnippet)
(yas-global-mode 1)
```
It should come with C snippets, so open a new buffer by `spacemacs/new-empty-buffer`, change to `c-mode` and see if you can expand a snippet, for example, type `d` and press `<TAB>` to see if it expands to `#define` and lets you add the parameter right away.

And you can use `SPC t s` to toggle syntax checking.

**Comment by geo7** [comment] 2015-10-23 17:09
@zhexuany bump! Did you try the steps suggested ? Any news / info on this? If all's good please close the issue :+1:

**Closed** 2015-10-23 17:16 UTC
Labels: C/C++, Yasnippet
