### ISSUE TITLE
cd and setq default-directory in .spacemacs not working

### ISSUE THREAD

**Issue by sid-kap** [syl20bnr/spacemacs#16530] opened 2024-08-23 19:55 UTC
I tried adding
```lisp
(cd "/Users/sidharthkapur/workspace")
(setq default-directory "/Users/sidharthkapur/workspace")
```
to dotspacemacs/user-config and to dotspacemacs/user-init but neither seems to work. I want ivy to default to the workspace folder when I do find-file (`SPC f f`).

It does work if I do `SPC SPC` and choose `cd` and type in `/Users/sidharthkapur/workspace`

**Comment by bcc32** [comment] 2024-08-23 20:04
`default-directory` is a buffer-local variable in Emacs, and `SPC f f` will always start from the `default-directory` of the current buffer (e.g., the containing directory of the file you're looking at).

Are you trying to make `SPC f f` always start from a particular directory, no matter what file you're in?

Maybe what you're looking for is something like `SPC p f` instead, which finds files based on the root of the current project (such as a git repo)?

**Comment by sid-kap** [comment] 2024-08-23 21:08
Thanks so much for explaining! My bad for not understanding this properly.

I wanted `SPC f f` to always open to ~/workspace just for the spacemacs home buffer, so before I've opened a file/entered a project.
Doesn't seem like a bug in spacemacs, so feel free to close

**Comment by bcc32** [comment] 2024-08-24 15:44
You could probably do something like:

```elisp
(add-hook 'spacemacs-buffer-mode-hook (lambda () (setq default-directory "~/workspace/")))
```

But indeed, I think this is up to your personal preference and not a bug in Spacemacs.  (I don't have maintainer access to this repo so I can't close the issue for you, sorry)

**Comment by sid-kap** [comment] 2024-08-24 15:49
This is really helpful, thanks so much!

**Closed as completed** 2024-08-24 15:49 UTC
