### ISSUE TITLE
maximize-centered-buffer changes overall function, no way to exit centered mode

### ISSUE THREAD

**Issue by vixr** [syl20bnr/spacemacs#3934] opened 2015-11-24 04:39 UTC
maximize-centered-buffer (spc-w-M) seems to be messing things up my overall view. For example, the narrow margins get applied to the leader popup. When using workspaces via eyebrowse, it seems to have an effect across workspaces. There also doesn't seem to be a way to get out of the mode once I'm in it.

**Comment by nixmaniack** [comment] 2015-11-24 05:52
Hitting same sequence should minimize it.

**Comment by StreakyCobra** [comment] 2015-11-28 12:01
@vixr Have you tried @nixmaniack solution? If it doesn't help, can you provide more details about your problem, like steps on how to reproduce?

**Comment by MichaelMartinez** [comment] 2016-01-11 02:39
Steps to reproduce:

1. Open (spac)emacs
2. Have two or more buffers open, can be anything (messages, scratch, compile log, etc.)
3. Hit SPC w M to get one buffer front and center, maximized.
4. Every time you hit space again, the text(right side) is cut off/truncated/missing from the leader popup. 
5. @nixmaniack 's solution does not work.
I've struggled with this for the last 2 days: emacs 24.3.1 && 24.4 with Ubuntu 14.04, and Ubuntu 14.04 MATE

It is completely unusable once you hit this combo unless you've memorized the entire right side of the popup...

![screenshot-emacs-24 4 li-uno](https://cloud.githubusercontent.com/assets/452345/12225922/63b7e6a6-b7d1-11e5-93d0-bc4ce6846d12.png)

**Comment by syl20bnr** [comment] 2016-01-11 03:00
I guess that which-key has to take into account the margin size in its calculations.
Reported upstream: https://github.com/justbur/emacs-which-key/issues/97

**Comment by justbur** [comment] 2016-01-11 03:59
> I guess that which-key has to take into account the margin size in its calculations.

I do, and I can't reproduce this. 

The width is calculated using `(frame-width)`, which reports the correct value for me. Maybe you can try `M-: (frame-width)` and see if the number of characters is wrong.

**Comment by nixmaniack** [comment] 2016-01-11 07:23
I can reproduce this. Toggling back produces following error.
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  jump-to-register(_)
  (progn (bzg-big-fringe-mode 0) (jump-to-register (quote _)))
```

I have perspectives and eyebrowse enabled, can it be that?

**Comment by justbur** [comment] 2016-01-11 12:04
That's not coming from which-key.

**Comment by StreakyCobra** [comment] 2016-01-11 12:10
I can reproduce.

Vertical split + `SPC w M`:

![screenshot](https://i.imgur.com/AvAvN6L.png)

vs only one buffer:

![screenshot](https://i.imgur.com/62MXIo4.png)

**Comment by nixmaniack** [comment] 2016-01-11 14:32
I mean I could reproduce the which-key part but also faced error while toggling back.
`SPC w 2` `SPC f e d` `SPC w w` `SPC f e d` `SPC w M` `SPC`
<img width="1280" alt="screen shot 2016-01-11 at 7 58 25 pm" src="https://cloud.githubusercontent.com/assets/542810/12236131/1a433d18-b89e-11e5-8dce-bdb08ed59936.png">

**Comment by justbur** [comment] 2016-01-11 14:37
Interesting. It's specific to emacs24. Ok, I think I have a solution.

**Comment by justbur** [comment] 2016-01-11 14:59
Should be fixed with https://github.com/justbur/emacs-which-key/commit/9bb70c8cdd43f0cd76871fddc4dd3ee1bccd3897

**Comment by justbur** [comment] 2016-01-15 19:58
@StreakyCobra or @nixmaniack can you confirm that this is fixed?

**Comment by StreakyCobra** [comment] 2016-01-15 22:40
@justbur I tested it briefly and it doesn't seems to be fixed, but I need to go so I tested it really quickly, maybe too quickly actually. I'll test it more carefully later this week-end. So… to be confirmed.

**Comment by syl20bnr** [comment] 2016-01-16 00:27
It is fixed for me after updating which-key :+1: 

@nixmaniack what error ? I tried your repo step and it is OK for me.

**Comment by nixmaniack** [comment] 2016-01-16 03:57
After updating which-key it's fixed for me as well. The whick-key pop up is correctly aligned in maximized centered buffer.

@syl20bnr I'm getting following error when trying to get back to original window configuration when I hit `SPC w M` 
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  jump-to-register(_)
  (progn (bzg-big-fringe-mode 0) (jump-to-register (quote _)))
  (if (= 1 (length (window-list))) (progn (bzg-big-fringe-mode 0) (jump-to-register (quote _))) (progn (set-register (quote _) (list (current-window-configuration))) (delete-other-windows) (bzg-big-fringe-mode 1)))
  spacemacs/toggle-maximize-centered-buffer()
  call-interactively(spacemacs/toggle-maximize-centered-buffer nil nil)
  command-execute(spacemacs/toggle-maximize-centered-buffer)
```

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: develop (rev. 8adb066)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" :disabled-for org erc)
 semantic better-defaults emacs-lisp
 (git :variables git-gutter-use-fringe t git-magit-status-fullscreen nil)
 github markdown yaml shell
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.emacs.d/private/elfeed.org"))
 lua python ruby ruby-on-rails
 (clojure :variables clojure-enable-fancify-symbols t)
 shell-scripts html javascript eyebrowse spacemacs-layouts
 (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e/")
 nix-mu4e gnus colors deft finance
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 version-control ansible emoji ranger osx typography
 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
 org)
```

**Comment by StreakyCobra** [comment] 2016-01-17 17:06
I tried a little bit more and it's something with my configuration. I tried with a default `.spacemacs` and indeed it works, but with my config I have this:

Normal:

![A](https://i.imgur.com/aMmHL9T.png)

`SPC w M`:

![B](https://i.imgur.com/dtL0kBy.png)
-----

Also I can confirm @nixmaniack even with a default `.spacemacs`:

`SPC w M` give me:

```elisp
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  jump-to-register(_)
  (progn (bzg-big-fringe-mode 0) (jump-to-register (quote _)))
  (if (= 1 (length (window-list))) (progn (bzg-big-fringe-mode 0) (jump-to-register (quote _))) (progn (set-register (quote _) (list (current-window-configuration))) (delete-other-windows) (bzg-big-fringe-mode 1)))
  spacemacs/toggle-maximize-centered-buffer()
  call-interactively(spacemacs/toggle-maximize-centered-buffer nil nil)
  command-execute(spacemacs/toggle-maximize-centered-buffer)
```

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: develop (rev. 9b77891)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(streakycobra asciidoc
              (auto-completion :variables auto-completion-enable-snippets-in-popup t)
              better-defaults c-c++ clojure colors command-log deft dockerfile
              (elfeed :variables rmh-elfeed-org-files
                      (list "~/org/elfeed.org"))
              emacs-lisp emoji erc ess evil-cleverparens extra-langs finance git github haskell html ipython-notebook javascript latex markdown mu4e no-dots ocaml org pandoc python ranger restclient ruby semantic shell shell-scripts speed-reading spacemacs-helm
              (spell-checking :variables spell-checking-enable-auto-dictionary t)
              syntax-checking themes-megapack theming typography
              (version-control :variables version-control-diff-tool 'diff-hl)
              yaml bepo)
```

**Comment by StreakyCobra** [comment] 2016-01-17 17:31
I found where the bug came from:

```elisp
  (setq-default left-fringe-width 20)
```

in my `user-init`. I don't know if it is an expected behaviour.

**Comment by MichaelMartinez** [comment] 2016-01-21 05:17
I got my Mac back and this bug followed me :cry: 

Is there a better way to manage windows... especially at start up? I find Messages opens up and sometimes compile opens too. I don't want them open, so I SPC b k and murder them. Scratch dutifully takes their place, but I want one window to open dired. So, I then SPC w M with focus on *spacemacs* to get started... Hit SPC again and the menu is crunched.

**Comment by rgrinberg** [comment] 2016-10-24 02:23
@MichaelMartinez can you reproduce the peoblem with emacs 25?

**Closed** 2017-07-04 08:45 UTC
Labels: Bug :-(, Reported upstream, Which-key
