### ISSUE TITLE
Variable is void: elm

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#4682] opened 2016-01-19 13:16 UTC
`elm-mode` complains that

> Symbol's value as variable is void: elm

Disabling `auto-completion` layer removes the issue.

I'm running Spacemacs on Emacs 24.5.1 on Arch Linux. I'm running off of the *develop* branch.

**Comment by TheBB** [comment] 2016-01-19 21:17
Your packages are up to date? This is reminiscent of https://github.com/jcollard/elm-mode/issues/50

**Comment by magthe** [comment] 2016-01-19 23:01
I did an upgrade of packages a few minutes before reporting. Did another one now, and the issue remains.

* `elm-mode-20160117.258`

Hopefully it's easy to reproduce by turning on `auto-completion` and `elm`, then opening an elm file.

**Comment by StreakyCobra** [comment] 2016-01-20 08:41
Indeed I can reproduce it. I assumed from TheBB response that he can't reproduce it. Wrong assumption on my side sorry.

**Comment by StreakyCobra** [comment] 2016-01-20 08:48
@magthe Btw, it would be nice (for your next reporting) if you can give more information, such as explained [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) :smiley: 

#### Description

`elm` with `auto-completion` is throwing an error.

#### Reproduction guide
- Be sure that `elm` and `auto-completion` layers are enabled
- Start Emacs
- Open an elm file: `SPC f J elm RET`

An error is thrown: `Symbol's value as variable is void: elm`

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. a8ce785)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(streakycobra asciidoc
              (auto-completion :variables auto-completion-enable-snippets-in-popup t)
              better-defaults c-c++ clojure colors command-log deft dockerfile
              (elfeed :variables rmh-elfeed-org-files
                      (list "~/org/elfeed.org"))
              emacs-lisp emoji erc ess evil-cleverparens extra-langs finance git github haskell html ipython-notebook javascript latex markdown mu4e no-dots ocaml org pandoc python ranger restclient ruby semantic shell shell-scripts speed-reading spacemacs-helm
              (spell-checking :variables spell-checking-enable-auto-dictionary t)
              syntax-checking themes-megapack theming typography elm
              (version-control :variables version-control-diff-tool 'diff-hl)
              yaml bepo)
```

#### Backtrace

```
Debugger entered--Lisp error: (void-variable elm)
  #[nil "\302\303\304	BD\"\207" [elm elm-oracle--pattern ac-define-source (candidates elm-oracle--get-completions ac-prefix t) prefix] 5]()
  eval-after-load(auto-complete #[nil "\302\303\304	BD\"\207" [elm elm-oracle--pattern ac-define-source (candidates elm-oracle--get-completions ac-prefix t) prefix] 5])
  require(elm-interactive)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\207" [require elm-tags elm-format elm-indent elm-interactive elm-font-lock] 2)
  elm-mode()
  set-auto-mode-0(elm-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(t t)
  find-file-noselect-1(#<buffer 20-094021.elm> "~/.emacs.d/.cache/junk/2016/01/20-094021.elm" nil nil "~/dev/projects/spacemacs/.cache/junk/2016/01/20-094021.elm" nil)
  find-file-noselect("/home/fabien/.emacs.d/.cache/junk/2016/01/20-094021.elm" nil nil nil)
  find-file("/home/fabien/.emacs.d/.cache/junk/2016/01/20-094021.elm")
  find-file-at-point("/home/fabien/.emacs.d/.cache/junk/2016/01/20-094021.elm")
  helm-find-file-or-marked("/home/fabien/.emacs.d/.cache/junk/2016/01/20-094021.elm")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  #[0 "\311\211\211\211\305\206\n
```

**Comment by magthe** [comment] 2016-01-20 10:02
Hmm, I'm guessing this is where github's *very* rudimentary issue system falls short... I'll try to remember for next time.

Maybe there should be a command for that? `SPC a r`

**Comment by TheBB** [comment] 2016-01-20 12:03
Ah, sorry. I didn't try to reproduce.

**Comment by TheBB** [comment] 2016-01-20 12:04
But anyway, this looks a lot like the same error from last time. @Bogdanp?

**Comment by Bogdanp** [comment] 2016-01-20 12:28
I don't think I've changed anything that would've affected this recently (the last change to `elm-interactive.el` was unrelated and it was over 6 days ago, for example). At any rate, I'll re-work the `auto-complete` stuff either tonight or tomorrow morning to ensure this doesn't happen again.

**Comment by Bogdanp** [comment] 2016-01-21 07:50
The issue should now be fixed in elm-mode. I ended up dropping the call to `ac-define-source` altogether in favor of a plain `defvar`.

**Comment by magthe** [comment] 2016-01-21 08:33
A question that betrays my absolut emacs-newbie-ism: How can I find out if this is on the way to an ELPA near me? ;)

**Comment by Bogdanp** [comment] 2016-01-21 08:39
[The MELPA website](http://melpa.org/#/) displays information about the current build. I don't think the change made it into the current build so it'll probably be another 4-5 hours until it goes up.

**Comment by StreakyCobra** [comment] 2016-01-21 09:22
@magthe You can "kind-of" follow the build progression [on twitter](https://twitter.com/melpa_emacs). Packages are built in alphabetical order.

**Comment by TheBB** [comment] 2016-01-21 15:57
It's not confirmed but I'll take the chance anyway to close this as fixed in develop. Thank you @Bogdanp!

**Closed** 2016-01-23 14:10 UTC
Labels: Auto-completion, bug :-(, Fixed upstream

**Comment by magthe** [comment] 2016-01-27 22:56
It seems to indeed be fixed upstream, so it was a good call to close it.
