### ISSUE TITLE
Unable to make Helm split only the selected window

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#8424] opened 2017-02-23 04:01 UTC
#### Description :octocat:
I'm trying to make Helm show the pop-up window my splitting inside the selected windows. However, it seems never work.

#### Reproduction guide :beetle:
- Start Emacs
- Set variable `helm-split-window-in-side-p` to `t` (actually, it is the default value of Spacemacs)
- Split the current frame into two vertical windows
- Call `M-x helm-mini`

*Observed behaviour:* :eyes: :broken_heart:
- The pop-up window is not shown by splitting the selected window. Instead, Spacemacs split the entire frame, and display the pop-up window at the end of the frame

*Expected behaviour:* :heart: :smile:
- I would expect only the selected windows is split.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(csv python html javascript auto-completion better-defaults emacs-lisp git markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control spacemacs-layouts semantic pdf-tools latex ocaml haskell tddsg)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by agrafix** [comment] 2017-05-25 16:14
Can confirm this!

**Comment by kjvic** [comment] 2017-07-30 01:09
It looks like https://github.com/syl20bnr/spacemacs/issues/9044 may be a duplicate of this issue. However, am linking to that issue because it appears that a workaround was found there.

**Comment by d12frosted** [comment] 2017-07-30 13:16
You're right, @kjvic. Thanks for the link.

I am closing this one in favour of #9044 as the latter has more activity.

**Closed by d12frosted** 2017-07-30 13:16 UTC
Labels: - Bug tracker -, Helm
