### ISSUE TITLE
Broken internal doc links (404 not found)

### ISSUE THREAD

**Issue by microamp** [syl20bnr/spacemacs#4721] opened 2016-01-21 10:16 UTC
Links appear to be broken in docs, https://github.com/syl20bnr/spacemacs/tree/master/doc

Clicking on any of the internal links under the heading 'Spacemacs conventions' in https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org would lead you to the GitHub 404 page.

**Comment by StreakyCobra** [comment] 2016-01-21 10:59
Closing as duplicate of #4399 :-)

**Closed by StreakyCobra** 2016-01-21 10:59 UTC
