### ISSUE TITLE
"Customize Option" buffers lack evil mode.

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#7583] opened 2016-10-28 22:12 UTC
#### Description :octocat:
"Customize Option" buffers lack evil mode.

#### Reproduction guide :beetle:
- Start Emacs
- SPC SPC, customize-variable
- Pick some variable

*Observed behaviour:* :eyes: :broken_heart:
- Get stuck in Emacs mode, panic, until you stumble on C-x b to get to another buffer

*Expected behaviour:* :heart: :smile:
- Move around the buffer in evil mode. I don't know what the expected behavior around the buttons and form field should be.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(dash chrome colors deft fasd semantic slack theming themes-megapack typography pdf-tools github helm latex pandoc restclient
      (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-space-key-behavior 'reject auto-completion-return-key-behavior 'reject auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1)
      better-defaults markdown org
      (shell :variables shell-default-shell 'term shell-default-term-shell "/usr/bin/zsh" shell-default-height 40 shell-default-position 'bottom)
      emacs-lisp javascript clojure react yaml git syntax-checking)
```

#### Backtrace :paw_prints:
```
```

**Comment by bmag** [comment] 2016-10-29 05:29
Duplicate of #6699

**Closed by bmag** 2016-10-29 05:29 UTC
