### ISSUE TITLE
Incorrect braces matching in Django templates/web-mode

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4812] opened 2016-01-26 04:11 UTC
This is the same as https://github.com/syl20bnr/spacemacs/issues/1333

Reproduce: Type `{{<SPC>` in `web-mode`.
Expected: Expands to `{{<SPC><SPC>}}`.
Actual: Expands to `{{<SPC><SPC>}}}`.

I have a relatively clean Spacemacs on a work computer that exhibits this; I will endeavor to post the `SPC h d s` within a few days.

The workaround posted in the old issue fixes the problem:

~~~
(sp-local-pair 'web-mode "<" nil :actions '(:rem insert))
(sp-local-pair 'web-mode "{" nil :actions '(:rem insert))
~~~

**Comment by TheBB** [comment] 2016-01-26 14:10
This is fixed by https://github.com/syl20bnr/spacemacs/pull/4728 and a duplicate of https://github.com/syl20bnr/spacemacs/issues/4499.

**Closed** 2016-01-26 14:11 UTC
Labels: bug :-(, duplicate (-: :-), Smartparens, Web
