### ISSUE TITLE
Treemacs, key press, Invalid face reference: spacemacs-treemacs-face

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#9725] opened 2017-10-12 00:13 UTC
#### Description :octocat:
When the `SPC f t` Treemacs window is selected, and a key is pressed, then the `SPC b m` `*Messages*` buffer repeats this messages:
>Invalid face reference: spacemacs-treemacs-face

#### Reproduction guide :beetle:
- Start Emacs with Spacemacs cloned, on the latest develop branch.
- With `treemacs` in the configuration layers list, and `neotree` commented out.
- Open the `*Messages*` buffer `SPC b m`
- Open the Treemacs window `SPC f t`
- Navigate to the next or previous line (`j` and `k` with the `vim` editing style, `n` and `p` with `emacs` style)

*Observed behaviour:* :eyes: :broken_heart:
The `*Messages*` buffer shows this message several times:
>Invalid face reference: spacemacs-treemacs-face

When this issue was written then the invalid face message repeated 9 times. But when Emacs was restarted with `SPC q R` (without resuming layouts), then it "only" repeated 5 times.

Most key presses cause the message to appear instantly, but if `g` is pressed then it doesn't appear right away, but if `r` is pressed right after `g` or if one waits for the which-key popup to open with the list of key bindings under `g`, then the invalid face message repeats again.

*Expected behaviour:* :heart: :smile:
The cause of the invalid face reference message should be fixed.

#### Notes
I found this issue on the Treemacs repository:
`shell-pop-eshell` fails when treemacs buffer is open https://github.com/Alexander-Miller/treemacs/issues/17
where the invalid face message also appears, but the preceding message, seems to have been the real issue there. Therefore the invalid face message never seems to be discussed.

I tried looking for an occurrence of `spacemacs-treemacs-face` but couldn't find a single instance, in the Spacemacs `.emacs.d` directory and it's sub-directories.

I don't know if this is relevant, but the closest thing related to treemacs, spacemacs and face, seems to be this face definition:
```elisp
(defface treemacs-help-title-face
  `((t :inherit ,(if (bound-and-true-p font-lock-builtin-face) 'spacemacs-transient-state-title-face 'font-lock-constant-face)))
  "Face for tags."
  :group 'treemacs-faces)
```
near the bottom of the file: `~/.emacs.d/elpa/treemacs-20171004.631/treemacs-faces.el`.

#### side note:
This comment: `;; 'face 'spacemacs-transient-state-title-face)`, near the bottom of the same file, might have been left behind, when the face definition above was written. Maybe it can be removed.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 07014dee)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 autohotkey emacs-lisp git helm markdown org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by Alexander-Miller** [comment] 2017-10-14 14:18
Does spacemacs/github have some means to be alerted about specific issues? I only found this one because I randomly looked through the issue list. Itd be great If I could be notified about new issues with "treemacs" in the title, or the File Browser label.

At any rate thanks for finding that borked face code, I guess I was in a hurry and forgot to finish that part. Ive pushed a fix for that now, maybe itll fix the invalid face ref as well.
I can confirm that treemacs never defines any face called `spacemacs-treemacs-face`, and I cannot reproduce the issue either, so lets do some debugging:

 * Does the error still appear if you start spacemacs with a different theme?
 * Do you get a backtrace if you `enable-debug-on-error` before first starting treemacs?

**Comment by duianto** [comment] 2017-10-14 16:57
I changed from the default `spacemacs-dark` theme, to the `whiteboard` theme, by adding it as the first theme in the `dotspacemacs-themes` variable in `.spacemacs`. And restarted Emacs.
The `whiteboard` theme was included with Emacs, so I also tried an external theme: 
`sanityinc-tomorrow-eighties`, there might not be any difference, but it's another test factor.

The `spacemacs-treemacs-face` messages still appear with both themes.

Toggling on debug on error with `SPC t D`, before opening treemacs, doesn't show a backtrace.

**Comment by Alexander-Miller** [comment] 2017-10-14 17:20
Lets wait until my patch is in melpa then and try again. You know you have the update when the value of `treemacs-version` is "1.11.7".
Also lets make clear whether this is a spacemacs thing or a treemacs thing: remove the layer and install treemacs with just use-package.

**Comment by duianto** [comment] 2017-10-14 17:56
I tried replacing the current `(defface treemacs-help-title-face` definition, with the one in commit:
Fix definition of the helpful hydra title face." https://github.com/Alexander-Miller/treemacs/commit/55ff2f25af5a36a364ccd34ba462bf54001a9de9

But there was no change.

So I removed the `treemacs` layer, restarted Spacemacs so that the `treemacs` layer was deleted.

I don't know how to install packages with `use-package`, so I just added `treemacs` to the additional-packages list. And now when I start `M-x treemacs` then the invalid face messages doesn't appear, when I navigate up or down in the `treemacs` list.

The invalid messages didn't appear in `emacs --quick`, `M-x package-initialize`, `M-x treemacs`, before I removed the `treemacs` layer, and installed the latest `treemacs-20171014.737` (Version: 1.11.7) package. And they don't appear now either when I try `emacs --quick` with the latest treemacs version.

So the source of the issue seems to be in the `treemacs` Spacemacs layer.

**Comment by duianto** [comment] 2017-10-14 18:03
Although replacing the face definition manually, probably confirmed that the update didn't solve it. 

I now also tested it by removing `treemacs` from the additional packages list, And added back the `treemacs` layer. And now the invalid face reference messages returned.

**Comment by Alexander-Miller** [comment] 2017-10-14 18:05
Did you recompile the file and then restart emacs? You need to do both to make sure the change is applied.

**Comment by duianto** [comment] 2017-10-14 18:20
Oh yeah, the file needs to be recompiled after making a manual change.

But now that the previous versions directory has been removed and the new version downloaded. Then it has been recompiled, because the `.elc` files show today's date and the time when the new version of the treemacs layers packages were downloaded.

Therefore the treemacs layer has been tested with the latest version.

**Comment by Alexander-Miller** [comment] 2017-10-14 18:31
What's the following code output?
```
(dolist (face 
         '(treemacs-directory-face
           treemacs-file-face
           treemacs-header-face
           treemacs-term-node-face
           treemacs-git-unmodified-face
           treemacs-git-modified-face
           treemacs-git-ignored-face
           treemacs-git-untracked-face
           treemacs-git-added-face
           treemacs-git-conflict-face
           treemacs-tags-face
           treemacs-help-title-face
           treemacs-help-column-face))
  (message "%s inherits %s" face (face-attribute face :inherit nil t)))
```

**Comment by duianto** [comment] 2017-10-14 18:40
```
treemacs-directory-face inherits font-lock-function-name-face
treemacs-file-face inherits default
treemacs-header-face inherits font-lock-constant-face
treemacs-term-node-face inherits font-lock-string-face
treemacs-git-unmodified-face inherits treemacs-file-face
treemacs-git-modified-face inherits font-lock-variable-name-face
treemacs-git-ignored-face inherits font-lock-comment-face
treemacs-git-untracked-face inherits font-lock-string-face
treemacs-git-added-face inherits font-lock-type-face
treemacs-git-conflict-face inherits error
treemacs-tags-face inherits font-lock-builtin-face
treemacs-help-title-face inherits spacemacs-transient-state-title-face
treemacs-help-column-face inherits font-lock-keyword-face
```

**Comment by Alexander-Miller** [comment] 2017-10-14 19:05
Found a likely culprit, maybe. `spacemacs//evil-state-face` would produce the invalid spacemacs-treemacs-face in the treemacs buffer. That still leaves a couple questions:
 * Its used in the modeline, but treemacs defines its own simple modeline. Why is this leading to errors for you?
 * What does your modeline in the treemacs buffer look like?
 * Whats the output of `(fboundp 'spaceline-install)`?

**Comment by duianto** [comment] 2017-10-14 19:16
I also just narrowed it down to the `treemacs-evil` package, by excluding both `treemacs-evil` and `treemacs-projectile`. That stopped the invalid face messages from appearing, then I tried adding them individually to the excluded packages list, and the invalid face messages only appears when `treemacs-evil` is installed.

This is what the modeline in treemacs looks like:

![emacs_2017-10-14_21-12-40](https://user-images.githubusercontent.com/13420573/31578596-9e969710-b124-11e7-92cc-e789e2fec640.png)

`(fboundp 'spaceline-install)` returns `t`

**Comment by duianto** [comment] 2017-10-14 21:10
I incorrectly assumed that the `spacemacs//evil-state-face`, function was defined in `treemacs-evil`. But now I see that it's a Spacemacs function that's defined here: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-modeline/funcs.el#L23

I added a test command: `(message "spacemacs//evil-state-face %s" (time-to-seconds))`  into that function, before `    (intern (format "spacemacs-%S-face" state))))`, but the test message only appears once in the messages buffer, before the invalid face reference message, which is repeated 5 times, when navigating in the treemacs window.

The only place I found where `spacemacs/evil-state-face` is called from, is in the 
`spacemacs-modeline/init-spaceline` function, that's defined here:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-modeline/packages.el#L50

I added a test message there as well, but it only gets called once when Spacemacs starts.

**Comment by duianto** [comment] 2017-10-14 22:08
I excluded the `spaceline` package, and the invalid face messages disappeared. The section comment above the `spacemacs//evil-state-face` function, says: `spaceline`. Therefore it probably only runs when the `spaceline` package is installed.

**Comment by Alexander-Miller** [comment] 2017-10-14 23:07
I could just define that face, but I doubt thats the right way to go. I assume there is some piece of configuration infrastructure that Im supposed to hook into. There is also the question of why I cannot reproduce the issue. Hopefully someone else can enlighten us on this.

In the meantime lets at least find out what the face is for. Eval the following code before starting treemacs. This face is large and ugly as sin, so youll have no trouble seeing where it is used.

```
(defface spacemacs-treemacs-face
  '((t :background "#0000ff" :foreground "#ff0000" :height 2.0 :box (:color "#000000" :line-width 5)))
  "Placeholder face.")
```

**Comment by duianto** [comment] 2017-10-14 23:11
![emacs_2017-10-15_01-11-07](https://user-images.githubusercontent.com/13420573/31580077-d36b040a-b145-11e7-9fe7-a10a93b9b678.png)

**Comment by duianto** [comment] 2017-10-15 00:05
No change, without the spacemacs-treemacs-face definition, the invalid face messages still appear.

**Comment by Alexander-Miller** [comment] 2017-10-15 00:09
@bmag can you help us out? You did say Id need to make an entry in `spacemacs-evil-cursors`. I didnt do it then because everything was already working as is, but theres a need for it anyway now.

**Comment by bmag** [comment] 2017-10-15 08:00
Currently, adding an entry to `spacemacs-evil-cursors` is the way to go. You have to add it to the `defvar`, because the faces are defined only during startup. The code is in the beginning of `spacemacs-bootstrap/init-evil`, but I can extract some of it to a "spacemacs/add-evil-cursor" function if you want (actually I prefer that myself, just didn't have the opportunity).

**Comment by bmag** [comment] 2017-10-15 08:19
How does #9734 look? With it, you'll only need to call `(spacemacs/add-evil-cursor "treemacs" "RoyalBlue1" '(hbar . 0))` from some init function in treemacs layer.

**Comment by Alexander-Miller** [comment] 2017-10-15 10:43
Looks good. Ill cherrypick your commit and open a PR for it.

**Comment by duianto** [comment] 2017-10-15 12:16
I tested the changes in PR: 
treemacs: add spacemacs-evil-cursors entry for treemacs. #9735 
and the invalid face messages are gone 👍

**Comment by bmag** [comment] 2017-10-15 14:23
Fix merged to develop, closing.

**Closed by bmag** 2017-10-15 14:23 UTC
Labels: - Bug tracker -, File browser, Hacktoberfest, Key Bindings
