### ISSUE TITLE
Problem about diminish-undo

### ISSUE THREAD

**Issue by tianyu-bai** [syl20bnr/spacemacs#8331] opened 2017-02-08 09:37 UTC
Hi,

I have a problem about diminish-undo function.

When I editing javascript, I want to see the source of company candidate, such as company-tern, company-etags, etc. As knows, the company minor-mode is diminished,  but after I execute diminish-undo company-mode,  nothing happens. 

Where's the problem?

**Comment by braham-snyder** [comment] 2017-02-10 07:22
<kbd>SPC</kbd><kbd>s</kbd><kbd>f</kbd> > `~/.emacs.d/` > `diminish company` showed me a line with:

```
layers/+completion/auto-completion/packages.el:84:18:      (spacemacs|diminish company-mode " ⓐ" " a")
```

I believe the issue is `spacemacs|diminish` – from the comments on [this PR](https://github.com/syl20bnr/spacemacs/pull/4696#issuecomment-173003190), I think `spacemacs|diminish` also prevents regular `diminish` from working on modes that have already been `spacemacs|diminish`ed. `spacemacs|diminish company-mode` should still work for you, I think.

That said, I think this isn't user-friendly (I'd been idly wondering for a while why certain diminish calls didn't seem to work for me). Would modifying `spacemacs|diminish` to prevent its precedence not be easy, or desirable? Would aliasing `diminish` to `spacemacs|diminish` (and `diminish-undo` to something like `spacemacs|diminish-undo`) just cause more confusion than it's worth?

(Side note: I think that running the above command in `~/.emacs.d/` – and `~/.emacs.d/elpa/` for that matter – maybe ought to be mentioned in the documentation or something? It wasn't clear to me how incredibly useful it is for troubleshooting Spacemacs until I stumbled upon a comment mentioning it – though that may or may not have been because I wasn't familiar with ag/rg.)

**Comment by braham-snyder** [comment] 2017-02-12 00:40
> we should provide a `spacemacs|diminish-undo` to cancel any previous diminish (regular or made with `spacemacs|diminish`).

can/should `diminish` and `diminish-undo` be modified in some way to direct users to their `spacemacs|..` variants? should we just append a note to their documentation?

**Comment by tianyu-bai** [comment] 2017-02-13 02:43
Thanks a lot. Expecting the fixing.

**Comment by syl20bnr** [comment] 2017-02-13 04:28
> can/should diminish and diminish-undo be modified in some way to direct users to their spacemacs|.. variants? should we just append a note to their documentation?

What we could do is to advice `diminish` functions to clean up the spacemacs data about minor mode lighters as well.
I have to think about it, expect a solution *soon*. :-)

**Comment by syl20bnr** [comment] 2017-04-13 04:29
Should be fixed in develop.
Documentation: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#restore-lighters

**Comment by tianyu-bai** [comment] 2017-06-08 03:47
I'm sorry about reply you so late. I have tried the develop branch, and thanks for the fix.

**Closed** 2021-08-24 02:24 UTC
Labels: Fixed in develop, Mode Line, Core, - Bug tracker -
