### ISSUE TITLE
Error when creating new layout

### ISSUE THREAD

**Issue by ilya-babanov** [syl20bnr/spacemacs#5567] opened 2016-03-22 20:27 UTC
#### Description
Hi! 
After recent changes in layouts logic it's impossible (for me) to create new layouts (`SPC-l-number`).
At every attempt to do that I get an error message.

#### Reproduction guide
- Start Emacs
- Try to create new layout (`SPC-l-number`)

*Observed behaviour:*
New layout isn't created. 
Instead you get this error message:
```
apply: Wrong number of arguments: (lambda (_new-persp-name) "Update and save current frame's eyebrowse workspace to its perspective.
Parameter _NEW-PERSP-NAME is ignored, and exists only for compatibility with
`persp-before-switch-functions'." (let* ((current-slot (eyebrowse--get (quote current-slot))) (current-tag (nth 2 (assoc current-slot (eyebrowse--get (quote window-configs)))))) (eyebrowse--update-window-config-element (eyebrowse--current-window-config current-slot current-tag))) (spacemacs/save-eyebrowse-for-perspective)), 2
```

*Expected behaviour:*
No errors, new layout is created.

*My investigation:*
It seems that problem with [`spacemacs/update-eyebrowse-for-perspective` function](https://github.com/syl20bnr/spacemacs/blob/82efa16dab91fcecb5996b91ed582e7ef5bc2855/layers/+spacemacs/spacemacs-layouts/funcs.el#L514). It is used as a hook for `persp-before-switch-functions`. But, according to [this code in persp-mode repository](https://github.com/Bad-ptr/persp-mode.el/blob/a425e09d0a9251971ea4f1fa748da773c3d3a11c/persp-mode.el#L1720-L1745), this hook is always called with two arguments, not one. And indeed - after adding second argument to `spacemacs/update-eyebrowse-for-perspective` everything is OK.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 82efa16)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx spacemacs-helm spacemacs-layouts
     (auto-completion :variables auto-completion-enable-sort-by-usage t)
     version-control git spell-checking
     (syntax-checking :variables syntax-checking-enable-tooltips nil)
     (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 60)
     org go csv html markdown javascript python ipython-notebook scheme racket clojure emacs-lisp common-lisp
     (haskell :variables haskell-enable-hindent-style "johan-tibell" haskell-enable-ghc-mod-support t)
     (ranger :variables ranger-parent-depth 3 ranger-cleanup-on-disable t ranger-show-dotfiles t ranger-show-preview t)
     (elfeed :variables url-queue-timeout 10 rmh-elfeed-org-files
             '("~/.emacs.d/private/core/elfeed.org"))
     core)
```

**Comment by TheBB** [comment] 2016-03-22 20:56
We don't use the official persp-mode package, but a fork. In this fork, that function is called with just one argument:

https://github.com/syl20bnr/persp-mode.el/blob/master/persp-mode.el#L1146

I can't reproduce your problem.

**Comment by ilya-babanov** [comment] 2016-03-22 21:13
Apparently I've had an official persp-mode package. I've deleted it from `elpa` directory and after restart spacemacs found that this package is missing and installed a new one. With newly installed package I can't reproduce this problem too.
I don't know why I've had an official persp-mode, but it's probably because of my own actions, not spacemacs.
Thanks!

**Comment by TheBB** [comment] 2016-03-22 21:22
Great, I'm closing this then.

**Closed by TheBB** 2016-03-22 21:22 UTC
Labels: - Bug tracker -, Spacemacs Layouts, To be reproduced

**Comment by JorisE** [comment] 2016-07-11 07:20
I know this is close, but I just ran in to the same problem after a freshly installed head of develop (f1247c8d189e5637b6c128f97fe4fb008b718940) so it may be good to keep this as reference.
Could it be that persp-mode is pulled by another package?
