### ISSUE TITLE
Python docstring highlighting is broken

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#6501] opened 2016-07-05 14:28 UTC
### Description :octocat:
Python highlighting is broken (docstring comments are no longer correctly
delimited)

Picture here: http://d.pr/i/L16o/X5zzP5oQ

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file with docstrings

#### Observed behaviour :eyes: :broken_heart:
Sometimes characters like `'` in the docstrings will cause the comment
highlighting to bleed into the following sections.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. a650877)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go sql nginx unscroll auto-completion xkcd emacs-lisp git yaml github javascript html markdown extra-langs python ruby org osx python django go syntax-checking spell-checking lua colors spacemacs-layouts vimscript spacemacs-helm
    (version-control :variables version-control-diff-tool 'diff-hl)
    (c-c++ :variables c-c++-enable-clang-support t)
    (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by cpaulik** [comment] 2016-07-05 18:13
Sometimes it takes a second to update the syntax highlighting but I've never seen it stay that way.

Can you reproduce this with `emacs -Q`? If so then please report it as an emacs bug.

**Comment by darkfeline** [comment] 2016-07-06 02:24
I ran into this as well.  Undoing my most recent package update fixed it, so I assume it's some upstream bug, but I haven't looked into it.

**Comment by microamp** [comment] 2016-07-06 11:34
Experiencing the same issue. Rolling back packages but I haven't had much luck yet.

**Comment by synic** [comment] 2016-07-06 14:24
Yeah, rolling back did not help.  It doesn't seem to be happening when I do `emacs -Q`

**Comment by microamp** [comment] 2016-07-06 22:05
@darkfeline 

Do you remember what packages you rolled back that fixed the issue for you?

**Comment by darkfeline** [comment] 2016-07-07 06:20
Here are the packages from a rollback that fixed the issue

``` emacs-lisp
(setq update-packages-alist
      (quote
       ((ag . "ag-20160321.1606")
        (avy . "avy-20160620.1240")
        (counsel . "counsel-20160630.140")
        (elfeed . "elfeed-20160619.613")
        (git-gutter . "git-gutter-20160610.852")
        (helm . "helm-20160629.116")
        (helm-core . "helm-core-20160627.324")
        (hydra . "hydra-20160616.24")
        (info+ . "info+-20151231.1403")
        (ivy . "ivy-20160630.857")
        (js2-mode . "js2-mode-20160626.2025")
        (magit . "magit-20160629.1156")
        (multiple-cursors . "multiple-cursors-20160616.1404")
        (mwim . "mwim-20150822.1236")
        (neotree . "neotree-20160306.730")
        (org-plus-contrib . "org-plus-contrib-20160627")
        (powerline . "powerline-20160601.724")
        (smartparens . "smartparens-20160619.322")
        (spacemacs-theme . "spacemacs-theme-20160625.847")
        (use-package . "use-package-20160614.803")
        (web-mode . "web-mode-20160628.1345")
        (which-key . "which-key-20160617.542")
        (xterm-color . "xterm-color-20160401.2025"))))
```

**Comment by cpaulik** [comment] 2016-07-07 07:38
I think I've narrowed this down to `xterm-color`. Disabling the shell layer fixed it and then rolling back only `xterm-color` worked for me.

**Comment by microamp** [comment] 2016-07-07 08:05
@cpaulik Thanks! I've added `xterm-color` to `dotspacemacs-excluded-packages` and so far so good. I'll test it a bit more. I'm curious to know how it got broken...

**Comment by cpaulik** [comment] 2016-07-07 08:11
I think it is because of the setting of `(setq font-lock-unfontify-region-function 'xterm-color-unfontify-region)` which is a strange setting for a package since it applies everywhere. Reported this upstream https://github.com/atomontage/xterm-color/issues/7 let's see if they know why this could happen.

**Comment by atomontage** [comment] 2016-07-07 23:53
This shouldn't be related to font-lock-unfontify-region-function (which is configured as intended), it's caused by a commit I recently merged that switched font-lock-syntactic-keywords to syntax-propertize-function thinking the 2 are equivalent (they are not).

The current master of xterm-color should fix the problem.

**Comment by cpaulik** [comment] 2016-07-08 08:15
This is fixed upstream and can be closed.

**Closed** 2016-07-08 13:24 UTC
Labels: - Bug tracker -, Python, Reported upstream

**Comment by d12frosted** [comment] 2016-07-08 14:28
@atomontage thank you for the quick fix!
