### ISSUE TITLE
broken markdown editing 

### ISSUE THREAD

**Issue by svalaskevicius** [syl20bnr/spacemacs#5382] opened 2016-03-06 21:05 UTC
#### Description
When editing markdown file, even in the insert mode (vim kb), pressing m opens a menu for markdown actions instead of writing `m`.

#### Reproduction guide
- Start Emacs
- open a *.md file
- type text that includes letter `m`

*Observed behaviour:*
when `m` is pressed a menu appears for markdown actions

*Expected behaviour:*
letter `m` to be written

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.12
- Spacemacs branch: master (rev. 531ec8e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx php lua markdown shell
     (git :variables git-gutter-use-fringe t git-enable-github-support t)
     syntax-checking auto-completion haskell themes-megapack html scala)
```

**Comment by StreakyCobra** [comment] 2016-03-06 23:18
I can't reproduce this, not on `develop` nor on `master`.

**Comment by svalaskevicius** [comment] 2016-03-07 08:39
Any tips of what could I look at or send to you for more info?

**Comment by svalaskevicius** [comment] 2016-03-07 08:41
The menu is the same as I get to with spc m in normal mode, just that it's also activated when simply typing text in insert mode too. So there has to be some keybinding doing this.. Somewhere.. And I don't know where to look for it

**Comment by StreakyCobra** [comment] 2016-03-07 08:59
You can try updating Spacemacs to 0.105.13, to update your packages (`[Update packages]` on the `*spacemacs*` buffer) and restart. If it doesn't work you can tell us to what the letter `m` is bound to with `M-m h d k m` (in insert mode). Otherwise I don't have further ideas for now, maybe waiting to see if someone has the same problem as you.

**Comment by svalaskevicius** [comment] 2016-03-07 11:53
updated, issue still here, the key combination didnt work, but `M-x` describe-keybindings did, 

showing this:

<img width="452" alt="screen shot 2016-03-07 at 11 51 22" src="https://cloud.githubusercontent.com/assets/893660/13568723/2487a08c-e45b-11e5-99d3-fc7926277f53.png">

**Comment by StreakyCobra** [comment] 2016-03-07 12:32
What is the value of `dotspacemacs-emacs-leader-key` in your `.spacemacs`?

**Comment by svalaskevicius** [comment] 2016-03-07 12:49
`dotspacemacs-emacs-leader-key " "`

**Comment by svalaskevicius** [comment] 2016-03-07 12:50
I guess thought that thats my answer :D what is the default value? I don't remember changing this although my .spacemacs file is based on an older version

**Comment by StreakyCobra** [comment] 2016-03-07 12:54
You guessed it :-) Here it is:

    dotspacemacs-emacs-leader-key "M-m"

`SPC f e D` for helping you keeping your `.spacemacs` up to date.

**Comment by svalaskevicius** [comment] 2016-03-07 12:55
thanks!

**Comment by StreakyCobra** [comment] 2016-03-07 13:11
You're welcome. I'm closing the issue as it has been addressed.

**Closed by StreakyCobra** 2016-03-07 13:11 UTC
Labels: - Bug tracker -, Markdown, Not a bug 8-), User Configuration
