### ISSUE TITLE
wrong-type-argument in command describe-keymap

### ISSUE THREAD

**Issue by demokritos** [syl20bnr/spacemacs#13302] opened 2020-02-25 13:49 UTC
#### Description :octocat:
Command `describe-keymap` results in an error:
```
In ‘describe-keymap History’ source: ‘#[0 \304\302\300\305\303$\211\205�\306\307\310\301""\207 [nil spacemacs-buffer-mode-map keymap-name-history t helm-comp-read-get-candidates nil delete  helm-cr-default] 6]’ 
 (wrong-type-argument listp keymap-name-history)
```

#### Reproduction guide :beetle:
- Start Emacs
- Type `M-x describe-keymap`
- Error

*Observed behaviour:* :eyes: :broken_heart:
Just error

*Expected behaviour:* :heart: :smile:
I should be asked a keymap.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 733a3a819)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment] 2020-02-25 21:31
@demokritos I have tried to reproduce your issue but `SPC SPC describe-keymap` works flawlessly on my PC. I am on linux on latest develop. Do you have some specific user config code run in you dotfile which could fail and abort the loading process?

Please double check your message buffer for error messages. If this does not help please also test with the latest stable emacs release 26.3.

Here are my system details:
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f44047ccd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-collapse-dirs 3 treemacs-use-git-mode 'deferred)
 emacs-lisp helm multiple-cursors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by demokritos** [comment] 2020-02-25 21:49
I am using emacs-git build on Arch Linux. It seems that there is a mismatch with the latest changes to emacs. This issue is in 28.0.50.140343 and over, but not in 28.0.50.139999.
But when I enter the command in the vanilla emacs, this issue is not seen.

**Comment by smile13241324** [comment] 2020-02-25 22:59
Great, so if this is caused by emacs please, go ahead and close the issue.

**Closed** 2020-02-25 23:07 UTC
