### ISSUE TITLE
SPC h I shows blank github page

### ISSUE THREAD

**Issue by simendsjo** [syl20bnr/spacemacs#5530] opened 2016-03-18 10:40 UTC
This text shows when I open a bug report
```
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs.
You can delete this message to start typing.
```

Following this message generates the following url, but the page is just blank
```
https://github.com/syl20bnr/spacemacs/issues/new?body=%3CPLEASE%20REPLACE%20ALL%20UPPERCASE%20EXPRESSIONS%20AND%20DELETE%20THIS%20LINE%3E%0D%0A%23%23%23%23%20Description%0D%0ADESCRIPTION%20OF%20THE%20PROBLEM%0D%0A%0D%0A%23%23%23%23%20Reproduction%20guide%0D%0A-%20Start%20Emacs%0D%0A-%20REPRODUCTION%20STEPS%0D%0A%0D%0A*Observed%20behaviour:*%0D%0ADESCRIPTION%20OF%20THE%20OBSERVED%20BEHAVIOUR%0D%0A%0D%0A*Expected%20behaviour:*%0D%0ADESCRIPTION%20OF%20THE%20EXPECTED%20BEHAVIOUR%0D%0A%0D%0A(%LAST_KEYS%)%0D%0A%0D%0A%23%23%23%23%20System%20Info%0A-%20OS:%20windows-nt%0A-%20Emacs:%2025.0.50.1%0A-%20Spacemacs:%200.105.14%0A-%20Spacemacs%20branch:%20master%20(rev.%20a298a5a)%0A-%20Graphic%20display:%20t%0A-%20Distribution:%20spacemacs%0A-%20Editing%20style:%20vim%0A-%20Completion:%20helm%0A-%20Layers:%0A%60%60%60elisp%0A(auto-completion%20better-defaults%20emacs-lisp%20git%20fsharp%20markdown%20org%20mu4e%20spell-checking%20syntax-checking%20version-control)%0A%60%60%60%0A%0D%0A%0D%0A%23%23%23%23%20Backtrace%0D%0A%60%60%60%0D%0ABACKTRACE%20IF%20RELEVANT%0D%0A%60%60%60%0D%0A
```

**Comment by StreakyCobra** [comment] 2016-03-18 10:49
Closing as duplicate of #5521

**Closed by StreakyCobra** 2016-03-18 10:49 UTC
