### ISSUE TITLE
Autocomplete not working in PHP or web-mode

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#7125] opened 2016-09-15 14:13 UTC
Hello,

Got an issue with auto-complete. Nothing work : no yas-snippet, no variable completion, nothing. Except for some Gtags stuff.

Same problem using web-mode.

When I open a php file, i got this error in *message*, but i dont know if it's related : 

```
File mode specification error: (void-function ert-set-test)
```

My private folder can be found here : https://github.com/phenix-factory/config-spacemacs
I tested using the "develop" branch, but nothing change.

Anyone know what I m missing ?

**Comment by TheBB** [comment] 2016-09-15 15:26
Try `SPC tD` then open a php file. Copy the backtrace here. In the meantime can you provide us with the output of `SPC hds`.

**Comment by phenix-factory** [comment] 2016-09-16 06:57
Didn't had the problem on an other computer, so I just copied the .emacs.d and now it's working.
I copied the "bad" .emacs.d so i can test it and get you the bug report you need, i just need some time to do it.

Thank you for your help.

**Comment by phenix-factory** [comment] 2016-09-17 06:58
#### Description
auto-complete. Nothing work : no yas-snippet, no variable completion, nothing. Except for some Gtags stuff.

#### Reproduction guide
- Start Emacs
- All updated
- Open a php file and try to autocomplete some variables

*Observed behaviour:*
Autocomplete doesn't work except for some Gtags

*Expected behaviour:*
Autocomplete working as usual :)


#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking shell-scripts php php-mby html javascript gtags yaml finance colors dash)
```


#### Backtrace

I dont know why, i can t copy more ...
```
Debugger entered--Lisp error: (void-function ert-set-test)
  ert-set-test(test-spip-group-lang-modules [cl-struct-ert-test test-spip-group-lang-modules "lang module classification." #[nil "\306\307\310!\311D\312\313\314\216\315	\"\211)\204
```

**Comment by TheBB** [comment] 2016-09-17 09:04
> I dont know why, i can t copy more ...

Can you screenshot? It's kind of important to find where it's coming from.

**Comment by phenix-factory** [comment] 2016-09-17 12:16
Yes, sorry !

![selection_082](https://cloud.githubusercontent.com/assets/1810149/18608139/26bcf748-7ce1-11e6-9879-cfe27a9fa6d5.png)

**Comment by bmag** [comment] 2016-09-17 13:38
Error stems from [spip-mode](https://github.com/bystrano/spip-mode). It [uses `ert-deftest`](https://github.com/bystrano/spip-mode/blob/8a33a7242c51c5e9e6189d54ce8c394b9480535d/spip-mode.el#L178) but doesn't require `ert`. `ert-deftest` is an auto-loaded macro that wraps `ert-set-test`, which isn't auto-loaded. Probably, after compilation `spip-mode.elc` contains a call to `ert-set-test` and not `ert-deftest`, and doesn't contain a call to `(require 'ert)`, hence the error when loading `spip-mode`.

A simple fix is to add `(require 'ert)` at the beginning of `spip-mode.el`. Another option is to move the test to a separate test file. Oh, and the last line should be `(provide 'spip-mode)`, not `(provide spip-mode)`.

I was able to reproduce the error by adding `(spip-mode :location (recipe :fetcher github :repo "bystrano/spip-mode"))` to `dotspacemacs-additional-packages` and manually evaluating  `(load "spip-mode")`.

@phenix-factory can you please report the bug upstream?

**Comment by TheBB** [comment] 2016-09-17 13:41
Yes, everything @bmag says is accurate. However how did spip-mode get into your Spacemacs install? I can't find any reference to it anywhere.

**Comment by TheBB** [comment] 2016-09-17 13:44
Okay it's part of your own config. https://github.com/phenix-factory/config-spacemacs/blob/master/php-mby/packages.el#L12-L13

Since this package is not included with Spacemacs, I'll close this.

**Closed by TheBB** 2016-09-17 13:44 UTC
Labels: - Bug tracker -, Auto-completion, Php, Should report upstream

**Comment by phenix-factory** [comment] 2016-09-17 13:50
Thank you @bmag ! Now i know what to do.

> P.S. being able to look at your config really helped me to identify the error, so thank you

No one can fix a bug without the code :), thank you for your work !

> Yes, everything @bmag says is accurate. However how did spip-mode get into your Spacemacs install? I can't find any reference to it anywhere.

[SPIP](http://www.spip.net/) is a french CMS we use, and we have created some tools to handle it, like spip-mode or a modified version of web-mode.
Ofc it s not a part of Spacemacs.
