### ISSUE TITLE
Warnings after package updates

### ISSUE THREAD

**Issue by topecongiro** [syl20bnr/spacemacs#8800] opened 2017-04-26 10:20 UTC
#### Description :octocat:
spacemacs emits warnings after updating packages.

#### Reproduction guide :beetle:
- Start Emacs
- Update Packages

*Observed behaviour:* :eyes: :broken_heart:
spacemacs emits the following warnings:
```
Error (use-package): pdf-tools :config: No executable `epdfinfo' found
Error (use-package): slime :config: Cannot open load file: No such file or directory, slime-company
```

*Expected behaviour:* :heart: :smile:
spacemacs should complete pacakges update without emitting error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ruby c-c   common-lisp go html latex python rust shell themes-megapack yaml ivy auto-completion emacs-lisp git gtags markdown org pdf-tools
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by LdBeth** [comment] 2017-05-01 07:03
Sometimes `use-packages` throws errors because some require dependencies are not installed before the congratulations are called. As specific to your problem, slime-company wasn't  installed before the configuration of silme, which calls a function defined in slime-company. Who's fault? Well, some layers do not optimize the order of loading packages and some error messages will be thrown only when the packages are updated. However, when the layers do such a optimize to have a "smooth" update, Spacemacs may get slowed down.

Thou I know it's annoying, it is not a big deal as long as those errors are not reproduced after restart Emacs. And this problem might not be addressed in short run.

I wish this explains to you about why that thing happened.

Consider to add an "as expected" label to this issue.

**Comment by topecongiro** [comment] 2017-05-01 07:38
@LdBeth Thank you for your explanation!

**Closed** 2018-01-22 04:20 UTC
