### ISSUE TITLE
dotspacemacs-command-key not working on splash screen

### ISSUE THREAD

**Issue by jasonkuhrt** [syl20bnr/spacemacs#1605] opened 2015-05-16 03:35 UTC
This customization to a default setting is no longer working on the splash screen since upgrading to `0.101.4`.
```cj
   ;; The command key used for Evil commands (ex-commands) and
   ;; Emacs commands (M-x).
   ;; By default the command key is `:' so ex-commands are executed like in Vim
   ;; with `:' and Emacs commands are executed with `<leader> :'.
   dotspacemacs-command-key ";"
```

**Comment by syl20bnr** [comment] 2015-05-17 04:13
I cannot reproduce it on `master` and `develop`. Do you have an error displayed ?

**Comment by TheBB** [comment] 2015-08-27 10:08
I can't reproduce this either. Since this is two versions ago and @jasonkuhrt has not replied, I'm closing this.

**Closed by TheBB** 2015-08-27 10:08 UTC
