### ISSUE TITLE
:disabled-for is not respected when running emacs with -file

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#2882] opened 2015-09-04 09:06 UTC
Following #2861. 

**Prerequisites**

Make sure that you are at least on 8adc82d and that `auto-completion` mode is disabled for `org` mode. 

```
(setq dotspacemacs-configuration-layers 
'((auto-completion :disabled-for (org))))
```

Also make sure that `emacs` in terminal runs new instance of emacs instead of running `emacsclient`.

**The problem**

Run following command in terminal.

```
$ emacs path/to/file.org
```

Notice that `company-mode` is enabled despite the fact `auto-completion` layer was disabled for `org` layer. It is expected that company-mode` is not enabled. 

**Additional notes**

If you alternate file - `company-mode` is disabled. If you run emacs first and then use `find-file` to open `org` file - everything is fine.

Also, it's not the problem with terminal emacs. You can also run GUI emacs passing it path to `org` file - the problem will be the same.

**Comment by TheBB** [comment] 2015-09-04 09:09
Ah, I see now where you're doing it wrong. It was changed to not require a list. I guess @syl20bnr forgot to mention that in the other issue.

```lisp
(setq dotspacemacs-configuration-layers 
 '((auto-completion :disabled-for org)))
```

Now it should work for you.

The reason it didn't work for me is because I had forgotten to pull last night's changes to my dotfile on my work computer.

**Comment by d12frosted** [comment] 2015-09-04 09:16
Ha. You're right. Works now. 

But it's puzzling, because with list it works when I run emacs first and only then find file. But it doesn't work when I start emacs with `find-file` option. Puzzling.

Well, thanks for the tip anyway.

**Comment by TheBB** [comment] 2015-09-04 09:18
Now that I can't reproduce, and this time I'm sure I did it right.

Anyway, I will close this then. :-)

**Closed by TheBB** 2015-09-04 09:18 UTC

**Comment by syl20bnr** [comment] 2015-09-04 11:06
@d12frosted sorry, I put a link to the commit where it is mentioned that this is no longer a list, I should have mentioned it explicitly to avoid misunderstanding.

**Comment by d12frosted** [comment] 2015-09-04 11:07
@syl20bnr Ah, it's my bad, so never mind. I didn't look into commit message.
