### ISSUE TITLE
"M-l" shortcuts overwrite lowercase behavior (default in emacs) with markdown-demote

### ISSUE THREAD

**Issue by zyxue** [syl20bnr/spacemacs#10640] opened 2018-05-02 18:21 UTC
May consider a different key binding, the code line:
https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Blang/markdown/packages.el#L155

Similarly, 

`M-l` overwrites the default behavior of cutting a paragraph,

https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Blang/markdown/packages.el#L154

**Comment by kccai** [comment] 2018-05-08 08:48
How about only enabling the following keybindings in evil **normal** and evil **insert** mode?
```
(kbd "M-h") 
(kbd "M-j") 
(kbd "M-k") 
(kbd "M-l") 
```
with
```
(mapc (lambda (state)
        (evil-define-key state markdown-mode-map
          (kbd "M-h") 'markdown-promote
          (kbd "M-j") 'markdown-move-down
          (kbd "M-k") 'markdown-move-up
          (kbd "M-l") 'markdown-demote))
      '(normal insert))
```
You can still use the "M-l" and "M-k" key bindings in the emacs editting mode by pressing `C-z`.

**Comment by zyxue** [comment] 2018-05-08 15:01
It reminds me of another confusion. What does `C-z` do, please? I used to use it to bring emacs to the background, which was very handy.

**Comment by kccai** [comment] 2018-05-09 14:32
@zyxue  If you use spacemacs with the vim editing style in GUI Emacs (not terminal Emacs), then `C-z` is bound to the command `evil-emacs-state`, which is used to switch between the vim and the emacs editing style.

**Comment by zyxue** [comment] 2018-05-18 15:43
Sorry for late response, @kccai. I've mainly been using holy mode, which is likely why I am a bit confused here.

**Comment by syl20bnr** [comment] 2018-06-06 05:18
Closed as duplicate of https://github.com/syl20bnr/spacemacs/issues/9715

**Closed by syl20bnr** 2018-06-06 05:18 UTC
Labels: - Bug tracker -, Duplicate ☝, Emacs style, Key Bindings, Markdown
