### ISSUE TITLE
In *helm-ag-edit* buffer,  press c-c c-k will issue error message

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#1856] opened 2015-06-05 07:40 UTC
`ad-Advice-select-window: Wrong type argument: window-live-p, #<window 369>`

And the *helm-ag-edit* buffer can't be closed.

**Comment by tuhdo** [comment] 2015-06-05 07:43
You should report to [helm-ag](https://github.com/syohex/emacs-helm-ag) and include a reproducible recipe.

**Comment by andyque** [comment] 2015-06-05 07:47
@tuhdo  I have installed `helm-ag` in a brand new Emacs config and it's ok.

**Comment by andyque** [comment] 2015-06-05 07:52
@tuhdo  I'm using the latest develop branch of spacemacs. Do you have this issue on your side?

**Comment by andyque** [comment] 2015-06-05 07:55
@tuhdo 

`
ad-Advice-select-window is a compiled Lisp function.

(ad-Advice-select-window AD--ADDOIT-FUNCTION WINDOW &optional NORECORD)

After-advice `powerline-select-window':
makes powerline aware of window changes

After-advice `evil'.`

I think this issue could only reproduce in spacemacs..

**Comment by syl20bnr** [comment] 2015-06-05 12:58
@andyque did you find a work-around to close the buffer ? I think I encountered this bug once and it was ver yannoying because afterwards I was not able to use the editing feature of `helm-ag` anymore (had to restart emacs).

**Comment by andyque** [comment] 2015-06-05 15:33
@syl20bnr  Very strange behavior, I can't reproduce it now...  If I can reproduce it in the future, I will try to find a work-around to this issue.

**Comment by andyque** [comment] 2015-06-05 15:37
@syl20bnr BTW,  I have upgraded all of my packages to the latest MELPA version. I'm not sure whether the issue is gone or not.

**Comment by StreakyCobra** [comment] 2015-11-13 20:30
As nobody reported this issue last 5 months, I assume it has been solved. I'm closing it, but feel free to open a new one in case of troubles :relaxed:

**Closed by StreakyCobra** 2015-11-13 20:30 UTC
Labels: bug :-(, Helm

**Comment by zilongshanren** [comment] 2015-11-14 00:33
@StreakyCobra  thanks
