### ISSUE TITLE
Error with lsp-ui-imenu: Wrong type argument: integer-or-marker-p

### ISSUE THREAD

**Issue by spacegoing** [syl20bnr/spacemacs#16051] opened 2023-06-23 15:14 UTC
#### Description :octocat:

While working with Python in Spacemacs using the LSP backend, I
encountered an error when trying to use `lsp-ui-imenu`. After
activating `lsp-ui-imenu` and pressing `RET` to jump to a symbol, I
receive the error message `Wrong type argument:
integer-or-marker-p`.

#### Reproduction guide :beetle:

- Open a Python file.
- Enable lsp-mode and lsp-ui-imenu (if not already enabled).
- Activate lsp-ui-imenu (e.g., SPC m i in the Python file).
- Attempt to jump to a symbol using RET.

*Observed behaviour:* :eyes: :broken_heart:

receive the error message

``` text
funcall-interactively: Wrong type argument: integer-or-marker-p,
#<overlay from 2868 to 2879 in doe_net.py> [3 times]
```

*Expected behaviour:* :heart: :smile:

I expected lsp-ui-imenu to navigate to the selected symbol in the Python file without error.

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c6c508254)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org sdefaults sdired sorg c-c++ python
      (python :variables python-backend 'lsp python-lsp-server 'pylsp python-formatter 'yapf)
      html yaml sql csv docker
      (latex :variables latex-enable-auto-fill t latex-enable-folding t)
      semantic lsp spell-checking syntax-checking)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

**Comment by stskyblade** [comment] 2023-06-26 02:21
I have tested it with same develop (rev. https://github.com/syl20bnr/spacemacs/commit/c6c508254f4552549f70af5d131dc7882f0d35d3) and layers as yours. Everything seems OK. I can jump to any symbol without error. I can't reproduce your bug. I don't have `sdefaults, sdired, sorg` layers.

Maybe you can remove those three layers and try again.
Or you can debug it by youself. You can use `toggle-debug-on-error` to find out what's going wrong.

**Comment by stskyblade** [comment] 2023-06-26 13:16
Will be fixed on https://github.com/emacs-lsp/lsp-ui/pull/753

This is because Semantic layer conflicts with the lsp-ui package. You can remove Semantic layer to solve this question.

**Comment by smile13241324** [comment] 2023-07-10 14:47
I have tested this on latest develop and this seems to be fixed already upstream. Please reopen if the issue still appears on latest develop.

For reference here is my config section:
```elisp
     semantic
     (python :variables
             python-backend 'lsp
             python-lsp-server 'pylsp
             python-test-runner 'pytest
             python-formatter 'lsp
             python-format-on-save t
             python-save-before-test t
             python-sort-imports-on-save t)
```
I have used the following tiny test file:
```python
print("asdf")
print("asdf")
print("asdf")
print("asdf")
print("asdf")
print("asdf")
print("asdf")
print("asdf")
print("asdf")
print("asdf")

def my_func():
    print("something")

my_func()
```
I have made sure that I can jump from the name of `my_func` to its definition as well as that I can activate `lsp-imenu` with `SPC m g M`.

**Closed as completed by smile13241324** 2023-07-10 14:47 UTC

**Comment by spacegoing** [comment] 2023-07-10 14:56
@smile13241324 just confim it is fixed for me too.

**Comment by spacegoing** [comment] 2023-07-10 14:57
@smile13241324 yet my org-toc-show stops working now ToT
