### ISSUE TITLE
Magit status commit (c c) error in terminal emacs

### ISSUE THREAD

**Issue by codedmart** [syl20bnr/spacemacs#4036] opened 2015-12-02 12:55 UTC
This just started a day or two ago. When I am in magit status `SPC g s` and stage some files/hunks, if I try to commit `c c` it fails and I get an error in the *magit-process* buffer:

```
  1 git ... commit --
Waiting for Emacs
*ERROR*: Args out of range: [], 0
error: There was a problem with the editor '/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.13/bin/emacsclient --socket-name=/var/folders/8w/n_txhbn945j9gxp6bbz2nhkhr0000gn/T/emacs501/server'.
Please supply the message using either -m or -F option.
```

**Comment by StreakyCobra** [comment] 2015-12-02 12:57
Have you tried to update the package to see if it goes away? Or was it because a packages update?

**Comment by codedmart** [comment] 2015-12-02 12:59
Sorry forgot to mention that I am on `develop` branch and it start a day or two ago from a package update. I did revert back to `master` and can confirm that I can `c c` fine there. I just did another package update right before I reported this and the problem still persists in `develop`. Things do work as expected from GUI emacs.

**Comment by StreakyCobra** [comment] 2015-12-02 13:14
Oh, actually I can confirm it on linux too.

```text
  1 git … commit --
Waiting for Emacs...
*ERROR*: Args out of range: [], 0
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server24611'.
Please supply the message using either -m or -F option.
```

***** 

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: contrib/bepo (rev. 40a63b9)
- Distribution: spacemacs
- Layers:
```elisp
(streakycobra asciidoc auto-completion better-defaults c-c++ colors dockerfile deft emacs-lisp emoji erc ess evil-cleverparens extra-langs finance git github haskell html ipython-notebook javascript latex markdown ocaml org pandoc python ranger restclient semantic shell shell-scripts
              (spell-checking :variables spell-checking-enable-auto-dictionary t)
              syntax-checking themes-megapack theming typography version-control yaml bepo)
```

**Comment by nixmaniack** [comment] 2015-12-02 14:25
High Priority! Any known workarounds except from dropping to shell?

**Comment by StreakyCobra** [comment] 2015-12-02 14:37
Does it happen with raw emacs with just magit?

**Comment by justbur** [comment] 2015-12-02 15:36
Those don't look like backtraces. Has anyone tried to get one yet?

**Comment by justbur** [comment] 2015-12-02 15:38
there was a recent change to with-editor here https://github.com/magit/magit/commit/310b5fa6387c18056a365409b9008092d4296006

**Comment by StreakyCobra** [comment] 2015-12-02 15:41
@justbur There is no backtrace

**Comment by justbur** [comment] 2015-12-02 15:43
Is this only with the daemon?

**Comment by StreakyCobra** [comment] 2015-12-02 15:45
`*Messages*`:
```text
(No files need saving)
SPC g s
Type C-h i to view popup manual, ? to describe an argument or action.
Running git commit --
(No files need saving)
Running git commit --
There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server14029'. ... [See buffer *magit-process: .spacemacs.d for details]
(No files need saving)
There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server14029'. ... [See buffer *magit-process: .spacemacs.d for details]
Reverting (up to) 1 file-visiting buffer(s)...
(No buffers need to be reverted)
```

`*magit-process: …*`:
```text
  1 git … commit --
Waiting for Emacs...
*ERROR*: Args out of range: [], 0
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server14029'.
Please supply the message using either -m or -F option.
```

`SPC t D` changes nothing. I tried with `emacs -nw`, so not in daemon mode, I even stopped it to be sure.

**Comment by justbur** [comment] 2015-12-02 15:47
looks like a magit bug to me

**Comment by StreakyCobra** [comment] 2015-12-02 15:48
For me too, it's why I asked if someone can try to reproduce it without Spacemacs to be sure before reporting upstream :-)

**Comment by justbur** [comment] 2015-12-02 15:59
@StreakyCobra you still get a reference to `emacsclient` when you use `emacs -nw`? That doesn't make sense

**Comment by StreakyCobra** [comment] 2015-12-02 16:15
Yes, even with a fresh `.spacemacs`. Maybe something related to my shell configuration.

**Comment by codedmart** [comment] 2015-12-02 16:17
I tried replacing `with-editor.el` with a earlier version but still see the same problem. I also get a reference to `emacsclient` when using `emacs -nw`.

**Comment by codedmart** [comment] 2015-12-02 16:18
@justbur Can you not reproduce this error? Is all working fine for you in terminal emacs?

**Comment by justbur** [comment] 2015-12-02 16:19
I use the gui version and haven't seen any changes

**Comment by codedmart** [comment] 2015-12-02 16:21
It is only related to the terminal. I don't have the problem in the gui version.

**Comment by justbur** [comment] 2015-12-02 16:32
> It is only related to the terminal. I don't have the problem in the gui version.

That suggests to me that it's something with the environment

**Comment by StreakyCobra** [comment] 2015-12-02 16:40
@codedmart has it on OS X, @justbur has it on Windows, I have it on Linux, all with different setups, so it looks like an upstream bug.

**Comment by codedmart** [comment] 2015-12-02 17:24
@justbur @StreakyCobra a `git bisect` resulted in 7e0d8f2d32fb8275a8fc044bb1396a7ef1664b78.

**Comment by codedmart** [comment] 2015-12-02 17:25
That seems unrelated to me, but anyone have some ideas from here?

**Comment by codedmart** [comment] 2015-12-02 17:39
Nevermind because of a different error my bisect failed. Let me try again.

**Comment by codedmart** [comment] 2015-12-02 17:49
OK did a new `git bisect` and a19c0f3d2457912e80a7934e8060096a90a733c8 appears to be the culprit. I manually confirmed this as well. The commit just before a19c0f3d2457912e80a7934e8060096a90a733c8 is working as expected.

**Comment by StreakyCobra** [comment] 2015-12-02 17:58
This one will be reverted by https://github.com/syl20bnr/spacemacs/pull/4025

**Comment by StreakyCobra** [comment] 2015-12-02 17:59
Can you try again with the patch applied?

**Comment by codedmart** [comment] 2015-12-02 18:00
@StreakyCobra @justbur Yes #4025 fixes the issue. Shall I close this now or does anyone need it open?

**Comment by StreakyCobra** [comment] 2015-12-02 18:01
:+1: Let it open until the PR is merged :-) We will take care of closing it

**Comment by justbur** [comment] 2015-12-02 18:46
That's so strange

**Comment by StreakyCobra** [comment] 2015-12-04 09:22
@codedmart It should be fine now, can you test it?

**Comment by codedmart** [comment] 2015-12-07 13:06
@StreakyCobra sorry got busy at the end of last week. I updated this morning and everything seems to be working as expected. Thanks!

**Comment by StreakyCobra** [comment] 2015-12-07 13:07
:+1:

**Closed** 2016-01-04 08:36 UTC
Labels: bug :-(, Git
