### ISSUE TITLE
php-extras package miss

### ISSUE THREAD

**Issue by netroby** [syl20bnr/spacemacs#2878] opened 2015-09-04 00:26 UTC
installing (php): php-extras... [1/1]
Package php-extras is unavailable. Is the package name misspelled?

so we can not load php-extras package,

**Comment by robbyoconnor** [comment] 2015-09-04 00:28
Seriously, Duplicate of [all of these](https://github.com/syl20bnr/spacemacs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+php)

**Comment by robbyoconnor** [comment] 2015-09-04 00:29
Also report your version number...which you didn't do...for example are you on `master` or `develop`?

**Comment by netroby** [comment] 2015-09-04 00:30
I am using master

git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d

**Comment by robbyoconnor** [comment] 2015-09-04 00:32
@netroby, 

The fix is to use `develop`. 

`cd ~/.emacs.d && git checkout develop && rm -de elpa/`

**Comment by robbyoconnor** [comment] 2015-09-04 00:32
@netroby, 

The fix is to use `develop`. 

`cd ~/.emacs.d && git checkout develop && rm -fr elpa/`

**Closed** 2015-09-04 00:31 UTC

**Comment by netroby** [comment] 2015-09-04 01:16
Thanks, i know it. already fixed it

**Comment by robbyoconnor** [comment] 2015-09-04 01:21
Ah, great :heart:
