### ISSUE TITLE
`[count] k` not working properly

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1103] opened 2015-04-10 06:38 UTC
`[count] k` does not behave as expected. Often it moves up (sometimes down) the lines pretty randomly.
The lowest `[count]` I could produce this behavior with was `6`.

`:normal [count]k` works fine.

![ezgif com-crop 2](https://cloud.githubusercontent.com/assets/6420591/7151273/329f5a48-e330-11e4-9a29-d6bb4b164f1c.gif)

**Comment by syl20bnr** [comment] 2015-04-10 23:21
I cannot reproduce it, what is your evil version ? (suffix of the directory name in `~/.emacs.d/elpa`)

**Comment by xged** [comment] 2015-04-11 00:15
20150408.1417

**Comment by syl20bnr** [comment] 2015-04-13 01:38
I tested with the last one 20150411.1336 and I cannot reproduce your issue.

**Comment by seveneightn9ne** [comment] 2015-04-29 20:15
I'm on 20150423.349 and I have the same bug. It seems like sometimes when `[count] k` would cause the screen to scroll up, it scrolls up the correct amount but then sets the cursor to the center of the window. I also couldn't reproduce with `[count] < 6`, which I think is because `scroll-margin` seems to be set to 5 (but I can't find where that is coming from because `help` says that `scroll-margin` is set to 0

**Comment by syl20bnr** [comment] 2015-05-10 03:40
I can reproduce with smooth-scrolling enabled and the point is at the top the page.

**Comment by xged** [comment] 2015-07-29 14:02
`version 0.104.0`: I can reproduce it just with `[count] > 10` now. Smooth-scrolling is enabled (by default).

**Comment by a13ph** [comment] 2015-10-29 21:33
Reproducible on 
Spacemacs: master (0.104.2)
evil: 20151027.3

And it's surely about visible part of buffer. I've zoomed up as much as I could with readable linum-relative, to test on bigger counts, it still bugs out.

**Comment by synic** [comment] 2015-10-29 21:58
Can confirm.  I can type 100k and it'll go up 5 lines.

**Comment by syl20bnr** [comment] 2016-05-31 16:57
May be fixed in develop since we don't use the smooth-scrolling package anymore.

**Comment by xged** [comment] 2016-06-06 19:24
I cannot reproduce it in develop.

**Comment by d12frosted** [comment] 2016-10-03 08:16
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 08:16 UTC
Labels: - Bug tracker -, Bug :-(, Evil, Fixed in develop, Smooth-scrolling
