### ISSUE TITLE
scala is not loading

### ISSUE THREAD

**Issue by zxcvbn97** [syl20bnr/spacemacs#1228] opened 2015-04-18 05:15 UTC
Hi there,

I'm using the latest version of spacemacs with scala layer.
However, a scala mode does not load for my .scala file.
Can you please have a look? 
![image](https://cloud.githubusercontent.com/assets/9757976/7214109/03c6b68a-e560-11e4-9aab-cc6054a88dda.png)

Thank you,

**Comment by zxcvbn97** [comment] 2015-04-18 05:15
@ chrisbarrett

**Comment by syl20bnr** [comment] 2015-04-19 07:21
(you put a space) cc @chrisbarrett

**Comment by syl20bnr** [comment] 2015-04-19 07:21
@zxcvbn97 You can try the gitter chat also.

**Comment by syl20bnr** [comment] 2015-05-10 03:00
@zxcvbn97 any news an this ?

**Comment by TheBB** [comment] 2015-08-25 19:42
Since nobody has been able to reproduce this, and @zxcvbn97 is not responding, I'm closing this for now. Feel free to reopen if this is still a problem.

**Closed by TheBB** 2015-08-25 19:42 UTC
Labels: Scala
