### ISSUE TITLE
Helm find files backward delete doesn't update the path displayed

### ISSUE THREAD

**Issue by markolenik** [syl20bnr/spacemacs#4538] opened 2016-01-11 14:31 UTC
Helm find file with `SPC f f` does not update the path when I try to delete a char backwards with backspace. This only occurs when `dotspacemacs-distribution 'spacemacs` is set, when choosing `'spacemacs-base` everything works as expected.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.7
- Spacemacs branch: master (rev. 8a94bbf)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp)
```
#### Replication
- Fresh-install spacemacs.
- Choose full spacemacs distribution instead of the base

**Comment by AlejandroCatalina** [comment] 2016-01-11 14:35
I also have this issue.

I avoided it (said by @StreakyCobra) by doing   
```elisp
;; Helm prompt in echo bottom area
  (setq helm-echo-input-in-header-line nil)

What it does is placing the helm prompt at the minibuffer area, so, somehow, it avoids the problem.

**Comment by StreakyCobra** [comment] 2016-01-11 14:37
*Note*: That's just a temporary workaround, there is still a bug to find/fix here :-)

**Comment by AlejandroCatalina** [comment] 2016-01-11 14:40
Absolutely, but at least you can work. Nonetheless, I think this is a helm bug, not spacemacs. Don't know, tho.

**Comment by markolenik** [comment] 2016-01-11 14:52
Thanks for the response, the workaround works :)

**Comment by carlosgaldino** [comment] 2016-01-11 17:07
Same thing happens when using `helm-projectile-find-file` (`SPC p f`).

**Comment by fishtreesugar** [comment] 2016-01-12 08:09
I also have this issue after update to 0.105.8 :(

**Comment by magthe** [comment] 2016-01-12 10:09
I recognise this too; it's been like this for a while on `develop`.  A rollback to 0.104.8 removes the issue, so it's not a pure helm thing I think.

**Comment by StreakyCobra** [comment] 2016-01-12 11:06
So it's probably not upstream. @justbur Does recent keymap changes and keymap priorities could have bring this behaviour?

**Comment by justbur** [comment] 2016-01-12 11:55
@StreakyCobra No reason it should have changed anything for helm, but that doesn't mean it's impossible.

It seems like a helm issue to me since the behavior depends on the value of `helm-echo-input-in-header-line`

**Comment by StreakyCobra** [comment] 2016-01-12 12:02
Yes, but @magthe said it was working on 0.104.8.

Does someone has the time to bissect?

**Comment by stshine** [comment] 2016-01-12 12:54
This is caused by setting ```helm-prevent-escaping-from-minibuffer``` to ```t```:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/spacemacs-helm/packages.el#L40
I suggest to disable this option, It really does not make sense.

**Comment by StreakyCobra** [comment] 2016-01-12 13:20
IIRC we added this option because otherwise there was people being stuck out of helm after some impromptus mouse click.

**Comment by justbur** [comment] 2016-01-12 13:23
@StreakyCobra that's right

This is still a helm bug as far as I can tell. We don't change the default behavior of delete

**Comment by stshine** [comment] 2016-01-12 13:29
But despite this issue, with this option sometimes I find my self being stuck in helm and inputing some random chars while trying to leave.

**Comment by agzam** [comment] 2016-01-13 02:21
updated my packages just a minute ago and issue disappeared. Maybe it is was Helm's own bug. 
I have `dotspacemacs-helm-no-header t` and `helm-echo-input-in-header-line nil`, works as it used to

**Comment by icambron** [comment] 2016-01-13 07:28
@agzam I think it's expected to work right without setting `helm-echo-input-in-header-line nil`. I have also just updated my packages (which did include a Helm update) but I still have the issue.

**Comment by magthe** [comment] 2016-01-13 08:17
@icambron Same here, `helm-echo-input-in-header-line` is `t` and `dotspacemacs-helm-no-header` is `nil` (the defaults I think, right?) and the issue remains.

**Comment by synic** [comment] 2016-01-19 17:55
@stshine: Setting `helm-prevent-escaping-from-minibuffer` in my `user-config` does not fix this issue, so I'm not sure that's the cause.

**Comment by joehillen** [comment] 2016-01-19 18:50
If this is an upstream issue, is there a issue open for helm?

**Comment by tuhdo** [comment] 2016-01-19 18:54
If you want to report to Helm, make sure you can reproduce it with `emacs-helm.sh` script in your installed Helm directory.

**Comment by tuhdo** [comment] 2016-01-19 19:03
This is something related to Spacemacs, not Helm. I tested with `emacs-helm.sh`, and such bug doesn't happen.

**Comment by joehillen** [comment] 2016-01-19 19:32
I also tested it with the following code pulled from spacemacs in `emacs-helm.sh` and still not reproduced:

```elisp
(setq helm-echo-input-in-header-line t)
(defun helm-hide-minibuffer-maybe ()
  (when (with-helm-buffer helm-echo-input-in-header-line)
    (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
      (overlay-put ov 'window (selected-window))
      (overlay-put ov 'face
                    (let ((bg-color (face-background 'default nil)))
                      `(:background ,bg-color :foreground ,bg-color)))
      (setq-local cursor-type nil))))
(add-hook 'helm-minibuffer-set-up-hook 'helm-hide-minibuffer-maybe)
```

**Comment by tuhdo** [comment] 2016-01-20 03:49
I found the culprit: it's the `spaceline` package that is causing this. Once you remove the package, the bug disappears. 

@TheBB

**Comment by robbyoconnor** [comment] 2016-01-20 04:22
@tuhdo is the fix trivial?

**Comment by joehillen** [comment] 2016-01-20 04:35
@tuhdo 

![](http://i.imgur.com/DYF6sRZ.jpg)

Confirmed. Removing spaceline fixed it for me too. How did you possibly figure that out?

**Comment by robbyoconnor** [comment] 2016-01-20 04:38
@joehillen - he just [knows a crapton about helm](http://tuhdo.github.io/helm-intro.html), see also [this](http://tuhdo.github.io/helm-projectile.html).

**Comment by tuhdo** [comment] 2016-01-20 04:51
:smile: 

It took quite awhile to find out. I tried commented all Helm config in `spacemacs-helm` layer, but it didn't work. Running `./emacs-helm.sh` doesn't have this issue. Scratched my head, then I remember @markolenik reported that `spacemacs-base` does not have a problem, I looked at both package lists in `spacemacs-base` and `spacemacs`, and test each package not in `spacemacs-base` one by one.

**Comment by tuhdo** [comment] 2016-01-20 04:52
@robbyoconnor I don't know. I haven't looked at it yet. But maybe @TheBB can make it quick.

**Comment by TheBB** [comment] 2016-01-20 11:53
Thanks for that. Quite surprising. It's due to `spaceline-helm-mode`, which advises some helm function. I'll have a look.

**Comment by TheBB** [comment] 2016-01-20 12:01
Fixed in Spaceline in https://github.com/TheBB/spaceline/commit/2d07d8f85fb0b46c3e52c737b03fe44450140656

Please update once it's out on MELPA.

Sorry about this. It was caused by me backporting some advice to pre-24.4 format and doing it improperly.

**Comment by TheBB** [comment] 2016-01-20 13:09
MELPA updated so I'm closing this now. Please reopen if I missed something.

**Closed by TheBB** 2016-01-20 13:09 UTC
Labels: bug :-(, Fixed upstream, Helm

**Comment by tuhdo** [comment] 2016-01-20 13:41
Great :+1: 

And thanks for the quick fix.

**Comment by icambron** [comment] 2016-01-20 20:11
Upgraded and confirmed fixed for me. Thanks!

**Comment by magthe** [comment] 2016-01-21 08:31
Very, very, very nicely done!

**Comment by markolenik** [comment] 2016-01-21 10:26
Great, thank you!
