### ISSUE TITLE
nixos layer breaks spacemacs

### ISSUE THREAD

**Issue by ankhers** [syl20bnr/spacemacs#5049] opened 2016-02-12 21:11 UTC
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(c-c++ common-lisp elixir emacs-lisp elm erlang go haskell html idris java javascript latex lua markdown purescript racket ruby rust sql yaml ruby-on-rails auto-completion better-defaults git github org colors jabber restclient dash erc gnus dockerfile spell-checking syntax-checking nixos)
```

Enabling the `nixos` layer and having the `nixos-options-json-file` seems to break emacs. If I do not have the file created, spacemacs starts fine with a minor error saying it is unable to find that file.

The error I get when trying to start emacs and having the `nixos-options-json-file` is: 

`*ERROR*: Symbol's function definition is void: page-break-lines-mode`

At which point, if I try to use certain other functions (`M-x`, `SPC b b`, I'm sure others), I get the following error: `Symbol's function definition is void: popwin-mode`.

Let me know if there is any other information I can provide.

**Comment by Andre0991** [comment] 2016-02-12 21:20
`*ERROR*: Symbol's function definition is void: page-break-lines-mode`

I got the same error today. I deleted `~/.emacs.d/elpa`, restarted Spacemacs and it worked.

**Comment by ankhers** [comment] 2016-02-12 21:40
That did indeed fix it. Thanks.

**Comment by ankhers** [comment] 2016-02-13 16:43
While this initially fixed my issue, when I updated my packages today, I received the same errors again. Unfortunately, removing `~/.emacs.d/elpa` on a regular basis is not really a solution.

**Comment by Andre0991** [comment] 2016-02-13 16:49
Can you start Spacemacs with `--debug-init` please? I didn't investigate what caused this error when I had this issue.

**Comment by ankhers** [comment] 2016-02-13 17:13
For some reason, when starting emacs with `--debug-init`, I do not get the debugger to popup, despite still seeing the error message. However, when I enable debug on error (`SPC t D`), and try to run various commands, I do get the debugger. The following is from trying to run `SPC b b`.

``` elisp
Debugger entered--Lisp error: (void-function popwin-mode)
  (popwin-mode -1)
  (let ((display-buffer-base-action (quote (nil)))) (setq spacemacs-display-buffer-alist display-buffer-alist) (setq display-buffer-alist nil) (popwin-mode -1) (if helm-prevent-escaping-from-minibuffer (progn (define-key evil-motion-state-map [down-mouse-1] nil))))
  spacemacs//helm-prepare-display()
  run-hooks(helm-after-initialize-hook)
  helm-log-run-hook(helm-after-initialize-hook)
  helm-initial-setup(nil)
  helm-initialize(nil nil nil (helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found))
  #[0 "\311\211\211\211\305\206\n&&'()*\312\313+\"\314\315\316\317\320\321!\322\"\323\324%DC\216\325\303\301\307\300$\210\326&!\210,\203?\327\330!\210\331\332\333\"\210\331\332\334\"\210\335\336!\210\314\337DC\216\340\302\301\304\303\306\307\310&\210*\210'?\205g\341 \335\342\343\344\345\"P!\210-\207" [(helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil nil mapcar #[257 "\211JB\207" [] 3 "\n\n(fn V)"] funcall make-byte-code 0 "\300\301\211:\203@\262\211A\262\242\262\211L\210A\262\202\266\302\303!\207" vconcat vector [nil helm-log "restore variables"] 5 "\n\n(fn)" helm-initialize helm-display-buffer helm--remap-mouse-mode 1 add-hook post-command-hook helm--maybe-update-keymap helm--update-header-line helm-log "show prompt" #[0 "\300 \207" [helm-cleanup] 1 "\n\n(fn)"] helm-read-pattern-maybe helm-execute-selection-action "[End session] " make-string 41 45 helm-buffer helm-quit helm-in-persistent-action helm-current-source helm-source-name helm-restored-variables helm-prevent-escaping-from-minibuffer] 9 "\n\n(fn)"]()
  funcall(#[0 "\311\211\211\211\305\206\n&&'()*\312\313+\"\314\315\316\317\320\321!\322\"\323\324%DC\216\325\303\301\307\300$\210\326&!\210,\203?\327\330!\210\331\332\333\"\210\331\332\334\"\210\335\336!\210\314\337DC\216\340\302\301\304\303\306\307\310&\210*\210'?\205g\341 \335\342\343\344\345\"P!\210-\207" [(helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil nil mapcar #[257 "\211JB\207" [] 3 "\n\n(fn V)"] funcall make-byte-code 0 "\300\301\211:\203@\262\211A\262\242\262\211L\210A\262\202\266\302\303!\207" vconcat vector [nil helm-log "restore variables"] 5 "\n\n(fn)" helm-initialize helm-display-buffer helm--remap-mouse-mode 1 add-hook post-command-hook helm--maybe-update-keymap helm--update-header-line helm-log "show prompt" #[0 "\300 \207" [helm-cleanup] 1 "\n\n(fn)"] helm-read-pattern-maybe helm-execute-selection-action "[End session] " make-string 41 45 helm-buffer helm-quit helm-in-persistent-action helm-current-source helm-source-name helm-restored-variables helm-prevent-escaping-from-minibuffer] 9 "\n\n(fn)"])
  helm-internal((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm-internal ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm(:sources (helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) :buffer "*helm mini*" :ff-transformer-show-only-basename nil :truncate-lines t)
  helm-mini()
  call-interactively(helm-mini nil nil)
  command-execute(helm-mini)
```

**Comment by bmag** [comment] 2016-02-13 17:19
@ankhers do you have a directory named `popwin-<numbers>` inside of `.emacs.d/elpa`? Please list all the files that it contains, and make sure that non of them is empty.
It should contain these files:
- popwin-autoloads.el
- popwin.el
- popwin.elc
- popwin-pkg.el
- popwin-pkg.elc

**Comment by ankhers** [comment] 2016-02-13 17:45
``` bash
12:36:31 {develop} popwin-20150315.600$ ls -lah
total 192
drwxr-xr-x    7 $USER  staff   238B 13 Feb 11:43 .
drwxr-xr-x  276 $USER  staff   9.2K 13 Feb 11:46 ..
-rw-r--r--    1 $USER  staff   2.4K 13 Feb 11:43 popwin-autoloads.el
-rw-r--r--    1 $USER  staff    97B 13 Feb 11:43 popwin-pkg.el
-rw-r--r--    1 $USER  staff   501B 13 Feb 11:43 popwin-pkg.elc
-rw-r--r--    1 $USER  staff    43K 13 Feb 11:43 popwin.el
-rw-r--r--    1 $USER  staff    39K 13 Feb 11:43 popwin.elc
```

None are empty.

As I stated in the original ticket, this issue goes away when I remove the `nixos-options-json-file`. By default, it is located in `~/share/doc/nixos/options.json`.

**Comment by bmag** [comment] 2016-02-13 17:56
Ok, it seems that popwin is installed correctly. I'm trying to reproduce the bug (on Ubuntu, though, not NixOS), can you help with that?
- Can you provide step-by-step instructions how to reproduce the bug?
- Does it happen also when the `nixos` layer is disabled?
- Can you attach an example of a json options file?

Thanks

**Comment by ankhers** [comment] 2016-02-13 19:24
I'm actually having this issue on OS X.

The json file is empty. I was originally getting an error that the file
isn't there, so I created the directory, `$ mkdir -p ~/share/doc/nixos`,
then I `$ touch ~/share/doc/nixos/options.json` which is when I started
getting the issue.

I can check a little bit later if it still happens if I remove nixos layer.

**Comment by ankhers** [comment] 2016-02-13 21:57
When I disable the `nixos` layer, this no longer happens.

As for step by step instructions:

1. Enable `nixos` layer
2. Notice error about missing the options file when starting emacs
3. `$ mkdir -p ~/share/doc/nixos`
4. `$ touch ~/share/doc/nixos/options.json`
5. Start emacs.

Step 5 is where the breakage happens. I dug through [`nixos-options`](https://github.com/travisbhartwell/nix-emacs) to find where the location of the json file is.

**Comment by bmag** [comment] 2016-02-23 18:35
@ankhers I managed to reproduce the bug with your instructions. At stage 5 I get the error `Symbol's function definition is void: page-break-lines-mode`.

I have managed to get rid of the error and start spacemacs normally by using an options file with this contents: (instead of an empty options file)
```
[]
```

**Comment by syl20bnr** [comment] 2016-02-24 15:16
We don't do anything special with the configuration of this layer, I think it should be reported upstream.

cc @travisbhartwell @CestDiego

**Comment by TheBB** [comment] 2016-09-22 21:07
Closing this since nobody seems to want to report upstream.

**Closed by TheBB** 2016-09-22 21:07 UTC
Labels: - Bug tracker -, Should report upstream
