### ISSUE TITLE
Spacemacs corrupts the first opened buffer by inserting what appears to be last copied clipboard contents

### ISSUE THREAD

**Issue by harikb** [syl20bnr/spacemacs#8235] opened 2017-01-23 00:15 UTC
#### Description :octocat:
Spacemacs corrupts the first opened buffer by inserting
the last copied text from clipboard in to the middle of the file 
(depending on where the cursor was)

*[ Edited to remove the reference to go layer, no connection to Go layer ]*

#### Reproduction guide :beetle:
- Start Emacs
- Chose any file from initial spacemacs screen (where it shows the list of recent files)

*Observed behaviour:* :eyes: :broken_heart:
The above text is automatically insert to the file. File status does become 'edited' (with a star mark in the status)
Undo ('u' in vim mode) reverts the change, but this entire sequence is unwanted.

*Expected behaviour:* :heart: :smile:
There should not be any changes to the opened file

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html auto-completion emacs-lisp go git markdown rust python syntax-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by harikb** [comment] 2017-01-23 00:29
Correction to my original report and come screenshots. The text seems to change to whatever was the last copied/yanked text. While submitting the above bug report, that first line of the template was the last one I yanked before exiting Spacemacs and that is the text you can see getting inserted in the screenshots below.

<img width="639" alt="_spacemacs_3" src="https://cloud.githubusercontent.com/assets/952886/22187685/b7ee19bc-e0bf-11e6-93df-6672cd9eab2f.png">
<img width="922" alt="_spacemacs_2" src="https://cloud.githubusercontent.com/assets/952886/22187686/b7ef99fe-e0bf-11e6-92d3-f072ecd0e210.png">
<img width="913" alt="_spacemacs_1" src="https://cloud.githubusercontent.com/assets/952886/22187687/b7f13052-e0bf-11e6-863c-ef3afc6469f2.png">

**Comment by harikb** [comment] 2017-01-23 00:31
Read the images above in the reverse order. First the home page, then the file with corrupted contents and then the undo that I normally do to get out of it.

**Comment by ljupchokotev** [comment] 2017-01-23 17:21
I can confirm that the same happens to me. I don't have the "go" layer installed so this isn't related to it. Anytime I open a file from the "Recent Files" it will paste what is in my clipboard in the buffer when it opens.

**Comment by zestyr** [comment] 2017-01-23 19:43
Happens for me too, specifically when I click on a file from recent files list with my mouse.

**Comment by abingham** [comment] 2017-03-08 08:47
I see something similar, though I don't see any correlation with the clipboard. Whenever I open a file using the "Recent Files" list in the `*spacemacs*` buffer, something inserts the character "p" into the buffer. This is on Emacs 25.1.1 on OS X.

**Comment by bmag** [comment] 2017-03-09 07:41
closing as duplicate of #5435

**Closed by bmag** 2017-03-09 07:41 UTC
