### ISSUE TITLE
Unable to jump to another window from NeoTree

### ISSUE THREAD

**Issue by JacobJakub** [syl20bnr/spacemacs#4535] opened 2016-01-11 10:55 UTC
#### Description
Hello, I am pretty sure that this worked fine to me but I am unable after an update (? probably after an update, been doing some changes to my `.spacemacs` too) to jump back from neotree to any buffer with `ctrl-l`. When I press `ctrl-l` it flashes and when I use `ctrl+w+l` it has a weird behaviour that it opens the node in my buffer where I am jumping to. Sometimes it even jumps to my rightest buffer. 

Anyone experiencing this issue?

#### Reproduction guide

1) open a project's file
2) `leader-p-t`
3) `ctrl-l`

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.7
- Spacemacs branch: master (rev. 8a94bbf)
- Distribution: spacemacs
- Layers:
```elisp
'(
     auto-completion
     better-defaults
     ;; Languages
     emacs-lisp
     ruby
     scala
     markdown
     javascript
     shell-scripts
     yaml
     html
     dockerfile
     ruby-on-rails
     ;; org
     (shell :variables
             shell-default-height 30
             shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     ;; version-control
     git
     github
     ;; themes
     themes-megapack
     colors
     ;; system
     osx
     tmux
     ;; chat
     erc
     )
```

`GNU Emacs 24.5.1` on osx

**Comment by JacobJakub** [comment] 2016-01-11 16:09
Just reinstalled spacemacs and used the default settings and it doesn't work too. So the issue should not be in my config file.

**Comment by nixmaniack** [comment] 2016-01-11 18:48
In my case, `C-l` is bound to `recenter-top-bottom` and as far I remember that's what it used to be. Can you provide more details according to [this guideline](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)?

**Comment by JacobJakub** [comment] 2016-01-19 15:48
@nixmaniack Done

**Comment by StreakyCobra** [comment] 2016-01-19 16:43
Thanks @JacobJakub . Up to my knowledge `C-l` was never used to move between windows, so at most it was a bug if it happened to work. What you can do is to use `SPC w h` (or `j`, `k` and `l`) to move between windows. It is also possible to use `SPC + 1` (or `2` … `9`) to select a windows directly with its number (indicated in the modeline). Finally there is `SPC w .` that allow you to enter a micro-mode that permits to navigate between windows with only one keypress on `h`, `j`, `k` and `l`, `q` for quitting it.

It this explanation OK for you or do you need more help from our side?

**Comment by JacobJakub** [comment] 2016-01-19 16:53
Thanks @StreakyCobra I was wondering which layer allows me to jump between the panels in the same way as in Tmux and turned out it's actually tmux layer https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/tmux/extensions/tmux/tmux.el

This layer uses the CTRL-hjkl to move between the windows so I am not sure if it's an issue or not.

**Comment by StreakyCobra** [comment] 2016-01-19 17:00
Oh, ok. Indeed looks like a bug.

**Comment by bmag** [comment] 2016-01-26 13:27
@JacobJakub neotree used to be in motion-state, but we evilified it a few weeks ago. The tmux layer binds `C-l` and other in `evil-motion-state-map` and `evil-normal-state-map` (see [here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/tmux/extensions/tmux/tmux.el#L87)), which is why it used to work. Since now neotree is in evilified-state, these bindings don't work anymore.

Changing tmux layer to bind these keys also in `evil-evilified-state-map` will fix the issue. Does it make sense for tmux layer to bind `C-h/j/k/l` in all evilified buffers?

**Comment by rteabeault** [comment] 2016-02-10 19:10
I tried adding the tmux layer to also bind the keys in the `evil-evilified-state-map` but it is still broken.

In `tmux.el`:
```
(define-key evil-evilified-state-map
                   (kbd "C-h")
                   (lambda ()
                     (interactive)
                     (tmux-navigate "left")))
(define-key evil-evilified-state-map
                   (kbd "C-j")
                   (lambda ()
                     (interactive)
                     (tmux-navigate "down")))
(define-key evil-evilified-state-map
                   (kbd "C-k")
                   (lambda ()
                     (interactive)
                     (tmux-navigate "up")))
(define-key evil-evilified-state-map
                   (kbd "C-l")
                   (lambda ()
                     (interactive)
                     (tmux-navigate "right")))
```

Is there something else I should be doing?

**Comment by bmag** [comment] 2016-02-10 20:23
@rteabeault I don't know why that doesn't work. Maybe @justbur will know.
I've added `(define-key evil-evilified-state-map (kbd "C-l") #'next-line)` to my `dotspacemacs/user-config`, restarted spacemacs and opened Neotree with `SPC f t`. I expected `C-l` to be bound to `next-line`, but it was bound to `recenter-top-bottom` (the original binding) instead. I evaluated the `(define-key ...)` manually and switched back to neotree, and only then was `C-l` really bound to `next-line`.

**Comment by justbur** [comment] 2016-02-10 20:44
@rteabeault @bmag I don't no why, but the evilify code doesn't want you to modify `evil-evilified-state-map`. [See here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/local/evil-evilified-state/evil-evilified-state.el#L165) and [here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/local/evil-evilified-state/evil-evilified-state.el#L219). It's purposefully using a copy of the original map and not the current version.

**Comment by rteabeault** [comment] 2016-02-10 20:47
@bmag, @justbur, I am a little out of my comfort zone here. Any ideas on how we could fix this then?

**Comment by justbur** [comment] 2016-02-10 20:47
I guess [this comment](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/local/evil-evilified-state/evil-evilified-state.el#L228) is the reason. Seems to be an implementation issue. 

You could try 
```elisp
  (evil-define-key 'evilified neotree-mode-map "\C-l" 'next-line)
```

**Comment by rteabeault** [comment] 2016-02-10 20:55
@justbur, NeoTree is not the problem I am having. This issue was opened for a problem in NeoTree but the underlying problem is that the tmux layer is broken in develop. This layer allows you to navigate across spacemacs and tmux windows using the same keys `C-hjkl`. I would like to find a solution that fixes the tmux layer.

**Comment by justbur** [comment] 2016-02-10 21:05
In that case, @bmag is right that the bindings in that layer are not affecting evilified state it seems. @syl20bnr is the one to ask about this.

**Comment by bmag** [comment] 2016-02-10 21:16
@justbur oh, I mentioned you because I thought you had a part in writing that code (didn't do a git blame).

@rteabeault as a workaround until the issue is fixed, you can add this code to your `dotspacemacs/user-config`:
```elisp
(defun add-tmux-binding (map)
  (evil-define-key 'evilified map
    (kbd "C-h") (lambda () (interactive) (tmux-navigate "leftj"))
    (kbd "C-j") (lambda () (interactive) (tmux-navigate "down"))
    (kbd "C-k") (lambda () (interactive) (tmux-navigate "up"))
    (kbd "C-l") (lambda () (interactive) (tmux-navigate "right"))))

(with-eval-after-load 'neotree
  (add-tmux-binding neotree-mode-map))
```
If there are other evilified modes where it bothers you, you can add more calls to `add-tmux-binding` with the appropriate major mode map, wrapped in a `with-eval-after-load`. I know this doesn't solve the issue, it's only a workaround.

**Comment by justbur** [comment] 2016-02-10 21:18
@bmag I fixed one or two things with it, but no it's mostly @syl20bnr that designed it as far as I know

**Comment by rteabeault** [comment] 2016-02-10 22:09
Is there a way to add it to all evilified modes?

**Comment by bmag** [comment] 2016-02-11 08:51
```elisp
(define-key evil-evilified-state-map <key> <command>)
```
Is the standard way, and it works for all the other states. I don't why it doesn't work for evilified state. I'm focusing on other stuff at the moment, so I won't be able to research this issue (not soon, at least), sorry :-(

**Comment by justbur** [comment] 2016-02-11 13:19
It was an easy fix. See #5034

**Comment by rteabeault** [comment] 2016-02-15 18:13
@justbur, Thanks for fixing this!

**Comment by justbur** [comment] 2016-02-15 18:19
@rteabeault np

@syl20bnr It's worth mentioning that [this should work](https://github.com/syl20bnr/spacemacs/issues/4535#issuecomment-182770508) but the current code in evil-evilified-state prevents it from being an option

**Closed** 2016-02-19 04:22 UTC
Labels: bug :-(, Fixed in develop, Windows layout
