### ISSUE TITLE
Error (use-package): org-projectile :config: Symbol’s function definition is void: org-projectile:per-repo

### ISSUE THREAD

**Issue by DWShuo** [syl20bnr/spacemacs#9483] opened 2017-08-24 10:08 UTC
This error was on a fresh install of spacemacs, another install of spacemacs was done 5 days ago on a different machine did not have this issue.

"Error (use-package): org-projectile :config: Symbol’s function definition is void: org-projectile:per-repo"

System Info 💻
    OS: antegros/linux
    Emacs: 25.2.1
    Spacemacs: 0.200.9
    Spacemacs branch: master (rev. 8e1af14)
    Distribution: spacemacs
    Editing style: vim
    Completion: helm

Same issue was reported 22 days ago #9340

**Comment by IvanMalison** [comment] 2017-08-28 00:44
org-projectile was recently refactored, AS mentioned in that issue, the issue is resolved in develop. I'm not really sure when the fix will be brought to master.

**Closed** 2017-08-28 11:05 UTC

**Comment by revmischa** [comment] 2017-12-28 07:58
Still getting this on fresh install

**Comment by IvanMalison** [comment] 2017-12-28 08:41
Are you on develop?

**Comment by revmischa** [comment] 2017-12-28 08:42
maybe? i just followed the instructions to clone the git repo to ~/.emacs.d. Is that develop?

**Comment by IvanMalison** [comment] 2017-12-28 17:22
no

**Comment by duianto** [comment] 2017-12-29 12:57
@revmischa You can switch to the `develop` branch, either by navigating to the `.emacs.d` directory in a terminal, and typing `git checkout develop` and restart Emacs.

Or from within Spacemacs, press `S-M-;` (hold down Shift and Alt, and press `;` (semicolon)) to open the `Eval:` prompt, then either type or copy and paste (`C-y`) the following command:
```
(spacemacs//git-checkout "develop")
```
Then press `RET`, and when you see a `t` in the minbuffer at the bottom, then restart Emacs

**Comment by revmischa** [comment] 2017-12-29 15:16
and this will fix all my problems?

**Comment by duianto** [comment] 2017-12-29 17:07
I don't know if it will fix all your problems 😄 

But according to IvanMalison and jajapater (in this issue: Error (use-package): org-projectile :config: Symbol’s function definition is void: org-projectile:per-repo #9340)
This issue seems to be fixed on the `develop` branch.

I just saw that you wondered how to switch to the `develop` branch.
