### ISSUE TITLE
auto-fill mode doesn't work in org-mode anymore

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#5761] opened 2016-04-11 20:28 UTC
#### Description
Enabling auto-fill-mode and setting fill-column has no effect in org-mode anymore.

#### Reproduction guide

I set the following in my `user-config` (it has worked prior to this):

```elisp
  ;; Org
  (add-hook 'org-mode-hook
            (lambda ()
              ;; Enable fill column indicator
              (fci-mode t)
              ;; Turn off line numbering, it makes org so slow
              (linum-mode -1)
              ;; Set fill column to 79
              (setq fill-column 79)
              ;; Enable automatic line wrapping at fill column
              (auto-fill-mode t)))

```

*Observed behaviour:*
When typing, long lines are not automatically split.

*Expected behaviour:*
Long lines should be automatically split.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.18
- Spacemacs branch: develop (rev. 2034195)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql nginx unscroll auto-completion xkcd emacs-lisp git yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking lua colors spacemacs-layouts vimscript spacemacs-helm
     (version-control :variables version-control-diff-tool 'diff-hl)
     (c-c   :variables c-c  -enable-clang-support t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by StreakyCobra** [comment] 2016-04-11 20:35
I can't reproduce, it works as expected with the provided config lines.

**Comment by TheBB** [comment] 2016-04-12 11:58
Duplicate of #5697.

**Closed** 2016-04-12 11:58 UTC
Labels: - Bug tracker -, Duplicate ☝, Org, To be reproduced
