### ISSUE TITLE
Go layer: gb support

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#2843] opened 2015-09-01 01:25 UTC
Go projects that [use gb](https://github.com/constabulary/gb) are not fully supported by the Go layer. Specifically vendor-ed imports are marked with red squiggly:

<img width="537" alt="screen shot 2015-08-31 at 6 23 36 pm" src="https://cloud.githubusercontent.com/assets/3998/9594253/9f578206-500d-11e5-8093-c9bc3810dcaa.png">

**Comment by srid** [comment] 2015-09-01 01:27
This may just be a matter of [patching gocode](https://github.com/nsf/gocode/pull/289).

**Comment by TheBB** [comment] 2015-09-02 08:45
The PR you linked to was merged a while ago. If you have updated packages and it still doesn't work, it's an issue with upstream.

**Comment by StreakyCobra** [comment] 2015-11-17 18:56
@srid Is it working now?

**Comment by StreakyCobra** [comment] 2015-12-23 22:35
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.

**Closed by StreakyCobra** 2015-12-23 22:35 UTC
Labels: Go, Waiting for response
