### ISSUE TITLE
Cannot start spacemacs if elpa.gnu.org is down

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#5139] opened 2016-02-19 08:57 UTC
I just restarted Spacemacs and it will not finish loading with the following:
```
Warning (initialization): An error occurred while loading `/Users/schmitta/.emacs.d/init.el':

File error: make client process failed, connection refused, :name, elpa.gnu.org, :buffer, #<killed buffer>, :host, elpa.gnu.org, :service, 443, :nowait, nil

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

Looking at the `*Messages*` buffer I see this:
```
(Spacemacs) --> refreshing package archive: melpa... [1/3]
Contacting host: melpa.org:443
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
(Spacemacs) --> refreshing package archive: org... [2/3]
Contacting host: orgmode.org:80
Importing package-keyring.gpg...done
(Spacemacs) --> refreshing package archive: gnu... [3/3]
Spacemacs is ready.
Loading /Users/schmitta/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
cond: Symbol's function definition is void: projectile-mode
Symbol's function definition is void: projectile-mode
```
Starting with `--debug-init` confirms the bug comes from elpa.gnu.org being down:

```
Debugger entered--Lisp error: (file-error "make client process failed" "connection refused" :name "elpa.gnu.org" :buffer #<buffer  *url-http-temp*> :host "elpa.gnu.org" :service 443 :nowait nil)
  make-network-process(:name "elpa.gnu.org" :buffer #<buffer  *url-http-temp*> :host "elpa.gnu.org" :service 443 :nowait nil)
  open-network-stream("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443)
  open-gnutls-stream("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443)
  network-stream-open-tls("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443 (:type tls :nowait t))
  open-network-stream("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443 :type tls :nowait t)
…
```

**Comment by axyz** [comment] 2016-02-19 09:02
+1

**Comment by nixmaniack** [comment] 2016-02-19 09:08
Since I track develop, only `uuidgen` package was missing for me(which is on melpa) since last update. So the workaround for me was comment elpa.gnu.org, restart emacs, let it download, uncomment elpa. Back to work.

```diff
diff --git a/core/core-configuration-layer.el b/core/core-configuration-layer.el
index 4b57943..218c385 100644
--- a/core/core-configuration-layer.el
+++ b/core/core-configuration-layer.el
@@ -132,7 +132,8 @@
 (defvar configuration-layer--elpa-archives
   '(("melpa" . "melpa.org/packages/")
     ("org"   . "orgmode.org/elpa/")
-    ("gnu"   . "elpa.gnu.org/packages/"))
+    ;("gnu"   . "elpa.gnu.org/packages/")
+    )
   "List of ELPA archives required by Spacemacs.")

 (defvar configuration-layer--package-archives-refreshed nil
```

On master, you can set `dotspacemacs-check-for-update` to `nil` to skip update on startup.

**Comment by axyz** [comment] 2016-02-19 09:16
I've figured out to start spacemacs correctly setting `(defvar configuration-layer--package-archives-refreshed t` on that file

**Comment by bmag** [comment] 2016-02-19 09:19
I wonder about the error `Symbol's function definition is void: projectile-mode`. It means that projectile's directory wasn't added to `load-path`, or `projectile-autloads.el` wasn't loaded, or `projectile.el` is malformed or empty. However, projectile is on melpa, not gnu elpa, so I don't understand why there's a problem with projectile.

**Comment by brabalan** [comment] 2016-02-19 09:23
@nixmaniack Thank you for the workaround, I was able spacemacs doing this

@bmag I think it's a side effect of the failure to access elpa.gnu.org, since I don't see this message when commenting that repository.

**Comment by nixmaniack** [comment] 2016-02-19 09:32
@axyz It would skip refreshing other package repos.

**Comment by marten** [comment] 2016-02-19 11:42
Does this issue mean you normally can't start Spacemacs when you don't have network connectivity?

**Comment by nixmaniack** [comment] 2016-02-19 12:00
@marten Unless there's some package missing, you should be able to start spacemacs normally without network. 

Reverting back to commit before pull(`develop@{1}`) and rolling back packages should be enough in such cases.

**Comment by chu-** [comment] 2016-02-19 12:28
+1

**Comment by a13ph** [comment] 2016-02-19 13:41
sane temp fix

:speech_balloon: [syl20bnr @ February 19, 2016 4:38 PM](https://gitter.im/syl20bnr/spacemacs?at=56c71ae25c3b0559674d5c31)

> copy back the packages from .cache/.rollback to your ELPA directory

**Comment by syl20bnr** [comment] 2016-02-19 13:43
Seems we need more robustness here. I'll check to add an automatic rollback prompt when this happens.

Thank you @a13ph for the link.

**Comment by pfitz** [comment] 2016-02-19 14:42
Workaround did the trick so far.

**Comment by carloscheddar** [comment] 2016-02-19 14:49
+1

**Comment by TheBB** [comment] 2016-02-19 15:03
I think the better workaround for now is to exclude the package that Spacemacs tries to download (which is uuidgen for most people).

**Comment by brabalan** [comment] 2016-02-19 15:22
@TheBB In my case I had just asked spacemacs to install another package (ebib). Refreshing the configuration did not download it (probably because elpa.gnu.org was down), so I decided to restart spacemacs.

**Comment by syl20bnr** [comment] 2016-02-19 15:52
Argh sorry guys about this, I hope we will be able to fix this mess "quickly".

**Comment by CestDiego** [comment] 2016-02-19 15:56
@syl20bnr I get this when trying to update packages:

```
Opening TLS connection to `elpa.gnu.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 elpa.gnu.org'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 elpa.gnu.org --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect elpa.gnu.org:443 -no_ssl2 -ign_eof'...failed
Opening TLS connection to `elpa.gnu.org'...failed
url-http: Could not create connection to elpa.gnu.org:443
```

**Comment by carloscheddar** [comment] 2016-02-19 16:17
BTW guys elpa.gnu.org is back up.

**Comment by syl20bnr** [comment] 2016-02-19 16:33
So when I have time to check the issue I cannot reproduce it.
The site is down but the repository seems to work fine :-(

**Comment by syl20bnr** [comment] 2016-02-19 16:34
I mean its cool that is works but it would have been easier to fix the issue if it was still down ;-)

**Comment by syl20bnr** [comment] 2016-02-19 16:55
Actually I don't use https, maybe this is why I cannot reproduce it here.

A fresh install (without https) does not block and gives me 10 errors:

```(Bootstrap) Installing evil...
(Bootstrap) Installing bind-map...
(Bootstrap) Installing bind-key...
(Bootstrap) Installing which-key...
(Bootstrap) Installing use-package...
(Bootstrap) Installing package-build...
(Bootstrap) Installing quelpa...
Found 193 new package(s) to install...
--> installing package: adaptive-wrap@spacemacs... [5/193]
An error occurred while installing adaptive-wrap (error: (file-error http://elpa.gnu.org/packages/adaptive-wrap-0.5.el Service unavailable))
--> installing package: company-statistics@auto-completion... [29/193]
An error occurred while installing company-statistics (error: (file-error http://elpa.gnu.org/packages/company-statistics-0.2.2.tar Service unavailable))
--> installing package: elm-mode@elm... [39/193]
An error occurred while installing elm-mode (error: (file-error http://elpa.gnu.org/packages/let-alist-1.0.4.el Service unavailable))
--> installing package: flycheck@syntax-checking... [69/193]
An error occurred while installing flycheck (error: (file-error http://elpa.gnu.org/packages/seq-1.11.el Service unavailable))
--> installing package: flycheck-elm@elm... [70/193]
An error occurred while installing flycheck-elm (error: (file-error http://elpa.gnu.org/packages/seq-1.11.el Service unavailable))
--> installing package: flycheck-pos-tip@syntax-checking... [71/193]
An error occurred while installing flycheck-pos-tip (error: (file-error http://elpa.gnu.org/packages/seq-1.11.el Service unavailable))
--> installing package: org-present@org... [142/193]
An error occurred while installing org-present (error: (file-error http://elpa.gnu.org/packages/org-20160215.tar Service unavailable))
--> installing package: orgit@git... [144/193]
An error occurred while installing orgit (error: (file-error http://elpa.gnu.org/packages/org-20160215.tar Service unavailable))
--> installing package: paradox@spacemacs... [147/193]
An error occurred while installing paradox (error: (file-error http://elpa.gnu.org/packages/spinner-1.7.el Service unavailable))
--> installing package: rainbow-mode@colors... [166/193]
An error occurred while installing rainbow-mode (error: (file-error http://elpa.gnu.org/packages/rainbow-mode-0.12.el Service unavailable))
--> installing package: yasnippet@auto-completion... [193/193]


```

**Comment by edrex** [comment] 2016-02-19 17:54
so we can help by DDoSing elpa? :trollface:

**Comment by CestDiego** [comment] 2016-02-19 18:09
Still having problem of not being able to conoect to elpa

On Fri, Feb 19, 2016 at 12:54 PM Eric Drechsel <notifications@github.com>
wrote:

> so we can help by DDoSing elpa? [image: :trollface:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/5139#issuecomment-186331587>
> .
>
-- 
Diego Berrocal
http://cestdiego.github.io

**Comment by aldanor** [comment] 2016-02-19 19:25
So it's impossible to set up a new installation currently?

**Comment by andrewhj-mn** [comment] 2016-02-19 22:29
I wasn't able to.  However, elpa appears to be back up now (It worked when I tried just now)

**Comment by syl20bnr** [comment] 2016-02-20 04:57
Should be addressed in 0.105.11, hopefully next time it happens Spacemacs should load normally reporting just a few errors about uninstalled packages. Thank you for the feedback.

**Closed by syl20bnr** 2016-02-20 04:57 UTC
Labels: bug :-(, High Priority, Install, Loading

**Comment by brabalan** [comment] 2016-02-20 08:43
Thank you!

**Comment by borag** [comment] 2016-02-25 08:04
Thanks (By the way it also says not available for melpa but --insecure solved my all problems)

**Comment by dhruvinsh** [comment] 2018-09-06 12:47
Its happening again, 08:47 (EST) elpa.gnu.org is down
