### ISSUE TITLE
evil latex : paragraph object commands not working properly

### ISSUE THREAD

**Issue by adrsta** [syl20bnr/spacemacs#5581] opened 2016-03-24 13:47 UTC
#### Description
paragraph commands like `d a p` `d i p` `v a p` `v i p` do not work in latex-mode
(but work perfectly in Vim)

#### Reproduction guide
- download repoduction file
[evil_latex_paragraph_bug.txt](https://github.com/syl20bnr/spacemacs/files/187940/evil_latex_paragraph_bug.txt)
- rename extensiton to .tex (github doesn't allow .tex file for some reason )
- Start Emacs
- open atached file
- move cursor somewhere inside in  the second paragraph
- beign in normal state type `d a p`

#### Expected result
entire second paragraph should be  killed

#### Actual result
only current line was killed

**Comment by StreakyCobra** [comment] 2016-03-24 14:08
It depends on what is your notion of a paragraph. If a paragraph is a continuous area of text surrounded by empty lines in the raw buffer, yes it doesn't work as expected. If a paragraph is a text paragraph as it will be outputed by latex, it works as expected.

For instance using this file:

```tex
\begin{enumerate}
\item one
\item Pellentesque dapibus suscipit ligula. Donec posuere augue in quam. Etiam
  vel tortor sodales tellus ultricies commodo. Suspendisse potenti. Aenean in
  sem ac leo mollis blandit. Donec neque quam, dignissim in, mollis nec,
  sagittis eu, wisi. Phasellus lacus. Etiam laoreet quam sed arcu. Phasellus at
  dui in ligula mollis ultricies. Integer placerat tristique nisl. Praesent
  augue. Fusce commodo. Vestibulum convallis, lorem a tempus semper, dui dui
  euismod elit, vitae placerat urna tortor vitae lacus. Nullam libero mauris,
  consequat quis, varius et, dictum id, arcu. Mauris mollis tincidunt felis.
  Aliquam feugiat tellus ut neque. Nulla facilisis, risus a rhoncus fermentum,
  tellus tellus lacinia purus, et dictum nunc justo sit amet elit.
  \begin{itemize}
  \item a
  \item b
  \item c
  \end{itemize}
\end{enumerate}
```

with the cursor being in the middle of the text, `dip` delete the text paragraph, but not the surrounding enumerate or following itemize, what is the right behavior IMHO because they are not part of the notion of text paragraph:

```tex
\begin{enumerate}
\item one
  \begin{itemize}
  \item a
  \item b
  \item c
  \end{itemize}
\end{enumerate}
```

Anyway, this is not handled by Spacemacs, it can be reproduced by only enabling `evil` in a stock emacs. I'm closing this as it's not a Spacemacs issue, but feel free to report and discuss this upstream (to `evil` or `latex` not sure which side) if you think it's not the correct behavior.

**Closed by StreakyCobra** 2016-03-24 14:08 UTC
Labels: - Bug tracker -, Evil, LaTeX

**Comment by adrsta** [comment] 2016-03-24 14:34
Ok, thanks for explanation! In that case I guess evil is the problem, because it is supposed to mimic Vim (including it's notion of paragraph).

**Comment by StreakyCobra** [comment] 2016-03-24 14:39
If you open a discussion upstream you can put a link to it here, it may help other people finding this thread to look further :-)

**Comment by adrsta** [comment] 2016-03-24 15:44
https://bitbucket.org/lyro/evil/issues/595/selecting-paragraphs-in-latex-mode
:|
