### ISSUE TITLE
emacs27 now follows XDG convention for init-files, breaks spacemacs

### ISSUE THREAD

**Issue by samhedin** [syl20bnr/spacemacs#12679] opened 2019-08-31 15:20 UTC
https://github.com/emacs-mirror/emacs/blob/172b99a43ab60dac29eb09231246793a1ab32343/etc/NEWS#L138

This change made spacemacs stop working for me, which is not super surprising. Cloning spacemacs to ~./config/emacs instead seems to have done the trick.
`git clone -b develop https://github.com/syl20bnr/spacemacs ~/.config/emacs`

Can someone else who is using emacs 27 try the fix, assuming they have issues?
If that's all there is to it, maybe the readme can be updated with info for people who are on emacs 27? 

Thanks to the great people on gitter who helped find this!

**Comment by marienz** [comment] 2019-09-01 11:59
Emacs is supposed to keep using ~/.emacs.d if ~/.config/emacs is not present (see https://lists.gnu.org/archive/html/emacs-devel/2019-09/msg00000.html), although it looks like that might've been buggy at first.

With Emacs 27 built from e8c46c2b6f76cc055366041b6112d61dd5f2dcf4, I currently cannot get Spacemacs to start. Backtrace:

```Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-directory-p(nil)
  custom-theme--load-path()
  custom-available-themes()
  (cons 'default (custom-available-themes))
  (defconst emacs-built-in-themes (cons 'default (custom-available-themes)) "List of emacs built-in themes")
  eval-buffer(#<buffer  *load*-748074> nil "/home/marienz/.config/emacs/core/core-themes-suppo..." nil t)  ; Reading at buffer position 387
  load-with-code-conversion("/home/marienz/.config/emacs/core/core-themes-suppo..." "/home/marienz/.config/emacs/core/core-themes-suppo..." nil t)
  require(core-themes-support)
  eval-buffer(#<buffer  *load*-81521> nil "/home/marienz/.config/emacs/core/core-spacemacs.el" nil t)  ; Reading at buffer position 699
  load-with-code-conversion("/home/marienz/.config/emacs/core/core-spacemacs.el" "/home/marienz/.config/emacs/core/core-spacemacs.el" nil t)
  require(core-spacemacs)
  (let ((file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start)))))
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (let ((file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start))))))
  eval-buffer(#<buffer  *load*> nil "/home/marienz/.config/emacs/init.el" nil t)  ; Reading at buffer position 1880
  load-with-code-conversion("/home/marienz/.config/emacs/init.el" "/home/marienz/.config/emacs/init.el" t t)
  load("/home/marienz/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157c9a8349f1>) #f(compiled-function () #<bytecode 0x157c9a834a05>) t)
  command-line()
  normal-top-level()
```

The problem is that `(custom-available-themes)` fails because `custom-theme-directory` is nil. `custom-theme-directory` defaults to `user-emacs-directory`, so this looks like fallout from changing that to be a variable (see https://debbugs.gnu.org/cgi/bugreport.cgi?bug=583#65). `(custom-available-themes)` fails for me in `emacs -Q` too, so I think it's an upstream Emacs bug, just one Spacemacs hits because it calls that function during initialization.

**Comment by colbell** [comment] 2019-09-02 00:06
This now seems to be fixed in the emacs source.

 I'm using the emacs-snapshot ppa for Ubuntu and the latest version emacs-snapshot - 20190901:98531-ba12c54~ubuntu19.10.1 is now loading successfully from ~/.emacs.d whereas the previous version wasn't.

**Comment by marienz** [comment] 2019-09-02 14:24
Looking at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37256 this should be fixed.

Looks like Spacemacs might want to mention the new $XDG_CONFIG_HOME/.emacs in its install instructions. The first time Emacs 27 starts without ~/.emacs.d present, it creates ~/.config/emacs. Once that has happened, installing Spacemacs into ~/.emacs.d will have no effect: Emacs will see the new directory and use it, without looking at the old one. (Just tested it: stop Emacs, move ~/.emacs.d away, start and stop Emacs, move ~/.emacs.d back, start Emacs again, don't get Spacemacs. No need to customize anything, just starting and stopping suffices.)

Previous versions of Emacs had a similar issue with ~/.emacs, which is mentioned here: https://github.com/syl20bnr/spacemacs#default-installation. So I guess those instructions could mention the new location, either as one to back up or as one to preferably install into if Emacs is new enough to recognize it.

**Comment by samhedin** [comment] 2019-09-03 08:33
Yeah, that sounds good to me. I guess this can be closed? :)

**Comment by MatthewZMD** [comment] 2019-09-04 12:42
Yes this can be closed.

**Closed** 2019-09-04 13:39 UTC
Labels: Fixed upstream
