### ISSUE TITLE
ycmd layer requires c-c++ layer

### ISSUE THREAD

**Issue by jynnantonix** [syl20bnr/spacemacs#1414] opened 2015-04-27 22:40 UTC
I don't use the c-c++ layer because it messes with my own configuration.  However, it seems that the auto-completion layer requires c-c++ to work properly.  Otherwise it complains:

    Error (use-package): company-ycmd :init: Symbol's value as variable is void: company-backends-c-mode-common

It should be possible to use auto-completion without requiring the c-c++ layer as well.

**Comment by trishume** [comment] 2015-04-27 22:52
It's not `auto-completion` that requires `c-c++`, it is the `ycmd` layer.

**Comment by jynnantonix** [comment] 2015-04-27 22:56
Ah you're right, my mistake.  Still, it should be possible to use ycmd without having to use the c-c++ layer as well.

**Comment by trishume** [comment] 2015-04-28 01:05
That's something that isn't possible or at least easy thanks to the new auto-completion architecture.
You might be better off overriding or using the ability to exclude packages to use the `c-c++` layer but not have it stomp your stuff.

**Comment by syl20bnr** [comment] 2015-04-28 01:30
Thank you for the report. This is fixed in `develop`. C/C++ specific configuration has been moved to `c-c++` layer in `post-init` functions. Using `ycmd` layer should correctly use the `company-ycmd` backend instead of `company-clang`.
Note that `ycmd` _and_ `auto-completion

**Comment by trishume** [comment] 2015-04-28 02:35
This solves the error message, but not the specific problem of wanting to use `ycmd` without `c-c++`. Although in this case I think maybe we should close the issue anyways because it is a bit of an unusual request and perhaps something @jynnantonix should hack together himself rather than something Spacemacs supports.

This change does make it easier though. Just don't include the `c-c++` layer and then in your personal configs just push `company-ycmd` onto the global `company-backends`.

**Comment by syl20bnr** [comment] 2015-04-28 02:46
The title of the issue is `auto-completion layer requires c-c++ layer`, it is fixed.

Now enabling `company-ycmd` for another language is another question for another issue and it is like you said which is basic company configuration stuff.

**Comment by syl20bnr** [comment] 2015-04-28 02:47
Well I should rename the title :-)

**Comment by naseer** [comment] 2015-04-28 20:02
on the master, I'm seeing two popup errors from flycheck - one from ycmd and another from somewhere else (clang? semantic? ) is this issue related?

**Comment by trishume** [comment] 2015-04-28 20:51
@naseer probably not.

**Comment by tuhdo** [comment] 2015-04-28 20:56
@naseer What is the popup errors? `semantic` does not check your code so it is excluded. Probably there are two clang checkers being used: one from `ycmd` and one from `flycheck` built-in clang checker.

**Comment by naseer** [comment] 2015-04-28 22:40
@tuhdo - just two popups together. flycheck clang doesn't work on it's own (I didn't configure the .clang_complete)
 I will post a gif in a new bug.

**Comment by tuhdo** [comment] 2015-04-28 22:48
You don't need to add `.clang_complete` for clang checker to work. I don't use `ycmd` and have no such issue.

**Comment by naseer** [comment] 2015-04-28 23:43
@tuhdo - I do need the config file for it to work for my setup as my C++ files are cross compiled.

**Closed** 2015-06-01 03:44 UTC
Labels: Auto-completion, C/C++, Fixed in `develop`
