### ISSUE TITLE
Haskell-mode error: ghc-mod: unknown command: `map-file'

### ISSUE THREAD

**Issue by IanQS** [syl20bnr/spacemacs#2709] opened 2015-08-21 02:30 UTC
Sorry, Haskell-mode meaning the Haskell stuff listed here https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/haskell#install

**Comment by Ikyushii** [comment] 2015-08-21 10:35
I had the same issue, but I think I fixed it by using melpa-stable package instead of melpa.

**Comment by ocecaco** [comment] 2015-08-21 11:04
The problem is that ghc-mod 5.3.0 does not support the "map-file" command when using ghc-mod legacy-interactive.

This has been fixed in kazu-yamamoto/ghc-mod@e0044a369 . Therefore compiling ghc-mod from master branch on GitHub should fix the problem.

**Comment by massimo-zaniboni** [comment] 2015-08-21 22:44
A note for inexperienced users like me: I put into ~/nixpkgs/config.nix, this content

```
{
  packageOverrides = super: let self = super.pkgs; pkgs0 = super.pkgs; in {
      haskellPackages = super.haskellPackages.override {
        overrides = self: super: {
          "ghc-mod" = super."ghc-mod".overrideDerivation (attrs: {
            src = pkgs0.fetchFromGitHub {
              owner = "kazu-yamamoto";
              repo = "ghc-mod";
              rev = "e0044a3697b4ffa8c454c93c93711a3b1c0cc791";
              sha256 = "0i9h7kq23ss5afzdavwvh7h2abg9g6hcz2rwd9xyqbmm3k6ayrl1";
            };  
            nativeBuildInputs = [ super."cabal-helper" super.cereal ] ++ attrs.nativeBuildInputs;
            postInstall = ""; 
          });
        };
      };
  };
}
```

and then installed again the ghc-mod package, with

    nix-env -f "<nixpkgs>" --show-trace -iA haskellPackages.ghc-mod

When ghc-mod will be upgraded, you can remove the customization, and reinstall the default ghc-mod package.

**Comment by IanQS** [comment] 2015-08-21 23:52
@Ikyushii I'd do that but I already have ghc-mod installed via cabal and I'm not a fan of downloading duplicates.

@ocecaco Sorry, could you point me towards how I would do that via cabal? Because the version that I see when I look via cabal is still 5.3.0 and when I try to reinstall via cabal it doesn't actually do anything. 

@massimo-zaniboni I don't know if that'll work on my OS... I'm not on Nix

**Comment by ocecaco** [comment] 2015-08-22 00:19
@IanQS I don't think it's possible to do using Cabal, since the newest version on Hackage is 5.3.0.

What I did was remove the `.cabal` and `.ghc` directories to delete all my existing Cabal packages. (Not sure if there's an easy way to remove only ghc-mod). Then I ran

```
git clone https://github.com/kazu-yamamoto/ghc-mod
cd ghc-mod
cabal sandbox init
cabal install --only-dependencies
cabal build
```

After this there is a `ghc-mod` and `ghc-modi` binary in `ghc-mod/dist/ghc-mod` and `ghc-mod/dist/ghc-modi` directories respectively. You can either modify your PATH such that those directories are included, or just move the binaries to some directory in your PATH. (Personally I put them in `~/.cabal/bin`). There's no need to keep the `ghc-mod` directory created when cloning the ghc-mod repo after you've copied the executables to some other directory.

Also I'm not sure if the Emacs package which talks to `ghc-mod` is separate from `ghc-mod` itself, but you might have luck with @Ikyushii 's suggestion if you just reinstall the Emacs package and leave the ghc-mod from Cabal alone. (I don't really know enough about Emacs to judge if this would work)

**Comment by IanQS** [comment] 2015-08-22 01:03
@ocecaco Awesome! Turns out I didn't have to uninstall everything. I just needed to remove the executables (ghc-mod and ghc-modi) from .cabal/bin, and the ghc-mod and ghc-modi from /.cabal/packages/hackage.haskell.org.

I then followed your instructions (moving just the executables into .cabal/bin and things worked so far. I'll post an update if anything breaks at some point

**Comment by boj** [comment] 2015-08-23 03:03
@massimo-zaniboni Thanks for the temporary fix there.

**Comment by obadz** [comment] 2015-08-27 10:36
I recognize my code in https://github.com/syl20bnr/spacemacs/issues/2709#issuecomment-133581686 -- feels good :)

**Comment by massimo-zaniboni** [comment] 2015-08-27 10:47
@obadz sincerely I had to add

    pkgs0 = super.pkgs;

and use it in

    src = pkgs0.fetchFromGitHub

otherwise your code, and some other example I tried to merge/use, was not working. I don't know Nix very well, and I'm not 100% aware of what I were doing, so if you see something of strange in the code, let me know...

**Comment by obadz** [comment] 2015-08-27 10:53
I use my overrides in a different file (default.nix for nix-shell). Now that ghc-mod was upgraded in hackage, the fix simplifies down to:

```nix
"ghc-mod" = super."ghc-mod".overrideDerivation (attrs: rec {
      src = pkgs.fetchFromGitHub {
        owner = "kazu-yamamoto";
        repo = "ghc-mod";
        rev = "e0044a3697b4ffa8c454c93c93711a3b1c0cc791";
        sha256 = "0i9h7kq23ss5afzdavwvh7h2abg9g6hcz2rwd9xyqbmm3k6ayrl1";
      };
    });
```

Spacemacs is still hanging on startup though, not sure why :-(

**Comment by massimo-zaniboni** [comment] 2015-08-27 10:58
@obadz ah ok, thanks for the clarification! One less mystery in my IT life :-)

> Spacemacs is still hanging on startup though, not sure why :-(

I don't know if it is the same problem, but if I open a *.hs file, Spacemacs seems blocked. Then I wait 1-4 seconds, in case something is working behind the scene, then press ctrl-g, and the file is opened, and I can use it, and I can have full access to the Haskell mode. Obviously this is only a work-around.

**Comment by obadz** [comment] 2015-08-27 11:06
Wow Ctrl+G works. Thanks!

Grrrr next problem: ghc-show-type does not work => "Cannot determine type"

**Comment by gregnwosu** [comment] 2015-08-28 18:04
Ikyushii this works!

**Comment by Ikyushii** [comment] 2015-08-29 08:05
@gregnwosu glad to hear it :).

**Comment by axg-ux** [comment] 2015-08-30 06:13
@Ikyushii what is exactly meant by using melpa-stable? How does changing a package source change the behavior of ghc-mod? I'm trying to fix the same problem.

**Comment by Ikyushii** [comment] 2015-09-01 07:51
melpa-stable is for stable packages, whearas malpa is for unstable one. So packages in melpa are more up to date, but less stable: API changes, for instance, happen.

So, rather than install the melpa package, you better install the melpa-stable package.

**Comment by TheBB** [comment] 2015-09-02 08:40
Closing since this is apparently fixed upstream.

**Closed by TheBB** 2015-09-02 08:40 UTC

**Comment by x-ji** [comment] 2015-09-03 11:41
@aug-ux To install a package from melpa-stable you can see https://emacs.stackexchange.com/questions/2969/is-it-possible-to-use-both-melpa-and-melpa-stable-at-the-same-time

Basically you can add melpa-stable to the list of sources and then use the alist `package-pinned-packages` to specify that `ghc` should be installed from melpa-stable instead of melpa.

Currently this seems to be the easiest fix, until the next version of `ghc-mod` gets out to Hackage it seems.
