### ISSUE TITLE
awk indentation broken

### ISSUE THREAD

**Issue by VMatrix1900** [syl20bnr/spacemacs#2103] opened 2015-06-24 08:27 UTC
As the picture shows, I am writing awk code using the awk mode.
But the indentation is wrong.
Try indenting the region. Still wrong.
The white region shouldn't exist.
![screen shot 2015-06-24 at 4 24 42 pm](https://cloud.githubusercontent.com/assets/3964947/8325658/d82c73f8-1a8d-11e5-945a-7b7006d9fe36.jpg)
![screen shot 2015-06-24 at 4 27 50 pm](https://cloud.githubusercontent.com/assets/3964947/8325681/11b040fa-1a8e-11e5-9156-226adc74b7fd.jpg)
![screen shot 2015-06-24 at 4 28 12 pm](https://cloud.githubusercontent.com/assets/3964947/8325682/11b23a86-1a8e-11e5-824d-297761b0f889.jpg)

**Comment by TheBB** [comment] 2015-06-24 08:49
I can't reproduce this. It looks like you have MMM-mode enabled. Have you tried turning that off?

**Comment by VMatrix1900** [comment] 2015-06-24 12:36
Turn mmm-mode off. Same problem.
BTW, I am using the develop branch.
![screen shot 2015-06-24 at 8 34 58 pm](https://cloud.githubusercontent.com/assets/3964947/8329961/8c24b056-1ab0-11e5-8e08-17c32b12e3fc.jpg)

**Comment by VMatrix1900** [comment] 2015-06-24 13:02
Turn off the mmm mode and restart spacemacs solve the problem. Don't know the reason.
When the mmm mode is on, run `evil-indent` once will add one more unnecessary indentation, run twice will add 2 more level indentation. Weird.

**Comment by syl20bnr** [comment] 2015-07-09 03:58
@VMatrix1900 Where did `mmm-mode` come from ?

**Comment by VMatrix1900** [comment] 2015-07-09 07:48
develop branch

**Comment by StreakyCobra** [comment] 2015-11-08 17:41
I tested it and indeed it comes from having `mmm-mode` enabled. This mode is not enabled for `awk` and there is no reason it should be, so I close this issue (it's also a pretty old one). In any case, feel free to open a new one in case of trouble :smile:

**Closed by StreakyCobra** 2015-11-08 17:41 UTC
Labels: bug :-(
