### ISSUE TITLE
Enable evil-execute-in-normal-state as a gateway to evil-mode in holy-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1394] opened 2015-04-26 17:22 UTC
I think this is the best way for Emacs users to experience Vim features i.e. text objects, folding (the default key bindings of `hs-minor-mode` are horrible).... That is, in the middle of editing, an Emacs user can execute a Vim command to do something with a text object and get back to editing with Emacs without having to switch mode.

**Comment by tuhdo** [comment] 2015-04-26 17:24
I suggest we replace `C-o` of stock Emacs with `evil-execute-in-normal-state` for consistency. An Emacs user can press `C-o o/O` to open line below or above anyway. We could also bind stock `open-line` to `SPC j o`.

**Comment by CestDiego** [comment] 2015-04-26 17:41
I find this useful but isn't `C-o` reserved for emacs users? D:

**Comment by tuhdo** [comment] 2015-04-26 17:42
That's why we give the command to `SPC j o`.

**Comment by CestDiego** [comment] 2015-04-26 17:43
But in holy mode `SPC` is not a preffix key is it? I think I didn't understand the proposal.

**Comment by tuhdo** [comment] 2015-04-26 17:56
In holy-mode, the default leader key is M-m and fuction like SPC.

**Comment by syl20bnr** [comment] 2015-04-27 02:16
To my mind a better approach is to you `ESC` then perform the action and hit `i` if required to go back in emacs mode.

For instance to insert a line below it is `ESC o` done.

**Comment by syl20bnr** [comment] 2015-04-27 02:17
What does `C-o` shadow ?
This would be handy indeed.

**Comment by CestDiego** [comment] 2015-04-27 02:17
ugh :( that takes to much movement of the hands :( that's the whole point of near home-row stuff.. `C-o o` is cool for example.

**Comment by CestDiego** [comment] 2015-04-27 02:18
C-o shadows `open-line`

**Comment by syl20bnr** [comment] 2015-04-27 02:21
I never had the need of such function :-) So we can shadow it. I don't know where to put this in the documentation though.

**Comment by CestDiego** [comment] 2015-04-27 02:23
In the *super sikrit tipz* section.

**Comment by tuhdo** [comment] 2015-04-27 06:55
I think we can put it in `better-defaults`.

**Comment by tuhdo** [comment] 2015-04-27 06:58
@syl20bnr I updated it to include this change in `better-defaults` along with documentation.

**Comment by StreakyCobra** [comment] 2015-11-11 21:38
As tuhdo implemented this change in `better-defaults`, the issue is solved. Closing.

**Closed by StreakyCobra** 2015-11-11 21:38 UTC
Labels: discussion, Holy-mode, Key Bindings
