### ISSUE TITLE
Autocompletion tooltips don't work on terminal

### ISSUE THREAD

**Issue by viccuad** [syl20bnr/spacemacs#4660] opened 2016-01-18 12:32 UTC
#### Description
Autocompletion tooltips don't show on terminal (yet they work on GUI).

Here it is the autocompletion tooltip in gui:
![autocompletion tooltip in gui](https://cloud.githubusercontent.com/assets/2196685/12391389/c3519b54-bde7-11e5-9703-f4d8c825559b.png).

#### Reproduction guide
- Start Emacs on terminal (`emacs -nw`).
- Be sure to have a minimal config to enable the tooltips:
  ```(auto-completion :variables  auto-completion-enable-help-tooltip t)```
- Open the `.spacemacs` file, write in buffer something that has a tooltip (such
  as auto-completion-return-key-behavior for example), autocomplete it, and 
  notice there isn't a tooltip for it (there is in GUI).

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: nil (rev. nil)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary)
 syntax-checking
 (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
 (colors :variables)
 evil-cleverparens evil-commentary evil-snipe vinegar tmux git c-c++ extra-langs html latex markdown vimscript cscope python django shell-scripts sql selectric speed-reading themes-megapack typography gnus)
```

#### Backtrace
I have enabled Debug mode and there isn't any error logged at the *Backtrace* 
buffer.

**Comment by robbyoconnor** [comment] 2016-01-18 12:38
`SPC hds` is helpful to provide for **ALL** reports.  Please read the following: https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report

**Comment by viccuad** [comment] 2016-01-18 12:56
Edited the report.

**Comment by StreakyCobra** [comment] 2016-01-18 13:07
:+1: Thanks @viccuad for the nice reporting and Thanks @robbyoconnor for the patrol :-)

**Comment by person808** [comment] 2016-01-18 18:06
Not a bug :) `company-quickhelp` only supports gui emacs.

**Comment by StreakyCobra** [comment] 2016-01-18 18:22
Thanks @person808.

@viccuad You may probably consider closing the issue then :-)

**Closed** 2016-01-18 19:23 UTC
Labels: as expected :P, Auto-completion, Running in terminal
