### ISSUE TITLE
golden ratio mode not functional

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#3232] opened 2015-10-02 06:58 UTC
**OS - Lubuntu 15.04**
**WM - XMonad**
**Emacs - 24.5.1**
**Spacemacs - v.0.104.2**

Earlier, when I switched between windows, `golden ratio` mode would automatically expand the currently active window at the expense of the other window(s). This is not happening since `Spacemacs 0.104.x`.
Now when I edit something in the active buffer and save the changes, then only, the buffer window gets resized.

**Comment by TheBB** [comment] 2015-10-02 15:04
I can't reproduce this, at least not on develop. Golden ratio seems to work fine. Does it work with the standard dotfile?

**Comment by aviralg** [comment] 2015-10-05 10:42
I also updated my emacs to the develop branch. Now it seems to work fine. I didn't check with the standard dotfile.

**Comment by TheBB** [comment] 2015-10-05 11:12
You mean the develop branch of Spacemacs or of Emacs?

**Comment by justbur** [comment] 2015-10-05 11:54
This might be dependent on the windows that are open. Some packages need to prevent golden-ratio from operating on certain windows, and there might be a package that is aggressive about doing this. In which-key, I had to disable golden-ratio while the which-key buffer is showing for example.

**Comment by conklech** [comment] 2015-10-17 00:05
I can reproduce this on both the 0.104 release and `develop` as of the time of this post. Switching between windows using, e.g., M-1, M-2, no longer triggers a rebalance. Certain activities in a frame, e.g. switching buffers with `SPC TAB`, do trigger a rebalance.

**Comment by StreakyCobra** [comment] 2015-11-05 20:06
@conklech In which modes are the two windows when you can reproduce this?

**Comment by conklech** [comment] 2015-11-09 20:24
@StreakyCobra One window in org mode, and the other in org-agenda mode. Some org-agenda actions would trigger rebalance.

Can no longer reproduce as of today's `develop`. Switching between org and org-agenda windows with M-1, M-2 now triggers rebalancing as expected.

**Comment by StreakyCobra** [comment] 2015-11-09 20:35
@conklech Glad to hear :smile: I tried it again on `master` and it's not working there, so `Fixed in develop` :relaxed:

**Closed** 2016-01-04 08:43 UTC
Labels: bug :-(, Fixed in develop, to be reproduced, Windows layout
