### ISSUE TITLE
After reopening the file within emacs session pipenv-activate stops working

### ISSUE THREAD

**Issue by chama-chomo** [syl20bnr/spacemacs#12729] opened 2019-09-14 18:41 UTC
#### Description :octocat:
After reopening the file within emacs session pipenv-activate fails

#### Reproduction guide :beetle:
- Start Emacs
- Have syntax-checking and python layers enabled
- Have python-pipenv-activate set to t
- Open a python file
- pipenv activates automatically
- Close the file with SPC-b-d
- Open the same file within same emacs session
- activating pipenv fails, en error is thrown

I tested this scenario also on fresh develop spacemacs installation, same happens

*Observed behaviour:* :eyes: :broken_heart:
After reopening the file pipenv activation fails with following:

```
pipenv --venv finished
File mode specification error: (user-error /home/xxx/.local/bin/pylint is no executable)
```

even though the file exists and is executable

When the file is open for the first time flycheck runs pylint from virt. env.
When the file is reopened again flycheck cannot find any pylint executable, even
though is exists in venv as well as main system.

Kind of W/A could be segtting 'pipenv-with-flycheck' to nil, then pipenv
activates, but if opening a file from a different project env doesn't change,
though it can be deactivated and re-activated to a proper one.

*Expected behaviour:* :heart: :smile:
pipenv activates regardless of how many times file gets re-opened within one emacs session

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a7e27370e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript helm
            (lsp :variables lsp-auto-configure t lsp-eldoc-hook nil lsp-ui-doc-enable t lsp-ui-doc-header nil lsp-ui-doc-include-signature nil lsp-ui-doc-position 'top lsp-ui-doc-max-width 120 lsp-ui-doc-max-height 40 lsp-ui-doc-use-childframe t lsp-ui-doc-use-webkit t lsp-ui-sideline t lsp-ui-sideline-enable t lsp-ui-sideline-ignore-duplicate t lsp-ui-sideline-show-symbol t lsp-ui-sideline-show-hover t lsp-ui-sideline-show-diagnostics nil lsp-ui-sideline-show-code-actions t lsp-ui-sideline-code-actions-prefix "" lsp-ui-peek-enable t lsp-ui-peek-peek-height 10 lsp-ui-peek-list-width 50 lsp-ui-peek-fontify 'always lsp-cache-candidates t lsp-clients-python-command
                 '("/home/cqs/.local/bin/pyls"))
            (python :variables python-backend 'lsp python-lsp-server 'pyls python-fill-column 99 python-enable-yapf-format-on-save nil python-sort-imports-on-save nil python-pipenv-activate t python-test-runner 'pytest python-auto-set-local-pyvenv-virtualenv nil)
            emacs-lisp json groovy dash
            (neotree :variables neo-vc-integration
                     '(face)
                     neo-autorefresh t neo-theme 'icons)
            (version-control :variables version-control-global-margin t version-control-diff-side 'left version-control-diff-tool 'diff-hl)
            git docker ansible plantuml salt markdown multiple-cursors org copy-as-format yaml search-engine csv html systemd confluence ranger dap
            (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory t auto-completion-enable-snippets-in-popup t spacemacs-default-company-backends
                             '(company-lsp company-anaconda company-files company-capf)
                             auto-completion-enable-help-tooltip t)
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by chama-chomo** [comment] 2019-09-21 16:57
with last pipenv package update things started working. Thanks

**Comment by chama-chomo** [comment] 2019-09-22 05:06
Actually, it still doesn't work when I set 'python-pipenv-activate' to t. My previous statement was mistaken because currently, I don't use this option. Nevertheless, my envs still get initialized when the file is opened. So there must have been something else that is triggering env initialization.

I've got this set in my .zshrc

>  export PIPENV_VENV_IN_PROJECT=1

**Comment by IngvarListard** [comment] 2019-12-10 20:12
I've experienced absolutely the same.

**Comment by chama-chomo** [comment] 2019-12-10 20:57
WA that helped me is to remove all system-wide checkers (pylint, flake8), so that emacs can find only those inside the virtual env.

**Comment by IngvarListard** [comment] 2019-12-11 13:32
Yeah, thanks a lot! It worked for me too.

**Comment by vonpupp** [comment] 2021-01-20 22:11
I have this same issue... @chama-chomo or @IngvarListard, could you please tell me how did you disable pylint and flake? This is very annoying. Thanks.

**Comment by chama-chomo** [comment] 2021-01-21 14:52
> I have this same issue... @chama-chomo or @IngvarListard, could you please tell me how did you disable pylint and flake? This is very annoying. Thanks.

if you installed it using pip, then `pip uninstall` should do. if you installed it using your package manager, use that one to remove those checkers.

**Comment by vonpupp** [comment] 2021-01-30 00:57
Thank you @chama-chomo. I thought there was a way to disable instead of uninstalling it. I rely on pipenv for other projects. This issue is quite annoying.

**Comment by lebensterben** [comment] 2022-04-01 14:03
closing now.

As pointed out by this [comment](https://github.com/syl20bnr/spacemacs/issues/12729#issuecomment-564254789), this is not really a bug, but a conflict caused by multiple python linters.

**Closed** 2022-04-01 14:04 UTC
Labels: Python
