### ISSUE TITLE
Evil-unimpaired fail to install

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#10783] opened 2018-05-31 07:16 UTC
#### Description :octocat:
Evil-unimpaired fail to install package :
(Spacemacs) Error: 
An error occurred while installing evil-unimpaired (error: (error Package lacks a "Version" or "Package-Version" header))
Skipping rebuild of /home/dde/.emacs.d/.cache/quelpa/packages/evil-unimpaired-20180525.83643.el
Error (use-package): Cannot load evil-unimpaired

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Installation fail :(

*Expected behaviour:* :heart: :smile:
Install evil-unimpaired

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 390462e36)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 helm emacs-lisp git markdown org neotree
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/usr/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil enable-flyspell-auto-completion t)
 syntax-checking shell-scripts php sql html javascript coffeescript
 (gtags :variables gtags-enable-by-default t)
 imenu-list yaml colors
 (version-control :variables version-control-global-margin t shell-default-term-shell "/bin/bash")
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/" mu4e-use-maildirs-extension t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LCMS2

**Comment by antonalekseev** [comment] 2018-06-01 15:19
Please, have a look at #10645.

**Comment by syl20bnr** [comment] 2018-06-04 05:43
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/10645

Feel free to re-open if needed 💜

**Closed by syl20bnr** 2018-06-04 05:43 UTC
Labels: - Bug tracker -, Duplicate ☝
