### ISSUE TITLE
Environment variable warnings

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#3920] opened 2015-11-23 03:29 UTC
I just updated my spacmeacs in develop branch. 
And emacs gave me a warning as follow:
Warning (emacs): You appear to be setting environment variables ("PATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .bash_profile or .zshenv.  Refer to your shell's man page for more info.  In future, exec-path-from-shell will not read variables set in the wrong files.

I have no idea what is going on about this. :(

**Comment by ntcong** [comment] 2015-11-23 06:48
Are you using OSX?

In OSX, program launch from Application/Dock/Spotlight doesn't inherit the interactive shell environment (.bashrc or .zshrc). So spacemacs have exec-path-from-shell in order to get PATH and GOPATH (not sure about other uses) from your shell rc.

exec-path-from-shell recently has a commit warning about the PATH setting in wrong file (it should be in bash_profile instead of bashrc)

**Comment by idoo** [comment] 2015-11-23 08:28
@ntcong do you have any ideas, how to fix it? move i moved PATH rows from .zshrc to .zshenv, but still receiving message. ( I'm oh my zsh user)

**Comment by magthe** [comment] 2015-11-23 08:45
I get this on Linux, but for `MANPATH`.

My shell of choice is *zsh*, and I'm using *antigen* and (parts of) OMZ.  (I saw OMZ mentioned in https://github.com/purcell/exec-path-from-shell/issues/34)

Anyway, `MANPATH` is actually unset in my setup (both *zsh* and *bash*), so I'm rather confused at this warning!

**Comment by ntcong** [comment] 2015-11-23 08:46
there's a running issue https://github.com/purcell/exec-path-from-shell/issues/34 . The commit is recent, so maybe there some edge cases.

**Comment by nixmaniack** [comment] 2015-11-23 09:06
There might be cases where some other utilities in your startup rc files are setting up environment variables. 
e.g in my case, after removing PATH, MANPATH etc, I was still getting this error. After analysing my rc file, I found `pyenv`, `rbenv` which modify and set PATH hence moving them to `.zshenv` in my case fixed this warning. 
So watch out for such tools.

**Comment by zhexuany** [comment] 2015-11-24 02:10
After I delete all PATH variable, then the warning vanishes.  I am currently using OSX and ZSH.

**Comment by magthe** [comment] 2015-11-24 08:42
How did you find out what caused it?

In my case it's `MANPATH`, and it's unset in *zsh*:

```
$ print $MANPATH

```

It's also unset in *emacs*, `getenv` tells me so.

So how would I go about finding where `exec-path-from-shell` gets its idea?

**Comment by StreakyCobra** [comment] 2015-11-24 08:42
I reopen this one to follow the upstream issue, as other poeple still has this problem

**Comment by nixmaniack** [comment] 2015-11-24 09:02
@magthe Check the suggestions on the upstream issue. Add this in your init file `(setq exec-path-from-shell-debug t)` which should give more information. I'm not sure what's the best place to put that in case of spacemacs, but I would try putting at the top of  `~/.emacs.d/init.el` just for the purpose of debugging.

**Comment by magthe** [comment] 2015-11-24 09:16
@nixmaniack The output isn't that easy to read:

```
Invoking shell /usr/bin/zsh with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${PATH-a7eb268137995dda67083d70138f6457}\" \"${MANPATH-a7eb268137995dda67083d70138f6457}\"")
Shell printed: "__RESULT^@/home/magnus/bin:/home/magnus/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl^@a7eb268137995dda67083d70138f6457TERM environment variable not set.
"
Invoking shell /usr/bin/zsh with args ("-l" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${PATH-efe416d259564be2f6e2e0d7d535e150}\" \"${MANPATH-efe416d259564be2f6e2e0d7d535e150}\"")
Shell printed: "__RESULT^@/home/magnus/bin:/home/magnus/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl^@efe416d259564be2f6e2e0d7d535e150"
```

Clearly the output for `MANPATH` is different, but not in any relevant way.  I'm also not sure what the stuff appended to the end of the variable names is supposed to be.

**Comment by magthe** [comment] 2015-11-24 09:37
And if I remove `MANPATH` from `exec-path-from-shell-variables` I get an error on `PATH`, with the debug print of:

```
Invoking shell /usr/bin/zsh with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s' \"${PATH-c93f10e5f78006bc62e3ba90fd24d74c}\"")
Shell printed: "__RESULT/home/magnus/bin:/home/magnus/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perlTERM environment variable not set.
"
Invoking shell /usr/bin/zsh with args ("-l" "-c" "/usr/bin/printf '__RESULT\\000%s' \"${PATH-6cd7100d2138e5fb980487ed417d9871}\"")
Shell printed: "__RESULT/home/magnus/bin:/home/magnus/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
```

Not sure if that gives further clues to what's going on.

**Comment by nixmaniack** [comment] 2015-11-24 10:02
@magthe I believe it would better if you report this upstream as they'd be able to help better. I'm afraid but I'm out of ideas here.

**Comment by magthe** [comment] 2015-11-24 12:14
@nixmaniack Sure thing :)  Thanks for your help this far.  Now I just hope upstream can sort it out.

**Comment by StreakyCobra** [comment] 2015-11-24 13:32
This warning really starts to annoy me. I can't make my `.zshrc`/`.zshenv` setup works with `exec-path-from-shell`, as the message suggest to. And I tried, trust me. So the workaround is to put the following line in your `dotspacemacs/user-init`:

```elisp
(setq exec-path-from-shell-arguments '("-l"))
```

The warning will be gone.

**Comment by magthe** [comment] 2015-11-24 13:37
:) I feel you!

I think the upstream attempt to push users in the direction of setting their paths properly for non-interactive shells (i.e. that they are identical to paths for interactive shells) was well-meaning but ultimately doomed to fail!

**Comment by StreakyCobra** [comment] 2015-11-24 13:41
I have the feeling we are not alone :-)

Indeed, and there are [valid reasons](https://github.com/purcell/exec-path-from-shell/issues/34#issuecomment-158928554) to have them different.

**Comment by auser** [comment] 2015-11-24 19:28
I definitely still have this issue too

**Comment by robbyoconnor** [comment] 2015-11-24 19:45
I fixed it by moving everything to ~/.zshenv

**Comment by gilbertkennen** [comment] 2015-11-25 00:05
This package solves PATH problems for OSX users and appears to not even do anything in other environments, but it is being loaded for everybody in spacemacs-base, perhaps it should only load for OSX or be moved to the osx layer?

**Comment by robbyoconnor** [comment] 2015-11-25 01:00
I mean it's not a bad thing to do this...

**Comment by Cifer-Y** [comment] 2015-11-25 03:26
@robbyoconnor When I moved all env to .zshenv, my spacemacs become very very slow... very strange

**Comment by syohex** [comment] 2015-11-25 07:09
This issue can be ignored by replacing `warn` function temporarily while `exec-path-from-shell` API is called as below.

```lisp
(defmacro ignore-warn (&rest body)
  (declare (debug t) (indent 0))
  `(cl-letf (((symbol-function 'warn) #'ignore))
     ,@body))

(ignore-warn
  (exec-path-from-shell-copy-env "PATH"))
```

**Comment by StreakyCobra** [comment] 2015-11-25 10:28
Isn't the code proposed [above](https://github.com/syl20bnr/spacemacs/issues/3920#issuecomment-159268197) simpler? It's also the workaround proposed by the `exec-path-from-shell` maintainer.

```elisp
(setq exec-path-from-shell-arguments '("-l"))
```

**Comment by syohex** [comment] 2015-11-25 12:23
If `-i` option is removed, then `.zshrc` or `.bashrc` is not loaded, because zsh/bash runs non-interactive mode. So if some users set environment variables only in `.zshrc` or `.bashrc`, exec-path-from-shell cannot get those environment variables and set them

**Comment by StreakyCobra** [comment] 2015-11-25 12:26
Make sense, I didn't look further as I don't use a lot of external tools.

**Comment by Jack091545** [comment] 2015-11-25 12:44
I understand the problem is that the environment variables need be changed in .zshenv, but what should do to fix it , is there any  response effective? T_T ,waste a whole night time. so sad!!!

**Comment by Jack091545** [comment] 2015-11-25 12:44
I understand the problem is that the environment variables need be changed in .zshenv, but what should do to fix it , is there any  response effective? T_T ,waste a whole night time. so sad!!!

**Comment by StreakyCobra** [comment] 2015-11-25 13:04
It seems `.zshenv` is the right place to define `$PATH` and `$MANPATH`, for being used both by interactive and non-interactive shells. `exec-path-from-shell` is trying to make people do this, by comparing both version and throwing a warning in case of difference. It's a good intention, but there are some drawbacks:

- People could be wanting to have different `$PATH` for [valid reasons](https://github.com/purcell/exec-path-from-shell/issues/34#issuecomment-158928554).

- Even when moving `$PATH` related stuff to `.zshenv`, some people [still have the warning](https://github.com/purcell/exec-path-from-shell/issues/34#issuecomment-159249697). I'm myself victim of this, and I don't know what to do more. Some suggest it can be `oh-my-zsh` related.

As there is no option to disable the warning, the current workarounds to remove it are:

- Adding `(setq exec-path-from-shell-arguments '("-l"))` to `dotspacemacs/user-init`, if you don't care about all this and don't have `$PATH` problem within spacemacs.

- [@syohex solution](https://github.com/syl20bnr/spacemacs/issues/3920#issuecomment-159522167) if you have `$PATH` problem within spacemacs, and don't want this warning.

- [@gilbertkennen suggested](https://github.com/syl20bnr/spacemacs/issues/3920#issuecomment-159444062) that this package is only useful for OS X users, so it can maybe be `excluded` from your `.spacemacs`. Not tested though, so we will have to check this, and if it is the case it can be moved to `osx` layer.

**Comment by purcell** [comment] 2015-11-25 18:37
> t seems .zshenv is the right place to define $PATH and $MANPATH, for being used both by interactive and non-interactive shells. exec-path-from-shell is trying to make people do this, by comparing both version and throwing a warning in case of difference. It's a good intention, but there are some drawbacks:
> 
>     People could be wanting to have different $PATH for valid reasons.
> 
>     Even when moving $PATH related stuff to .zshenv, some people still have the warning. I'm myself victim of this, and I don't know what to do more. Some suggest it can be oh-my-zsh related.
> 
> Well, you can do what the warning message say and move PATH and MANPATH related definition to you shell environment file (.bash_profile, .zshenv). If the message still appear or if you don't want to do this, as there is no option to disable the warning, the current workarounds to remove it are:
> 
>     Add (setq exec-path-from-shell-arguments '("-l")) to dotspacemacs/user-init, if you don't care about all this and don't have $PATH problems within spacemacs.
> 
>     @syohex solution if you have $PATH problems within spacemacs, and don't want this warning.
> 
>     @gilbertkennen suggested that this package is only useful for OS X users, so it can maybe be excluded from your .spacemacs. Not tested though, so we will have to check this, and if it is the case it can be moved to osx layer.

Hey all, author of `exec-path-from-shell` here. This change has been an experiment to encourage people to change their startup files for the better, but I don't want it to eat up lots of people's time figuring things out. So I'll figure out a way forward (which may involve dropping the warning), and in the meantime I've switched to a less obtrusive message, so the next version of the package which MELPA builds will not should at you so loudly. :-)

**Comment by purcell** [comment] 2015-11-25 18:37
> This issue can be ignored by replacing warn function temporarily while exec-path-from-shell API is called as below.

Please don't do that!

This change has been an experiment to encourage people to change their startup files for the better, but I don't want it to eat up lots of people's time figuring things out. So I'll figure out a way forward (which may involve dropping the warning), and in the meantime I've switched to a less obtrusive message, so the next version of the package which MELPA builds will not should at you so loudly. :-)

**Comment by StreakyCobra** [comment] 2015-11-25 19:10
@purcell Hi! Thanks for your message :smile: Glad to hear that it will be less obtrusive. It's a nice intention to do this and to inform the user about the future differences, as it will impact some installations. It makes sense to keep the check and the warning, but personally I would like it to be:

- Less obtrusive, like just a `message`; and/or
- Optional, like with a `(setq exec-path-from-shell-no-warnings '(interactive))` to disable it.

Also if I may ask, you wrote your package is useful because «This happens a lot on OS X». Do you know if your package is really only useful for OS X, or is it mandatory also in some windows or linux configurations?

**Comment by purcell** [comment] 2015-11-25 19:22
> Do you know if your package is really only useful for OS X, or is it mandatory also in some windows or linux configurations?

No, it's necessary in a number of environments, including some Windows and X11 setups. But I originally wrote it to get things working nicely on OS X. It should actually be safe to enable it on every platform.

**Comment by StreakyCobra** [comment] 2015-11-25 19:28
Ok, thanks for your response :+1:

**Comment by robbyoconnor** [comment] 2015-11-26 05:57
@purcell I switched it to squash the warning...what is the point of zshrc then?!

**Comment by purcell** [comment] 2015-11-26 09:08
> @purcell I switched it to squash the warning...what is the point of zshrc then?! I guess I should read up..

Visual niceties you can see in the terminal, like your prompt, or conveniences like aliases.

**Comment by StreakyCobra** [comment] 2015-11-26 15:34
Thanks to @purcell, this issue has been corrected upstream. Updating your packages will solve the warning problem.

I'm closing this issue, but feel free to open a new one in case of troubles, and link this one if you think it's related :relaxed:

**Closed by StreakyCobra** 2015-11-26 15:34 UTC
Labels: Reported upstream

**Comment by shangsunset** [comment] 2016-10-06 01:13
Hey @StreakyCobra, spacemacs noob here. Im on the latest spacemacs version, how do I update `exec-path-from-shell` in spacemacs to get rid of the warning? thanks.

**Comment by StreakyCobra** [comment] 2016-10-06 08:20
Something like this in `dotspacemacs/user-init` should probably work:

```elisp
(setq exec-path-from-shell-check-startup-files nil)
```

**Comment by purcell** [comment] 2016-10-06 08:22
@shangsunset Note also that the warning is there for a reason: the best fix is to set up your shell config files so that this warning is not reported. :-)

**Comment by shangsunset** [comment] 2016-10-06 14:31
@StreakyCobra @purcell  Thanks for your comment. I moved everything in `.zshrc` to `.zshenv` and the warning went away.

Is it ok to use `.zshenv` as `.zshrc` as the profile config file though? I only know that `.zshrc` is for interactive shell, does it mean that interactive commands shouldnt live in `.zshenv` and can only stay in `.zshrc`? If so, could you give an example command that can only stay in `.zshrc`?

Thanks again.

**Comment by purcell** [comment] 2016-10-08 05:37
@shangsunset Put environment variable settings that should affect scripts run non-interactively in `.zshenv`. Put stuff you need in interactive shells (ie. prompt, convenience functions etc.) in `.zshrc`.

**Comment by 97-109-107** [comment] 2017-03-04 23:54
When trying to avoid moving to ``zshenv`` I tried using @StreakyCobra's suggestion like so:
````
(setq gc-cons-threshold 100000000)


(defconst spacemacs-version          "0.200.7" "Spacemacs version.")
(defconst spacemacs-emacs-min-version   "24.4" "Minimal version of Emacs.")

(if (not (version<= spacemacs-emacs-min-version emacs-version))
    (message (concat "Your version of Emacs (%s) is too old. "
                     "Spacemacs requires Emacs version %s or above.")
             emacs-version spacemacs-emacs-min-version)
  (load-file (concat (file-name-directory load-file-name)
                     "core/core-load-paths.el"))
  (require 'core-spacemacs)
  (setq exec-path-from-shell-check-startup-files nil)
  (spacemacs/init)
  (spacemacs/maybe-install-dotfile)
  (configuration-layer/sync)
  (spacemacs-buffer/display-info-box)
  (spacemacs/setup-startup-hook)
  (require 'server)
  (unless (server-running-p) (server-start)))
````
Upon introducing ``(setq exec-path-from-shell-check-startup-files nil)`` I get the following message
earlier in startup:

````
(Spacemacs) Error in dotspacemacs/init: Symbol’s value as variable is void: f
````

I'm on ``master``.

**Comment by nixmaniack** [comment] 2017-03-05 06:20
@97-109-107 You edited wrong file. You're not supposed to edit `~/.emacs.d/init.el`. 

You should edit `~/.spacemacs` and in there in section `user-init` add `(setq exec-path-from-shell-check-startup-files nil)`

**Comment by 97-109-107** [comment] 2017-03-05 11:40
@nixmaniack Thank you for your help, I was a bit confused.

**Comment by dudelson** [comment] 2017-08-02 03:46
I'm sorry if this is a bad place to put this information but I was just debugging my emacs path and the problem turned out to be directly related to `exec-path-from-shell` and my `.zshenv` file. 

If you find that your emacs `PATH` does not match your shell's `PATH` and you're also:

1. running Arch Linux (although this could potentially also be a problem on other distros); and
2. using zsh, with your `PATH` set in `.zshenv`

then you probably have the problem described in purcell/exec-path-from-shell#40. The solution is to prevent `exec-path-from-shell` from invoking zsh as a login shell. You can do this by adding the following line to `dotspacemacs/user-init` (*not* `dotspacemacs/user-config`) in your `init.el`:

      (setq exec-path-from-shell-arguments '("-i")))

Hope this helps someone.

**Comment by mimischi** [comment] 2017-09-19 15:49
@dudelson Thanks! Small correction though, you need to drop the last `)`:
```(setq exec-path-from-shell-arguments '("-i"))```

**Comment by dudelson** [comment] 2017-09-20 03:54
@mimischi sharp eye! Thank you for the correction, I've updated my comment.

**Comment by kirk86** [comment] 2018-04-11 22:31
I started getting this error only when I moved `.bash_profile` from `~` to `~/.config/bashrc/.bash_profile`. Is there any way to update exec-path-from-shell to point to the new destination?

**Comment by purcell** [comment] 2018-04-12 08:56
> I started getting this error only when I moved .bash_profile from ~ to ~/.config/bashrc/.bash_profile. Is there any way to update exec-path-from-shell to point to the new destination?

@kirk86 `exec-path-from-shell` is meant to replicate the environment variables you see when you start your regular shell in a terminal, so this feels like it's missing the point a bit. That said, you _might_ be able to adjust `exec-path-from-shell-arguments` to get the effect you want.

**Comment by kirk86** [comment] 2018-04-12 09:58
@purcell thanks for the answer, could you provide a minimal example how to make `exec-path-form-shell-arguments` work if I move my `.bash_profile` to a custom location?

**Comment by purcell** [comment] 2018-04-12 19:50
@kirk86 Sorry, no: I'd just look in the `bash` man page to see if one can override the startup file with either a command line arg or by setting an environment variable.

**Comment by robbyoconnor** [comment] 2018-04-14 04:26
There is always symlinks ;)

**Comment by kirk86** [comment] 2018-04-14 16:41
@robbyoconnor I think it defeats the purpose, at least for me, since I want my `~` clean. If I use symlink then I'll still see `.whatever` in my `~` directory.

**Comment by robbyoconnor** [comment] 2018-04-14 19:31
I'm sure there is a config file somewhere to specify the location where
bashrc is located.

**Comment by kirk86** [comment] 2018-04-14 20:00
@robbyoconnor Sure there is but the problem since day 1. If I move `.bashrc` from `~` to some custom folder then we go back to what @purcell  described in the first place.

**Comment by robbyoconnor** [comment] 2018-04-15 11:41
Then just do a symlink for your bashrc...everything else can be done
differently

**Comment by purcell** [comment] 2018-04-16 08:02
@kirk86 see also [this comment](https://github.com/purcell/exec-path-from-shell/pull/79#issuecomment-381283092), in which I suggest a different approach to a user wanting something similar to you. It might be helpful.

**Comment by Leryan** [comment] 2018-10-02 12:43
Strangely enough, disabling the warning as @StreakyCobra said fixed another issue with Spacemacs resetting the $PATH variable inside emacs…

**Comment by dogweather** [comment] 2019-02-23 06:27
This workaround is still relevant: The Anaconda Python installer adds a bunch of setup to `.bashrc`.

**Comment by rthoma** [comment] 2019-04-20 00:07
I also have this issue. I'm running macOS 10.14.4, exec-path-from-shell 1.11 from Melpa-Stable, and emacs 26.1 built with Homebrew. When launching emacs from Terminal, I see the warning:

> You appear to be setting environment variables ("MANPATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .profile, .bash_profile or .zshenv.  Refer to your shell’s man page for more info.  Customize ‘exec-path-from-shell-arguments’ to remove "-i" when done, or disable ‘exec-path-from-shell-check-startup-files’ to disable this message.

Like some others above, I don't have a .bashrc or .zshrc. This warning only appears when I launch emacs from Terminal (but that's how I always launch it, so I see it all the time). [Note this is the graphical emacs from `brew cask install emacs`.] When started this way `getenv MANPATH` returns something that looks like junk: `6bd201b691ce99512ce97f2e4400fe0bSaving session...`. Another commenter above reported something very similar. When I launch emacs by clicking on the application icon, the warning doesn't appear. The command `getenv MANPATH` won't even execute in this case because it doesn't find a variable match. Before I updated some packages, it was returning something like `Not Set`, which is basically equivalent to no match. My `init.el` includes the lines: 

```(when (eq system-type 'darwin)
      (exec-path-from-shell-initialize))```

I'm a little confused why `exec-path-from-shell-initialize` is setting MANPATH when the application is launched from Terminal, but not when it's launched graphically? I also don't have a good feel for where the value used to initialize MANPATH is coming from. Any insight would be appreciated. Right now I'm thinking about just manually resetting MANPATH after `exec-path-from-shell-initialize` and suppressing the warning check, but I'd prefer a cleaner solution. Many thanks~

**Comment by purcell** [comment] 2019-04-20 00:19
> When started this way `getenv MANPATH` returns something that looks like junk: `6bd201b691ce99512ce97f2e4400fe0bSaving session...`. Another commenter above reported something very similar.

My guess from this (as the `exec-path-from-shell` author) is that your shell is non-standard, or is printing out extra text when asked to run commands. You can set `exec-path-from-shell-debug` and try again, which might provide clues in the `*Messages*` buffer.



> I'm a little confused why `exec-path-from-shell-initialize` is setting MANPATH when the application is launched from Terminal, but not when it's launched graphically?

It seems unlikely that this is what is happening, fwiw, but I'm not a Spacemacs user.

**Comment by purcell** [comment] 2019-04-20 00:21
(To clarify, try `M-: (setq exec-path-from-shell-debug t)` followed by `M-x exec-path-from-initialize`, then look in `*Messages*`)

**Comment by rthoma** [comment] 2019-04-20 00:27
Hey, many thanks for the quick reply. Here is the output of `exec-path-from-shell-initialize` with the debug option turned on:
```
Invoking shell /bin/bash with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${PATH-b34c8cfeb46bf6cf45f3a8172005c6a5}\" \"${MANPATH-b34c8cfeb46bf6cf45f3a8172005c6a5}\"")
Shell printed: "Restored session: Fri Apr 19 17:24:37 PDT 2019
__RESULT/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/sbin:/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10:/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10:/usr/local/Cellar/aspell/0.60.6.1_1/bin:/usr/texbinb34c8cfeb46bf6cf45f3a8172005c6a5Saving session...
...saving history...
...completed.
"
```

**Comment by purcell** [comment] 2019-04-20 00:49
Okay. Turns out this was [fixed in 2017](https://github.com/purcell/exec-path-from-shell/issues/41), but because you're using MELPA Stable, you don't have the fix. Despite maintaining MELPA, I don't use MELPA Stable myself, and don't generally recommend it. In any case, I've tagged a 1.12 release which should contain the fix once MELPA builds it.

**Comment by rthoma** [comment] 2019-04-20 01:00
Hey, thanks! I'll just pin `exec-path-from-shell` to MELPA instead of MELPA Stable in my use-package instructions.

**Comment by iburunat** [comment] 2020-05-12 08:11
Hi, I'm having the same "warning" problem. The issue is that moving all my environment variables (as suggested by the warning message) to .zshenv, does only solve the warning at the cost of messing with the operation of some packages (i.e., ob-ipython). I think the order or sourcing of the .bashrc/.zshrc, .zchenv, .zprofile files plays a role here, and so moving all $PATH variables to .zshenv could be overriding the previously working settings.
