### ISSUE TITLE
Magit: s in visual-state should call magit-stage-item

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#1462] opened 2015-05-01 10:49 UTC
Magit allows one to make very fine grained commits by visually selecting part of the diff in the `magit-status` buffer and then calling `magit-stage-item`, which is normally bound to `s`. However `evil-surround` currently overshadows this key in `visual-state`.

I tried

```elisp
(evil-define-key 'visual magit-status-mode-map (kbd "s") 'magit-stage-item)
```

which didn't fix the problem.

**Comment by tuhdo** [comment] 2015-05-01 12:23
hmm this is a serious problem since that `magit` feature is awesome. No wonder some Spacemacs Vim users are struggling with Magit.

**Comment by trishume** [comment] 2015-05-01 18:35
I manage to use s just fine in the default state of magit. I just spam it to stage everything.

Is it that you want to use evil visual state to say select 3 lines that pressing s should stage all of them? Can you do that with emacs regions?

**Comment by tuhdo** [comment] 2015-05-01 18:55
You can move point on any hunk, select part of it with a region then press "s" to stage only the region. And yes, it works in Emacs state.

**Comment by syl20bnr** [comment] 2015-05-02 02:52
I wonder when this regression was introduced, I was sure that it works because I use it sometimes but that's not the case even with `C-SPC` (what I'm used to use im magit). This regression may have been introduce with the evilified state. I'm looking into it.

**Comment by syl20bnr** [comment] 2015-05-02 04:41
Should be fixed in develop branch.
Note that it is better to use `v` instead of `V`, `V` has a side effect which put the point back to the beginning of the buffer.

**Comment by jupl** [comment] 2015-05-07 23:47
`s` and `u` is working great for staging/unstaging. Can we get discard as well? `K` is currently bound to `evil-lookup`.

**Closed** 2015-06-01 03:44 UTC
Labels: Fixed in `develop`, Git, regression :-(

**Comment by hafenr** [comment] 2015-06-01 20:19
Updating via the `[Update]` shortcut in the spacemacs main window didn't work initially. A complete reinstall did however indeed fix the problem on master. `s` is now working with selected lines.
