### ISSUE TITLE
Helm-swoop keyboard arrow keys broken when helm-full-frame is set to true

### ISSUE THREAD

**Issue by dtreiter** [syl20bnr/spacemacs#2157] opened 2015-07-01 19:45 UTC
_Steps to reproduce_:
- Open spacemacs
- Set helm-full-frame to t
- Do helm-swoop
- Try to use the up and down arrow keys to move between candidates

_Expected behavior_: Should move the selection up and down one line at a time.
_Current behavior_: Behaves unpredictably.

I'm not sure if this is an issue with spacemacs or with helm/helm-swoop. Please correct me if this should be opened on helm or helm-swoop.

**Comment by StreakyCobra** [comment] 2015-11-10 20:45
Can anyone reproduce this with a raw emacs? To know if it should be reported upstream or solved here?

**Comment by dlebrecht** [comment] 2016-06-20 09:59
differently than reported above, but probably the same bug. 

If i have in my .spacemacs, 
`(setq same-window-regexps '("."))`

helm-swoop get stuck in the first and last entries, using all available shortcuts. Removing that line solves the issue.

**Comment by tgroshon** [comment] 2018-01-09 16:39
I'm having this same issue since upgrading to `0.200.10`.  It doesn't occur in my `0.200.9` install on my other computer.

**Comment by davhanks** [comment] 2018-01-09 16:40
Same issue since upgrading to `0.200.10`. Cannot go up or down with arrows or other move commands.

**Comment by ngoue** [comment] 2018-01-09 16:40
Also having this issue in `0.200.10@25.2.1`.  Maybe related, swoop now defaults to full-screen mode too...

**Comment by tgroshon** [comment] 2018-01-09 17:26
Also, my `helm-full-frame` is set to `nil`. So it doesn't appear to be related to this problem.

**Comment by duianto** [comment] 2018-01-09 21:22
After setting `helm-full-frame` to `t`, and opening `helm-swoop`, then the first time one moves the selection, with either `C-j`, `C-n` or `<down>` (or the move up equivalent bindings), then the selection moves one line, as expected. 

But after the first time, then moving down doesn't move the selection, and moving up, moves the selection by two lines at a time.

It's as if the selection actually is on the line above the current visibly selected line.

Checking the key binding `S-C-h <down>` shows that it's bound to the expected command: `helm-next-line`, the same applies for the `<up>` binding which calls `helm-previous-line`.

I tried to replicate it without Spacemacs, by starting Emacs with the `--quick` argument, and pointing the `package-user-dir` variable, to the develop branchs' packages directory:
`(setq package-user-dir "~/.emacs.d/elpa/26.0/develop/")`
`M-x package-initialize`
`S-M-; (setq helm-full-frame t)`
`M-x helm-swoop`

But the helm-swoop buffer doesn't fill the frame, it only takes up the bottom half, the same way as when the `helm-full-frame` variable is set to `nil`.
Moving the selection down `C-n`, `<down>`, or up, moves one line at a time, as expected.

I don't know what additional settings/commands are needed to get `helm-swoop` to fill the frame, outside Spacemacs.

**Comment by duianto** [comment] 2018-01-11 11:51
The cursor can also be moved up or down once, in a full frame HELM Swoop, after pressing either:
`M-<` which calls: `helm-beginning-of-buffer` or
`M->` which calls: `helm-end-of-buffer`

Any following single line navigation key presses, have the same broken behaviour, of not moving down, and moving up two lines at a time.

**Comment by ngoue** [comment] 2018-01-16 23:56
Reloading the `.spacemacs` file fixes it (among other issues) for me: `SPC f e R`.  You have to reload it after every startup.  Not sure what reloading does differently than the normal startup, but maybe that helps.

**Comment by davidar** [comment] 2018-03-14 09:09
I'm also seeing this bug occur when neotree is open (`SPC p t`). Can confirm that reloading `.spacemacs` fixes the issue - does anyone know why this is the case?

**Comment by tgroshon** [comment] 2018-04-24 00:11
I also confirm that when neotree is open, swoop navigation is broken, but when you close neotree it works.  Also by reloading `.spacemacs`, issues (even other issues with Neotree e.g. creating files) are fixed.

**Comment by tgroshon** [comment] 2018-04-24 00:16
@syl20bnr @StreakyCobra  I would suggest tagging this with `Neotree` because evidence seems to say it's related.  See last few comments.

**Comment by surgeboris** [comment] 2019-09-17 22:57
I'm also encountering this issue even though I don't have `neotree` loaded, and `treemacs` also does not seem to affect the issue in any way.

For me it pretty much same as described in [this comment](https://github.com/syl20bnr/spacemacs/issues/2157#issuecomment-356418330) with the only exception that I don't have `helm-full-frame` set to `t`.

There's two more important details I've spotted:

1. issue is only reproduced when I have a single window (when I have two windows side-by-side both `<C-n>` and `<C-p>` are working correctly)
2. issue is not there when I run Spacemacs without my personal customizations (I failed to find anything helm-related in my customizations though)

I tried to debug this issue and found out that this issue is related to the way swoop buffer is opened:
1. `helm-swoop.el` explicitly uses "split-window-..." + "switch-buffer" combination
2. [spacemacs overrides it since 2014](https://github.com/syl20bnr/spacemacs/commit/1326943321bdd5a1a402dcb0d046a215767f016a);  although the reason for that isn't entirely clear for me I suspect it was  [something like this](https://github.com/syl20bnr/spacemacs/issues/4117#issuecomment-163700921)  (but why commit dates back to 2014 and issue is created in 2015 then?)
3. as a result of spacemacs override we have `helm.el` internally calling `display-buffer` as opposed to default "split-window-..." + "switch-buffer"
4. for some reason `helm.el`'s call to `display-buffer` does not result into actual window split - swoop buffer is opened in the only window
5. when you open swoop buffer in the only window - you have this issue with `<C-n>` and `<C-p>` (I suspect it is caused by failed attempts to move point in other non-existing window). This is something that could potentially be reported upstream, although I doubt it is something that helm-swoop maintainers should support
   
I'm trying to debug the reason behind [4], but `display-buffer` is too complex for me, and I doubt that I'll find a plausible solution there.

Meanwhile the easiest way to fix it is to disable the override (see [2]). However I cannot do that, since I do not know the exact reason behind it. @syl20bnr can you clarify what you were trying to achieve with it 5 years ago? 😝

**Comment by syl20bnr** [comment] 2019-10-19 13:57
@surgeboris pheeew hard one :-) I don't remember more than the comment on top of the override unfortunately.
If it works for you by disabling the override then feel free to open a PR and ask people to try in their config, ping me on the PR as well if you do it. Thank you for the investigation.

**Comment by surgeboris** [comment] 2019-10-19 15:36
> If it works for you by disabling the override

It worked for me by resetting `pop-up-windows` to default `t` (instead of `nil` coming from my `custom-file`).

> I don't remember more than the comment on top of the override unfortunately.

At the time of the investigation I failed to understand what "behaves like helm" means, so I asked you for clarifications. But now I'm starting to realize that this commit message actually tells it all: you wanted swoop window to behave consistently with the rest of the helm popups and follow generic helm settings. E.g. I'm now using `(setq helm-split-window-default-side 'right)` to always open all the helm popups (including `helm-swoop`) to the right from the current window; without the override I would have to specify a setting for `helm-swoop` separately.

> feel free to open a PR

Given the new-found perspective above I'm having a split feelings for disabling the override:
- on one hand it will prevent `helm-full-frame` and `pop-up-windows` settings from breaking the `helm-swoop`;
- on the other hand it will make a special case out of the `helm-swoop` popup, so users will have to configure it separately even though they want it to behave as rest of the helm windows do;

I'm fine with keeping things as they are right now since "it works for me".

> Thank you for the investigation.

Thank you for Spacemacs!

**Comment by calmofthestorm** [comment] 2020-10-21 00:36
This still reproduces at 0284f8037593d725a393ee566ba45387fa7db0f2 on develop with default .spacemacs (evil mode, standard distribution). Just opened an org file, helm swoop works fine, set helm-full-frame to 't, and the arrows get "stuck" after a few up and down.

**Comment by surgeboris** [comment] 2020-10-21 01:02
@calmofthestorm Last time I checked it - it wasn't possible to use `helm-swoop` with `helm-full-frame` due to implementation details of `helm-swoop`. Now, you can try to persuade `helm-swoop` maintainers to change that, but why you would even want to do that in the first place?

The whole point of `helm-swoop` is to be able to **simultaneously** navigate both: your file buffer and your search results buffer (see the screencast on [their README.md](https://github.com/emacsorphanage/helm-swoop/blob/701c0f33b1045e70a8233b4981ca965ac5f6c887/README.md)). When you only navigate search results buffer opened full-screen it's no longer **simultaneous** navigation, so it functionally equivalent to ordinary search (i.e. `<C-S>` in holy mode or `/` in vim normal mode). Why do you want to use `helm-swoop` when ordinary search is enough?

**Comment by dtreiter** [comment] 2020-10-21 01:39
Original bug reporter here. I don't really use spacemacs nowadays and don't mind if you decide not to fix this if it's difficult / infeasible / outside the scope of spacemacs - not sure how others feel. I think I originally ran into this because I had turned on `helm-full-frame` to workaround being on a small screen.

A couple thoughts:
1) Someone might set `helm-full-frame` to true because they find value in it with other helm commands besides `helm-swoop`. However, setting it will also affect `helm-swoop`. Perhaps there's a work-around to make it not apply to `helm-swoop`.

2) > The whole point of helm-swoop is to be able to simultaneously navigate both

There are use cases for using `helm-swoop` where seeing the source buffer simultaneously is not necessary, and would not be easily replaced with incremental search. For example, what if I want to see everywhere a variable gets referenced within a file to get an idea of how it's used? Incremental search would not be ideal for this case since you must press 'next' repeatedly -- but `helm-swoop` works pretty well, even with `helm-full-frame` on. One could argue a better replacement would be something like using interactive grep on the current buffer or xrefs if your language has support for them.

I can imagine there being other use cases involving helm-swoop's editing features that would also make sense even with `helm-full-frame` on.

**Comment by calmofthestorm** [comment] 2020-10-21 02:05
* As dtreiter notes, the main problem is that setting helm-full-frame to 't for other helm commands does make sense, and doing so breaks helm-swoop.
* IMO simply ignoring the setting of helm-full-frame in helm-swoop would be a good solution.
* It is possible to invoke helm-swoop with helm-full-frame set to 't at 0284f8037593d725a393ee566ba45387fa7db0f2. It works as expected except for this bug.
* I do not agree that it is functionally equivalent to normal search if the source buffer is hidden. It hides non-matching lines making it easier to skim all matches, bypasses folding and the like (useful in org mode), and allows use of helm-swoop-edit, allowing you to use block select on non-consecutive lines.
* I can accept that this is out of scope/not worth making work for helm-swoop/spacemacs.
* I acknowledge that there are many other ways of doing each of the examples I give in Emacs (indirect buffers, folding, org-sparse-tree in org, etc).

**Comment by surgeboris** [comment] 2020-10-21 02:40
@dtreiter @calmofthestorm OK, guys, looks like you have compelling enough arguments to request "fullscreen-mode" from helm-swoop maintainers - feel free to do that if you really want `helm-swoop` in fullscreen. Personally I don't see much sense in it.

However, if you don't necessarily want to have `helm-swoop` full-frame, and it's good enough for you to just have `helm-swoop` ignoring full-frame setting (while keeping other helm buffers full-frame) - you really have a point here. It's definitely worth having commuinty-based solution for that on a Spacemacs level. So I made a PR https://github.com/syl20bnr/spacemacs/pull/14075/files - let's hope it will be merged soon.

**Comment by calmofthestorm** [comment] 2020-10-21 05:11
Thanks! I look forward to being able to use full frame mode for everything except swoop.

**Comment by duianto** [comment] 2020-10-22 17:55
The following PRs changes have been applied to the `develop` branch:
[helm-swoop] ignore `helm-full-frame' and `pop-up-windows' settings #14075

**Closed** 2021-08-24 02:20 UTC
Labels: Fixed in develop, Helm
