### ISSUE TITLE
"No org agenda currently displayed" when use `show clock report` in org-agenda

### ISSUE THREAD

**Issue by forrestchang** [syl20bnr/spacemacs#2621] opened 2015-08-11 15:30 UTC
I updated org-mode to 8.3 and then org-agenda can't work like before.

When use the `show clock report` function in org-agenda, the buffer will dead and can't use other functions. The message show "No org agenda currently displayed".

Hope someone can fix this bug:)

**Comment by forrestchang** [comment] 2015-08-11 23:52
Update:

When I reinstall org layer and it works again. The org version is 8.2.10, so I think 8.3 has some conflicts with other layers.

I install the layers below:

``` lisp
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom
            shell-default-term-shell "/bin/zsh")
     ;; syntax-checking
     version-control
     ;;auctex
     (colors :variables colors-enable-nyan-cat-progress-bar t)
     osx
```

**Comment by forrestchang** [comment] 2015-08-12 14:37
Update:
The problem occured again and the org-version is sitll 8.2, so maybe the bug is not occured by the version.

**Comment by sooheon** [comment] 2015-11-01 16:34
@forrestchang when I call `org-agenda`, I see the following:
![screen shot 2015-11-02 at 1 34 03 am](https://cloud.githubusercontent.com/assets/302945/10869956/d51b93e4-8101-11e5-865a-6758afd7cc1b.png)
There is no item `show clock report`. Calling org-clock-report works fine. Could you elaborate how to reproduce?

**Comment by forrestchang** [comment] 2015-11-02 14:21
@sooheon
I delete `.emacs.d` and reinstall `spacemacs`, the the bug disappered. You can try that.

**Comment by sooheon** [comment] 2015-11-02 14:32
Ah if the issue is no longer there for you, we should close it.

**Closed** 2015-11-02 14:33 UTC
Labels: bug :-(, Org
