### ISSUE TITLE
Error on update (0.102.2 -> 0.103.0): "Invalid version string 'nil'"

### ISSUE THREAD

**Issue by Peeja** [syl20bnr/spacemacs#2176] opened 2015-07-02 14:14 UTC
I'm on 0.102.2 and just saw the notification to update to 0.103.0. When I hit "[Update]" on the Spacemacs home buffer, I see

```
Updating Spacemacs... (for now only ELPA packages are updated)
--> fetching new package repository indexes...
```

and a whole lot of normal looking stuff flash by in the echo area, followed by the message

```
Invalid version string 'nil'
```

Afterwards, nothing appears to have updated. The process is repeatable, and restarting Emacs appears to make no difference.

**Comment by emmanueltouzery** [comment] 2015-07-02 16:21
this is a duplicate of https://github.com/syl20bnr/spacemacs/issues/839 -- the workaround given there worked for me.

**Comment by syl20bnr** [comment] 2015-07-04 05:14
I got this too, I will have a look next time I encounter it.

**Comment by Kernael** [comment] 2015-07-06 08:29
The workaround doesn't seem to work for me, on pressing 'x' I have the following error :

`package-menu-mode error "The current buffer is not in Package Menu mode" ...`

**Comment by sickill** [comment] 2015-08-03 11:07
I tried the workaround described in #839. It upgraded 64 packages. When I quit and started Emacs again it still says it's 0.102.x, and when I try "Update" again it still displays `Invalid version string: 'nil'` error.

**Closed** 2015-09-28 06:53 UTC
Labels: duplicate (-: :-), Fixed in `develop`
