### ISSUE TITLE
ag.el is not included in package

### ISSUE THREAD

**Issue by bgvianyc** [syl20bnr/spacemacs#3141] opened 2015-09-25 14:52 UTC
spacemacs includes projectile and helm which make use of ag.el (helm-do-ag) (projectile-ag - C-c p s s), but does not include the package necessary to run these commands, which is ag.el.

**Comment by justbur** [comment] 2015-09-25 16:17
Helm-ag is the package required for these commands, and yes it is included.

**Comment by TheBB** [comment] 2015-09-25 17:36
Indeed, and for the record, `helm-ag` does *not* depend on `ag`.

https://github.com/syohex/emacs-helm-ag/blob/master/helm-ag.el#L8

**Comment by TheBB** [comment] 2015-09-28 20:12
This is not a bug, so I'm closing this. If you have any actual problems with ag-related commands, please reopen.

**Closed by TheBB** 2015-09-28 20:12 UTC
Labels: question

**Comment by simendsjo** [comment] 2016-11-02 17:01
I'm having some issues here too. `ag` exists on my system (running `:!ag` lists the usage), and `helm-do-ag` and `helm-projectile-ag` works fine. `projectile-ag`, however, says `Package 'ag' is not available`.

**Comment by zachdaniel** [comment] 2016-11-11 00:36
Same here.  Any ideas?

**Comment by lvh** [comment] 2016-11-30 03:53
Same here; although I'm not sure if #7868 is a better description; there might be more than one issue at play.
