### ISSUE TITLE
json/init-json-navigator unintentionally causes some modes to open in evilified-state

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14645] opened 2021-04-15 09:55 UTC
#### Description :octocat:
`evilified-state-evilify-map tabulated-list-mode-map` in `json/init-json-navigator` causes some modes to open in `evilified` state.

#### Reproduction guide :beetle:
- add json (or javascript) layer
- Start Emacs
- start eww

Eww opens in `evilified` state while it should open in `normal` state.
This makes it impossible to type e.g. in the google search box.

*Observed behaviour:* :eyes: :broken_heart:
Eww opens in `evilified` state

*Expected behaviour:* :heart: :smile:
Eww opens in `normal` state

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: Fix-scheme-layer (rev. 53462d8b7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((org-wiki :variables org-wiki-location "~/Sync/org/wiki")
 command-log
 (latex :variables latex-backend 'company-auctex)
 auto-completion better-defaults emacs-lisp common-lisp
 (scheme :variables scheme-implementations
         '(guile racket))
 racket haskell git helm
 (ivy :variables ivy-enable-advanced-buffer-information t)
 lsp dap markdown multiple-cursors
 (spacemacs-evil :variables spacemacs-evil-collection-allowed-list 'nil)
 helpful rust python yaml javascript
 (org :variables org-directory "~/Sync/org" org-default-notes-file "~/Sync/org/notes.org" org-agenda-files
      '("~/Sync/org/google-calendar" "~/Sync/org/contacts.org" "/home/dalanicolai/Sync/org/journal" "/home/dalanicolai/Sync/org/journal" "/mnt/4EEDC07F44412A81/git/Masterthesis/TODOs.org" "~/spacemacs/diary.org")
      org-enable-notifications t org-start-notification-daemon-on-startup t org-enable-org-journal-support t org-journal-enable-agenda-integration t org-journal-dir "~/Sync/org/journal/" org-journal-file-format "%Y%m%d.org" org-journal-file-type 'weekly org-enable-roam-support t org-enable-templated-html-support t org-enable-github-support t org-enable-reveal-js-support t org-enable-org-contacts-support t org-contacts-files
      '("~/Sync/org/contacts.org")
      org-capture-templates
      '(("c" "Contacts" entry
         (file "~/Sync/org/contacts.org")
         "* %(org-contacts-template-name)\n          :PROPERTIES:\n          :EMAIL: %(org-contacts-template-email)\n          :PHONE:\n          :ALIAS:\n          :NICKNAME:\n          :IGNORE:\n          :ICON:\n          :NOTE:\n          :ADDRESS:\n          :BIRTHDAY:\n          :END:")))
 ebib
 (bibtex :variables bibtex-enable-ebib-support t ebib-preload-bib-files
         '("~/lib.bib")
         org-ref-default-bibliography
         '("~/lib.bib")
         bibtex-completion-bibliography
         '("~/lib.bib")
         org-ref-possible-bibfiles ebib-preload-bib-files org-ref-get-pdf-filename-function 'org-ref-get-zotero-filename)
 (google-calendar :variables org-gcal-client-id "" org-gcal-client-secret "" org-gcal-file-alist
                  '(("dalanicolai@gmail.com" . "~/Sync/org/google-calendar/dalanicolai.org")))
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control treemacs djvu
 (pdf :variables pdf-view-restore-filename "~/.spacemacs.d/.pdf-view-restore")
 toc
 (calibre :variables calibredb-root-dir "/mnt/4EEDC07F44412A81/Calibrebibliotheek" calibredb-add-delete-original-file "yes" calibredb-download-dir "~/Downloads" calibredb-fetch-covers "yes" calibredb-show-entry-switch 'switch-to-buffer-other-window calibredb-show-results t calibredb-title-width 84 calibredb-author-width 25 calibredb-tag-width 14 calibredb-comment-width 32)
 fasd html github eaf info)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment] 2021-05-09 21:17
The json layer is misbehaving here. It changes the default evil state for a general mode from which others derive hence forcing his setup to other layers. The intended behaviour was to define an evilified state for the json tree navigation mode instead.

I have removed the critical part of the code for now, I will have a look at this layer again this week as it seems that not all functions are still functional.

**Comment by smile13241324** [comment] 2021-05-09 21:17
@dalanicolai can you check if this change fixed your issue?

**Comment by dalanicolai** [comment] 2021-05-09 21:56
@smile13241324 Yes this fixes the issue...

**Comment by smile13241324** [comment] 2021-05-16 19:42
The layer has been fixed, therefore I am closing this ticket.

**Closed by smile13241324** 2021-05-16 19:42 UTC
Labels: Bug :-(
