### ISSUE TITLE
ci" doesn't work on ruby-mode

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#612] opened 2015-02-17 00:39 UTC
`"<CURSOR>hello world"`
Typing `ci"` at this point will result in an error: "Wrong Argument Type: integer-or-marker-p, nil". Works fine in other modes however.

**Comment by syl20bnr** [comment] 2015-02-17 01:09
duplicate of #441 
Seems that it is not related to spacemacs, someone on twitter had the issue before trying it.
I mark all these issues as duplicate but it is likely due to different things though.

**Comment by exitface** [comment] 2015-02-17 03:14
I actually figured out the issue - should have tested more. It was occuring becaue enh-ruby-mode was not being triggered on all valid ruby filetypes:

contrib/lang/ruby/packages.el [line 38]

```lisp
(defun ruby/init-enh-ruby-mode ()
  "Initialize Enhanced Ruby Mode"
  (use-package enh-ruby-mode
    :defer t
    :mode (("\\(rake\\|thor\\|guard\\|gem\\|cap\\|vagrant\\)file\\'" . enh-ruby-mode)
           ("\\.\\(rb\\|ru\\|builder\\|rake\\|thor\\|gemspec\\)\\'" . enh-ruby-mode))))
```
Should be capitallzed

```lisp
(defun ruby/init-enh-ruby-mode ()
  "Initialize Enhanced Ruby Mode"
  (use-package enh-ruby-mode
    :defer t
    :mode (("\\(Rake\\|Thor\\|Guard\\|Gem\\|Cap\\|Vagrant\\)file\\'" . enh-ruby-mode)
           ("\\.\\(rb\\|ru\\|builder\\|rake\\|thor\\|gemspec\\)\\'" . enh-ruby-mode))))
```

I can submit a pull req but wasn't sure if there was a better/idiomatic way to do that

**Comment by syl20bnr** [comment] 2015-02-17 03:26
They are regexp so `\\([Tt]hor\\)` should do it for instance.

**Comment by exitface** [comment] 2015-02-17 04:20
So you may have noticed I'm using enh-ruby-mode above. Versions beyond v0.60.0 that use ruby-mode rather than enh-ruby-mode. This still fail with the previous error, regardless of whether the regexp is changed. If I 1) replace ruby-mode with enh-ruby-mode 2) Change the regexp, it will work as expected. 

Lastly removing ruby from my configuration layers will cause it to reverting to the incorrect behavior, so it seems like it was something that enh-ruby-mode was adding to the pot?

**Comment by syl20bnr** [comment] 2015-02-25 02:51
I consider it fixed with the move to enh-ruby-mode.

**Closed by syl20bnr** 2015-02-25 02:51 UTC
Labels: <=(- UBO -)=>, duplicate (-: :-)
