### ISSUE TITLE
Using QUELPA for treating extensions as packages

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#2468] opened 2015-07-30 03:15 UTC
Old issue: https://github.com/syl20bnr/spacemacs/issues/5

Since `quelpa` is merged into MELPA: https://github.com/milkypostman/melpa/pull/2968, maybe it is the time to use `quelpa`, so we can add useful packages not on MELPA for layers.

**Comment by justbur** [comment] 2015-07-31 13:36
We could also use quelpa to support installing layers in third-party github repositories. This would allow people to try different implementations of the same layer and to help layer development progress faster before they are merged.

**Comment by syl20bnr** [comment] 2015-07-31 17:43
Thank you for notifying about this, this is a good news :+1: 

Be patient, I have some ground to prepare in core first :-)

**Comment by syl20bnr** [comment] 2015-07-31 17:43
Noted as a duplicate of #5

**Comment by TheBB** [comment] 2015-08-01 07:11
https://github.com/quelpa/quelpa-use-package/

**Comment by justbur** [comment] 2015-08-01 13:06
That looks perfect.

**Comment by CestDiego** [comment] 2015-08-01 13:29
:hype: I'm looking forward to this so

**Comment by syl20bnr** [comment] 2015-08-04 17:23
Indeed!
I'll look tonight to bootstrap quelpa in spacemacs so you can start to play with it :-)

**Comment by TheBB** [comment] 2015-08-04 17:56
:tada:

**Comment by CestDiego** [comment] 2015-08-04 18:12
Awesume :+1:  thanks @syl20bnr

**Comment by syl20bnr** [comment] 2015-08-05 02:35
This is pushed to develop. `:quelpa` and all its goodies should be available. :-)

**Comment by CestDiego** [comment] 2015-08-05 02:36
@syl20bnr how shall we do this? is it docummented?

**Comment by syl20bnr** [comment] 2015-08-05 02:43
For now it is not documented. You can read the documentation of the repo: https://github.com/quelpa/quelpa-use-package

**Closed** 2015-09-28 06:53 UTC
Labels: Core, duplicate (-: :-), enhancement :-D, Fixed in `develop`
