### ISSUE TITLE
Emacsclient in terminal closing itself on develop branch

### ISSUE THREAD

**Issue by perfectayush** [syl20bnr/spacemacs#4121] opened 2015-12-09 14:34 UTC
On the develop branch, when opening an emacsclient instance in terminal using "emacsclient -t", emacsclient closes unexpectedly. 
![emacsclient](https://cloud.githubusercontent.com/assets/1427611/11687819/e584c9f6-9eae-11e5-8514-7f3a945d5f93.gif)

This issue doesn't happen on the stable branch, and it doesn't happen when creating GUI Frames from the terminal using "emacsclient -c". There is no error in \*Messages\* buffer to debug this issue. I am using Emacs on OSX from http://emacsformacosx.com/

**Comment by agriffis** [comment] 2015-12-09 17:08
I'm suspicious this has the same underlying cause as #4120

**Comment by syl20bnr** [comment] 2015-12-10 00:39
Confirmed to be a duplicate of #4120

**Closed** 2016-01-04 08:34 UTC
Labels: bug :-(, duplicate (-: :-), Fixed in develop, High Priority, Running as daemon
