### ISSUE TITLE
Align Flycheck setup with Flycheck's setup instructions

### ISSUE THREAD

**Issue by lunaryorn** [syl20bnr/spacemacs#4782] opened 2016-01-24 16:09 UTC
To my surprise I recently noticed that Spacemacs does not follow Flycheck's setup instructions and does not use Global Flycheck Mode.  Instead it appears to `flycheck-mode` to individual mode hooks directly.  

Speaking as Flycheck's maintainer, I do not agree with this setup and strongly advise against it.  Global Flycheck Mode takes precautions to not enable Flycheck for buffers where it would not work or even be harmful, specifically remote files and encrypted files respectively.

I urge you to replace your current Flycheck setup with Global Flycheck Mode, and use the customisation option `flycheck-global-modes` to limit Flycheck Mode to particular major modes if you desire (though I can't see why you'd not want to enable Flycheck anywhere it's supported).

If you want to keep your current setup for whatever reason, at the very least use `flycheck-mode-on-safe` instead of `flycheck-mode` to take the same precautions as Global Flycheck Mode.  That'd not be our preferred solution, though.

To clarify, we consider Global Flycheck Mode as the **only official entry point** to Flycheck.

**Comment by robbyoconnor** [comment] 2016-01-24 16:24
It has yet to break on us and it seems to work

**Comment by syl20bnr** [comment] 2016-01-24 16:38
This is by design.
The layer architecture is aimed to bring as much isolation as possible. Global minor modes while very handy in a personal configuration is not ideal for a configuration at the scale of Spacemacs which integrates hundreds of packages.
It means that flycheck must be explicitly listed on the list of packages of each layer but this is on purpose. Layer as isolated and should ideally self contained which means that ideally looking at the list of packages of a layer tells me what it supported for it.
Thanks to this approach the syntax-checking layer can provide several packages but it does not decide what should be enable for what. It is the layer that enable the services provided by another layer depending on its needs.

We will change for `flycheck-mode-on-safe`, I did not know about it , sorry.
Thank you!

**Comment by syl20bnr** [comment] 2016-01-24 16:40
@lunaryorn  Sorry for the typos, if you read this via email, please visite github for an corrected version :-)

**Comment by syl20bnr** [comment] 2016-01-24 18:30
Some addition on this:
- any user can enable flycheck globally in their dotfile making it global explicitly. Company is in the same boat, see https://github.com/syl20bnr/spacemacs/tree/master/layers/auto-completion#enable-company-or-auto-complete-globally
- it should be possible to enable Flycheck even in packages where Flycheck is not explicitly supported by the layer but it seems there is a bug, pressing `SPC t a` in any buffer should enable the default syntax checker of choice of Spacemacs (ie Flycheck) :-(

**Comment by lunaryorn** [comment] 2016-01-25 17:45
@robbyoconnor With all due respect,

> it has yet to break on us and it seems to work

that's no argument.  Flycheck takes precautions for a reason.  

If you've never seen nightfall a car without lights will also *seem* to work.

@syl20bnr Well, I would argue that the purpose of a `syntax-checking` layer is to, well, enable syntax checking, for _all_ buffers where it's supported, and particularly for all those that Spacemacs doesn't have explicit layers for.  

> It means that flycheck must be explicitly listed on the list of packages of each layer on purpose. Layers are isolated and should ideally be self contained which means that looking at the list of packages of a layer tells me what is supported for it.

I'm not sure whether I can follow this argument.  I see what you're trying to tell me, but I think you could just as well reverse your arguments, i.e. argue that precisely because a language layer explicitly needs to enable syntax checking neither syntax checking nor the language layer are actually self contained.

Neither works without the other with regards to syntax checking: The former doesn't configure Flycheck to fit into Spacemacs, while the latter does not actually enable syntax checking where it's possible.

To me this mutual dependency indicates coupling (and rather tight one) rather than isolation.

I know that you do that for auto-completion as well, but I'd argue that it's even worse there: The `javascript` layer for instance even literally checks for the presence of the `auto-completion` layer.  That's no isolation, that's tight coupling, in my opinion.

In my opinion `global-flycheck-mode` in `syntax-checking` would actually *increase* the isolation between layers (likewise for Company).  

Your milage may vary, of course, and I know that I'm not in a position to change your ideas of layers, but I find it disappointing that you purposely and deliberately put a limit on the number of languages that Flycheck supports—many of which don't even have a Spacemacs layer at all—for the purpose of—errant, in my opinion—isolation, and I must admit that personally I find it hard to support this artificial limit on the scope of our extension.

**Comment by robbyoconnor** [comment] 2016-01-25 19:14
@lunaryorn If a language doesn't have a layer, then the major-mode isn't installed...then flycheck won't work even if it was set up correctly..

**Comment by lunaryorn** [comment] 2016-01-25 20:08
@robbyoconnor I'm sure you know about the means Spacemacs provides to install packages outside of layers, and about all the built-in major modes Emacs includes.

I can perfectly visit Texinfo files without any layer…

**Comment by robbyoconnor** [comment] 2016-01-25 20:33
Oh yes, that -- I guess I can see your point...

**Comment by Andre0991** [comment] 2016-01-26 03:25
> Well, I would argue that the purpose of a syntax-checking layer is to, well, enable syntax checking, for all buffers where it's supported, and particularly for all those that Spacemacs doesn't have explicit layers for. 

Going even further, I would say that syntax checking and auto completion should be transparent, ie automatically added to all programming languages layers.

Say I'm a new user. I want to use python in Spacemacs. Fine, I see python in the list of layers. I add it. Cool. Now let's open a `.py` file... wait. There's no completion. No syntax checking either. Have I really added the python layer? Humm...

(just my opinion, but I like the current design of layers too.)

**Comment by tuhdo** [comment] 2016-01-26 03:51
I agree with @lunaryorn that we should enable `flycheck` globally, as it checks for supported major modes to be activated in a buffer anyway, so it's useless to duplicate all the work again. There's no need to do that. Many Emacs major modes are built-in and have currently have no layer.

**Comment by TheBB** [comment] 2016-01-26 16:55
We had this discussion before, regarding company. https://github.com/syl20bnr/spacemacs/issues/1841 Essentially the same arguments are repeated here, and I'm not sure there's any point going through the same motions. I don't have any particularly strong opinion, but I can see the merit of @syl20bnr's stance.

**Comment by tuhdo** [comment] 2016-01-27 02:41
@TheBB but `flycheck` is different from `company`, as suggested by @lunaryorn . `company`, when globally enabled, it is everywhere, while `flycheck` is only activated in modes that it supports. So, what we are doing in Spacemacs is just redundant, and thus useless.

**Comment by TheBB** [comment] 2016-01-27 08:24
It's different, but @syl20bnr's argument didn't rest entirely on that.

I for one would find global syntax checking to be a nightmare. I don't understand why the *only* official entry point into the package should be a global mode that can only discriminate based on major modes and nothing else.

If I want syntax checking by default in rust but not in python, I would enable global flycheck mode and remove python from the list of modes. How then do I turn on flycheck when needed in a python buffer? If the only official entry point is global flycheck mode I don't see any option left for me but to use an unofficial entry point.

**Comment by tuhdo** [comment] 2016-01-27 08:32
> If I want syntax checking by default in rust but not in python, I would enable global flycheck mode and remove python from the list of modes. How then do I turn on flycheck when needed in a python buffer?

Why do you want to enable it again, since you first said that you don't want syntax checking in Python. If you meant that always disable Python syntax checking, but sometimes turn it on then you can turn on by simply running `flycheck-mode` command.

**Comment by TheBB** [comment] 2016-01-27 08:42
Yes that is what I meant. But according to @lunaryorn I shouldn't, because that's not an official entry point to flycheck.

I'm trying to make the point that this restriction from flycheck's side seems over the top.

**Comment by TheBB** [comment] 2016-01-27 08:43
> Why do you want to enable it again, since you first said that you don't want syntax checking in Python.

I like to code without the distraction of syntax checking. Every now and then I do some code cleanup, at which point I turn flycheck on.

**Comment by tuhdo** [comment] 2016-01-27 08:48
> Yes that is what I meant. But according to @lunaryorn I shouldn't, because that's not an official entry point to flycheck.

I think he meant that Spacemacs shouldn't enable `flycheck` manually per layer, but let Spacemacs takes care of that, for all major modes in and not in a layer.

> I like to code without the distraction of syntax checking. Every now and then I do some code cleanup, at which point I turn flycheck on.

If you enable syntax checking, `flycheck` is enabled in a major mode by default as whenever a layer supports `flycheck`. So, you still have to disable `flycheck` yourself (probably with `prog-mode-hook` or a variable in `syntax-checking` layer) if you want that workflow.

The point is that what Spacemacs is doing for isolation, is already done by `flycheck`.

**Comment by TheBB** [comment] 2016-01-27 08:55
I am doing that already, using the `syntax-checking-enable-by-default` variable. Yes, I understand that flycheck already supports disabling itself for specific major modes. Which is great. I would be happy to get rid of `syntax-checking-enable-by-default` for a more fine-grained variable.

Maybe I just don't understand what is meant by

> To clarify, we consider Global Flycheck Mode as the **only official entry point** to Flycheck.

How is this reconciled with

> then you can turn on by simply running `flycheck-mode` command

(Or `flycheck-mode-on-safe`, or whatever.)

Or in other words: if I am *officially* only allowed to use global flycheck mode, am I then *officially* not able (easily) to perform my current workflow?

**Comment by TheBB** [comment] 2016-01-27 09:03
Anyway I think this is a reasonable compromise:

* We remove the `syntax-checking-enable-by-default` variable and document `flycheck-global-modes` as a substitute.
* We change the hook function for flycheck to `flycheck-mode-on-safe`. (And we make this function autoloadable.)
* We leave the toggle as is, otherwise (if we change it to `flycheck-mode-on-safe`) people like me won't be able to selectively enable flycheck.

**Comment by robbyoconnor** [comment] 2016-01-27 09:09
:+1:

**Comment by lunaryorn** [comment] 2016-01-27 09:19
Folks, please hold on, and _ask me_ if there are unclear points.  Please don't jump to (absurd) conclusions too fast, and don't _guess_ what I could have meant.  Thanks.

@TheBB In the context of this issue I was talking about *non-interactive* entry points to Flycheck, obviously, because we're currently discussing how Spacemacs *non-interactively* enables Flycheck (i.e. in mode hooks).  Please be aware that the distinction between interactive and non-interactive use is very important in Emacs, and that a package can very well have different APIs for non-interactive and interactive use.  Simply speaking, Flycheck Mode is part of the "interactive" API of Flycheck, but not of its "non-interactive" API.

Interactive use of Flycheck is totally fine and you're of course free to interactively toggle Flycheck Mode in any buffer you like, for at this point you take a deliberately action and are (hopefully :blush: ) aware of the risks if any.

But's is just not safe or secure to enable Flycheck Mode in arbitrary buffers non-interactively (e.g. from a hook).  Global Flycheck Mode takes a number of precautions to ensure that Flycheck Mode is only enabled in "safe" buffers.

It's the only non-interactive entry point we support because globalized minor modes are the standard mechanism for this purpose, and we'd like to keep the public interface as small as possible to reduce the amount of support we have to provide to clients and to maintain freedom make whatever changes we deem necessary internally.  We consider `flycheck-mode-on-safe` internal API (hence no autoload).  We can't stop you from using it—and it's better than `flycheck-mode` at least—but at your own risk.

I'm unwilling to change my policy in this point, partially for said reason, but also because I'm personally disappointed to see Flycheck being artificially crippled for a reason that I can't follow.

**Comment by TheBB** [comment] 2016-01-27 09:42
> In the context of this issue I was talking about non-interactive entry points to Flycheck, obviously

Since the distinction was lost on me I can't agree that it was “obvious”, but okay. Then the following would seem to satisfy everyone, no?

* We remove the `syntax-checking-enable-by-default` variable and document `flycheck-global-modes` as a substitute.
* We set `flycheck-global-modes` to `nil` during `init-flycheck`.
* Instead of adding to a hook, we add a mode symbol to this list.

**Comment by TheBB** [comment] 2016-01-27 09:43
And of course I'm asking you. That's why I'm posting in this issue.

**Comment by TheBB** [comment] 2016-01-27 09:45
Actually there is another problem. Doing this would force flycheck to be loaded on startup.

**Comment by lunaryorn** [comment] 2016-01-27 10:09
@TheBB I don't think that I am not in a position to suggest how you could setup Flycheck.  

Please understand that I'd just like present Flycheck's point of view.  I've read over the arguments in #1841, and while I don't agree with much that was said there, I also have no intention to fight over chance.

If your priorities and aims conflict with those of Flycheck you may have to choose an approach that does not comply with what Flycheck recommends and supports. I can't say that I'd be happy with that, obviously, but I can perfectly accept that, as long as you are aware and have considered of our point of view and are willing to accept that our own priorities and aims imply that we can't always make allowances for Spacemacs needs in our development then.

----

With regards to loading, I don't think that it makes a difference whether you load Flycheck upfront or not: The first buffer is likely to load Flycheck anyway, even in your current setup.  You'd just shift around what's probably just a tiny percentage of the initial load time.

But your milage may vary, and I'm fine with that, see my comments above).

----

I've unsubscribed from this issue because I don't think that I can still contribute anything, and I believe that any further discussion leads anywhere.  Please mention me directly if you want me to read anything.  Thank you.

**Comment by syl20bnr** [comment] 2016-01-27 12:38
The conflict here is that layer proposes its own general way to selectively enable a mode for some others. 

As I said the automatic setup of Flycheck is convenient for personal configurations but it is not for the scale _and scope_ of Spacemacs. We need better abstraction _at the layer level_ without dealing with service internals. syntax-checking is syntax-checking in the abstract, sorry to say this but syntax-checking is not flycheck... like auto-completion is not company or auto-compete. The layer provides abstract service and we MUST stay decoupled to be able to stay agile and be able to propose new service back-ends (packages) that can come up in the future.

I will repeat what I said:
- enabling flycheck or company globally is an explicit move to be done by the user, Spacemacs won't impose them to the users.
- flycheck can (should) be enabled even in non explicitly configured packages by Spacemacs by pressing SPC t s and not here that I said flycheck but in fact SPC t s is referring to toggling _syntax-checking_ not flycheck

A precision I missed: we can disable a layer for other layers with `:disabled-for` keyword in the layer list. So it is possible to disable the syntax-checking services for say... Org layer, without knowing anything about the backend being flycheck.

@lunaryorn I understand your points and we'll make as much as we can to correctly handle flycheck at the layer level but global flycheck is up to the user to make this choice, not Spacemacs. I hope you understand this stance.

**Comment by lunaryorn** [comment] 2016-01-27 13:20
@syl20bnr I must admit that I don't, but don't care either.  I've told our point of view, Flycheck will stick to the aforementioned policy, and from now on its your choice.

**Comment by syl20bnr** [comment] 2016-01-27 14:04
And it's fine, Flycheck should provide what best fits regular Emacs users.
Spacemacs cannot use the global mechanism but it has the responsibility of selectively enable the mode correctly which should be addressed thanks to your recommendation about the safe method :+1:

**Comment by syl20bnr** [comment] 2016-01-27 14:20
The main point of friction here is the notion of service in Emacs and Spacemacs. And I would say that the raison d'être of Spacemacs relies a lot on the difference between a service in Emacs and a service in Spacemacs.

In Emacs the service unit is the mode, major and minor. It translates to package in the modern era of ELPA.

In Spacemacs the service is the layer that should hide the underlying Emacs services, or packages.

In this context at the Emacs level it makes sense for package authors to provide a global toggle for the service since Emacs only provide a very basic support for this via globalized modes.

At the Spacemacs level, a full framework for managing services is provided which directly make obsolete the lower level package service management. This framework is a generalization and can be applied to any package.

While in the Spacemacs word layers replace the need for package to provide their own activation mechanism, this mechanism is still mandatory because packages must work with Emacs and that's 200% fine. But this is the source of the clash here.

Now why I said that this difference is at the heart of the existence of Spacemacs ?
Because with the rising of MELPA and the proliferation of packages we need a new level of abstraction to keep things manageable, ie isolated to be able to integrate them sanely and avoid bankruptcy.
I was calling this system Emacs-Crown but I drop it to implement it directly in my configuration which became Spacemacs.

Maybe this layer system could be interesting for Emacs itself. Maybe I post my ideas on the ML.

**Comment by lunaryorn** [comment] 2016-01-27 15:38
@syl20bnr Now, that's a very interesting point of view, and it absolutely helps to clarify your position.  

I'm still not sure whether I can really follow it—I'm approaching Spacemacs from a large single-file `use-package` configuration after all—but I see your point now.  

Probably Emacs needs an abstraction layer that provides modularisation and boundaries at a higher level than packages, e.g. something like "services" or so.  That's a new aspect that I failed to see hitherto, and a nice abstraction for arguing about this problem.

Thank you very much for taking the time to thoroughly explain your ideas about Spacemacs so well.  I feel honoured :blush:

**Comment by robbyoconnor** [comment] 2016-04-27 01:16
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67o9p-sj&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=-Cydtthj&invitationId=6130896983466004480








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67o9p-sj&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHe9ozhkOfTHgAAAVRVSb_Lj2IVM5_5bQQxQea_wM0KixG19mmjO1K5k_77AJHNTm21yhiq0IS7tyG8FiiMd8OOXcHlw1nWAHkoTjrpOm8h6woGYQUwo5We6DL7BYZXveC3eaWSUNas0qG4-nJeQFgKrD34NV1DX79U5KJklUI1zezZsrHUkqk060YgxpYnJnNJ&eid=0-ini67o9p-sj


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67o9p-sj&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by d12frosted** [comment] 2016-10-03 09:11
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 09:11 UTC
Labels: Enhancement ☺, Fixed in develop, Syntax-checking
