### ISSUE TITLE
Update annoyances

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#5200] opened 2016-02-23 16:00 UTC
This is a list of things I find annoying about "Update Packages". Some might be necessary, but I suspect that they're not. 

 1. Having to restart emacs: Is this really necessary? What problem does it solve? As far as I know updating through `list-packages` works fine without a restart, so why does spacemacs need a restart?

 2. No knowledge of dependencies: Every time `magit` updates with `with-editor` I have to update twice (2! restarts if you follow the spacemacs update procedure), because `with-editor` is deleted, which `magit` needs so `magit` fails to be installed the first time, requiring another restart.

 3. It's getting better but it is still difficult to keep track of what packages were updated and what their versions were. A simple  log would be really nice here (Ref #3798)

**Comment by TheBB** [comment] 2016-02-23 16:09
Another thing I would like (because I just experienced a need for it) is to be able to hold packages back from being updated.

**Comment by syl20bnr** [comment] 2016-02-23 16:45
1- This is necessary because of bugs we encountered when not doing so. The current process of updating package has been built empirically given the numerous bugs we got in the first end of 2-14 and beginning half of 2015. I never had any issue since then I use the `Udpate packages` button of Spacemacs.

2- Dependencies are handled by `package.el`.

3- We can much improve this indeed.

>  hold packages back from being updated

This is a planned feature in my todo list (I may know why you needed it :-D).

**Comment by syl20bnr** [comment] 2016-02-23 16:50
For the magit issue, it may be due to it being too smart by asynchronously updating itself to avoid the bugs we cannot encounter in Spacemacs. Let me find the thread about it. May or may not be related.

**Comment by justbur** [comment] 2016-02-23 16:50
> 2- Dependencies are handled by package.el.

Yes, which is why it refuses to install magit the first time.

 1. Update Packages
 2. Updates for with-editor and magit detected so these are deleted (well moved to rollback)
 3. Restart
 4. Spacemacs appears to process the to be installed packages in alphabetical order
 5. magit is scheduled to be installed first, but with-editor is not available so the install fails.
 6. with-editor installs fine
 7. Restart
 8. magit can now install because with-editor is available. 

5 seems completely unnecessary and avoidable. You could check that with-editor is about to be installed

**Comment by syl20bnr** [comment] 2016-02-23 16:51
See: https://github.com/magit/magit/pull/2156

**Comment by justbur** [comment] 2016-02-23 16:51
No, this is not the same issue. This is a spacemacs issue with the order in which packages are processed.

**Comment by syl20bnr** [comment] 2016-02-23 16:52
> magit is scheduled to be installed first, but with-editor is not available so the install fails.

Then it is an issue in magit dependencies decalaration, not Spacemacs.

**Comment by syl20bnr** [comment] 2016-02-23 16:52
> No, this is not the same issue. This is a spacemacs issue with the order in which packages are processed. 

Nope, dependencies are handled by `package.el`.

**Comment by justbur** [comment] 2016-02-23 16:53
```
Found 2 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: magit@git... [1/2]
An error occurred while installing magit (error: (error Unable to activate package ‘git-commit’.
Required package ‘with-editor-20160128.1201’ is unavailable))
--> installing dependency: with-editor... [2/2]
```

I can reproduce by deleting magit and with-editor and restarting

**Comment by syl20bnr** [comment] 2016-02-23 16:53
I repeat, this is an issue at the magit dependencies level.

**Comment by justbur** [comment] 2016-02-23 16:55
Ugh, no it's not, because when I restart magit installs fine. The dependencies are there and are being read correctly.

**Comment by justbur** [comment] 2016-02-23 16:55
There have been issues with magit's dependencies but this is not one of them

**Comment by syl20bnr** [comment] 2016-02-23 16:57
Nope there is something special about Magit at the dependency level, this is definitely not the issue of Spacemacs.

It it was then not only Magit would be impacted.

**Comment by syl20bnr** [comment] 2016-02-23 16:58
If you find another example of such error I can look at it.

**Comment by syl20bnr** [comment] 2016-02-23 17:00
Funnily enough the thread I linked to you mentioned magit and with-editor at the end... coincidence ?

**Comment by justbur** [comment] 2016-02-23 17:02
Suppose that it is a problem with package.el, why can't we avoid it?

with-editor in this case is literally next in line to be installed and spacemacs knows this.

**Comment by justbur** [comment] 2016-02-23 17:04
here's a full backtrace (by the way please use `condition-case-unless-debug` so we can get full backtraces with --debug-init)

```
Debugger entered--Lisp error: (error "Unable to activate package ‘git-commit’.
Required package ‘with-editor-20160128.1201’ is unavailable")
  signal(error ("Unable to activate package ‘git-commit’.\nRequired package ‘with-editor-20160128.1201’ is unavailable"))
  error("Unable to activate package `%s'.\nRequired package `%s-%s' is unavailable" git-commit with-editor "20160128.1201")
  package-activate-1([cl-struct-package-desc git-commit (20160130 649) "Edit Git commit messages" ((emacs (24 4)) (dash (20151021 113)) (with-editor (20160128 1201))) nil nil "c:/Users/burketje/.emacs.d/elpa/git-commit-20160130.649" ((:keywords "git" "tools" "vc") (:url . "https://github.com/magit/magit")) nil] nil deps)
  package-activate(git-commit)
  (if (version< emacs-version "24.3.50") (package-activate pkg (quote (0 0 0 0))) (package-activate pkg))
  configuration-layer//activate-package(git-commit)
  (while --dolist-tail-- (setq dep (car --dolist-tail--)) (configuration-layer//activate-package (car dep)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (configuration-layer//get-package-deps-from-archive pkg-name)) dep) (while --dolist-tail-- (setq dep (car --dolist-tail--)) (configuration-layer//activate-package (car dep)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (if (not (assq pkg-name package-archive-contents)) (spacemacs-buffer/append (format (concat "\nPackage %s is unavailable. " "Is the package name misspelled?\n") pkg-name)) (let ((--dolist-tail-- (configuration-layer//get-package-deps-from-archive pkg-name)) dep) (while --dolist-tail-- (setq dep (car --dolist-tail--)) (configuration-layer//activate-package (car dep)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (package-install pkg-name))
  configuration-layer//install-from-elpa(magit)
  (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (eieio-oset pkg (quote :lazy-install) nil)))) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg) (eieio-oset pkg (quote :lazy-install) nil)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name)))
  (condition-case err (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (eieio-oset pkg (quote :lazy-install) nil)))) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg) (eieio-oset pkg (quote :lazy-install) nil)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while installing %s " "(error: %s)\n") pkg-name err))))
  (if (package-installed-p pkg-name) nil (condition-case err (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (eieio-oset pkg (quote :lazy-install) nil)))) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg) (eieio-oset pkg (quote :lazy-install) nil)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while installing %s " "(error: %s)\n") pkg-name err)))))
  (let* ((layer (if pkg (progn (eieio-oref pkg (quote :owner))))) (location (if pkg (progn (eieio-oref pkg (quote :location)))))) (spacemacs-buffer/replace-last-line (format "--> installing %s: %s%s... [%s/%s]" (if layer "package" "dependency") pkg-name (if layer (format "@%S" layer) "") installed-count noinst-count) t) (if (package-installed-p pkg-name) nil (condition-case err (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name) (if pkg (progn (eieio-oset pkg ... nil)))) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg) (eieio-oset pkg (quote :lazy-install) nil)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while installing %s " "(error: %s)\n") pkg-name err))))))
  configuration-layer//install-package([eieio-class-tag--cfgl-package magit git (shell) nil elpa t nil nil nil nil])
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))
  (if noinst-pkg-names (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")))
  (let* ((noinst-pkg-names (configuration-layer//get-uninstalled-packages (mapcar (quote car) (object-assoc-list :name packages)))) (noinst-count (length noinst-pkg-names)) installed-count) (if noinst-pkg-names (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))))
  configuration-layer//install-packages(([eieio-class-tag--cfgl-package ace-link spacemacs-ui nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package ace-window spacemacs-ui nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package adaptive-wrap spacemacs-editing-visual nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package aggressive-indent spacemacs-editing nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package anaconda-mode python nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package atom-one-dark-theme dotfile nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package auctex latex nil (latex-extra) elpa t nil nil nil nil] [eieio-class-tag--cfgl-package auctex-latexmk latex nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package auto-compile emacs-lisp nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package auto-dictionary spell-checking nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package auto-highlight-symbol spacemacs-editing-visual nil (spacemacs-ivy) elpa t nil nil nil nil] [eieio-class-tag--cfgl-package avy spacemacs-editing nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package beacon dotfile nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package bind-key spacemacs-base nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package bind-map spacemacs-base nil nil elpa t pre nil nil nil] [eieio-class-tag--cfgl-package bookmark spacemacs-base nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package bracketed-paste spacemacs-editing nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package buffer-move spacemacs-ui nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package calfw dotfile nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package clean-aindent-mode spacemacs-editing nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package company auto-completion (shell) (python org latex emacs-lisp) elpa t nil nil nil nil] [eieio-class-tag--cfgl-package company-anaconda python nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package company-quickhelp auto-completion nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package company-statistics auto-completion nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package counsel spacemacs-ivy nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package csv-mode csv nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package cython-mode python nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package define-word spacemacs-language nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package desktop spacemacs-ui nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package diff-hl version-control nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package diff-mode version-control nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package diminish spacemacs-base nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package drag-stuff dotfile nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package ebib dotfile nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package ediff spacemacs-base nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package eldoc spacemacs-base nil (python emacs-lisp) elpa t nil nil nil nil] [eieio-class-tag--cfgl-package elisp-slime-nav emacs-lisp nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package esh-help shell nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package eshell-prompt-extras shell nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package eshell-z shell nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package ess ess nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package ess-R-data-view ess nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package ess-R-object-popup ess nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package ess-smart-equals ess nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package eval-sexp-fu spacemacs-editing nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package evil spacemacs-base nil (emacs-lisp spacemacs-base) elpa t nil nil nil nil] [eieio-class-tag--cfgl-package evil-anzu spacemacs-evil nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package evil-args spacemacs-evil nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package evil-cleverparens my-evil-cleverparens nil nil elpa t nil nil nil nil] [eieio-class-tag--cfgl-package evil-ediff spacemacs-base nil nil elpa t nil nil nil nil] ...))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))

```

**Comment by syl20bnr** [comment] 2016-02-23 17:05
I think the answer is in the thread I linked to you, we can try disabling asynchronous install of Magit (this is not done yet I believe).

**Comment by justbur** [comment] 2016-02-23 17:05
Nope, I'm convinced it's a spacemacs issue. Look at that backtrace. You're trying to activate git-commit before with-editor is installed

**Comment by justbur** [comment] 2016-02-23 17:09
In case it's not clear, here's what it happening

 1. Want to install magit
 2. git-commit is seen as a dependency, so try to activate it now
 3. Error because git-commit has a dependency that's not installed (it is scheduled to be installed though)

I think you need to process the dependencies of git-commit and install them before activating the package.

**Comment by syl20bnr** [comment] 2016-02-23 17:10
Seems that `configuration-layer//get-package-deps-from-archive pkg-name` should be DFS.

**Comment by justbur** [comment] 2016-02-23 17:11
DFS?

**Comment by syl20bnr** [comment] 2016-02-23 17:12
Should be a depth first search.

**Comment by syl20bnr** [comment] 2016-02-23 17:14
I'll look at it tonight and try to add tests, I was lazy about the tests because of the data structure it depends on, my bad on this.

**Comment by syl20bnr** [comment] 2016-02-23 17:15
Also it was done at 24.3 time, I'll look into package.el source again to see if I can find some interesting bits.

**Comment by syl20bnr** [comment] 2016-02-23 17:16
mmmh, seems that the error is here: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L1445

**Comment by syl20bnr** [comment] 2016-02-23 17:17
mmmmhhh .... no it prepends the dependencies actually.

**Comment by syl20bnr** [comment] 2016-02-23 17:20
I'm confused about this: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L988-L992

**Comment by justbur** [comment] 2016-02-23 17:20
The issue is that magit does not depend directly on with-editor it depends on git-commit which depends on with-editor. It seems the dependencies are not being recursively processed.

**Comment by justbur** [comment] 2016-02-23 17:20
> I'm confused about this: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L988-L992

why?

**Comment by syl20bnr** [comment] 2016-02-23 17:20
They are processed recursively with a DFS and correct merge of the results.

**Comment by syl20bnr** [comment] 2016-02-23 17:21
> why?

Seems I activate the packages before installing it ?

**Comment by justbur** [comment] 2016-02-23 17:22
you're activating the dependencies before installing the package. Don't know why. 

I don't know the configuration-layer code, since I haven't looked at it really. All I can report is that this strongly smells like a spacemacs issue.

**Comment by syl20bnr** [comment] 2016-02-23 17:23
I'm confused, it is surprising that we get this error only with magit, we should have other cases like that.

**Comment by syl20bnr** [comment] 2016-02-23 17:26
Ok I understand.

It happens with Magit because this is maybe the only package which updates all its dependencies at once. We would definitely have this error for other packages.

**Comment by syl20bnr** [comment] 2016-02-23 17:26
The code is wrong, my apologies for this.

**Comment by syl20bnr** [comment] 2016-02-23 17:28
I'm fixing it, hopefully :-)

**Comment by justbur** [comment] 2016-02-23 17:33
No worries. I was just saying it's annoying and could be better.

**Comment by syl20bnr** [comment] 2016-02-23 18:01
Should be fixed in develop, see https://github.com/syl20bnr/spacemacs/commit/8849e9c

**Comment by syl20bnr** [comment] 2016-02-23 18:04
BTW Thank you :-)

**Comment by syl20bnr** [comment] 2016-02-23 18:08
I don't have Emacs 25 at hand right now, someone can test this against it ? (I know tests, tests, tests... :-))

**Comment by fbergroth** [comment] 2016-02-23 18:23
Out of curiosity, why not do it in two passes? An installation phase and an activation phase?

**Comment by justbur** [comment] 2016-02-23 18:41
@syl20bnr I'm not getting the error anymore on emacs 25. Thanks

**Comment by syl20bnr** [comment] 2016-02-23 18:43
Spacemacs delays activation to speed up the loading, activation can be done at once when initializing package.el but it takes more time, don't know if it is still the case currently, ideally we should have regression tests for this, but I guess I will test it when emacs 25 is released.

Activation of dependencies is necessary to make the libraries available (basically add library path to load-path) at the installation time of a package.

**Closed** 2016-03-19 18:36 UTC
Labels: - Mailling list -, Update
