### ISSUE TITLE
Will no more spacemacs versions be released?

### ISSUE THREAD

**Issue by Compro-Prasad** [syl20bnr/spacemacs#11191] opened 2018-08-19 06:43 UTC
There is quite a lot of work done on the develop branch. There are more than 100 issues which have already been fixed in develop. Considering the stability factor, Spacemacs is a beta software/configuration. So, most of the users will always face instabilities given the pace at which packages in Emacs are released through Melpa.
1. Is Spacelpa ready for use?
2. The list of changes is too large. Is it still possible to plan out a release?

Edit: Pdumper point was removed as it has been already merged into Emacs master branch.

**Comment by jvillasante** [comment] 2018-08-24 22:17
I'm also interested on this. Should people switch to develop or will be more releases?

**Comment by robbyoconnor** [comment] 2018-08-25 00:16
The `develop` branch does introduce regressions. For example -- when @syl20bnr went on a bit of a bender with the deferred loading of packages as an example of one instance. Other issues do occasionally pop up. People should not become deluded and think `develop` is stable -- it's not. It breaks at times -- but usually not for long. it's stable _most of the time_, but not always.

**Comment by Miciah** [comment] 2018-08-25 00:43
Over time, the develop branch is unstable, no question.  What I meant to ask is the following: Does the develop branch _in its present state_ introduce any regressions vis-à-vis the master branch?

I know there were a lot of issues surrounding deferred loading and environment variables, but those seem to be resolved modulo some edge cases.  Looks like there are issues around Spacelpa still.  Anything else?

**Comment by robbyoconnor** [comment] 2018-08-25 01:39
Not that I see -- I actually use `develop` as my daily driver

**Comment by martin-liu** [comment] 2018-09-04 18:05
+1

**Comment by robbyoconnor** [comment] 2018-09-04 18:26
Keep in mind that @syl20bnr could get busy with life but he has people merging PRs and with @Miciah helping to triage issues and squash bugs-- which was a major pain point -- things are at least moving forward.

**Comment by jeremyong** [comment] 2018-11-13 18:23
I think at this point, all development should just move to `master`. I understand that maintainers get busy, but having this much divergence for this long doesn't make sense. It's easier to develop live off `HEAD` and periodically tag a release to demarcate "stable" points for people who really don't want changes.

**Comment by karlicoss** [comment] 2019-02-15 23:16
https://github.com/syl20bnr/spacemacs/issues/11741 perhaps this can be closed, release should be soon!

**Comment by Compro-Prasad** [comment] 2019-02-17 14:33
Yeah, this will be closed. Lets have a release first.

**Comment by agzam** [comment] 2019-02-20 17:59
I personally switched to `develop` branch over 3 years ago and never looked back. Ironically it feels more stable because whenever something breaks due to upstream issues of some package and the only way to fix it is to adjust Spacemacs, things get fixed faster in `develop`.

**Comment by Miciah** [comment] 2019-02-20 23:46
> whenever something breaks due to upstream issues of some package and the only way to fix it is to adjust Spacemacs, things get fixed faster in `develop`

I believe Spacelpa is supposed to solve exactly that problem.  At the moment, a Spacelpa-related issue, #10438, is the only remaining issue for 0.300: https://github.com/syl20bnr/spacemacs/milestone/7.

(I too prefer using the develop branch though.)

**Comment by hanzhixing** [comment] 2019-03-22 09:51
Waited for long time from last 0.200...

**Comment by c089** [comment] 2019-08-08 06:45
Cross-referencing other threads these since I've also been wondering:

Possible Duplicate of #11352
Possible Duplicate of #12418

**Comment by robbyoconnor** [comment] 2019-08-09 06:46
No, they're definitely dupes.

**Comment by macintacos** [comment] 2019-11-27 04:47
As a new user, it's disappointing that I had to spend almost an hour to figure that a layer that's been merged with `develop` since 2017 (!), `treemacs` (#9680), hasn't been merged with the default `master` branch and thus isn't included in a clean installation. I'll be trying my luck with the `develop` branch, but what's up with this release cadence?

**Comment by l2dy** [comment] 2019-11-27 05:00
> Also, side note; I'm perfectly fine with unreleased features being documented, but it makes it a bit confusing to a casual user like myself that thinks that the documentation is detailing what's on the "latest stable" branch, i.e. the one that is installed from master. The [layers documentation](https://develop.spacemacs.org/layers/+filetree/treemacs/README.html) gave no indication that I wouldn't be able to enable `treemacs` until I was on the `develop` branch, which is why I'm a bit frustrated.

The [layers documentation](https://www.spacemacs.org/layers/LAYERS.html) is under www.spacemacs.org, not *develop*.spacemacs.org. The domain is the indication.

**Comment by robbyoconnor** [comment] 2019-11-27 05:45
develop almost never is unstable. If you want the latest, use that. If
it ever does break, it's not broken for long and roll-back is easy.

**Comment by macintacos** [comment] 2019-11-27 07:32
Touché @l2dy! Hadn't noticed the domain :)

Understand the workaround, and I'll be doing that going forward; just doesn't "feel" great.

**Comment by jr0cket** [comment] 2020-06-17 14:47
For future reference and anyone looking to upgrade from Spacemacs master to develop can use this comprehensive guide
https://practicalli.github.io/spacemacs/install-spacemacs/switch-to-develop.html

**Comment by KitsuneSan89** [comment] 2021-09-04 18:50
It's now been over 3 years since the last release. Is there any expectation that another release will happen, or should everyone just be on develop?

**Comment by real-or-random** [comment] 2022-05-16 07:52
I think the answer is in this commit message:

https://github.com/syl20bnr/spacemacs/commit/964f4c5af3615b648a7707a39b82b7ef02dc4807#diff-44bd77bd979018c8610440ea263a5790522d32dee6f60d5187fbe7de9440f8d0

> The master branch is using curated version of packages for increased stability. 
>
> However this approach proofed to be very work intensive and we have therefore stopped supplying those versions for now.
> As these packages are not longer updated you should consider migrating to the maintained "develop" branch.

I still think there should be some roadmap / tracking issue for further changes:
 - Are there some (even rough) plans to revive the `master` idea or not? (Not wishing for any particular answer, I'm just asking).
 - https://develop.spacemacs.org/ should be moved to https://www.spacemacs.org/
 - Consider renaming the `master` branch and/or the `develop` branch
 - The README should have a migration guide, or point to one. @practicalli-john wrote an excellent guide here: https://practical.li/spacemacs/install-spacemacs/switch-to-develop.html
 - Close remaining duplicates, e.g. https://github.com/syl20bnr/spacemacs/issues/12418
 - ...

**Comment by costa** [comment] 2023-04-26 09:41
I'm sorry for the harsh words (especially coming from an ex-rails dev), but this project is off the rails...

I've been using it for many years, enjoyed its stability (while bringing order into Emacs chaos), and recommended to anyone serious about text management. It has become a professional tool of choice for many, many devs. Nowadays, the versions are like effectively totally gone — I mean, if I'd seen this project with no versions back when I started, there'd been no chance in hell (wink!) I'd been starting using it at all — it can be relied upon almost as much as your own first `~/.emacs` in the olden days.

Now, I have a very modest setup, with essentially all defaults, and after many, many happy times (with almost no config tinkering), in recent years, it's been degrading on me from update to update, and in the last few days, even a clean fresh install of everything on my macos (maybe not the latest macos, but the brew's latest emacs app and github's latest spacemacs version) is now deficient wrt basic functionality (such as treemacs panel coming up — or even being able to replace treemacs with neotree).

I will be sorry to see good devs and also myself walk away from this project just because it failed on its main successful idea: stability of package configuration. I have not contributed to this project (no lisp here), but it seems unfair to those who did — denying good code from living on, potentially with others' forks of stable versions.

Is there at least a chance that there comes a hero who shall patch the latest stable version — while working around resurrecting old packages as needed (possibly marking stuff unsafe) — and make it work for the most popular layers at least? Thanks.

**Comment by practicalli-johnny** [comment] 2023-04-26 12:58
As a minor contributor to the Spacemacs project I am very grateful to everyone who has contributed and to the original maintainer who started the project.

I am a long time used of Spacemacs develop branch (2015) and have rarely had any serious issues.  I can upgrade to packages and pull Spacemacs changes as required without having to manage a big upgrade.

The rolling release model has been adopted by huge numbers of people and has long been the recommended approach by the community at large (from 2015 onward)

I do not believe a stable release schedule it's needed or valued highly (or someone would have done it already).

Having tried other community configurations earlier this year, I found no as feature rich, reliable and as easy to use as Spacemacs.  I will continue using Spacemacs for the foreseeable future.

It is very sad to see rants disparaging all the work that everyone has committed and I would hope that people making such comments wonder why they are not helping instead (especially if those people don't even take the time to contribute anything)

There are plenty of choice with Emacs, so people can either help shape and evolve the Spacemacs project or they can take make an alternative choice.

**Comment by robbyoconnor** [comment] 2023-04-26 15:08
@practicalli-john -- Yeah, if I ever face issues, they're usually not issues for long.

**Comment by costa** [comment] 2023-04-28 08:00
<img width="1169" alt="Screenshot 2023-04-28 at 14 54 26" src="https://user-images.githubusercontent.com/45370/235089156-83871897-1319-4386-ae0e-a9a36c65758c.png">
...just as another screencast of mine is ruined by buggy(!) Ruby(!!) syntax highlighting (!!!)...

**Closed** 2023-04-28 08:05 UTC
