### ISSUE TITLE
Discussion about search key bindings / tools, formerly known as a simple bug report.

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#2023] opened 2015-06-16 06:26 UTC
I assume that `SPC s b` should only search in currently opened buffers. This is not the case for me. See below to reproduce:

- Start spacemacs 
- press `SPC s b`.
- type something short and common so that it is found
- a lot of results pop up from files all over the file system

**Comment by tuhdo** [comment] 2015-06-16 06:33
You can try `SPC s s` to search in current buffer.

To search in selected buffers, you can use `SPC s S`.

To search in all opened buffers, you can use `SPC s C-s`.

**Comment by cpaulik** [comment] 2015-06-16 06:46
Really? `SPC s C-s` is not bound for me.

`SPC s S` searches in the current buffer but automatically selects the point or region as a starting pattern.

Well anyway. The described bug only occurs in a freshly opened spacemacs with no other buffers opened. It works as expected if at least one buffer was opened which is probably fine.

**Comment by tuhdo** [comment] 2015-06-16 06:51
Probably something's wrong. It's defined in `spacemacs/init-helm-swoop`. You can use `SPC f e h` to jump to that package. Did you exclude `helm-swoop`?

**Comment by cpaulik** [comment] 2015-06-16 07:02
To avoid any confusion, I'm talking about latest develop. I think helm-swoop was removed there and the new search keybindings were introduced. See https://github.com/syl20bnr/spacemacs/commit/2adf5bf0e5eab548b3a5622e55dc80ec2867ca5d
and
https://github.com/syl20bnr/spacemacs/commit/90008bb9008b091ff8187dc8f6ffe0fbf5979222

**Comment by tuhdo** [comment] 2015-06-16 07:05
Hmm what kidn of search key bindings are there? I thought that the new search command is for searching in files, not buffers....

**Comment by tuhdo** [comment] 2015-06-16 07:10
Wow i've just skimmed the new search scheme. The concept is flawed. `helm-swoop` is a different kind of searching compared with `helm-ag`: `helm-swoop` searches using Emacs, while `helm-ag` and others use external tools. Setting up grep and other search tools are more difficult on Windows.

@syl20bnr Please revert the change.

**Comment by tuhdo** [comment] 2015-06-16 07:15
@cpaulik This is serious. You should reopen the issue.

**Comment by cpaulik** [comment] 2015-06-16 07:23
Actually this issue was about search in buffers not behaving as I expected it to work. Since it is broken directly after startup. But we might as well discuss it here if the thread has already started.

**Comment by tuhdo** [comment] 2015-06-16 07:43
@syl20bnr So, I read the chatroom. If you want to write directly on the grep results and save everything all at once, you can use [wgrep](https://github.com/mhayashi1120/Emacs-wgrep). It's awesome. Demo (assumed you already installed `wgrep`):

- Run `rgrep`.
- Search for a string i.e. test
- After you have the `*grep*` buffer, switch to it and press `C-c C-p`.
- Now you can edit anything you want i.e. using `iedit` to change all occurrences.
- Save with `C-c C-e`.

`wgrep` also has a packaged named `wgrep-helm` that works in similar manner, except on the search result buffer exported by `helm-grep` or `helm-ag` (yes, it works with `helm-ag`). For example, after installing `wgrep`, you can search with `helm-ag`, press `F3` to store the results in a buffer, then `M-x wgrep-change-to-wgrep-mode` to edit and `C-c C-e` to commit all.

There are [more features](https://github.com/mhayashi1120/Emacs-wgrep#usage). One useful feature is that you can temporary toggle read-only on/off, so you can remove unwanted results that you don't want to change by using `C-k` or `dd` (in Evil). For example, you can toggle read-only off with `C-c C-p` (while in `wgrep-mode`) and remove unwanted lines. After you're done, toggle read-only on it on and now you won't be able to remove any result but you can only delete text **after** the file and line number i.e. a result like this:

```text
core/core-release-management.el:103:  (let ((version (spacemacs/git-latest-tag remote branch)))
```
You can only edit after the colon next to `103`.

**Comment by luxbock** [comment] 2015-06-16 09:50
Perhaps the issue should be renamed to reflect a more general issue with the new search approach?

I understand the motive for the new search tools approach, but I am a bit unhappy with the re-assignment of `SPC s s`, which has been one of my most used key combinations. In addition to the point that @tuhdo made about external vs. Emacs tooling, I'd also like to point out that by far the biggest annoyance for me has been that `helm-ag-this-file` acts nothing like `helm-swoop` does functionally:
- It uses a prompt for the inital search term and then filters based on additional input in helm, as opposed to giving you interactive feedback since the beginning. This breaks the workflow of coming up with the search term to use on the fly based on the feedback from helm.
- `helm-ag` lacks the very useful edit functionality of `helm-swoop`, bound to `C-c C-e`.

**Comment by cpaulik** [comment] 2015-06-16 11:06
It is strange that `C-c C-e` does not work for `SPC s s` since it works for all other searches based on `helm-ag`

**Comment by syl20bnr** [comment] 2015-06-16 11:29
@luxbock the issue you described should be fixed in helm-ag soon. SPC s S
will be like helm-swoop. I can re-enable it temporarily since helm-ag is
not yet ready.

For the grep thing, let's be serious, any Spacemacs user must set up at
least one search tool otherwise he is in serious trouble. Helm-ag works
with a drop-in search tool called `pt` which cannot be easier to install
consistently and any platform.

Le mardi 16 juin 2015, luxbock <notifications@github.com> a écrit :

> Perhaps the issue should be renamed to reflect a more general issue with
> the new search approach?
>
> I understand the motive for the new search tools approach, but I am a bit
> unhappy with the re-assignment of SPC s s, which has been one of my most
> used key combinations. In addition to the point that @tuhdo
> <https://github.com/tuhdo> made about external vs. Emacs tooling, I'd
> also like to point out that by far the biggest annoyance for me has been
> that helm-ag-this-file acts nothing like helm-swoop does functionally:
>
>    - It uses a prompt for the inital search term and then filters based
>    on additional input in helm, as opposed to giving you interactive feedback
>    since the beginning. This breaks the workflow of coming up with the search
>    term to use on the fly based on the feedback from helm.
>    - helm-ag lacks the very useful edit functionality of helm-swoop,
>    bound to C-c C-e.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/2023#issuecomment-112368436>
> .
>


-- 
-syl20bnr-

**Comment by tuhdo** [comment] 2015-06-16 11:35
@syl20bnr The problem is that `helm-swoop` can search non-file buffers. Have you thought about this?

**Comment by syl20bnr** [comment] 2015-06-16 11:41
Indeed I did not think about it. I'll re-enable helm-swoop then :-)
But we have to adapt the key bindings with the new scheme, that is SPC s S
to search for thing at point or region.

SPC s b (search in opened buffers) could be migrated to helm-swoop as well,
once again we have to work to make helm-ag and helm-swoop behaviors as
closed as possible.

Le mardi 16 juin 2015, Tu Do <notifications@github.com> a écrit :

> @syl20bnr <https://github.com/syl20bnr> The problem is that helm-swoop
> can search non-file buffers. Have you thought about this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/2023#issuecomment-112392436>
> .
>


-- 
-syl20bnr-

**Comment by cpaulik** [comment] 2015-06-16 12:11
[This question](https://gitter.im/syl20bnr/spacemacs?at=55800b9f7d5adaae3b4f34ac) in gitter could also be relevent here. Are there any search tools that would work on a remote host or is this a mute point anyway?

@dab

**Comment by tuhdo** [comment] 2015-06-16 12:15
@dab you may try `rgrep` for searching on remote host. Helm search won't work over Tramp.

**Comment by dab** [comment] 2015-06-16 12:20
@tuhdo yes, I can, but I'd like to use ag there as well :)

**Comment by tuhdo** [comment] 2015-06-16 12:22
@dab you can install `ag` package on MELPA:

- `M-x list-package`
- Choose `ag`
- Install it.
- Use it.

If you don't want Spacemacs to delete it, add it to your own package layer, or add it to `dotspacemacs-additional-packages` in `.spacemacs`.

**Comment by syl20bnr** [comment] 2015-06-16 14:04
Thank you for your feedback :+1:

I re-enabled `helm-swoop` in develop, it is now possible to look for the selected region as well, note that this is on `SPC s S` instead of `SPC s s` to match the other key bindings.

I know that some users may want to swap lowercase and uppercase bindings behaviors depending on their use cases. We may provide a setting to do this swap if enough users ask for it.

**Comment by syl20bnr** [comment] 2015-06-21 03:43
I consider this discussion closed, let me know if I overlooked something.

**Closed by syl20bnr** 2015-06-21 03:43 UTC
Labels: discussion, Key Bindings

**Comment by tE74567** [comment] 2023-01-06 07:11
Ok
