### ISSUE TITLE
missing package

### ISSUE THREAD

**Issue by svalaskevicius** [syl20bnr/spacemacs#1986] opened 2015-06-14 09:55 UTC
after an upgrade I get this error: `Package php-extras is unavailable. Is the package name misspelled?`

it looks like its only available in marmalade repo, but its not available and is only added like this:
```
 26   ;; Emacs 24.3 and above ships with python.el but in some Emacs 24.3.1 packages
 27   ;; for Ubuntu, python.el seems to be missing.
 28   ;; This hack adds marmalade repository for this case only.
 29   (unless (or (package-installed-p 'python) (version< emacs-version "24.3"))
 30     (add-to-list 'package-archives
 31                  '("marmalade" . "http://marmalade-repo.org/packages/")))
```

a) is there a quick way to enable it from user's spacemacs config?
b) wouldn't it be better to enable it for all cases? (not sure whats the reason its disabled in non python case)

**Comment by lufeihaidao** [comment] 2015-06-14 15:27
Same problem

**Comment by CestDiego** [comment] 2015-06-15 04:25
same

**Comment by syl20bnr** [comment] 2015-06-21 03:20
I'm not for mixing too much repositories since it can lead to issues, and I don't want to use the pinning functionality in spacemacs either. Since `php-mode` is on MELPA then `php-extras` should be on MELPA too if we want it to be in spacemacs layer.

I won't add marmalade or MELPA stable in spacemacs.

**Comment by CestDiego** [comment] 2015-06-21 04:12
Then shall we take php-extras out of the layer or submit ask the mantainer to submit it to MELPA?

**Comment by syl20bnr** [comment] 2015-06-21 04:22
I would go for increasing MELPA coverage :-)

**Comment by MadAnd** [comment] 2015-07-01 12:02
This issue is a duplicate of #1314

**Comment by StreakyCobra** [comment] 2015-11-20 11:32
This is an old issue, duplicate of #1314 that has been fixed both in `master` and `develop`. I'm closing it, but feel free to open a new issue in case of troubles :relaxed:

**Closed by StreakyCobra** 2015-11-20 11:32 UTC
Labels: bug :-(, duplicate (-: :-), Php
