### ISSUE TITLE
emacs directory is not clean

### ISSUE THREAD

**Issue by benneti** [syl20bnr/spacemacs#5704] opened 2016-04-06 16:17 UTC
#### Description
If I use spacemacs for some time and try to update i get this message:
"Your emacs directory is not clean
git status:
?? session.*" (Not actually a * but a long integer)
I don`t know wether this is a problem but it is annoying, an easy fix would propably be to add "session.*" to gitignore.

#### Reproduction guide
- Start Emacs
- use it some time
- check for updatest on the startpage (Update Spacemacs)

*Observed behaviour:*
unclean directory, session files are created

*Expected behaviour:*
no session.* files are created or they are ignored

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(eyebrowse org
           (shell :variables shell-default-height 20 shell-default-shell 'ansi-term shell-default-position 'bottom)
           git
           (auto-completion :variables auto-completion-enable-snippets-in-popup t)
           ycmd
           (dash :variables dash-helm-dash-docset-path "~/.docsets")
           (spell-checking :variables spell-checking-enable-auto-dictionary t)
           syntax-checking
           (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
           emacs-lisp
           (latex :variables latex-enable-folding t latex-enable-auto-fill t)
           python octave rust shell-scripts html games)
```

#### Thank You
- for making emacs more awesome
- for making emacs more accessible

**Comment by TheBB** [comment] 2016-04-06 16:41
Yeah, I get these session files as well sometimes.

**Comment by LeartS** [comment] 2016-04-07 14:07
I too get some files sometimes that block spacemacs updates.

**Comment by nujabse** [comment] 2016-04-11 00:30
I got this problem too, maybe try manual updates?

**Comment by biocyberman** [comment] 2016-04-11 12:59
Well, I get this every time I try to use spacemacs GUI/Terminal interface to update spacemacs. I have to run `git pull --rebase` outside spacemacs. These are the files that make the repo not clean:'

```
custom.el
org-clock-save.el
recentf
srecode-map.el
```
I think the solution is to add them to the `.gitignore` file.

**Comment by StreakyCobra** [comment] 2016-04-11 13:05
The better would be to find from where they are coming from in order to redirect them to the `.cache` folder. If it's not possible then `.gitignore` is the solution.

**Comment by benneti** [comment] 2016-04-11 17:07
Probably, but i have no idea where they come from :(

**Comment by 3rd3** [comment] 2016-04-12 15:36
This is duplicate of #5556.

**Comment by StreakyCobra** [comment] 2016-04-12 16:06
Indeed, closing this one as it is more recent. @biocyberman  Could you report your list of problemtic files in #5556? Thanks :-) 

Everybody: you can follow the other thread by clicking on the "subscribe" button there, or directly participating to the discussion.

**Closed by StreakyCobra** 2016-04-12 16:06 UTC
Labels: - Bug tracker -, <=(- UBO -)=>
