### ISSUE TITLE
Make some stock Emacs key bindings use Helm version instead

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1522] opened 2015-05-07 10:05 UTC
In Vim, `C-x C-f` prompts for files to insert in the current buffer. In Emacs, using `helm-find-files`, you can navigate to anywhere and press `C-c i` to insert path at point, and it works for both absolute paths and relative paths. Currently, `C-x C-f` is bound to `ido-find-files` which does not have this feature. Binding `helm-find-files` to `C-x C-f` not only makes Spacemacs more consistent but also more feature rich.

We should also bind `C-x b` to `helm-mini`, since it's shorter for Emacs people to press rather than `C-c b b`. Currently `C-x b` uses `ido-switch-buffer` which is not standard Emacs command anyway.

**Comment by tiborsimko** [comment] 2015-12-03 22:50
FWIW I like the proposal to map helm functions over ido functions when possible in Spacemacs defaults.

One example: in my setup I observed frequent freezing when doing `C-x C-f` and `C-x b` like operations. (Due to say finger memory as opposed to using `SPC f f` and friends.) The minimal recipe to reproduce the problem was: start Emacs, `C-x C-f somefile RET`, `C-x 2`, after which pressing `C-x C-f` led to a freeze. The workaround was to use `dotspacemacs-excluded-packages '(ido)` after which helm commands are mapped behind `C-x C-f` and `C-x b` instead of `ido` commands, solving the freeze that way.

Since helm is extensively used in spacemacs, it makes sense to map it by default over ido in the stock Emacs bindings. Maybe the value of `dotspacemacs-use-ido` could be governing this behaviour.

**Comment by d12frosted** [comment] 2016-10-03 09:16
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 09:16 UTC
Labels: Beginner friendly, Enhancement ☺, Fixed in develop, Helm, Key Bindings
