### ISSUE TITLE
Cannot `<escape>` or `C-g` out of `evil-insert-state` in terminals

### ISSUE THREAD

**Issue by bryce-carson** [syl20bnr/spacemacs#15481] opened 2022-04-20 05:41 UTC
In Tmux, GNOME Terminal, and XTerm normal state cannot be escaped by calling ESC or C-g. The only way to exit insert or another evil state and return to normal state is with `M-x evil-normal-state`.

**Comment by lebensterben** [comment] 2022-04-20 05:44
are those keys used by tmux?

**Comment by bryce-carson** [comment] 2022-04-20 05:46
> are those keys used by tmux?

Yes.

**Comment by bryce-carson** [comment] 2022-04-20 05:48
I can't reproduce it now in Termux with the latest commit and no exclusion of the problem package, but it's probably related to that problem package.

I'm pretty confused right now.

**Comment by bryce-carson** [comment] 2022-04-20 05:54
I was able to reproduce it in Termux when using Zsh, but not when using BASH using the latest commit.

It must be terminal dependent, which again points towards the culprit package.

**Comment by lebensterben** [comment] 2022-04-20 06:07
> I was able to reproduce it in Termux when using Zsh, but not when using BASH

which means it's not caused by terminal

**Comment by bryce-carson** [comment] 2022-04-20 06:13
I tested excluding `evil-terminal-cursor-changer` in `.spacemacs`, and the problem persists in Zsh on Termux.

Not sure what else to test right now.

**Comment by arifer612** [comment] 2022-04-21 15:04
I cannot reproduce it for tmux started in zsh.

**Comment by bryce-carson** [comment] 2022-04-21 15:24
Termux, on Android, not Tmux.

I was able to reproduce it st one point with Xterm on Linux.

I'll keep am eye out

**Comment by bryce-carson** [comment] 2022-04-26 01:58
It seems using the portable dumper in Termux (Android) is what causes the issue.

Loading Emacs without a dump file everything is fine.

**Comment by lebensterben** [comment] 2022-04-26 02:15
Android won't be supported.

**Closed** 2022-04-26 02:15 UTC

**Comment by bryce-carson** [comment] 2022-04-27 05:52
@lebensterben The portable dumper causes the same issue in terminals on Linux (tested with Konsole).

**Comment by lebensterben** [comment] 2022-04-27 06:55
please follow the issue template.
