### ISSUE TITLE
Powerline doesn't display on emacs25 64bit for Windows

### ISSUE THREAD

**Issue by quartz55** [syl20bnr/spacemacs#1426] opened 2015-04-28 18:10 UTC
After getting the new 64bit binaries for emacs25 on Windows and launching it I've noticed that powerline doesn't display anymore
Here's what comes up on **\*Messages*** :
```
Error during redisplay: (eval (spacemacs/mode-line-prepare)) signaled (error "Bad bounding indices: 0, 1") 
```

I checked the powerline git issues but found nothing that helped

**Comment by syl20bnr** [comment] 2015-04-28 19:05
Thank you for the report. Emacs 25 is not officially supported by spacemacs so this bug is not very high priority for now.

**Comment by quartz55** [comment] 2015-04-28 20:44
What I got from the powerline github issues was that it is fixed for emacs25, so it should be a spacemacs thing

I'll report more stuff I find :)

**Comment by justbur** [comment] 2015-04-29 13:40
I was having the same issue in both 24.5 and 25. Commenting out the line with `(powerline-chamfer-left ...)` fixed the issue with minimal effects on the mode line, so I created a PR for this issue.

**Comment by quartz55** [comment] 2015-04-29 14:10
@justbur That didn't fix it for me, still getting the same error:
```
Error during redisplay: (eval (spacemacs/mode-line-prepare)) signaled (error "Bad bounding indices: 0, 1") 
```

**Comment by justbur** [comment] 2015-04-29 14:17
@quartz55 What I did was to turn on debug on error (`SPC t D`) and execute the function `(spacemacs/mode-line-prepare)` in a scratch buffer, which pointed to the offending line. Perhaps a different part of the mode line is causing the problem for you. It's easy for me to reproduce the problem on my computer by uncommenting the line in the PR again.

**Comment by justbur** [comment] 2015-04-29 15:40
Sorry, I made a mistake. I thought I tried it in v24.5, but I didn't. This does seem to be just a v25 problem.

**Comment by syl20bnr** [comment] 2015-05-03 02:47
@justbur or @quartz55 can you report this issue upstream ? https://github.com/milkypostman/powerline
If you do, can you also add a link to it here so we can track the progress ? Thank you !

**Comment by justbur** [comment] 2015-05-03 23:41
Done! Github picked up the link automatically. I closed the pull request for now, but it's worth mentioning that the fix still works. For some reason, there is just a problem with certain separators, like `chamfer`. Arrows work fine for me, for example.

**Comment by justbur** [comment] 2015-06-29 11:00
This should be fixed upstream now. See https://github.com/milkypostman/powerline/pull/91

**Comment by justbur** [comment] 2015-07-03 19:14
The upstream fix definitely works for me. I think this can be closed, unless @quartz55 is still having a problem after updating powerline

**Closed** 2015-08-26 08:16 UTC
Labels: 25.0, bug :-(, Fixed upstream, Mode Line
