### ISSUE TITLE
Fix smartparens and yasnippet comptibility

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#541] opened 2015-02-04 10:50 UTC
The issue is described here: https://github.com/Fuco1/smartparens/issues/431

To workaround this, we can disable smartparens before snippet is inserted and enable after the snippet is inserted:

```elisp
(add-hook 'yas-before-expand-snippet-hook (lambda () (smartparens-mode -1)))
(add-hook 'yas-after-exit-snippet-hook (lambda () (smartparens-mode 1)))
```

**Comment by expez** [comment] 2015-02-04 13:08
If the problem is tied to `auto-complete` then a better solution would be to adopt `company-mode` instead.  This will turn off `smartparens-mode` while the user is filling out snippets which is unfortunate.

**Comment by tuhdo** [comment] 2015-02-04 13:29
It's not. I do not have `auto-complete` installed in my own Emacs configuration, and I ran `yas-expand` separately. 

> This proposed solution will turn off smartparens-mode while the user is filling out snippets which is unfortunate.

But then, I don't think in most case a pair is needed in filling out snippets, while many snippets contain paired characters, such as many C/C++ snippets.

**Comment by tuhdo** [comment] 2015-02-04 13:35
For some reason, it did not happen anymore. But maybe the issue should remain opened here since Spacemacs uses `auto-complete`.

**Comment by syl20bnr** [comment] 2015-02-06 04:35
@tuhdo the issue has magically disappeared ?

**Comment by exitface** [comment] 2015-02-10 22:14
Unless I use the snippet originally provided by tuhdo, I get extra parens when expanding snippets

```javascript
log<TAB> -> console.log(|))
```
Note the extra paren on the end

**Comment by syl20bnr** [comment] 2015-02-25 02:54
duplicate of #452

**Comment by expez** [comment] 2015-02-25 07:24
I believe we fixed this in [#431](https://github.com/Fuco1/smartparens/issues/431)

**Comment by exitface** [comment] 2015-02-25 21:42
No longer having the extra paren issue

**Comment by syl20bnr** [comment] 2015-02-26 06:13
Fixed upstread (https://github.com/Fuco1/smartparens/issues/431)

**Closed by syl20bnr** 2015-02-26 06:13 UTC
Labels: duplicate (-: :-), enhancement :-D

**Comment by kevinushey** [comment] 2015-06-27 19:46
This issue does not appear to be resolved to me, unfortunately. `smartparens` is still erroneously inserting parentheses when I attempt to expand certain snippets.

The workaround by the OP does still work, though.

**Comment by kevinushey** [comment] 2015-06-27 19:47
Sorry -- it sounds like this just made it into the `develop` branch here: https://github.com/syl20bnr/spacemacs/pull/1644.
