### ISSUE TITLE
A function definition is void with avy.

### ISSUE THREAD

**Issue by skarekrow** [syl20bnr/spacemacs#6843] opened 2016-08-17 01:40 UTC
#### Description
I seem unable to be able to use avy.

#### Reproduction guide
- Start Emacs
- Go to spacemacs buffer
- Hit 'o'

*Observed behaviour:*
You will see `let: Symbol's function definition is void: avy--with-avy-keys`

*Expected behaviour:*
To jump to the links or buttons

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking version-control go projectile)
```

#### Backtrace
```
let: Symbol's function definition is void: avy--with-avy-keys
```

**Comment by TheBB** [comment] 2016-08-17 04:19
Duplicate of https://github.com/syl20bnr/spacemacs/issues/5307

It has been fixed in develop, and there's a workaround in the linked issue.

**Closed by TheBB** 2016-08-17 04:19 UTC
Labels: Duplicate ☝

**Comment by skarekrow** [comment] 2016-08-17 04:51
My apologies, I didn't see that in my search.

Thanks!
