### ISSUE TITLE
Julia Language server crashes

### ISSUE THREAD

**Issue by AkashGanesan** [syl20bnr/spacemacs#12191] opened 2019-04-17 11:16 UTC
#### Description :octocat:
Julia Language server crashes and I'm left with no autocomplete :(

#### Reproduction guide :beetle:
- Start Emacs
- Do the following to install the LanguageServer in a julia terminal.
```
>> ] dev PackageCompiler
>> ] add SymbolServer
>> ] add LanguageServer#master # You can try with no master as well
>> compile_package("LanguageServer")
```

- Use the develop branch of spacemacs (latest).
- Do the steps provided in the language server.
- Julia version : 1.0.3
- [2b0e0bc5] LanguageServer v0.5.1+ #master (https://github.com/JuliaEditorSupport/LanguageServer.jl.git)
- [9b87118b] PackageCompiler v0.6.3+ [`~/.julia/dev/PackageCompiler`]
- [cf896787] SymbolServer v0.1.3

*Observed behaviour:* :eyes: :broken_heart:
Whgen I open a `jl` file, the julia language server starts up and then crashes with the following message

```
[ Info: Started symbol server
[ Info: StaticLint store set
ERROR: MethodError: no method matching String(::Nothing)
Closest candidates are:
  String(!Matched::String) at boot.jl:309
  String(!Matched::Array{UInt8,1}) at strings/string.jl:39
  String(!Matched::Base.CodeUnits{UInt8,String}) at strings/string.jl:75
  ...
Stacktrace:
 [1] LanguageServer.TextDocumentItem(::Dict{String,Any}) at /home/<USER>/.julia/packages/LanguageServer/2C2HB/src/protocol/protocol.jl:25 (repeats 2 times)
 [2] parse_params(::Type{Val{Symbol("textDocument/didOpen")}}, ::Dict{String,Any}) at /home/<USER>/.julia/packages/LanguageServer/2C2HB/src/requests/textdocument.jl:2
 [3] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at /home/<USER>/.julia/packages/LanguageServer/2C2HB/src/jsonrpc.jl:38
 [4] run(::LanguageServerInstance) at /home/<USER>/.julia/packages/LanguageServer/2C2HB/src/languageserverinstance.jl:44
 [5] top-level scope at none:0

Process julia-ls stderr finished

```

I also get the following in the *Message* buffer

```
LSP :: julia-ls has exited (exited abnormally with code 1)
Error running timer ‘lsp--update-document-links’: (cl-assertion-failed (lsp--capability "documentLinkProvider"))
Server julia-ls:28262 exited with status exit. Do you want to restart it? (y or n)
```

*Expected behaviour:* :heart: :smile:
For the language server to work and let me autocomplete!

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2206095be)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(php csv rust markdown helm auto-completion better-defaults python emacs-lisp git org bibtex spell-checking syntax-checking lsp
     '(lsp :variables lsp-prefer-flymake nil)
     julia haskell
     (julia :variables julia-mode-enable-lsp t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
*lsp-log*
```
Command "julia --startup-file=no --history-file=no -e using LanguageServer, Sockets, SymbolServer; server = LanguageServer.LanguageServerInstance( stdin, stdout, false, "/home/akaberto/.julia/environments/v1.0", "",Dict()); server.runlinter = true; run(server);" is present on the path.
Found the following clients for /home/akaberto/a.jl: (server-id julia-ls, priority 0)
The following clients were selected based on priority: (server-id julia-ls, priority 0)
>>> julia-ls:9711 status:starting(async)
Content-Length: 3499

{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "processId": 9130,
    "rootPath": "/home/akaberto/",
    "rootUri": "file:///home/akaberto/",
    "capabilities": {
      "workspace": {
        "workspaceEdit": {
          "documentChanges": true,
          "resourceOperations": [
            "create",
            "rename",
            "delete"
          ]
        },
        "applyEdit": true,
        "symbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26
            ]
          }
        },
        "executeCommand": {
          "dynamicRegistration": false
        },
        "didChangeWatchedFiles": {
          "dynamicRegistration": true
        },
        "workspaceFolders": true,
        "configuration": true
      },
      "textDocument": {
        "declaration": {
          "linkSupport": true
        },
        "definition": {
          "linkSupport": true
        },
        "implementation": {
          "linkSupport": true
        },
        "typeDefinition": {
          "linkSupport": true
        },
        "synchronization": {
          "willSave": true,
          "didSave": true,
          "willSaveWaitUntil": true
        },
        "documentSymbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26
            ]
          },
          "hierarchicalDocumentSymbolSupport": true
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "codeAction": {
          "dynamicRegistration": true,
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": [
                "",
                "quickfix",
                "refactor",
                "refactor.extract",
                "refactor.inline",
                "refactor.rewrite",
                "source",
                "source.organizeImports"
              ]
            }
          }
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true
          }
        },
        "signatureHelp": {
          "signatureInformation": {
            "parameterInformation": {
              "labelOffsetSupport": true
            }
          }
        },
        "documentLink": {
          "dynamicRegistration": true
        },
        "hover": {
          "contentFormat": [
            "plaintext",
            "markdown"
          ]
        },
        "foldingRange": {
          "dynamicRegistration": true,
          "rangeLimit": null,
          "lineFoldingOnly": null
        }
      }
    },
    "initializationOptions": null
  },
  "id": 22
}

<<<< julia-ls:9711 status:starting
{
  "id": 22,
  "jsonrpc": "2.0",
  "result": {
    "capabilities": {
      "textDocumentSync": 2,
      "hoverProvider": true,
      "completionProvider": {
        "resolveProvider": false,
        "triggerCharacters": [
          "."
        ]
      },
      "signatureHelpProvider": {
        "triggerCharacters": [
          "("
        ]
      },
      "definitionProvider": true,
      "typeDefinitionProvider": false,
      "implementationProvider": false,
      "referencesProvider": true,
      "documentHighlightProvider": false,
      "documentSymbolProvider": true,
      "workspaceSymbolProvider": true,
      "codeActionProvider": true,
      "documentFormattingProvider": true,
      "documentRangeFormattingProvider": false,
      "renameProvider": true,
      "documentLinkProvider": {
        "resolveProvider": false
      },
      "colorProvider": false,
      "executeCommandProvider": {
        "commands": []
      },
      "workspace": {
        "workspaceFolders": {
          "supported": true,
          "changeNotifications": true
        }
      },
      "experimental": null
    }
  }
}
>>> julia-ls:9711(async)
Content-Length: 69

{
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {
  }
}

>>> julia-ls:9711(async)
Content-Length: 231

{
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///home/akaberto/a.jl",
      "languageId": null,
      "version": 0,
      "text": "a = 1 + 1\n\n\n\nfo"
    }
  }
}

>>> julia-ls:9711(async)
Content-Length: 165

{
  "jsonrpc": "2.0",
  "method": "textDocument/documentLink",
  "params": {
    "textDocument": {
      "uri": "file:///home/akaberto/a.jl"
    }
  },
  "id": 23
}

>>> julia-ls:9711(async)
Content-Length: 366

{
  "jsonrpc": "2.0",
  "method": "textDocument/codeAction",
  "params": {
    "textDocument": {
      "uri": "file:///home/akaberto/a.jl"
    },
    "range": {
      "start": {
        "line": 4,
        "character": 0
      },
      "end": {
        "line": 4,
        "character": 2
      }
    },
    "context": {
      "diagnostics": []
    }
  },
  "id": 24
}

>>> julia-ls:9711(async)
Content-Length: 221

{
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "file:///home/akaberto/a.jl"
    },
    "position": {
      "line": 4,
      "character": 0
    }
  },
  "id": 25
}

>>> julia-ls:9711(async)
Content-Length: 221

{
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "file:///home/akaberto/a.jl"
    },
    "position": {
      "line": 4,
      "character": 2
    }
  },
  "id": 26
}

>>> julia-ls:9711(async)
Content-Length: 229

{
  "jsonrpc": "2.0",
  "method": "textDocument/signatureHelp",
  "params": {
    "textDocument": {
      "uri": "file:///home/akaberto/a.jl"
    },
    "position": {
      "line": 4,
      "character": 2
    }
  },
  "id": 27
}

<<<< julia-ls:9711
{
  "method": "client/registerCapability",
  "id": "278352324",
  "params": {
    "registrations": [
      {
        "method": "workspace/didChangeWorkspaceFolders",
        "id": "28c6550c-bd7b-11e7-abc4-cec278b6b50a"
      }
    ]
  },
  "jsonrpc": "2.0"
}
>>> julia-ls:9711(async)
Content-Length: 62

{
  "jsonrpc": "2.0",
  "id": "278352324",
  "result": null
}


```

**Comment by AkashGanesan** [comment] 2019-04-19 14:29
Also, what should I know what is being passed to the language server so that I can open an issue there if it is a LanguageServer.jl issue.

**Comment by yyoncho** [comment] 2019-04-21 19:08
you may set lsp-print-io to t and then check the content of \*lsp-log\*.

**Comment by AkashGanesan** [comment] 2019-04-22 02:00
The last few lines of the *lsp-log* are as follows

```

>>> julia-ls:30708(async)
Content-Length: 228

{
  "jsonrpc": "2.0",
  "method": "textDocument/signatureHelp",
  "params": {
    "textDocument": {
      "uri": "file:///home/akaberto/a.jl"
    },
    "position": {
      "line": 0,
      "character": 1
    }
  },
  "id": 8
}

<<<< julia-ls:30708
{
  "method": "client/registerCapability",
  "id": "278352324",
  "params": {
    "registrations": [
      {
        "method": "workspace/didChangeWorkspaceFolders",
        "id": "28c6550c-bd7b-11e7-abc4-cec278b6b50a"
      }
    ]
  },
  "jsonrpc": "2.0"
}
>>> julia-ls:30708(async)
Content-Length: 62

{
  "jsonrpc": "2.0",
  "id": "278352324",
  "result": null
}

```

**Comment by AkashGanesan** [comment] 2019-04-24 14:47
Any clue as to what is going on and if there's something I can help with?

**Comment by yyoncho** [comment] 2019-04-24 14:59
1. This is not the full log.
2. You may try to use lsp-mode from melpa stable to check whether it was caused by something new introduced in lsp-mode
3. You may try with the julia language server that is packaged with vscode extension
4. If it works in vscode but it does not work in lsp-mode we may compare what the traffic generated by lsp-mode and vscode.

**Comment by yyoncho** [comment] 2019-04-24 15:04
5. And also check the error buffer.

**Comment by gdkrmr** [comment] 2019-04-24 15:24
last time I checked, all Language Server dependencies had to be master, latest release did not work.

**Comment by AkashGanesan** [comment] 2019-04-24 15:28
1. Updated the log now.

@gdkrmr : All of them are at master in my build.  Including the dependencies.

**Comment by yyoncho** [comment] 2019-04-24 15:36
> 1. Updated the log now.

I do not see anything suspicious.

**Comment by gdkrmr** [comment] 2019-04-24 16:37
I have the same issue now with both the latest releases and latest master of all LanguageServer.jl packages. This is a LanguageServer.jl specific problem an I opened an Issue there (https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/341)

**Comment by gdkrmr** [comment] 2019-04-25 08:18
try the following:
```julia
(v1.1) pkg> add CSTParser#24c51db DocumentFormat#5f1b151 JSON#741cbd5 LanguageServer#d355ba6 StaticLint#b26ec4f SymbolServer#be60a94 Tokenize#24e5179 URIParser#7d0dc91
```
these are exactly the versions that VSCode uses (https://github.com/JuliaEditorSupport/julia-vscode/tree/master/scripts/languageserver/packages).

Also set 
```elisp
     (julia :variables
            lsp-julia-command "julia-1.1"
            lsp-julia-default-environment "/home/gkraemer/.julia/environments/v1.1"
            julia-mode-enable-lsp t
            julia-mode-enable-ess nil)
```
to the correct values in your layer configuration to match the same julia installation.

I still get the same error. I haven't tried with julia 1.0 yet.

**Comment by AkashGanesan** [comment] 2019-04-25 20:47
I tried it with julia-1.0.3  I've the same error still.

**Comment by d1cker** [comment] 2019-05-04 11:59
got the same thing on windows with lsp-mode

**Comment by AkashGanesan** [comment] 2019-05-06 04:24
Can we label this as a bug?

**Comment by gdkrmr** [comment] 2019-05-12 17:41
Fixed with latest `lsp-mode` from Melpa, see https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/341 for details.

**Comment by AkashGanesan** [comment] 2019-05-17 12:37
I tried.  It still doesn't work.

**Comment by gdkrmr** [comment] 2019-10-23 20:15
you should add `lsp` to `dotspacemacs-configuration-layers` and not  add `lsp-mode` manually.

**Comment by duianto** [comment] 2019-11-09 18:15
Since it looks like the issue authors issue has been solved, let's close this.

**Closed by duianto** 2019-11-09 18:15 UTC
Labels: - Bug tracker -, Julia
