### ISSUE TITLE
SPC f e R reset spacemacs layouts

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#4433] opened 2016-01-05 18:09 UTC
Pretty annoying, when re-syncing the dotfile the layouts are reset and must be explicitly reloaded with `SPC l L`

**Comment by d12frosted** [comment] 2016-01-05 18:14
:+1:

**Comment by StreakyCobra** [comment] 2016-01-05 18:26
Closing as duplicate of #3875 (I hope I'll not be fired :grin:)

**Closed by StreakyCobra** 2016-01-05 18:26 UTC
Labels: bug :-(, Dotfile, Spacemacs Layouts

**Comment by syl20bnr** [comment] 2016-01-05 19:21
@StreakyCobra your knowledge of the issue database is impressive! (so no you are not fired :-D)
