### ISSUE TITLE
Tern binary not found when launching spacemacs but tern-mode can enabled manually

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#7905] opened 2016-12-04 08:17 UTC
My .spacemacs has following lines in user-config()
```
  (setenv "PATH" (concat (getenv "PATH") ":/usr/share/vim/vimfiles/node_modules/tern/bin"))
  (setq exec-path (append exec-path '("/usr/share/vim/vimfiles/node_modules/tern/bin")))
```

The above path exists.

But still get warning when launching spacemacs:
- tern binary not found!      

I open one js file and enable tern-mode with M-x tern-mode.
The tern server is launched successfully.

How to eliminate the warning message?

**Comment by bostonaholic** [comment] 2016-12-09 03:10
Related to #7497

**Comment by bmag** [comment] 2016-12-10 07:43
@csfreebird try moving those lines to user-init. If that doesn't work, then it's probably a duplicate of #7497 (thanks @bostonaholic)

**Closed** 2018-05-26 11:02 UTC
Labels: - Bug tracker -, JavaScript
