### ISSUE TITLE
Commit 2b139ac has issue

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#7832] opened 2016-11-25 00:55 UTC
#### Description :octocat:
Commit 2b139ac causes `SPC j i` always call `helm-restclient` no matter which major mode I'm at.

#### Reproduction guide :beetle:
- Start Emacs
- Open any program file, like a JavaScript file or a Python file
- Type `SPC j i`

*Observed behaviour:* :eyes: :broken_heart:
When type `SPC j` usually the following `i` should trigger imenu for my major mode, but now it always give `helm-restclient` which has nothing to do with my current editing file

*Expected behaviour:* :heart: :smile:
`SPC j i` should hornor current major mode

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. a1516a6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(osx
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
 better-defaults emacs-lisp imenu-list colors
 (mu4e :variables mu4e-enable-mode-line t mu4e-enable-notifications t)
 (version-control :variables version-control-diff-tool 'diff-hl)
 (shell :variables shell-default-shell 'ansi-term)
 markdown csv gtags yaml git html
 (scala :variables scala-use-unicode-arrows t)
 javascript typescript ansible python django evil-commentary org syntax-checking restclient vinegar)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment] 2016-11-25 09:51
@syl20bnr is this the intended behavior?
@liujoey you can use `SPC s j` in the meantime.

**Comment by syl20bnr** [comment] 2016-11-27 17:58
nope, should be available only if the user is not user `ob-http`.

**Comment by bmag** [comment] 2016-12-07 18:44
#7875

**Comment by smile13241324** [comment] 2017-01-16 19:34
I have noticed that ticket while I was looking for an easy issue to fix.

It seems that the merge request #7875 is not longer necessary.
When I use `SPC j i` it already calls `spacemacs/helm-jump-in-buffer` in org as well as in elisp mode in develop and master.
  
I think this ticket should be closed

**Comment by bmag** [comment] 2017-01-17 08:01
@smile13241324 thanks, you're correct. It was fixed by https://github.com/syl20bnr/spacemacs/commit/590f2298542253e1b5edc747a074ee13c0ca5430

**Closed** 2017-01-17 11:54 UTC
Labels: - Bug tracker -, Beginner friendly, Fixed in develop, Helm, Key Bindings
