### ISSUE TITLE
spacemacs/next-real-buffer loops if no real buffers are open

### ISSUE THREAD

**Issue by conklech** [syl20bnr/spacemacs#1617] opened 2015-05-16 21:45 UTC
When you first start spacemacs there are four "special" buffers and no real buffers open. If you engage the spacemacs buffer micro-state (`SPC b .`) and press `n` or `N` (`spacemacs/next-real-buffer` or `spacemacs/prev-real-buffer`) you get a hard crash as it loops endlessly looking for a real buffer.

It looks like the functions are intended to give up after a hundred iterations, but here at least (Windows, emacs 24.3) it spins for at least a minute before I force-kill it.

**Comment by person808** [comment] 2015-05-17 01:56
I cannot reproduce this bug. By default, `*scratch*` is the only useful buffer created on startup. Even when deleting the `*scratch*` buffer, I can not trigger an infinite loop. The function should only try to loop once through the list of buffers and give up if there are no real buffers.

**Comment by conklech** [comment] 2015-05-17 02:14
@person808 - Are you on `master`? Your description doesn't seem consistent with [the definition of `next-real-buffer` that I see](https://github.com/syl20bnr/spacemacs/blob/d56a2b0ef51abe5c5d216f6e201c4eda3d160a1e/spacemacs/funcs.el#L348).

I'd be glad to provide more information for reproduction. I cloned `master` this morning; the `*spacemacs*` buffer says version 0.101.4.

**Comment by person808** [comment] 2015-05-17 02:17
I'm on `develop` theres been a lot of changes since the last release. This bug is fixed on `develop`

**Closed** 2015-06-01 03:44 UTC
Labels: bug :-(, Fixed in `develop`
