### ISSUE TITLE
Emacs-lisp macrostep micro-state not working

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#2886] opened 2015-09-04 16:43 UTC
When I try to use the macroexpand mini-state, via `,dm` on the following form:
```emacs-lisp
(defmacro foobar (x)
  `(cons ,x '(foo bar)))

(foobar 5)
```

 I get the following error:

`up-list: Scan error: "Unbalanced parentheses", 87, 1`

**Comment by syl20bnr** [comment] 2015-09-04 19:29
There is a bug which is that the point must be _on_ the closing parenthesis, not after. I did not dig where this difference comes from. Maybe some special handling for evil in macrostep.

**Comment by StreakyCobra** [comment] 2015-11-20 11:41
@luxbock Is this bug still valid? I can't reproduce it, maybe can you give more steps on how to reproduce?

**Comment by luxbock** [comment] 2015-11-28 04:03
@StreakyCobra It's valid in the way that @syl20bnr described it. If the point is on top of the closing parentheses then everything works fine for me, but if the point is after the last closing parentheses then I am still getting the same error.

**Comment by StreakyCobra** [comment] 2015-11-28 15:30
Ok thanks. From my point of view I don't see the problem of having to be inside or over the parenthesis to expend it. But there is probably a good reason.

Alright then, I hope someone will try to fix this :relaxed:

**Comment by justbur** [comment] 2016-02-18 00:44
This is not a bug. You're simply doing it wrong :smile: Here's the documentation

```
Expand the macro form following point by one step.

Enters ‘macrostep-mode’ if it is not already active, making the
buffer temporarily read-only. If macrostep-mode is active and the
form following point is not a macro form, search forward in the
buffer and expand the next macro form found, if any.
```

**Comment by StreakyCobra** [comment] 2016-02-18 09:30
@justbur Thanks
@luxbock It seems to be as expected then. I'm closing this issue, let me know if you think it shouldn't be.

**Closed by StreakyCobra** 2016-02-18 09:30 UTC
Labels: bug :-(
