### ISSUE TITLE
spacemacs/sort-lines, optional argument, sort-reverse function and key binding

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#7978] opened 2016-12-16 18:27 UTC
#### 1. A visual block selection doesn't sort the selected lines.
The whole buffer gets sorted when a <kbd>C-v</kbd> visual block selection is active.

#### Reason
`spacemacs/sort-lines` checks `(region-active-p)`, if it's: `t`, then the region gets sorted, but if it's: `nil` then the whole buffer gets sorted.

When a visual block selection is active then `(region-active-p)` returns: `nil`

#### Possible solution
Change `(region-active-p)` to `(evil-visual-state-p)`, because it seems to return: `t`, for these selection commands (maybe there are more selection commands):
<kbd>v</kbd> (evil-visual-char)
<kbd>S-v</kbd> (evil-visual-line)
<kbd>C-v</kbd> (evil-visual-block)
<kbd>C-SPC</kbd> (set-mark-command)
<kbd>C-x SPC</kbd> (rectangle-mark-mode)

#### Before:
```
  (let ((beg (if (region-active-p) (region-beginning) (point-min)))
        (end (if (region-active-p) (region-end) (point-max)))
```
#### After:
```
  (let ((beg (if (evil-visual-state-p) (region-beginning) (point-min)))
        (end (if (evil-visual-state-p) (region-end) (point-max))))
```
#### Possible `(evil-visual-state-p)` issue
Will `(evil-visual-state-p)` work for people that use the Emacs editing style?

If not then maybe `(evil-mode)` could be checked and if it's true, then check: `(evil-visual-state-p)` otherwise check `(region-active-p)`.

#### 2. There are two instances when the cursor doesn't get restored correctly.
- When a <kbd>S-v</kbd> line selection is active then the cursor ends up on the first selected line, even if the selection was made from top to bottom.

- When there's no active selection and the whole buffer gets sorted, then the cursor ends up on the buffers first line.

#### A. Add an optional argument to `spacemacs/sort-lines`
`spacemacs/sort-lines` doesn't accept an argument, it just passes `nil` to the `sort-lines` command. A non-nil argument makes it possible to sorts the lines in reverse order with for example: <kbd>SPC u SPC x l s</kbd>.

#### Before:
```
(defun spacemacs/sort-lines ()
  "Sort lines in region or current buffer"
...
(sort-lines nil beg end)
```
#### After:
```
(defun spacemacs/sort-lines (&optional arg)
  "Sort lines in a region or the current buffer.
A non-nil argument sorts in reverse order."
...
(sort-lines arg beg end)
```

#### B. Add a function and key binding that sorts in the opposite direction
```
(defun spacemacs/sort-lines-reverse (&optional arg)
  "Sort lines in reverse order, in a region or the current buffer.
A non-nil argument sorts in non-reverse order."
  (spacemacs/sort-lines (if arg nil "non-reverse")))
```

"non-reverse order" sounds a bit strange, maybe the function should be written with "ascending" and "descending":

```
(defun spacemacs/sort-lines-descending (&optional arg)
    "Sort lines in descending order, in a region or the current buffer.
A non-nil argument sorts in ascending order."
  (spacemacs/sort-lines (if arg nil "descending")))
```

It should probably be bound to: <kbd>SPC x l S</kbd>, since a lot of commands work in the opposite direction when the uppercase key is pressed.

If "ascending" and "descending" order are better choices, then maybe the `spacemacs/sort-lines` function also should be renamed to `spacemacs/sort-lines-ascending`. At least it's function comment will need to be updated.

#### I. Should a message be shown when the sorting is done?
`(message "Lines sorted%s" (if arg " in reverse order." "."))`

> Lines sorted.
> Lines sorted in reverse order.

or
`(message "Lines sorted in %s order." (if arg "descending" "ascending"))`

> Lines sorted in ascending order.
> Lines sorted in descending order.

or something better.

#### II. Should the lines be counted?
If the lines in the region or buffer are counted, then the number of sorted lines could be shown: "12 lines sorted in reverse (descending) order.". And if there's only one line then a message could be shown: "Sorting requires two or more lines."

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 6288b28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(auto-completion autohotkey emacs-lisp git helm html org)
‘‘‘
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by bmag** [comment] 2016-12-17 13:47
About issue 1: I can reproduce. Changing `region-active-p` to something else (maybe `use-region-p`) might solve this issue. 
> Will `(evil-visual-state-p)` work for people that use the Emacs editing style?

Probably not, and checking value of `evil-mode` won't help either since it's `t` also in Emacs style (and you can check that yourself by toggling Emacs style `SPC t E e`).

About issue 2: not sure what's the issue here. I was not aware that any "cursor restoration" is supposed to happen, and I'm unable to understand what are your expectations of such a restoration.

About suggestions A and B: sure, why not. Just needs someone to write them.

About question I: re-arranging the lines is enough of a visual indication, no need for a message as well.
About question II: irrelevant if you accept my answer to question I.

P.S. can you give us a TL;DR next time? It was hard to read this report.

**Comment by duianto** [comment] 2016-12-20 16:39
Sorry for forgetting the TL;DR section.
<hr>

> (maybe use-region-p) might solve this issue.

`use-region-p` also returns `nil` when a `evil-visual-block` is active. But i noticed that there's an `evil-emacs-state-p` command, it can be used to check `region-active-p` when the emacs state is active, otherwise it checks `evil-visual-state-p`.

I tested that solution with all 10 states: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#states , and the `spacemacs/sort-lines` command still works in all but one of them.

In the hybrid modes insert state `evil-hybrid-state`, there the whole buffer gets sorted instead of the selected lines. That's because both the `evil-emacs-state-p` and the `evil-visual-state-p` return `nil`. It can be solved by also checking for `(evil-hybrid-state-p)`.

``` elisp
  (let* ((region-active (if (or (evil-emacs-state-p) (evil-hybrid-state-p))
                            (region-active-p)
                          (evil-visual-state-p)))
```

The reason why `evil-visual-block` makes `region-active-p` return `nil`, seems to be because, it calls the command: `(evil-transient-mark -1)`. I'm guessing that it might be so that the selection can be drawn as an actual rectangle (like it does in vim):
![evil-visual-block](https://cloud.githubusercontent.com/assets/13420573/21321966/4cb28b8c-c617-11e6-9417-307f18a8c8a7.png)

Unlike a `rectangle-mark-mode` selection which shows the selection extending to the right and left edges of the window between the start and end of the selection.
![rectangle-mark-mode](https://cloud.githubusercontent.com/assets/13420573/21321970/51c013e2-c617-11e6-9a0d-a342d0c694e7.png)
<hr>

> I was not aware that any "cursor restoration" is supposed to happen, and I'm unable to understand what are your expectations of such a restoration.

My description wasn't very clear now that i read it again. I was expecting the cursor to stay where it was before the lines were sorted. The `sort-lines` function in `sort.el` uses `save-excursion` to save and restore the cursors position. But it only seems to work on these selection modes:
<kbd>v</kbd> `evil-visual-char`
<kbd>C-v</kbd>  `evil-visual-block`
<kbd>C-SPC</kbd> `set-mark-command`
<kbd>C-x SPC</kbd> `rectangle-mark-mode`

It isn't perfect, sometimes the cursor moves to the right by a couple of characters when the length of the sorted lines vary.
Example:
[8]73568
234
7652
13478
257
- move the cursor to the first character: 8
- <kbd>v</kbd> `evil-visual-char` select to the 2 on the last line
- sort the lines <kbd>SPC x l s</kbd>

13478
2
234
7652
87356[8]57
the cursor ends up on the second 8 on the last line, but at least it's on the same line.

But here's the real issue, when a <kbd>S-v</kbd> `evil-visual-line` selection is active, then the cursor moves to the top most (first) selected line, and when there's no active selection, then the whole buffer gets sorted and the cursor jumps to buffers first line.
<hr>

> About question I: re-arranging the lines is enough of a visual indication, no need for a message as well.
> About question II: irrelevant if you accept my answer to question I.

It's fine if the messages and counting are left out, there are other functions for counting lines.
<hr>

This is what i've come up with so far. Suggestions welcome if there's something that can be improved.

`.emacs.d/layers/+distributions/spacemacs-base/funcs.el`

``` elisp
(defun spacemacs/sort-lines (&optional reverse)
  "Sort lines in a region or the current buffer.
A non-nil argument sorts in reverse order."
  (interactive "P")
  (let* ((region-active (if (or (evil-emacs-state-p) (evil-hybrid-state-p))
                            (region-active-p)
                          (evil-visual-state-p)))
         (beg (if region-active (region-beginning) (point-min)))
         (end (if region-active (region-end) (point-max))))
    (sort-lines reverse beg end)))

(defun spacemacs/sort-lines-reverse ()
  "Sort lines in reverse order, in a region or the current buffer."
  (interactive)
  (spacemacs/sort-lines -1))
```

`.emacs.d/layers/+distributions/spacemacs-base/keybindings.el`
``` elisp
  "xlS" 'spacemacs/sort-lines-reverse
```

Here's an attempt at restoring the cursors position:
``` elisp
(defun spacemacs/sort-lines (&optional reverse)
  "Sort lines in a region or the current buffer.
A non-nil argument sorts in reverse order."
  (interactive "P")
  (let* ((region-active (if (or (evil-emacs-state-p) (evil-hybrid-state-p))
                            (region-active-p)
                          (evil-visual-state-p)))
         (beg (if region-active (region-beginning) (point-min)))
         (end (if region-active (region-end) (point-max)))
         (pre-sort-cursor-line-pos (line-number-at-pos))
         (pre-sort-cursor-column-pos (current-column)))
    (sort-lines reverse beg end)
    ;; Restore the cursors position to the same line and column
    ;; or to the end of the line if it became shorter.
    (goto-char (point-min))
    (forward-line (1- pre-sort-cursor-line-pos))
    (setq line-length (- (line-end-position) (line-beginning-position)))
    (if (< line-length pre-sort-cursor-column-pos)
        (goto-char (line-end-position))
      (forward-char pre-sort-cursor-column-pos))))
```
With this solution, then the cursor doesn't move in all but one case: When a `evil-visual-line` selection is active.

**Comment by duianto** [comment] 2016-12-21 13:45
I noticed that the `spacemacs/uniquify-lines` function has the same problem with a <kbd>C-v</kbd> `evil-visual-block` selection, it uniquifies the whole buffer:
``` elisp
(defun spacemacs/uniquify-lines ()
  "Remove duplicate adjacent lines in region or current buffer"
  (interactive)
  (save-excursion
    (save-restriction
      (let ((beg (if (region-active-p) (region-beginning) (point-min)))
            (end (if (region-active-p) (region-end) (point-max))))
        (goto-char beg)
        (while (re-search-forward "^\\(.*\n\\)\\1+" end t)
          (replace-match "\\1"))))))
```

If the suggested `spacemacs/sort-lines` solution works, for checking `region-active-p` in emacs and hybrid state, otherwise `evil-visual-state-p`, then it could be used for this function as well.

**Comment by bmag** [comment] 2016-12-23 19:10
Well, it seems to me the correct condition to use is:
```elisp
(or (region-active-p) (evil-visual-state-p))
```
However, in `C-v` selection `spacemacs/sort-lines` is still going to sort all the text between the top-left and bottom-right corners of the selection, not only the part of it that's inside the highlighted block. Fixing that would probably require ditching the built-in `sort-lines`.

As for point restoration, my understand is that the point needs to end on the line that has the same contents as the first or last line of the original selection. It would probably be easier to save the line's contents before sorting, and later search for the contents with a search expression. (`search-forward` etc.)

**Comment by duianto** [comment] 2016-12-23 23:02
`(or (region-active-p) (evil-visual-state-p))` is much better 😄.

Is there a preferred choice between assigning the region/visual state to a variable, and checking that variable when the `beg` and `end` assignments occur:
```elisp
  (let* ((region-active (or (region-active-p) (evil-visual-state-p)))
         (beg (if region-active (region-beginning) (point-min)))
         (end (if region-active (region-end) (point-max)))))
```
Or should the region/visual state be checked directly with each `beg` and `end` assignment, without the additional `region-active` variable:
```elisp
  (let ((beg (if (or (region-active-p) (evil-visual-state-p))
                 (region-beginning)
               (point-min)))
        (end (if (or (region-active-p) (evil-visual-state-p))
                 (region-end)
               (point-max)))))
```
the second choice can use a `let` instead of `let*` because an earlier assigned variable won't be needed in a later variable. I don't know if it matters, but just something i noticed. The second choice could also be joined to just two lines, but they would be 93 chars wide, so i'm guessing that it's better to split them.

#### Block/Rect sorting:
A <kbd>C-v</kbd> `evil-visual-block` selection also being sorted as lines is expected behavior since the function is called `spacemacs/sort-lines`. Sorting the selected contents of a block/rectangle selection could be implemented as an additional sort function, possibly named something like `sort-rectangle` or `sort-block`, but that might be a future project if there's a lot of requests for such a feature.

#### Sorting a column, functions and key bindings
There's a `sort-columns` function in `sort.el`, it seems to sort the selected lines by the left most selected column.

#### Question:
If it would be useful to have `spacemacs/sort-columns` and `spacemacs/sort-columns-reverse` functions implemented with the key bindings: 
<kbd>SPC x l c</kbd> for `spacemacs/sort-columns (&optional reverse)` 
<kbd>SPC x l C</kbd> for `spacemacs/sort-columns-reverse`.

Then i could make a PR of it when we get the `spacemacs/sort-lines` functions working.

#### Point restoration
If i understood the `search-forward` suggestion correctly, then it sounds like the cursor would move to the new location of the line that was under the cursor when the sort command was called. 

Then that's not what i was suggesting, it might have been the phrase "cursor doesn't get restored correctly" and the poor explanation i initially gave, that caused the confusion. What i meant was that the cursor would stay in the same location relative to the buffer.
Ex:
876
12[3]
745

if the cursor is on the 3 and the <kbd>SPC x l s</kbd> `spacemacs/sort-lines` key binding is pressed, then the lines get sorted into:
123
74[5]
876

but the cursor would remain on the same line and in the same column, but if the middle line would have become shorter then the cursor would move to the end of the line.

**Comment by bmag** [comment] 2016-12-24 08:44
To summarize:
- The condition in `spacemacs/sort-lines` needs to change to:
```elisp
(or (region-active-p) (evil-visual-state-p))
```
It can use either of `let` or `let*` versions, it really doesn't matter. Personally I'd go with the `let*` version.

- restore point to same column and line: we can live without it, but if you want to implement it: `line-number-at-pos` returns current line number, `current-column` returns the current column number (maybe not accurately), `move-to-column` moves point to a column in the current line, moving to a line can be done with: (suggested by `goto-line`'s documentation)
```elisp
(goto-char (point-min))
(forward-line (1- N))
```

- `spacemacs/sort-columns`: PR welcome
- `sort-block`/`sort-rectangle`: PR welcome, but I agree it would be harder to implement

**Closed** 2017-01-14 22:56 UTC
Labels: - Bug tracker -, Fixed in develop
