### ISSUE TITLE
Saving a markdown file sometimes replaces plus symbols (+) with bar symbols (|)

### ISSUE THREAD

**Issue by bch29** [syl20bnr/spacemacs#8237] opened 2017-01-23 18:04 UTC
#### Description :octocat:

Saving a markdown file sometimes replaces `+` with `|`. This seems to happen specifically whenever the pattern '-+-' occurs, no matter where in the line.

#### Reproduction guide :beetle:
- Start Emacs
- Open a buffer in markdown-mode
- Enter the text "-+-"
- Save with [SPC f s]

*Observed behaviour:* :eyes: :broken_heart:
The '+' turns into a '|'.

*Expected behaviour:* :heart: :smile:
The '+' remains as is.

#### System Info :computer:
- OS: gnu/linux (Arch Linux)
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts auto-completion emacs-lisp git github version-control latex markdown shell syntax-checking haskell agda extra-langs sml spell-checking scheme yaml java nim terraform common-lisp c-c   javascript rust csharp idris org purescript octave)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
```

**Comment by Stebalien** [comment] 2017-01-24 21:29
I can reproduce this. It's due to a hack to cleanup org tables (spacemacs uses orgtbl-mode to auto format tables). Unfortunately, the hack is wrong; it's an `after-save-hook` that does a global search and replace instead of an advice around some orgtbl-mode function. Worse, there doesn't appear to be an easy way to disable this; you should be able to just exclude the `org-table` package from the `markdown` layer but `org-table` is configured from the `markdown-mode` init function.

Introduced here: https://github.com/syl20bnr/spacemacs/pull/7224/files

**Comment by Stebalien** [comment] 2017-01-24 21:30
CC @robbyoconnor, @d12frosted

**Comment by robbyoconnor** [comment] 2017-01-24 21:47
This may be my fault...

**Comment by robbyoconnor** [comment] 2017-01-24 22:24
@Stebalien, @bch29-- I apologize -- let's fix this so it works -- but don't roll back entirely :) -- I don't feel like doing it though.

**Comment by Stebalien** [comment] 2017-01-24 23:39
Sorry, on review my comment was *way* harsher than intended (it was intended as a polite ribbing but lacked the appropriate emoji). No need to apologize.

**Comment by robbyoconnor** [comment] 2017-01-24 23:45
@Stebalien --- nah I introduced a regression...it worked for my needs...

**Comment by mgsloan** [comment] 2018-01-11 10:32
Uhh, yeah, this kind of magic is terrible and unexpected for users.  Please don't do any sort of "automunge" beyond benign things like whitespace trimming.  Even if the automunge is perfectly correct, this leads to making unintended changes to files.

I typed up a duplicate bug report: https://github.com/syl20bnr/spacemacs/issues/10129

I noticed an even stranger bug, though which is that when I submitted the bug report, every instance of `+` in the bug report got replaced by ` `, even the ones that didn't look like they were in tables, just inline wrapped in backticks.

**Comment by dankessler** [comment] 2021-09-22 22:37
I believe this has now been fixed by [this commit](https://github.com/syl20bnr/spacemacs/commit/b96ace131)

**Closed** 2021-09-22 22:53 UTC
Labels: Fixed in develop, Markdown, - Bug tracker -
