### ISSUE TITLE
Perl 6 layer

### ISSUE THREAD

**Issue by AlexDaniel** [syl20bnr/spacemacs#5019] opened 2016-02-10 14:25 UTC
Would be nice to have a layer for Perl 6. See [perl6-mode](https://github.com/hinrik/perl6-mode).

**Comment by AlexDaniel** [comment] 2016-02-11 20:33
I'll keep some notes here.

Currently fancy quotes are not supported. All these are not working: ``c i ‘``, ``c i “``, ``c i «``, ``c i ｢``.

**Comment by TheBB** [comment] 2016-02-23 09:24
Use `spacemacs|define-text-object` to make new text objects for those things.

https://github.com/TheBB/spacemacs/blob/develop/layers/+distribution/spacemacs-base/packages.el#L378-L387

**Comment by theckman** [comment] 2017-04-26 11:40
@syl20bnr has there been any thought to a Perl 5 layer? I think #7758 may have accidentally been closed as a duplicate of this one.

**Comment by AlexDaniel** [comment] 2017-04-26 11:44
@theckman that's right

**Comment by CeleritasCelery** [comment] 2017-04-26 14:18
People unfamiliar with Perl don't know that Perl 6 and Perl 5 are different languages. There is an attempt at a Perl 5 layer with [#8572](https://github.com/syl20bnr/spacemacs/pull/8572) but I seriously doubt it will get merged because it overextends on scope and is messy. What we really need is simple Perl 5 layer PR to get started with. I have been intending open one. Maybe we should just start with an issue for discussion.

**Comment by AlexDaniel** [comment] 2020-02-29 21:38
Dear bot, I still want this.

**Comment by kalkin** [comment] 2020-03-02 12:55
Dear @AlexDaniel this is solved in the current development branch :)

**Comment by AlexDaniel** [comment] 2020-03-02 13:05
Ah, right, I remember. But… it is **still** in the development branch??

**Comment by kalkin** [comment] 2020-03-02 14:21
@AlexDaniel According to the [CHANGELOG.develop](https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#L353) it is. It's part of the next release I guess…

**Comment by lebensterben** [comment] 2021-08-24 02:21
closing since it's added to develop branch.

**Closed by lebensterben** 2021-08-24 02:21 UTC
Labels: Fixed in develop, Feature request, - Forum -
