### ISSUE TITLE
Ipython can not work.

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#2198] opened 2015-07-03 08:53 UTC
I have a notebook server running. When i want to run a block , I get

```
Error (websocket): in callback `on-open': Cannot send message to a closed websocket: cl-struct-websocket-frame, text, "{\"header\":{\"msg_id\":\"721dfcc1-fbf8-42fb-99e9-b61bee15793f\",\"username\":\"username\",\"session\":\"79f807aa-0ee8-419c-aa02-3e25cda8c31d\",\"msg_type\":\"execute_request\"},\"metadata\":{},\"content\":{\"code\":\"__import__('sys').stdout.write(__import__('os').getcwd())\",\"silent\":true,\"user_variables\":[],\"user_expressions\":{},\"allow_stdin\":true},\"parent_header\":{}}", nil, t
Error (websocket): in callback `on-open': Wrong type argument: arrayp, nil
Error (websocket): in callback `on-close': Wrong type argument: arrayp, nil


```

**Comment by cpaulik** [comment] 2015-07-05 23:34
Could you give a little more details? IPython in emacs works very well for me.

**Comment by CestDiego** [comment] 2015-10-26 01:12
can't reproduce.

**Comment by TheBB** [comment] 2015-10-29 10:34
Please reopen if you can give more information. Closing this now because it is old and @hujianxin hasn't replied.

**Closed by TheBB** 2015-10-29 10:34 UTC
Labels: bug :-(, Python
