### ISSUE TITLE
eyebrowse error

### ISSUE THREAD

**Issue by mateusz-piotrowski** [syl20bnr/spacemacs#14113] opened 2020-11-04 00:11 UTC
In my notebook, I can't install WSL so I decided to use MSYS2.
I install emacs and during setup spacemacs, I received the following error:
![emacs - eyebrowse error](https://user-images.githubusercontent.com/7917509/98054224-a9c30980-1e3a-11eb-91f6-c6f9e86260cb.png)

**Comment by smile13241324** [comment] 2020-11-14 22:49
Duplicate of #14114

**Closed by smile13241324** 2020-11-14 22:49 UTC
