### ISSUE TITLE
Duplicated layer Warnings

### ISSUE THREAD

**Issue by chengyi** [syl20bnr/spacemacs#7494] opened 2016-10-20 09:53 UTC
#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Duplicated layer Warnings

*Expected behaviour:* :heart: :smile:
remove these warnings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. b550945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults emacs-lisp markdown org lua python colors git spacemacs-layouts ranger
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     ycmd auto-completion
     (chinese :variables chinese-enable-youdao-dict t)
     deft prow)
```

#### Backtrace :paw_prints:
```
(Spacemacs) Warning: Duplicated layer prow-ui detected in directory "/home/osboxes/.spacemacs.d/layers/prow-ui", replacing old directory "/home/osboxes/.spacemacs.d/layers/prow-ui/" with new directory.
(Spacemacs) Warning: Duplicated layer prow detected in directory "/home/osboxes/.spacemacs.d/layers/prow", replacing old directory "/home/osboxes/.spacemacs.d/layers/prow/" with new directory.
(Spacemacs) Warning: Duplicated layer prow-develop detected in directory "/home/osboxes/.spacemacs.d/layers/prow-develop", replacing old directory "/home/osboxes/.spacemacs.d/layers/prow-develop/" with new directory.
(Spacemacs) Warning: Duplicated layer prow-misc detected in directory "/home/osboxes/.spacemacs.d/layers/prow-misc", replacing old directory "/home/osboxes/.spacemacs.d/layers/prow-misc/" with new directory.
(Spacemacs) Warning: Duplicated layer prow-org detected in directory "/home/osboxes/.spacemacs.d/layers/prow-org", replacing old directory "/home/osboxes/.spacemacs.d/layers/prow-org/" with new directory.
```

**Comment by chengyi** [comment] 2016-10-20 09:56
as mentioned above the new directory and old directory is almost the same.

**Comment by bmag** [comment] 2016-10-20 10:05
closing as duplicate of #7481

**Closed by bmag** 2016-10-20 10:05 UTC
