### ISSUE TITLE
[auctex] C-` is undefined

### ISSUE THREAD

**Issue by rakyi** [syl20bnr/spacemacs#643] opened 2015-02-20 12:24 UTC
In auctex layer after pressing <kbd>S m b</kbd> ( `auctex/build-view`) message "Errors! Check with C-\`"  is displayed if errors are encountered, but C-\` is undefined.

**Comment by pluskid** [comment] 2015-06-07 01:26
+1

**Comment by TheBB** [comment] 2015-10-19 20:06
Hi guys. This issue is several months old, I can't reproduce it (it says `C-c \`` which works fine for me), and probably a lot of things have changed about this layer since this was reported. I'm going to close this for these reasons and if you find it still happens, please feel free to reopen.

**Closed by TheBB** 2015-10-19 20:06 UTC
Labels: bug :-(, Key Bindings, LaTeX
