### ISSUE TITLE
Neotree/Treemacs opens as window number 1

### ISSUE THREAD

**Issue by piotrpalek** [syl20bnr/spacemacs#9798] opened 2017-10-30 07:59 UTC
#### Description :octocat:
Opening Neotree or Treemacs on the master or develop branch (tried it with clean installs removing .spacemacs and .emacs.d a few times) results in opening the tree view in window number 1. Normally the tree should be opened in window number 0.

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC f t
- Look at window number of the filetree window

*Observed behaviour:* :eyes: :broken_heart:
The filetree opens in window number 1

*Expected behaviour:* :heart: :smile:
The filetree opens in window number 0

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cc73871c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby python helm auto-completion better-defaults emacs-lisp typescript csv yaml lua git github markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control javascript html erlang elixir react treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by piotrpalek** [comment] 2017-10-30 08:02
Relevant discussion on gitter: https://gitter.im/syl20bnr/spacemacs?at=59f67bfe4ff065ac1890571a

**Comment by safijari** [comment] 2017-10-30 22:34
Gyahh, I just ran into this on a new machine and thought it was something weird with the configuration on the new machine.

I know this is new but can someone suggest a way to go back (old version of vimum or whatever?). It's breaking my brain right now.

**Comment by duianto** [comment] 2017-10-30 23:33
### Cause:
The emacs-winum package made the variable `winum-assign-func` obsolete on oct 19
https://github.com/deb0ch/emacs-winum/commit/bfef4ae6d0e0e5f1fb7e13e06298e4692e5b11a6#diff-44da362b85e63f9109555d7fdb343cbdR96

The obsolete variable is used:
in the neotree layer here:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+filetree/neotree/packages.el#L114

and in the treemacs layer here:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+filetree/treemacs/packages.el#L74

### Possible solution:
I followed the instructions in the `winum-assign-functions` doc-string:
In the neotree layer `packages.el` I replaced:
`    (setq winum-assign-func 'spacemacs//winum-neotree-assign-func)`
with:
`    (add-to-list 'winum-assign-functions #'spacemacs//winum-neotree-assign-func)`

In the treemacs layers `packages.el` I replaced: 
`    (setq winum-assign-func #'treemacs--window-number-ten)`
with:
`    (add-to-list 'winum-assign-functions #'treemacs--window-number-ten)`

and now the *tree windows are selected again with `SPC 0`.

**Comment by syl20bnr** [comment] 2017-10-31 03:33
@duianto thank you for the investigation 👍

**Comment by syl20bnr** [comment] 2017-10-31 03:40
Should be fixed in develop.
Tomorrow I'm hot fixing the master branch and release the 200.10 version.

**Comment by piotrpalek** [comment] 2017-10-31 08:11
Fixed for me in develop, thansk! :+1: 
btw. this is a bit offtopic but the selected file in treemacs is _really_ hard to see it's almost indistinguishable from non-selected elements for the dark theme as there is no marker and the background is just very slightly darker. If I have serious problems finding the selected item in the tree I can only imagine that people with color blindness and other issues may not see any difference between selected elements and the rest of them. The light theme is only slightly better imo but still pretty hard to see.

**Comment by Alexander-Miller** [comment] 2017-11-01 10:37
Mea culpa. I made that change a while ago in winum so that multiple packages could grab static numbers without getting in each other's way. It's gotten merged just now, when I'm busy moving and don't have time to make all the necessary fixes.
@duianto's solution is correct, that's how winum is supposed to work now.

> this is a bit offtopic but the selected file in treemacs is really hard to see

AFAIK no spacemacs theme adjustments were made for treemacs. This means the faces treemacs uses for its nodes are inherited from basic syntax highlighting faces and file selection is shown simply via the builtin hl-line-mode. If you're having trouble seeing it it's a general problem.
I used the spacemacs dark theme to take the screenshot in the layer readme and there the selected file has a dark and clearly visible background. Has something changed, or did you customize your theme?

**Comment by syl20bnr** [comment] 2017-11-02 01:55
cc @nashamri ^ :-)

**Comment by duianto** [comment] 2017-11-02 07:43
It's probably not a good idea to just change the contrast of the `hl-line` face's color in the spacemacs themes, because other themes, like these that come with Emacs: leuven, tsdh-dark and tsdh-light, also have a low contrast line highlight (there's probably more themes with the same issue, in for example the `themes-megapack` layer).

It might be better to use another method or face to indicate the cursor in the Treemacs window.

It's probably best if this discussion is continued in a separate issue, since it isn't related to the main window numbers issue that has been solved.

**Comment by piotrpalek** [comment] 2017-11-02 07:53
@Alexander-Miller I think the main issue is that the highlight is sometimes hard to see on a big screen with a big tree open. It seems that treemacs sometimes also highlight the text instead of only the background which would make it much more visible. But I'll try to open a new issue for this to not spam in here. Ok to ping you in there?

@duianto I agree I'll open a new issue for this.

**Comment by Alexander-Miller** [comment] 2017-11-02 08:08
> But I'll try to open a new issue for this to not spam in here. Ok to ping you in there?

👍 

>  It seems that treemacs sometimes also highlight the text instead of only the background which would make it much more visible.

Also worth its own issue. But I'll need more information - if not an outright reproduction recipe, then at least I need to know when this *tends* to happen. My hunch is that this is hl-line-mode not repainting right when interacting with something window layout changing like eyebrowse.

**Comment by nashamri** [comment] 2017-11-02 17:04
Hello all :smile:

I agree with @duianto that it might be not wise to change the contrast of `hl-line`. I think if upstream `treemacs` defined a face for the highlighted item, that would solve the issue. I'm working on theming the other aspects of `treemacs` at the moment.

**Comment by deb0ch** [comment] 2017-11-05 13:45
Hey, it seems like the fix has made its way to master, shouldn't this be closed ?

**Comment by syl20bnr** [comment] 2017-11-12 15:19
Yep, fixed in both branches.

**Closed by syl20bnr** 2017-11-12 15:19 UTC
Labels: - Bug tracker -, File browser, Fixed in develop

**Comment by piotrpalek** [comment] 2018-01-11 11:58
Hey, this is happening to me again after recent updates, can someone confirm?

**Comment by Alexander-Miller** [comment] 2018-01-11 12:04
I assume that's because treemacs now supports multiple frames, so it cannot grab window 10 when the winum scope is global.

Short-term solution: set winum-scope to frame-local
Long-term solution: winum will ignore treemacs in a future update

**Comment by deb0ch** [comment] 2018-01-11 16:03
Or alternative solution: just give treemacs a regular window number.

I don't know if this is the case for many, but I find it both counter intuitive and impractical that a window, even being a treemacs or neotree window, has a special treatment to be numbered 0.

Not only that, but 0 is on most keyboard on the far right end, out of reach for your left hand and away from other window numbers, which I find impractical.

Maybe it is just my opinion, but i don't see how it is not extra effort to:
- either *think* of using your right hand for this special case,
- or make your left hand travel across the keyboard, far away from the homerow.

**Comment by safijari** [comment] 2018-01-11 17:12
My 2 cents: While this bug was active I made an effort to get used to the
treemacs window being window 1 and failed. I very much like that opening
the treemacs window doesn't mess up my existing window numbering. Having to
remember that my window 1 is now window 2 but soon will be window 1 again
when I got spc p t was evidently a bigger burden than pressing 0.

**Comment by safijari** [comment] 2018-01-11 17:13
Reading your question again: I've always used my right hand to press
numbers on the right side so maybe there's part of the disconnect for me.

**Comment by Alexander-Miller** [comment] 2018-01-11 17:39
Giving treemacs its own number achieves 2 goals: it is consistent and non-disruptive - 1) treemacs always has the same number (even when displayed on the right of the screen), so you'll always select it with the same keypress, and 2) as @safijari  said, it does not interfere with the rest of the window numbering.
With the current scheme selecting treemacs is bound to M-0 for me. I see no problem with shifting my right hand to reach 0, in fact it's burned in pretty hard into my hand by now.

With the new multiframe support there is no *good* solution for keeping treemacs' number other than forcing people to set winum to frame-local. The fix will be to instead have winum ignore treemacs. Spacemacs will then bind M-0 to selecting treemacs directly, so you won't have to get rid of your muscle memory.
I'll be dropping the patches over the weekend.

**Comment by deb0ch** [comment] 2018-01-11 18:54
Well, this is Emacs, maybe there is an option for that ? (using 0 or not for treemacs).

Regarding the multi-frame issue, maybe it would make more sense to set 0 to the treemacs window inside the currently focused frame and give treemacs a regular window number in the other frame ?

I'm sure this is technically possible, right ?

I think it would be a lot more intuitive for multi-frame users.

Or maybe I didn't understand the problem ?

**Comment by piotrpalek** [comment] 2018-01-12 13:52
> Regarding the multi-frame issue, maybe it would make more sense to set 0 to the treemacs window inside the currently focused frame and give treemacs a regular window number in the other frame ?

I think this is the most intuitive way. I'm not sure why it should be any other way. I also agree with @Alexander-Miller consistency is key here, the number should/could be configurable but it should stay the same.

**Comment by Alexander-Miller** [comment] 2018-01-14 14:52
PR is a go https://github.com/syl20bnr/spacemacs/pull/10152

> maybe it would make more sense to set 0 to the treemacs window inside the currently focused frame and give treemacs a regular window number in the other frame ?

Possible, with some non-trivial changes to winum, but that would still either shift around window numbers when switching frames or leave them wrong, depending on whether winum updates on frame focus change or not.

**Comment by Alexander-Miller** [comment] 2018-01-15 18:47
Treemacs fix is pushed as well. Winum will now ignore treemacs so long as you don't use more than 5  treemacs buffers on 5 frames.
