### ISSUE TITLE
Colors incorrect at startup with gruvbox

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#8319] opened 2017-02-06 13:59 UTC
When emacs first starts, some colors are set to the Spacemacs dark ones rather than gruvbox (the theme I'm using). This is fixed if I toggle to another theme then back to gruvbox.

Particularly noticeable in the spaceline.

**Comment by deb0ch** [comment] 2017-02-06 14:19
Same here with Monokai, the theme is only partially applied at startup and needs to be manually reapplied.

What's also particularly bothering is that during the entire init process the active theme is only Spacemacs Dark instead of your own, and your own theme is only (partially) applied after the init is done.

**Comment by zwb-ict** [comment] 2017-02-06 14:43
+1 Same here with Seti

**Comment by mahinshaw** [comment] 2017-02-06 16:33
I have the same problem, and it seems to be related to `spacemacs--fallback-theme` and the move to making the spacemacs-theme part of the shipped libs.

**Comment by zestyr** [comment] 2017-02-06 17:32
A simple workaround until an update is released that includes the new theme stuff, is setting the theme to a default one like wombat, and in your user-init, run `(spacemacs/load-theme 'gruvbox)`

**Comment by Nelthorim** [comment] 2017-02-07 09:41
This used to happen with `sanityinc-tomorrow-night` as well, and it was fixed, but it seems that the latest `develop` commits have regressed it for some reason.

**Comment by korayal** [comment] 2017-02-07 11:41
I'm using zenburn and I have the same issue. Then I modified my `dotspacemacs-themes` as below and now it's working alright:

```
   dotspacemacs-themes '((zenburn :location (recipe :fetcher github
                                                    :repo "bbatsov/zenburn-emacs"))
                         monokai
                         spacemacs-dark
                         solarized-dark
                         spacemacs-light
                         solarized-light
                         leuven)
```

**Comment by andrebeat** [comment] 2017-02-07 12:11
I think 252547aa815e2df89c4f5a80046a226f10eece7b is the commit that broke it.

**Comment by beojan** [comment] 2017-02-07 12:34
@zestyr 
> A simple workaround until an update is released that includes the new theme stuff, is setting the theme to a default one like wombat, and in your user-init, run (spacemacs/load-theme 'gruvbox)

That works, but it needs to be `(spacemacs/load-theme gruvbox)` (i.e. without the `'`).

**Comment by fintelkai** [comment] 2017-02-07 14:36
I have the same issue with solarized-light

**Comment by zestyr** [comment] 2017-02-07 16:25
@beojan ah yes, you have to put `(spacemacs/load-theme 'gruvbox)` under user-config, then it works

**Comment by AngelTerrones** [comment] 2017-02-07 19:13
Reporting: i have the same issue with flatland :(

**Comment by deb0ch** [comment] 2017-02-08 08:31
Please stop adding +1 messages, I think we got the point here

**Comment by aaronjensen** [comment] 2017-02-11 19:53
@syl20bnr fyi, this is a regression from the recent changes to the theme system. The workaround mentioend by @korayal worked for me w/ monokai, but obviously it should work the same if you specify `monokai` w/o a github location.

**Comment by syl20bnr** [comment] 2017-02-11 22:23
Sorry for the long delay, should be fixed on develop.

**Comment by mahinshaw** [comment] 2017-02-11 22:29
Fix is working for me

**Comment by zwb-ict** [comment] 2017-02-12 01:17
Fix is working for me too

**Closed** 2017-04-02 06:03 UTC
Labels: - Bug tracker -, Core, Fixed in develop, Loading, Regression :-(, Themes

**Comment by rltbennett** [comment] 2017-06-23 03:15
Still having this issue on master
