### ISSUE TITLE
Guide-key breaks truncate lines

### ISSUE THREAD

**Issue by yangj1e** [syl20bnr/spacemacs#1680] opened 2015-05-21 15:11 UTC
When the cursor is in the visual line, press some key (e.g. `SPC`)  to trigger guide-key frame, then the lines become untruncated. Press navigation keys (e.g. `j`, `k`), the lines resume truncated.

**Comment by TheBB** [comment] 2015-08-27 10:28
Guide-key has been replaced in develop, and I can't reproduce this there. Tentatively labeling as fixed in develop.

**Closed** 2015-09-28 06:53 UTC
Labels: Fixed in `develop`
