### ISSUE TITLE
Meet error when installing everypackage.

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#3187] opened 2015-09-29 05:44 UTC
Today, I found that there was a new version of spacemacs. So I `rm -rf ~/.emacs.d` , and reclone the latest repository.
But when I started up emacs and installed the package, I meet these errors.
```
(Bootstrap) Installing dash...
(Bootstrap) Installing s...
(Bootstrap) Installing bind-key...
(Bootstrap) Installing use-package...
(Bootstrap) Installing package-build...
(Bootstrap) Installing quelpa...
(Bootstrap) Installing which-key...
(Bootstrap) Installing evil...
(Bootstrap) Installing evil-leader...
Found 69 new package(s) to install...
--> fetching new package repository indexes...
--> installing spacemacs:ace-link... [1/69]An error occurred while installing ace-link (error: (void-variable warning-minimum-level))
--> installing spacemacs:ace-window... [2/69]An error occurred while installing ace-window (error: (file-already-exists File exists /home/hujianxin/.emacs.d/elpa/avy-20150922.251/avy-pkg.el))
--> installing spacemacs:avy... [7/69]An error occurred while installing avy (error: (file-already-exists File exists /home/hujianxin/.emacs.d/elpa/avy-20150922.251/avy-pkg.el))
--> installing spacemacs:clean-aindent-mode... [9/69]An error occurred while installing clean-aindent-mode (error: (void-variable warning-minimum-level))
--> installing spacemacs:eval-sexp-fu... [12/69]An error occurred while installing eval-sexp-fu (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-anzu... [13/69]An error occurred while installing evil-anzu (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-exchange... [16/69]An error occurred while installing evil-exchange (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-iedit-state... [17/69]An error occurred while installing evil-iedit-state (error: (void-variable warning-minimum-level))(Bootstrap) Installing dash...
(Bootstrap) Installing s...
(Bootstrap) Installing bind-key...
(Bootstrap) Installing use-package...
(Bootstrap) Installing package-build...
(Bootstrap) Installing quelpa...
(Bootstrap) Installing which-key...
(Bootstrap) Installing evil...
(Bootstrap) Installing evil-leader...
Found 69 new package(s) to install...
--> fetching new package repository indexes...
--> installing spacemacs:ace-link... [1/69]An error occurred while installing ace-link (error: (void-variable warning-minimum-level))
--> installing spacemacs:ace-window... [2/69]An error occurred while installing ace-window (error: (file-already-exists File exists /home/hujianxin/.emacs.d/elpa/avy-20150922.251/avy-pkg.el))
--> installing spacemacs:avy... [7/69]An error occurred while installing avy (error: (file-already-exists File exists /home/hujianxin/.emacs.d/elpa/avy-20150922.251/avy-pkg.el))
--> installing spacemacs:clean-aindent-mode... [9/69]An error occurred while installing clean-aindent-mode (error: (void-variable warning-minimum-level))
--> installing spacemacs:eval-sexp-fu... [12/69]An error occurred while installing eval-sexp-fu (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-anzu... [13/69]An error occurred while installing evil-anzu (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-exchange... [16/69]An error occurred while installing evil-exchange (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-iedit-state... [17/69]An error occurred while installing evil-iedit-state (error: (void-variable warning-minimum-level))
```

I think it's not network error, beause i reinstalled it with japan's vpn, but error again.

**Comment by hujianxin** [comment] 2015-09-29 05:45
Oh, I copied twice the error massages
```
(Bootstrap) Installing dash...
(Bootstrap) Installing s...
(Bootstrap) Installing bind-key...
(Bootstrap) Installing use-package...
(Bootstrap) Installing package-build...
(Bootstrap) Installing quelpa...
(Bootstrap) Installing which-key...
(Bootstrap) Installing evil...
(Bootstrap) Installing evil-leader...
Found 69 new package(s) to install...
--> fetching new package repository indexes...
--> installing spacemacs:ace-link... [1/69]An error occurred while installing ace-link (error: (void-variable warning-minimum-level))
--> installing spacemacs:ace-window... [2/69]An error occurred while installing ace-window (error: (file-already-exists File exists /home/hujianxin/.emacs.d/elpa/avy-20150922.251/avy-pkg.el))
--> installing spacemacs:avy... [7/69]An error occurred while installing avy (error: (file-already-exists File exists /home/hujianxin/.emacs.d/elpa/avy-20150922.251/avy-pkg.el))
--> installing spacemacs:clean-aindent-mode... [9/69]An error occurred while installing clean-aindent-mode (error: (void-variable warning-minimum-level))
--> installing spacemacs:eval-sexp-fu... [12/69]An error occurred while installing eval-sexp-fu (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-anzu... [13/69]An error occurred while installing evil-anzu (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-exchange... [16/69]An error occurred while installing evil-exchange (error: (void-variable warning-minimum-level))
--> installing spacemacs:evil-iedit-state... [17/69]An error occurred while installing evil-iedit-state (error: (void-variable warning-minimum-level))(Bootstrap) Installing dash...

```

**Comment by hujianxin** [comment] 2015-09-29 05:47
My OS is ubuntu 14.04, and Emacs version is 24.3.1

**Comment by robbyoconnor** [comment] 2015-09-29 05:56
Dupe of #3184.

**Comment by hujianxin** [comment] 2015-09-29 09:43
Hi everyone, this issue was resolved after upgrading to emacs 24.5.

**Comment by robbyoconnor** [comment] 2015-09-29 10:39
24.4 or above will not have this issue. We are going to stop supporting 24.3 in the future.

**Comment by wraithan** [comment] 2015-09-29 18:17
Dropping support for the emacs that is in the latest ubuntu LTS repos seems suboptimal. Is there a recommended PPA to grab newer versions from?

http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=emacs24-nox&searchon=names

**Comment by syl20bnr** [comment] 2015-09-29 18:29
Actually we will continue to support 24.3, see https://github.com/syl20bnr/spacemacs/issues/3116#issuecomment-142915183

**Comment by justbur** [comment] 2015-09-29 18:32
@wraithan I can't say recommended because I've never used it, but [this PPA](https://launchpad.net/~andreas-h/+archive/ubuntu/emacs) is the one I saw mentioned when I was looking for information on this.

**Comment by TheBB** [comment] 2015-09-30 07:35
As far as I can tell, this shouldn't happen now on 0.104.2. Please reopen if I am mistaken. :-)

**Closed by TheBB** 2015-09-30 07:35 UTC
Labels: 24.3, High Priority, Install, regression :-(
