### ISSUE TITLE
Solarized Themes not in Helm Themes

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#4062] opened 2015-12-04 21:10 UTC
I have `solarized-light` included in `dotspacemacs-themes`. I can toggle it eventually with `SPC T n`. However, when I type `SPC T h` I don't see the the theme available to select in Helm, even after the theme is installed.

**Comment by StreakyCobra** [comment] 2015-12-05 13:06
Probably a duplicate of #1193 (i.e. not `init-solarized-light` function present)

**Comment by aldanor** [comment] 2016-02-24 10:28
As already reported in #5198, the theme list behaves quite weird and may be extremely confusing to the unaware -- most themes can't be seen at all in `SPC T h` and are only appearing in the list as you cycle through with `SPC T n`.

Would this require upstream changes? How could this be solved? Otherwise, if it's expected, should it be documented?

**Comment by tuhdo** [comment] 2016-02-24 11:01
You have to set `helm-candidiate-number-limit` to `nil` to show all candidates, and in this case, themes. For now, to see all, you have to type the theme name. It's there, just doesn't show, or set `helm-candidiate-number-limit` to `nil`.

We can set it specifically for this command @syl20bnr @TheBB @StreakyCobra .

**Comment by StreakyCobra** [comment] 2016-02-24 12:00
@tuhdo The problem is not that they are not shown in the initial candidates, but that even when filtering the list they don't appear at all.

**Comment by TheBB** [comment] 2016-02-24 12:07
I assume that is because even though themes are listed in `dotspacemacs-themes` they aren't actually installed until you cycle to them. `SPC T h` only lists installed themes.

**Comment by aldanor** [comment] 2016-02-24 12:35
There's two separate problems really -- the main one being that themes that are not "installed" (which is triggered by cycling to them) don't appear in the list. Would it make sense to have an dotspacemacs option to automatically install all themes listed in `dotspacemacs-themes` so it's less confusing to the new users?

The other one is, as @tuhdo mentioned, that it may make sense to set `helm-candidate-number-limit` to `nil` for helm themes list?

**Comment by StreakyCobra** [comment] 2016-02-24 13:03
For the second point, setting it to `nil` breaks helm-flx. I have open an issue upstream https://github.com/PythonNut/helm-flx/issues/16.

**Comment by TheBB** [comment] 2016-02-24 13:17
I think it makes more sense just to install all themes in `dotspacemacs-themes`, period. Presumably they would not be listed there if the user didn't plan on using them. We can curate the default value if that's too much.

**Comment by syl20bnr** [comment] 2016-02-24 17:13
We can wrap them in `cfgl-package` and add them to the list of used packages `configuration-layer--packages`, it will remove the need to protect them and effectively install them.

**Comment by syl20bnr** [comment] 2017-02-02 05:10
WOW I did not remember this dicussion but:

> I think it makes more sense just to install all themes in dotspacemacs-themes, period. Presumably they would not be listed there if the user didn't plan on using them. We can curate the default value if that's too much.

> We can wrap them in cfgl-package and add them to the list of used packages configuration-layer--packages, it will remove the need to protect them and effectively install them.

is basically what I did in last develop, except theme packages are treated like `dotspacemacs-additional-packages` so their owner is the `dotfile`.

I pushed a fix  to set `helm-candidate-number-limit` to `nil`.

Marking this issue as fixed in develop.

**Closed** 2017-04-02 06:00 UTC
Labels: Duplicate ☝, Fixed in develop, Themes
