### ISSUE TITLE
[Windows 10][layer: javascript] `error in process filter: import-js-handle-data: Symbol’s function definition is void: nil`

### ISSUE THREAD

**Issue by dennismayr** [syl20bnr/spacemacs#15174] opened 2021-11-22 14:28 UTC
#### Description :octocat:
Under Windows 10 (new machine at work, Windows 10 is required, haven't used Windows in a couple of years) with cygwin64 and system-wide npm modules (as listed on Spacemacs' documentation for the `develop` branch), the required dependencies for the `javascript` layer + `lsp` have been installed, but when opening a `.js` file, the following messages are shown:
```
Error running timer ‘git-gutter:live-update’: (file-missing "Searching for program" "No such file or directory" "diff")
error in process filter: import-js-handle-data: Symbol’s function definition is void: nil
error in process filter: Symbol’s function definition is void: nil
```

The file is opened, `lsp` server is loaded, `eslint` is loaded, but none have an effect on `lsp-mode` when navigating code: no suggestions, no actions, no correction.
The same layer configuration in Linux works perfectly.
I'm using my same development dotfile from my Linux dev laptop, with minor corrections regarding paths and suggested workarounds.

#### Reproduction guide :beetle:
- Start Emacs (in Windows 10)
- `C-x C-f`, create new `.js` file.
- Write some `javascript` code, see that there are no actions, corrections nor suggestions.
- Or open a `.js` file and observe the same behaviour.

*Observed behaviour:* :eyes: :broken_heart:
The npm dependencies have no effect.

*Expected behaviour:* :heart: :smile:
`lsp-mode` behaves just as it does in Linux.

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1a4912e51)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls c-c++-dap-adapters 'dap-lldb)
 (clojure :variables clojure-backend 'lsp clojure-enable-fancify-symbols t clojure-enable-linters
          '(clj-kondo joker))
 csv
 (dart :variables dart-backend 'lsp lsp-dart-flutter-sdk-dir "~/flutter/bin/" lsp-dart-sdk-dir "~/flutter/bin/cache/dart-sdk/")
 emacs-lisp
 (go :variables go-backend 'lsp go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc gofmt-command "gofumpt")
 graphql groovy
 (html :variables web-fmt-tool 'web-beautify)
 (java :variables java-backend 'lsp)
 (javascript :variables javascript-backend 'lsp javascript-fmt-tool 'web-beautify javascript-import-tool 'import-js javascript-repl 'nodejs js2-include-node-externs t)
 (json :variables json-fmt-tool 'web-beautify)
 (julia :variables julia-backend 'lsp)
 (latex :variables latex-backend 'lsp latex-build-command "LaTeX")
 major-modes octave
 (perl5 :variables perl5-backend 'lsp)
 (plantuml :variables plantuml-jar-path "/usr/share/plantuml/plantuml.jar" org-plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
 (php :variables php-backend 'ac-php-core)
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-test-runner
         '(pytest nose)
         python-formatter 'yapf python-sort-imports-on-save t)
 (rust :variables rust-backend 'lsp lsp-rust-server 'rust-analyzer cargo-process-reload-on-modify t)
 (sql :variables sql-backend 'lsp sql-capitalize-keywords t sql-lsp-sqls-workspace-config-path 'workspace)
 (typescript :variables typescript-backend 'lsp typescript-fmt-tool 'typescript-formatter)
 react
 (vue :variables vue-backend 'lsp)
 ansible asciidoc markdown nginx
 (shell-scripts :variables shell-scripts-backend 'lsp)
 systemd windows-scripts yaml
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults emoji
 (geolocation :variables geolocation-enable-automatic-theme-changer t)
 helm helpful
 (lsp :variables lsp-lens-enable t lsp-headerline-breadcrumb-enable t)
 (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
 nav-flash
 (org :variables org-enable-appear-support t org-enable-asciidoc-support t org-enable-bootstrap-support t org-enable-epub-support t org-enable-hugo-support t org-enable-github-support t org-enable-notifications t org-start-notification-daemon-on-startup t org-enable-org-journal-support t org-journal-dir "~/Documentos/emacs-journal/" org-enable-trello-support t org-enable-valign t org-todo-dependencies-strategy 'naive-auto)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (treemacs :variables treemacs-use-collapsed-directories 3 treemacs-use-git-mode 'deferred treemacs-use-filewatch-mode t treemacs-use-all-the-icons-theme t)
 (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-set
                '("<*" "<*>" "<+>" "<$>" "***" "<|" "|>" "<|>" "!!" "||" "===" "==>" "<<<" ">>>" "<>" "+++" "<-" "->" "=>" ">>" "<<" ">>=" "=<<" "-<" ">-" "-<<" ">>-" "/=" "==" "::" "++"))
 (bibtex :variables bibtex-enable-ebib-support t)
 (cmake :variables cmake-backend 'lsp cmake-enable-cmake-ide-support t)
 copy-as-format epub eww dap debug docker elasticsearch
 (git :variables git-enable-magit-gitflow-plugin t)
 github import-js meson pandoc pdf prettier quickurl search-engine slack syntax-checking systemd templates version-control web-beautify
 (xclipboard :variables xclipboard-enable-cliphist t)
 spotify)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
none yet
```

**Comment by lebensterben** [comment] 2021-11-22 14:44
It says clearly diff is not found.

**Comment by dennismayr** [comment] 2021-11-22 14:55
It is installed, though.

Anyway, this morning's pull seems to have cleared the issue.
Thanks for looking into it!

**Comment by lebensterben** [comment] 2021-11-22 15:53
evaluate (execute-find "diff")

**Comment by dennismayr** [comment] 2021-11-22 16:24
Evaluating with `C-x C-e` shows:

```elisp
Debugger entered--Lisp error: (void-function execute-find)
  (execute-find "diff")
  eval((execute-find "diff") nil)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1064831>)(nil)
  #f(compiled-function (&rest _it) #<bytecode 0x9fb0895>)()
  funcall(#f(compiled-function (&rest _it) #<bytecode 0x9fb0895>))
  eval-sexp-fu-flash-doit-simple(#f(compiled-function (&rest _it) #<bytecode 0x9fb0895>) #f(compiled-function (&rest args2) #<bytecode 0x44bb709>) #f(compiled-function (&rest args2) #<bytecode 0x44bb729>))
  funcall(eval-sexp-fu-flash-doit-simple #f(compiled-function (&rest _it) #<bytecode 0x9fb0895>) #f(compiled-function (&rest args2) #<bytecode 0x44bb709>) #f(compiled-function (&rest args2) #<bytecode 0x44bb729>))
  eval-sexp-fu-flash-doit(#f(compiled-function (&rest _it) #<bytecode 0x9fb0895>) #f(compiled-function (&rest args2) #<bytecode 0x44bb709>) #f(compiled-function (&rest args2) #<bytecode 0x44bb729>))
  (prog1 (eval-sexp-fu-flash-doit do-it-thunk hi unhi) (setq ret t))
  (unwind-protect (prog1 (eval-sexp-fu-flash-doit do-it-thunk hi unhi) (setq ret t)) (if ret nil (funcall eflash)))
  (let (ret) (unwind-protect (prog1 (eval-sexp-fu-flash-doit do-it-thunk hi unhi) (setq ret t)) (if ret nil (funcall eflash))))
  esf-flash-doit(#f(compiled-function (&rest _it) #<bytecode 0x9fb0895>) #f(compiled-function (&rest args2) #<bytecode 0x44bb709>) #f(compiled-function (&rest args2) #<bytecode 0x44bb729>) #f(compiled-function (&rest args2) #<bytecode 0x44bb749>))
  ad-Advice-eval-last-sexp(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1064831>) nil)
  apply(ad-Advice-eval-last-sexp #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1064831>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

```

**Comment by lebensterben** [comment] 2021-11-22 16:29
executable-find

**Comment by dennismayr** [comment] 2021-11-22 16:35
Evaluates to `nil` 😦

(even if `diff` is in `$PATH`)

**Comment by lebensterben** [comment] 2021-11-22 16:38
As I said in the beginning, diff is not found.

**Comment by lebensterben** [comment] 2021-11-22 16:42
Closing since this is not a bug.
Please use other means to solve the question of how to setup emacs in Cygwin.

**Closed by lebensterben** 2021-11-22 16:42 UTC
