### ISSUE TITLE
c/c++ layer company-c-headers should comes before company-ycmd

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#1588] opened 2015-05-13 15:21 UTC
When enable company-ycmd in c-c++ layer, the ycmd company-backend is in front of company-c-headers. When doing header file completion, the ycmd backend will intercept and company-c-headers has no oppurtunity to work.

**Comment by andyque** [comment] 2015-05-13 15:47
I could add

```
  (delete 'company-c-headers company-backends-c-mode-common)
  (delete 'company-clang company-backends-c-mode-common)
  (push 'company-c-headers company-backends-c-mode-common)
```

in my .spacemacs file. 

But I think put the company-c-header backend in the front most is the better default.
Thanks.

**Comment by dzhwinter** [comment] 2015-05-14 04:51
agreed can't any more @andyque

**Comment by zilongshanren** [comment] 2015-07-16 03:01
@dzhwinter  
I have modified the backend to 

```
(setq company-backends-c-mode-common '((company-c-headers
                                          company-ycmd
                                          company-dabbrev :with company-yasnippet)))
```

It's really a big win. yeah :)
Company backends should be grouped sometimes, it's overlooked always.

**Comment by StreakyCobra** [comment] 2015-11-10 22:15
@zilongshanren If you have solved your problems, then we can probably close this issue. If you think this should be Spacemacs' default, I suggest you to PR your changes :relaxed:

**Comment by StreakyCobra** [comment] 2015-12-23 22:28
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.

**Closed by StreakyCobra** 2015-12-23 22:28 UTC
Labels: Auto-completion, C/C++, Waiting for response

**Comment by syl20bnr** [comment] 2018-01-06 06:18
@zilongshanren why did you remove the `company-clang` backend in this message ? https://github.com/syl20bnr/spacemacs/issues/1588#issuecomment-101721599

I'm in the process of refactoring the C/C++ layer to current standard and make some cleanup at the same time.
