### ISSUE TITLE
Box characters?

### ISSUE THREAD

**Issue by adriandeveloper** [syl20bnr/spacemacs#4995] opened 2016-02-08 04:59 UTC
Opened up Spacemacs and got these box characters instead of the normal font. I haven't changed anything from defaults as far as fonts goes.  Any ideas?

![screen shot 2016-02-07 at 10 44 47 pm](https://cloud.githubusercontent.com/assets/3031275/12878669/6a29f474-cdee-11e5-9864-41957b7ded29.png)

**Comment by d12frosted** [comment] 2016-02-08 06:50
It would be helpful to have more information about your setup. Like, what version of emacs you are using (for some reason I don't see it in spacemacs home buffer), which version of spacemacs you are using (the same here).

It looks like you are using Source Code Pro font. Is it possible to use it without any problems in Text Edit (or any other app)?

**Comment by JAremko** [comment] 2016-02-08 07:09
Try installing these fonts [1](https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.zip) [2](http://www.ffonts.net/NanumGothic.font.zip)

*It's actualy looks pretty darn cool. Are you sure you want to change it?  Because it can be hard to reproduce* :smile:

**Comment by d12frosted** [comment] 2016-02-08 07:11
Wow, why NanumGothic? :)

**Comment by JAremko** [comment] 2016-02-08 07:13
@d12frosted  [src](https://github.com/syl20bnr/spacemacs/blob/ef5a2ad5ee6362588244374364fe4ac2df066f37/core/core-fonts-support.el#L33)

```elisp
    ;; fallback font for unicode characters used in spacemacs
    (pcase system-type
      (`gnu/linux
       (setq fallback-font-name "NanumGothic")
       (setq fallback-font-name2 "NanumGothic"))
      (`darwin
       (setq fallback-font-name "Arial Unicode MS")
       (setq fallback-font-name2 "Arial Unicode MS"))
      (`windows-nt
       (setq fallback-font-name "MS Gothic")
       (setq fallback-font-name2 "Lucida Sans Unicode"))
      (`cygwin
       (setq fallback-font-name "MS Gothic")
       (setq fallback-font-name2 "Lucida Sans Unicode"))
      (other
       (setq fallback-font-name nil)
       (setq fallback-font-name2 nil)))
```

**Comment by d12frosted** [comment] 2016-02-08 07:15
Wow. Didn't know about that. Anyway, OP is on OS X (darwin) :D

**Comment by adriandeveloper** [comment] 2016-02-08 07:17
Right. Sorry.  

I'm using Emacs 24.5.1

In my .spacemacs file, I've disabled the Spacemacs Icon but I don't think that has anything to do with the home buffer being enabled (unless I disabled that as well. Here is my current .[spacemacs config file](https://github.com/adriandeveloper/dotfiles/blob/master/.spacemacs)).  I'm using the Release 0.105.x of spacemacs.  In the terminal spacemacs loads just fine albeit the colors or wonky but that's due to the theme I have running. I'm going to edit the .spacemacs font to something else instead of Source Code Pro to see if that fixes the problem.

**Comment by adriandeveloper** [comment] 2016-02-08 07:20
And sure enough, I switch fonts and I actually get something that's readable!  But any idea as to why the Source Code Pro font would work in the Terminal but not in Spacemacs?  I'm using "Sauce Code Pro for Powerline" now.  I'll have to investigate further.

**Comment by JAremko** [comment] 2016-02-08 07:28
Terminal probably uses standard terminal font.

**Comment by d12frosted** [comment] 2016-02-08 08:50
> Terminal probably uses standard terminal font

Menlo regular :) 

@adriandeveloper so what about using this font in any other application (like Text Edit)?

**Comment by adriandeveloper** [comment] 2016-02-08 09:06
@d12frosted I used Source Code Pro font in iTerm, Vim, Atom. It all looks fine.  

@JAremko  wow didn't know about those other backup fonts. I'll try that and see if this is the case.  Thanks.

**Comment by adriandeveloper** [comment] 2016-02-08 10:06
So it looks like my Source Code Pro font has become corrupted.  I don't know what caused it.  @JAremko linked to the font and I reinstalled it.  Sure enough, everything works normally again.  Don't know if there is some log file I could sent to help diagnose. If not, this case can be closed.  Thanks for your help everyone.

**Comment by JAremko** [comment] 2016-02-08 10:08
Glad it helped :+1:

**Comment by StreakyCobra** [comment] 2016-02-08 10:37
I don't think the font corruption issue is related to Spacemacs, so as requested I'm closing it. Let me know if you think the problem is related to Spacemacs.

**Closed by StreakyCobra** 2016-02-08 10:37 UTC
Labels: Fonts
