### ISSUE TITLE
Opening file using "emacs <file>" fails to actually open file

### ISSUE THREAD

**Issue by ElessarWebb** [syl20bnr/spacemacs#4452] opened 2016-01-06 14:18 UTC
emacs <file> 

fails to deliver; instead it just opens the spacemacs homepage. <file> does appear at the top of the recent files list.

**Comment by TheBB** [comment] 2016-01-06 14:28
Thanks, but this is a duplicate of https://github.com/syl20bnr/spacemacs/issues/4057.

**Closed by TheBB** 2016-01-06 14:28 UTC
