### ISSUE TITLE
Broken behavior of x and delete key in evil mode

### ISSUE THREAD

**Issue by kepi** [syl20bnr/spacemacs#2787] opened 2015-08-27 21:55 UTC
I just switched yesterday to develop spacemacs and found out that `x` key is working wrong (= not like in Vim) and same is for `delete` key.

After some digging I think this change was introduced by commit 84ad24f8f  which originates from pull request #2649 

I believe this is bug and not intended behavior.

**Comment by kepi** [comment] 2015-08-27 21:59
Looks like my digging was wrong one :) Reverting that commit doesn't fix issue.

**Comment by syl20bnr** [comment] 2015-08-27 22:27
What behavior do you get ?

It seems to behave correctly here, `x` deletes the current char, `X` the previous char.

Since `delete` does not work as well in your configuration then there must be something that modifier the functions called by evil and delete.

`SPC h d k` or `C-h k` then enter `x` or `delete`, gives me:
- `x` in normal state is bound to `evil-delete-char` with no advice
- `delete` is insert state is bound to `delete-char` again with no advice

**Comment by cpaulik** [comment] 2015-08-27 22:39
I'm not sure if this is what @kepi meant but I just noticed a difference between master and develop which is strange. 

Press `$` in develop and the cursor will move beyond the last character in the line and `x` will not delete anything.
Doing the same on master puts the cursor on the last character and `x` will delete this character.

**Comment by syl20bnr** [comment] 2015-08-27 22:53
@cpaulik see https://github.com/syl20bnr/spacemacs/issues/2525

**Comment by cpaulik** [comment] 2015-08-27 22:57
@syl20bnr Thanks, I did not see this discussion

**Comment by kepi** [comment] 2015-08-27 22:57
In vim and also in emacs with evil mode (and I belive in production spacemacs too) if I press `x` it deletes first current character, than characters after the cursor and than start deleting characters before. Better than to explain, this gif shows correct behavior:

![delete in evil](http://tmp.kepi.cz/spacemacs-delete.gif)

**Comment by cpaulik** [comment] 2015-08-27 23:00
So this is related to the `evil-move-beyond-eol` settings since it does not delete backwards from the last character is this is set.

**Comment by kepi** [comment] 2015-08-27 23:05
Thanks @cpaulik ! With reverting variable back to `nil` it works as it should.

As long as it would be documented in changelog or upgrade notes, it is probably ok even if I personally dislike it.

@syl20bnr if this is what you intended than you can probably close this issue. It will just be really good to put some big notice somewhere :)

**Comment by syl20bnr** [comment] 2015-08-27 23:08
This is something to fix when beyond-eol is set to `t`. Spacemacs is not only Vim it is also Emacs and being able to move behind the last character of a line is very important in Emacs.
I'll try to get `$` and `x` fixed beyond eol.

**Comment by syl20bnr** [comment] 2015-08-27 23:11
duplicate of #2525

**Comment by StreakyCobra** [comment] 2015-11-14 19:48
`evil-mode-beyond-eol` has been set back to `nil` in 41459bea123d534ed48b1e3b50ee97723605b442. This solve this issue, and is coherent with vim behaviour. If `evil-move-beyond-eol` is set, then it's normal that it's not behaving like in vim anymore.

`evil-move-beyond-eol`, `x` (`evil-delete-char`) and `$` (`evil-end-of-line`) are all native `evil` function, so if someone don't like this behaviour it should probably be reported upstream.

I'm closing this issue then, but feel free to open a new one in case of troubles with this. I'm also open to discussion if someone think it's not solved and should be reopened :relaxed:

**Closed by StreakyCobra** 2015-11-14 19:48 UTC
Labels: duplicate (-: :-), Evil
