### ISSUE TITLE
ruby-on-rails Layer Breaks TRAMP

### ISSUE THREAD

**Issue by n4580** [syl20bnr/spacemacs#5857] opened 2016-04-21 21:34 UTC
#### Description

If the ‘ruby-on-rails’ layer is enabled, then the Password: prompt in TRAMP never shows up, and emacs freezes. I tested this on a clean install with both the master and develop branches. The master branch displays a ‘Tramp: Sending password’ message on the master branch just before it freezes. (the server I'm connecting to is replaced with `<domain>` below)

If you `C-g`, it occasionally is able to stop. The messages buffer then displays:

```
Tramp: Opening connection for <domain> using ssh...
Tramp: Sending command `exec ssh   -o ControlMaster=auto -o ControlPath='tramp.%C' -o ControlPersist=no -e none <domain>’
Tramp: Waiting for prompts from remote shell...
Tramp: Sending password
Tramp: Waiting for prompts from remote shell...failed
Tramp: Opening connection for <domain> using ssh...failed
Error in nil (nil): (quit)
```
#### Reproduction guide
- Start Spacemacs with ‘ruby-on-rails’ in ’dotspacemacs-configuration-layers’
- `C-x C-f /ssh:<domain>:/`
- If you don’t have an SSH key enabled, emacs displays the Password: prompt. If ‘ruby-on-rails’ is installed, emacs freezes.

_Observed behaviour:_
On the master branch, the message ‘Tramp: Sending password’ shows up. On the development branch, there is no message. In both cases, emacs appears to freeze. Hitting ‘C-g’ a few times in the GUI version can sometimes unfreeze it.

_Expected behaviour:_
Display a `Password:` prompt
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp ruby-on-rails)
```

**Comment by StreakyCobra** [comment] 2016-04-22 07:38
Not sure it's related to the ruby-on-rails layer. I don't have it and I still have the problem.

**Comment by paradigmshift** [comment] 2016-06-28 14:17
I have the same issue and removing the ruby-on-rails layer fixes it... there must be an incompatibility somewhere there.

**Comment by keigo-brook** [comment] 2016-07-03 07:34
Hi, I'm having same issue.
And I find similar issue here: https://github.com/bbatsov/prelude/issues/594, 
and here https://github.com/bbatsov/projectile/issues/523

This problem seems a projectile bug, and ruby-on-rails layer using projectile, so this happen.

When I remove the ruby-on-rails layer fixed it too, and when I disabled projectile-global-mode, fixed too.

**Comment by keigo-brook** [comment] 2016-10-13 15:46
Hi, After updating to emacs 25.1.1 & Spacemacs 0.200.1, this bug no longer appears.(I'm sorry but I don't know what was the cause)

**Comment by Miciah** [comment] 2018-07-09 00:34
The upstream issue https://github.com/bbatsov/projectile/issues/523 has been closed as fixed.  Can this issue be closed as well?

**Comment by sdwolfz** [comment] 2018-07-09 16:06
👍 This is an old one, I thinks it's safe to close.

**Closed by sdwolfz** 2018-07-09 16:06 UTC
Labels: - Bug tracker -, Bug :-(, Reported upstream, Tramp
