### ISSUE TITLE
[develop] Yanking a multi-line selection in visual mode only yanks first line

### ISSUE THREAD

**Issue by SolidHal** [syl20bnr/spacemacs#14975] opened 2021-08-05 16:39 UTC
#### Description :octocat:
Yanking a multi-line selection in visual mode only yanks first line

only other reference to this issue I could find:
https://old.reddit.com/r/spacemacs/comments/ji3cbu/help_spacemacs_gets_stuck_in_a_weird_state_i_cant/

only workaround I have found is to restart emacs completely. 

unsure if this occurs on master as well

#### Reproduction guide :beetle:
- Start Emacs
- use emacs for a while, sometime days on the same server session
- eventually observe this bug

*Observed behaviour:* :eyes: :broken_heart:
1) select multiple lines in "line" visual mode: "V"
2) press "y" to yank selected lines
3) press "p" to paste the yanked lines
4) observe only one line is pasted, which was the last hightlighted line

ex: if I select and yank all of the `testline#`, starting my selection at testline1 and ending it at testline3:
```
unselectedline_top
testline1
testline2
testline3
unselectedline_bottom
```
I only paste

```
testline3
```

if instead, I start my selection at testline3 and end my selection at testline1
I only paste:

```
testline1
```

*Expected behaviour:* :heart: :smile:
1) select multiple lines in "line" visual mode: "V"
2) press "y" to yank selected lines
3) press "p" to paste the yanked lines
4) observe all selected and yanked lines are pasted

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b3786f52)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(clojure javascript csv yaml html php markdown auto-completion git colors spell-checking syntax-checking c-c++ python shell-scripts lsp emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment] 2021-08-05 20:04
This happens to me sometimes.
If you see something in the minibuffer persistent, try C-w j to switch the focus there, and SPC w d to close it. This should not happen and is a bug.

**Comment by duianto** [comment] 2021-08-06 12:38
This is a duplicate of:
Evil search bug breaks Spacemacs #10410

As lbensterben said, it occurs when the minibuffer is waiting for input.

This occurs when the minibuffer has focus and another window is selected.

For example when opening an evil search prompt:
```
/                      ;; evil-ex-search-forward
```
and another window is selected:
- `C-x o`
- or by mouse clicking in another window

The most upvoted workaround can be found here:
https://github.com/syl20bnr/spacemacs/issues/10410#issuecomment-391641439

There's a pending PR, upstream:
Exit search prompt on mouse leave minibuffer https://github.com/emacs-evil/evil/pull/1330

But they only solve the issue when another window is selected with the mouse.

**Comment by lebensterben** [comment] 2021-08-20 04:34
closing since it's duplicated.

**Closed by lebensterben** 2021-08-20 04:34 UTC
Labels: Duplicate ☝, Evil, Mini-buffer
