### ISSUE TITLE
Can not use 'C-x C-left' or 'C-x C-right' to back to spacemacs buffer

### ISSUE THREAD

**Issue by was4444** [syl20bnr/spacemacs#7983] opened 2016-12-17 03:45 UTC
Hi,
If I change to a new buffer(e.g. scratch) use `C-x C-right`, then can not back to spacemacs buffer with `C-x C-left`.

spacemacs version: 0.200.5
emacs version: 24.5.1

**Comment by bmag** [comment] 2016-12-17 13:20
Duplicate of #7104. Different command (`alternate-buffer` vs. `previous-buffer`) same reason

**Closed by bmag** 2016-12-17 13:20 UTC
