### ISSUE TITLE
Choosing file to attach in mu4e broken

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#5105] opened 2016-02-17 09:29 UTC
The change <https://github.com/syl20bnr/spacemacs/commit/204b6af424ab84f68327517ae51e67415fb8d242> seems to break attaching files in `mu4e` (`C-c C-a`). When choosing a file to attach the files and folders are listed twice, and completion with TAB is broken.

I'm not even close to understand why this is.

#### Reproduction steps

1. Enter `mu4e`: `SPC a M`
2. Compose a message: `C`
3. Move down to the message and attach a file, `C-c C-a`
4. Try to navigate the helm file chooser

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: nil (rev. 204b6af)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion evil-commentary evil-snipe git gtags mu4e syntax-checking vim-powerline
                 emacs-lisp
                 (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "johan-tibell")
                 scheme dockerfile markdown org pandoc yaml archlinux clipboard-fix)
```

**Comment by cpaulik** [comment] 2016-02-18 15:51
I've seen something similar in `SPC g s` when started outside of a git repo.

**Comment by mskorzhinskiy** [comment] 2016-02-20 11:49
I'm also see this while trying to copy\move file in dired.

**Comment by syl20bnr** [comment] 2016-02-20 13:43
@magthe can you provide a screenshot of the issue ? Did you update your packages before it starts to happen ?

**Comment by mskorzhinskiy** [comment] 2016-02-20 13:53
@syl20bnr 

Fresh install. After reverting that commit everything works fine.

Attaching files
![mml-attach](https://cloud.githubusercontent.com/assets/15213728/13197047/4d5c6d96-d7f2-11e5-854b-f776b06f826c.png)
Magit status
![magit-status](https://cloud.githubusercontent.com/assets/15213728/13197046/4d5c3f7e-d7f2-11e5-851a-156904a214fb.png)
Copy file
![dired-copy](https://cloud.githubusercontent.com/assets/15213728/13197048/4d6fe2fe-d7f2-11e5-9d8a-173aa313f8d4.png)

**Comment by syl20bnr** [comment] 2016-02-20 18:43
Ohh I believe I saw this yesterday at work offer updating my packages, I did not pay attention to much and I don't recall exactly what I was doing. Looks like a regression upstream to me.

**Comment by aminb** [comment] 2016-02-22 20:08
I, too, had the same problem as @cpaulik but I updated my packages today (which include helm and helm-core) and the problem seems to be fixed for me.

**Comment by cpaulik** [comment] 2016-02-22 20:34
Yeah, seems that it was fixed upstream. @magthe Can you confirm?

**Comment by magthe** [comment] 2016-02-23 07:13
@cpaulik Yupp, after updating today the issue is gone :)

**Comment by StreakyCobra** [comment] 2016-02-23 09:02
@magthe If the problem is fixed you may consider closing the issue :relaxed:

**Closed** 2016-02-23 13:05 UTC
Labels: - Bug tracker -, Bug :-(, Email
