### ISSUE TITLE
sudo-edit fails (develop) when emacs daemonized

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#2714] opened 2015-08-21 16:11 UTC
Any idea why tramp is failing with this error message when trying to issue `sudo-edit`, when I'm on nixos-unstable (sudo is configured and working)  with emacs running as a systemd user service (--daemon)?

```sh
Tramp failed to connect. If this happens repeatedly, try `M-x tramp-cleanup-this-connection'
```
No problem to use `sudo-edit` in a regular emacs session.

**Comment by usharf** [comment] 2015-08-21 17:14
Seems to be nix issue with setting the path for this configuration. i.e. some stuff is not on the `exec-path` like `sudo`.

**Comment by StreakyCobra** [comment] 2015-11-11 21:57
The cause of this bug is a duplicate of #2294. I'm closing this one as the other as more information. You can maybe try [the solution proposed in a comment](https://github.com/syl20bnr/spacemacs/issues/2294#issuecomment-131552605).

**Closed by StreakyCobra** 2015-11-11 21:57 UTC
Labels: bug :-(, duplicate (-: :-)
