### ISSUE TITLE
Org capture error void-function org-mks

### ISSUE THREAD

**Issue by emacsLover** [syl20bnr/spacemacs#12829] opened 2019-10-14 08:45 UTC
#### Description :octocat:
org-capture-select-template: Symbol’s function definition is void: org-mks
#### Reproduction guide :beetle:
- Start Emacs
- `Space C c` (org-capture)

*Observed behaviour:* :eyes: :broken_heart:
org-capture-select-template: Symbol’s function definition is void: org-mks

*Expected behaviour:* :heart: :smile:
Can select org-capture template

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spotify
 mermaid
 (elfeed :variables rmh-elfeed-org-files
         (list "~/dotfiles/myinit.org"))
 (geolocation :variables geolocation-enable-weather-forecast t)
 (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
 prodigy pdf-tools
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/mu4e")
 (colors :variables colors-enable-nyan-cat-progress-bar nil)
 finance exwm
 (ranger :variables ranger-show-preview t)
 helm auto-completion better-defaults emacs-lisp git markdown
 (org :variables org-enable-reveal-js-support t)
 (shell :variables shell-default-height 30 shell-default-position 'right)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function org-mks)
  org-mks((("t" "Todo" entry (file+headline "/home/dotfiles/myinit.org" "Tasks") "* TODO %?\n  %i\n  %a") ("j" "Journal Entry" entry (file+olp+datetree "/home/dotfiles/myinit.org") "* %T %?\n%a" :tree-type week)) "Select a capture template\n=========================" "Template key: " (("C" "Customize org-capture-templates") ("q" "Abort")))
  org-capture-select-template(nil)
  org-capture(nil)
  funcall-interactively(org-capture nil)
  call-interactively(org-capture nil nil)
  command-execute(org-capture)
```

**Comment by anbrog** [comment] 2019-11-14 05:19
I have the same issue

**Comment by duianto** [comment] 2019-11-17 10:10
`SPC C c` works for me on the `develop` branch.

But there's a mention of this same error message with a possible workaround, on this page:
https://doubleloop.net/2019/09/09/6081/

>Started getting this error after an upgrade to Emacs 26.2 on Mint:
> org-capture-select-template: Symbol’s function definition is void: org-mks
>
>Doing the same trick as for similar org errors, basically removing compiled org files and recompiling (see doubleloop.net/2019/04/21/5260/), then restarting Emacs, sorted it out.

On the linked page https://doubleloop.net/2019/04/21/5260/ it says:
> Noting for myself, whenever I get an `org-preserve-local-variables` error, this is the way to solve it:
> \# bash
> cd ~/.emacs.d/elpa
> find org*/*.elc -print0 | xargs -0 rm
> 
> (where the elpa directory might be in a different location depending which version/branch you’re on.)
> 
> And then run `M-x spacemacs/recompile-elpa`.
> 
> source: github.com/syl20bnr/spacemacs/issues/11801

The quotes were posted here in case the page ever goes down/disappears.

#### A note about Githubs formatting of urls:
The url on the last line in the quote doesn't show the username.
It also happens when the url is typed outside a quote:
github.com/syl20bnr/spacemacs/issues/11801

The full url looks like this:
`github.com/syl20bnr/spacemacs/issues/11801`

It seems to be caused by the url not having the leading protocol: `https://`
When it's added, then only the issue number is shown (probably as expected):
https://github.com/syl20bnr/spacemacs/issues/11801

**Comment by emacs18** [comment] 2019-12-01 15:12
As I commented in #11801 this issue may also be general package update problem where if old version of a package is already loaded within emacs and a newer version is installed, the byte compiled files may be corrupted due to using old version of some code in generating the byte code for the new version.

**Comment by emacs18** [comment] 2019-12-01 16:40
I figured out how to reproduce the problem as detailed below.
The problem seems to be with emacs 25.2, but not with emacs 26.3.

```
;; This elisp code demonstrates org mode byte code corruption problem reported
;; such as https://github.com/syl20bnr/spacemacs/issues/12829
;; The problem is that we encounter this error:
;;
;;   org-capture-select-template: Symbol’s function definition is void: org-mks
;;
;; To see this problem save the code below to a temporary file say ~/bug.el, then
;; launch emacs 25.2 via this command as I did on ubuntu 18.04:
;;
;;     /usr/bin/emacs -q -l ~/bug.el
;;
;; The error persists even if emacs is restarted.
;;
;; I don't see the problem using emacs 26.3.
;; I see the problem only on emacs 25.2.


;; Load built-in org mode.  Without this step, we don't see the problem.
(load-library "org")

;; Add a package archive that has late org-plus-contrib package.
(custom-set-variables
 `(package-archives
   '(
     ("orgmode" . "http://orgmode.org/elpa/")
     )))

;; Use a temporary directory to install org-plus-contrib package.
(setq package-user-dir (expand-file-name "~/tmplisp"))

(unless (file-directory-p package-user-dir)
  (make-directory package-user-dir))

(package-initialize 'no-activate)
(package-refresh-contents)
(package-install 'org-plus-contrib)

;; This generates org-mks error mentioned before.
(org-capture)

```

**Comment by emacs18** [comment] 2019-12-01 16:48
I quoted an email from emacs-devel list in #11801 

As stated in that email, emacs folks have fixed problems in this byte code corruption area as indicated by the fact that the problem is no longer found on emacs 26.3.

I think this issue should be closed since the root cause is problem within emacs itself and not with spacemacs.  Also the problem seems to have been fixed in newer version of emacs.

**Comment by duianto** [comment] 2019-12-03 18:48
The issue authors system info shows: Emacs: 26.3
But on the Spacemacs `master` branch.

@emacsLover could you test if it also happens for you on the `develop` branch.

Backup your current setup, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

**Comment by emacs18** [comment] 2019-12-03 19:24
The author may  have been using 26.3 at the time of the report.  But was he/she using 26.3 when org package was installed?  I'm guess that an older emacs was used to install org package, then emacs was updated without also wiping out all byte compiled files.

**Comment by duianto** [comment] 2019-12-03 19:30
Good point, that is one possibility. Then let's close this.

It can be reopened if @emacsLover or someone else reports seeing the issue again with a fresh clone and Emacs 26.3.

**Comment by Christophe1997** [comment] 2019-12-09 13:09
This issus occurs on my spacemacs (develop branch) with emacs version 26.1 and org-version 9.1.9, 9.3(I reinstalled the org-mode and recompiled it). 
One thing attract me is that it reported a `Symbol’s function definition is void: org-dynamic-block-define` error during recompiling. So any idea about this problem, I wonder it was caused by the `org-dynamic-block-define`.

**Comment by emacs18** [comment] 2019-12-11 06:39
You ran into the same problem as others. As I explained before, the
problem likely is that old org.el was loaded when you installed new
version of org. If you want to update org, you must find a way to
prevent loading old org files.

**Comment by Christophe1997** [comment] 2019-12-11 07:35
@emacs18 So, where is the old files? Do you mean the `.el` files under the dir `/usr/local/share/emacs`? I have tried to delete all the org related files under the `elpa/develop` and reinstall org-mode.

**Comment by bjonnh** [comment] 2020-01-14 20:03
Still having that problem, tried to delete the elc files and recompile but still the same issue.
I'm getting :
org-capture-select-template: Symbol’s function definition is void: org-mks

when trying to run a capture 

System info:  (bjo-notmuch only contain custom keystrokes)
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bcc3f129)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(markdown helm emacs-lisp org notmuch bjo-notmuch git spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by bjonnh** [comment] 2020-01-14 20:13
What I tried:
- Kill .emacs.d and repull it
- Kill all the .elc files in elpa/develop (and recompiling elpa)
- Kill all the .elc files in .emacs.d  (and recompiling elpa)
- Kill all the .elc and force a full recompilation with (byte-recompile-directory "~/.emacs.d/elpa" 0 t)

**Comment by bjonnh** [comment] 2020-01-14 20:16
Also tried: https://github.com/syl20bnr/spacemacs/issues/11801#issuecomment-564653505  still doesn't work

**Comment by bjonnh** [comment] 2020-01-14 20:56
Finally found the problem. I had a typo in my .spacemacs config that was trying to configure org-babel outside of my user-config function. This made emacs trying to load org-mode before any spacemacs specific layer initialization which made it load the emacs-provided orgmode, not the ELPA one. Can be marked as solved, sorry for the noise.

**Comment by duianto** [comment] 2020-01-14 21:03
Thanks for posting what you've tested, and the cause and solution when you found it. I'm sure it will help others that run into the same problem.

It's not noise, it's a useful data point.

**Closed by duianto** 2020-01-14 21:03 UTC
Labels: - Bug tracker -, Org

**Comment by lorenschwartz** [comment] 2020-05-19 18:01
> Finally found the problem. I had a typo in my .spacemacs config that was trying to configure org-babel outside of my user-config function. This made emacs trying to load org-mode before any spacemacs specific layer initialization which made it load the emacs-provided orgmode, not the ELPA one. Can be marked as solved, sorry for the noise.

This worked for me as well. I moved the org-babel commands from user-init to user-config.
