### ISSUE TITLE
Web mode curly brackets conflict with something

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#4864] opened 2016-01-29 14:31 UTC
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion git ruby-on-rails yaml syntax-checking
                 (ruby :variables ruby-version-manager 'rbenv))
```
#### Reproduction guide
- Open `html` file, make sure you have web mode enabled
- Type `{{ `, pressing space at the end is important.
- Watch how your `{{ ` is turned into `{{ }}}`, but it should be `{{ }}`.

**Comment by StreakyCobra** [comment] 2016-01-29 15:05
I'm pretty sure this has already been reported somewhere, I just have to find it :stuck_out_tongue: . I think I've also seen a PR correcting something like this, not sure it was for this case though.

**Comment by StreakyCobra** [comment] 2016-01-29 15:07
Duplicate of #4499, related PR #4728. Closing as duplicate :-) (let me know if I'm mistaken)

**Closed by StreakyCobra** 2016-01-29 15:07 UTC
