### ISSUE TITLE
Plans to merge `dev` into `master`?

### ISSUE THREAD

**Issue by karansag** [syl20bnr/spacemacs#12418] opened 2019-06-09 18:56 UTC
Are there any plans to merge `dev` into `master`? There are some features I would like that were merged a while back (https://github.com/syl20bnr/spacemacs/pull/9209/commits) into `dev`. It would be nice to stay on `master`, since I'm assuming that is the most stable branch.

**Comment by tuxayo** [comment] 2019-06-09 20:52
Or maybe such a release model doesn't fit anymore and the devel branch should be the recommended one?

**Comment by tuxayo** [comment] 2019-06-09 21:06
Or could there be commits on devel that a posteriori are tagged as stable enough for the most conservative users?

**Comment by tuxayo** [comment] 2019-06-09 21:09
Or could there be a testing channel which would be freezed at a devel commit.
Then if not major regression are found, this commit would be tagged for release in the stable channel. And the testing channel/branch would jump to a newer commit from devel to test it's stability.
While devel would be like today.

I don't know if these ideas are relevant ^^"

**Comment by fiveNinePlusR** [comment] 2019-06-09 21:28
they did recently get a release 

https://github.com/syl20bnr/spacemacs/issues/11741

i believe releases will be more common but in general you can just backup your config/cache and update to whatever commit you'd like to use and it's usually pretty stable. might need to update your packages because spacemacs develop is usually developed for the newer packages.

**Comment by howdoicomputer** [comment] 2019-06-09 23:13
https://github.com/syl20bnr/spacemacs/issues/11741 being closed does not constitute a release. There is no `v0.300` tag or branch. The master branch hasn't seen anything other than a README update in, like, a year. The last Twitter message from the Spacemacs Twitter is from January and there doesn't seem to be any open GitHub issues for discussing cutting a new release.

The `v0.300` [milestone](https://github.com/syl20bnr/spacemacs/milestone/7) was hit but nobody ever drafted a release from it. There is a `v0.301` bug fix milestone that exists despite there not being a `v0.300` release - which is kind of weird. Especially since the description for the `v0.301` milestone is "All issues/PRs assigned to this milestone are for regressions discovered after releasing 0.300.0 that need to be shipped out quickly."

Honestly, it's kind of hard to figure out what is going on. I saw some discussion on setting up [Spacelpa](https://github.com/syl20bnr/spacelpa) and how its progress is a blocker for `0.300` but the last commit for that project was 7 months ago when various packages were added.

There is [this comment](https://github.com/syl20bnr/spacemacs/issues/10438#issuecomment-492662168) by @sdwolfz saying that it's up to @syl20bnr to decide when it's okay to release. That comment was 25 days ago.

The closest thing there is right now, I think, to a `v0.300` release is [this branch](https://github.com/syl20bnr/spacemacs/tree/release_notes_0.300).

Things broke for me last time I tried out `develop` so I usually just back port fixes into my configuration as time goes along.

**Comment by fiveNinePlusR** [comment] 2019-06-09 23:36
I use develop and update every so often and fix the fallout of whatever breaks if anything (last few times were fine) so it's surprising to me that they hit the .3 milestone but haven't done the basic release task. i'd think that you could use the .3 docs branch just fine as it's likely going to be the one that is pinned. 

looks like there's about 26 commits in master that need to be merged with the docs branch. perhaps there was something in there that was not trivial to merge and they haven't had time?

**Comment by howdoicomputer** [comment] 2019-06-10 00:05
Yeah, no idea. I'm just trying to summarize because I was looking for a yasnippets fix that was committed to `develop` last year and found this issue posted at the top. It'd be great if there was a some kind of central location to get information on releases.

Or, like, if two or three people forked this project and continuously cut "good enough" releases from `develop`.

**Comment by dijonkitchen** [comment] 2020-02-07 23:28
Looks like this is holding things up: https://github.com/syl20bnr/spacemacs/issues/12652#issuecomment-544145131

**Comment by zabbal** [comment] 2020-08-13 12:09
Given the amount of changes in Emacs 27.1 it might make sense to make a release before incorporating them.

**Comment by McPhale** [comment] 2021-09-13 16:45
This is still valid.

**Comment by McPhale** [comment] 2022-09-13 23:53
this is still valid lol

**Comment by howdoicomputer** [comment] 2022-09-14 00:59
I haven't used Spacemacs in years but I will say that the reason I stopped
was because there was no stable branch that was up to date enough for the
tooling I used.

It would really be cool if there was a regular release cadence.

Granted, maybe the dev branch has gotten so reliable and well documented
that it *is* the stable branch.

**Comment by lebensterben** [comment] 2022-09-14 01:16
there's no plan to merge dev into master.

I may adopt a fixed release cycle of 6 weeks.

**Comment by dijonkitchen** [comment] 2022-09-14 13:25
This can probably be closed since `develop` is the main branch now. Also related: https://github.com/syl20bnr/spacemacs/issues/11352#issuecomment-1105708486

**Comment by smile13241324** [comment] 2022-09-18 17:49
I really think there is no point in trying to merge dev into master, doing stable releases takes far too much time. Therefore stable is deprecated and develop is the main branch now.

**Closed** 2022-09-18 17:50 UTC
