### ISSUE TITLE
Unable to activate package 'helm-gitignore', required package 'request-0.1.0' is unavailable

### ISSUE THREAD

**Issue by mjm** [syl20bnr/spacemacs#5523] opened 2016-03-17 17:51 UTC
#### Description
Upon updating my packages to get around the issue with smooth-scrolling, my Emacs setup can't finish installing packages because it can't find 'request-0.1.0', which helm-gitignore depends on.

I have two machines that I updated my packages on, running the same version of Emacs. Only one of them is stuck here.

#### Reproduction guide
- Start Emacs
- Let missing packages try to install

*Observed behaviour:*
Eventually:

```
Warning (spacemacs): 
Error connection time out for gnu repository!
Warning (initialization): An error occurred while loading ‘/Users/matt/.emacs.d/init.el’:

error: Unable to activate package ‘helm-gitignore’.
Required package ‘request-0.1.0’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Now this occurs right away upon Emacs startup.

*Expected behaviour:*
All packages install correctly.

#### System Info
- OS: darwin
- Emacs: 25.0.92.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org syntax-checking version-control common-lisp html javascript ruby shell-scripts yaml restclient themes-megapack osx gnus
                 (mu4e :variables mu4e-installation-path "/Volumes/Work/Brew/share/emacs/site-lisp/mu/mu4e"))
```

**Comment by NJBS** [comment] 2016-03-17 17:56
Can you try nuking `emacs.d/elpa` and restarting emacs with the `--insecure` flag?

**Comment by mjm** [comment] 2016-03-17 20:50
This is what happens when I did so. I'm not sure if the --insecure flag is working.

```
Warning (spacemacs): 
Error connection time out for melpa repository!
Warning (spacemacs): 
Error connection time out for gnu repository!
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package ‘color-theme-sanityinc-tomorrow-’ is unavailable))
Warning (initialization): An error occurred while loading ‘/Users/matt/.emacs.d/init.el’:

error: Package ‘evil-’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by mjm** [comment] 2016-03-18 18:17
It almost seems like package names are being truncated in weird ways.

**Comment by syl20bnr** [comment] 2016-03-19 22:36
Try with `dotspacemacs-elpa-https` to `nil` in your dotfile.

**Comment by igagen** [comment] 2016-03-27 01:08
Not sure if this is related, but I just saw a similar error when trying to install Spacemacs on NixOS:

```
Warning (spacemacs):
Error while contacting melpa repository!
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package `spacemacs-theme-' is unavail\
able))
Warning (initialization): An error occurred while loading `/root/.emacs.d/init.el':

error: Package `evil-' is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

**Comment by daniellandau** [comment] 2016-04-01 11:43
For me nuking `.emacs.d/elpa` and restarting Emacs (no `--insecure`) solved this issue.

**Comment by istinspring** [comment] 2016-04-05 17:12
> For me nuking .emacs.d/elpa and restarting Emacs (no --insecure) solved this issue.

not for me, spacemacs initial install done without any problems but when i added some layers...

```
An error occurred while installing company-quickhelp (error: (cl-assertion-failed (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))))
--> installing package: company-statistics@auto-completion... [7/28]
An error occurred while installing company-statistics (error: (cl-assertion-failed (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))))
--> installing package: company-tern@javascript... [8/28]
```

**Comment by Szunti** [comment] 2016-04-17 11:06
This happened to me on emacs 24.5. I think it's because the hack of setting the package location to built-in (https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/packages.el#L51)

The fix was to delete the helm-gitignore package: looks like installing as a dependency works.

To reproduce just delete request package from elpa directory. If not pulled in as dependency it won't install.

**Comment by syl20bnr** [comment] 2016-04-17 13:28
I'm confused about request being marked as built-in, I suppose it has to do with elpa time out tests, I used a local version of request.el but I removed this and used a vanilla Emacs function instead of request.el. I guess we should remove the built-in location now.

Thank you for the finding, PR welcome to fix this.

**Comment by stl-royseto** [comment] 2016-04-28 22:47
I had the same issue @Szunti reported on emacs 24.5.1 and spacemacs 0.105.19. Deleting ~/.emacs.d/elpa/helm-gitignore* and restarting emacs made the issue go away.

**Comment by anmoljagetia** [comment] 2016-07-02 09:38
For me, it doesn't even get to the point where it creates an error in the `.emacs.d/elpa` folder is created. I have no firewall installed, and I can get the `curl -s -I http://melpa.org/packages/archive-contents  ` command to work perfectly fine! 

Any help is greatly appreciated

**Comment by crmne** [comment] 2016-07-08 09:50
setting `dotspacemacs-elpa-https` to `nil` in my dotfile fixed it. nothing else worked

**Comment by d12frosted** [comment] 2016-10-03 08:44
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 08:44 UTC
Labels: - Bug tracker -, Emacs 25.1, Fixed in develop, Update

**Comment by HappyAndHarmless** [comment] 2016-10-31 03:29
I'm using v0.200.4 and still have this problem.

Neither `--insecure` not the `dotspacemacs-elpa-https` trick worked for me. I do not even see a `.emacs.d/elpa` directory being created.

What can I do to help debug this issue? I'm running this on Ubuntu 16.04 under Parallels Desktop in OS X.

**Comment by HappyAndHarmless** [comment] 2016-10-31 04:32
Increasing the value for `dotspacemacs-elpa-timeout` to 60 (in addition to disabling https) fixed it for me.
