### ISSUE TITLE
Spaceline deferred loading broke things? 

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#10849] opened 2018-06-11 10:25 UTC
#### Description :octocat:
Spaceline theme doesn't work with resumed layouts in broke in 4bb1d6ab391c89e772de526e5d4b45d013dc4a74...

#### Reproduction guide :beetle:
- Start Emacs
- Have a few layouts open
- `SPC q r`
- go to the first layout

*Observed behaviour:* :eyes: :broken_heart:
It shows in the Report-Issue buffer fine... but is wonky elsewhere
![image](https://user-images.githubusercontent.com/23088/41226907-ecfeb9d6-6d40-11e8-96f0-837e57d30bd3.png)

*Expected behaviour:* :heart: :smile:
should look the same all over...
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 65018ea)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(coffeescript json bibtex nginx twitter graphviz
              (ivy :variables ivy-enable-advanced-buffer-information t)
              asciidoc speed-reading swift plantuml
              (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
              better-defaults emacs-lisp
              (git :variables git-magit-status-fullscreen t)
              github gnus version-control
              (markdown :variables markdown-live-preview-engine 'vmd)
              syntax-checking
              (latex :variables latex-enable-auto-fill t)
              (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
              docker
              (ansible :variables ansible-auto-encrypt-decrypt t)
              puppet evil-commentary
              (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
              fasd finance floobits xkcd autohotkey csv
              (c-c++ :variables c-c++-enable-clang-support t)
              (clojure :variables clojure-enable-fancify-symbols t)
              major-modes
              (go :variables gofmt-command "goimports" go-use-gometalinter t go-use-gocheck-for-testing t go-use-test-args "-race -timeout 10s" godoc-at-point-function 'godoc-gogetdoc go-tab-width 2)
              (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
              html java
              (javascript :variables javascript-disable-tern-port-files t javascript-backend 'lsp)
              (python :variables python-backend 'lsp python-enable-yapf-format-on-save t python-fill-column 80 python-auto-set-local-pyenv-version 'on-visit python-auto-set-local-pyvenv-virtualenv 'on-visit python-sort-imports-on-save t python-test-runner
                      '(nose pytest))
              lsp racket
              (ruby :variables ruby-version-manager `rvm)
              ruby-on-rails
              (rust :variables rust-enable-rustfmt-on-save t)
              (scala :variables scala-indent:use-javadoc-style t scala-enable-eldoc t scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-start-ensime t)
              shell-scripts
              (restclient :variables restclient-use-org t)
              themes-megapack tmux vim-empty-lines spotify vagrant
              (ibuffer :variables ibuffer-group-buffers-by 'projects)
              semantic deft
              (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
              erc chrome d emoji gtags prodigy evernote
              (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-org-journal-support t org-enable-hugo-support t org-projectile-file "TODOs.org" org-want-todo-bindings t org-enable-bootstrap-support t)
              search-engine yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger wakatime dash spell-checking jabber cscope vinegar rcirc games react php vimscript geolocation idris
              (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
              elixir
              (typography :variables typography-enable-typographic-editing nil)
              pdf imenu-list slack systemd command-log
              (terraform :variables terraform-auto-format-on-save t)
              pass parinfer groovy kotlin unicode-fonts epub
              (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by robbyoconnor** [comment] 2018-06-11 10:32
Yup, I was right...it didn't work well for this...

**Comment by robbyoconnor** [comment] 2018-06-11 12:17
Appears that [86b4e6f...65018ea](https://github.com/syl20bnr/spacemacs/compare/86b4e6f...65018ea) have had some adverse side effects.

**Comment by Compro-Prasad** [comment] 2018-06-11 13:31
I think it should be something specidfic in your config that might cause it or the way you are using Emacs. I couldn't reproduces this eissue.

**Comment by syl20bnr** [comment] 2018-06-11 15:54
I pushed a fix in develop branch, please verify :-)

**Comment by rynffoll** [comment] 2018-06-11 16:53
It didn't help in my case. I reproduced this bug by following steps:
- Start spacemacs without restoring layouts
- `SPC b s`

Also in `*spacemacs*` buffer I can see that [my settings for spaceline](https://github.com/rynffoll/.spacemacs.d/blob/master/layers/rynffoll-ui/packages.el#L6) from my private layout weren't applied.

![image](https://user-images.githubusercontent.com/5983502/41245518-df438536-6db0-11e8-8323-1861c3767277.png)

**Comment by Compro-Prasad** [comment] 2018-06-11 17:09
I got that too ^^. I believe it applies only to the home screen and not to all startup buffers.

**Comment by westlywright** [comment] 2018-06-11 17:13
I was having an issue with the zerodark-theme this morning and its mode line. I rolled back to c12b72 and do not see the issue. @syl20bnr i pulled the latest develop but still saw the issue.

**Comment by Compro-Prasad** [comment] 2018-06-11 17:22
@rynffoll Like?

**Comment by robbyoconnor** [comment] 2018-06-11 18:39
The layouts issue is fixed but I think these lazy loading introduced odd edge cases that need more testing.

**Comment by robbyoconnor** [comment] 2018-06-11 18:39
I'm going to continue working from 86b4e6f76b062cbf921a617cc0eac5d73cb376a4

**Comment by syl20bnr** [comment] 2018-06-11 21:50
> I mean that my spaceline settings don't apply.

Found the issue, opened a PR upstream: https://github.com/TheBB/spaceline/pull/198
Hopefully it will be accepted.

**Comment by BinaryKhaos** [comment] 2018-06-13 13:56
Basically all buffers that are created _before_ spaceline is loaded and configured, will have a messed up powerline. Right now, only most of (not all) the startup buffers are explicitly set to the new modeline config after spaceline is ready but that's about it ("\*Messages\*", "\*spacemacs\*", "\*Compile-Log\*", but not "\*scratch\*" or any file buffer that was opened due to cmdline parameters):

https://github.com/syl20bnr/spacemacs/blob/8754b24509aaf13a6d08be3314280d5f4b5d702d/layers/%2Bspacemacs/spacemacs-modeline/packages.el#L141-L143

One solution would be to extend that to _all_ buffers or simply don't idle load spaceline.

**Comment by robbyoconnor** [comment] 2018-06-14 03:20
Most of this lazy loading are micro-optimizations that don't add much
value but are causing a whole lot of regressions.

**Comment by syl20bnr** [comment] 2018-06-14 05:12
> Basically all buffers that are created before spaceline is loaded and configured, will have a messed up powerline.

Should be fixed in last develop.

**Comment by BinaryKhaos** [comment] 2018-06-14 13:44
> Should be fixed in last develop.

I can confirm it is fixed. Thanks (also for all the hard work and time you are investing into this project -- it is very much appreciated!).

**Comment by syl20bnr** [comment] 2018-06-14 14:10
I pushed a new way to load the spaceline fast enough at startup without lazy-loading it in commit https://github.com/syl20bnr/spacemacs/commit/d7f5b5889

Should close this issue.

**Comment by robbyoconnor** [comment] 2018-06-23 03:51
Should I close this?

**Closed** 2018-06-23 19:38 UTC
Labels: - Bug tracker -, Mode Line, Reported upstream, Spacemacs Layouts
