### ISSUE TITLE
Problem with Splitting Maximized Windows

### ISSUE THREAD

**Issue by sbdchd** [syl20bnr/spacemacs#6887] opened 2016-08-22 00:41 UTC
#### Description :octocat:
Window splitting, with maximized windows, kills the windows that were split before maximizing.

#### Reproduction guide :beetle:
- Start Emacs
- <kbd>SPC w v</kbd> Split current window
- <kbd>SPC w m</kbd> Maximize window
- <kbd> SPC w s</kbd> Split maximized window
- <kbd> SPC w m</kbd> Unmaximize window

*Observed behaviour:* :eyes: :broken_heart:
- initial split window is gone

*Expected behaviour:* :heart: :smile:
- window would unmaximize and split -- like tmux
- no disappearing windows

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.3
- Spacemacs: 0.105.22
- Spacemacs branch: nil (rev. d94d0d9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp extra-langs haskell html java javascript latex lua markdown python sql typescript vimscript yaml
            (go :variables gofmt-command "goimports")
            typography colors osx
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/bash")
            auto-completion spell-checking
            (syntax-checking :variables syntax-checking-use-original-bitmaps t)
            git)
```

Edit: added key presses

**Comment by bmag** [comment] 2016-08-22 05:20
Can you update the recipe with the exact keys to press?

**Comment by duianto** [comment] 2016-08-22 12:33
This might be related.

1. start emacs
2. open the window manipulation transient state popup window `SPC w .`
3. split vertically & follow `S` (press: shift + s)
4. split horizontally `v` 2 times
5. move one of the bottom 3 windows in any direction, ex: left: `H` (press: shift + h)

The moved window ends up on the left side of the frame (as expected), but now there are only 3 windows and the minibuffer shows:
`(wrong-type-argument stringp (nil #<buffer *spacemacs*> #<buffer *spacemacs*>))`

In step 4, if the bottom windows are split 8 times, for a total of 10 windows, then the minibuffer shows:
`(wrong-type-argument stringp (nil #<buffer *spacemacs*> #<buffer *spacemacs*> #<buffer *spacemacs*> #<buffer *spacemacs*> #<buffer *spacemacs*> #<buffer *spacemacs*> #<buffer *spacemacs*> #<buffer *spacemacs*>))`


#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 4071e0c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

I'm unable to reproduce the windows closing when maximizing or unmaximize, i've tried splitting before or after maximizing or unmaximizing, with several splits in between, but the frame keeps the same number of split windows.

Maybe it's a darwin (mac?) issue, it's not happening in windows 10 v1511 b10586.545.

**Comment by duianto** [comment] 2016-08-22 13:28
This probably isn't related, but maybe it's something that could be investigated at the same time as the closing windows issue.

When the emacs window has it's default window size 658x640
and the spacemacs home buffer is open `SPC b h`
open the window manipulation transient state `SPC w .`
split horizontally `v` 8 times

the 8 time the window is split then the minibuffer shows:
`Wrong type argument: wholenump, -1`

and the messages buffer shows:
```
(wrong-type-argument wholenump -1)
vconcat: Wrong type argument: wholenump, -1
```


The message seems to depend on which buffer is open, with the messages buffer open, then the 9th time the window is split, then this message is shown: 
`(error "Size of new window too small (after split)")`
this is probably the correct message to display.

**Comment by sbdchd** [comment] 2016-08-22 23:39
@bmag added key presses

**Comment by bmag** [comment] 2016-08-23 14:15
@sbdchd <kbd>SPC w m</kbd> is bound to `spacemacs/toggle-maximize-buffer`. This key has two use-cases: 1) delete other windows so there's only one buffer visible. 2) focus on one buffer, make changes in the buffer, then return to the earlier state.

Because of the 1st use-case, <kbd>SPC w m</kbd> always treats a split screen as "user wants to maximize current window". We could add a command to be used in the last step instead of <kbd>SPC w m</kbd>:
```elisp
(defun spacemacs/unmaximize-window ()
  "Unmaximize current window state into the previous unmaximized state.
Typically, the previous unmaximized state is the last state that
`spacemacs/toggle-maximize-buffer' maximized."
  (interactive)
  (if (assoc ?_ register-alist)
      (let ((frame-root-state (window-state-get)))
        (jump-to-register ?_)
        ;; `window-state-put' fails if target window is dedicated
        (set-window-dedicated-p nil nil)
        (window-state-put frame-root-state))
    (user-error "Can't unmaximize: no previous unmaximized state.")))
```

I'm curious though, how does the tmux feature work, and does it use the same command to maximize and unmaximize? Do you see this as a real Spacemacs use-case that you're going to use?

**Comment by bmag** [comment] 2016-08-23 14:17
@duianto I can reproduce this on Ubuntu, can you please post it as a new issue? It's not related to @sbdchd's issue.

**Comment by duianto** [comment] 2016-08-23 19:36
@bmag 
Done, it's been reported upstream: 
https://bitbucket.org/lyro/evil/issues/704/moving-a-window-closes-some-windows

**Comment by d12frosted** [comment] 2016-10-11 06:04
Closing this as it was [resolved upstream](https://bitbucket.org/lyro/evil/issues/704/moving-a-window-closes-some-windows).

**Closed by d12frosted** 2016-10-11 06:04 UTC
Labels: - Bug tracker -, Reported upstream
