### ISSUE TITLE
Org-table functions missing

### ISSUE THREAD

**Issue by dustinswan** [syl20bnr/spacemacs#1800] opened 2015-06-01 15:49 UTC
After upgrading to version 0.102.0, I no longer have any org-table functions.

> Symbol's function definition is void: org-table-begin

This stackoverflow could be related? http://stackoverflow.com/questions/23339575/org-mode-from-git-problems-with-tables

**Comment by dustinswan** [comment] 2015-06-01 16:21
I found a solution: add 'org-table' to the org-modules variable.

**Comment by michelk** [comment] 2015-06-02 07:13
I just encountered the same problem; this issue should be reopened.

**Comment by michelk** [comment] 2015-06-02 09:28
Also `org-archive` is affected.

**Comment by TheBB** [comment] 2015-06-02 13:52
Try adding `ox-gfm` to `dotspacemacs-excluded-packages`.

**Comment by dustinswan** [comment] 2015-06-02 14:04
@TheBB that fixes it for me as well.

**Comment by michelk** [comment] 2015-06-02 14:08
Thanks @TheBB. That works.

**Comment by TheBB** [comment] 2015-06-02 14:37
Great! I believe @syl20bnr introduced a fix for this problem in 0.102.1, but I'm still seeing it in the latest version. I know the original report was made for 0.102.0, but maybe you two can confirm or deny whether this is a problem still in the .1 version?

**Comment by dustinswan** [comment] 2015-06-02 14:42
Running 0.102.1 now, still broken if I remove `ox-gfm` from `dotspacemacs-excluded-packages`.

**Comment by TheBB** [comment] 2015-06-02 14:46
Thanks! I see the same.

@syl20bnr I conclude that it's not just me and there's still a genuine bug. :-/

**Comment by syl20bnr** [comment] 2015-06-02 17:30
I looked a bit and the issue is related to the file `org-loaddefs.el` in the install directory of `ox-gfm`. If I remove it then everything works fine. I don't why this file is messing org.

**Comment by syl20bnr** [comment] 2015-06-02 17:43
My theory is that `ox-gfm's org-loaddefs.el` shadows the feature `org-loaddefs`.

**Comment by syl20bnr** [comment] 2015-06-02 21:16
So I asked the package author and the MELPA maintainers with no luck.
https://github.com/larstvei/ox-gfm/issues/4
https://github.com/milkypostman/melpa/issues/2826

I think I will move it to the extensions directory. I'll do it tonight.

**Comment by syl20bnr** [comment] 2015-06-03 02:10
@dustinswan @TheBB Can you try with latest develop without excluding `ox-gfm` ?
Also be sure to set `org-enable-github-support` to `t` in your layer variable: https://github.com/syl20bnr/spacemacs/blob/develop/contrib/org/README.md#github-support

**Comment by TheBB** [comment] 2015-06-03 06:38
It works! :+1:

**Comment by dustinswan** [comment] 2015-06-03 13:53
@syl20bnr Yep, develop works here too. Thanks

**Comment by syl20bnr** [comment] 2015-06-03 15:37
Excellent I will push it to 0.102.2, thank you guys!

**Closed** 2015-06-04 00:29 UTC
Labels: bug :-(, Fixed in `develop`, High Priority, Org

**Comment by conklech** [comment] 2015-06-04 15:27
The problem with `ox-gfm` was also fixed upstream.
