### ISSUE TITLE
ipython is not the default interpreter

### ISSUE THREAD

**Issue by guibor** [syl20bnr/spacemacs#16001] opened 2023-05-02 05:28 UTC
#### Description :octocat:

In README.org, it is indicated that "ipython" is the default interpreter for the python shell: "If ipython is available in system executable search paths, ipython will be used to launch python shell".

When I check the value of `python-shell-interpreter` it is equal to "/opt/homebrew/bin/ipython" and `spacemacs--python-shell-interpreter-origin` is equal to "python3" (`(eval (car (get 'python-shell-interpreter 'standard-value)))` evaluates to "python3").
As a result, ``(or (null python-shell-interpreter)
            (equal python-shell-interpreter spacemacs--python-shell-interpreter-origin))`` is `nil` and the entire environment isn't setup correctly unless I manually set `python-shell-interpreter` to "ipython".

#### Reproduction guide :beetle:
- Start Emacs
- Launch a REPL using `spacemacs/python-start-or-switch-repl`

*Observed behaviour:* :eyes: :broken_heart:
`python3` shell is launched unless `python-shell-interpreter` is manually set to "ipython"

*Expected behaviour:* :heart: :smile:
`ipython` shell starts.

#### System Info :computer:
- OS: darwin
- Emacs: 29.0.90
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6b3d581e5)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: (compleseus csv dap emacs-lisp emoji ess fasd finance git graphviz html imenu-list javascript json latex lsp lua markdown multiple-cursors neotree octave osx outshine org pdf protobuf python ruby rust search-engine semantic shell slack solidity spotify sql toc djvu typescript xkcd yaml treemacs)
- Layers:
```elisp
((java :variables java-backend 'lsp)
 mu4e better-defaults clojure compleseus csv dap emacs-lisp emoji ess fasd finance git graphviz html imenu-list javascript json latex lsp lua markdown multiple-cursors neotree octave osx outshine pdf protobuf python ruby rust search-engine semantic shell slack solidity spotify sql toc typescript xkcd yaml treemacs)
```
- System configuration features: ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM XWIDGETS ZLIB

**Comment by lebensterben** [comment] 2023-05-02 06:47
tagging @sunlin7 since he has recently contributed to python layer.

**Comment by sunlin7** [comment] 2023-05-02 15:15
Hi @guibor 
You mentioned the statement is in the function `spacemacs//python-setup-shell`, which will try to setup the two variables:
`python-shell-interpreter` and `python-shell-interpreter-args`.
If you already got the correct value `python-shell-interpreter` (as your comments, it's "ipython"), the function should skip to change the variables.

**Comment by guibor** [comment] 2023-05-02 15:26
README.org explains that `ipython` is default, when in reality the default is whatever `(eval (car (get 'python-shell-interpreter 'standard-value)))` evaluates to. So either the code is incorrect or the documentation is.

Note that a few commits ago, the logic was as below (which indeed defaults to `ipython`), and this changed for some reason: 

```
(if (spacemacs/pyenv-executable-find "ipython")
      (progn (setq python-shell-interpreter "ipython")
             (if (version< (replace-regexp-in-string "\\(\\.dev\\)?[\r\n|\n]$" "" (shell-command-to-string (format "\"%s\" --version" (string-trim (spacemacs/pyenv-executable-find "ipython"))))) "5")
                 (setq python-shell-interpreter-args "-i")
               (setq python-shell-interpreter-args "--simple-prompt -i")))
    (progn
      (setq python-shell-interpreter-args "-i")
      (setq python-shell-interpreter "python")))
```

**Comment by sunlin7** [comment] 2023-05-02 16:09
The follow commit/conversation has many details for how to determine the python shell interpreter.
https://github.com/syl20bnr/spacemacs/pull/15848

The document says:
> If =ipython= is available in system executable search paths, =ipython=
will be used to launch python shell; otherwise, default =python=
interpreter will be used. You may change your system executable
search path by activating a virtual environment.

For your case, it seems you have local virtual environments ?

**Comment by guibor** [comment] 2023-05-02 21:19
I do not have a local virtual environment.
What do you expect `(eval (car (get 'python-shell-interpreter 'standard-value)))` to evaluate to?

**Comment by sunlin7** [comment] 2023-05-02 23:21
That will give the standard value, which may be different from the customer value.
Your initial comment says 
> python-shell-interpreter it is equal to "/opt/homebrew/bin/ipython" 

That indicate it already get the `ipython`, no need to manually change the value.
Or if the value is manually configured by user, then the `spacemacs//python-setup-shell` won't change anything.

**Comment by guibor** [comment] 2023-05-05 12:37
I did not change the value and it was not manually configured - indeed the the default should be `ipython`.
This was the behavior in previous versions of this layer - but now it defaults to `(eval (car (get 'python-shell-interpreter 'standard-value)))` which is just `python3`.

**Comment by lebensterben** [comment] 2023-05-05 15:42
https://github.com/emacs-mirror/emacs/blob/b28d44d4226497c4b2582bc15a59fc817eb3ce0a/lisp/progmodes/python.el#L2548

standard-value of python-she'll-interpreter will be python3 or python and never ipython.

**Comment by guibor** [comment] 2023-05-06 22:22
But the documentation (`README.org`) says that `ipython` is default.
Furthermore, this was the behavior in the past:

```elisp
(defun spacemacs//python-setup-shell (&rest args)
  (if (spacemacs/pyenv-executable-find "ipython")
      (progn (setq python-shell-interpreter "ipython")
             (if (version< (replace-regexp-in-string "\\(\\.dev\\)?[\r\n|\n]$" "" (shell-command-to-string (format "\"%s\" --version" (string-trim (spacemacs/pyenv-executable-find "ipython"))))) "5")
                 (setq python-shell-interpreter-args "-i")
               (setq python-shell-interpreter-args "--simple-prompt -i")))
    (progn
      (setq python-shell-interpreter-args "-i")
      (setq python-shell-interpreter "python")))) 
```

**Comment by lebensterben** [comment] 2023-05-06 22:24
I am describing a bug. I am not referring to documentation even for once.

**Comment by sunlin7** [comment] 2023-05-07 16:55
Hi @guibor 

Still unable get your key point. 
Do you have any suggestions on code change or document change? Then maybe can help me to understand what's your concern.

The documents said ipython in the path case:
> If =ipython= is available in system executable search paths, =ipython=
will be used to launch python shell; otherwise, default =python=
interpreter will be used. You may change your system executable
search path by activating a virtual environment.

**Comment by cremacs1** [comment] 2023-05-11 21:13
See also #15873. I think my diagnosis is accurate:
> I use conda, but I believe the issue is somewhere in the commit; reverting to `b28d65b7a`, `python-shell-interpreter` becomes "ipython", but using `b28d65b7a` (or `HEAD`), it has the value "python3". I also verified that the same behavior occurs when not using conda (removing the entire anaconda subtree from PATH) and on a fresh install of spacemacs.

**Comment by sunlin7** [comment] 2023-05-11 21:34
trying to reproduce on my local now.

**Comment by sunlin7** [comment] 2023-05-12 00:09
@guibor  please help verify the solution #16011 , thanks

**Comment by guibor** [comment] 2023-05-28 07:29
Thanks this fixes the issue for me!

**Comment by sunlin7** [comment] 2023-05-30 05:09
Thanks, merged.

**Closed as completed** 2023-06-08 12:38 UTC
