### ISSUE TITLE
Improving Performance

### ISSUE THREAD

**Issue by fasddag** [syl20bnr/spacemacs#1114] opened 2015-04-11 21:54 UTC
This must be a common question, but I could not find an answer: how do I improve spacemacs performance?

I suspect I do not need or use most of the functionality, because I do not know about it. 
Things like auto-completion, line-highlight, linum (whatever that is), smooth scrolling, spell check? In fact, I'd give up things that are useful just to speed things up.

Perhaps, someone could share their init file with all the fancy things disabled?

**Comment by trishume** [comment] 2015-04-11 22:00
Spacemacs shouldn't be slow other than maybe startup. If it is slow it is usually one specific laggy thing and not general cruft.

What kind of slowness are you experiencing? When is it happening?

**Comment by syl20bnr** [comment] 2015-04-12 04:07
If you are on `develop`, `auto-completion` is not part of the stock spacemacs, you have to add the layer explicitly  in your dotfile.
For the packages you don't want you can add them to `dotspacemacs-excluded-packages` list and spacemas will ignore them and then uninstall them.

**Comment by CarlQLange** [comment] 2015-04-12 07:10
Also, just to answer your specific question, `linum` is a package that displays the line numbers of the file you're in :)

**Comment by tuhdo** [comment] 2015-04-12 07:24
I wonder what your performance problem is. Could you be more specific?

**Comment by fasddag** [comment] 2015-04-12 11:02
I have a general lag after pretty much any input. Which is particularly noticeable after simple commands, like "j", "k" in normal mode and typing, backspace and ctrl+w in insert mode. 
This is because you expect them to be instant, but they aren't.
Also, this delay builds up. 
So, for example, if I go ctrl+w, ctrl+w... five times it will pause shortly, delete last word, then pause for longer and delete the other four. If I push and hold "j", it will scroll some, then pause and scroll in chunks or not scroll at all if I am in a larger org-mode-file until I release the "j".

**Comment by syl20bnr** [comment] 2015-04-14 01:47
You can disable the mode listed in the mode line with circled letter by pressing on `SPC t <letter>` where letter corresponds to the circled letter. If you disable auto-completion with `SPC t a` is it better ?

**Comment by fasddag** [comment] 2015-04-15 22:53
"spc t a" did not make a noticeable difference. 
Seeing how spacemacs-lite is, apparently, not a thing, am I to close this issue?

ps thanks for your help and spacemacs syl20bnr.

**Comment by jb55** [comment] 2015-04-17 16:34
This is actually a big deal for me as well. I get considerable `hjkl` lag. Any way to profile this? I have all modeline modes disabled.

**Comment by trishume** [comment] 2015-04-17 17:00
System specs might help. OS? Emacs version? Where did you get your emacs? Is your computer old?

Also scope statements and testing might help. Does this happen in multiple types of buffer, or just a certain language? What layers do you have installed?

**Comment by jb55** [comment] 2015-04-17 17:18
* Macbook Pro retina mid 2012
* 2.3 GHz Intel Core i7
* SSD
* Yosemite
* Emacs 24.4.1 (gui mode)

Happens in all buffers, even in fundamental mode. It gets worse over time. When I restart emacs it gets a bit snappier but only for a short while. Killing all buffers doesn't seem to help.

I'm guessing some list is being accumulated and traversed over time and is called on every motion? That's my best guess...

**Comment by tuhdo** [comment] 2015-04-17 17:26
Is the Emacs you are using from Emacs Mac OS X? If so, you should upgrade to Emacs 24.5 since the "stable" version is not so stable. See this issue: https://github.com/syl20bnr/spacemacs/issues/1184

**Comment by jb55** [comment] 2015-04-17 17:30
I'm using the version recommended in the docs: https://github.com/syl20bnr/spacemacs#os-x

**Comment by x-ji** [comment] 2015-06-06 19:53
I wonder whether this has something to do with this issue https://github.com/syl20bnr/spacemacs/issues/1369 The performance issue I experienced was related to a `savehist` variable `kill-ring` and now it has been removed in `develop` branch. Maybe you can give it a try?

**Comment by jasonkuhrt** [comment] 2015-06-11 16:45
I found this issue because I was coming to open a discussion about performance too. General text entry in `spacemacs` is noticeably and quite much slower than e.g. `SublimeText`. Smooth scrolling is way worse, but I would be happy to just get decently performing text entry at least. Text entry in `vim` is also very fast on my machine, its just `emacs` that is quite slow seemingly. I know the next thing to do is display a bunch of stats about my machine and plugins I am using, but I can frankly say that I have done very little to tax what is basically a default spacemacs install on a solid machine (same as @jb55 basically). In other words, it doesn't seem to be easy to just fall into the pit of performance by default. Users need to "think" about it?

More generally my concern is whether `emacs` is just generally never going to match `vim` et al in editing performance. I couldn't care less about startup time for now.

**Comment by rphillips** [comment] 2015-06-11 17:03
Make sure your `Key Repeat` and `Delay Until Repeat` are customized to your liking within the `"System Preferences" -> "Keyboard"` preferences. `Delay Until Repeat` should probably be `short`. There still might be something wrong with Emacs, but this global improvement should be double checked.

**Comment by tuhdo** [comment] 2015-06-11 17:11
How slow is slow? I opened a 300MB text file fine in `fundamental-mode`. For programming modes, even files with 10-20k lines are non-issue.

**Comment by jasonkuhrt** [comment] 2015-06-11 17:13
@tuhdo These are hard discussions to have accurately. For a quick and dirty test can you open that same file in SublimeText and tell me if you can observe a improve or not? Large or not?

**Comment by tuhdo** [comment] 2015-06-11 17:14
If you want to open large file, be sure to disable smooth scrolling. It improves performance quite significant.

**Comment by jasonkuhrt** [comment] 2015-06-11 17:16
@rphillips I updated that setting though not related to the performance I am talking about. `hjkl` navigation and so on is simply not on par with raw `vim`.

**Comment by jasonkuhrt** [comment] 2015-06-11 17:16
> disable smooth scrolling

How?

**Comment by x-ji** [comment] 2015-06-11 17:16
I'd say text entry is indeed considerably slower than in `Vim` especially in modes such as `orgmode`, though it occurs in all major modes. But the cursor movement speed was quite OK and not that far away from `Vim` when I set both `Key Repeat` and `Delay Until Repeat` to their respective maximum values. Not sure if there's some configuration issue.

**Comment by tuhdo** [comment] 2015-06-11 17:18
I have no problem with Emacs. It scrolls fast, even with that 300MB text file. If you want a prorgramming file to test, `SPC h L` then open `vhdl-mode.el.gz`. It's 17k elisp lines and I can press `C-v` repeatedly to continuously scroll. 

My OS is Ubuntu on a 5400 rpm hard drive with a 5 years-old Windows.



> How?

Set `dotspacemacs-smooth-scrolling` to `nil` in your `.spacemacs`.

**Comment by rphillips** [comment] 2015-06-11 17:24
I did see something like this awhile ago, and IIRC installing aspell from homebrew cleared it up for me.

**Comment by syl20bnr** [comment] 2015-06-11 17:36
@jasonkuhrt What theme are you using ? On XQuartz on Yosemite I have poor performance in some themes like zenburn and some others, the display is slower in every way with these themes, I don't know why.

Also what build and version of Emacs are your using ? I was impressed by emacs-mac-port from homebrew which far more responsive than the stock brew Emacs build under XQuartz.

**Comment by syl20bnr** [comment] 2015-06-11 17:37
@jasonkuhrt also do you have any similar issue with `emacs -nw` ?

**Comment by x-ji** [comment] 2015-06-11 18:16
@syl20bnr indeed `emacs-mac-port` seems to perform much better. Text entry speed is quite OK now. Maybe worth mentioning this in the README file or documentation? Otherwise sometimes people like me might get confused and thought the performance issue stems from Spacemacs while it seems that the real problem lies with the Emacs build we chose.

**Comment by trishume** [comment] 2015-06-11 18:21
@x-ji good point about giving a reason. The real reason though is not just performance, it is better in every conceivable way. Better rendering, better perf, better OSX integration, better scrolling, better stability, ...

**Comment by jasonkuhrt** [comment] 2015-06-11 18:26
@syl20bnr `emacs-mac`? 

```
❯ brew search emacs
emacs					      emacs-mac
emacs-clang-complete-async		      railwaycat/emacsmacport/emacs-mac
Caskroom/cask/emacs
```

**Comment by syl20bnr** [comment] 2015-06-11 18:27
@jasonkuhrt Indeed `emacs-mac` sorry, it has support for spacemacs icon, be sure to check the available options :-) (there is a PR running to add this to the README).

**Comment by jasonkuhrt** [comment] 2015-06-11 18:51
@syl20bnr Themese I have are:

```
   dotspacemacs-themes '(sanityinc-tomorrow-blue
                         tronesque
                         fogus
			 gruvbox
			 sanityinc-tomorrow-blue
                         django
                         dakron
                         busybee
                         hickey
                         dorsey
                         clues
                         hc-zenburn
                         )
```

I installed `emacs-mac` but so far no super-obvious improvement. I'll see how it goes though. I also set     `dotspacemacs-smooth-scrolling nil` but no major difference so far (actually scrolling appears the same too).

**Comment by syl20bnr** [comment] 2015-06-11 18:59
@jasonkuhrt 
> I installed emacs-mac but so far no super-obvious improvement

Then there is definitely something different in your setup that makes it abnormally slow. Maybe try without a `.spacemacs` so you can remove from the equation your settings.

**Comment by x-ji** [comment] 2015-06-11 19:08
@jasonkuhrt Also might try to inspect your `.emacs.d` folder and even nuking it after making a backup... I was given a lot of headache by one rogue cache file in `.cache` subfolder which got super large. I remember other people also having similar issues.

**Comment by trishume** [comment] 2015-06-12 13:22
Something else people might want to check out on this thread is your file system. At work I've been using Spacemacs on things served over NFS and all sorts of things, even ones that I wouldn't expect to use the file system, are WAY slower. At times it can't even keep up with my typing speed, I have no idea why. I have no problems on fast local files.

**Comment by mathpunk** [comment] 2015-07-02 20:54
Now that my main org file is decently sized, I'm having performance issues as well. I used `M-x profiler-start`, typed a bit, and opened the profiler-report. I saw that a big hunk of CPU was being used like this:

- command-execute                                               16540  50%
 - call-interactively                                           16540  50%
  - byte-code                                                   13336  40%
   + evil-operator-range                                         9048  27%
   + helm-M-x-read-extended-command                              4288  13%

...and I could expand further. I don't know what to do with this information in order to improve performance.

**Comment by jasoncyu** [comment] 2015-07-02 22:59
i've experienced the same thing as you @trishume w/ vagrant NFS. it's most noticeable when i try to use magit

**Comment by catesandrew** [comment] 2015-07-31 01:21
i was having issues with tramp-mode. turned out to be an issue with projectile. I used a defadvice posted in one of the threads and it seemed to help a lot. try disabling projectile and flycheck to see if that helps any before investigating any further with the issues on projectile project.

**Comment by stormpat** [comment] 2015-08-28 11:15
Just to put my two cents in, i have noticed Spacemacs being (sometimes/rarely), quite slow, and laggy but its always hard/impossible to pinpoint the issue. Usually this is the case when having to work with a large file (> 300 lines)

I have narrowed it down to the font and theme. So anyone having similar issues try to change your font, and theme, my problems are gone with Fira Mono (DejaVu Sans was slow) and im using some of the soft-* themes, theres dark and light ones available.

And for ultimate speed, turn off font-lock-mode.

**Comment by laohyx** [comment] 2015-09-01 13:25
+1, @stormpat 
The fonts slow my emacs! When I change the font to `Fira Mono`, it works well. And then I tried many fonts, such as `Courier New`, `Menlo`, `Monaco` and `Microsoft Yahei`, all of them goes slow.

Maybe some modes or the emacs itself are incompatible with some fonts?
It also explains why the `spacemacs` is not laggy in CLI mode, no fonts at all!

**Comment by laohyx** [comment] 2015-09-01 13:29
BTW, here is my environment:
* Macbook Pro retina mid 2012 (same with @jb55 )
* 2.6 GHz Intel Core i7
* SSD
* OS X 10.11 El capitan
* Emacs 24.5 (homebrew, railwaycat/emacsmacport)

If anyone feels slow in a brand new `spacemacs` under OS X, try to change the font to `Fira Mono`.

**Comment by jasonkuhrt** [comment] 2015-09-01 13:43
I think continuous benchmarking would be awesome but of course a non-trivial task.

For example on every commit a battery of tests would run such that:
- Various combinations of layers would be enabled / disabled
- Various tasks would be conducted:
  - Boot time
  - Open small file for each language
  - Open large file for each language
  - cursor movement speed
  - other latency metrics? Search / Replace etc.

With a report for each git commit on the project it would be practical to track regressions and discover issues. I'm handwaving obviously, the task is comparable to testing every aspect of a a webapp in every device etc. but Something minimal might be practical which would be better than nothing.

For now I'm unsubscribing from this thread as anecdotes mostly make for chasing phantoms. Cheers.

**Comment by synic** [comment] 2015-09-01 14:03
I tried "Fira Mono" as @laohyx suggested.  It is much faster.   Windows redraw faster (when using golden-ratio), etc.  With Fira Mono, all window operations appear to happen instantly, while with "Hack" or "Deja Vu Sans Mono" or "Sourcecode Pro", there is a delay.

**Comment by Devagamster** [comment] 2015-09-01 14:58
@synic That is wacky. Seems to make an improvement on Windows as well. Its hard to tell if its just me perceiving differences though. It also might be that the Fira Mono font is taller making less lines appear on the screen. Not sure.

**Comment by myrjola** [comment] 2015-09-01 15:31
I can confirm that changing the font to "Fira Mono" worked for me too. I'm using a Macbook. Changing themes didn't improve performance perceptibly for me.

I'm also using the [emacs-mac-port](https://github.com/railwaycat/emacs-mac-port) with smooth scrolling. The scrolling is not yet buttery smooth. But much nicer on the eye after I changed the font. Happiness can come from small things.

Performance regression testing suggested in https://github.com/syl20bnr/spacemacs/issues/1114#issuecomment-136726651 would be very nice, but I don't think it's possible to implement in our current testing infrastructure. See https://github.com/travis-ci/travis-ci/issues/352.

**Comment by swaroopch** [comment] 2015-09-02 04:02
Wow, indeed, switching to Fira Mono makes Spacemacs go faster. On a MacBook Pro.

**Comment by TheBB** [comment] 2015-09-02 08:25
Is Fira Mono distributed in a different format than SCP?

**Comment by synic** [comment] 2015-09-03 01:36
I am also on a macbook pro, fwiw.  Using the recommended emacs build.

**Comment by x-ji** [comment] 2015-09-03 04:56
I didn't see perceivable difference? How did you install Fira Mono font? It seems that it has various distribution formats at https://github.com/mozilla/Fira and I installed the `otf` format.

**Comment by laohyx** [comment] 2015-09-03 17:17
Hi, here is the latest progress about font slow problem.
Setting `dotspacemacs-mode-line-unicode-symbols` to `nil` may solve the problem. 

Here is the reason.
We found that changing default font to `Fira Mono` fixes the delay. But have you installed the font `Fira Mono`? At least I haven't.
If you haven't either, we could discuss the root cause.

But why changing to a non-existed font could solve the delay? In fact, my power line cannot display the powerline's unicode symbols.
So I speculate that drawing unicode symbols make the emacs slow. When I specify the font as `Fira Mono`, which doesn't exist, emacs will fall back to `Monaco`, in which there is no unicode symbols.

<img width="411" alt="1" src="https://cloud.githubusercontent.com/assets/1221508/9665393/95e4a810-52a2-11e5-8e41-45a90a1ce3b9.png">


Then I disabled `dotspacemacs-mode-line-unicode-symbols` according to [the document](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#powerline-separators), making no unicode symbols displayed, and it works. 

So the root cause is that drawing powerline's unicode symbols slows emacs in OS X. Please have a try, and disable `dotspacemacs-mode-line-unicode-symbols` with any fonts.

@synic @TheBB @swaroopch @myrjola

**Comment by x-ji** [comment] 2015-09-03 17:34
@laohyx OK so I have always been using `vim-powerline` which does not have unicode symbols displayed at all. Maybe that's why I didn't feel any difference. I doubt whether all the other people didn't even install Fira Mono when they specified it as the font though.

**Comment by swaroopch** [comment] 2015-09-04 06:43
@laohyx I have Fira Mono installed and I do have Unicode symbols displayed, and Spacemacs *is* faster for me than the default Spacemacs font.

<img width="441" alt="screen shot 2015-09-03 at 11 43 09 pm" src="https://cloud.githubusercontent.com/assets/42988/9678021/8ecdf6ce-5295-11e5-8aad-892b0a45da7d.png">

**Comment by synic** [comment] 2015-09-04 13:22
Yes, I also installed the font.

**Comment by syl20bnr** [comment] 2015-09-04 13:42
Which format of the font have you installed ?
Do you think we should switch the default font in Spacemacs ?

**Comment by syl20bnr** [comment] 2015-09-04 13:46
@laohyx unicode symbols use fallback fonts so I'm suprised that changing the main prevents the unicode characters from being displayed properly.

**Comment by synic** [comment] 2015-09-04 13:48
I installed the ttf from the mozilla: https://github.com/mozilla/Fira/tree/master/ttf

I think it's worth looking into a font that is faster, but not Fira Mono :)

**Comment by syl20bnr** [comment] 2015-09-04 14:04
@synic I agree.
If you guys find a popular fastest font we can consider to change Source Code Pro.
I wonder if the number of supported glyphs could slow Emacs.

**Comment by xxv** [comment] 2015-09-04 14:40
Just to confirm, `nil`ing `dotspacemacs-mode-line-unicode-symbols` caused notable lag to go away on my configuration.

In particular, the lag was present when the whole screen would scroll (not just moving the cursor). And to be very specific about the lag, I mean: I would hold down `j` or `k` for 1s and release it: the cursor would keep moving (upwards of a couple seconds) and the scroll animation would be choppy while it moved. Now, if I release the key, it only continues scrolling for a fraction of the time it did previously.

This is Debian stretch/sid, running `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.4)
 of 2015-06-28 on trouble, modified by Debian`. I'm running awesomewm and don't have Fira Mono. The fallback font is DejaVu Sans Book. I do have SourceCodePro and a couple Powerline fonts installed, though.

**Comment by xxv** [comment] 2015-09-04 14:51
This bug report, [Font-related window redrawing delays on OS X](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19266), may have some more interesting hints at a solution.

**Comment by laohyx** [comment] 2015-09-04 15:51
@xxv , letting `dotspacemacs-mode-line-unicode-symbols ` be `t` causes the notable lag.

I installed `Fira Mono` in `ttf` format, and the delay is notably decreased, but still a slightly lag comparing to no unicode symbols.

Indeed `Fira Mono` is much faster than `Source Code pro` on Mac OS X. But the unicode symbols still slows emacs. You can paste these symbols into a buffer, and you will see that moving cursor is very slow, even with `Fira Mono`.

```
ⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐ
ⓒⓒⓒⓒⓒⓒⓒⓒⓒⓒ
ⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻ
```

So that is a bug of emacs as @xxv  said.

**Comment by kendall** [comment] 2015-09-04 16:04
I can’t tell any perf diff on OSX between Fira Mono and Source Code Pro FYI.
Cheers, Kendall

On Fri, Sep 4, 2015 at 11:51 AM, laohyx < notifications@github.com > wrote:
@xxv , letting dotspacemacs-mode-line- unicode-symbols be t causes the notable lag.

I installed Fira Mono in ttf format, and the delay is notably decreased, but still a slightly lag comparing
to no unicode symbols.

Indeed Fira Mono is much faster than Source Code pro on Mac OS X. But the unicode symbols still slows emacs. You can paste these
symbols into a buffer, and you will see that moving cursor is very slow, even
with Fira Mono .

ⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐⓐ
ⓒⓒⓒⓒⓒⓒⓒⓒⓒⓒ
ⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻⒻ


So that is a bug of emacs as @xxv said.

**Comment by d12frosted** [comment] 2015-09-04 16:34
Oh man. Setting `dotspacemacs-mode-line-unicode-symbols` to `nil` is like... well, riding rocket after using bicycle.

**Comment by mbertheau** [comment] 2015-09-04 18:47
Just as a data point, `dotspacemacs-mode-line-unicode-symbols` makes no noticeable difference in speed on Ubuntu 14.04, and with the ⓐⓒⒻ characters in a buffer the point moves as fast as ever.

**Comment by laohyx** [comment] 2015-09-20 12:10
Well, maybe the font issue is more complex than I thought. Many causes may make emacs slow.

On my computer, the unicode symbols slows emacs. After disabling `dotspacemacs-mode-line-unicode-symbols `, it works.

Then I upgrade my MAC OS X to El capitan `GM edition`, unicode symbols don't lag emacs any more.
Maybe the El capitan Beta indeed have something wrong in unicode rendering.

My spacemacs runs soooooo fast, thank you all.

**Comment by d12frosted** [comment] 2015-09-20 12:40
I'am experiencing problems even on `10.10.5 (14F27)`.

**Comment by jetaggart** [comment] 2015-09-29 16:48
FWIW, @rphillips recommended install aspell which seemed to fix the issue with me. Mac OS X, development branch.

**Comment by jetaggart** [comment] 2015-09-29 22:27
Nevermind, it's still slow :/ This is especially noticeable when editing ruby code.

**Comment by d12frosted** [comment] 2015-10-05 13:48
I found that `GNU Emacs 25.0.50.1` is much faster than `emacs-mac`. A lot of operations are much smoother in one very huge project I am using for testing purposes.

**Comment by TheBB** [comment] 2015-10-28 15:19
Closing this now since this discussion has simmered down and it's really too general. You can open new issues for more specific performance problems if you find them.

**Closed by TheBB** 2015-10-28 15:19 UTC
Labels: Fonts, question

**Comment by Clamwinds** [comment] 2016-01-12 01:50
Changing the font from sans-mono to the fira-mono font fixed all my lag problems. It has something to do  with that I guess.

Remember to restart spacemacs as well.

**Comment by kostajh** [comment] 2016-03-20 18:16
Just came across this myself. Fira Mono + disabling unicode made a massive difference. Should we perhaps mention this in the docstring in `init.el` so that it's easier to get this info in front of users?

**Comment by stormpat** [comment] 2016-03-21 05:47
To reiterate on this, i have been using GNU Emacs 25 (head) on OSX, and the speed is much better than in the emacs-mac port. I suggest trying it out if someone has any perf problems with Spacemacs.

Also, i have the latest OSX version and im not sure if the font is still an issue. I have been using CamingoCode and M+ fonts they all work as they should. Not sure about Source Code Pro though.

**Comment by kzjeef** [comment] 2016-04-20 09:14
Just my two cents, 

I found If I change the powerline-scale to 1.0 (maybe means don't do any scale in dotspacemacs/init will improve a lot of scrolling speed.

seems the 1.1 scale is copy from default config.

like

```
   dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight normal
                               :width normal
                               :powerline-scale 1.0)

```

**Comment by sam217pa** [comment] 2016-04-27 11:55
I can also confirm that deactivating linum-mode for every programming  mode : 
`  (add-hook 'prog-mode-hook
            (lambda ()
              (spacemacs/toggle-line-numbers-off)
`
and / or deactivating smooth-scrolling increased speed a great deal. I did not change anything else.

**Comment by epogue** [comment] 2016-04-28 16:06
@d12frosted Thank you for pointing out that `GNU Emacs 25` is faster! Just switched from `emacs-mac` and it's night and day.

**Comment by rdlugosz** [comment] 2016-05-16 16:31
FWIW, I've seen a similar issue in Vim when using unicode characters and different fonts. I believe the issue is related to whether or not a particular glyph is available in the currently-configured font. If it is, there's no speed impact. If it isn't, OS X does _something_ to locate a fallback font and this process (or possibly the process of drawing the fallback) is slow. See [my comment here](https://github.com/tpope/vim-sensible/issues/57#issuecomment-21043434) for further details.

**Comment by vladh** [comment] 2016-05-28 20:51
I can confirm that changing `powerline-scale` to `1.0` and switching to Emacs 25 led to a visible reduction of lag. It's still there, but not so bad. Strangely, switching to Fira Mono from Monaco didn't really do anything for me.

**Comment by nwaywood** [comment] 2016-06-06 00:58
I have tried:

- `Fira Mono` font
- `:powerline-scale 1.0`
- GNU Emacs 25
- `dotspacemacs-mode-line-unicode-symbols` to `nil`

and I still have horrible lag on my MBP :( Even entering numbers into the calculator there is about a 1 second delay.

**Comment by voeler** [comment] 2016-08-05 13:14
I had major input lag for pretty much anything in Spacemacs. After trying many things I simply started disbling minor modes until I found out **flycheck** caused the slowness on my Windows installation. Hope this helps anyone.

**Comment by mrkgnao** [comment] 2016-10-13 04:45
I had an almost unusable spacemacs for a while after opening ~10 buffers, although it would be really snappy right after startup with only one or two buffers open. This was enough of a problem that I contemplated switching to, and even spent a few hours building a config for, neovim.
It turns out killing `linum-mode` works the necessary magic and I don't have to go anywhere :)

Does anyone have any insight into why this happens?

**Comment by daviswahl** [comment] 2016-11-12 06:25
The issue for me was with `pbcopy`. I believe it only occurs when you run emacs within a terminal, there's less of an issue when running from within the full application. 

Simply toggling off `pbcopy` fixed my performance issues.

**Comment by mrkgnao** [comment] 2016-11-12 10:56
For me, it was `linum-mode`. Not using that has given me stable performance improvements, to the point where I don't have any palpable lag.

**Comment by djm** [comment] 2016-12-09 12:08
Just as another point, my lag has gone after disabling `dotspacemacs-mode-line-unicode-symbols`. The font in question was Operator Mono.

**Comment by gitfoxi** [comment] 2017-03-14 01:08
I've been reading mail using the mu4e layer and I notice some messages are very slow to load.

Before reading this thread I didn't notice what the slow messages have is common: Chinese characters.

I wish there was a way to just turn off the unicode rendering since I don't speak Chinese I won't miss much. Of course it would be better if the rendering could be fast.
