### ISSUE TITLE
Adding Julia Layer to .spacemacs raises error

### ISSUE THREAD

**Issue by danmrc** [syl20bnr/spacemacs#16032] opened 2023-05-31 04:25 UTC
Issue: adding Julia to `dotspacemacs-configuration-layers` raises an error `Symbol’s function definition is void: configuration-layer/layer-used-p`

In fact, the whole layer has disappeared from the layers list on the website, so I am not sure of what is going on. 

I am using archlinux, emacs 28.2.2 and the latest spacemacs

Thanks

**Comment by alexey0308** [comment] 2023-06-05 22:20
> In fact, the whole layer has disappeared from the layers list on the website, so I am not sure of what is going on.

The Julia layer documentation is accessible [here](https://develop.spacemacs.org/layers/+lang/julia/README.html) at the develop branch.

**Comment by danmrc** [comment] 2023-06-05 22:41
Ok, my error was relying on the bookmarked spacemacs website, which was not the develop.spacemacs. So that is completely on me.

I will check if installing spacemacs using the link on that website solves the problem. This might take a while, since that computer is under repair. I am pretty sure I tried cloning the repo and that didn't work either, but I want to be 100% sure about that (and that will allow me to copy the whole message error)

**Comment by smile13241324** [comment] 2023-06-08 09:01
Take your time :), I am just installing the julia layer and it looks to be ok on develop.

**Comment by smile13241324** [comment] 2023-06-11 13:19
Now that I have (mostly) recovered from the first major step of physical transitioning, I would like to clean up our issue list a bit first before I jump back into coding. Therefore I would prefer to close this ticket for now, @danmrc feel free to reopen it when the issue is confirmed.

**Closed as completed by smile13241324** 2023-06-11 13:19 UTC

**Comment by danmrc** [comment] 2023-06-20 18:42
Downloaded the latest version from github and using emacs 28.2-2 from pacman and I don´t have any issue. So, whatever it was, was due to using the spacemacs website instead of the github version. 

If there was an issue, there isn´t one anymore.
