### ISSUE TITLE
Emacs becomes unresponsive when attempting to save to file the Default layout

### ISSUE THREAD

**Issue by al3xandru** [syl20bnr/spacemacs#5449] opened 2016-03-11 09:44 UTC
#### Description

Emacs becomes unresponsive when attempting to save the _Default_ layout set up in a project folder with 3 windows and 3 buffers.
#### Reproduction guide
1. Start Emacs
2. New frame (`make-frame-command`)
3. Open file (`helm-find-files` in a .git project)
4. Create 3 windows (sequence: `spc w v`, `spc w l`, `spc w s`)
5. Open files from project in the 3 windows
6. Save layouts by name (`spc l S`)
7. Select _Default_

_Observed behaviour:_

After step 6, a new prompt is displayed and Emacs becomes unresponsive. Force quitting is the only way to get out.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(eyebrowse themes-megapack theming dash search-engine git
           (auto-completion :variables auto-completion-enable-snippets-in-popup t)
           semantic
           (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
           asciidoc c-c   csharp emacs-lisp go html java javascript markdown org php python ruby scala shell-scripts swift yaml evil-commentary evil-snipe imenu-list)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by al3xandru** [comment] 2016-03-11 09:48
1. Doing the same sequence with a new layout leads to the same result. 
2. All packages are up to date.

**Comment by StreakyCobra** [comment] 2016-03-11 09:52
Have you tried selecting `[>done<]` in the prompt once the layout you wanted to save has been selected the first time?

**Comment by al3xandru** [comment] 2016-03-11 10:01
That's the point, attempting to select `[>done<]`, where Emacs becomes unresponsive.

**Comment by StreakyCobra** [comment] 2016-03-11 10:11
Ok weird, I can't reproduce on `develop` right now, it works as expected.

**Comment by d12frosted** [comment] 2016-10-30 10:47
This should be already fixed. Closing issue. let me know if it's relevant for you.

**Closed by d12frosted** 2016-10-30 10:47 UTC
Labels: - Bug tracker -, Spacemacs Layouts, To be reproduced, Unresponsive
