### ISSUE TITLE
Warning errors after a fresh reinstall on MacOs

### ISSUE THREAD

**Issue by oliverhr** [syl20bnr/spacemacs#14379] opened 2021-02-13 22:09 UTC
Warning errors even after a fresh reinstall on MacOs

I get this error after select "Update Spacemacs", I tried removing 

```
~/.spacemacs
~/.spacemacs.env
~/.emacs.d

/Applications/Emacs.app/
```

Note: I'm a complete newbie to emacs and spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- Update spacemacs
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
After the reinstall, this error is being displayed
```
Warning (evil-collection): `evil-want-keybinding' was set to nil but not before loading evil.

Make sure to set `evil-want-keybinding' to nil before loading evil or evil-collection.

See https://github.com/emacs-evil/evil-collection/issues/60 for more details.
Error (use-package): window-purpose/:config: Symbol’s value as variable is void: magit-display-buffer-function
```

This warning persists after restart
```
Error (use-package): window-purpose/:config: Symbol’s value as variable is void: magit-display-buffer-function
```

*Expected behaviour:* :heart: :smile:
Normal start without warnings

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b93bdbd4a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER

**Comment by TinyStego** [comment] 2021-02-13 23:23
I'm having this same issue. Fresh install on Manjaro Linux. I have emacs 27.1 installed and cloning the develop branch to ~/.emacs.d. Currently trying to track down the source of the issue, but I'm new to emacs and it's hard to navigate the debugger.

I tried removing the source-control layer and removed 'use-package' from .spacemacs to try to prevent it from using it, but the issue still occurs.

It seems like the issue is stemming from magit, wonder if the package itself is broken.

**Comment by jethrosun** [comment] 2021-02-14 03:44
Same here, I am using Arch Linux

**Comment by emacs18** [comment] 2021-02-14 17:25
This was fixed upstream few hours ago.  The author stated few minutes ago that he was waiting for MELPA to rebuild.

In the mean time af0d0e72763c6b441087dfdb96b65020c3c4365 was checked in 9 hours ago.  This change should not be necessary once MELPA rebuild is done of window-purpose package.

**Comment by emacs18** [comment] 2021-02-14 17:27
https://github.com/bmag/emacs-purpose/commit/cb61b9381ef9865e725c4641588d7b8945d35003 is the upstream fix.

**Comment by oliverhr** [comment] 2021-02-15 14:38
I can confirm, by updating the packages the warning is gone.

**Comment by oliverhr** [comment] 2021-02-15 14:38
I can confirm, by updating the packages the warning is gone.

**Closed** 2021-02-15 14:38 UTC
