### ISSUE TITLE
Spacemacs error on startup after upgrading emacs-mac to 5.10

### ISSUE THREAD

**Issue by MerelyAPseudonym** [syl20bnr/spacemacs#2765] opened 2015-08-26 16:48 UTC
Ever since upgrading to emacs-24.5-mac-5.10 ([there was a new release recently](https://github.com/railwaycat/homebrew-emacsmacport/commit/9f1e9cf6b470ca71d2ef940c8ffadb85f1605a3c)) I've been seeing the following error:

```
An error occurred while initializing emacs-builtin-emacs-lisp (error: (error Key sequence m e $ starts with non-prefix key m e))
```

This occurs on both the `master` and `develop` branches on fresh installs.

On the `develop` branch, I can get more information by passing the `--debug-init` option. Here's the associated backtrace:
```
Debugger entered--Lisp error: (error "Key sequence m e $ starts with non-prefix key m e")
  define-key((keymap (109 keymap (121 . evil-lisp-state-sp-copy-sexp) (87 . evil-lisp-state-sp-unwrap-sexp) (119 . evil-lisp-state-wrap) (22 . evil-lisp-state-evil-visual-block) (86 . evil-lisp-state-evil-visual-line) (118 . evil-lisp-state-evil-visual-char) (18 . evil-lisp-state-undo-tree-redo) (85 . evil-lisp-state-sp-backward-up-sexp) (117 . evil-lisp-state-undo-tree-undo) (116 . evil-lisp-state-sp-transpose-sexp) (83 . evil-lisp-state-sp-backward-slurp-sexp) (114 . evil-lisp-state-sp-raise-sexp) (80 . evil-lisp-state-evil-paste-before) (112 . evil-lisp-state-evil-paste-after) (76 . evil-lisp-state-sp-forward-sexp) (108 . evil-lisp-state-forward-symbol) (107 . evil-lisp-state-prev-opening-paren) (74 . evil-lisp-state-sp-join-sexp) (106 . evil-lisp-state-next-closing-paren) (73 . evil-lisp-state-evil-insert-line) (105 . evil-lisp-state-evil-insert-state) (72 . evil-lisp-state-sp-backward-sexp) (69 . evil-lisp-state-sp-splice-sexp-killing-backward) (101 . evil-lisp-state-sp-splice-sexp-killing-forward) (68 keymap (120 . evil-lisp-state-sp-backward-kill-sexp) (119 . evil-lisp-state-sp-backward-kill-word) (115 . evil-lisp-state-sp-backward-kill-symbol)) (100 keymap (109 . spacemacs/macrostep-micro-state) (120 . evil-lisp-state-sp-kill-sexp) (119 . evil-lisp-state-sp-kill-word) (115 . evil-lisp-state-sp-kill-symbol)) (99 . evil-lisp-state-sp-convolute-sexp) (66 . evil-lisp-state-sp-backward-barf-sexp) (98 . evil-lisp-state-sp-forward-barf-sexp) (97 . evil-lisp-state-sp-absorb-sexp) (57 . evil-lisp-state-digit-argument) (56 . evil-lisp-state-digit-argument) (55 . evil-lisp-state-digit-argument) (54 . evil-lisp-state-digit-argument) (53 . evil-lisp-state-digit-argument) (52 . evil-lisp-state-digit-argument) (51 . evil-lisp-state-digit-argument) (50 . evil-lisp-state-digit-argument) (49 . evil-lisp-state-digit-argument) (48 . evil-lisp-state-beginning-of-sexp) (96 keymap (116 . evil-lisp-state-sp-transpose-hybrid-sexp) (115 . evil-lisp-state-sp-slurp-hybrid-sexp) (112 . evil-lisp-state-sp-push-hybrid-sexp) (107 . evil-lisp-state-sp-kill-hybrid-sexp)) (36 . evil-lisp-state-sp-end-of-sexp) (41 . evil-lisp-state-insert-sexp-after) (40 . evil-lisp-state-insert-sexp-before) (58 . evil-lisp-state-evil-ex) (37 . evil-lisp-state-evil-jump-item) (104 . evil-lisp-state-sp-backward-symbol) (103 keymap (103 . elisp-slime-nav-find-elisp-thing-at-point)) ...) keymap (57 . select-window-9) (56 . select-window-8) (55 . select-window-7) (54 . select-window-6) (53 . select-window-5) (52 . select-window-4) (51 . select-window-3) (50 . select-window-2) (49 . select-window-1) (48 . select-window-0) (82 . group:pcre2el) (63 . helm-descbinds) (47 . spacemacs/helm-project-smart-do-search-region-or-symbol) (f1 . helm-apropos) (118 . er/expand-region) (59 . evilnc-comment-operator) (108 . avy-goto-line) (32 . avy-goto-word-or-subword-1) (83 keymap (110 . flyspell-goto-next-error) (100 . ispell-change-dictionary)) (74 . sp-split-sexp) (9 . spacemacs/alternate-buffer) (33 . shell-command) (117 . universal-argument) (122 . group:zoom) (120 . group:text) (119 . group:windows) (84 . group:toggles/themes) (116 . group:toggles) (115 . group:search/symbol) (114 . group:registers/rings) (113 . group:quit) (112 . group:projects) (110 . group:narrow/numbers) (107 . group:lisp) (106 . group:join/split) (105 . group:insertion) (104 . group:helm/help/highlight) (103 . group:git/versions-control) (102 . group:files) (69 . group:editing-modes) (101 . group:errors) (67 . group:capture/colors) (99 . group:compile/comments) (98 . group:buffers) (97 . group:applications)) "me$" lisp-state-eval-sexp-end-of-line)
  evil-leader--def-keys((keymap (109 keymap (121 . evil-lisp-state-sp-copy-sexp) (87 . evil-lisp-state-sp-unwrap-sexp) (119 . evil-lisp-state-wrap) (22 . evil-lisp-state-evil-visual-block) (86 . evil-lisp-state-evil-visual-line) (118 . evil-lisp-state-evil-visual-char) (18 . evil-lisp-state-undo-tree-redo) (85 . evil-lisp-state-sp-backward-up-sexp) (117 . evil-lisp-state-undo-tree-undo) (116 . evil-lisp-state-sp-transpose-sexp) (83 . evil-lisp-state-sp-backward-slurp-sexp) (114 . evil-lisp-state-sp-raise-sexp) (80 . evil-lisp-state-evil-paste-before) (112 . evil-lisp-state-evil-paste-after) (76 . evil-lisp-state-sp-forward-sexp) (108 . evil-lisp-state-forward-symbol) (107 . evil-lisp-state-prev-opening-paren) (74 . evil-lisp-state-sp-join-sexp) (106 . evil-lisp-state-next-closing-paren) (73 . evil-lisp-state-evil-insert-line) (105 . evil-lisp-state-evil-insert-state) (72 . evil-lisp-state-sp-backward-sexp) (69 . evil-lisp-state-sp-splice-sexp-killing-backward) (101 . evil-lisp-state-sp-splice-sexp-killing-forward) (68 keymap (120 . evil-lisp-state-sp-backward-kill-sexp) (119 . evil-lisp-state-sp-backward-kill-word) (115 . evil-lisp-state-sp-backward-kill-symbol)) (100 keymap (109 . spacemacs/macrostep-micro-state) (120 . evil-lisp-state-sp-kill-sexp) (119 . evil-lisp-state-sp-kill-word) (115 . evil-lisp-state-sp-kill-symbol)) (99 . evil-lisp-state-sp-convolute-sexp) (66 . evil-lisp-state-sp-backward-barf-sexp) (98 . evil-lisp-state-sp-forward-barf-sexp) (97 . evil-lisp-state-sp-absorb-sexp) (57 . evil-lisp-state-digit-argument) (56 . evil-lisp-state-digit-argument) (55 . evil-lisp-state-digit-argument) (54 . evil-lisp-state-digit-argument) (53 . evil-lisp-state-digit-argument) (52 . evil-lisp-state-digit-argument) (51 . evil-lisp-state-digit-argument) (50 . evil-lisp-state-digit-argument) (49 . evil-lisp-state-digit-argument) (48 . evil-lisp-state-beginning-of-sexp) (96 keymap (116 . evil-lisp-state-sp-transpose-hybrid-sexp) (115 . evil-lisp-state-sp-slurp-hybrid-sexp) (112 . evil-lisp-state-sp-push-hybrid-sexp) (107 . evil-lisp-state-sp-kill-hybrid-sexp)) (36 . evil-lisp-state-sp-end-of-sexp) (41 . evil-lisp-state-insert-sexp-after) (40 . evil-lisp-state-insert-sexp-before) (58 . evil-lisp-state-evil-ex) (37 . evil-lisp-state-evil-jump-item) (104 . evil-lisp-state-sp-backward-symbol) (103 keymap (103 . elisp-slime-nav-find-elisp-thing-at-point)) ...) keymap (57 . select-window-9) (56 . select-window-8) (55 . select-window-7) (54 . select-window-6) (53 . select-window-5) (52 . select-window-4) (51 . select-window-3) (50 . select-window-2) (49 . select-window-1) (48 . select-window-0) (82 . group:pcre2el) (63 . helm-descbinds) (47 . spacemacs/helm-project-smart-do-search-region-or-symbol) (f1 . helm-apropos) (118 . er/expand-region) (59 . evilnc-comment-operator) (108 . avy-goto-line) (32 . avy-goto-word-or-subword-1) (83 keymap (110 . flyspell-goto-next-error) (100 . ispell-change-dictionary)) (74 . sp-split-sexp) (9 . spacemacs/alternate-buffer) (33 . shell-command) (117 . universal-argument) (122 . group:zoom) (120 . group:text) (119 . group:windows) (84 . group:toggles/themes) (116 . group:toggles) (115 . group:search/symbol) (114 . group:registers/rings) (113 . group:quit) (112 . group:projects) (110 . group:narrow/numbers) (107 . group:lisp) (106 . group:join/split) (105 . group:insertion) (104 . group:helm/help/highlight) (103 . group:git/versions-control) (102 . group:files) (69 . group:editing-modes) (101 . group:errors) (67 . group:capture/colors) (99 . group:compile/comments) (98 . group:buffers) (97 . group:applications)) "me$" lisp-state-eval-sexp-end-of-line ("meb" eval-buffer "mec" spacemacs/eval-current-form "mee" eval-last-sexp "mer" eval-region "mef" eval-defun "mel" lisp-state-eval-sexp-end-of-line "m," lisp-state-toggle-lisp-state "mtb" spacemacs/ert-run-tests-buffer "mtq" ert))
  evil-leader/set-key-for-mode(emacs-lisp-mode "me$" lisp-state-eval-sexp-end-of-line "meb" eval-buffer "mec" spacemacs/eval-current-form "mee" eval-last-sexp "mer" eval-region "mef" eval-defun "mel" lisp-state-eval-sexp-end-of-line "m," lisp-state-toggle-lisp-state "mtb" spacemacs/ert-run-tests-buffer "mtq" ert)
  emacs-lisp/init-emacs-builtin-emacs-lisp()
  funcall(emacs-lisp/init-emacs-builtin-emacs-lisp)
  (let ((owner (eieio-oref pkg (quote :owner)))) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))))
  (let ((pkg-name (eieio-oref pkg (quote :name)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append (format ... pkg-name layer err)))))) (eieio-oref pkg (quote :pre-layers))) (let ((owner (eieio-oref pkg (quote :owner)))) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name)))) (mapc (function (lambda (layer) (spacemacs-buffer/message (format "  -> post-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/post-init-%S" layer pkg-name))) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append (format ... pkg-name layer err)))))) (eieio-oref pkg (quote :post-layers))))
  configuration-layer//configure-package([object cfgl-package "emacs-builtin-emacs-lisp" emacs-builtin-emacs-lisp emacs-lisp nil nil local post nil])
  (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) ((eq (quote local) (eieio-oref pkg (quote :location))) (let* ((owner (object-assoc (eieio-oref pkg (quote :owner)) :name configuration-layer--layers)) (dir (eieio-oref owner (quote :dir)))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)) (setq load-path (cons (format "%sextensions/%S/" dir pkg-name) load-path))) (configuration-layer//configure-package pkg)) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))
  (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) ((eq (quote local) (eieio-oref pkg (quote :location))) (let* ((owner (object-assoc (eieio-oref pkg ...) :name configuration-layer--layers)) (dir (eieio-oref owner (quote :dir)))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)) (setq load-path (cons (format "%sextensions/%S/" dir pkg-name) load-path))) (configuration-layer//configure-package pkg)) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg))))
  (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) ((eq (quote local) (eieio-oref pkg (quote :location))) (let* ((owner (object-assoc ... :name configuration-layer--layers)) (dir (eieio-oref owner ...))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)) (setq load-path (cons (format "%sextensions/%S/" dir pkg-name) load-path))) (configuration-layer//configure-package pkg)) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg) (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) ((eq (quote local) (eieio-oref pkg (quote :location))) (let* ((owner ...) (dir ...)) (setq load-path (cons ... load-path)) (setq load-path (cons ... load-path))) (configuration-layer//configure-package pkg)) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2(([object cfgl-package "emacs-builtin-emacs-lisp" emacs-builtin-emacs-lisp emacs-lisp nil nil local post nil]))
  configuration-layer//configure-packages(([object cfgl-package "ace-link" ace-link spacemacs nil nil elpa nil nil] [object cfgl-package "ace-window" ace-window spacemacs nil nil elpa nil nil] [object cfgl-package "adaptive-wrap" adaptive-wrap spacemacs nil nil elpa nil nil] [object cfgl-package "aggressive-indent" aggressive-indent spacemacs nil nil elpa nil nil] [object cfgl-package "auto-dictionary" auto-dictionary spacemacs nil nil elpa nil nil] [object cfgl-package "auto-highlight-symbol" auto-highlight-symbol spacemacs nil nil elpa nil nil] [object cfgl-package "avy" avy spacemacs nil nil elpa nil nil] [object cfgl-package "bind-key" bind-key spacemacs nil nil elpa nil nil] [object cfgl-package "bookmark" bookmark spacemacs nil nil elpa nil nil] [object cfgl-package "buffer-move" buffer-move spacemacs nil nil elpa nil nil] [object cfgl-package "centered-cursor" centered-cursor spacemacs nil nil local nil nil] [object cfgl-package "clean-aindent-mode" clean-aindent-mode spacemacs nil nil elpa nil nil] [object cfgl-package "company" company nil nil (emacs-lisp) elpa nil nil] [object cfgl-package "define-word" define-word spacemacs nil nil elpa nil nil] [object cfgl-package "desktop" desktop spacemacs nil nil elpa nil nil] [object cfgl-package "diff-hl" diff-hl version-control nil nil elpa nil nil] [object cfgl-package "diff-mode" diff-mode version-control nil nil elpa nil nil] [object cfgl-package "diminish" diminish spacemacs nil nil elpa nil nil] [object cfgl-package "doc-view" doc-view spacemacs nil nil elpa nil nil] [object cfgl-package "ediff" ediff spacemacs nil nil elpa nil nil] [object cfgl-package "eldoc" eldoc spacemacs nil (emacs-lisp) elpa nil nil] [object cfgl-package "elisp-slime-nav" elisp-slime-nav emacs-lisp nil nil elpa nil nil] [object cfgl-package "emacs-builtin-emacs-lisp" emacs-builtin-emacs-lisp emacs-lisp nil nil local post nil] [object cfgl-package "emacs-builtin-process-menu" emacs-builtin-process-menu spacemacs nil nil local nil nil] [object cfgl-package "eval-sexp-fu" eval-sexp-fu spacemacs nil nil elpa nil nil] [object cfgl-package "evil" evil spacemacs nil (emacs-lisp) elpa nil nil] [object cfgl-package "evil-anzu" evil-anzu spacemacs nil nil elpa nil nil] [object cfgl-package "evil-args" evil-args spacemacs nil nil elpa nil nil] [object cfgl-package "evil-escape" evil-escape spacemacs nil nil elpa nil nil] [object cfgl-package "evil-exchange" evil-exchange spacemacs nil nil elpa nil nil] [object cfgl-package "evil-iedit-state" evil-iedit-state spacemacs nil nil elpa nil nil] [object cfgl-package "evil-indent-textobject" evil-indent-textobject spacemacs nil nil (recipe :fetcher github :repo "TheBB/evil-indent-textobject") nil nil] [object cfgl-package "evil-jumper" evil-jumper spacemacs nil nil elpa nil nil] [object cfgl-package "evil-leader" evil-leader spacemacs nil nil elpa nil nil] [object cfgl-package "evil-lisp-state" evil-lisp-state spacemacs nil nil elpa nil nil] [object cfgl-package "evil-matchit" evil-matchit spacemacs nil nil elpa nil nil] [object cfgl-package "evil-nerd-commenter" evil-nerd-commenter spacemacs nil nil elpa nil nil] [object cfgl-package "evil-numbers" evil-numbers spacemacs nil nil elpa nil nil] [object cfgl-package "evil-search-highlight-persist" evil-search-highlight-persist spacemacs nil nil elpa nil nil] [object cfgl-package "evil-surround" evil-surround spacemacs nil nil elpa nil nil] [object cfgl-package "evil-terminal-cursor-changer" evil-terminal-cursor-changer spacemacs nil nil elpa nil nil] [object cfgl-package "evil-tutor" evil-tutor spacemacs nil nil elpa nil nil] [object cfgl-package "evil-visualstar" evil-visualstar spacemacs nil nil elpa nil nil] [object cfgl-package "exec-path-from-shell" exec-path-from-shell spacemacs nil nil elpa nil nil] [object cfgl-package "expand-region" expand-region spacemacs nil nil elpa nil nil] [object cfgl-package "fancy-battery" fancy-battery spacemacs nil nil elpa nil nil] [object cfgl-package "fill-column-indicator" fill-column-indicator spacemacs nil nil elpa nil nil] [object cfgl-package "flx-ido" flx-ido spacemacs nil nil elpa nil nil] [object cfgl-package "flycheck" flycheck nil nil (emacs-lisp) elpa nil nil] [object cfgl-package "fringe-helper" fringe-helper spacemacs nil nil elpa nil nil] ...))
  configuration-layer//load-packages(([object cfgl-package "ace-link" ace-link spacemacs nil nil elpa nil nil] [object cfgl-package "ace-window" ace-window spacemacs nil nil elpa nil nil] [object cfgl-package "adaptive-wrap" adaptive-wrap spacemacs nil nil elpa nil nil] [object cfgl-package "aggressive-indent" aggressive-indent spacemacs nil nil elpa nil nil] [object cfgl-package "auto-dictionary" auto-dictionary spacemacs nil nil elpa nil nil] [object cfgl-package "auto-highlight-symbol" auto-highlight-symbol spacemacs nil nil elpa nil nil] [object cfgl-package "avy" avy spacemacs nil nil elpa nil nil] [object cfgl-package "bind-key" bind-key spacemacs nil nil elpa nil nil] [object cfgl-package "bookmark" bookmark spacemacs nil nil elpa nil nil] [object cfgl-package "buffer-move" buffer-move spacemacs nil nil elpa nil nil] [object cfgl-package "centered-cursor" centered-cursor spacemacs nil nil local nil nil] [object cfgl-package "clean-aindent-mode" clean-aindent-mode spacemacs nil nil elpa nil nil] [object cfgl-package "company" company nil nil (emacs-lisp) elpa nil nil] [object cfgl-package "define-word" define-word spacemacs nil nil elpa nil nil] [object cfgl-package "desktop" desktop spacemacs nil nil elpa nil nil] [object cfgl-package "diff-hl" diff-hl version-control nil nil elpa nil nil] [object cfgl-package "diff-mode" diff-mode version-control nil nil elpa nil nil] [object cfgl-package "diminish" diminish spacemacs nil nil elpa nil nil] [object cfgl-package "doc-view" doc-view spacemacs nil nil elpa nil nil] [object cfgl-package "ediff" ediff spacemacs nil nil elpa nil nil] [object cfgl-package "eldoc" eldoc spacemacs nil (emacs-lisp) elpa nil nil] [object cfgl-package "elisp-slime-nav" elisp-slime-nav emacs-lisp nil nil elpa nil nil] [object cfgl-package "emacs-builtin-emacs-lisp" emacs-builtin-emacs-lisp emacs-lisp nil nil local post nil] [object cfgl-package "emacs-builtin-process-menu" emacs-builtin-process-menu spacemacs nil nil local nil nil] [object cfgl-package "eval-sexp-fu" eval-sexp-fu spacemacs nil nil elpa nil nil] [object cfgl-package "evil" evil spacemacs nil (emacs-lisp) elpa nil nil] [object cfgl-package "evil-anzu" evil-anzu spacemacs nil nil elpa nil nil] [object cfgl-package "evil-args" evil-args spacemacs nil nil elpa nil nil] [object cfgl-package "evil-escape" evil-escape spacemacs nil nil elpa nil nil] [object cfgl-package "evil-exchange" evil-exchange spacemacs nil nil elpa nil nil] [object cfgl-package "evil-iedit-state" evil-iedit-state spacemacs nil nil elpa nil nil] [object cfgl-package "evil-indent-textobject" evil-indent-textobject spacemacs nil nil (recipe :fetcher github :repo "TheBB/evil-indent-textobject") nil nil] [object cfgl-package "evil-jumper" evil-jumper spacemacs nil nil elpa nil nil] [object cfgl-package "evil-leader" evil-leader spacemacs nil nil elpa nil nil] [object cfgl-package "evil-lisp-state" evil-lisp-state spacemacs nil nil elpa nil nil] [object cfgl-package "evil-matchit" evil-matchit spacemacs nil nil elpa nil nil] [object cfgl-package "evil-nerd-commenter" evil-nerd-commenter spacemacs nil nil elpa nil nil] [object cfgl-package "evil-numbers" evil-numbers spacemacs nil nil elpa nil nil] [object cfgl-package "evil-search-highlight-persist" evil-search-highlight-persist spacemacs nil nil elpa nil nil] [object cfgl-package "evil-surround" evil-surround spacemacs nil nil elpa nil nil] [object cfgl-package "evil-terminal-cursor-changer" evil-terminal-cursor-changer spacemacs nil nil elpa nil nil] [object cfgl-package "evil-tutor" evil-tutor spacemacs nil nil elpa nil nil] [object cfgl-package "evil-visualstar" evil-visualstar spacemacs nil nil elpa nil nil] [object cfgl-package "exec-path-from-shell" exec-path-from-shell spacemacs nil nil elpa nil nil] [object cfgl-package "expand-region" expand-region spacemacs nil nil elpa nil nil] [object cfgl-package "fancy-battery" fancy-battery spacemacs nil nil elpa nil nil] [object cfgl-package "fill-column-indicator" fill-column-indicator spacemacs nil nil elpa nil nil] [object cfgl-package "flx-ido" flx-ido spacemacs nil nil elpa nil nil] [object cfgl-package "flycheck" flycheck nil nil (emacs-lisp) elpa nil nil] [object cfgl-package "fringe-helper" fringe-helper spacemacs nil nil elpa nil nil] ...))
  configuration-layer/sync()
  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-startup-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start)))
  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-startup-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start))))
  eval-buffer(#<buffer  *load*> nil "/Users/josh/.emacs.d/init.el" nil t)  ; Reading at buffer position 998
  load-with-code-conversion("/Users/josh/.emacs.d/init.el" "/Users/josh/.emacs.d/init.el" t t)
  load("/Users/josh/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

**Comment by justbur** [comment] 2015-08-26 17:10
I'm guessing that somewhere you have `SPC m e` bound to a command. It's trying to assign a command to `SPC m e $` but it's reporting that `SPC m e` is not a prefix, meaning it's been assigned already.

**Comment by justbur** [comment] 2015-08-26 17:10
You could try `SPC h d k SPC m e` and see if it gives you something.

**Comment by MerelyAPseudonym** [comment] 2015-08-26 17:21
@justbur <kbd>SPC h d k SPC m</kbd> (i.e., without the final <kbd>e</kbd>) tells me that <kbd>SPC m</kbd> isn't bound to anything, which seems really weird.

**Comment by MerelyAPseudonym** [comment] 2015-08-26 17:24
# The emacs-mac version may be a red herring!
Reverting to emacs-24.5-mac-5.9 doesn't make the error message go away, and neither did downgrading to version 5.8.

**Comment by justbur** [comment] 2015-08-26 17:24
sorry, you need to be in emacs-lisp-mode to check this

**Comment by justbur** [comment] 2015-08-26 17:25
Yeah I didn't think it had anything to do with that

**Comment by syl20bnr** [comment] 2015-08-26 17:36
Flagging it as not a bug for now, it seems to be a user configuration error.

**Comment by MerelyAPseudonym** [comment] 2015-08-26 18:53
@justbur In `emacs-lisp-mode`, <kbd>SPC m e</kbd> is bound to `evil-lisp-state-sp-splice-sexp-killing-forward`.

@syl20bnr I had thought that I was getting these errors in a fresh sandbox, but I just realized that I *did* have some packages installed from [homebrew-emacs](https://github.com/homebrew/homebrew-emacs)...

**Comment by justbur** [comment] 2015-08-26 18:57
@syl20bnr this might be a bug since evil-lisp-state is part of default
spacemacs, right?

**Comment by MerelyAPseudonym** [comment] 2015-08-26 19:07
N.B. The problem does *not* show up if I use the Emacs from <http://emacsformacosx.com/>. I believe that's because the version of Emacs from there *isn't* specially configured to use `/usr/local/share/emacs/site-lisp/**`.

**Comment by justbur** [comment] 2015-08-26 19:12
My guess is that it has to do with whether spacemacs tries to add `SPC m e $` before or after evil-lisp-state.el is loaded.

**Comment by MerelyAPseudonym** [comment] 2015-08-26 19:13
`brew uninstall homebrew/emacs/use-package` makes the error go away. (the `use-package` formula is from [this PR](https://github.com/Homebrew/homebrew-emacs/pull/13/files#diff-ad58fa0d6336f32dc79dfc88ffb1d6b8))

Sorry for the false alarm everybody =)

@syl20bnr feel free to close this issue—the only reason *I'm* not is so that you get a chance to see what the resolution was in case a similar problem shows up in the future.

**Comment by syl20bnr** [comment] 2015-08-26 19:15
That's a weird bug... but glad that you found how to fix it.

**Comment by syl20bnr** [comment] 2015-08-26 19:17
I close it then, thank you.

**Closed by syl20bnr** 2015-08-26 19:17 UTC
Labels: bug :-(, User Configuration
