### ISSUE TITLE
Cannot create a frame with `emacsclient`.

### ISSUE THREAD

**Issue by kindaro** [syl20bnr/spacemacs#14991] opened 2021-08-15 08:37 UTC
#### Description :octocat:

`emacsclient --create-frame` dies with `*ERROR*: Attempt to set a constant symbol: nil` when Emacs server is run as a daemon.

Note that it works fine if either:

* `emacsclient` is run without `--create-frame`, in which case it opens a text based user interface in the terminal.
* Emacs is run as `emacs` with `.spacemacs` augmented with `(defun dotspacemacs/user-config () … (server-start) …)` _(running both a server and a graphical frame)_.

The problem only appears when Emacs is started without a frame and then `emacsclient` is instructed to create a frame.

#### Reproduction guide :beetle:
- Start Emacs in daemon mode: `emacs --daemon`.
- Run `emacsclient --create-frame /tmp/example`.

*Observed behaviour:* :eyes: :broken_heart:

    % emacsclient --create-frame /tmp/example
    Waiting for Emacs...
    *ERROR*: Attempt to set a constant symbol: nil

*Expected behaviour:* :heart: :smile:

A new frame opens, editing the specified file.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9bb3115bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust idris
      (typescript :variables typescript-backend 'tide)
      react web-beautify javascript sql purescript yaml python ocaml
      (haskell :variables haskell-enable-ghc-mod-support nil)
      (keyboard-layout :variables kl-layout 'bepo)
      coq
      (erc :variables erc-server-list
           '(("irc.freenode.net" :port "6697" :ssl t :nick "kindaro")))
      cmake lsp gpu
      (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow)
      helm html auto-completion emacs-lisp markdown syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment] 2021-08-15 17:49
Closing since this is not a bug.

You need -a=ALTERNATIVE when you use emacsclient -c

See https://www.emacswiki.org/emacs/EmacsClient#h5o-4

**Closed by lebensterben** 2021-08-15 17:49 UTC
Labels: Not a bug 8-)

**Comment by kindaro** [comment] 2021-08-15 19:14
You are wrong, please reopen.

* Supplying this option does not solve it.
* Removing Spacemacs configuration _(the entire `~/.emacs.d`)_ solves it.

Therefore I still believe that this is a bug somewhere in Spacemacs.

**Comment by lebensterben** [comment] 2021-08-15 20:24
Paste the exact command and output.

**Comment by kindaro** [comment] 2021-08-16 09:52
Sure.

```
% emacsclient --create-frame --alternate-editor "" /tmp/example
Waiting for Emacs...
*ERROR*: Attempt to set a constant symbol: nil
% emacsclient --create-frame -a "" /tmp/example
Waiting for Emacs...
*ERROR*: Attempt to set a constant symbol: nil
% emacsclient --create-frame --alternate-editor "chromium" /tmp/example
Waiting for Emacs...
*ERROR*: Attempt to set a constant symbol: nil
% emacsclient --create-frame -a "chromium" /tmp/example
Waiting for Emacs...
*ERROR*: Attempt to set a constant symbol: nil
% which chromium
/usr/bin/chromium
```

As I said above, removing the `~/.emacs.d` solves the issue. And there is nothing there but Spacemacs.

```
% (cd ~/.emacs.d && git remote -v && git status)
origin	https://github.com/syl20bnr/spacemacs (fetch)
origin	https://github.com/syl20bnr/spacemacs (push)
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
```

Anything else you would like me to try?

I am currently bisecting the difference between my `~/.spacemacs` and the default one generated by `dotspacemacs/install`. My configuration is a few years old and there are many differences. Maybe the fault is therein.

**Comment by kindaro** [comment] 2021-08-16 10:20
Alright, I found it.

```
(defun dotspacemacs/emacs-custom-settings ()
  "Emacs custom settings.
This is an auto-generated function, do not modify its content directly, use
Emacs customize menu instead.
This function is called at the very end of Spacemacs initialization."
(custom-set-variables
 …
 '(nil nil t)
 …
 )
```

Removing `'(nil nil t)` obviates the issue.

How did this line even get there?

However, this is still a fault of Spacemacs. The correct behaviour is to issue a warning and continue, which is what it does when I start it in any other way.

**Comment by lebensterben** [comment] 2021-08-16 16:38
Two things,

First you have to have -a unless you're sure the Emacs daemon is running. Supplying an empty optarg to -a is simply wrong. You'd use something like `emacsclient -c -a=emacs".

Second,
> However, this is still a fault of Spacemacs. The correct behaviour is to issue a warning and continue, which is what it does when I start it in any other way.

Stop being rediculous. The warning occurs in the daemon so you didn't see it.
