### ISSUE TITLE
binding of <C-i> disappear

### ISSUE THREAD

**Issue by XiaoLiuAI** [syl20bnr/spacemacs#5050] opened 2016-02-13 03:53 UTC
Hello, 

I am new to spacemacs. In the latest version 0.105.9, I found that the keybinding ```<C-i>``` is undefined even after changing the variable ```dotspacemacs-distinguish-gui-tab``` to ```t``` and restarting emacs. I studied from spacemacs tips that this keybinding should be associated to ```evil-jump-forword```. I checked the difference between this version and version 0.105.6 and found following codes
``` Lisp
       ;; Move keybindings into global motion state map
       (add-hook 'evil-jumper-mode-hook
                 (lambda ()
                   (if evil-jumper-mode
                       (progn
                         (define-key evil-motion-state-map (kbd "TAB") 'evil-jumper/forward)
                         (define-key evil-motion-state-map (kbd "<C-i>") 'evil-jumper/forward)
                         (define-key evil-motion-state-map (kbd "C-o") 'evil-jumper/backward))
                     (define-key evil-motion-state-map (kbd "TAB") 'evil-jump-forward)
                     (define-key evil-motion-state-map (kbd "<C-i>") 'evil-jump-forward)
                     (define-key evil-motion-state-map (kbd "C-o") 'evil-jump-backward))))
       (evil-jumper-mode t)
       (setcdr evil-jumper-mode-map nil))))
```
are replaced by 
``` Lisp
       (evil-jumper-mode t))))
```

However, the keybinding ```<C-o>``` works correctly. Could you please check it?

Thank you in advance for your help.

**Comment by StreakyCobra** [comment] 2016-02-13 18:52
@XiaoLiuAI Can you try to update your packages («Update packages» on Spacemacs buffer)? And also to remove `evil-snipe` from you layer list if you have enabled it? If this still doesn't work after this, can you update your issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)

**Comment by XiaoLiuAI** [comment] 2016-02-14 00:10
I tried to update the packages following the =Update Packages= link, but the problem still occurs. I don't have any configuration about evil-snipe in my dot file.

## Current configuration
I am running emacs under OS X Yosemite. I downloaded this git repository and created a symbolic link to it under my home folder to let the spacemacs active. 
I have following configurations in ```user-config```:
```elisp
  (setq dotspacemacs-enable-golden-ratio t)
  (setq powerline-default-separator 'bar)
  (setq dotspacemacs-enable-paste-micro-state t)
  (setq-default dotspacemacs-smartparens-strict-mode t)
  (setq paradox-github-token "*******")
```
I also activated these layers:
```
     auto-completion
     better-defaults
     git
     markdown
     org
     spell-checking
     eyebrowse
     ess
     python
     c-c++
     octave
     scala
     shell
```
In ```dotspacemacs/init```, I made following modification:
```elisp
   dotspacemacs-editing-style 'hybrid
   dotspacemacs-distinguish-gui-tab t
   dotspacemacs-auto-resume-layouts t
   dotspacemacs-persistent-server t
```

## Reproduce the issue

I removed my dot file and the repository, then download the repository and open emacs again, using the vim mode and standard distribution. This time, I saw a compilation error:
``` 
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/popwin-20150315.600/" -*-
Compilation started at Sun Feb 14 00:54:34

make -k 
make: *** No targets specified and no makefile found.  Stop.

Compilation exited abnormally with code 2 at Sun Feb 14 00:54:34
```

After that, I modified the ```dotspacemacs-distinguish-gui-tab``` in the new, clean dot file. I still got ```<C-i> is undefined```.

**Comment by StreakyCobra** [comment] 2016-02-14 12:45
>       (setq dotspacemacs-enable-paste-micro-state t)
>       (setq-default dotspacemacs-smartparens-strict-mode t)

These two variables exist in `dotspacemacs/init` and should be modified there.

I don't really know what the problem is then. Maybe a problem related to the different version of emacs on OS X? I can't really help more :-(

**Comment by XiaoLiuAI** [comment] 2016-02-14 13:10
Could you please tell me what emacs do you use?

**Comment by StreakyCobra** [comment] 2016-02-14 13:28
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. a111f48)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 bb-latex bepo better-defaults c-c++ clojure colors command-log csv deft dockerfile
 (elfeed :variables rmh-elfeed-org-files
         (list "~/org/elfeed.org"))
 encoding emacs-lisp emoji erc erlang ess evil-cleverparens evil-little-word extra-langs finance git github haskell html imenu-list ipython-notebook javascript jb-replace-text latex markdown mu4e no-dots ocaml org pandoc plantuml python ranger restclient ruby scala semantic shell shell-scripts spacemacs-helm speed-reading
 (spell-checking :variables spell-checking-enable-auto-dictionary t)
 syntax-checking systemd themes-megapack theming typography
 (version-control :variables version-control-diff-tool 'diff-hl)
 writeroom yaml)
```

**Comment by daniloisr** [comment] 2016-02-17 16:20
@XiaoLiuAI I'm facing your problem on OSX too, and this variable fixed `C-i` for me:

```emacs-lisp
;; .spacemacs
(custom-set-variables
 '(evil-want-C-i-jump t))
```

But seems that this this is not the desired behaviour, as @StreakyCobra did this  https://github.com/syl20bnr/spacemacs/commit/daef4d5301ea8db903e9325e1d77c486b3ef9375  a few days ago.

Maybe this is related to my version of Emacs:
```
brew tap railwaycat/homebrew-emacsmacport
brew install emacs-mac
```

**Comment by justbur** [comment] 2016-02-17 16:27
@XiaoLiuAI Are you using emacs in the terminal?

**Comment by XiaoLiuAI** [comment] 2016-02-17 16:30
@justbur I use GUI, teh emacs compiled and installed from homebrew.

**Comment by XiaoLiuAI** [comment] 2016-02-17 16:33
@daniloisr Currently, I just set global key in user configuration block in dot file.
```elisp
  (global-set-key (kbd "<C-i>") 'evil-jumper/forward)
```
It's an urgly method, but I don't have other solution, setting hook does not work.

**Comment by justbur** [comment] 2016-02-17 16:35
@XiaoLiuAI evil-jumper was removed last night, so that's not going to work anymore fyi. 

What message do you get if you do `M-: (read-key) RET C-i`

**Comment by XiaoLiuAI** [comment] 2016-02-20 23:23
@justbur I just got ```C-i``` in mini-buffer.

**Comment by justbur** [comment] 2016-02-21 00:22
@XiaoLiuAI Hm, that's the right response. Do you mind checking these things? You can eval them in an emacs-lisp-mode buffer or using `M-:`. Thanks
```elisp
(lookup-key evil-motion-state-map [C-i]) ;; should be evil-jump-forward
(display-graphic-p) ;; should be t
dotspacemacs-distinguish-gui-tab ;; should be t
(lookup-key key-translation-map [?\C-i]) ;; should be spacemacs/translate-C-i
```

**Comment by XiaoLiuAI** [comment] 2016-02-21 00:27
@justbur 
The answers are:
```
nil
t
t
spacemacs/translate-C-i
```

**Comment by justbur** [comment] 2016-02-21 00:38
The nil is the problem then. Are you sure you don't have anything related to that key binding in your personal config and that you are up to date with spacemacs sources?

**Comment by XiaoLiuAI** [comment] 2016-02-21 00:47
The only thing I did, which is direclty relative to this key binding, is adding ```(global-set-key (kbd "<C-i>") 'evil-jumper/forward)``` aftering having this problem.

**Comment by justbur** [comment] 2016-02-21 18:30
@XiaoLiuAI I see the problem. Somehow the tab translation made it into the master branch but the binding didn't (it's still only in the develop branch). As a workaround you can add this line to user-config.
```elisp
(define-key evil-motion-state-map [C-i] 'evil-jump-forward)
```

cc @syl20bnr

**Comment by XiaoLiuAI** [comment] 2016-02-23 08:58
@justbur Thanks!

**Comment by chessman** [comment] 2016-04-11 16:02
Hi! Do you plan to backport this issue? It's still in master.

**Comment by TheBB** [comment] 2016-04-12 11:49
We can backport the solution. Not the issue. :-)

**Comment by StreakyCobra** [comment] 2016-04-12 12:40
I've marked it as such also ;-)

**Closed** 2016-04-21 03:14 UTC
Labels: - Bug tracker -, Bug :-(, Hotfix Required, Key Bindings

**Comment by syl20bnr** [comment] 2016-04-21 03:58
Fixed in 0.105.19

**Comment by lulin** [comment] 2016-07-19 03:04
Hi, I met the problem in terminal. set "dotspacemacs-distinguish-gui-tab t" works fine in gui, but it doesn't work in terminal, :sweat:

**Comment by TheBB** [comment] 2016-07-19 08:22
There's no way to distinguish C-i and TAB in the terminal.

**Comment by nicber** [comment] 2017-04-04 11:58
This happens to me on Ubuntu 16.04, Emacs 25.1, Spacemacs 0.200.8.
If I press C-h k and then C-i I get the description for the command that is bound to TAB.

**Comment by krizex** [comment] 2017-06-16 03:22
@nicber I have solved my problem following https://github.com/syl20bnr/spacemacs/issues/5936
May it will help you too.

**Comment by semihalf-dubiel-michal** [comment] 2017-08-24 09:09
May I ask if it means that Spacemacs does not intend to behave the same way Vim or vanilla Evil (without spacemacs) does in the terminal? I understand that C-i and TAB are indistinguishable in the terminal but they could be bound to jumping forward functionality as the vanilla Evil does in normal mode.

**Comment by mcp292** [comment] 2022-01-04 18:50
> This happens to me on Ubuntu 16.04, Emacs 25.1, Spacemacs 0.200.8. If I press C-h k and then C-i I get the description for the command that is bound to TAB.

Is there any way to have `C-i` call `evil-jump-forward` and not act as `TAB`?
