### ISSUE TITLE
golang jump to define not bind to gg

### ISSUE THREAD

**Issue by zwb-ict** [syl20bnr/spacemacs#6663] opened 2016-07-24 08:00 UTC
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-C C-C` TO SUBMIT>>
#### Description :octocat:
golang jump to define not bind to gg

#### Reproduction guide :beetle:
- Start Emacs
- open a golang file
- point at a function run , g g

*Observed behaviour:* :eyes: :broken_heart:
File GTAGS not found. Run 'gtags'? (y or n) 

*Expected behaviour:* :heart: :smile:
call godef-jump

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 1b5bc13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(erc
 (syntax-checking :variables syntax-checking-enable-tooltips t)
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete)
 helm ivy nginx better-defaults
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (org :variables org-enable-github-support t)
 ruby-on-rails
 (chinese :variables chinese-enable-fcitx t)
 c-c  
 (clojure :variables clojure-enable-fancify-symbols t)
 emacs-lisp erlang
 (go :variables gofmt-command "goimports" go-use-gometalinter t)
 haskell html javascript latex lua markdown
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm ruby-test-runner 'rspec)
 (rust :variables rust-enable-rustfmt-on-save t)
 scala shell-scripts yaml osx floobits
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
 github
 (version-control :variables version-control-diff-tool 'git-gutter  version-control-global-margin t)
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 cscope gtags ahei
 (dash :variables helm-dash-docset-newpath "~/Library/Application Support/Dash/DocSets")
 docker fasd ranger
 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/local/bin/zsh")
 tmux vagrant
 (ycmd :variables ycmd-server-command
       '("python" "/Users/zwb/.bin/ycmd/ycmd")
       ycmd-force-semantic-completion t)
 evernote
 (wakatime :variables wakatime-api-key "b0d4cb91-e437-470c-b54c-72d92716287c" wakatime-cli-path "/usr/local/bin/wakatime")
 blog gtd zwb)
```

#### Backtrace :paw_prints:
none

**Comment by TheBB** [comment] 2016-07-24 08:05
Closing this as a duplicate of https://github.com/syl20bnr/spacemacs/issues/6619.

**Closed by TheBB** 2016-07-24 08:05 UTC
Labels: Duplicate ☝
