### ISSUE TITLE
lsp + typescript has flycheck constantly rechecking on idle

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#13765] opened 2020-07-13 09:41 UTC
#### Description :octocat:
lsp + typescript has flycheck constantly rechecking on idle

#### Reproduction guide :beetle:
- Start Emacs
- open a typescript file
- make an edit

*Observed behaviour:* :eyes: :broken_heart:
1. flycheck runs
1. flycheck runs
1. flycheck runs
1. ... repeat forever

Flycheck is running its "on idle" check (via lsp--on-idle-timer) and displaying the results but instead of leaving it at that, it'll run again, and again, ...

And while flycheck is busy looping switching focus elsewhere seems to help sometimes, but not always. My guess is that switching to another typescript files keeps lsp/flycheck busy, but switching to a different buffer, like treemacs or magit-status makes it stop and switching back it stays idle. But after making another edit it starts looping again.

It doesn't seem to always start happening, tried with `create-react-app` project from scratch, and I can't share the code unfortunately. I know it's not much to go by but I don't quite know where to start looking.

(To make things worse as flycheck creates a temporary file in the current directory it triggers file change notifiers, say webpack dev server, which sometimes even manages to break the watcher to need to be manually restarted. There's a bug in the watcher yes, but lsp/flycheck shouldn't be busylooping to trigger it.)

*Expected behaviour:* :heart: :smile:
1. flycheck runs
1. the end

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs
            (auto-completion :variables auto-completion-enable-help-tooltip t)
            colors csv dash docker git
            (go :variables go-backend 'lsp go-format-before-save t go-use-golangci-lint t gofmt-command "goimports")
            graphviz helpful html imenu-list
            (javascript :variables javascript-backend 'lsp)
            lsp markdown nginx
            (org :variables org-enable-reveal-js-support t org-enable-sticky-header t org-enable-verb-support t)
            (osx :variables osx-command-as 'hyper osx-right-command-as 'super osx-option-as 'none osx-right-option-as 'meta)
            plantuml puppet python react restclient semantic shell-scripts syntax-checking
            (typescript :variables typescript-backend 'lsp)
            version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

**Comment by tko** [comment] 2020-07-15 18:31
The problematic project has tslint configured (`"extends": ["tslint-config-airbnb"]` + extras) but adding that to a newly created `create-react-app` project doesn't seem to be enough to trigger the odd behavior.

**Comment by smile13241324** [comment] 2020-07-18 21:25
@tko I have never heard of an issue like that :confused:.
First of all how do you know that there are multiple flycheck processes running? When I check `SPC a p` I am only seeing `ts-ls` the lsp server.

I have checked the flycheck config and flycheck is run entirely by `ts-ls` except when php layer is loaded and `drupal-mode` is loaded which seems to load a next checker after `LSP-UI` but I doubt that this could create the behaviour you are describing.
In this setup if someone is creating linter processes in an endless loop it would be the LSP server or lsp-mode not spacemacs itself.

Not sure if I can help in this case....

**Comment by tko** [comment] 2020-07-20 10:55
@smile13241324 I can tell from the `flycheck_whatever.tsx` file, named after the file I'm editing, appearing and disappearing repeatedly. There are not multiple flycheck processes _in parallel_ just the one being triggered from `lsp--on-idle-timer` sequentially, once one process ends soon after another gets started. If I disable `flycheck-mode` on the buffer the timer will report an error and the repeating stops.

My best guess is there's something in the project configuration that somehow manages to trigger something somewhere, but educated guesses haven't worked and I'm unfamiliar with the whole lsp/elisp side and I should be working instead of debugging this so my progress is slow to glacial 😕

**Comment by smile13241324** [comment] 2020-07-21 19:50
@tko you say you have a linter run after lsp? This should actually not run. When I am using your layer config I am just having lsp run which is responsible for running other linters. When I activate tslint, lsp is deactivated. 

Do you change the flycheck config in your dotfile or do you activate global flycheck mode?

You already said that you cannot share your project, however for diagnostics I need at least some sample configs to reproduce your issue. With my very simple single file project I cannot reproduce it.

**Comment by tko** [comment] 2020-07-22 09:40
Oof, right, I'm manually adding `tslint` as next checker for `lsp`, sorry. 🤦 

```elisp
(flycheck-add-mode 'typescript-tslint 'typescript-tsx-mode)
(flycheck-add-next-checker 'lsp 'typescript-tslint 'append)
```
mimicking what typescript layer does when `typescript-linter` is `'eslint`

That's my (attempted) workaround for typescript layer not running tslint when `'lsp` backend is used, it's run with `'tide`, and I forgot to report that bug.

Still, I can't reproduce this with a simple project either! The following does _not_ show the symptoms, lsp/tslint both run just fine, and I'm running out of ideas what might be triggering anything.
```bash
npx create-react-app --template typescript 13765
cd 13765
yarn add -D typescript@3.5.3 tslint@5.10.0 tslint-config-airbnb@5.9.2 @types/react
echo '{ "extends": ["tslint-config-airbnb"] }' > tslint.json
emacsclient -n src/App.tsx
```

**Comment by duianto** [comment] 2020-07-28 13:38
The following PRs changes have been applied to the `develop` branch:
[typescript] configure tslint also for lsp backend #13797

Feel free to close this if the issue has been resolved.

**Closed** 2021-08-23 23:42 UTC
Labels: Fixed in develop, Syntax-checking, TypeScript, Language Server Protocol
