### ISSUE TITLE
Can't install spacemacs

### ISSUE THREAD

**Issue by trev-dev** [syl20bnr/spacemacs#11094] opened 2018-07-28 03:18 UTC
#### Description :octocat:
Can't get Spacemacs to install on Emacs 26.1 with neither the release or the dev branch

#### Reproduction guide :beetle:
- Get emacs on arch using pacman
- Install spacemacs using the git repo to .emacs.d
- Start Emacs
- Emacs tries to find the 90 some odd packages it needs, but can't. I wind up with an error message instead.
- Kill emacs task
- run as --insecure - same problem happens
- kill emacs, delete ~/.emacs.d and ~/.spacemacs
- try the developer banch instead. All of the above ensues. 

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
![screenshot from 2018-07-27 20-03-26](https://user-images.githubusercontent.com/28788713/43352455-93b27162-91d8-11e8-8ebd-6007ba2785c2.png)

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
Spacemacs downloads all of its packages and starts.

(%LAST_KEYS%)
^ What?

%SYSTEM_INFO%
![screenshot from 2018-07-27 20-10-23](https://user-images.githubusercontent.com/28788713/43352471-d8d4446e-91d8-11e8-86f9-ce917f5f5eab.png)
(Not sure what specific system information you need beyond this. Just ask.)

#### Backtrace :paw_prints:
from --debug-init
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "bind-map")
  require(bind-map)
  spacemacs-bootstrap/init-bind-map()
  funcall(spacemacs-bootstrap/init-bind-map)
  (let* ((pkg-name (eieio-oref pkg ':name)) (owner (car (eieio-oref pkg ':owners)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))))) (eieio-oref pkg ':pre-layers)) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored post-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> post-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/post-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while post-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))))) (eieio-oref pkg ':post-layers)))
  configuration-layer//configure-package(#<cfgl-package cfgl-package>)
  (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))
  (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))
  (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg))))))
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2((async bind-key bind-map diminish evil hydra use-package which-key))
  configuration-layer//configure-packages((abbrev ace-jump-helm-line ace-link ace-window adaptive-wrap aggressive-indent ansi-colors archive-mode async auto-compile auto-highlight-symbol avy bind-key bind-map bookmark bracketed-paste centered-buffer-mode centered-cursor clean-aindent-mode column-enforce-mode conf-mode debug default-helm-config default-ivy-config default-org-config define-word desktop diminish dired dired-x doc-view dumb-jump edebug ediff eldoc electric-indent-mode elisp-slime-nav emacs-lisp eval-sexp-fu evil evil-anzu evil-args evil-ediff evil-escape evil-evilified-state evil-exchange evil-iedit-state evil-indent-plus evil-lisp-state evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-search-highlight-persist evil-surround evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar exec-path-from-shell expand-region eyebrowse fancy-battery fill-column-indicator flx-ido golden-ratio google-translate helm helm-ag helm-descbinds helm-flx helm-make helm-mode-manager helm-projectile helm-spacemacs-faq helm-spacemacs-help helm-swoop helm-themes help-fns+ hexl hi-lock hide-comnt highlight-indentation highlight-numbers highlight-parentheses hl-anything hl-todo holy-mode hs-minor-mode hungry-delete hybrid-mode hydra ido ido-vertical-mode ielm image-mode imenu indent-guide info+ link-hint linum linum-relative lorem-ipsum macrostep move-text neotree occur-mode open-junk-file org-bullets org-plus-contrib origami package-menu page-break-lines paradox pcre2el persp-mode popup popwin process-menu projectile rainbow-delimiters recentf request restart-emacs savehist saveplace smartparens smooth-scrolling space-doc spaceline spacemacs-theme spacemacs-whitespace-cleanup subword tar-mode toc-org undo-tree uniquify url use-package uuidgen vi-tilde-fringe visual-line-mode volatile-highlights which-key whitespace winner winum ws-butler zoom-frm))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require 'core-spacemacs) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require 'server) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/trevdev/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/home/trevdev/.emacs.d/init.el" "/home/trevdev/.emacs.d/init.el" t t)
  load("/home/trevdev/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x25ee0d>)()
  command-line()
  normal-top-level()
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "bind-map")
  require(bind-map)
  spacemacs-bootstrap/init-bind-map()
  funcall(spacemacs-bootstrap/init-bind-map)
  (let* ((pkg-name (eieio-oref pkg ':name)) (owner (car (eieio-oref pkg ':owners)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/pre-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while pre-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))))) (eieio-oref pkg ':pre-layers)) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not (configuration-layer//package-enabled-p pkg layer)) (spacemacs-buffer/message (format "  -> ignored post-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> post-init (%S)..." layer)) (condition-case err (funcall (intern (format "%S/post-init-%S" layer pkg-name))) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append (format (concat "\nAn error occurred while post-configuring %S " "in layer %S (error: %s)\n") pkg-name layer err))))))))) (eieio-oref pkg ':post-layers)))
  configuration-layer//configure-package(#<cfgl-package cfgl-package>)
  (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))
  (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))
  (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg))))))
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ':owners)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ':location))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons (file-name-as-directory location) load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq 'local location) (eq 'dotfile (car (eieio-oref pkg ':owners)))) (setq load-path (cons (file-name-as-directory (concat configuration-layer-private-directory "local/" (symbol-name (eieio-oref pkg ':name)))) load-path))) ((eq 'local location) (let* ((owner (configuration-layer/get-layer (car (eieio-oref pkg ':owners)))) (dir (if owner (progn (eieio-oref owner ':dir))))) (setq load-path (cons (format "%slocal/%S/" dir pkg-name) load-path)))))) (if (memq (eieio-oref pkg ':location) '(local site built-in)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2((async bind-key bind-map diminish evil hydra use-package which-key))
  configuration-layer//configure-packages((abbrev ace-jump-helm-line ace-link ace-window adaptive-wrap aggressive-indent ansi-colors archive-mode async auto-compile auto-highlight-symbol avy bind-key bind-map bookmark bracketed-paste centered-buffer-mode centered-cursor clean-aindent-mode column-enforce-mode conf-mode debug default-helm-config default-ivy-config default-org-config define-word desktop diminish dired dired-x doc-view dumb-jump edebug ediff eldoc electric-indent-mode elisp-slime-nav emacs-lisp eval-sexp-fu evil evil-anzu evil-args evil-ediff evil-escape evil-evilified-state evil-exchange evil-iedit-state evil-indent-plus evil-lisp-state evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-search-highlight-persist evil-surround evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar exec-path-from-shell expand-region eyebrowse fancy-battery fill-column-indicator flx-ido golden-ratio google-translate helm helm-ag helm-descbinds helm-flx helm-make helm-mode-manager helm-projectile helm-spacemacs-faq helm-spacemacs-help helm-swoop helm-themes help-fns+ hexl hi-lock hide-comnt highlight-indentation highlight-numbers highlight-parentheses hl-anything hl-todo holy-mode hs-minor-mode hungry-delete hybrid-mode hydra ido ido-vertical-mode ielm image-mode imenu indent-guide info+ link-hint linum linum-relative lorem-ipsum macrostep move-text neotree occur-mode open-junk-file org-bullets org-plus-contrib origami package-menu page-break-lines paradox pcre2el persp-mode popup popwin process-menu projectile rainbow-delimiters recentf request restart-emacs savehist saveplace smartparens smooth-scrolling space-doc spaceline spacemacs-theme spacemacs-whitespace-cleanup subword tar-mode toc-org undo-tree uniquify url use-package uuidgen vi-tilde-fringe visual-line-mode volatile-highlights which-key whitespace winner winum ws-butler zoom-frm))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require 'core-spacemacs) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require 'server) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/trevdev/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/home/trevdev/.emacs.d/init.el" "/home/trevdev/.emacs.d/init.el" t t)
  load("/home/trevdev/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x25ee0d>)()
  command-line()
  normal-top-level()

```

**Comment by trev-dev** [comment] 2018-07-28 08:04
I had to adjust my .spacemacs

   ;; If non nil ELPA repositories are contacted via HTTPS whenever it's
   ;; possible. Set it to nil if you have no way to use HTTPS in your
   ;; environment, otherwise it is strongly recommended to let it set to t.
   ;; This variable has no effect if Emacs is launched with the parameter
   ;; `--insecure' which forces the value of this variable to nil.
   ;; (default t)
   **dotspacemacs-elpa-https nil**
   ;; Maximum allowed time in seconds to contact an ELPA repository. (default is 5 seconds??)
   **dotspacemacs-elpa-timeout 20**

Installed and happy!!

**Comment by smile13241324** [comment] 2018-08-11 17:14
@trev-dev just found your issue, when you were able to solve it yourself, would you mind closing your ticket?

**Comment by trev-dev** [comment] 2018-08-11 23:10
My apologies, I didn't realize that I could and should close issues! Done.

**Closed** 2018-08-11 23:09 UTC

**Comment by PierreR** [comment] 2018-09-06 11:28
Isn't this a real issue ? You need to do `dotspacemacs-elpa-https nil` otherwise you cannot install.
Is it something that is just a temporary workaround on another elpa related issue ?
Anyhow thanks @trev-dev. Without your post I would have been losing many more time on this.

**Comment by PierreR** [comment] 2018-09-06 11:35
Well my problem seems that https://elpa.gnu.org is down again.

**Comment by trev-dev** [comment] 2018-09-06 14:12
Even when it's not down, I have to tweak the settings every time I install *shrug*. My guess is Melpa doesn't have the greatest response time in general. While using my regular emacs config, I don't even designate any sort of timeout.

**Comment by masukomi** [comment] 2019-07-29 02:25
This really ought to be reopened. Spacemacs literally won't function without this change. It doesn't matter that a random user found a workaround (thanks @trev-dev ). 

There are 2 problems related to this

* doesn't work at all for new users unless they figure out just the right search term to google for
* the 3 packages it was dying on (undo-tree, adaptive-wrap, and spinner) don't appear to be core to spacemacs being functional and as such the install shouldn't fail when they're missing. It should just let you know there's some packages it couldn't download , and list what they are. Noting, of course, that their related functionality won't be available.

**Comment by duianto** [comment] 2019-07-29 06:16
Currently there's an Emacs issue that seems like it's going to be fixed in the next Emacs version (26.3?).

There's a workaround in this issue:
Failed to download 'gnu' archive. Bad request. (Solution included) #12535

**Comment by markboston34** [comment] 2019-07-30 16:23
i am also having this issue. i can use https on my system so im not sure what the problem is. when will this be fixed? i don't really want to turn off secure connection.

**Comment by smile13241324** [comment] 2019-08-02 17:03
As duianto already said this is an upstream issue and can therefore not be fixed by spacemacs.
Your best bet is to either upgrade your emacs or to downgrade your gnu-tls library which seems to be the root cause, judging from the details [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34341).
