### ISSUE TITLE
Failed to install paradox package!

### ISSUE THREAD

**Issue by NeedtoLearn** [syl20bnr/spacemacs#4644] opened 2016-01-17 06:28 UTC
Hi guys,

I followed the installation instructions, everything is ok until I start emacs --insecure. 2 errors appears, caused spacemacs cannot operate properly.

<img width="740" alt="screen shot 2016-01-17 at 2 26 20 pm" src="https://cloud.githubusercontent.com/assets/3848577/12376290/6a42dada-bd26-11e5-9aad-2bc92c6ec6db.png">

Anyone got same issue with me? Is it due to elpa server or mistakes I made during installation steps?

Thanks.

**Comment by StreakyCobra** [comment] 2016-01-17 16:09
This *may* be a duplicate of https://github.com/syl20bnr/spacemacs/issues/4138

**Comment by TheBB** [comment] 2016-09-21 19:34
No reproduction.

**Closed by TheBB** 2016-09-21 19:34 UTC
Labels: Install, To be reproduced
