### ISSUE TITLE
[Go layer] Seems like lsp is not a valid backend for gopls anymore?

### ISSUE THREAD

**Issue by Asalle** [syl20bnr/spacemacs#13841] opened 2020-08-14 10:26 UTC
#### Description :octocat:
Seems like lsp is not a valid backend for gopls anymore? I start spacemacs and try to work and gopls just exits (see backtrace).

#### Reproduction guide :beetle:
- Start Emacs
- Add the following to your .spacemacs
```
     (go :variables
				 go-backend 'lsp
         go-format-before-save t
         go-use-golangci-lint t
         godoc-at-point-function 'godoc-gogetdoc)
```
- Open any go file
- Start typing, and then try to code-complete a variable name.

*Observed behaviour:* :eyes: :broken_heart:
No code-completion is happenning, errors are see in the minibuffer. gopls exits with code 2.

*Expected behaviour:* :heart: :smile:
Code-completion is happening, no errors, gopls carries on.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76301564c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(octave typescript systemd php python yaml javascript graphviz
				(markdown :variables markdown-live-preview-engine 'vmd)
				(go :variables go-format-before-save t go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc)
				helm auto-completion git org c-c++ github
				(shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
				better-defaults syntax-checking lsp protobuf dap)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS GLIB NOTIFY GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS

#### Backtrace :paw_prints:
```
error in process sentinel: flycheck-add-next-checker: lsp is not a valid syntax checker
error in process sentinel: lsp is not a valid syntax checker
LSP :: gopls:22497 initialized successfully
LSP :: unexpected config codelens
LSP :: Sending to process failed with the following error: Process gopls not running [2 times]
```

**Comment by Asalle** [comment] 2020-08-14 10:28
seems related to this one? https://github.com/hlissner/doom-emacs/issues/1530

**Comment by smile13241324** [comment] 2020-08-26 21:09
I can reproduce this on almost all LSP powered modes, I will have a look into this. Thanks for reporting.

**Comment by smile13241324** [comment] 2020-08-26 22:08
Found and fixed the issue, it was primarily caused by the `typescript-layer` trying to add `tslint` to `lsp` when `lsp` is not yet loaded and do that unconditionally. I have also found that the way how the go layer activated `golangci-lint` was also deprecated.

After correcting both statements the issue is gone on my linux box.
@Asalle can you retry?

**Comment by Asalle** [comment] 2020-08-27 06:58
thank you so much for quick reply and taking action!
I checked out your commit (15d93914f5caf6a3a15c573da60576313b0eee04) on develop and restarted emacs, I can still see this in `Messages`:
```
[go] Setting lsp-diagnostic-package :none to enable golangci-lint support.
LSP :: Connected to [gopls:20988 status:starting].
LSP :: gopls:20988 initialized successfully
LSP :: unexpected config codelens
```
Should I do something else apart from checking out the commit to check it properly?

**Comment by smile13241324** [comment] 2020-08-28 21:36
Yes please close it, I think what you are seeing here is a minor misconfiguration between lsp-mode and the latest version of you go LSP server. If this persists you should open a ticket with `lsp-mode`, they can surely double check.

**Closed by smile13241324** 2020-08-28 21:36 UTC
Labels: Go, Language Server Protocol
