### ISSUE TITLE
Add "persist/" and "tutorial/" in .gitignore, please?

### ISSUE THREAD

**Issue by breadncup** [syl20bnr/spacemacs#15207] opened 2021-12-14 19:18 UTC
I have been using spacemacs for a while, not sure when/how `persist/` and `tutorial/` directories were created, but they were generated.

Anyway, could you consider putting those directories in .gitignore, please because they're not managed by the spacemacs?

**Comment by lebensterben** [comment] 2021-12-14 20:18
Anyone has idea what package created these directories?

**Comment by breadncup** [comment] 2021-12-15 04:33
```shell
$ l persist
total 8
drwxr-xr-x   3 ysong  staff    96B Dec 14 20:31 .
drwx------  40 ysong  staff   1.3K Dec 14 20:31 ..
-rw-r--r--   1 ysong  staff   1.4K Dec 14 20:31 org-drill-sm5-optimal-factor-matrix
```

and

```shell
$ l tutorial
total 96
drwxr-xr-x   3 ysong  staff    96B Dec  7 22:17 .
drwx------  40 ysong  staff   1.3K Dec 14 20:31 ..
-rw-r--r--   1 ysong  staff    46K Oct 31 12:05 English.tut
```

**Comment by breadncup** [comment] 2021-12-15 04:37
Looks like `persist` was generated by org-drill package.

The tutorial is generated by Emacs tutorial. Opening `English.tut` file, I could see it starts like this:

```
-1
50
Emacs tutorial.  See end for copying conditions.

Emacs commands generally involve the CONTROL key (sometimes labeled
CTRL or CTL) or the META key (sometimes labeled EDIT or ALT).  Rather than
write that in full each time, we'll use the following abbreviations:
```

**Comment by lebensterben** [comment] 2021-12-18 05:18
@breadncup 
I believe you've added org-drill package yourself. So you'd be responsible for the directory it created. But I doubt whether it's the real culprit.

**Comment by lebensterben** [comment] 2021-12-18 05:20
Merely starting emacs-tutorial won't create the tutorial directory.
I guess you've created it by yourself when you followed its instructions. And you should expect yourself to remove any artifacts.

**Comment by breadncup** [comment] 2021-12-18 05:23
@lebensterben , okay.

I didn't create or follow any instructions. Actually, I don't remember opening Emacs tutorial at all, but while using the Emacs or referring a help file, would it be created by Emacs itself?

I may check org-drill case if I can reroute the directory creation, but would it be possible for you to check the Emacs tutorial, please? I have no idea how it was created.

**Comment by lebensterben** [comment] 2021-12-18 05:27
> but while using the Emacs or referring a help file, would it be created by Emacs itself?

Not AFAIK

**Comment by lebensterben** [comment] 2021-12-18 05:28
Closing it now since this is not reproducible.

You should manually remove those two directories. Should they be created again, please re-open this issue and attach relevant information.

**Closed by lebensterben** 2021-12-18 05:28 UTC

**Comment by breadncup** [comment] 2021-12-18 05:30
Found who create `~/.emacs.d/persist` It's `persist` package, and looks like org-drill depends on the package and it is installed by it.

`persist--directory-location` has the default value of `~/.emacs.d/persist` So, I can deal with it.

However, I'm still not sure about the Tutorial directory.

**Comment by lebensterben** [comment] 2021-12-18 05:37
@breadncup 
[persist](https://elpa.gnu.org/devel/persist.html) is not used by Spacemacs and only be `org-drill` via dependency.

**Comment by breadncup** [comment] 2021-12-18 05:44
@lebensterben , yes. I think I can handle the case of `org-drill`

Now I look more into the tutorial thingy, and, now I found a way to reproduce it with vanilla spacemacs.

I will create a new ticket since it is closed.
