### ISSUE TITLE
Powerline confused about frame focus

### ISSUE THREAD

**Issue by skrat** [syl20bnr/spacemacs#2545] opened 2015-08-05 10:24 UTC
Look at this http://i.imgur.com/ke3t4Gc.gif

It's from i3-wm, I have multiple frames open, and the powerline doesn't reflect correctly whichever frame is focused.

**Comment by travisbhartwell** [comment] 2015-08-05 13:17
I have noticed similar behavior.  What I noticed with i3wm is due to the container nature of i3.  When you move the mouse I believe what happens is the container gets focused, not the window.  I have verified this by enabling a "focus child" keybinding in my i3 config, say by uncommenting the following line from the default config:

```
#bindsym Mod1+d focus child
```

After I move the mouse over the other frame, I hit `Mod1+d` (or whatever you bind this to), and the next keystroke I press causes the Emacs window to behave as if it has focus and the powerline displays appropriately.  It's as if i3 is not sending the focus events to the Emacs window otherwise.

Does this explain the behavior you're seeing?

**Comment by skrat** [comment] 2015-08-05 13:28
Yes that would explain it. Have you found any way around it?

**Comment by skrat** [comment] 2015-08-05 13:30
Well, you can see in my screencast that the the current line gets highlighted, and also the cursor changes to its focused look. So actually no, it doesn't explain it :)

**Comment by travisbhartwell** [comment] 2015-08-05 13:43
I guess I haven't investigated it further since I discovered that focusing the child would get around it.  I need to figure out what event causes Powerline to change appearance and see why i3wm isn't sending it.

**Comment by syl20bnr** [comment] 2015-08-05 14:02
What is weird is that the powerline behavior is exactly inversed, empty when focused and full when not focused. Maybe digging `powerline-selected-window-active` would give some answers.

**Comment by felipe-barros** [comment] 2015-08-05 21:37
Also in i3wm, when I create a new frame, the modeline colors are totally wrong.
![borked-modeline-on-new-frame](https://cloud.githubusercontent.com/assets/9657386/9098550/fbf39d1e-3ba0-11e5-8bed-82bd32d17dc4.png)

**Comment by CestDiego** [comment] 2015-08-06 04:54
@felipe-barros make sure you don't have custom-variables regarding theme faces in your .spacemacs

**Comment by felipe-barros** [comment] 2015-08-06 05:12
``` elisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ahs-case-fold-search nil)
 '(ahs-default-range (quote ahs-range-whole-buffer))
 '(ahs-idle-interval 0.25)
 '(ahs-idle-timer 0 t)
 '(ahs-inhibit-face-list nil)
 '(ring-bell-function (quote ignore) t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil)))))
```

Besides this at the end (and I still don't understand this auto-generated code), there is nothing else changing theme faces.

**Comment by rasmikun** [comment] 2015-08-26 15:57
I have faced that bug too and tried another wm's: xmonad and wmii. But bug still present there.

So I write small spiky workaround: just remove not from 'powerline-set-selected-window' (powerline package) and all windows become grey despite focus.

**Comment by rasmikun** [comment] 2015-09-14 14:22
Also, I noticed that if you open some window (for example type <M-x> and open helm window), powerline focus move to the right window.

**Comment by rasmikun** [comment] 2015-09-15 09:49
So, also tried fluxbox, and behavior was exactly the same. Then I put some debug output and what I've got:

Setting (powerline-selected-window) is done by calling (focus-in-hook) and (focus-out-hook). Therein, in handlers, (powerline-selected-window) set to the (frame-selected-window). BUT the frame-selected-window is pointed to the wrong window, the window that is previously selected. If then you execute (print (frame-selected-window)) you will get the correct answer. So, the problem is deeper in core of emacs, in code that handling focusing events and setting (frame-selected-window). For some reason focus hooks raising earlier then setting frame-selected-window. 

Moreover, by the documentation (frame-selected-window) is pointing to the last frame that gains input focus. So, if you move focus from the emacs at all to some other window, the (powerline-selected-window) will be not nill and one of the emacs window will have a colored modeline, despite the real focus.

May be this questions should be asked to the powerline developers?

**Comment by rasmikun** [comment] 2015-09-15 12:46
And I discover more convenient workaround with powerline: i make the powerline-selected-window-active always returning true, and unselected windows disappear at all, all windows are like a selected now.

Just rewrite the powerline-selected-window-active elpa/powerline-x/powerline.el as

`(defun powerline-selected-window-active ()
   "Return whether the current window is active."
   t)`

**Comment by curtmack** [comment] 2015-09-22 14:20
I can confirm this happens in xmonad.

**Comment by StreakyCobra** [comment] 2015-11-10 20:00
Still happening with `spaceline` (and i3-wm in my case). It's not inverted between focused and unfocused windows, as previously suggested, but it's always the previously focused windows that is "highlighted". In other words, the highlighting is always one windows behind.

**Comment by mskorzhinskiy** [comment] 2016-03-03 13:02
There is new pull request to powerline appeared and merged to powerline not so far ago. Check it: https://github.com/milkypostman/powerline/pull/111. It's solves this issue for me.

But, it introduces a new bug. Check here for explanation and fix: https://github.com/zakame/.emacs.d/commit/818b5e364f40424fb47549a85dd275b8e307c255

Anyway, I believe this issue can be closed after @skrat confirmation.

**Comment by TheBB** [comment] 2016-03-03 14:51
I can confirm that something seems to have fixed this, at least. :-)

**Comment by TheBB** [comment] 2016-06-10 11:51
Closing since this appears to be fixed, and no reports to the contrary.

**Closed by TheBB** 2016-06-10 11:51 UTC
Labels: - Bug tracker -, Bug :-(, Mode Line, Waiting for response
