### ISSUE TITLE
Magit: "eval-buffer: Cannot open load file: no such file or directory, magit-autorevert"

### ISSUE THREAD

**Issue by microamp** [syl20bnr/spacemacs#4585] opened 2016-01-13 00:37 UTC
With the latest updates, none of the Magit commands works anymore in my Emacs reporting the following error message:
```
eval-buffer: Cannot open load file: no such file or directory, magit-autorevert
```

**Comment by syohex** [comment] 2016-01-13 00:44
Please see https://github.com/milkypostman/melpa/issues/3488

**Comment by microamp** [comment] 2016-01-13 03:52
Thanks for the info, @syohex

**Comment by malchmih** [comment] 2016-01-13 05:25
Is there a workaround for this?

**Comment by syohex** [comment] 2016-01-13 05:27
Download the file and put it under load-path directory.

**Comment by malchmih** [comment] 2016-01-13 05:27
Thanks :smile:

**Comment by syohex** [comment] 2016-01-13 07:43
MELPA PR has been merged. This issue will be fixed when magit on MELPA is updated.

**Comment by oskarizu** [comment] 2016-01-14 08:26
I've just updated package magit in spacemacs and can confirm that the issue is solved for me, `magit` is working fine again, thanks!

**Comment by StreakyCobra** [comment] 2016-01-14 09:09
:+1: Closing as fixed upstream

**Closed by StreakyCobra** 2016-01-14 09:09 UTC
Labels: Fixed upstream, Git

**Comment by microamp** [comment] 2016-01-16 05:26
Awesome, thanks guys :+1:
