### ISSUE TITLE
Buffer file name is missing in modeline

### ISSUE THREAD

**Issue by souvik1997** [syl20bnr/spacemacs#9881] opened 2017-11-16 21:58 UTC
When I open a file in Spacemacs I can see the buffer file name in the modeline, but after using projectile-ag to search for some text and closing the frame that projectile-ag creates, the buffer file name disappears. Is there a way to disable this behavior?

**Comment by bmag** [comment] 2017-11-17 10:46
Please provide repro steps and system info. Try to make a clear report so we can understand exactly what happened. If you have to windows open in the same frame, does the inactive window show the buffer's name?

**Comment by RockyRoad29** [comment] 2017-11-23 09:39
This issue affects me as well, now using v0.200.7/develop (rev. 0c8af9686).
For me it tends to happen especially 
   - in .git tracked projects (magit indicators present)
   - when emacs windows is in default size or narrower, 
   - window is active ... 

Then I noticed this new `"edit"` segment in the modeline, rather wide, and I found out that it comes from
the [spacemacs-purpose layer](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-purpose/README.org).
Things went better since I decided, as a workaround, to disable the segment in my `.spacemacs`
``` elisp
(defun dotspacemacs/user-config ()
  (spaceline-toggle-purpose-off)
)
``` 
The buffer name still happens to disappear though, I suspect that the segment itself still exists and uses width, I don't know how to change that. I don't know either if there would be some kind of segment priority settings to the spaceline. IMHO the buffer name segment should be of high priority.

Maybe the window purpose indicator could be reduced to some tiny symbol, or replaced with color indication ?

**Comment by bmag** [comment] 2017-11-23 09:49
Perhaps buffer name is hidden because the window is so small (or the font so big) that Spaceline can't fit all the segments inside, and has to hide some of them?

**Comment by RockyRoad29** [comment] 2017-11-23 17:39
On 23/11/17 10:50, bmag wrote:
> Perhaps buffer name is hidden because the window is so small (or the 
> font so big) that Spaceline can't fit all the segments inside, and has 
> to hide some of them?

Well... that's a way of putting it :-! My font is just unchanged Source 
Code Pro 13, on a 1366x768 laptop screen. I was just carefully 
suggesting there could be too much stuff to display ...

**Comment by HongbinZhou** [comment] 2017-12-05 09:58
I met the same issue, buffer file name was missing in modeline. I did the following trick and it was back:
- change Source Code Pro font size from 15 to 13
- disable `which-function-mode` (I had `(which-function-mode 1)` in my init file before)

It should be better way to fix this...

**Comment by carloscheddar** [comment] 2018-01-26 14:43
I have this issue as well and I've found that toggling `golden-ratio` on and off brings the buffer names back. Definitely seems to be related to the window size.

**Comment by howardabrams** [comment] 2018-02-13 00:58
I have tried everyone suggested here, but I think something else is going on. Here is my modeline attempting to display the *scratch* buffer:
![spacemacs-missing-buffername](https://user-images.githubusercontent.com/500621/36128185-e473b150-1015-11e8-8ef9-b1473a5c4a29.png)

**Comment by autosquid** [comment] 2018-02-24 13:49
using vim-powerline theme instead of spacemacs theme is the solution for me.

**Comment by carloscheddar** [comment] 2018-03-07 19:41
I think this is related to the `responsive` mode of the `mode-line`. I disabled it by pressing(`SPC t m r`) this then lets me see the file name and all the other info. Once I found that out I kept responsive mode enabled but ended up disabling minor-modes(`SPC t m m`) to get more space to fit the file name.

**Comment by RockyRoad29** [comment] 2018-03-11 15:46
Thanks carloscheddar for the nice alternative to get the precious buffer-name back in the
modeline.
For myself, I prefer hiding the far-right end of the mode line than
the nice space-optimized icons of minor mode.

Obviously different users would have different priorities. I like using helm
command discovery feature to find which command could help try: `M-x toggle mode
line` (separate words) or \M-x space line toggle. 
Key bindings exist for a subset of them; furthermore,
you get the exact command name if you want to insert that in your spacemacs
config (`SPC f e d`). Hence I updated it l

```elisp
  (defun dotspacemacs/user-config ()
    ;; ...
    ;; modeline optimization/workarounds
    ;; (spaceline-toggle-purpose-off)
    (spacemacs/toggle-mode-line-responsive-off)
  )
```

I'd love to be able to replace contents of the rightmost modeline segments with
utf8 symbols, like minor modes indicators.

**Comment by piotrpalek** [comment] 2018-03-16 08:07
I'm another one with a similar issue.

Reproduction steps for are:
1. Open a vertical split
2. Make it small enough so that the buffer name is hidden. 

@bmag If the issue is that the mode line doesn't have enough space to display everything, wouldn't it be best to preserve the filename as the main thing to be displayed, and hide all of the other stuff first? Seems like a good default to me. Currently it seems to me that when there isn't enough space, the buffer name is the first thing being hidden.

@carloscheddar didn't think about hiding stuff, thanks this should help a bit in the meantime :)

**Comment by TheBB** [comment] 2018-03-20 08:44
This should be fixed upstream.

**Closed** 2018-03-20 08:45 UTC
Labels: - Bug tracker -, Fixed upstream, Mode Line
