### ISSUE TITLE
Renaming file in dired: progn: Buffer is read-only: #<buffer foo>

### ISSUE THREAD

**Issue by Andre0991** [syl20bnr/spacemacs#5044] opened 2016-02-12 13:41 UTC
#### Description
I get the following message after trying to rename a folder in dired:
`progn: Buffer is read-only: #<buffer foo>`, where `foo` is the name of the directory.

#### Reproduction guide
- Start Emacs
- Open dired
- Use `R` to rename a file

*Observed behaviour:*
I get a message `progn: Buffer is read-only: #<buffer foo>`

*Expected behaviour:*
File is renamed.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: andre0991 (rev. 4a43898)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx spacemacs-helm spacemacs-ivy andre-spacemacs-ivy emacs-lisp syntax-checking common-lisp git github
     (shell :variables shell-default-shell 'eshell)
     spacemacs-layouts erc html pdf-tools
     (elfeed :variables rmh-elfeed-org-files
             (list "/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org"))
     themes-megapack semantic
     (auto-completion :variables auto-completion-private-snippets-directory "/Users/andre0991/Dropbox/backup/emacs/yasnippet-snippets/" auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for latex)
     org
     (ranger :variables ranger-show-preview t)
     markdown latex spell-checking version-control mu4e andre-common-lisp andre-elfeed andre-osx andre-erc andre-eww andre-mu4e)
```

@AlejandroCatalina is able to reproduce. He said that he gets this message in other buffers too (apart from dired) so it seems a more general problem.

Edit: My branch comes from develop.

**Comment by AlejandroCatalina** [comment] 2016-02-12 13:50
I've been getting this *<buffer fooo> is read-only>* all the morning, yes.

**Comment by StreakyCobra** [comment] 2016-02-12 14:53
It's probably related to upstream as there wasn't any commit recently on Spacemacs' side.

**Comment by bmag** [comment] 2016-02-12 17:29
I was not able to reproduce the error. You can try and debug it with `SPC t D` (`spacemacs/toggle-debug-on-error`). It should produce a backtrace when the error occurs.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. a111f48)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(spacemacs-helm
 (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control evil-cleverparens python command-log eyebrowse smex themes-megapack c-c++ ruby ibuffer window-purpose imenu-list debug extra)
```

**Comment by AlejandroCatalina** [comment] 2016-02-12 17:33
I think there is no *error* as is, maybe a misconfiguration or some weird conditions.

**Comment by bmag** [comment] 2016-02-12 17:43
Right, apparently Emacs doesn't see `Buffer is read-only` as an error. You can try `M-x debug-on-entry rename-buffer`, see if that does something. Although that won't do anything if the error is caused before actually renaming the buffer.

Other option: call `M-x rename-buffer` directly, see if you can rename a buffer. If that works, then the error is somewhere in the UI, probably.

**Comment by Andre0991** [comment] 2016-02-12 21:13
@AlejandroCatalina is correct, it doesn't trigger errors, seems that something is toggling read-only mode.

Also, I can rename the buffer, and toggling read-only mode makes it possible to rename files, as expected.

I noticed that this happens only when `spacemacs-ivy` is enabled.

After using `M-x debug-on-entry rename-buffer`, the problem is gone, even after restarting Spacemacs (??).

**Comment by AlejandroCatalina** [comment] 2016-02-12 22:25
I confirm it happened under `spacemacs-ivy`, i didn't think of that as i am no longer using helm, so it might be affecting. 

I couldn't tell under which situations this happens, for sure not only renaming buffers.

**Comment by Andre0991** [comment] 2016-02-14 00:29
@AlejandroCatalina Is the input duplicated when you use `f` in `Ranger`?

**Comment by Andre0991** [comment] 2016-02-14 00:55
OK, using `M-x debug-on-entry rename-buffer` and using `h` in ranger to get back, I got this error:

```
Debugger entered--entering a function:
* rename-buffer("andre0991" t)
  uniquify-rename-buffer([cl-struct-uniquify-item "andre0991" "/Users" #<buffer ~> "andre0991"] "andre0991")
  uniquify-rationalize-conflicting-sublist(([cl-struct-uniquify-item "andre0991" "/Users" #<buffer ~> "andre0991"]) "andre0991" 0)
  uniquify-rationalize-a-list(([cl-struct-uniquify-item "andre0991" "/Users" #<buffer ~> "andre0991"]))
  uniquify-rationalize(([cl-struct-uniquify-item "andre0991" "/Users" #<buffer ~> "andre0991"]))
  uniquify-rationalize-file-buffer-names("andre0991" "/Users/" #<buffer ~>)
  uniquify--create-file-buffer-advice(#[257 "\301!\211\302\230\203\f\262\303\304\305\306\307#)\266\203\203#\310P\202$!\207" [inhibit-changing-match-data file-name-nondirectory "" generate-new-buffer "\\` " nil t string-match "|"] 10 0] "~")
  apply(uniquify--create-file-buffer-advice #[257 "\301!\211\302\230\203\f\262\303\304\305\306\307#)\266\203\203#\310P\202$!\207" [inhibit-changing-match-data file-name-nondirectory "" generate-new-buffer "\\` " nil t string-match "|"] 10 0] "~")
  create-file-buffer("~")
  dired-internal-noselect("~/" nil)
  dired-noselect("~/")
  ranger-find-file("~/")
  ranger-up-directory()
  call-interactively(ranger-up-directory nil nil)
  command-execute(ranger-up-directory)

```

**Comment by justbur** [comment] 2016-02-14 01:12
@Andre0991 it looks like you're using ranger not dired, so you should specify that and ping @ralesi

**Comment by Andre0991** [comment] 2016-02-14 01:20
@justbur It happens in both ranger and plain dired. I tested this after excluding range and it happens too.

**Comment by Andre0991** [comment] 2016-02-14 01:27
I switched back to `develop` (the `andre` branch is where I apply `git am` to get some PRs not merged yet) and I get this error on startup:

`(Spacemacs) Error in dotspacemacs/user-config: Symbol's function definition is void: spacemacs/defer-until-after-user-config`

It is up to date. 

`--debug-init` doesn't really creates a debug buffer.

I have no idea if this has to do with the other issue. I don't know what's going on :scream:

**Comment by justbur** [comment] 2016-02-14 01:29
That's a new function that I introduced for transient states. Try checking out `origin/develop` and restarting in case there's something strange in your local repo

**Comment by Andre0991** [comment] 2016-02-14 01:41
@justbur Ah, ok. That happened because it was on `0.105.8` then actually (`origin` actually wasn't what I thought and it wasn't up to date). It works now (that is, I just have the original issue).

**Comment by Andre0991** [comment] 2016-02-14 01:57
Aha! I think I got it.

The problem was that I was using this:

``` emacs-lisp
(ivy-set-actions
 t
 '(("I" ivy-copy-to-buffer-action "insert")
   ("Y" ivy-yank-action "yank"))))
```

This is very convenient as I can insert/yank the candidate easily. But that was
affecting other things in a unexpected way. For example, when using the
`find-library` or any command in which `ivy` is being applied but wasn't really
customised (not sure what's the right term here, it's analogous to "helmize"
when using `helm`), after I selected the library and pressed `RET`, it not only
opened the file, but inserted (because of the action) its name on the previous
buffer!

@justbur is this expected when using Ivy? I still have to learn its API properly.

And that's why `f` in `ranger` had the path duplicated: `I` was somehow being
applied. This behaviour was messing lots of places.

**Comment by justbur** [comment] 2016-02-14 02:05
@Andre0991 @abo-abo might be able to help. I don't see what the issue is

**Comment by abo-abo** [comment] 2016-02-14 09:14
@Andre0991 should be fixed now, please check.

**Comment by Andre0991** [comment] 2016-02-14 16:57
@abo-abo Thanks, it doesn't insert in the buffer anymore when I use `find-library`.

The input in `dired` is still duplicated, though - I'm not sure if this caused by Ivy, but I think so.

To reproduce it:
- Open `dired`
- In the dired buffer, run `dired` again

It will ask for a path, which will be duplicated. For example, if you called it from `~`, the input is `~/~/`. This happens when I have `ivy-copy-to-buffer-action` and `ivy-yank-action`, or just the latter. If I remove these two actions, the path is not duplicated.

**Closed** 2016-06-10 11:59 UTC
Labels: Bug :-(, Waiting for response
