### ISSUE TITLE
spacemacs won't work with hybrid-mode on develop

### ISSUE THREAD

**Issue by kain88-de** [syl20bnr/spacemacs#8304] opened 2017-02-04 07:58 UTC
#### Description :octocat:
Spacemacs won't start with hybrid mode. This happens after [this commit](https://github.com/syl20bnr/spacemacs/commit/c7e47de). Using the commit before everything works

#### Reproduction guide :beetle:
- enable hybrid mode
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
hybrid-mode-use-evil-search-module is void 

*Expected behaviour:* :heart: :smile:
emacs starts fine

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable hybrid-mode-use-evil-search-module)
  (and (eq (quote hybrid) style) hybrid-mode-use-evil-search-module)
  (or (eq (quote vim) style) (and (eq (quote hybrid) style) hybrid-mode-use-evil-search-module))
  (cond ((or (eq (quote vim) style) (and (eq (quote hybrid) style) hybrid-mode-use-evil-search-module)) (setq-default evil-search-module (quote evil-search))) (t (setq-default evil-search-module (quote isearch))))
  spacemacs/set-evil-search-module(hybrid)
  spacemacs-bootstrap/init-evil()
  funcall(spacemacs-bootstrap/init-evil)
  (let* ((pkg-name (eieio-oref pkg (quote :name))) (owner (car (eieio-oref pkg (quote :owners))))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not ...) (spacemacs-buffer/message ...) (spacemacs-buffer/message ...) (condition-case err ... ...)))))) (eieio-oref pkg (quote :pre-layers))) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not ...) (spacemacs-buffer/message ...) (spacemacs-buffer/message ...) (condition-case err ... ...)))))) (eieio-oref pkg (quote :post-layers))))
  configuration-layer//configure-package([eieio-class-tag--cfgl-package evil nil (spacemacs-bootstrap) nil (ivy emacs-lisp) elpa t bootstrap nil t nil])
  (cond ((eq (quote dotfile) (car (eieio-oref pkg (quote :owners)))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))
  (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons ... load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq (quote local) location) (eq (quote dotfile) (car ...))) (setq load-path (cons (file-name-as-directory ...) load-path))) ((eq (quote local) location) (let* ((owner ...) (dir ...)) (setq load-path (cons ... load-path)))))) (if (memq (eieio-oref pkg (quote :location)) (quote (local site built-in))) nil (configuration-layer//activate-package pkg-name)) (cond ((eq (quote dotfile) (car (eieio-oref pkg (quote :owners)))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))
  (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path ...) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq ... location) (eq ... ...)) (setq load-path (cons ... load-path))) ((eq (quote local) location) (let* (... ...) (setq load-path ...))))) (if (memq (eieio-oref pkg (quote :location)) (quote (local site built-in))) nil (configuration-layer//activate-package pkg-name)) (cond ((eq (quote dotfile) (car (eieio-oref pkg ...))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg))))))
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ...))) (cond ((stringp location) (if ... ... ...)) ((and ... ...) (setq load-path ...)) ((eq ... location) (let* ... ...)))) (if (memq (eieio-oref pkg (quote :location)) (quote (local site built-in))) nil (configuration-layer//activate-package pkg-name)) (cond ((eq (quote dotfile) (car ...)) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg ...))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location ...)) (cond (... ...) (... ...) (... ...))) (if (memq (eieio-oref pkg ...) (quote ...)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq ... ...) (spacemacs-buffer/message ...)) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2((async bind-key bind-map diminish evil hydra use-package which-key))
  configuration-layer//configure-packages((abbrev ac-ispell ace-link ace-window adaptive-wrap aggressive-indent anaconda-mode ansi-colors archive-mode async auctex auctex-latexmk auto-compile auto-complete auto-dictionary auto-highlight-symbol auto-yasnippet avy bind-key bind-map bookmark bracketed-paste cc-mode centered-buffer-mode centered-cursor clang-format clean-aindent-mode cmake-mode coffee-mode column-enforce-mode comint company company-anaconda company-auctex company-c-headers company-quickhelp company-statistics company-tern conf-mode counsel counsel-projectile cython-mode default-helm-config default-ivy-config default-org-config define-word desktop diminish dired dired-x ...))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/max/.emacs.d/init.el" nil t)  ; Reading at buffer position 1270
  load-with-code-conversion("/home/max/.emacs.d/init.el" "/home/max/.emacs.d/init.el" t t)
  load("/home/max/.emacs.d/init" t t)
  #[0 "\205\266
```

**Comment by jackkamm** [comment] 2017-02-04 09:12
I would like to report I am having this problem as well since I updated develop branch 5 minutes ago.

**Comment by korayal** [comment] 2017-02-04 21:49
the issue is with that new toggle not having a default value inside `layers/+distributions/spacemacs-base/local/hybrid-mode/hybrid-mode.el` file.

If you use your own defaults as stated in the spacemacs readme file you can bypass this issue. 

replace:
```
   dotspacemacs-editing-style 'hybrid
```
with:
```
   dotspacemacs-editing-style '(hybrid :variables
                                  hybrid-mode-enable-evilified-state t
                                  hybrid-mode-enable-hjkl-bindings nil
                                  hybrid-mode-use-evil-search-module nil
                                  hybrid-mode-default-state 'normal)
```

I'm sure this will be fixed in the next commit, but for those that do not want to wait, this is the fastest fix.

**Comment by nixmaniack** [comment] 2017-02-05 08:15
The variable is defined in `spacemacs-base` and I think it's not available in `spacemacs-bootstrap` where it's being used _due to load ordering_.

**Comment by syl20bnr** [comment] 2017-02-07 22:00
Fixed in develop.

**Closed by syl20bnr** 2017-02-07 22:00 UTC
Labels: - Bug tracker -, Evil, Hybrid style, Regression :-(
