### ISSUE TITLE
:skip-install doesn't seem to work

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#4661] opened 2016-01-18 13:08 UTC
After updating to latest develop, we have access to `:skip-install` which should skip installation of package if non-nil. This is set for mu4e package still I get following error.

```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: mu4e@mu4e... [1/1]
Package mu4e is unavailable. Is the package name misspelled?
```

Repro steps: Update packages from spacehome, restart emacs(you should have mu4e in your enabled layers).

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. a8ce785)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" :disabled-for org erc)
 semantic better-defaults emacs-lisp
 (git :variables git-gutter-use-fringe t git-magit-status-fullscreen nil)
 github markdown yaml shell
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.emacs.d/private/elfeed.org"))
 lua python ruby ruby-on-rails
 (clojure :variables clojure-enable-fancify-symbols t)
 shell-scripts html javascript eyebrowse spacemacs-layouts
 (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e/")
 nix-mu4e gnus colors deft finance
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 version-control ansible emoji ranger osx typography
 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
 org)
```

**Comment by nixmaniack** [comment] 2016-01-18 13:10
Although mu4e starts even after error. 

Going back to old hack of `:location built-in` is current workaround just to get rid of that error.

**Comment by syl20bnr** [comment] 2016-01-19 05:00
I cannot reproduce it, `:skip-install` works as expected here event after updating. Do you have a personal layer referencing mu4e ?

**Comment by nixmaniack** [comment] 2016-01-19 08:28
Yes, I do have personal layer (with quite a bit of configuration) and I have added :skip-install to it as well. 
```
Still facing the error. 
But in the error it says it's originating from mu4e layer.

**Comment by StreakyCobra** [comment] 2016-01-19 09:12
I only use the mu4e layer and I also have this behavior.

**Comment by TheBB** [comment] 2016-01-21 15:41
The real problem here is that the org layer defines the `mu4e` package, which overwrites the `:skip-install` of the `mu4e` layer.

I fixed this in https://github.com/syl20bnr/spacemacs/pull/4727 and I believe this is the *proper* solution to this problem.

**Comment by syl20bnr** [comment] 2016-01-26 06:29
Fixed in develop.

**Closed by syl20bnr** 2016-01-26 06:29 UTC
Labels: bug :-(, Fixed in develop, Loading
