### ISSUE TITLE
Error in which-key--update introduced by setting which-key-allow-multiple-replacements in commit 3dd753945

### ISSUE THREAD

**Issue by jgracin** [syl20bnr/spacemacs#12008] opened 2019-02-21 13:00 UTC
#### Description :octocat:

When leader key is set to TAB, which-key throws:
Error running timer ‘which-key--update’: (wrong-type-argument arrayp nil)

This does not happen when leader key is the default SPC.

The problem is introduced by commit 3dd753945 which sets
which-key-allow-multiple-replacements.

Here are my settings related to leader key:
```
   dotspacemacs-leader-key "<tab>"
   dotspacemacs-emacs-command-key "SPC"
   dotspacemacs-ex-command-key ":"
   dotspacemacs-emacs-leader-key "<tab>"
   dotspacemacs-major-mode-leader-key nil
```

#### Reproduction guide :beetle:

- Set leader key to TAB in .spacemacs `(dotspacemacs-leader-key "<tab>")`
- Start Emacs
- Press TAB

*Observed behaviour:* :eyes: :broken_heart:

The following error gets reported in the minibuffer:
Error running timer ‘which-key--update’: (wrong-type-argument arrayp nil)

*Expected behaviour:* :heart: :smile:

Excpected to see the regular which-key list of bindings.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(swift restclient asciidoc latex python docker csv html typescript ruby javascript yaml
       (clojure :variables clojure-enable-clj-refactor t)
       helm auto-completion better-defaults emacs-lisp git markdown org
       (ibuffer :variables ibuffer-group-buffers-by 'projects)
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       spell-checking syntax-checking version-control pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("<\\([[:alnum:]-]+\\)>" "\\1" nil t)
  which-key--maybe-replace(("<tab> 2" . "winum-select-window-2") [tab])
  which-key--format-and-replace((("SPC" . "helm-M-x") ("TAB" . "spacemacs/alternate-buffer") ("!" . "shell-command") ("'" . "spacemacs/default-pop-shell") ("*" . "spacemacs/helm-project-smart-do-search-region-or-symbol") ("/" . "spacemacs/helm-project-smart-do-search") ("0" . #("treemacs-select-window" 0 22 (button (t) category default-button face which-key-command-description-face help-echo "Select the treemacs window if it is visible. Bring it to the foreground if it is not visible. Initialize..."))) ("1" . "winum-select-window-1") ("2" . "winum-select-window-2") ("3" . "winum-select-window-3") ("4" . "winum-select-window-4") ("5" . "winum-select-window-5") ("6" . "winum-select-window-6") ("7" . "winum-select-window-7") ("8" . "winum-select-window-8") ("9" . "winum-select-window-9") (";" . "evilnc-comment-operator") ("?" . "helm-descbinds") ("`" . "winum-select-window-by-number") ("a" . "Prefix Command") ("b" . "Prefix Command") ("C" . "Prefix Command") ("c" . "Prefix Command") ("e" . "Prefix Command") ("F" . "Prefix Command") ("f" . "Prefix Command") ("g" . "Prefix Command") ("h" . "Prefix Command") ("i" . "Prefix Command") ("j" . "Prefix Command") ("k" . "Prefix Command") ("l" . "lazy-helm/spacemacs/layouts-transient-state/body") ("m" . "spacemacs-spacemacs/report-issue-mode-map-prefix") ("N" . "Prefix Command") ("n" . "Prefix Command") ("o" . "Prefix Command") ("p" . "Prefix Command") ("q" . "Prefix Command") ("r" . "Prefix Command") ("S" . "Prefix Command") ("s" . "Prefix Command") ("T" . "Prefix Command") ("t" . "Prefix Command") ("u" . "universal-argument") ("v" . "er/expand-region") ("w" . "Prefix Command") ("x" . "Prefix Command") ("z" . "Prefix Command") ("²" . "winum-select-window-by-number") ("<f1>" . "lazy-helm/helm-apropos")) [tab] nil)
  which-key--get-bindings([tab] nil nil)
  which-key--create-buffer-and-show([tab])
  which-key--update()
  apply(which-key--update nil)
  timer-event-handler([t 0 0 400000 t which-key--update nil idle 0])
```

**Comment by gcentauri** [comment] 2019-02-22 15:55
I can confirm that I have the same issue with my leader key set to `<prior>` (page-up)

**Comment by gcentauri** [comment] 2019-02-22 21:47
I did a bit of digging into this bug and found that the function `which-key--maybe-replace` ends up setting the `key-binding` to `nil` rather than ignoring it as it looks like it is intended to do.  The documentation for the `which-key-replacement-alist` says

> If REPLACEMENT is anything other than a cons cell (and non nil) the key binding is ignored by which-key.

In the spacemacs code that is populating the `which-key-replacement-alist` we have this:

```
;; Hide the entries for M-[2-9] in the SPC h k Top-level bindings,
;; and for [2-9] in the SPC- Spacemacs root
  (push '((nil . "winum-select-window-[2-9]") . t)
        which-key-replacement-alist)
```

That value of `t` as the `cdr` of the list entry should cause the replacement to be ignored, which must work fine when the leader key isn't remapped.  However, something is happening in the `dolist` loop of `which-key--maybe-replace` that ends up setting the `key-binding` string to nil because all of the conditions fail on the first loop.  The second time through, this branch is triggered:

```
(cond ((and (caar repl) (cadr repl))
                               (replace-regexp-in-string
                                (caar repl) (cadr repl) (car key-binding) t))
                              ((cadr repl) (cadr repl))
                              (t (car key-binding)))
```

`(car key-binding)` is nil and causes the error in `replace-regexp-in-string`

**Comment by gcentauri** [comment] 2019-02-25 20:31
The maintainer of `which-key` made a change that fixes this bug to me in this commit that is now in `master` https://github.com/justbur/emacs-which-key/commit/3b184d6f0c78231f9e6c2ed95c2e8d218ae56fb8

**Comment by jgracin** [comment] 2019-02-26 05:41
@gcentauri It works for me too!  Thanks Grant and everybody involved!

**Comment by gcentauri** [comment] 2019-02-26 23:10
@jgracin I think you can close this issue now :)

I'm not actually a maintainer, so I can't do anything with the actual ticket.

**Closed** 2019-02-27 06:02 UTC
