### ISSUE TITLE
ruby-on-rails layer is broken when turning on projectile-rails

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2748] opened 2015-08-25 00:17 UTC
```
projectile-rails-on: Symbol's value as variable is void: hydra-projectile-rails-find
Error in post-command-hook (projectile-global-mode-check-buffers): (void-variable hydra-projectile-rails-find)

```

**Comment by syl20bnr** [comment] 2015-08-25 17:53
Seems to be an issue upstream, the dependency on hydra may not have been added to the package.

**Comment by syl20bnr** [comment] 2015-08-25 17:54
See last commits here: https://github.com/asok/projectile-rails/commits/master

**Comment by TheBB** [comment] 2015-10-04 17:15
I wasn't able to reproduce this myself. Hydra seems to be installed as a dependency of something else I have. If nobody wants to report upstream I'm closing this.

**Closed by TheBB** 2015-10-04 17:15 UTC
Labels: bug :-(, Install, package, Ruby
