### ISSUE TITLE
messed up evil bindings when minibuffer looses focus

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#10869] opened 2018-06-13 11:38 UTC
If I start a search with `/` and the minibuffer looses focus, e.g. by clicking into one of the open buffers, the evil key binding get messed up, e.g. `d` deletes an entire line instead of `dd`.
This can be fixed simply by clicking into the minibuffer and pressing `C-g`, but this can be annoying at times.

Edit: I am on Emacs 26.1.1 and the Spacemacs develop branch.

**Comment by ljupchokotev** [comment] 2018-06-13 14:01
This is a known bug, see #10410 for a workaround.

**Comment by syl20bnr** [comment] 2018-06-14 05:11
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/10410

**Closed by syl20bnr** 2018-06-14 05:11 UTC
Labels: - Bug tracker -, Duplicate ☝
