### ISSUE TITLE
Evil insert mode keybindings won't work with `ivy-wgrep-change-to-wgrep-mode`

### ISSUE THREAD

**Issue by Andre0991** [syl20bnr/spacemacs#11006] opened 2018-07-06 21:20 UTC
#### Description :octocat:
It's not possible to use insert mode after entering `ivy-wgrep-change-to-wgrep-mode`.

This functionally is described in https://sam217pa.github.io/2016/09/11/nuclear-power-editing-via-ivy-and-ag/.

#### Reproduction guide :beetle:
Assuming that Ivy is used:

- `SPC s s`
- `C-o o` (`ivy-occur`)
- `SPC SPC ivy-wgrep-change-to-wgrep-mode`

*Observed behaviour:* :eyes: :broken_heart:
Use `i` to go to insert mode - it won't work. Same for `q` (start recording a macro) and others
Also, the buffer is not editable.

*Expected behaviour:* :heart: :smile:
Evil keybindings work and we can edit the buffer and persist it.

I tried to use `evilified-state-evilify-map`, but it didn't work properly.
#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 666671a88)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(clojure common-lisp emacs-lisp erc git github html ivy javascript markdown org osx plantuml shell-scripts scala spacemacs-layouts syntax-checking themes-megapack theming version-control
         (shell :variables shell-default-shell 'eshell)
         (elfeed :variables rmh-elfeed-org-files
                 (list "~/Dropbox/backup/emacs/elfeed-feeds.org"))
         (c-c++ :variables c-c++-enable-clang-support t)
         (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil :disabled-for latex)
         (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t)
         andre-common-lisp andre-elfeed andre-erc andre-eww andre-ivy nov)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by bmag** [comment] 2018-07-09 07:42
Thanks for the report. Marking as duplicate of #10290, should be fixed in develop now. 

This is a good bug report, but in the future, in the observed behavior it is more helpful to write what DOES happen when something doesn't work. For example:
> Use `i` to go to insert mode - it won't work.

That's good, but what did happen? In this case the minibuffer shows a "i is undefined" message, which is meaningful information that can help me understand the problem.

Thanks again for the report.

**Closed by bmag** 2018-07-09 07:42 UTC

**Comment by Andre0991** [comment] 2018-07-09 15:15
Sorry for omitting the actual error.

It works now, thanks!
