### ISSUE TITLE
IPython 5 will cause problems.

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#6580] opened 2016-07-14 13:21 UTC
IPython5 is no longer using `readline` and they have basically dropped emacs `inferior shell` support.
See the last paragraph [here](http://ipython.readthedocs.io/en/stable/whatsnew/version5.html#id1) as well as the discussion in https://github.com/ipython/ipython/issues/9725 

When I have more time to look into this we might have to change a few settings in spacemacs. It seems that we might have to do something like https://github.com/jorgenschaefer/elpy/issues/908 or drop ipython support for the moment.

**Comment by tacaswell** [comment] 2016-07-14 16:36
https://github.com/matplotlib/matplotlib/pull/6734  will make the event loop integration much more automatic.  It should be v2.0 which should be released 'soon'.

**Comment by cpaulik** [comment] 2016-07-14 17:37
@tacaswell how does this relate to emacs support?

**Comment by tacaswell** [comment] 2016-07-14 17:50
Because the event loop integration was happen by chance because some of the qui frameworks register them selves into the inputhook that the readline based code looks at.

With the move away from readline you will need manually do the integration with the new IPython event loop.  That mpl PR makes the setup automatic.

**Comment by cpaulik** [comment] 2016-07-14 18:02
Aha, I have no idea how this all works. But this fix would only apply if matplotlib is imported?

**Comment by TheBB** [comment] 2016-07-15 18:43
It does seem peculiar that a matplitlib PR should fix an ipython issue…

**Comment by tacaswell** [comment] 2016-07-15 19:03
This was linked to from an issue related to mpl integration with ipython, I am probably a bit confused.

**Comment by ThatGeoGuy** [comment] 2016-07-20 22:12
If you don't all mind me chiming in, I think the problem may actually be solvable once the matplotlib folks remove whatever event loop stuff they've done to hook into the IPython readline. The issue referenced (which I filed) though seemed to be caused by not being able to use `jupyter console` within Emacs once I upgrade to IPython / jupyter-console 5.0. 

By default IPython will work in Emacs, provided you set the following: 

```elisp
(setq-default python-shell-interpreter "ipython"
              python-shell-interpreter-args "")
```

I think these are the defaults from the layer anyways in Spacemacs, so I don't think anything has to be done. The problem then, is using Emacs this way has traditionally meant that you can't use any of the matplotlib integrations, because the event loop would be tied to the process inside Emacs, and then any figures you load would lock up the event loop / process. To work around this, in the past you could get by with setting the following: 

```elisp
(setq-default python-shell-interpreter "jupyter"
              python-shell-interpreter-args "console")
```

This meant that jupyter would spawn a process separate from Emacs, and then Emacs would just hook into a console that fed the jupyter kernel with whatever you wanted to run. Since the event loop ran in the kernel, it didn't race / block the Emacs process, and since neither of them were touching one another, everything with matplotlib ran smoothly. Eventually, this led to the upgrade to IPython / jupyter-console 5.0, which meant that using a jupyter-console kernel to run your IPython code broke (see [my original issue](https://github.com/ipython/ipython/issues/9725)). 

I guess I can wait and see when matplotlib2.0 ships and see if this fixes any issues with the event loops and Emacs and report back, but so far I don't know if this will actually fix anything. I would expect the bigger fix would be to support running a jupyter-console kernel from inside Emacs. This could have other implications too, such as being able to hook into the same kernel from a Jupyter Notebook and Emacs at the same time, or hooking Emacs up to a jupyter-console kernel that doesn't run on the local machine. These would be cool features, even if they would be unlikely to be used by most users.

Another cool thing if jupyter-console still worked, is that it would be pretty trivial for developers to add other language REPLs to Emacs through jupyter just by loading a different kernel config (Julia, Haskell, etc.) when calling the shell interpreter command. In any case, I guess I don't really care too much about that sort of thing, but the idea itself seems to have some merit, so I thought I should mention it.

**Comment by tacaswell** [comment] 2016-07-21 13:33
> If you don't all mind me chiming in, I think the problem may actually be solvable once the matplotlib folks remove whatever event loop stuff they've done to hook into the IPython readline.

mpl is doing no explicit event loop integration, that has always been delegated to down stream packages.  Some of the GUI event loops registered them selves with `PyOS_InputHook` which is in turn used by the readline.  A change in 2.0 will be if `IPython` is in `sys.modules` when `pyplot` is imported, it will automatically ask `IPython` to do it's event loop integration. 

> The problem then, is using Emacs this way has traditionally meant that you can't use any of the matplotlib integrations, because the event loop would be tied to the process inside Emacs, and then any figures you load would lock up the event loop / process.

You just have to run `%matplotlib` (which tells IPython to _do_ the event loop integration) and everything works correctly.

> I guess I can wait and see when matplotlib2.0 ships and see if this fixes any issues with the event loops and Emacs and report back,

you can install beta3 now via  `pip install --pre matplotlib` or  `conda install -c conda-forge/label/rc -c conda-forge matplotlib` .  It is labeled a beta, but is functionally stable.

**Comment by ThatGeoGuy** [comment] 2016-07-21 15:34
> You just have to run `%matplotlib` (which tells IPython to do the event loop integration) and everything works correctly.

Unfortunately this is not the case on Windows. On Linux, I agree, this works and is not a problem. However on Windows calling `%matplotlib` and then attempting to plot something causes the figure window to hang. This eventually kills the Python process inside Emacs, without even plotting the data or allowing you to recover from the error.

**Comment by ThatGeoGuy** [comment] 2016-09-21 15:26
Hi @TheBB I noticed that this is "Fixed in develop" now. How long does that take before it lands in stable / master? Is more testing needed on Windows to make it land faster?

**Comment by cpaulik** [comment] 2016-09-21 15:40
The fixed in develop refers to the original problem of Ipython readline support. And even that is not fixed for all cases. AFAIK we have not done anything for matplotlib/jupyter support.

**Comment by d12frosted** [comment] 2016-10-03 07:49
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 07:49 UTC
Labels: - Mailling list -, Fixed in develop, Python

**Comment by shelper** [comment] 2017-02-09 17:43
i dont think it is fixed on windows platform.

**Comment by ThatGeoGuy** [comment] 2017-02-09 18:51
Indeed. Confirmed with Windows today and this does not fix it. I have yet to test with Linux.

**Comment by shelper** [comment] 2017-05-15 14:41
does jupyter 6.0 solve this issue?

**Comment by cpaulik** [comment] 2017-05-15 15:19
It might solve it. See http://ipython.readthedocs.io/en/stable/whatsnew/version6.html#configurable-terminalinteractiveshell-readline-interface and the https://github.com/ipython/rlipython project. But I have tested neither.

**Comment by jinyangustc** [comment] 2017-07-13 15:56
@cpaulik I've tested with "rlipython" on Python 3.6.0 and IPython 6.1.0, it works well. Just change the `python-shell-interpreter-args` to `-i`. I've opened a PR #9223.

**Comment by shelper** [comment] 2017-09-27 21:19
i dont think the rlipython + ipython 6.x solves the issue. on my windows machine, when i enable rlipython, i got ipython shell prompt error and matplotlib still hangs when plot a figure
![image](https://user-images.githubusercontent.com/546163/30938443-05d51ca6-a3a8-11e7-86c0-51ec884d7bc1.png)
