### ISSUE TITLE
Layouts are always assigned #1

### ISSUE THREAD

**Issue by Linuus** [syl20bnr/spacemacs#9544] opened 2017-09-05 17:52 UTC
#### Description :octocat:
When creating a new Layout, both using `SPC p l` and `SPC l <number>`, it's always assigned the number 1.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC l 2`
- Press y
- Enter a layout name

*Observed behaviour:* :eyes: :broken_heart:
The new layout gets assigned the number 1 instead of 2.

*Expected behaviour:* :heart: :smile:
The new layout gets assigned the number 2.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 3208cc9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion dash elixir emacs-lisp erlang
                 (elfeed :variables rmh-elfeed-org-files
                         (list "..."))
                 git ivy html javascript latex lua
                 (markdown :variables markdown-live-preview-engine 'vmd)
                 org org-page osx react restclient ruby ruby-on-rails rust syntax-checking themes-megapack version-control yaml
                 (erc :variables erc-server-list
                      '((...)))
                 (shell :variables shell-default-shell 'eshell shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by agzam** [comment] 2017-09-06 17:35
This I think is upstream issue in persp-mode.el. It appears broken since they added `persp-name-cache` https://github.com/Bad-ptr/persp-mode.el/commit/5e6b41257cd7ab5c2c386d7b0a7b8d2e2025a61d

**Comment by Bad-ptr** [comment] 2017-09-06 18:02
Can you say the name of a function bound to `SPC p l` or `SPC p <number>`.
And cast @bmag.)

**Comment by bmag** [comment] 2017-09-07 10:58
Does https://github.com/syl20bnr/spacemacs/commit/f221d7ed7308d029bb302757161ec51853c461b2 fix the issue?

**Comment by bmag** [comment] 2017-09-07 13:58
Never mind, the commit I linked is irrelevant.

**Comment by agzam** [comment] 2017-09-07 17:10
@Bad-ptr this is what's bound to `SPC l <number>`

```
(defun spacemacs/layout-switch-by-pos (pos)
  "Switch to perspective of position POS.
If POS has no layout, and `dotspacemacs-auto-generate-layout-names'
is non-nil, create layout with auto-generated name. Otherwise,
ask the user if a new layout should be created."
  (let ((persp-to-switch
         (nth pos (persp-names-current-frame-fast-ordered))))
    (if persp-to-switch
        (persp-switch persp-to-switch)
      (let ((persp-reset-windows-on-nil-window-conf t)
            (generated-name (and dotspacemacs-auto-generate-layout-names
                                 (spacemacs//generate-layout-name pos))))
        (cond
         (generated-name
          (persp-switch generated-name))
         ((y-or-n-p (concat "Layout in this position doesn't exist. "
                            "Do you want to create one? "))
          (persp-switch nil)
          (spacemacs/home-delete-other-windows)))))))
```

**Comment by ynilu** [comment] 2017-09-07 17:14
I think the cause of this issue is that the new persp name we created is pushed to the FRONT of `persp-names-cache` in `persp-add-to-menu`. When reading out all persps, it just return the persps in the order in `persp-names-cache`. I am not sure this is the expected behavior or a bug.

**Comment by ynilu** [comment] 2017-09-07 17:19
```
(defun persp-add-to-menu (persp)
  (let ((name (safe-persp-name persp)))
    (push name persp-names-cache)
    (lexical-let ((str_name name))
      (easy-menu-add-item persp-minor-mode-menu nil
                          (vector str_name #'(lambda () (interactive)
                                               (persp-switch str_name))))
      (when persp
        (easy-menu-add-item persp-minor-mode-menu '("kill")
                            (vector str_name #'(lambda () (interactive)
                                                 (persp-kill str_name))))))))
```
Change `(push name persp-names-cache)` to `(add-to-list 'persp-names-cache name t)`.
Append the name to the back and layout just work as usual.

**Comment by Bad-ptr** [comment] 2017-09-07 17:24
> Change (push name persp-names-cache) to (add-to-list 'persp-names-cache name t)

Hah, really. This may be the proper fix.

**Comment by Bad-ptr** [comment] 2017-09-07 17:34
Can somebody test the [persp-mode.el develop branch](https://github.com/Bad-ptr/persp-mode.el/tree/develop) ?

**Comment by Bad-ptr** [comment] 2017-09-07 18:39
No one? He-he, well i'll not torture you by testing. Merged to master.

**Comment by ynilu** [comment] 2017-09-07 18:55
I tried... but it's strange...
I tried to use `persp-load-state-from-file` and it turns out that the order is mess up.
If append with `(add-to-list 'persp-names-cache name t)`, the order is correct.

**Comment by agzam** [comment] 2017-09-08 07:57
Seems it's fixed. Let's wait for a few days, and if no objections, this ticket may be closed.

**Comment by Linuus** [comment] 2017-09-08 08:03
Works for me as well now! Thanks! ❤️

**Comment by bmag** [comment] 2017-09-10 16:50
@Bad-ptr thanks for the fix. Is there a guarantee that `persp-names-cache`/`persp-names-current-frame-fast-ordered` will remain sorted from oldest to newest in the future as well? (as long as the user doesn't customize it through hooks)

**Closed** 2017-09-10 16:51 UTC
Labels: - Bug tracker -, Fixed upstream, Spacemacs Layouts

**Comment by Bad-ptr** [comment] 2017-09-10 16:57
> Is there a guarantee

`¯\_(ツ)_/¯`
I have no plans to change it.

**Comment by agzam** [comment] 2017-09-10 21:43
Anyone is brave enough to add "move layout right/left" functions to `spacemacs/layouts-transient-state`?
Maybe bind them to `<` and `>`?
What do you guys think?

**Comment by bmag** [comment] 2017-09-11 05:24
@agzam with current implementation (that could change in the future ☹️), it's just a matter of moving an entry in `persp-names-cache` left or right. Using `<` and `>` is good.

**Comment by Linuus** [comment] 2017-09-11 08:35
This sounds like a neat feature. I'd like to give it a shot as soon as I get some time (in a few days probably).

I don't know much elisp but I want to learn and this seems to be easy enough for me to get started 😄

**Comment by agzam** [comment] 2017-10-21 00:10
This is my attempt of implementing sliding to left/ to right (if anyone interested):

    (defun -slide-item (l e dir)
      "Slides item E in list L to the right or left position
    DIR - is positive or negative number (relative to the position of E). Item can't exceed boundaries of the list - e.g. if given DIR value larger than length of the list - item becomes the last.
    "
      (let* ((c-pos (-elem-index e l)))
        (if c-pos
            (let* ((f (cond ((<= (- (length l) 1) dir) (- (length l) 1))
                            (t dir)))
                  (new-p (+ c-pos f)))
              (-insert-at new-p e (-remove-at c-pos l))) l)))

    (defun persp-slide-to-left ()
      (interactive)
      (setq persp-names-cache (-slide-item persp-names-cache persp-last-persp-name -1))
      (spacemacs/layouts-transient-state/body))

    (defun persp-slide-to-right ()
      (interactive)
      (setq persp-names-cache (-slide-item persp-names-cache persp-last-persp-name 1))
      (spacemacs/layouts-transient-state/body))

    (define-key spacemacs/layouts-transient-state/keymap (kbd "<") #'persp-slide-to-left)
    (define-key spacemacs/layouts-transient-state/keymap (kbd ">") #'persp-slide-to-right)

**Comment by bmag** [comment] 2017-10-21 13:27
#9591 is now merged, thanks for the reminder @agzam. To add keybindings to a TS you need to call `spacemacs/transient-state-register-add-bindings`, by the way.

**Comment by agzam** [comment] 2017-10-21 18:44
@bmag oh cool! thanks!
