### ISSUE TITLE
(Spacemacs) Error in dotspacemacs/user-config: Cannot open load file: No such file or directory, mu4e-org

### ISSUE THREAD

**Issue by HanshenWang** [syl20bnr/spacemacs#14275] opened 2021-01-08 09:35 UTC
#### Description :octocat:
Develop Commit number ab4877f218def9ad1d90a1b625db6ff44c394286 breaks mu4e layer

I get the error message upon startup:

(Spacemacs) Error in dotspacemacs/user-config: Cannot open load file: No such file or directory, mu4e-org

#### Reproduction guide :beetle:
- Start Emacs
- Enable mu4e layer with these 2 variables (as seen in the mu4e layer docs, this issue occurred to me only after the following was set)
  (setq-default dotspacemacs-configuration-layers
                '((mu4e :variables
                        mu4e-org-compose-support t)))

(defun dotspacemacs/user-config ()
(setq org-mu4e-convert-to-html t))
- Reload Emacs
- Error message shows upon starting emacs

Please note that I using ubuntu 20.04 with version 1.2.0 of mu.

Also removing the commit returns things to normal. It wasn't until I tried the feature org-mu4e that this problem occurs. In my steps to solve the problem I have also tried nuking the .emacs.d folder. My current .spacemacs.d also works fine with the mu4e layer disabled. Reverting the line 156 in the package.el was the only thing that worked.

Specifically, line 156 of the mu4e packages.el layer:
(require 'mu4e-org)

to

(require 'org-mu4e)

*Observed behaviour:* :eyes: :broken_heart:
Attempting to start mu4e =SPC a e m=, will return this error and mu4e will not start:

Eager macro-expansion failure: (file-missing "Cannot open load file" "No such file or directory" "mu4e-org") [2 times]

*Expected behaviour:* :heart: :smile:
Able to use mu4e layer as normal :). Sorry, I'm still newish to github and spacemacs so I'm not sure about pushing the change myself.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bfed28d3c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults bibtex dap
                 (dash :variables dash-docs-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
                 (elfeed :variables rmh-elfeed-org-files
                         (list "~/Dropbox/project-maria/elfeed.org"))
                 emacs-lisp emoji erc finance git helm helpful html
                 (javascript :variables javascript-backend 'lsp)
                 (latex :variables latex-build-command "LatexMk")
                 lsp mu4e multiple-cursors
                 (org :variables org-want-todo-bindings t org-enable-org-journal-support t)
                 outshine pandoc pdf
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm)
                 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dbankmann** [comment] 2021-01-08 10:14
I can confirm this. For now, I'm just setting `(setq mu4e-org-link-support nil)` in my user-init (to avoid the problematic sections in the code)

**Comment by nickanderson** [comment] 2021-01-08 21:01
The change in https://github.com/syl20bnr/spacemacs/pull/14277 works for me.

**Comment by smile13241324** [comment] 2021-01-09 07:27
@HanshenWang great find, thanks for fixing 👍, I have merged your PR into develop, please double check if the issue is gone and close this ticket if it is.

**Comment by HanshenWang** [comment] 2021-01-09 18:34
https://github.com/syl20bnr/spacemacs/issues/13913 tells me its not a typo, either way mu4e-org-compose-support works fine for the most part @codetrick. Thank you for that feature. I have noticed "org-mu4e-convert-to-html" does not fully work with "mail-add-attachment", it will send the attachment fine, but also leave the lines containing <#part type>, <#/part>. For now I've been sticking to exporting with "org-mime-org-buffer-htmlize".

Happy to help. And cheers to Mr. Wolff and others for making spacemacs possible.

**Comment by codetrick** [comment] 2021-01-10 00:45
> #13913 tells me its not a typo, either way mu4e-org-compose-support works fine for the most part @codetrick. Thank you for that feature. I have noticed "org-mu4e-convert-to-html" does not fully work with "mail-add-attachment", it will send the attachment fine, but also leave the lines containing <#part type>, <#/part>. For now I've been sticking to exporting with "org-mime-org-buffer-htmlize".
> 
> Happy to help. And cheers to Mr. Wolff and others for making spacemacs possible.

Hi Hanshen,

I think your "fix" is actually a regression for newer versions of mu4e. As you might have realized, the `mu4e-org` feature is split into two starting at version 1.3.6. The proper way to fix this issue is to check for mu4e version, and if version < 1.3.6, load `org-mu4e` instead of `mu4e-org`.

```elisp
(with-eval-after-load 'org
        (require 'mu4e-meta)
        (if (version<= mu4e-mu-version "1.3.5")
            (require 'org-mu4e)
          (require 'mu4e-org))
        ;; We require mu4e due to an existing bug https://github.com/djcb/mu/issues/1829
        ;; Note that this bug prevents lazy-loading.
        (if (version<= mu4e-mu-version "1.4.13")
            (require 'mu4e))
        )
```

Could you reopen the issue and fix it properly?

**Comment by HanshenWang** [comment] 2021-01-10 07:26
Yessir. My bad, had a feeling I jumped the gun. Thanks for the snippet, everything works just peachy on my end.

**Comment by smile13241324** [comment] 2021-01-10 18:57
Merged, please retest.

**Comment by codetrick** [comment] 2021-01-11 00:26
Works for me. Thanks!

**Closed** 2021-01-12 01:03 UTC
