### ISSUE TITLE
Let me use common escape sequences of the movement keys.

### ISSUE THREAD

**Issue by aeschylus** [syl20bnr/spacemacs#2292] opened 2015-07-09 22:22 UTC
Hello. I am trying to get spacemacs to return to "normal mode" (in vim terms) when pressing "kj" in quick succession while in "insert mode". This is a very common vim configuration and I've become accustomed to it. I have tried an earlier suggestion to add "(define-key evil-insert-state-map "kj" 'evil-force-normal-state)", however, this obviously prevents me from typing the letter "k" (or anything after it) at all. Not the intended behaviour.

How can I cause the mode shift only if the keys are pressed in quick succession?

"jf" is another common one.

I have been told on the gitter channel that it is not possible to do with the movement keys.

**Comment by geo7** [comment] 2015-07-09 22:34
I'm guessing you've tried 
```lisp
  (setq-default evil-escape-key-sequence "kj")
```
as well. 

I've tried to use movement keys and had issues before (it was me on the chat for the information of others). AFAIK they can't be used without side effects, if there's any more information though that would be good to hear.

**Comment by kRITZCREEK** [comment] 2015-07-09 22:41
A quick google gave me this promising blog post: [keychord](http://blog.jenkster.com/2013/02/mapping-jk-in-emacs-evil-mode.html)

**Comment by geo7** [comment] 2015-07-10 21:37
@aeschylus just a note - if you use `ij` as your esc sequence things such as `dip` won't work properly. 

Seems evil can't process things like vim, no idea why what etc... hopefully someone else chimes in :)

**Comment by felipe-barros** [comment] 2015-07-10 21:46
As @kRITZCREEK said, Keychord looks a lot like the solution.

**Comment by geo7** [comment] 2015-07-10 21:52
@felipe-barros heard a few people say it's the solution, yet to hear someone say 'yeah I use this and it makes everything as expected'

**Comment by sooheon** [comment] 2015-07-11 06:09
evil-escape is built into spacemacs, no need to reinvent the wheel with keychord. It even escapes from "deeper" inside modes, like iedit-insert mode or whatever else.

**Comment by aeschylus** [comment] 2015-07-11 06:10
Yes, the default "fd" key sequence has a timeout associated with it. I am able to type "f", and if I wait more than about 200ms it will in fact insert the letter "f". Not so with (define-key evil-insert-state-map "kj" 'evil-force-normal-state).

**Comment by aeschylus** [comment] 2015-07-11 06:11
How would I use `evil-escape` instead of `define-key`?

**Comment by sooheon** [comment] 2015-07-11 06:13
`(setq-default evil-escape-key-sequence "kj")`

**Comment by aeschylus** [comment] 2015-07-11 06:24
Evil escape key apparently doesn't work with movement keys. Actually "ij" did not work for me either.

**Comment by sooheon** [comment] 2015-07-11 06:39
According to the [docs](https://github.com/syl20bnr/evil-escape/#first-key), `kj` should be fine to use. `ij` would not work. You should put this in dotspacemacs/init as explained [here](https://github.com/syl20bnr/evil-escape/#customization)

**Comment by felipe-barros** [comment] 2015-07-12 01:46
I'm trying to set `ht` as my escape sequence but then `h` movement stops working, so I have opened the issue in the Evil Escape page, but I guess this is the same bug.
https://github.com/syl20bnr/evil-escape/issues/32

**Comment by aeschylus** [comment] 2015-07-12 03:49
Yes, it does not work, regardless of where it is placed.

**Comment by nosami** [comment] 2015-07-12 04:16
fwiw, adding `(setq-default evil-escape-key-sequence "kj")` as the first line in init worked fine for me.

**Comment by felipe-barros** [comment] 2015-07-12 04:54
I have done what @nosami recommended @aeschylus , but it only worked after a restart. `SPC f e R` did not reload it.
So now I have `ht` escaping me and `h` stil moves left, but now it has a micro-lag.

**Comment by geo7** [comment] 2015-07-12 11:08
yeah the sequence generally works but it will create a lag or something which is really annoying and basically renders it unusable... On my system the sequence `ij` makes it so that I can't use something like `dip` to delete in a paragraph.

**Comment by aeschylus** [comment] 2015-07-13 19:14
Yes, it interferes with other modes. I finally got "kj" working for general editing, but now in the evil file explorer (if you type `:e ./`, for instance), I can't use "k" to go up anymore.

**Comment by geo7** [comment] 2015-07-13 20:01
thought I'd add this here as It's relevant (i think?)

I have mapped esc in my init section of .spacemacs as follows : 

```
  (setq-default evil-escape-key-sequence "kj")
```

Now if I want to move 8 lines up i can't use `8k`. 

I'm not sure if anyone else has this issue

**Comment by geo7** [comment] 2015-07-13 20:28
Right this is really bugging me :P


I've just tried the `key-chord` thing and it didn't work for me - has anyone
**actually tried it** from this thread?

@felipe-barros when you mapped using `h` as the first key, did it retrict
movements such as `5h`?

@nosami when you say that it worked fine - did you have any lag / restrictions on what you could do?
I have tried `kj` and it prevented me from being able to do `8k` for example.

**Comment by aeschylus** [comment] 2015-07-13 20:39
I can confirm that commands like `10k` on longer work. It just moves the cursor up one line.

**Comment by geo7** [comment] 2015-07-13 21:14
@aeschylus cheers, of all the things **not** to be implemented properly in Evil! I'm not sure if this is an emacs or evil issue or what though

**Comment by geo7** [comment] 2015-07-14 10:09
OKOKOKOK try this please all : 

in `.spacemacs` there's a section called `dotspacemacs-additional-packages`, in there you should add the keychord package. I tried with M-x package install, which doesn't work as spacemacs will erase it on next startup (i think? correct me If I'm wrong)

So your additional packages section should look like this (maybe with others as well, I don't know your 
config ;) ): 


```
   ;; additional layers for spacemacs
   dotspacemacs-additional-packages '(
                                     key-chord
                                     )
```

Then in the `dotspacemacs/config` section add the following lines : 

```
  ;; ---------------------------------------------------------------------------
  ;; -------------------- REMAPPING THE ESC KEY WITH KEYCHORD ------------------
  (require 'key-chord)
  (key-chord-mode 1)
  (key-chord-define evil-insert-state-map  "jk" 'evil-normal-state)
  ;; ---------------------------------------------------------------------------
```

After restarting (or maybe `SPC f e R`, I restarted...) it *should* enable you to esc with `jk` **OR** `kj` and not get in the way of movements. 

Hope it works for you guys

@syl20bnr would be great to add this to the docs if it's a robust solution? I've only just set it up, so perhaps there are problems I haven't yet seen...

**Comment by felipe-barros** [comment] 2015-07-15 05:32
@geo7 followed your instructions and it worked fine for me. Escaping, no lag and have yet to find any issues.

**Comment by NotBrianZach** [comment] 2015-07-22 05:31
Also worked for me, thanks @geo7 ! Was driving me nuts as well.

**Comment by felipe-barros** [comment] 2015-07-22 07:25
I've found an apparent issue, where if I have defined `jk` or `ht`, the reverse also escapes: `kj` and `th`, in this example.

**Comment by TheBB** [comment] 2015-07-22 09:27
That's the intended behaviour of `key-chord`.

**Comment by cgag** [comment] 2015-08-04 23:52
@geo7 You're a hero.

Hopefully this ends up in the readme, I'd probably have stopped using spacemacs if I couldn't do this. Not being able to escape normally is such a big piece of friction for such an otherwise nice experience.

**Comment by syl20bnr** [comment] 2015-08-09 17:32
evil-escape was using key-chord at some point, unfortunately I could reliably CRASH emacs with it when configured to use `fd`, I don't recall exactly the repro steps but numeric prefix and search for a character were involved. Maybe they are some more info in the history of spacemacs and or evil-escape. Maybe it was a emacs bug, I don't know. Also the numerical prefixes were buggy with key-chord (look at the echo area).

For the lag thing, I'm surprised about the result, evil-escape should be less laggy, essentially in insert-state, in the other states it should be similar to key-chord.

Anyway I have a version 3 planned for evil-escape now I have better knowledge about how key maps work :-)

**Comment by geo7** [comment] 2015-08-09 17:37
@syl20bnr the `key-chord` solution was working fine for general editing until I updated about 10 minutes ago now it's just giving me the error 

```
dotspacemacs/config: Cannot open load file: no such file or directory, key-chord
```


I'm using it as 

```
  (require 'key-chord)
  (key-chord-mode 1)
  (key-chord-define evil-insert-state-map  "jk" 'evil-normal-state)
```



it's in 

```
   dotspacemacs-additional-packages '(
                                      key-chord
                                      )
```

and is in elpa 

```
┌─[vco @ geoHP]─[~/.emacs.d/elpa]─[18:14:04]
└─[$]› find -name '*chord*'
./key-chord-20150808.1705
./key-chord-20150808.1705/key-chord-pkg.el
./key-chord-20150808.1705/key-chord.el
./key-chord-20150808.1705/key-chord-autoloads.el
./key-chord-20150808.1705/key-chord.elc
./key-chord-20150808.1705/key-chord-pkg.elc

```

**Comment by syl20bnr** [comment] 2015-08-09 18:11
I will fixed as soon as I can, sorry for the inconvenient.

**Comment by syl20bnr** [comment] 2015-08-09 18:48
@geo7 should be OK now.

**Comment by geo7** [comment] 2015-08-09 23:55
@syl20bnr still not working here :/

What was changed?

**Comment by syl20bnr** [comment] 2015-08-10 01:51
I don't know what's going on with your config, I really fixed the issue and it works flawlessly here, I even retried it 3 times, no issue. What is you error ?

**Comment by StreakyCobra** [comment] 2015-11-16 18:55
As the problem have been solved upstream and nobody reported this issue the last 3 months, I'm closing it. Feel free open a new issue in case of troubles :relaxed:

**Closed by StreakyCobra** 2015-11-16 18:55 UTC
Labels: bug :-(, Evil-escape, package, Reported upstream

**Comment by cocodrino** [comment] 2015-12-27 20:41
Hi guys, I followed the steps from @geo7 but  for some reason the keybindings are not taken by spacemacs...that means, when I press jk in insert mode it doesn't change to normal mode, BUT the mode is running and if I evaluate this expresio M-:  (key-chord-define evil-insert-state-map  "jk" 'evil-normal-state) works, what could be the reason?..thanks!!!
