### ISSUE TITLE
ess layer breaks org-mode keybindings

### ISSUE THREAD

**Issue by leezu** [syl20bnr/spacemacs#7890] opened 2016-12-01 12:24 UTC
#### Description :octocat:
Enabling the `ess` layer breaks org-mode keybindings, such as `t` for `org-todo` (which changes the TODO state of an item).

I have verified this issue with a fresh spacemacs install containing only the `org` and `ess` layers.

#### Reproduction guide :beetle:
- Start Emacs
- Enable org layer and reload config
- Restart
- Make sure t works for org-todo
- Enable ess layer and reload config
- Restart
- t will not work anymore and is instead bound to evil-find-char-to

*Observed behaviour:* :eyes: :broken_heart:
- t will not work anymore and is instead bound to evil-find-char-to

*Expected behaviour:* :heart: :smile:
- t continues to work

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org ess)
```

**Comment by izahn** [comment] 2016-12-02 02:06
Pretty sure this is a symptom of a busted org loading process as reported in [several other issues](https://github.com/syl20bnr/spacemacs/search?utf8=%E2%9C%93&q=void-variable+org-babel-safe-header-args&type=Issues). It usually works for me to 

1. remove org if installed
2. remove org-plus-contrib
3. reinstall org-plus-contrib

**Comment by bmag** [comment] 2016-12-10 08:34
This bug report is missing some information:
> Make sure t works for org-todo

How do you make sure? How do you determine if it works? What are the exact steps?

**Comment by leezu** [comment] 2016-12-10 13:07
I mean make sure `org-todo` is bound to `t` and not any other function.

**Comment by bmag** [comment] 2016-12-10 13:39
I managed to repro this behavior, and indeed it is weird. For those wondering, here are the repro steps:
- have `org` and `ess` layers enabled and installed
- start Emacs
- open an Org file
- press `SPC h d k t`

Observed behavior: help buffer opens saying that "t runs the command evil-find-char-to".
Expected behavior: help buffer opens saying that "t runs the command org-todo".

**Comment by bmag** [comment] 2016-12-10 14:08
There is also an error in the echo-area when opening the org file (at first it was hidden from me by a later unrelated message). I turned on debug-on-error (before opening a new org file) and got this backtrace:
```
Debugger entered--Lisp error: (invalid-function org-babel-header-args-safe-fn)
  org-babel-header-args-safe-fn((:cache :colnames :comments :exports :epilogue :hlines :noeval :noweb :noweb-ref :noweb-sep :padline :prologue :rownames :sep :session :tangle :wrap (:eval "never" "query") (:results lambda (str) (not (string-match "file" str))) :width :height :bg :units :pointsize :antialias :quality :compression :res :type :family :title :fonts :version :paper :encoding :pagecentre :colormodel :useDingbats :horizontal))
  byte-code("\301\302\303\304!#\210\305\306\307\310\311DD\312\313\314\315\316\317\320&	\207" [ob-R-safe-header-args put org-babel-default-header-args:R safe-local-variable org-babel-header-args-safe-fn custom-declare-variable org-babel-R-command funcall function #[0 "\300\207" ["R --slave --no-save"] 1 "R --slave --no-save"] "Name of command to use for executing R code." :group org-babel :version "24.1" :type string] 10)
  require(ob-R)
  org-babel-do-load-languages(org-babel-load-languages ((python . t) (R . t) (clojure . t) (shell . t) (emacs-lisp . t)))
  spacemacs//org-babel-do-load-languages()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  set-auto-mode-0(org-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil nil t nil nil)
  revert-buffer--default(nil nil)
  revert-buffer(nil nil)
  spacemacs/safe-revert-buffer()
  funcall-interactively(spacemacs/safe-revert-buffer)
  call-interactively(spacemacs/safe-revert-buffer nil nil)
  command-execute(spacemacs/safe-revert-buffer)
```

I've managed to solve the problem by recompiling `ob-R.el`: I opened directory `elpa/org-plus-contrib-*` with `M-x dired`, went to `ob-R.el` and then pressed `B` to byte-compile the file. I agree with @izahn that it's "a symptom of a busted org loading process" or a symptom of a busted installation and compilation process.

**Comment by bmag** [comment] 2016-12-10 14:25
@leezu I'm assuming recompiling `ob-R.el` will fix your issue, so I'm closing this issue in favor of #4618. If recompiling doesn't help, feel free to go over the discussion in that PR to see what else you can try to fix the issue, and if you have new input you can post comments there.

**Closed by bmag** 2016-12-10 14:25 UTC
Labels: - Bug tracker -, ESS, Org
