### ISSUE TITLE
`toc-org` tests are failing

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#7259] opened 2016-10-03 17:53 UTC
#### Description :octocat:

`toc-org` seems to be including its tests into "global test scope". It should not.
its failing tests making it difficult to test other things
#### Reproduction guide :beetle:
- make sure `org-layer` is included 
- and `toc-org` package is not in `dotspacemacs-excluded-packages`
- Start Emacs
- `M-x` `ert-run-tests-interactively` `t`

_Observed behaviour:_ :eyes: :broken_heart:
What I'm seeing is - one of the toc-org tests failing.
These tests I believe should not be running at all (unless specifically running `ert` from their file)

_This is probably an upstream issue and I have created issue on package's github page as well_
#### Temporary solution:

Exclude `toc-org` package
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: develop (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(yaml
 (org :variables org-enable-reveal-js-support t)
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle)
 emacs-lisp javascript html markdown shell-scripts clojure lua react
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm
 (shell :variables shell-enable-smart-eshell t shell-default-term-shell "/bin/zsh")
 (deft :variables deft-directory "~/Google Drive/deft" deft-auto-save-interval 60)
 fasd ibuffer osx chrome
 (semantic :disabled-for emacs-lisp)
 restclient emoji ranger search-engine imenu-list pdf-tools docker git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :variables gist-view-gist t)
 agzam ag-dash synonyms)
```

**Comment by bmag** [comment] 2016-10-04 05:15
Can you post which toc-org tests are executed? I suspect at least part of the problem is that five tests are defined in `core/tools/spacefmt/toc-org.el`, instead of in a separate file:
- `toc-org-test-raw-toc`
- `toc-org-test-hrefify-gh`
- `toc-org-test-hrefify-toc`
- `toc-org-test-flush-subheadings`
- `toc-org-test-insert-toc`

**Comment by TheBB** [comment] 2016-10-04 07:41
> This is probably an upstream issue and I have created issue on package's github page as well

Link please: https://github.com/snosov1/toc-org/issues/34

**Comment by snosov1** [comment] 2016-10-04 09:29
Hey, there!

Just wanted to clarify a bit. If I understand it correctly, there are 2 issues here:

1. `toc-org` tests are being "added to global test scope", but they shouldn't.
2. one of the tests (`test-toc-org-insert-toc`) fails

Right?

For the first issue (again, if I understand it correctly), the reason is that I include the tests alongside the code, but I really should have them in a separate file. Can you, please, advise me a read about "conventional" approach to testing of Emacs packages (cause I'm a bit ignorant in this respect)?

For the second issue - I don't seem to be able to reproduce the fail on my side (I have 2 Emacs instances on my machines and a CI instance). Can you, please, provide a bit more details about the fail?

Thx!

**Comment by bmag** [comment] 2016-10-04 09:45
> Can you, please, advise me a read about "conventional" approach to testing of Emacs packages (cause I'm a bit ignorant in this respect)?

There is the basic [ERT manual](https://www.gnu.org/software/emacs/manual/html_node/ert/). More to the point, the section about [running tests in batch mode](https://www.gnu.org/software/emacs/manual/html_node/ert/Running-Tests-in-Batch-Mode.html#Running-Tests-in-Batch-Mode). For more heavyweight approaches, you can try [ert-runner](https://github.com/rejeep/ert-runner.el), [Ecukes](https://github.com/ecukes/ecukes) or [Buttercup](https://github.com/jorgenschaefer/emacs-buttercup).

**Comment by snosov1** [comment] 2017-01-26 08:59
Hey!

I've moved the tests into a separate file. It should solve the problem with `toc-org` tests loading unintentionally. https://github.com/snosov1/toc-org/issues/34

Are we good to close this issue?

**Comment by duianto** [comment] 2017-01-29 12:52
This change to `toc-org` might have caused `dotspacemacs/sync-configuration-layers` which is called by the <kbd>SPC f e R</kbd> key binding, to stop syncing the configuration layers. 

The messages buffer shows this message: 
`run-hooks: Symbol’s function definition is void: toc-org-enable`

I made a separate issue about it here:  #8258

**Closed** 2017-04-25 20:16 UTC
Labels: - Bug tracker -, Reported upstream
