### ISSUE TITLE
How to use mouse wheel in terminal ?

### ISSUE THREAD

**Issue by mushanshitiancai** [syl20bnr/spacemacs#4591] opened 2016-01-13 04:22 UTC
I use spacemacs in terminal. And when I use mouse wheel, it show:

    <mouse-4> is undefined
    <mouse-5> is undefined

How to config?Thank.

**Comment by agonzalezro** [comment] 2016-01-22 15:09
I've faced this issue (or misconfiguration) as well.

I am using vim mode and emacs in terminal inside tmux.

**Comment by StreakyCobra** [comment] 2016-01-22 15:45
I just tested `emacs -nw` within `urxvt` and scrolling seems to work fine here. Maybe it has something to do with the terminal emulator used, or with the emacs version.

**Comment by agonzalezro** [comment] 2016-01-22 15:50
Hi @StreakyCobra, thanks for the quick reply.

I've just opened the default terminal on Mac (before I was using iTerm2) and I got the same result. No tmux or iTerm2 involved in this test.

I have the latest spacemacs and I am using emacs `emacsGNU Emacs 25.1.50.1`.

This is my conf file in case it helps, pretty standard:

```
;; -*- mode: emacs-lisp -*-
;; This file is loaded by Spacemacs at startup.
;; It must be stored in your home directory.

(defun dotspacemacs/layers ()
  "Configuration Layers declaration.
You should not put any user code in this function besides modifying the variable
values."
  (setq-default
   ;; Base distribution to use. This is a layer contained in the directory
   ;; `+distribution'. For now available distributions are `spacemacs-base'
   ;; or `spacemacs'. (default 'spacemacs)
   dotspacemacs-distribution 'spacemacs
   ;; List of additional paths where to look for configuration layers.
   ;; Paths must have a trailing slash (i.e. `~/.mycontribs/')
   dotspacemacs-configuration-layer-path '()
   ;; List of configuration layers to load. If it is the symbol `all' instead
   ;; of a list then all discovered layers will be installed.
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     ;; org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     spell-checking
     syntax-checking
     version-control

     ansible
     chrome
     dockerfile
     javascript
     elixir
     emoji
     go
     html
     osx
     ruby
     )
   ;; List of additional packages that will be installed without being
   ;; wrapped in a layer. If you need some configuration for these
   ;; packages, then consider creating a layer. You can also put the
   ;; configuration in `dotspacemacs/user-config'.
   dotspacemacs-additional-packages '()
   ;; A list of packages and/or extensions that will not be install and loaded.
   dotspacemacs-excluded-packages
   '(
     smartparens
   )
   ;; If non-nil spacemacs will delete any orphan packages, i.e. packages that
   ;; are declared in a layer which is not a member of
   ;; the list `dotspacemacs-configuration-layers'. (default t)
   dotspacemacs-delete-orphan-packages t))

(defun dotspacemacs/init ()
  "Initialization function.
This function is called at the very startup of Spacemacs initialization
before layers configuration.
You should not put any user code in there besides modifying the variable
values."
  ;; This setq-default sexp is an exhaustive list of all the supported
  ;; spacemacs settings.
  (setq-default
   ;; If non nil ELPA repositories are contacted via HTTPS whenever it's
   ;; possible. Set it to nil if you have no way to use HTTPS in your
   ;; environment, otherwise it is strongly recommended to let it set to t.
   ;; This variable has no effect if Emacs is launched with the parameter
   ;; `--insecure' which forces the value of this variable to nil.
   ;; (default t)
   dotspacemacs-elpa-https t
   ;; Maximum allowed time in seconds to contact an ELPA repository.
   dotspacemacs-elpa-timeout 5
   ;; If non nil then spacemacs will check for updates at startup
   ;; when the current branch is not `develop'. (default t)
   dotspacemacs-check-for-update t
   ;; One of `vim', `emacs' or `hybrid'. Evil is always enabled but if the
   ;; variable is `emacs' then the `holy-mode' is enabled at startup. `hybrid'
   ;; uses emacs key bindings for vim's insert mode, but otherwise leaves evil
   ;; unchanged. (default 'vim)
   dotspacemacs-editing-style 'vim
   ;; If non nil output loading progress in `*Messages*' buffer. (default nil)
   dotspacemacs-verbose-loading nil
   ;; Specify the startup banner. Default value is `official', it displays
   ;; the official spacemacs logo. An integer value is the index of text
   ;; banner, `random' chooses a random text banner in `core/banners'
   ;; directory. A string value must be a path to an image format supported
   ;; by your Emacs build.
   ;; If the value is nil then no banner is displayed. (default 'official)
   dotspacemacs-startup-banner 'official
   ;; List of items to show in the startup buffer. If nil it is disabled.
   ;; Possible values are: `recents' `bookmarks' `projects'.
   ;; (default '(recents projects))
   dotspacemacs-startup-lists '(recents projects)
   ;; Number of recent files to show in the startup buffer. Ignored if
   ;; `dotspacemacs-startup-lists' doesn't include `recents'. (default 5)
   dotspacemacs-startup-recent-list-size 5
   ;; Default major mode of the scratch buffer (default `text-mode')
   dotspacemacs-scratch-mode 'text-mode
   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press <SPC> T n to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   dotspacemacs-themes '(sanityinc-tomorrow-night
   		         sanityinc-tomorrow-bright
   		         sanityinc-tomorrow-eighties
   		         adwaita)
   ;; If non nil the cursor color matches the state color in GUI Emacs.
   dotspacemacs-colorize-cursor-according-to-state t
   ;; Default font. `powerline-scale' allows to quickly tweak the mode-line
   ;; size to make separators look not too crappy.
   dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
   ;; The leader key
   dotspacemacs-leader-key "SPC"
   ;; The leader key accessible in `emacs state' and `insert state'
   ;; (default "M-m")
   dotspacemacs-emacs-leader-key "M-m"
   ;; Major mode leader key is a shortcut key which is the equivalent of
   ;; pressing `<leader> m`. Set it to `nil` to disable it. (default ",")
   dotspacemacs-major-mode-leader-key ","
   ;; Major mode leader key accessible in `emacs state' and `insert state'.
   ;; (default "C-M-m)
   dotspacemacs-major-mode-emacs-leader-key "C-M-m"
   ;; These variables control whether separate commands are bound in the GUI to
   ;; the key pairs C-i, TAB and C-m, RET.
   ;; Setting it to a non-nil value, allows for separate commands under <C-i>
   ;; and TAB or <C-m> and RET.
   ;; In the terminal, these pairs are generally indistinguishable, so this only
   ;; works in the GUI. (default nil)
   dotspacemacs-distinguish-gui-tab nil
   ;; (Not implemented) dotspacemacs-distinguish-gui-ret nil
   ;; The command key used for Evil commands (ex-commands) and
   ;; Emacs commands (M-x).
   ;; By default the command key is `:' so ex-commands are executed like in Vim
   ;; with `:' and Emacs commands are executed with `<leader> :'.
   dotspacemacs-command-key ":"
   ;; If non nil `Y' is remapped to `y$'. (default t)
   dotspacemacs-remap-Y-to-y$ t
   ;; Name of the default layout (default "Default")
   dotspacemacs-default-layout-name "Default"
   ;; If non nil the default layout name is displayed in the mode-line.
   ;; (default nil)
   dotspacemacs-display-default-layout nil
   ;; If non nil then the last auto saved layouts are resume automatically upon
   ;; start. (default nil)
   dotspacemacs-auto-resume-layouts nil
   ;; Location where to auto-save files. Possible values are `original' to
   ;; auto-save the file in-place, `cache' to auto-save the file to another
   ;; file stored in the cache directory and `nil' to disable auto-saving.
   ;; (default 'cache)
   dotspacemacs-auto-save-file-location 'cache
   ;; Maximum number of rollback slots to keep in the cache. (default 5)
   dotspacemacs-max-rollback-slots 5
   ;; If non nil then `ido' replaces `helm' for some commands. For now only
   ;; `find-files' (SPC f f), `find-spacemacs-file' (SPC f e s), and
   ;; `find-contrib-file' (SPC f e c) are replaced. (default nil)
   dotspacemacs-use-ido nil
   ;; If non nil, `helm' will try to minimize the space it uses. (default nil)
   dotspacemacs-helm-resize nil
   ;; if non nil, the helm header is hidden when there is only one source.
   ;; (default nil)
   dotspacemacs-helm-no-header nil
   ;; define the position to display `helm', options are `bottom', `top',
   ;; `left', or `right'. (default 'bottom)
   dotspacemacs-helm-position 'bottom
   ;; If non nil the paste micro-state is enabled. When enabled pressing `p`
   ;; several times cycle between the kill ring content. (default nil)
   dotspacemacs-enable-paste-micro-state nil
   ;; Which-key delay in seconds. The which-key buffer is the popup listing
   ;; the commands bound to the current keystroke sequence. (default 0.4)
   dotspacemacs-which-key-delay 0.4
   ;; Which-key frame position. Possible values are `right', `bottom' and
   ;; `right-then-bottom'. right-then-bottom tries to display the frame to the
   ;; right; if there is insufficient space it displays it at the bottom.
   ;; (default 'bottom)
   dotspacemacs-which-key-position 'bottom
   ;; If non nil a progress bar is displayed when spacemacs is loading. This
   ;; may increase the boot time on some systems and emacs builds, set it to
   ;; nil to boost the loading time. (default t)
   dotspacemacs-loading-progress-bar t
   ;; If non nil the frame is fullscreen when Emacs starts up. (default nil)
   ;; (Emacs 24.4+ only)
   dotspacemacs-fullscreen-at-startup nil
   ;; If non nil `spacemacs/toggle-fullscreen' will not use native fullscreen.
   ;; Use to disable fullscreen animations in OSX. (default nil)
   dotspacemacs-fullscreen-use-non-native nil
   ;; If non nil the frame is maximized when Emacs starts up.
   ;; Takes effect only if `dotspacemacs-fullscreen-at-startup' is nil.
   ;; (default nil) (Emacs 24.4+ only)
   dotspacemacs-maximized-at-startup nil
   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's active or selected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-active-transparency 90
   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's inactive or deselected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-inactive-transparency 90
   ;; If non nil unicode symbols are displayed in the mode line. (default t)
   dotspacemacs-mode-line-unicode-symbols t
   ;; If non nil smooth scrolling (native-scrolling) is enabled. Smooth
   ;; scrolling overrides the default behavior of Emacs which recenters the
   ;; point when it reaches the top or bottom of the screen. (default t)
   dotspacemacs-smooth-scrolling t
   ;; If non nil line numbers are turned on in all `prog-mode' and `text-mode'
   ;; derivatives. If set to `relative', also turns on relative line numbers.
   ;; (default nil)
   dotspacemacs-line-numbers nil
   ;; If non-nil smartparens-strict-mode will be enabled in programming modes.
   ;; (default nil)
   dotspacemacs-smartparens-strict-mode nil
   ;; Select a scope to highlight delimiters. Possible values are `any',
   ;; `current', `all' or `nil'. Default is `all' (highlight any scope and
   ;; emphasis the current one). (default 'all)
   dotspacemacs-highlight-delimiters 'all
   ;; If non nil advises quit functions to keep server open when quitting.
   ;; (default nil)
   dotspacemacs-persistent-server nil
   ;; List of search tool executable names. Spacemacs uses the first installed
   ;; tool of the list. Supported tools are `ag', `pt', `ack' and `grep'.
   ;; (default '("ag" "pt" "ack" "grep"))
   dotspacemacs-search-tools '("ag" "pt" "ack" "grep")
   ;; The default package repository used if no explicit repository has been
   ;; specified with an installed package.
   ;; Not used for now. (default nil)
   dotspacemacs-default-package-repository nil
   ;; Delete whitespace while saving buffer. Possible values are `all'
   ;; to aggressively delete empty line and long sequences of whitespace,
   ;; `trailing' to delete only the whitespace at end of lines, `changed'to
   ;; delete only whitespace for changed lines or `nil' to disable cleanup.
   ;; (default nil)
   dotspacemacs-whitespace-cleanup nil
   ))

(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put almost
any user code here.  The exception is org related code, which should be placed
in `dotspacemacs/user-config'."
  )

(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."
  ;; (global-linum-mode)
  ;; (linum-relative-toggle)

  (spacemacs/toggle-mode-line-minor-modes-off)

  (setq powerline-default-separator 'nil)

  (setq gofmt-command "goimports")
  )

;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (color-theme-sanityinc-tomorrow yaml-mode ws-butler window-numbering which-key web-mode web-beautify volatile-highlights vi-tilde-fringe use-package tagedit spacemacs-theme spaceline smooth-scrolling smeargle slim-mode scss-mode sass-mode rvm ruby-tools ruby-test-mode ruby-end rubocop rspec-mode robe reveal-in-osx-finder restart-emacs rbenv rainbow-delimiters quelpa popwin persp-mode pcre2el pbcopy paradox page-break-lines osx-trash orgit open-junk-file neotree move-text mmm-mode markdown-toc magit-gitflow macrostep lorem-ipsum linum-relative leuven-theme less-css-mode launchctl json-mode js2-refactor js-doc jade-mode info+ indent-guide ido-vertical-mode hungry-delete hl-todo highlight-parentheses highlight-numbers highlight-indentation help-fns+ helm-themes helm-swoop helm-projectile helm-mode-manager helm-make helm-gitignore helm-flyspell helm-flx helm-descbinds helm-css-scss helm-company helm-c-yasnippet helm-ag google-translate golden-ratio go-eldoc gmail-message-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-gutter-fringe git-gutter-fringe+ gh-md flycheck-pos-tip flx-ido fill-column-indicator fancy-battery expand-region exec-path-from-shell evil-visualstar evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit evil-lisp-state evil-jumper evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-args evil-anzu eval-sexp-fu emoji-cheat-sheet-plus emmet-mode elisp-slime-nav edit-server dockerfile-mode diff-hl define-word company-web company-tern company-statistics company-quickhelp company-go company-emoji coffee-mode clean-aindent-mode chruby bundler buffer-move auto-yasnippet auto-highlight-symbol auto-dictionary auto-compile ansible-doc ansible alchemist aggressive-indent adaptive-wrap ace-window ace-link ace-jump-helm-line ac-ispell))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil)))))
```

**Comment by StreakyCobra** [comment] 2016-01-22 16:01
Ok, so I don't really know, maybe it's my terminal that is smarter to deal with the mouse :smile: Joke aside, I probably can't help you more as I'm not on OS X, sorry.

What I could suggest you is to try with a raw emacs (without spacemacs at all) and see how it behaves. If it works, then it means we have a bug in spacemacs. If it dosen't, it means that there is a problem or configuration to do somewhere between your emacs/terminal/system :-)

**Comment by agonzalezro** [comment] 2016-01-22 16:05
Removing `$HOME/.emacs.d` & `$HOME/.spacemacs` I don't get scrolling either. The only difference is that I don't see the error message: `<mouse-X> is undefined`

Do you think that it's a problem with the underlying emacs?

**Comment by StreakyCobra** [comment] 2016-01-22 16:15
I tried the same and it does not work here either. So it means Spacemacs is doing some configurations to make it work, and that these configurations are working on some setups but not for all. You probably will have to find how to make it work by yourself (except if you are lucky and someone here has a solution). If you find a way to make it works let us know, we probably can make it part of Spacemacs for other users :-)

**Comment by agonzalezro** [comment] 2016-01-27 10:40
Hi, I got it working with this:

```
  (global-set-key [mouse-4] 'scroll-down-line)
  (global-set-key [mouse-5] 'scroll-up-line)
```

Perhaps it's not the best way, but I don't know how the default scroll looks like either.

**Comment by mushanshitiancai** [comment] 2016-01-28 06:34
@agonzalezro thank you code. I use it, it works, but it perform badly(delay and not smooth).

But if I use it whit emacs barely(not use spacemacs config),it perfrom well,just like vim or tmux.

**Comment by tuhdo** [comment] 2016-01-28 06:36
Jsut disable `xterm-mouse-mode`, then you can copy/paste/scroll in terminal like before:

```lisp
(xterm-mouse-mode -1)
```

**Comment by mushanshitiancai** [comment] 2016-01-28 06:52
@tuhdo `xterm-mouse-mode` can click,select but not scroll in my osx and centos

**Comment by tuhdo** [comment] 2016-01-28 07:02
@mushanshitiancai I can scroll up, but not scroll down. Maybe if you use terminal, better use PgUp/PgDown since you can't use the scroll bar to jump to a specific point anyway.

**Comment by agonzalezro** [comment] 2016-01-28 15:19
@mushanshitiancai yes,it's not smooth at all this is why I said that it's not the best way. I am pretty sure that there is a simple solution in front of our eyes but I have no idea what it can be yet.

In the meantime I am scrolling with keys, but it's always nice to have proper mouse scrolling.

**Comment by WarFox** [comment] 2016-06-02 12:13
Thanks much!

I got it working in OS X with iTerm2 with this

```lisp
  ;; Enable mouse support
  (unless window-system
    (global-set-key (kbd "<mouse-4>") 'scroll-down-line)
    (global-set-key (kbd "<mouse-5>") 'scroll-up-line))
```

**Comment by d12frosted** [comment] 2016-10-25 12:06
I am closing this issue since solution is proposed. Thanks all.

**Closed by d12frosted** 2016-10-25 12:06 UTC
Labels: - Forum -, Key Bindings, Mouse device, Running in terminal

**Comment by yxzoro** [comment] 2017-01-13 09:04
some changes detween emacs 24.3 and emacs24.4 about mouse-4/5 event ?

**Comment by thammegowda** [comment] 2018-03-16 00:13
disabling `xterm-mouse-mode` solved. (I am using magic trackpad with OSX) I can now scroll up/down, highlight, copy text using pointer (away to other apps) from the `-nw` mode. Thanks @tuhdo

**Comment by madgen** [comment] 2018-03-27 11:52
Well, neither of these are perfect solutions as disabling `xterm-mouse-mode` gives you smooth scrolling but takes away the ability to select windows or lines by clicking. The `global-set-key` approach, on the other hand, is not smooth at all.

**Comment by losnappas** [comment] 2018-05-19 14:29
```
(if (load "mwheel" t)
    (mwheel-install))
```
In my .spacemacs -> dotspacemacs/user-config function. Not sure if that's where it belongs but it works for me.
Found it from
https://www.emacswiki.org/emacs/DotEmacsChallenge

**Comment by Johnson9009** [comment] 2018-07-03 16:14
I have found the root cause of this issue, and found one almost perfect solution to it.
Mouse scrolling doesn't work when emacs is run in Mac OSX terminal. The root cause is that mwheel.el set "mouse-wheel-up-event" and "mouse-wheel-down-event" to "wheel-down" and "wheel-up" because of "ns-win" always in "features" of emacs no matter emacs is launched in GUI or terminal environment. In addition, the mouse wheel keys received from terminal is "mouse-4" and "mouse-5", received from GUI is "wheel-up" and "wheel-down". 
```
(defcustom mouse-wheel-down-event
  (if (or (featurep 'w32-win) (featurep 'ns-win))
      'wheel-up
    (intern (format "mouse-%s" mouse-wheel-down-button)))
  "Event used for scrolling down."
  :group 'mouse
  :type 'symbol
  :set 'mouse-wheel-change-button)
```
So change the values of "mouse-wheel-up-event" and "mouse-wheel-down-event" directly like below can't make emacs GUI and terminal clients work well at the same time when they connect to the same emacs daemon.
```
(unless window-system
  (global-set-key (kbd "<mouse-4>") 'mwheel-scroll)
  (global-set-key (kbd "<mouse-5>") 'mwheel-scroll)
  (setq mouse-wheel-up-event 'mouse-5)
  (setq mouse-wheel-down-event 'mouse-4))
```
So finally I come to below method, i.e., just map the key "mouse-4" and "mouse-5" to "wheel-up" and "wheel-down" on Mac OSX, note that on Linux and Windows nothing need to do. If you want you can add below code in your "dotspacemacs/user-config" and try it, I hope you can enjoy it, thanks.
```
  (if (featurep 'ns)
      (progn
        (global-set-key (kbd "<mouse-4>") (kbd "<wheel-up>"))
        (global-set-key (kbd "<mouse-5>") (kbd "<wheel-down>"))))
```

**Comment by johanatan** [comment] 2020-04-06 01:48
The solutions offered here do indeed work but I've found that `mouse-wheel-follow-cursor` is ignored when set to `'t`. This is the standard behavior for Linux and Max OS X windowing systems where a window doesn't need "focus" to accept wheel events. With the workarounds provided here, the wheel events will always go to the frame with focus (in a multi-frame, single window terminal) rather than the frame under the mouse cursor. Any ideas how to fix this?

**Comment by supern8ent** [comment] 2023-08-01 17:57
iterm2 3.4.19 and emacs 28.2:
```
;; Enable mouse scrolling in terminal
(unless window-system
  (xterm-mouse-mode t)
  (global-set-key (kbd "<mouse-4>") 'scroll-down-line)
  (global-set-key (kbd "<mouse-5>") 'scroll-up-line)
```

**Comment by zzeitt** [comment] 2025-07-10 06:37
Hint, the belowing commands works in my cases.
```elisp
(xterm-mouse-mode 1)
(mouse-wheel-mode 1)
```
