### ISSUE TITLE
Helm not tracking backspaces and any keys after that

### ISSUE THREAD

**Issue by paradigmshift** [syl20bnr/spacemacs#4711] opened 2016-01-20 20:48 UTC
When using Helm commands (SPC f f, SPC p f, etc.) Helm doesn't track the backspace key or any other keys I type after that in the minibuffer. While the results change appropriately, I can't see the changed I'm making in the echo area.

![keys-not-working](https://cloud.githubusercontent.com/assets/846449/12462547/32bbc09a-bfbf-11e5-87e6-5c54e6173c35.gif)

**Comment by TheBB** [comment] 2016-01-20 21:45
Duplicate of https://github.com/syl20bnr/spacemacs/issues/4538, fixed upstream. Update your packages.

**Closed** 2016-01-20 21:45 UTC
Labels: duplicate (-: :-)
