### ISSUE TITLE
- doesn't navigate up in vinegar

### ISSUE THREAD

**Issue by BrianHicks** [syl20bnr/spacemacs#6140] opened 2016-05-26 21:13 UTC
#### Description

`-` doesn't navigate up in vineager

#### Reproduction guide
- Start Emacs
- Add vinegar to layers and install
- Navigate to the buffer directory by pressing `-`
- Press `-` again

*Observed behaviour:*

nothing

*Expected behaviour:*

dired navigates up one directory

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory nil auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle)
 better-defaults colors dash dockerfile
 (elm :variables elm-format-on-save t)
 emacs-lisp evil-commentary fasd git github
 (go :variables gofmt-command "goimports")
 html javascript markdown
 (osx :variables mac-right-option-modifier nil)
 prodigy
 (python :variables python-auto-set-local-pyenv-version 'on-project-switch)
 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/zsh")
 shell-scripts syntax-checking terraform typography unimpaired vagrant version-control vinegar yaml)
```

**Comment by StreakyCobra** [comment] 2016-05-27 08:08
I can't reproduce this on `develop` with my config.

-----

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 584cae8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 bb-git bb-latex bepo better-defaults c-c++ clojure colors command-log csv dash deft dockerfile
 (elfeed :variables rmh-elfeed-org-files
         (list "~/org/main.org"))
 encoding emacs-lisp emoji erc erlang ess evil-cleverparens extra-langs finance git github haskell html imenu-list ipython-notebook java javascript
 (keyboard-layout :variables kl-layout 'bepo)
 latex markdown mu4e nginx no-dots ocaml org pandoc php plantuml python vinegar rebox restclient ruby rust scala semantic shell shell-scripts spacemacs-helm speed-reading
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 sql syntax-checking systemd themes-megapack typography
 (version-control :variables version-control-diff-tool 'diff-hl)
 vimscript yaml)
```

**Comment by houli** [comment] 2016-05-27 19:50
This is still related to this commit https://github.com/syl20bnr/spacemacs/commit/54a978c8e2a38698bbcd1ff080520da96b30b9b3
and this issue https://github.com/syl20bnr/spacemacs/issues/5883

**Comment by StreakyCobra** [comment] 2016-05-28 11:20
Ok, thanks for the info @houli . I'm closing this one as duplicate then.

**Closed by StreakyCobra** 2016-05-28 11:20 UTC
Labels: - Bug tracker -, File browser, To be reproduced
