### ISSUE TITLE
font sizing with mouse wheel

### ISSUE THREAD

**Issue by manu09** [syl20bnr/spacemacs#4587] opened 2016-01-13 01:13 UTC
I think it would be better to enable usual `copy/paste` keys by default. Who remembers the other commands to do so? I also would like to see the ability to increase/decrease font size with `C-mousewheel`. These keybindings are known across many applications, so let them feel comfy in spacemacs as well! :ok_woman:

**Comment by StreakyCobra** [comment] 2016-01-13 09:43
What are usual copy/paste keys for you? `C-insert`/`S-insert`? `y/p`? `C-c`/`C-v`?

`y` and `p` should copy/pase to/from the system clipboard, they are not hard to remember, go for it :-) `C-c` is an important emacs bindings, so it's probably not a good idea to remap it directly into Spacemacs. If you are missing them you can remap them on your own configuration.

Increasing/decreasing font size with `C-wheel` can be a good idea, and shouldn't be hard, let's tag this as `Beginner friendly` then.

**Comment by StreakyCobra** [comment] 2016-01-13 09:50
Starting point: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs/local/zoom-frm/zoom-frm.el#L115-L119

**Comment by mankoell** [comment] 2016-01-13 10:05
Please take a look at [Emacs Wiki](http://www.emacswiki.org/emacs/CuaMode)
> Cua-mode is part of GnuEmacs versions 22.1.1 and later (at least).
> Cua-mode allows one to use ‘C-v’, ‘C-c’, and ‘C-x’ to paste, copy, and cut the region. Since this 
> conflicts with very important keybindings in Emacs, these CUA bindings are only active when the 
> mark is active.

and the [manual](http://www.gnu.org/software/emacs/manual/html_node/emacs/CUA-Bindings.html)
> When CUA mode is enabled, the keys C-x, C-c, C-v, and C-z invoke commands that cut (kill), copy, > paste (yank), and undo respectively. The C-x and C-c keys perform cut and copy only if the region is > active. Otherwise, they still act as prefix keys, so that standard Emacs commands like C-x C-c still 
> work. 

So they will never conflict with `C-c`. :ok_hand:

**Comment by StreakyCobra** [comment] 2016-01-13 10:16
Ok, I was not aware of this. I'm still not sure it should be a default, especially as it can be really easily activated from user configuration (calling `(cua-mode t)`). For instance:

    The package does a whole lot more, too: ‘C-z’ to undo

will conflict with:

    C-z runs the command evil-emacs-state

which is an important binding for some users. But it can probably be documented in the FAQ for how to activate standard copy/paste shortcuts.

**Comment by AlejandroCatalina** [comment] 2016-01-13 10:18
I think the emacs default are nice for emacs style and `y/p` for evil mode. Emacs has always had `M-w/C-y/M-y` as copy/yank/cycle through yanks commands. IMO, if anyone wants CUA, it's fairly easy to set up in the user-config section.

**Comment by Andre0991** [comment] 2016-01-13 19:07
I think it would be cool to have a `cua-state` or something like that, if someone works on a layer that provides compatibility between Spacemacs and cua keybindings (like the `C-z` issue pointed out by @StreakyCobra .)

This would make Spacemacs more appealing to a *much* broader range of users.

Of course, setting up cua cua is fairly easy, but we can't underestimate "The Power of Defaults". If it were possible to select cua keybindings on setup, I'm sure I could recommend Spacemacs to many more friends.
 
Also don't underestimate the fact that `C-c` and `C-v` not working as usual put off a lot of people.

By the way, I once read that Emacs got its keybindings for editing text just because they were used in the popular text editors of the time, making the migration easy. Fast forward some decades and we still have them, but the "smooth migration" part is totally gone.

Anyway, I think it's good that you brought up this discussion. It's pretty controversial and sometimes we don't care as we got used to whichever editing style we use in Emacs, but I think properly introducing `cua` style keybindings would be awesome.

**Comment by StreakyCobra** [comment] 2016-01-13 20:37
From my point of view having a way to integrate cua in spacemacs and enable it *on user request* would be nice, even by asking the question at install time :-)

I just don't want it to be the default in spacemacs, especially for user using the `evil` mode. People using `vim` bindings should already be used to `y` and `p`, and enabling cua will break `C-v`, which is an important one for visual selection (square region).

Anyway, if someone want to work on it, feel free :-)

**Comment by Andre0991** [comment] 2016-01-13 20:55
Yeah, totally agree. It could be an option; I myself wouldn't ever want to use it :)

**Comment by justbur** [comment] 2016-01-13 21:01
just make it a layer

**Comment by mankoell** [comment] 2016-01-13 22:42
Sorry, I didn't know about (spacemacs is spamming many other keyboard shortcuts other than `SPC`). I dont want to put my use case over yours, sometimes it is hard to figure out where the diff between good defaults and user config is. Sure, it isnt hard to activate cua.

**Comment by hasufell** [comment] 2016-05-17 18:16
> People using vim bindings should already be used to y and p

The first thing I did in vim a long long time ago was implementing C-c/C-x/C-v behavior, so I definitely disagree.

**Comment by d12frosted** [comment] 2016-10-24 19:14
Closing this issue as duplicate of #5429 and #1298.

**Closed by d12frosted** 2016-10-24 19:14 UTC
Labels: Discussion, Key Bindings
