### ISSUE TITLE
SanityInc Tomorrow themes don't work as default theme

### ISSUE THREAD

**Issue by nedludd** [syl20bnr/spacemacs#388] opened 2015-01-08 13:34 UTC
The SanityInc themes from the themes megapack work fine if you load them after emacs is loaded.

But if you make it the default: `dotspacemacs-default-theme 'sanityinc-tomorrow-night`, emacs fails to load correctly.

````
Debugger entered--Lisp error: (error "Package `sanityinc-tomorrow-night-theme-' is unavailable")
  signal(error ("Package `sanityinc-tomorrow-night-theme-' is unavailable"))
  error("Package `%s-%s' is unavailable" sanityinc-tomorrow-night-theme "")
  package-compute-transaction(nil ((sanityinc-tomorrow-night-theme)))
  package-install(sanityinc-tomorrow-night-theme)
````
Seems to have something to do with the way that particular meta-package is configured, but I'm afraid I lack the experience to debug it.

**Comment by syl20bnr** [comment] 2015-01-08 15:21
Thanks for the report. I will work on the support for it.

duplicate of #163

**Closed** 2015-01-15 03:52 UTC
Labels: duplicate (-: :-)
