### ISSUE TITLE
nyan-mode is too old

### ISSUE THREAD

**Issue by hanm2019** [syl20bnr/spacemacs#13635] opened 2020-06-02 02:28 UTC
when i use spacemacs in develop branch, i found a error report in message buffer that

 `Error during redisplay: (eval (doom-modeline-segment--buffer-position)) signaled (void-variable nyan-minimum-window-width)`, 

then i found the doom-modeline is rely on this value, but the file(nyan-mode.el) in spacemacs is too old , there isn't var: `nyan-minimum-window-width`, so i think maybe we can update this value with https://github.com/TeMPOraL/nyan-mode/blob/master/nyan-mode.el

**Comment by smile13241324** [comment] 2020-06-05 21:21
This is a duplicate of #12946

**Comment by smile13241324** [comment] 2020-06-05 21:22
Closed for being duplicate

**Closed by smile13241324** 2020-06-05 21:22 UTC
Labels: Duplicate ☝
