### ISSUE TITLE
Error occurs on updating move-text package from ELPA

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#5065] opened 2016-02-14 10:05 UTC
Is anyone else getting this error after updating the packages?

    An error occurred while installing move-text (error: (error Error retrieving: https://melpa.org/packages/move-text-20160211.1847.el "incomprehensible buffer"))

**Comment by bmag** [comment] 2016-02-14 10:22
Template for reporting issues: https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report

Similar issues:
- https://lists.gnu.org/archive/html/emacs-devel/2015-12/msg01300.html
- https://github.com/bbatsov/prelude/issues/947
- https://github.com/syl20bnr/spacemacs/issues/3854

**Comment by TheBB** [comment] 2016-02-23 09:58
I'm closing this as a duplicate of #3854.

**Closed by TheBB** 2016-02-23 09:58 UTC
