### ISSUE TITLE
org-export-as: Wrong number of arguments

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#2856] opened 2015-09-02 03:00 UTC
`, e h h` (org export to html) is broken in the latest develop branch (Spacemacs v.0.104.0):

```
org-export-as: Wrong number of arguments: #[(templates) "ebÆÇÈÆÉ#\\�Ê Ë	!Ì=X�Í	
\"ÎÏ	\"	ÎÐ	\"E<�ÑÒÎÓ	\"\"W�W�
BÎÔ	\"bÕÆx`|c)+)�*" [record object templates value begin signature nil re-search-forward "{{{[-A-Za-z0-9_]" t ...] 6 ("/usr/local/Cellar/emacs/24.5/share/emacs/24.5/lisp/org/org-macro.elc" . 3797)], 3
```

**Comment by TheBB** [comment] 2015-09-02 08:28
I can't reproduce. Have you updated org?

**Comment by mnick** [comment] 2015-09-02 14:19
I had the same problem. Deleting the `org` directory in the `emacs.d/elpa` directory and reinstalling org (just restart spacemacs) fixed it for me.

**Comment by bjeanes** [comment] 2015-09-11 06:29
Also having this problem. `rm -rf ~/.emacs.d/elpa/org*` and restarting Spacemacs to reinstall org did not change the result for me.

```
Invalid face reference: t [372 times]
progn: Wrong number of arguments: #[(templates) "ebÆÇÈÆÉ#\\Ê Ë	!Ì=XÍ	
\"ÎÏ	\"	ÎÐ	\"E<ÑÒÎÓ	\"\"WW
BÎÔ	\"bÕÆx`|c)+)*" [record object templates value begin signature nil re-search-forward "{{{[-A-Za-z0-9_]" t ...] 6 ("/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.9/share/emacs/24.5/lisp/org/org-macro.elc" . 3797)], 3Invalid face reference: t
```

**Comment by bjeanes** [comment] 2015-09-11 06:34
I noticed another error `Symbol's value as variable is void: org-planning-line-re`. That lead me to [this StackOverflow question](https://stackoverflow.com/questions/31924867/emacs-stopped-exporting-org-files).

Running `org-reload` fixes exporting for me (at least perhaps until the next restart). It seems like maybe corrupt compiled elc between the ELPA org and the stock org mode. I don't know enough about Emacs to understand the implications of this in the long term or what next steps would be, as it seems like `org-reload` is a workaround at best.

**Comment by StoneJiaJia** [comment] 2015-09-13 17:11
Can't solve this programming,when I executed R code on org-mode babel happen to me.Tride all the solution above all ,Can't help.

**Comment by StoneJiaJia** [comment] 2015-09-13 17:29
It was ok when I executed R code with ess .Just happened on org-mode babel

**Comment by mnick** [comment] 2015-09-17 01:10
I ran into the problem again. This time deleting `elpa/org*` didn't fix the problem. However, as @bjeanes  suggested, putting `(org-reload)` at the end of `dotspacemacs/config()` fixed it for me.

**Comment by StreakyCobra** [comment] 2015-11-07 16:51
Could this be a bug caused by https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-do-some-of-my-org-related-settings-cause-problems ?

**Comment by TheBB** [comment] 2016-01-06 13:46
I think so, since the filename in the error message is not in the elpa directory.

I'm leaning towards closing this as a user configuration error, then.

**Comment by TheBB** [comment] 2016-01-06 13:54
@adimit had this exact problem on gitter and fixed it by changing his configuration so that org was not loaded early. I think that's enough evidence.

**Closed by TheBB** 2016-01-06 13:54 UTC
Labels: <=(- UBO -)=>, Org

**Comment by adimit** [comment] 2016-01-06 13:57
Yup. Watch out for stuff like `custom-set-variables`, which will evaluate *before* `user-init` is run. Wrap `custom-set-variables` in `with-eval-after-load 'org`.

**Comment by nrolland** [comment] 2016-04-24 14:43
same pb here, doing `org-reload` manually for now

**Comment by TheColourOutOfSpace** [comment] 2016-08-12 10:01
The solution by @StreakyCobra  and @adimit works for me. Putting _org-babel-do-load-languages_ inside _with-eval-after-load 'org_ made it go away.
