### ISSUE TITLE
an issues about auto completion

### ISSUE THREAD

**Issue by tianyuqi123** [syl20bnr/spacemacs#5745] opened 2016-04-10 04:30 UTC
I got an error when I add ‘auto-completion’ in ~/.emacs.d/.spacemacs
File mode specification error: (void-function yas--load-pending-jits)
yas-minor-mode: Symbol's function definition is void: yas--load-pending-jits
Error in post-command-hook (yas--post-command-handler): (void-function yas--post-command-handler)
Error in post-command-hook (yas-global-mode-check-buffers): (void-function yas--load-pending-jits)
How can i fix it?
emacs24.5.1 ubuntu

**Comment by NJBS** [comment] 2016-04-10 04:32
Duplicate of https://github.com/syl20bnr/spacemacs/issues/5736

**Comment by tianyuqi123** [comment] 2016-04-10 04:38
@NJBS thank you. : )

**Closed** 2016-04-10 04:39 UTC
