### ISSUE TITLE
Visual State streams highlighted text into clipboard

### ISSUE THREAD

**Issue by seanstrom** [syl20bnr/spacemacs#1504] opened 2015-05-06 04:20 UTC
Hey so I have an issue where Spacemacs will stream, or consistently copy, the highlighted text into
my system clipboard. I'm using the official Emacs distribution for Mac OSX (not the port) and should be using the latest Spacemacs. I think this should be something configurable but I can't find the setting looking for some help please. :)

**Comment by syl20bnr** [comment] 2015-05-07 05:12
Is this in the terminal or GUI ?

**Comment by tuhdo** [comment] 2015-05-07 05:17
You can prevent Emacs from inserting system clipboard with `x-select-enable-clipboard ` by setting it to `nil`. In the old days before Emacs 24, Emacs does not share its text with system clipboard and people found that annoying as it is the default behaviour in every application out there. See [Using the Clipboard](http://www.gnu.org/software/emacs/manual/html_node/emacs/Clipboard.html). When I was using Emacs 23, I was trying hard to get Emacs to share with system clipboard and thankfully it is enabled by default in Emacs 24 onward.

**Comment by seanstrom** [comment] 2015-05-07 21:48
This is in the GUI.
If im using `x-select-enable-clipboard`, anything I highlight with the cursor in Visual Mode will be copied to the clipboard. I just want the Visual Mode to highlight and then Evil Yank to copy

**Comment by syl20bnr** [comment] 2015-05-08 02:05
Ok but `x-select-enable-clipboard` is not what you want then, it clearly put the selection in the clipboard but what you want is the opposite of this. So leave it to `nil` and when you want to yank into the clipboard use `"*y`.

**Comment by seanstrom** [comment] 2015-05-11 14:32
That sounds good to me! Thanks for the help guys!

**Comment by andrewsanchez** [comment] 2015-08-17 04:49
Is there a way to set `x-select-enable-clipboard` to and still be able to use just `y` to yank into the clipboard?

**Comment by jneen** [comment] 2015-10-14 15:49
Same question as @andrewsanchez.  The use case here for me is this: I've copied some text and I want to replace some text with my copied text.  I highlight the text I want to replace and paste - ...except the mere act of highlighting has blown away my clipboard.

**Comment by justin808** [comment] 2015-10-24 04:10
I'd like to do the same as @andrewsanchez and @jneen, and also enable the regular clipboard to paste to Emacs if x-select-enable-clipboard is nil.

**Comment by justin808** [comment] 2015-10-24 04:17
Solution:

```lisp
(fset 'evil-visual-update-x-selection 'ignore)
```

**Comment by StreakyCobra** [comment] 2015-11-10 22:11
I can't reproduce the original issue (which is pretty old), the original author has said being satisfied by the solution and the ending discussion having also been answered, I'm closing this issue. In any case, feel free to open a new issue in case of troubles :relaxed:

**Comment by justin808** [comment] 2015-11-11 02:59
@StreakyCobra Is my suggested change no longer necessary? I'm using "master".

**Comment by StreakyCobra** [comment] 2015-11-11 09:26
@justin808 I've done some searches, and [it seems](http://emacs.stackexchange.com/a/15054/6662) what you have is a normal behaviour, not a bug. But it should probably be documented in the FAQ, in `How do I disable visual selection to override the system clipboard`.

So reopening it and labelling as documentation and beginner friendly :relaxed:

**Closed** 2016-01-04 08:43 UTC
Labels: documentation :->, Fixed in develop
