### ISSUE TITLE
, i c not inserting citation

### ISSUE THREAD

**Issue by RaghuNaik** [syl20bnr/spacemacs#8741] opened 2017-04-19 17:52 UTC
####  Description:

, i c does not insert citation (bibtex layer installed). 

#### Reproduction guide:

- Start emacs

- open .org file

- press , i c to insert citation

- search for the right reference in the opened .bib database

- press enter to insert the citation

####  Observed behavior

Instead of inserting citation, the bib file opens in the buffer with the cursor on the relevant bib entry.  *This has started happening only since yesterday after an update*.

####  Expected behavior
A citation should have been inserted. 

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.8
- Spacemacs branch: master (rev. bd7ef98e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html syntax-checking spell-checking helm auto-completion better-defaults smex org sql ess deft latex emacs-lisp git pandoc markdown bibtex graphviz colors finance python ipython-notebook themes-megapack ibuffer speed-reading ranger extra-langs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by JP-Ellis** [comment] 2017-04-20 03:04
Thanks for the nice bug report :) This is a duplicate of #8739.

**Comment by RaghuNaik** [comment] 2017-04-20 13:27
Thanks for the response. Much appreciated :-)

**Closed** 2017-04-21 19:23 UTC
