### ISSUE TITLE
MELPA repository not available in 0.105

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#4402] opened 2016-01-05 03:04 UTC
I installed spacemacs from a fresh start. After bootstrap and intialized, I hit `SPC a k` to check the package list, but only packages from `org elpa` and `gnu elpa` were there. **All MELPA packages were gone**. Whether **using --insecure option or not**, no MELPA packages showing. I can't add layers now due to this issue since no packages from MELPA will be installed.

I also tried use spacemacs behind a socks proxy wrapper, but still no good.

I'm using `Windows 7 64bit`, `emacs w64 24.5.1`, `git for windows 2.6.4`. Any help will be appreciated.

**Comment by et2010** [comment] 2016-01-05 03:30
I tried toggling `dotspacemacs-elpa-https` to `t` or `nil`, neither of them worked.

**Comment by et2010** [comment] 2016-01-05 03:48
With using `describe-variable` on `package-archives`, I got this:
>Its value is (("gnu" . "http://elpa.gnu.org/packages/"))

while `dotspacemacs-elpa-https` were set to `t`

**Comment by syl20bnr** [comment] 2016-01-05 06:05
I cannot reproduce this bug, the output of describe variable on my system is:

```
package-archives is a variable defined in `package.el'.
Its value is (("melpa" . "https://melpa.org/packages/")
 ("org" . "http://orgmode.org/elpa/")
 ("gnu" . "https://elpa.gnu.org/packages/"))

Original value was 
(("gnu" . "http://elpa.gnu.org/packages/"))
```

What is the output of the following code ?

```elisp
(configuration-layer//resolve-package-archives configuration-layer--elpa-archives)
```

**Comment by et2010** [comment] 2016-01-05 09:55
Weird, the output seems right:
>(("melpa" . "https://melpa.org/packages/") ("org" . "http://orgmode.org/elpa/") ("gnu" . "https://elpa.gnu.org/packages/"))

**Comment by et2010** [comment] 2016-01-05 10:29
Also, the value of  `package-enable-at-startup` is `t`, i.e. variable `package--initialized` in following function was set to `t` unexpectedly during launching. But I don't know why this is happening.
```emacs-lisp
(defun configuration-layer/initialize ()
  "Initialize `package.el'."
  (setq configuration-layer--refresh-package-timeout dotspacemacs-elpa-timeout)
  (configuration-layer//parse-command-line-arguments)
  (unless package--initialized
    (setq package-archives (configuration-layer//resolve-package-archives
                            configuration-layer--elpa-archives))
    ;; optimization, no need to activate all the packages so early
    (setq package-enable-at-startup nil)
    (package-initialize 'noactivate)
    ;; TODO remove the following hack when 24.3 support ends
    ;; Emacs 24.3 and above ships with python.el but in some Emacs 24.3.1
    ;; packages for Ubuntu, python.el seems to be missing.
    ;; This hack adds marmalade repository for this case only.
    (unless (or (package-installed-p 'python) (version< emacs-version "24.3"))
      (add-to-list 'package-archives
                   '("marmalade" . "https://marmalade-repo.org/packages/")))))
```

**Comment by et2010** [comment] 2016-01-05 10:48
Eh, sorry, my fault. I finally figured out why. I used to add following statement in function definition of ```dotspacemacs/user-init ()``` in my .spacemacs file:
```
(package-initialize)
```
to fix org mix-installation problem (ie. shipped version and elpa version are both loaded, see: http://stackoverflow.com/a/17422623). This changed the value of `package--initialized` to `t` and lead to my problem.

Sorry for the false alarm! Thank you very much for your help! @syl20bnr

**Comment by StreakyCobra** [comment] 2016-01-05 10:54
:+1: If your problem is solved you may consider to close the issue then :-)

**Comment by StreakyCobra** [comment] 2016-01-05 10:55
:smile:

**Closed** 2016-01-05 10:55 UTC
Labels: to be reproduced

**Comment by et2010** [comment] 2016-01-05 11:00
@StreakyCobra Thanks for reminder.
