### ISSUE TITLE
Migrate off of Travis CI Legacy platform

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2512] opened 2015-08-01 21:43 UTC
Everytime I look at a spacemacs the CI status on Travis, I see the message, "This job ran on our legacy infrastructure. Please read our docs on [how to upgrade](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)"

**Comment by EricCrosson** [comment] 2015-08-04 16:02
In order to upgrade we need to remove all sudo invocations from the .travis.yml file. If you have a way to reproduce the following without sudo:

```sh
sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
  sudo apt-get -qq update &&
  sudo apt-get -qq -f install &&
  sudo apt-get -qqy install emacs-snapshot;
```

we'll be in the clear.

**Comment by rphillips** [comment] 2015-08-04 16:10
Instructions: https://github.com/travis-ci/apt-source-whitelist

.travis.yml:
```
sudo: false
addons:
  apt:
    sources:
    - ubuntu-elisp
    packages:
    - emacs-snapshot
```

Looks like we need to patch this repo though to whitelist the ubuntu-elisp ppa [1].

[1] https://github.com/travis-ci/apt-source-whitelist

**Comment by robbyoconnor** [comment] 2015-08-04 19:43
I would have made a PR but I wanted to get some actual work that isn't spacemacs done before it gets too bad!

**Comment by rphillips** [comment] 2015-08-04 19:46
@robbyoconnor sorry... I just went through this migration and figured I would make the upstream change.

**Comment by robbyoconnor** [comment] 2015-08-04 21:52
@rphillips, it is completely cool -- we're a community -- we're all volunteers who care about spacemacs :)

**Comment by StreakyCobra** [comment] 2015-11-09 22:03
This issue is not relevant anymore. Closing.

**Closed by StreakyCobra** 2015-11-09 22:03 UTC
Labels: build, enhancement :-D
