### ISSUE TITLE
problem with anaconda-mode

### ISSUE THREAD

**Issue by XiaoLiuAI** [syl20bnr/spacemacs#5166] opened 2016-02-20 23:58 UTC
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description
When I use org-publish to export files, I got error message
```
progn: Symbol's function definition is void: anaconda-eldoc-mode
```
I releaized it is probably a problem with python mode, then I opened a python source file and got message:
```
eldoc error: (error Eldoc needs an inferior Python process running)
```
Remoing the hook ```(remove-hook 'python-mode-hook 'spacemacs//init-eldoc-python-mode)``` solves all the problems.

#### Reproduction guide
- Make an org project
- Put an org file with python source code
- Start Emacs
- run function org-publish

*Observed behaviour:*
Error in mini buffer and no output generated ( or output process stops while processing the org file that contains python source code.

*Expected behaviour:*
Run smoothly, and output the html files into destination directory.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 6689699)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults spell-checking syntax-checking eyebrowse version-control git org markdown emacs-lisp ess python c-c   java javascript html octave scala shell evernote dash chrome)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by syl20bnr** [comment] 2016-02-21 07:32
Are your packages up to date ?

**Comment by mandarvaze** [comment] 2016-02-23 14:42
I also get this.
Seems like the problem "appeared"  in 0.105.10 when "anaconda-eldoc-mode" was introduced. (I never saw this error earlier)
I'm also on OSX
Is there a way I can go back to 0.105.9 ?

**Comment by mandarvaze** [comment] 2016-02-23 14:43
@XiaoLiuAI Where should I put ``(remove-hook 'python-mode-hook 'spacemacs//init-eldoc-python-mode)`` ?
Am new to emacs/spacemacs

**Comment by XiaoLiuAI** [comment] 2016-02-23 14:47
@mandarvaze in the user-custom section of your dot file.

**Comment by StreakyCobra** [comment] 2016-02-23 14:47
@mandarvaze https://github.com/syl20bnr/spacemacs/issues/5142#issuecomment-186187528

**Comment by StreakyCobra** [comment] 2016-02-23 14:48
@XiaoLiuAI Also it would be nice if you can edit the template to provide the "reproduction guide" :-)

**Comment by XiaoLiuAI** [comment] 2016-02-23 15:00
@StreakyCobra I saw that "reproduction guide" part, it's shame that I have no idea how to reproduce it. I just found it happens. I suppose anyone who install the same layers as listed above and try the function in my problem description will face the same problem. If not, I also don't the reason.

**Comment by StreakyCobra** [comment] 2016-02-23 15:16
@XiaoLiuAI Even if you don't know how to reproduce, and even if it is as simple as:

- Start Emacs
- Open an python file with `SPC f J py RET`

And describing what you observed and what you expected.

It's important to have it, even it if may sound dummy, because:

- It may be obvious for you what you did, but not for others. People trying to reproduce cannot know if they are doing it the same way as you if they failed.

- It already contains information. In my example above it would show that the bug is not dependent of the content of the file for instance.

- It may trigger neurons of people that went through the same procedure without even trying to reproduce.

- It allows people in a hurry to not spend time trying to find/guess what you did :-) And usually people who are the most competent art the ones with the less time.

**Comment by mandarvaze** [comment] 2016-02-24 06:55
I can confirm that after I "updated the packages" my problem went away.
Unfortunately, I didn't know that I need to do that manually.
I sorta assumed that updating spacemacs to the latest version is all  I need to do.
@StreakyCobra Thanks for the pointer to #5142

**Comment by syl20bnr** [comment] 2016-02-24 16:31
> I sorta assumed that updating spacemacs to the latest version is all I need to do.

Indeed this is on my todo list.

**Comment by deb0ch** [comment] 2016-10-10 14:19
Is this one fixed now ? Can we close this issue ?

**Comment by xiao-liu-noisychannels** [comment] 2016-10-11 13:47
I have no idea the latest progress about this issue. From @mandarvaze 's description, this can be solved by updating the packages. So I think it can be closed.

**Comment by deb0ch** [comment] 2016-10-11 13:56
Ok thanks ! Anyways, if that bug appears again someone will most likely report it again.

Are you the same person who opened the issue but under a different account ?

**Comment by xiao-liu-noisychannels** [comment] 2016-10-11 14:10
@deb0ch Yes, I forgot to switch my account... Sorry for that.

**Comment by mandarvaze** [comment] 2016-10-12 11:13
Currently I am on 0.200, and I don't see this issue anymore. 
Can be closed.

**Closed** 2016-10-25 16:00 UTC
Labels: - Bug tracker -, Need repro steps, Python, Waiting for response
