### ISSUE TITLE
Delete command broken after `org-present`

### ISSUE THREAD

**Issue by meditans** [syl20bnr/spacemacs#2117] opened 2015-06-25 16:31 UTC
Hi, I found the `d` key doesn't work anymore after quitting an`org-present` presentation.

To reproduce this bug:
0) Install the `org` layer
1) Create a `.org` file
2) `M-x org-present`
3) exit with `q`
4) try to use `dd` to delete a line

**Comment by swaroopch** [comment] 2015-06-25 16:45
This is rather strange because we don't override the `d` key at all.

Please see https://github.com/syl20bnr/spacemacs/blob/develop/contrib/org/packages.el#L158

Is the buffer in `buffer-read-only` mode?

**Comment by meditans** [comment] 2015-06-25 16:50
Yeah, I never enter in write mode while in `org-present`.
The exact error is `d is undefined`. To be fair, the problem is not limited to the `d` key. I have the same problem with `y` or `p`. The movement keys seem to work, however.

**Comment by swaroopch** [comment] 2015-06-25 17:07
I can reproduce the problem. The worst part is that even `i` becomes undefined, so you can't go from normal mode to insert mode.

**Comment by swaroopch** [comment] 2015-06-25 17:12
Interestingly, if I comment out these two lines, things work as expected:

```
      ;; (add-hook 'org-present-mode-hook 'spacemacs//org-present-start)
      ;; (add-hook 'org-present-mode-quit-hook 'spacemacs//org-present-end)
```

So I'm guessing the problem has to do something with `(evil-evilified-state)` and `(evil-normal-state)`.

@meditans Can you confirm that the behavior is normal when you comment out those two above lines in `contrib/org/packages.el` ?

**Comment by robbyoconnor** [comment] 2015-08-01 10:14
This is bad -- because i'm giving a talk trying to sell spacemacs and this glitch won't sell it well as I plan on demoing parts :-)

**Comment by robbyoconnor** [comment] 2015-08-01 10:38
Also none of the changes above fix the issue...I'm not sure what's causing the issue but I can't get any of the vim key bindings to work :crying_cat_face:

**Comment by syl20bnr** [comment] 2015-08-12 05:35
Should be fixed in develop.

**Comment by robbyoconnor** [comment] 2015-08-12 06:13
i can't enter insert mode after exiting `org-present`

**Comment by syl20bnr** [comment] 2015-08-12 13:26
@robbyoconnor You may have another issue, the fact that even the proposed fixes above did not work for you is weird.
I tried on several machines and this issue does not happen anymore.

**Closed** 2015-09-28 06:53 UTC
Labels: bug :-(, Fixed in `develop`, High Priority, Key Bindings, Org
