### ISSUE TITLE
After updating ESC throws error 

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#6270] opened 2016-06-08 20:27 UTC
Very annoying to use - as you have to press ESC sequence twice to get out of insert mode

```
byte-code: Beginning of buffer [8 times]
if: Wrong number of arguments: #[(&optional continue) "	?Ä 
¢Å Æ" [evil-undo-list-pointer evil-in-single-undo continue buffer-undo-list evil-refresh-undo-step undo-boundary nil] 2 ("/home/vco/.emacs.d/elpa/evil-20160608.229/evil-common.elc" . 102227)], 2
if: Wrong number of arguments: #[(&optional continue) "	?Ä 
¢Å Æ" [evil-undo-list-pointer evil-in-single-undo continue buffer-undo-list evil-refresh-undo-step undo-boundary nil] 2 ("/home/vco/.emacs.d/elpa/evil-20160608.229/evil-common.elc" . 102227)], 2
if: Wrong number of arguments: #[(&optional continue) "	?Ä 
¢Å Æ" [evil-undo-list-pointer evil-in-single-undo continue buffer-undo-list evil-refresh-undo-step undo-boundary nil] 2 ("/home/vco/.emacs.d/elpa/evil-20160608.229/evil-common.elc" . 102227)], 2
```

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete)
 better-defaults c-c++ colors emacs-lisp emoji erc evil-snipe eyebrowse git github haskell html ipython-notebook javascript latex markdown ranger org python
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 syntax-checking themes-megapack version-control yaml)
```

**Comment by syl20bnr** [comment] 2016-06-08 20:30
Updating Spacemacs or the packages ?

**Comment by rsenna** [comment] 2016-06-08 20:32
I'm on OSX. In my case, there seems to be no way of getting back to normal mode. Stuck in regular Emacs mode (I also use the hybrid editing style).

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 458c08b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp
                 (git :variables git-gutter-use-fringe t)
                 markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control ansible chrome clojure common-lisp csharp dockerfile eyebrowse html java javascript osx puppet restclient scala search-engine)
```

**Comment by syl20bnr** [comment] 2016-06-08 20:33
I cannot reproduce it after updating my packages (evil was part of the upgrade).
Check the cache files in `~/.emacs.d/.cache` and in doubt remove `~/.emacs.d/elpa/evil-xxxxxx` and restart.

**Comment by syl20bnr** [comment] 2016-06-08 20:33
I'm on develop branch, I'll check on master.

**Comment by syl20bnr** [comment] 2016-06-08 20:39
Oh reproduced :-) I happens only in hybrid mode indeed.
Will check this evening.

**Comment by syl20bnr** [comment] 2016-06-09 02:36
Should be fixed in develop branch.

**Comment by syl20bnr** [comment] 2016-06-09 03:31
Backported to 0.105.21, I hope it correctly fixes it.

**Closed** 2016-08-29 19:37 UTC
Labels: - Bug tracker -, Evil, Fixed in current release-x.x, Fixed in develop, Hybrid style
