### ISSUE TITLE
Common lisp mode bindings missing

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4135] opened 2015-12-10 13:43 UTC
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. eaf6b8c)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 dash elfeed erc finance gtags ibuffer mu4e org ranger
 (shell :variables shell-default-shell 'shell shell-default-height 50)
 spacemacs-layouts version-control git github c-c++ common-lisp emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml evil-cleverparens mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-mpc)
```

Common lisp `lisp-mode` major mode leader bindings are missing.  Only binding is `SPC m .` `erc-log-micro-state`.

**Comment by tuhdo** [comment] 2015-12-10 16:58
I can confirm this. It seems like `evil-leader/set-key-for-mode` is broken.

**Comment by justbur** [comment] 2015-12-10 17:38
They are there for me

**Comment by tuhdo** [comment] 2015-12-10 17:48
If you open the `.lisp` file before running `slime` command, the key bindings won't be there. You have to `M-x slime`, then run again for the key bindings to be available. The reason is that the slime configuration is only activated upon `slime-mode` command. It should be activated for `lisp-mode` as well.

**Comment by justbur** [comment] 2015-12-10 17:56
`slime-mode` is in `lisp-mode-hook` so this shouldn't be necessary. I just went into scratch and did `M-x lisp-mode` and everything was there, but I can verify the behavior you see. 

Also, you should find that if you open a .lisp file and run `M-x lisp-mode` everything shows up. I think this is a problem with the bindings being deferred in :config which isn't necessary and is supposed to be avoided because it makes it difficult for users to override them.

What I can do is make sure the bindings are activated even if they are bound after the major-mode is set up (they are activated through the after-change-major-mode-hook)

**Comment by justbur** [comment] 2015-12-10 20:17
This should be fixed if you update to the latest version of bind-map

**Comment by darkfeline** [comment] 2015-12-11 03:45
Confirmed fixed after package update, thanks.

**Closed** 2015-12-11 03:45 UTC
Labels: Key Bindings, Waiting for response

**Comment by zhexuany** [comment] 2015-12-27 10:30
@darkfeline  I have same problem here. When I type SPC-m, emacs tell me this key bindings is undefined. What is your configuration then? I am pretty sure, everything in my Mac is updated.

**Comment by StreakyCobra** [comment] 2015-12-27 12:02
@zhexuany What is the output of `SPC h d s` ? Have you updated the packages with the `update` button (on master) or the `update packages` button (on `develop`)?

**Comment by zhexuany** [comment] 2015-12-27 12:06
@StreakyCobra  To be exactly, this is only happened when I am not in lisp mode. If I use SPC : and chose lisp mode, everything works fine. How can I use the key bindings even I am not in lisp mode?

**Comment by StreakyCobra** [comment] 2015-12-27 12:18
@zhexuany Bindings under `SPC m` are mode-specific. They will be different under `python-mode` or `javascript-mode`, and not all mode defines bindings there. For instance there is not `SPC m` bindings on the `*Spacemacs*` home buffer.

**Comment by zhexuany** [comment] 2015-12-27 16:38
@StreakyCobra  I see your point. Thank for your kindly reply.
