### ISSUE TITLE
Ctrl-k doesn't go up in company dropdown menu

### ISSUE THREAD

**Issue by al3xandru** [syl20bnr/spacemacs#5817] opened 2016-04-17 07:26 UTC
#### Description
In the company popup, `C-k` doesn't go up but insert a `?`. `C-j` works as expected.

#### Reproduction guide
- Start Emacs
- Open .spacemacs
- Inside `user-config` write some code that brings up the company popup
- Navigate down using `C-j`
- Try to navigate up using `C-k`

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: develop (rev. edfc5de)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(spacemacs-ivy
 (spell-checking :variables spell-checking-enable-by-default nil)
 theming
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 emacs-lisp)
```

**Comment by al3xandru** [comment] 2016-04-17 07:30
Before removing almost all customizations from my .spacemacs, I was suggested to `C-h company-active-map`. The output https://gist.github.com/al3xandru/666785cb966bf884dec0569761d7bf72

**Comment by cpaulik** [comment] 2016-04-17 22:55
Possible duplicate or related https://github.com/syl20bnr/spacemacs/issues/2974

**Comment by al3xandru** [comment] 2016-04-18 03:20
Based on a comment from issue #2974 I've tried adding the following but it didn't fix the issue.

```
(evil-define-key 'insert company-active-map (kbd "C-k") 'company-select-previous)
```

**Comment by StreakyCobra** [comment] 2016-04-18 07:15
@al3xandru Does this happen with or without the `company-quickhelp-mode`?

**Comment by al3xandru** [comment] 2016-04-19 03:57
@StreakyCobra I don't know how to check for `company-quickhelp-mode`. I do have tooltips enabled.

**Comment by StreakyCobra** [comment] 2016-04-19 07:38
`SPC h d v company-quickhelp-mode RET`. If is says `Its value is t` it means it's activated, if it says `Its value is nil` then it isn't.

**Comment by al3xandru** [comment] 2016-04-20 01:37
`company-quickhelp-mode` seems to be on (value is `t`). Is this enabled by setting `auto-completion-enable-help-tooltip`?

**Comment by StreakyCobra** [comment] 2016-04-20 07:20
Ok, so it's indeed a duplicate of  https://github.com/syl20bnr/spacemacs/issues/2974. Can you report your last finding there :-) Thanks!

**Closed by StreakyCobra** 2016-04-20 07:20 UTC
Labels: - Bug tracker -, Auto-completion, Key Bindings
