### ISSUE TITLE
Emacsclient in terminal does not work / cannot close spacemacs after using client in terminal

### ISSUE THREAD

**Issue by duerrp** [syl20bnr/spacemacs#4700] opened 2016-01-20 02:37 UTC
#### Description
Starting spacemacs with `emacs` and using `emacsclient -t` the first time, everything is working as expected. 
On using `emacsclient -t` the second time, however, it fails (returning to the prompt immediately without any error). `toggle-debug-on-error` does not show anything either. 
Moreover, when I try to quit emacs after trying `emacsclient -t` more than once, I cannot do so and the error "apply: Device 1 is not a termcap terminal device" appears in the message buffer (again, `toggle-debug-on-error` does not yield anything).

I have no idea what the problem could be... can anyone reproduce the issue?
(I am using an Ubuntu 14.04, x86, using xmonad and urxvt)

#### Reproduction guide
- Start Emacs
- Run `emacsclient -t` in another terminal
- Run `emacsclient -t` in another terminal
- Try to close emacs (SPC q q)

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.9
- Spacemacs branch: nil (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 better-defaults
 (git :variables git-magit-status-fullscreen t magit-repo-dirs
      '("~/.repopi" "~/Dev")
      magit-repo-dirs-depth 3)
 version-control markdown
 (org :variables org-confirm-babel-evaluate nil)
 syntax-checking python nim
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 semantic gtags
 (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "johan-tibell")
 emacs-lisp racket
 (shell :variables shell-default-shell 'eshell shell-default-term-shell "/usr/bin/zsh")
 clojure lua
 (java :variables eclim-eclipse-dirs "~/Software/eclipse" eclim-executable "~/Software/eclipse/eclim")
 scala javascript latex puppet deft fasd
 (dash :variables dash-helm-dash-docset-path "~/.repopi/emacs-config/docsets")
 eyebrowse spacemacs-layouts dockerfile eww ob-ipython ipython-notebook
 (ranger :variables ranger-cleanup-on-disable t ranger-show-dotfiles nil ranger-show-literal t)
 spell-checking
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 unimpaired rcirc speed-reading evil-cleverparens literature peter)
```

Edit: @robbyoconnor thanks for the tip

**Comment by robbyoconnor** [comment] 2016-01-20 04:26
Please [follow this format](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) when reporting bugs. Currently you're missing some critical information here.

**Comment by duerrp** [comment] 2016-01-20 06:36
@robbyoconnor done, sorry

**Comment by robbyoconnor** [comment] 2016-01-20 06:42
Thank you :)

**Comment by phinicota** [comment] 2016-01-20 14:11
Not a solution but I'm currently using this without problems (the advantage is it will launch the daemon if needed):

    emacsclient -c -a ""

If you're interested in the terminal mode, I just tested this and it seems to be working too.

    emacsclient -t -c -a ""

**Comment by duerrp** [comment] 2016-01-20 23:59
@phinicota Thank you very much for testing. I tried `emacsclient -t -c -a ""` and unfortunately it does not work here... what's your emacs version?

**Comment by duerrp** [comment] 2016-01-21 03:39
@phinicota Seems your guess that it's related to my configuration is half-correct. `emacsclient -t` works with a default .spacemacs. However, on closing spacemacs after using the terminal client, "apply: Device 1 is not a termcap terminal device" still appears and closing fails, even with only default configuration.

I am now trying to figure out which layer / configuration causes the client to fail...

**Comment by duerrp** [comment] 2016-01-21 04:10
Getting there... I found the cause for the failing `emacsclient -t` in a key-binding (of all places):
```
 (define-key keym (kbd "M-]") 'corral-braces-forward)
```
(where `keym` comes from `(dolist (keym (list evil-normal-state-map evil-insert-state-map))`)

Maybe it's related to the M-] mapping to ESC in the terminal? Does anyone have an idea how to fix this?

**Comment by thang1thang2** [comment] 2016-01-21 06:48
I can confirm the issue with closing emacs after using a terminal client. I mentioned it in the gitter chat but I haven't (as of yet) gotten around to filling out a bug report. Seems I don't have to (yay).

# Current Setup:

```
# My systemd emacs.service file that automatically starts an emacs daemon is as follows:
# path is $HOME/config/systemd/user/emacs.service

[Unit]
Description=Emacs: the extensible, self-documenting text editor

[Service]
Type=forking
ExecStart=/usr/bin/emacs --daemon
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Restart=always

[Install]
WantedBy=default.target
```

```
#!/bin/bash
# this script is called "ec" for emacs client (GUI)
# Number of current visible frames,
# Emacs daemon always has a visible frame called F1
visible_frames() {
  emacsclient -a "" -e '(length (visible-frame-list))'
}

change_focus() {
  emacsclient -n -e "(select-frame-set-input-focus (selected-frame))" > /dev/null
}

# try switching to the frame incase it is just minimized
# will start a server if not running
test "$(visible_frames)" -eq "1" && change_focus

if [ "$(visible_frames)" -lt  "2" ]; then # need to create a frame
  # -c $@ with no args just opens the scratch buffer
  emacsclient -n -c "$@" && change_focus
else # there is already a visible frame besides the daemon, so
  change_focus
  # -n $@ errors if there are no args
  test  "$#" -ne "0" && emacsclient -n "$@"
fi
```

```
#!/bin/bash
# This script is called "et" for "emacs terminal"
TERM=xterm-256color

exec emacsclient -a "" -t "$@"
```

Here's my `ps aux | grep emacs` on a clean boot: 

```
MYNAME+   562  3.6  1.5 469356 127076 ?       Ssl  22:28   0:03 /usr/bin/emacs --daemon
MYNAME+  2435  0.0  0.0  10736  2232 pts/3    S+   22:30   0:00 grep emacs
```

And after I run my `ec` script to start up an emacs GUI, it's the same. After running my `et` script, however, I now have two windows open (emacs in terminal and emacs in GUI):

```
MYNAME+   562  3.5  2.0 655972 167964 ?       Ssl  22:28   0:06 /usr/bin/emacs --daemon
MYNAME+  3599  0.0  0.0   4212   820 pts/3    S+   22:31   0:00 emacsclient -a  -t
MYNAME+  3784  0.0  0.0  10736  2204 pts/2    S+   22:31   0:00 grep emacs
```
Typing `SPC-q-q` in emacs terminal kills both windows and I'm left with the same `ps aux | grep emacs` that I had on clean boot. Typing `SPC-q-q` in emacs GUI does the same result. `SPC-q-r` does not re-open any windows like I'd intuitively expect.

Next I tried using two terminal windows with two different emacs frames open with different files. `SPC-q-q` works perfectly. In fact, I currently cannot reproduce the issue at the moment. However, I know I did have the issue when I had `dotspacemacs-persistent-server t` on. On a hunch, I set it to nil before I started writing this post and I'm pretty sure that's where the issue is stemming from.

My guess is that the systemd management of emacs daemon + spacemacs managing a persistent server instance screws with stuff. I also recall reading somewhere that emacs [did not support multiple terminal devices at the same time](http://www.emacswiki.org/emacs/EmacsClient). Apparently this seems to be fixed, maybe?

----

For what it's worth, when I could reproduce the error, I couldn't quit emacs from the GUI through `SPC-q-q` but I could quit it from the terminal. My `ps aux | grep emacs` also showed about 2-3 different `emacs --daemon` processes and one `/usr/bin/emacs --daemon` (ie from systemd) process.

**Comment by syl20bnr** [comment] 2016-01-21 17:02
I hit it today but I don't know how to reproduce, does anyone have a repro step to share ?

**Comment by avdv** [comment] 2016-01-22 07:26
I also hit it yesterday.

A bit more info: the error comes frome [here](https://github.com/emacs-mirror/emacs/blob/master/src/dispnew.c#L5596), when calling the `send-string-to-terminal` function. Does this ring a bell to anyone?

**Comment by duerrp** [comment] 2016-01-22 07:48
@syl20bnr I get it consistently with the steps mentioned above:

1. Start emacs (spacemacs)
2. Start emacsclient -t from terminal, close it by `:q`
3. Repeat step 2.
4. In the original emacs, try `SPC qq`, observe error

Thanks to @thang1thang2 I now have a workaround: closing emacs from the terminal client works as expected...

**Comment by phinicota** [comment] 2016-01-22 14:20
@duerrp can confirm repro steps.
Launching emacs --daemon first (instead of emacs) and then all the desired emacsclient -c or emacsclient -t seems to avoid the issue though.

**Comment by mkomitee** [comment] 2016-01-22 18:35
I can confirm as well.

**Comment by gour** [comment] 2016-02-08 21:14
Same here...have to kill it to close it.

**Comment by mkomitee** [comment] 2016-02-08 22:35
@gour you can close it with `SPC qq` in a terminal client.

**Comment by gour** [comment] 2016-02-09 09:53
@mkomitee I'll try, but for now the above-mentioned steps referenced by @duerrp do not reproduce the problem here...

**Comment by gour** [comment] 2016-02-09 09:58
@mkomitee confirmed. starting another client from terminal, closes it.

**Comment by avdv** [comment] 2016-04-07 10:14
I digged a bit deeper into this.

The problem is the `bracketed-paste--tty-state-exit-hook` entry in `kill-emacs-hook` which tries to send `"\e[?2004l"` to the TTY display.

This hook entry does not exist when first starting Emacs, it only gets added when using `emacsclient -t` a second time.

Seems to be a bug in bracketed-paste then, right?

**Comment by StreakyCobra** [comment] 2016-04-07 10:59
You can try to reproduce on a stock emacs with just bracketed-paste, this will tell you if the problem if coming from this or if it is more complex.

**Comment by avdv** [comment] 2016-04-07 11:25
> You can try to reproduce on a stock emacs with just bracketed-paste, this will tell you if the problem if coming from this or if it is more complex.

Yep, seems to be the case.

1. start `emacs -q`

2. run

   ```elisp
   (server-start)
   (load-file "~/.emacs.d/elpa/bracketed-paste-20140222.1801/bracketed-paste.elc")
   (bracketed-paste-enable)
   ```

3. run `emacslient -t`

This adds the `bracketed-paste--tty-state-exit-hook` entry to the kill hook and you cannot close emacs from the X11 client.

**Comment by aaronjensen** [comment] 2016-04-07 13:34
fwiw, this is a workaround:

```elisp
(defadvice bracketed-paste--tty-state-exit-hook (around fix)
  "This hook fails if the selected frame is graphical, so prevent it"
  (unless (display-graphic-p)
    ad-do-it))
(ad-activate 'bracketed-paste--tty-state-exit-hook)
```

**Comment by aaronjensen** [comment] 2016-04-08 00:23
Looks like bracketed paste support is built into 25, so should we exclude this package for 25+? Also, this was fixed upstream thanks to @avdv 

https://github.com/hchbaw/bracketed-paste.el/pull/3#issuecomment-207147163

**Comment by StreakyCobra** [comment] 2016-04-08 08:46
Yes, I think we can safely guard the use-package to emacs < 25 conditional

**Comment by aaronjensen** [comment] 2016-04-10 05:34
@StreakyCobra done: https://github.com/syl20bnr/spacemacs/pull/5746

**Closed** 2016-08-28 19:12 UTC
Labels: Bug :-(, Fixed upstream, Running as daemon
