### ISSUE TITLE
"dotspacemacs-auto-save-file-location" not triggering "after-save-hook"?

### ISSUE THREAD

**Issue by vicmortelmans** [syl20bnr/spacemacs#16432] opened 2024-06-03 20:46 UTC
#### Description :octocat:
I want to sync the files in my project on github using `auto-save` and `git-auto-commit-mode`.

My dotspacemacs has:

`   dotspacemacs-auto-save-file-location 'original`

and:

`   dotspacemacs-additional-packages '(git-auto-commit-mode)`

and in user-config:
```
  (setq-default gac-ask-for-summary-p nil)
  (setq-default gac-automatically-push-p t)
  (setq-default gac-silent-message-p t)
```
The files I want to sync are in a git repo and contain in the header:

`;; -*- eval: (git-auto-commit-mode 1) -*-`

When I manually save, it works, but when an open file is auto-saved, no commit is happening.

`git-auto-commit-mode` relies on the `after-save-hook`. Can it be that auto-save isn't triggering this hook?

#### Reproduction guide :beetle:
- Start Emacs
  1. open file
  2. edit
  3. wait for auto-save

*Observed behaviour:* :eyes: :broken_heart:
File is saved, but not committed.

*Expected behaviour:* :heart: :smile:
File is saved and committed.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.3
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 9cddd1543)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            version-control treemacs tabs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by fnussbaum** [comment] 2024-06-05 13:14
Thanks for reporting. This seems to be the same issue as https://github.com/ryuslash/git-auto-commit-mode/issues/32, so you could probably solve it in your configuration by using `auto-save-visited-mode` instead of the `dotspacemacs-auto-save-file-location 'original` option. 

Of course this should also (or rather instead) be addressed in Spacemacs, we should not use the deprecated option `auto-save-visited-file-name` anymore.

**Comment by smile13241324** [comment] 2024-06-12 16:17
I think the root cause is that spacemacs is using an outdated mode for auto saving, lets change this on the Spacemacs level.

**Closed as completed** 2024-06-12 18:09 UTC
