### ISSUE TITLE
Hydra 

### ISSUE THREAD

**Issue by okaoka337** [syl20bnr/spacemacs#13678] opened 2020-06-16 00:04 UTC
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by duianto** [comment] 2020-06-25 08:05
Could you provide more information about the issue your having, or if this was opened by mistake, then you can close it.

**Comment by smile13241324** [comment] 2020-07-02 23:36
No answer after 8 days and the issue is completely empty, therefore I will close it now. @okaoka337 feel free to open a new one with proper content from `SPC SPC spacemacs/report-issue` if you still require help.

**Closed by smile13241324** 2020-07-02 23:36 UTC
