### ISSUE TITLE
NeoTree breaks eyebrowse

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3306] opened 2015-10-08 16:34 UTC
If you have neotree open, and try to switch workspaces via `SPC W [num]`, it will fail.  The only window that will be left open is neotree, and you can't switch away from it with eyebrowse, nor can you close it.  You have to change buffers entirely.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion emacs-lisp git gtags yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors eyebrowse
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by TheBB** [comment] 2015-10-08 17:07
I can't reproduce this. Eyebrowse and neotree work well together for me.

**Comment by synic** [comment] 2015-10-08 18:29
Just tried it on develop, same thing happens.  I am opening NeoTree via `SPC p t`.  Then, I try to switch via `SPC W [num]`.   This is what I see after that (there used to be another window opened on the right): http://d.pr/i/rglO/1zxLyYlN

**Comment by bmag** [comment] 2015-10-08 18:40
See https://github.com/wasamasa/eyebrowse/issues/36 and https://github.com/syl20bnr/spacemacs/issues/2008. This is a bug in Emacs that will be fixed in Emacs 25.1 (next major release). Eyebrowse has a work-around for Emacs 24.5.1 and older, but you have Emacs 24.5.7 so the work-around is not applied. When the bug was fixed, 24.5.1 was the latest release in the 24.5.x line. I've posted on https://github.com/wasamasa/eyebrowse/issues/36 and it will probably be fixed soon (last time the author fixed it within two days :smile:)

**Comment by wasamasa** [comment] 2015-10-08 18:43
I've set a new record, fixing it in under fifteen minutes :sunglasses:

**Comment by TheBB** [comment] 2015-10-08 18:45
Cool cool cool!

**Closed by TheBB** 2015-10-08 18:45 UTC
Labels: bug :-(, Fixed upstream

**Comment by synic** [comment] 2015-10-09 13:48
There is still various issues with this.  Sometimes when you have NeoTree open, and you switch to a new workspace, neotree ends up on top of a horizontal split.  Sometimes, after switching workspaces, if you try to close neotree, it just opens up a new one to the right of the old one.

**Comment by ignu** [comment] 2017-01-03 07:20
huh. i just started seeing this out of nowhere.
