### ISSUE TITLE
Adapt Helm to use flx for better fuzzy matching

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#3327] opened 2015-10-10 09:18 UTC
I already created [this thread](https://www.reddit.com/r/emacs/comments/3o7a9i/using_helm_with_flx_for_better_fuzzy_matching/) on Reddit. If you already use `ido`, you know that `flx` vastly improve Emacs experience.

**Comment by bmag** [comment] 2015-10-10 11:37
Using `flx` in Helm will be awesome, but are you sure this works as expected? When using `smex`, if I type "em" then `eldoc-mode` is the first result, but when using `helm-M-x`, typing "em" gives `evil-mode` as the first result and `eldoc-mode` is only the second. When looking at "Emacs Command History" candidates before I type any input, I see that `eldoc-mode` is much higher (more recent) than `evil-mode`, so why don't I get `eldoc-mode` as the first result?

**Comment by tuhdo** [comment] 2015-10-10 12:26
Yes I'm sure it works, and works as you described. But you must not execute `evil-mode`, so it does not appear in command history and is prioritised higher. A better way is to compared between before and after this tweak is added. Before adding, typing `hpa` gives candidates like `w[h]at-[pa]ge`, `c[h]eck-[pa]rens`....; after adding, typing `hpa` gives `[h]elm-[p]rojectile-[a]g` (characters in `[]` are highlighted)..

**Comment by d12frosted** [comment] 2015-10-13 14:12
Wow. Nice thing. Any chance that it will be part of Spacemacs?

**Comment by ReneFroger** [comment] 2015-10-14 20:59
Any update on this?

**Comment by tuhdo** [comment] 2015-10-15 02:45
We can easily update now. @PythonNut added a package for it: https://github.com/PythonNut/helm-flx

**Comment by d12frosted** [comment] 2015-10-15 08:18
Great to hear.

**Comment by TheBB** [comment] 2015-10-15 14:23
#3414

**Comment by CestDiego** [comment] 2015-10-17 19:14
are we doing this? <3 I see nobody objected this.

**Comment by TheBB** [comment] 2015-10-18 09:51
The PR is up there at least.

**Comment by herbertjones** [comment] 2015-10-22 05:15
Unfortunately it appears that `helm-flx` has a poor runtime growth rate.  As the input buffer size grows larger than 20, there is a visible slowdown.  To test, `SPC b b`, then type a single character about 20 times.  Each time the character is entered, the `helm mini` buffer takes approximately twice as much time as the previous press to update the display which indicates a growth rate of `2^n`.

**Comment by tuhdo** [comment] 2015-10-22 06:29
I do not have this issue, even for 50k candidates, on both OS X/Linux. I am also using latest develop. Maybe you should try on stock Spacemacs to see if the problem occurs?

**Comment by herbertjones** [comment] 2015-10-22 13:26
@tuhdo You repeated a single character into the input buffer 25 times and got 50k candidates?  I don't think you are talking about the same input as I am.  I am talking about the length of the input field.  Of course, for `helm mini` it isn't normal to take 25+ keystrokes before finding what you are looking for.  However, in `Helm Find Files`, attempting to recurse down a deep directory hierarchy is normal, as is trying to use `Helm Find Files` to create a new file, perhaps one with a name longer than 25 characters.  Unfortunately in that situation this plugin doubles the amount it takes to react for each character in the filename or directory path entered, eventually timing out around 25 characters.  This makes helm break before entering the filename, so that `Helm Find Files` can't be used to create new files that have long filenames, or are in a deep directory hierarchy.

I have completely wiped my `.spacemacs` and `.emacs.d` directory and reproduced the issue.  The issue is more apparent on OSX, as it locks up the GUI, unlike on Linux.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 47ce170)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp git)
```

**Comment by TheBB** [comment] 2015-10-22 13:45
Surely `helm-find-files` shouldn't be testing against the whole path, but rather the last part (the after the last forward slash, that is)?

I can reproduce the issue though. Basically what I did:

```sh
cd ~
mkdir yolloyollo && cd yolloyollo
# Repeat about 20 times
```

Then go to `helm-find-files` and try to navigate to the end of `~/yolloyollo/.../`. Good luck. I can make it about four or five levels in before it gives up.

**Comment by CestDiego** [comment] 2015-10-22 13:46
if you are gonna type the whole path, why use fuzzy search?

**Comment by TheBB** [comment] 2015-10-22 13:48
I can't even `C-l` my way to the end. No typing necessary.

**Comment by PythonNut** [comment] 2015-10-22 20:10
@TheBB @herbertjones 

See https://github.com/lewang/flx/pull/75.

**Comment by tuhdo** [comment] 2015-10-23 03:17
I still can't reproduce according to @TheBB instructions. In this demo, you can see that when I type `elm`, `helm-M-x` gave me `evil-local-mode`, `eldoc-mode`...., it means `helm-flx-mode` is activated. Beside, I am using veresion 105.x. Then, I tried to go down the yolo directories as much as I could, but I could not see any slow down on update:

![test](https://cloud.githubusercontent.com/assets/4818719/10683659/8d9abe2c-796e-11e5-8418-5df6099da77a.gif)

However, @PythonNut confirmed this issue and made a fix, so it did exist and I'm glad it got fixed so quickly.

**Comment by PythonNut** [comment] 2015-10-23 03:27
Admittedly, I haven't reproduced the bug myself either. I do know that flx has horrible asymptotic complexity over the length of the input. 

I assume that you need to invoke a recursive file finder to run into the bug.

**Comment by AlKapote** [comment] 2015-10-23 22:01
Note that helm-flx won't give good results when the number of matches exceeds `helm-candidate-number-limit`, because helm will only pass helm-flx the first LIMIT matches it finds, no matter their quality. 

https://github.com/emacs-helm/helm/issues/1237
https://github.com/emacs-helm/helm/pull/1238

**Comment by PythonNut** [comment] 2015-10-24 05:26
@AlKapote thanks. I'm glad to see this being worked on. It's been in the back of my mind as a sort of mathematical bugaboo for a while.

@Tudyk do note that I'd be totally okay with adding advise to `helm-flx` if we can't merge it into `helm` proper.

**Comment by robbyoconnor** [comment] 2015-10-24 07:21
@PythonNut -- @tuhdo is the a ninja with `helm` -- he knows what he's saying/doing :D

**Comment by cpaulik** [comment] 2015-10-24 09:35
Helm-flx seems to break some helm features for me. 

Compare the two situations on the screenshot below. On the left is `helm` and on the right `helm`+`helm-flx`.
- helm-flx removes the colors for directories, symlinks etc.
- helm-flx makes it harder to distinguish between e.g. a new file `tes` entered below and marked with `?` in original helm
- helm-flx shows the full path for some reason.
![20151024112603](https://cloud.githubusercontent.com/assets/380927/10709966/44dea00c-7a42-11e5-9ee8-82f6a5dcde00.png)

This is on latest develop with 
`helm-20151023.1330` and `helm-flx-20151023.2240`

**Comment by TheBB** [comment] 2015-10-24 09:40
Yeah, that's unfortunate. I see the same, and I had to update packages this morning to reproduce it, so it must be a recent change.

**Comment by TheBB** [comment] 2015-10-24 09:41
@PythonNut I assume it's due to https://github.com/PythonNut/helm-flx/commit/bf4943ef45491a5985aeb224ef9d7d8c7324c30f.

**Comment by TheBB** [comment] 2015-10-24 09:49
(advice-remove 'helm-ff-sort-candidates 'helm-flx-helm-ff-sort-candidates)

Works around it for now.

**Comment by PythonNut** [comment] 2015-10-24 14:55
@cpaulik @TheBB should be fixed now, sorry.

> PythonNut -- tuhdo is the a ninja with helm -- he knows what he's saying/doing :D 

@robbyoconnor no of course. Everyone knows tuhdo is a ninja. However, the process for getting code merged into `helm` can be very... interesting.

**Comment by TheBB** [comment] 2015-10-24 15:25
Thanks!

> However, the process for getting code merged into helm can be very... interesting.

Oh, I believe you. :-/

**Comment by PythonNut** [comment] 2015-10-24 16:01
You guys may be interested in [disabling `helm-find-files` support](https://github.com/PythonNut/helm-flx/commit/d23420182a3dfe19ef1604804d3d47a2beb2c6de) until the bugs are worked out.

**Comment by TheBB** [comment] 2015-10-24 17:26
Appreciate it.

Related commit: https://github.com/syl20bnr/spacemacs/commit/e776ada203390fd3655423ac5e2ed8ebb2391a6c

The update hasn't reached MELPA yet but it'll catch on when it does.

**Comment by Alk-a** [comment] 2015-10-25 21:44
> However, the process for getting code merged into helm can be very... interesting.

I just learned this the hard way when trying to fix the problem from https://github.com/syl20bnr/spacemacs/issues/3327#issuecomment-150703170. 

After spending a couple of days addressing his concerns I asked him if there was anything else that needed to be done. His reply was that although he hasn't really had time to look at the code, it still has (unspecified) "errors", that he suspects performance is bad (It's fine, he didn't actually try it), and that he really thinks a better way to fix the problem would be... to implement exactly what I described, explained, and implemented.  Sorry, life's too short. I tried...

**Comment by PythonNut** [comment] 2015-10-26 01:57
@ghost would you like to push the changes to `helm-flx` in the form of advice?

**Comment by EphramPerdition** [comment] 2015-10-26 19:20
@PythonNut, thanks, It's a package now (Please Ignore my shifting username):

https://github.com/EphramPerdition/helm-fuzzier

The README recommends it be used together with `helm-flx`.

I'd like a few folks to try it out and report whether it breaks something for them before pushing it to MELPA. 

`helm-fuzzier` together with `helm-flx` *finally* makes Helm do what I mean.

**Comment by TheBB** [comment] 2015-10-26 19:36
@EphramPerdition Thanks, I'm trying it out. So far so good.

**Comment by EphramPerdition** [comment] 2015-10-26 20:19
Great, "works for me" is just as useful as a bug report at this point.

**Comment by PythonNut** [comment] 2015-10-26 20:39
@EphramPerdition

> The README recommends it be used together with `helm-flx`.

Is there any case where you would use`helm-fuzzier` without `helm-flx`?

**Comment by EphramPerdition** [comment] 2015-10-26 20:52
@PythonNut, you can use it without `helm-flx`, sure. The results should be better then vanilla helm,
even without `helm-flx`. 

Note that each of these packages touches a different part of helm. `helm-fuzzier` improves matching, and `helm-flx` improves the scoring. You might conceivably want to swap one and not the other for something you like better.

**Comment by PythonNut** [comment] 2015-10-28 22:52
As of https://github.com/lewang/flx/pull/78, `flx`, should now have substantially improved asymptotic complexity.

**Closed** 2016-01-04 08:43 UTC
Labels: enhancement :-D, Fixed in develop, Helm
