### ISSUE TITLE
Blank powerline when switching between frames using other-frame / C-x 5 o.

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#4417] opened 2016-01-05 12:42 UTC
Powerline blanks out if the frame is not in focus and remains completely blank until I activate a different frame with the mouse cursor.

I'm using Emacs from the standard brew formula: `emacs: stable 24.5 (bottled), HEAD`, `Built from source with: --with-cocoa --with-gnutls --with-imagemagick --with-librsvg --with-mailutils`

**Comment by TheBB** [comment] 2016-01-05 14:13
Can't reproduce. Please let me know the error you get (in the `*Messages*` buffer).

**Comment by TheBB** [comment] 2016-01-05 14:35
I'm guessing this is a duplicate of #4413.

**Comment by 3rd3** [comment] 2016-01-05 15:44
I've updated to 0.105.1 but the bug persists. Sometimes even clicking does not help.

**Comment by 3rd3** [comment] 2016-01-05 15:49
Didn't read it carefully enough, only 0.105.2 will fix it. This issue can be closed as duplicate of #4413.

**Comment by TheBB** [comment] 2016-01-05 16:09
If you could actually tell me the error you are getting I could tell you for sure.

**Comment by syl20bnr** [comment] 2016-01-05 18:04
> only 0.105.2 will fix it

You've got a DeLorean ? Version `0.105.2` has just been published, it was not 2 hours ago. :-)

**Comment by StreakyCobra** [comment] 2016-01-05 18:24
Closing as duplicate then :-)

**Closed by StreakyCobra** 2016-01-05 18:24 UTC
Labels: Mode Line, to be reproduced
