### ISSUE TITLE
Parinfer Layer Functionality Impeded

### ISSUE THREAD

**Issue by hrestey** [syl20bnr/spacemacs#15921] opened 2023-02-16 05:52 UTC
I recently switched to Spacemacs as a Clojure editor. I have installed the Parinfer layer for improved fluidity of editing the structure of lisp code, but I am unable to use tabs to change the indentation in Indent Mode, as described in this [reddit post](https://www.reddit.com/r/spacemacs/comments/icoahm/parinfer_and_tab_in_insert_mode/). Paren Mode seems to work just fine.

I have added the following lines to `dotspacemacs/user-config` without effect:
```
(use-package parinfer-rust-mode
    :hook clojure-mode)
(setq-default tab-always-indent t)
```

Also, an issue that does not break functionality but does make things a little more confusing is that there is currently no way to tell whether you are in Indent Mode or Paren Mode (at least in terminal, I haven't checked with the GUI).

**Comment by lebensterben** [comment] 2023-02-16 06:51
I actually never used tab for indentation.....

why do you want to manually control indentation level?

**Comment by hrestey** [comment] 2023-02-16 14:49
Parinfer takes the general style rules that most Lisps follow for parenthesis placement and indentation and automates the management of that. If I'm writing a block of code in Clojure and I decide to go and refactor it, Parinfer makes it so much more fluid to do so it's not even funny. There is a good demonstration of Parinfer [here](https://shaunlebron.github.io/parinfer/). But in short, manually controlling indentation level in conjunction with this tool gives me much more freedom and flexibility in writing code.

**Comment by lebensterben** [comment] 2023-02-16 18:02
you can simply use space instead of tab.

**Comment by hrestey** [comment] 2023-02-16 19:44
That would be a simple alteration to get the whitespace, yes, but unfortunately I tried it, and it does not really seem to work. If I want to edit a piece of code like this:
```
(let [a (assoc {:a 1 :b 2} :c 3)
        ])
```
into a piece of code that looks something like this:
```
(let [a (assoc {:a 1 :b 2}
               :c 3
               :d 4)])
```
It won't actually allow me to space the closing square-bracket on the second line past where the leading parens in the `(assoc ...)` expression is. Therefore Parinfer won't dynamically move the closing parens to the second line to wrap any new elements I want to add to that expression. Not a huge deal with a simple bit of code like this, but if you have something more complex, for example this reduce expression: 
```
(let [word-frequency (reduce #(assoc %1 %2 (inc (%1 %2 0))) {} (re-seq #"\w+" s))])
```
It becomes much more difficult to manage. When I write more complex statements like this on the fly, I tend to jump around the expression a lot as I think through the problem. Being able to manually manipulate indentation and by extension parenthesis placement by hitting tab and back-tab a few times is really helpful.

**Comment by lebensterben** [comment] 2023-02-16 20:01
I completely don't understand what you're doing.

1. Start with
```clojure
(let [a (assoc {:a 1 :b 2} :c 3)])
```
2. Move the point before `:c`, and press <kbd>RET</kbd>
```clojure
(let [a (assoc {:a 1 :b 2}
               :c 3)])
```
3. Move the point before the closing parenthesis after `:c 3`, and press <kbd>RET</kbd>, and enter `:d 4`
```clojure
(let [a (assoc {:a 1 :b 2}
               :c 3
               :d 4)])
```

**Comment by hrestey** [comment] 2023-02-16 20:04
OK, yeah, I see why you're confused, it's hard to grasp what this is with just the static text. The Parenfer [demo](https://shaunlebron.github.io/parinfer/#indent-mode) does a much better job of showing what this does.

**Comment by lebensterben** [comment] 2023-02-16 20:05
Note that, normally <kbd>TAB</kbd> binds to `indent-for-tab-command`, which

> Indent the current line or region, or insert a tab, as appropriate.

Pressing <kbd>TAB</kbd> has no effect because the indentation isn't wrong in the first place.

**Comment by hrestey** [comment] 2023-02-16 20:09
Right, that's what I surmised the issue is. Spacemacs thinks "this expression is properly formatted, don't insert new indentation", but I want to change the structure of some code, perhaps a heavily nested data structure, or something like that, and it's about moving from one correctly formatted piece of code to another, equally correct piece of code. Parinfer just makes that process a lot smoother. But I haven't found any option to remove that kind of limit. The `clojure-mode` indentation options are all about different conventions for indentation, but at the end of the day there is still code saying "don't allow indentation that doesn't conform with the structure of the existing code". Which appears to be applied to space as well as tab.

**Comment by lebensterben** [comment] 2023-02-16 20:23
The link you pointed to has two problems.

First it's `parinfer` not `parinfer-rust`. This is minor, but there's no guarantee the two libraries behave the same.

Second, the instruction is talking in a editor-agnostic way and it certainly doesn't apply to Emacs.

> Spacemacs thinks "this expression is properly formatted, don't insert new indentation"

This has nothing to do with Spacemacs. This is the behaviour of Emacs.

<kbd>TAB</kbd> binds to `indent-for-tab-command`. The indenting behaviour is controlled by the variable `indent-line-function`, and in `clojure-mode` it's `clojure-indent-line`.

**Comment by lebensterben** [comment] 2023-02-16 20:27
Use `C-q TAB` to insert TAB.

See https://www.gnu.org/software/emacs/manual/html_node/emacs/Inserting-Text.html

**Comment by hrestey** [comment] 2023-02-17 20:59
My man I gotta be honest with you, I'm very unfamiliar with Spacemacs, and I've never used Emacs. I really don't know much about how configuration works within this space. I've been reading a lot of documentation on how it works, but there's a ton of info to get lost in there when I really am just trying to figure out how to have it change one bit of behavior that's interrupting my workflow. I'm sure you're busy, but do you think you can take some time to help me understand what it is exactly I need to change, and where, to get this working well? `C-q TAB` is a great start but it's difficult to work that into a smooth workflow.

**Comment by lebensterben** [comment] 2023-02-17 21:06
closing since this is not a bug.

**Closed as not planned** 2023-02-17 21:06 UTC
