### ISSUE TITLE
Duplicated layer warnings for private layers

### ISSUE THREAD

**Issue by dubnde** [syl20bnr/spacemacs#7481] opened 2016-10-19 10:55 UTC
#### Description :octocat:

I keep on observing multiple warnings for my layers in the `dotspacemacs-configuration-layer-path`.
It appears spacemacs searchs `.spacemacs.d/layers` and then `.spacemacs.d/` so will always finds
private layers twice

Actually the warnings are observed even when the private layers are not added to the layers list
#### Reproduction guide :beetle:
- Start Emacs
- Configure private layers in `dotspacemacs-configuration-layer-path`.

_Observed behaviour:_ :eyes: :broken_heart:
Warnings as the example below are observed for each layer in the folder

```
- Duplicated layer my-ycmd detected in directory "$HOME/.spacemacs.d/layers/my-ycmd",
  replacing old directory "$HOME/.spacemacs.d/layers/my-ycmd/" with new directory.
```

_Expected behaviour:_ :heart: :smile:
No such warnings as above should be observed
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. b550945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t :disabled-for shell erc)
 (c-c   :variables c-c  -enable-clang-support t c-c  -default-mode-for-headers 'c  -mode)
 (colors :variables colors-colorize-identifiers 'variables)
 cscope emacs-lisp evil-cleverparens evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 fasd git graphviz html
 (ibuffer :variables ibuffer-group-buffers-by 'projects ibuffer-show-empty-filter-groups nil)
 imenu-list java javascript markdown osx pdf-tools python semantic
 (shell :variables shell-enable-smart-eshell t shell-default-full-span nil)
 shell-scripts spell-checking syntax-checking
 (typography :variables typography-enable-typographic-editing t)
 version-control vimscript windows-scripts yaml my-c-c   my-ycmd my-org my-uml)
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment] 2016-10-19 14:58
> It appears spacemacs searchs .spacemacs.d/layers and then .spacemacs.d/ so will always finds
private layers twice

Did you add one of these to the search path? You shouldn't have to.

**Comment by dubnde** [comment] 2016-10-19 15:02
I originally had. Removed it and still see warnings. 

Even when I remove the layer from the list of layers still shows the warnings. I can see https://github.com/syl20bnr/spacemacs/pull/7482 addressing this issue

**Comment by TheBB** [comment] 2016-10-19 15:30
> Even when I remove the layer from the list of layers still shows the warnings. 

Well of course, this has nothing to do with *used* layers.

**Comment by dubnde** [comment] 2016-10-19 17:55
@TheBB thanks.

**Comment by jupl** [comment] 2016-10-19 18:50
I have the same issue and I haven't touched the search path.

**Comment by zilongshanren** [comment] 2016-10-20 01:56
+1 for the issue, I also don't touch the search path...

**Comment by hershal** [comment] 2016-10-20 01:57
+1 for the issue

**Comment by TheBB** [comment] 2016-10-20 10:07
Guys, please add a :+1: to the OP instead of spamming with +1 messages.

**Comment by bmag** [comment] 2016-10-20 10:09
I can reproduce it as well, by creating a new private layer `mylayer` with an empty `mylayer-packages` inside of `~/.spacemacs.d/layers/` directory. #7482 seems to fix this.

**Comment by TheBB** [comment] 2016-10-20 10:12
I have several layers there already and can't reproduce it, however the PR is harmless enough so I've merged it.

**Comment by dubnde** [comment] 2016-10-21 09:21
I am still able to reproduce this in `develop` branch even though it says `Fixed in develop`. What am I missing?

**Comment by TheBB** [comment] 2016-10-21 10:11
I forgot to push. :sob:

**Comment by dubnde** [comment] 2016-10-21 10:29
thanks

**Comment by syl20bnr** [comment] 2016-12-25 20:15
We were adding some directories multiple times, I made some cleanup in commit: https://github.com/syl20bnr/spacemacs/commit/f5957eb

**Closed** 2017-04-02 06:03 UTC
Labels: - Bug tracker -, Fixed in develop
