### ISSUE TITLE
install package evil-unimpaired error (wrong-type-argument package-desc nil)

### ISSUE THREAD

**Issue by sniperhalo** [syl20bnr/spacemacs#9653] opened 2017-09-26 10:14 UTC
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by CeleritasCelery** [comment] 2017-09-30 05:51
Should should follow the instructions you just posted.

**Comment by garriguv** [comment] 2017-10-02 10:21
I ran into the same issue. Deleting the cache and restarting Emacs fixed it:

```
rm -rf /Users/$(whoami)/.emacs.d/.cache/
```

**Comment by duianto** [comment] 2017-10-02 12:02
This is a duplicate of several evil-unimpaired issues that mention the same error message.

A likely source of the issue is described here: https://github.com/syl20bnr/spacemacs/issues/8901#issuecomment-304492105

It states that downloading evil-unimpaired between midnight and 1AM, adds two zeros `00`, to the beginning of the package timestamp, but only one of the zeros is removed.

**Comment by garriguv** [comment] 2017-10-02 12:48
@duianto wow, thanks for the link. That's a great bug!

We can probably close this issue now that there's a link to the original issue.

**Closed** 2017-10-06 06:44 UTC

**Comment by froderick** [comment] 2018-01-22 06:07
I just ran into this. Glad I found this issue, I was really puzzled.
