### ISSUE TITLE
Key binding isn't working when reading README.org

### ISSUE THREAD

**Issue by Arbitrageur** [syl20bnr/spacemacs#3596] opened 2015-10-29 16:42 UTC
Problem: 
Key bindings like 'gj', 'gh' and 'gk' is not workinging in Org-mode

Description:
Start a new emacs and press 'SPC f e h.'
Type 'python' and press RET. Then README.org will be opened.
But keybindings for org-mode is not working.
However, after entering 'insert-state' and coming back to 'normal-state', key bindings are working.

**Comment by TheBB** [comment] 2015-10-29 17:19
I can't reproduce this. These bindings work out of the box for me, no state changes necessary.

**Comment by sooheon** [comment] 2015-11-02 06:03
Also cannot reproduce. Curious what state it could be in that it doesn't work initially and only works after entering insert state?

**Comment by Arbitrageur** [comment] 2015-11-03 07:44
I don't think that the previous state matters. 
As I tested several times, I found that when I open any org files, key bindings are not activated.
However, after changing the state to insert state or emacs state, key bindings are activated.
Also, pressing ESC activates key bindings.

I'm using OS X 10.11.1 and railwaycat/emacs-mac from homebrew

**Comment by TheBB** [comment] 2015-11-11 07:07
I was just made aware of #2615, so closing this as duplicate.

**Closed by TheBB** 2015-11-11 07:07 UTC
Labels: duplicate (-: :-), Org, to be reproduced

**Comment by Arbitrageur** [comment] 2015-11-25 15:32
Glad to hear that it's been fixed in develop.

Btw, it's been fixed by removing org layer from .spacemacs file and adding the layer back.
