### ISSUE TITLE
"t" for org-todo stopped working in org-mode

### ISSUE THREAD

**Issue by kepi** [syl20bnr/spacemacs#9305] opened 2017-07-29 16:13 UTC
#### Description :octocat:
I'm not able to use "t" key to switch todo states of current heading in org-mode

I hope that this is only not intended side effect and not "yet another rebinding (TM)" which happens in last months in org-mode.

This problem was introduced in c533605df08bfd60b1c58ce8b9312454bc9c1cc4

I'm all in for nice "<leader>TT" shortcut but please leave it for those who don't work with org-mode on regular basis and need to discover this key. I think both shortcuts can work simultaneously without any problem.

#### Reproduction guide :beetle:
- Start Emacs
- open any org document with some heading
- go to heading
- press "t"

*Observed behaviour:* :eyes: :broken_heart:
After pressing "t" nothing happens

*Expected behaviour:* :heart: :smile:
After pressing "t" I'm able to choose desired todo state.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 4c00e3ad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(nginx go html
       (sql :variables sql-capitalize-keywords t)
       vimscript python
       (ivy :variables ivy-initial-inputs-alist
            `((org-refile . "")
              (org-agenda-refile . "")
              (org-capture-refile . "")
              (counsel-M-x . "")
              (counsel-describe-function . "")
              (counsel-describe-variable . "")
              (man . "")
              (woman . "")))
       emacs-lisp
       (auto-completion :variables auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
       (org :variables org-enable-reveal-js t)
       pandoc
       (kepi-mu4e :variables mu4e-enable-mode-line t)
       (kepi-groovy)
       ansible git
       (ruby :variables ruby-version-manager 'rbenv)
       javascript react vagrant
       (haskell :variables haskell-completion-backend 'intero)
       php purescript markdown pdf-tools ess shell-scripts syntax-checking elm
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by d12frosted** [comment] 2017-07-29 16:28
You might want to set `org-want-todo-bindings` to `t`. 

```
  (org :variables org-enable-reveal-js t org-want-todo-bindings t)
```

**Comment by d12frosted** [comment] 2017-07-29 16:30
Actually, duplicate of https://github.com/syl20bnr/spacemacs/issues/8640. So closing this one. Let me know if proposed solution doesn't work for you.

**Closed by d12frosted** 2017-07-29 16:30 UTC
Labels: - Forum -, Key Bindings, Org
