### ISSUE TITLE
Auto-completion for yasnippet and python not working after certain commit

### ISSUE THREAD

**Issue by myme5261314** [syl20bnr/spacemacs#10603] opened 2018-04-19 08:28 UTC
#### Description :octocat:
Seems the commit 81a931f48bdd6bcca4fdf0a3baab7b4bd7695591 on develop branch made the auto-completion(code completion and yasnippet part) for python. And there will be one python interpreter icon stuck on the dock plane for each *.py file you opened.

#### Reproduction guide :beetle:
- checkout spacemacs to commit 81a931f48bdd6bcca4fdf0a3baab7b4bd7695591 
- Start Emacs
- Open one or two python file.
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
you type some snippet keywords such as `main` or `fd`, no auto-completion triggered at all. And if you open two python files, there will be two python interpreter icon(a rocket?) stuck on the dock plane (maybe with jump).

*Expected behaviour:* :heart: :smile:
auto-completion works and no stucked icon on dock plane.
auto-completion will work at commit 66afcce4d1512382daba5a15b35df0b2e3ca2734 (previous commit of 81a931f48bdd6bcca4fdf0a3baab7b4bd7695591), but the icon still stucked.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: temp (rev. 66afcce4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby ruby-on-rails docker nginx csv javascript helm better-defaults github
      (version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t)
      semantic markdown
      (vinegar :variables vinegar-reuse-dired-buffer t)
      (org :variables org-projectile-file "TODOs.org")
      prodigy search-engine
      (syntax-checking)
      (spell-checking)
      yaml python lua html command-log emacs-lisp emoji fasd deft ranger gtags cscope
      (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
      (colors :variables colors-enable-nyan-cat-progress-bar t)
      (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
      (ibuffer :variables ibuffer-group-buffers-by 'projects)
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
      (shell :variables shell-default-position 'full shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
      (chinese :variables chinese-enable-fcitx t chinese-enable-youdao-dict t)
      emacs-lisp markdown dash bibtex django pandoc vimscript my)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment] 2018-07-21 05:15
This looks like it may be a duplicate of issue #10638.  Can you still reproduce the issue on the develop branch?

**Closed** 2018-08-12 09:37 UTC
