### ISSUE TITLE
Shortcut for kill-buffer-and-window?

### ISSUE THREAD

**Issue by sid-kap** [syl20bnr/spacemacs#8071] opened 2016-12-28 19:48 UTC
I think it would be useful to have a `SPC` keyboard shortcut for `kill-buffer-and-window`, especially for Vim users who are fond of `:q` in Vim (which does a similar thing when you have multiple buffers open).

I use this command often because I often open up a new buffer in a split, use it for a few seconds, and then want to kill the split and the buffer together. I currently use `C-x 4 0` but this is not as convenient as a `SPC` shortcut.

Does anyone else think this might be a useful shortcut to add? Maybe as `SPC b q` or `SPC w q`?

(Also, by the way, if I just wanted to add this shortcut to my own `.spacemacs`, how would I do that? I tried adding `  (spacemacs/set-leader-keys "bq" 'kill-buffer-and-window)` to my `dotspacemacs/user-config` but that doesn't seem to work.)

**Comment by nixmaniack** [comment] 2016-12-28 19:53
> (Also, by the way, if I just wanted to add this shortcut to my own .spacemacs, how would I do that?)

```elisp
(spacemacs/set-leader-keys
  "bq" 'kill-buffer-and-window)
```

**Comment by sid-kap** [comment] 2016-12-28 19:57
@nixmaniack I tried adding that to the end of `dotspacemacs/user-config` and restarting emacs, but it doesn't seem to work.

**Comment by nixmaniack** [comment] 2016-12-28 20:10
Can you try `SPC u SPC b d` which also invokes `kill-buffer-and-window`?

**Comment by sid-kap** [comment] 2016-12-28 20:11
Yep, that works.

**Comment by nixmaniack** [comment] 2016-12-28 20:12
What does `SPC h d k` `SPC b q` give you?

**Comment by sid-kap** [comment] 2016-12-28 20:14
It says `SPC b q is undefined`

**Comment by nixmaniack** [comment] 2016-12-28 20:16
That's strange. Can you paste your `.spacemacs` somewhere if it doesn't have any sensitive information?

**Comment by sid-kap** [comment] 2016-12-28 20:18
[Sure](http://pastebin.com/TU3xynfV)

**Comment by nixmaniack** [comment] 2016-12-28 20:29
Can you also paste the o/p of `SPC h d s`? I'm not able to reproduce it - may be someone else can. Adding that to the end of `user-config` and restarting emacs adds that binding under `SPC b q` for me.

**Comment by nixmaniack** [comment] 2016-12-28 20:32
You might want add some debug print statements and check if its reaching this configuration point at least.

**Comment by sid-kap** [comment] 2016-12-29 01:20
You're right, it wasn't getting to that part of the configuration. I removed the offending lines and it works now. Thanks for all your help!

**Comment by leohxj** [comment] 2016-12-29 03:15
`SPC b d` ? it means kill this buffer.

**Comment by sid-kap** [comment] 2016-12-29 05:36
@leohxj It kills the buffer, but keeps the split open. I wanted a command to kill the buffer and close the split.

**Comment by nixmaniack** [comment] 2016-12-29 08:30
The default binding provided by Spacemacs is `SPC u SPC b d`.

**Comment by nixmaniack** [comment] 2016-12-29 08:31
@sid-kap You can close the issue if your problem is resolved :).

**Comment by d12frosted** [comment] 2016-12-29 13:32
if it's something everyone would use (especially since `SPC b q` is faster than `SPC u SPC b d`), then we should add it to the core! 😸 

but I am not good at key bindings and ergonomic, so... i'll let someone else to decide 😸

**Comment by nixmaniack** [comment] 2016-12-29 13:53
I occasionally use `kill-buffer-and-window` hence `SPC u SPC b d` is fine for me. 
I mostly use `SPC w d` to delete the window as most of the times I just want to get rid of the window and keep the buffer. Quite opinionated workflow though. 

> if it's something everyone would use (especially since SPC b q is faster than SPC u SPC b d), then we should add it to the core!

Let's 👍 👎

**Comment by d12frosted** [comment] 2016-12-29 14:55
Lol, I kill buffers only why I make a typo in `C-x C-f` or when I wish to get rid of interactive session. So it's usually enough to `SPC w d`.

**Closed** 2018-02-05 21:09 UTC
Labels: - Mailling list -, Key Bindings

**Comment by duianto** [comment] 2018-02-05 21:39
I'm guessing that this issue was closed because the develop branch recently added the keybindings:
`SPC b x` and `SPC w x` which both call `kill-buffer-and-window`.

It's might be helpful for anyone finding this issue in the future, if one mentions that the issue has been solved, and possibly if a link was included to the relevant PR: Keybindings for kill buffer and window #10139

**Comment by sid-kap** [comment] 2018-02-05 21:43
@duianto, wow, I actually had no idea this has been added! Thanks for the update!

(I actually closed the issue because I was going through my old Issues and closing them, and this one seemed resolved/I must have forgotten to close it earlier.)
