### ISSUE TITLE
Leave persistent server open under `SPC q q`

### ISSUE THREAD

**Issue by calebmeyer** [syl20bnr/spacemacs#5039] opened 2016-02-11 18:42 UTC
Spacemacs takes a while to start up, even with nothing but the base spacemacs layer and no additional packages. The often recommended solution is to use `emacs --daemon` to start up an emacs server (so you only have to pay this time cost once), and then to use `emacsclient -t` and `emacsclient -c` to open up a terminal emacs session or gui emacs session, respectively.

The problem is that I'm very used to using `SPC q q` as quit. The dotfile has a setting, with a comment:
```el
   ;; If non nil advises quit functions to keep server open when quitting.
   ;; (default nil)
   dotspacemacs-persistent-server t
```

However, quitting with `SPC q q` does indeed kill the server. Just closing the frame with `SPC q z` (frame-killer) works, but it's awkward on a QWERTY keyboard to reach your weakest finger from q to z.

Can we change the behavior of the quit function to not kill your server when you're quitting (only if the above option is enabled)? As it stands today, I'm not sure what the option does for us.

It may be worth considering having a way to quit that does kill the server. Perhaps `SPC q k` would work for this?

**Comment by izahn** [comment] 2016-02-11 19:47
I don't have an opinion on the keybindings, but if spacemacs takes a long
time to start up maybe there is something mis-configured. For me it takes
about one second with the default packages and even with about 10 layers it
starts in 1.7 seconds. Or maybe we just have different ideas about how long
it should take emacs to start.

**Comment by calebmeyer** [comment] 2016-02-11 19:50
@izahn For me it has always taken about 5-10 seconds (layers and packages or no). That's not an astronomically long time, but it feels weird coming from vim or a persistent atom session, where loading is always subsecond.

I have a 2012 Mac Book Pro, and I run a lot of other applications simultaneously, so that could be contributing to my longer load times.

**Comment by StreakyCobra** [comment] 2016-02-12 00:56
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/2625. Feel free to report your remarks there :-)

**Closed by StreakyCobra** 2016-02-12 00:56 UTC
