### ISSUE TITLE
[SPC a s i] splits the original buffer in addition to opening the terminal.

### ISSUE THREAD

**Issue by deech** [syl20bnr/spacemacs#7899] opened 2016-12-02 21:44 UTC
#### Description :octocat:
[SPC a s i] to open a terminal also splits the original window.

#### Reproduction guide :beetle:
- Start Emacs
- Go to any buffer, eg. [SPC f e d] for the config buffer
- Do [SPC a s i]

*Observed behaviour:* :eyes: :broken_heart:
- Config buffer is split vertically.

*Expected behaviour:* :heart: :smile:
- Config buffer should not be split, there should only be one split, the original and the terminal.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html yaml nim python markdown markdownerc erlang ocaml scala auto-completion org git shell magit-extras epresent rust)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

Before:
![before-spc-asi](https://cloud.githubusercontent.com/assets/76703/20851433/18046000-b8a6-11e6-9e51-e1bb2edb0af0.png)
After:
![after-spc-asi](https://cloud.githubusercontent.com/assets/76703/20851436/1ce48294-b8a6-11e6-866b-5dd109b3c87e.png)

**Comment by bmag** [comment] 2016-12-03 08:58
duplicate of #7691

**Closed by bmag** 2016-12-03 08:58 UTC
