### ISSUE TITLE
[slack layer] Keyboard shortcuts not working.

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#13301] opened 2020-02-25 13:18 UTC
The keyboard shortcuts defined in the slack layer do not work in Slack Message Buffer mode. `SPC m`, as well as `,` are not bound correctly.

`,` is bound to `evil-repeat-find-char-reverse`.

The relevant function of the slack layer is:

    (defun slack/init-slack ()
      "Initialize Slack"
      (use-package slack
        :commands (slack-start)
        :defer t
        :init
        (progn
          (spacemacs/declare-prefix "aC" "slack")
          (spacemacs/set-leader-keys
            "aCs" 'slack-start
            "aCj" 'slack-channel-select
            "aCg" 'slack-group-select
            "aCr" 'slack-select-rooms
            "aCd" 'slack-im-select
            "aCq" 'slack-ws-close)
          (setq slack-enable-emoji t))
        :config
        (progn
          (spacemacs/set-leader-keys-for-major-mode 'slack-mode
            "j" 'slack-channel-select
            "g" 'slack-group-select
            "r" 'slack-select-rooms
            "d" 'slack-im-select
            "p" 'slack-room-load-prev-messages
            "e" 'slack-message-edit
            "t" 'slack-thread-show-or-create
            "q" 'slack-ws-close
            "mm" 'slack-message-embed-mention
            "mc" 'slack-message-embed-channel
            "k" 'slack-select-rooms
            "@" 'slack-message-embed-mention
            "#" 'slack-message-embed-channel
            ")" 'slack-message-add-reaction
            "(" 'slack-message-remove-reaction)
          (evil-define-key 'insert slack-mode-map
            (kbd "@") 'slack-message-embed-mention
            (kbd "#") 'slack-message-embed-channel))))

Which looks good, because `slack-message-buffer-mode` is a derived mode from `slack-mode`. Do you have any ideas what could be the problem here?

**Comment by smile13241324** [comment] 2020-02-25 22:34
Well the problem is most likely that by deriving one mode from another only the `slack-mode` specific mode map is copied. However the keybindings set by `spacemacs/set-leader-keys-for-major-mode` go into a special `spacemacs-mode` keymap which seems to be not copied.

I have double checked the layer and adapted it a bit so that the `slack-mode` bindings are now also available in `slack-message-buffer-mode`.

Would you mind giving it a go and close this issue if it is ok now?

Here is the commit 937ab011150c832fc4e68b830f7731df9db11e04.

**Comment by dschrempf** [comment] 2020-02-26 07:47
Works perfectly, thank you!

**Closed** 2020-02-28 08:26 UTC
Labels: Waiting for response
