### ISSUE TITLE
mode-line overlapping keys in which-key buffer after syncing configuration layers

### ISSUE THREAD

**Issue by jbharat** [syl20bnr/spacemacs#11165] opened 2018-08-12 08:21 UTC
#### Description :octocat:
which-key starts showing modeline after calling
dotspacemacs/sync-configuration-layers(SPC f e R) which sometimes overlaps the
the keys
*Before SPC f e R -> no overlapping of modeline and keys*
<img width="838" alt="screen shot 2018-08-12 at 5 52 39 pm" src="https://user-images.githubusercontent.com/6837979/43999910-8e461322-9e59-11e8-9495-ab9082bdfd11.png">
*After SPC f e R -> mode-line overlapping keys*
<img width="839" alt="screen shot 2018-08-12 at 5 53 27 pm" src="https://user-images.githubusercontent.com/6837979/44000046-cfcec6a2-9e5b-11e8-94c1-4f256e353ffb.png">

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC which shows which-key
- Pres SPC f e R
- Press SPC which now shows modeline

*Observed behaviour:* :eyes: :broken_heart:
keys are being overlapped by mode-line

*Expected behaviour:* :heart: :smile:
keys should not be overlapped by mode-line

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6a724e4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first nil)
 colors csv emacs-lisp emoji evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 git groovy html
 (ivy :variables ivy-wrap t ivy-height 15 ivy-use-virtual-buffers t)
 java
 (javascript :variables javascript-disable-tern-port-files t)
 kotlin lua
 (markdown :variables markdown-command 'pandoc markdown-live-preview-engine 'vmd)
 (org :variables org-projectile-file "TODOs.org" org-enable-org-journal-support t org-journal-file-format "%Y-%m-%d" org-journal-date-prefix "#+TITLE: " org-journal-date-format "%A, %B %d %Y" org-journal-time-prefix "* " org-journal-time-format "%I:%M%p%n" org-journal-dir
      (getenv "ho15")
      org-enable-reveal-js-support t org-enable-github-support t)
 (osx :variables osx-command-as 'super)
 pandoc
 (python :variables python-sort-imports-on-save t python-enable-yapf-format-on-save t)
 react
 (shell :variables shell-default-shell 'eshell shell-default-height 20 shell-default-term-shell "/bin/zsh" shell-default-position 'bottom)
 spacemacs-org
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default t)
 tern
 (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-follow-mode t treemacs-git-mode 'extended treemacs-use-collapsed-directories 3)
 (version-control :variables version-control-diff-tool 'git-gutter version-control-diff-side 'right version-control-global-margin t)
 yaml)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment] 2018-08-13 14:27
Keep a check on `which-key` customize group if anything changed. Maybe there is a setting that alters the way which-key shows keys either in an actual buffer or minibuffer.

**Comment by jbharat** [comment] 2018-08-14 01:07
@Compro-Prasad Are you able to reproduce it.

**Comment by Compro-Prasad** [comment] 2018-08-14 02:59
I haven't yet updated anything but still it is reproducible by following your steps.

**Comment by jbharat** [comment] 2018-08-14 06:06
@Compro-Prasad that at least confirms that it is not caused by my personal config.

**Comment by eeshugerman** [comment] 2018-09-03 01:10
I too have this issue after switching to the develop branch today.

**Comment by Voleking** [comment] 2018-09-04 07:03
After syncing configuration layers, which key buffer is too high and powerline-separator change to default(I have set it to slant).
<img width="1280" alt="screen shot 2018-09-04 at 14 59 46" src="https://user-images.githubusercontent.com/13161779/45015157-66e72a80-b053-11e8-8da2-984b5ad9dfc4.png">

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ffc1617dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm osx
      (chinese :variables chinese-enable-fcitx t)
      dash git github pandoc
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil c-c++-enable-google-style nil)
      emacs-lisp
      (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
      (markdown :variables markdown-command "pandoc -t html5 -f markdown+smart --mathjax --highlight-style=pygments --toc --toc-depth 3 --template github.html5 --css html/css/github.css" markdown-live-preview-engine 'pandoc)
      (org :variables org-agenda-files
           '("~/Documents/Org")
           org-directory '"~/Documents/Org" org-projectile-file "TODOs.org" org-want-todo-bindings t org-enable-hugo-support t org-enable-reveal-js-support t org-enable-org-journal-support t org-journal-dir "~/Documents/Org/journal/")
      (latex :variables latex-build-command "XeLaTeX" latex-enable-auto-fill t latex-enable-folding t latex-enable-magic nil)
      (deft :variables deft-directory "~/Documents/Org/Notes" deft-extensions
        '("org" "md" "txt")
        deft-recursive t deft-use-filename-as-title nil deft-use-filter-string-for-filename t deft-file-naming-rules
        '((noslash . "-")
          (nospace . "-")
          (case-fn . downcase)))
      (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t company-minimum-prefix-length 3)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (wakatime :variables wakatime-api-key "2ccf4cb6-4369-40b5-9165-718666b8bb32" wakatime-cli-path "/usr/local/bin/wakatime")
      unicode-fonts vim-empty-lines xkcd cfg)
```

**Comment by duog** [comment] 2018-09-25 23:05
I think what's happening is the *which-key* buffer is having it's mode line assigned in `spacemacs//restore-buffers-powerline`.

Changing the definition to:
```elisp
(defun spacemacs//restore-buffers-powerline ()
  "Restore the powerline in all buffers."
  (dolist (buffer (buffer-list))
    (unless (string-match-p "\\*which-key\\*" (buffer-name buffer))
      (spacemacs//restore-powerline buffer))))
```
seems to fix the issue for me. Perhaps it would be better to check for a nil local `mode-line-format` in `spacemacs//restore-powerline`?

**Comment by jbharat** [comment] 2018-09-25 23:42
@duog I added that function to my init.el. Didn't work for me. I tried in both daemon mode and opening emacs normally. Mode-line returns after SPC f e R. I can't find that function in .spacemacs.d. Where is it defined?

**Comment by duog** [comment] 2018-09-25 23:44
It's in spacemacs/layers/+spacemacs/spacemacs-modeline/funcs.el

**Comment by jbharat** [comment] 2018-09-25 23:51
@duog Perfect. Thanks. I had added the function to my init.el and it didn't work. But replacing the function in `/layers/+spacemacs/spacemacs-modeline/funcs.el` fixed it.

**Comment by Voleking** [comment] 2018-09-26 11:19
I try to replace the function in `/layers/+spacemacs/spacemacs-modeline/funcs.el`, not work for me.

**Comment by BrandonShega** [comment] 2019-04-08 13:32
Was there a chance of getting this merged in to develop? I'm experiencing this same issue and it looks like maybe there is a fix?

**Comment by Voleking** [comment] 2019-04-15 02:26
Seem my issue is not same with this and it's fixed now.

**Comment by duianto** [comment] 2019-04-15 08:34
Thanks @duog, your solution https://github.com/syl20bnr/spacemacs/issues/11165#issuecomment-424530605 has been implemented on the `develop` branch.

**Closed by duianto** 2019-04-15 08:34 UTC
