### ISSUE TITLE
weird bug that makes emacs unsuable in WSL2

### ISSUE THREAD

**Issue by MntiKor** [syl20bnr/spacemacs#15962] opened 2023-04-03 12:57 UTC
#### Description :octocat:
When trying to launch emacs from Windows taskbar or from WSL command, approximately 9 times on 10, emacs starts, starts loading spacemacs and then the window disappears. I can still see it in my taskbar, process is still running in WSL but there is nothing I can do to make it display anything. running `emacs --quick` makes the software run correctly

#### Reproduction guide :beetle:
- install Spacemacs
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Emacs window appears, and when Spacemacs should start, disappears.

%SYSTEM_INFO%

Windows 11 Pro with WSL2 Ubuntu

**Comment by rommeswi** [comment] 2023-04-04 01:04
I am using spacemacs on WSL2 without major problems. Are you using wslg?
The only time that my window disappears is when my internet connection changes, for example if I turn Wi-Fi on/off. This is because the display server connects via a network connection.

I also recommend [compiling emacs with wayland](https://batsov.com/articles/2021/12/19/building-emacs-from-source-with-pgtk/).

**Comment by lebensterben** [comment] 2023-04-04 03:28
@MntiKor 

Can you try starting Emacs with `emacs -nw` and post the command line output (if any)?

**Comment by smile13241324** [comment] 2023-07-10 15:01
I am sorry but I think we are not able to provide help with WSL2 bugs, therefore I will close this issue now. 

However I think that a simple WSL2 update should help resolving the issues you see. I can confirm that Spacemacs runs fine on latest WSL2 on Windows 10 running in an Ubuntu 22.04.2 LTS using a cygwin X server. I have never tried to work with the Microsoft X server implementation and I am unsure how well this works already.

**Closed as completed by smile13241324** 2023-07-10 15:01 UTC
Labels: Microsoft Windows
