### ISSUE TITLE
Contents of clipboard get pasted when a file is opened

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#8324] opened 2017-02-07 12:39 UTC
When I open a new file, the contents of my clipboard gets pasted wherever the cursor ends up.

**Comment by zestyr** [comment] 2017-02-07 16:28
Duplicate of #5435

**Comment by bmag** [comment] 2017-02-26 15:57
Not really enough information to decide if duplicate or not (or to understand what actually happened), but based on @beojan's lack of response I'm going to assume it is indeed a duplicate.

**Closed by bmag** 2017-02-26 15:57 UTC
Labels: Duplicate ☝

**Comment by beojan** [comment] 2017-02-26 16:41
@bmag Sorry, yes it seems to be the same issue since @hemcsec's snippet seems to fix it.
