### ISSUE TITLE
modline/spaceline clobbered during git commit with magit

### ISSUE THREAD

**Issue by jsilve24** [syl20bnr/spacemacs#14726] opened 2021-04-29 12:59 UTC
#### Description :octocat:
First off, thank you for all your help building spacemacs, its awesome.

This is an expansion on the brief notes I left on closed issue #176 (https://github.com/TheBB/spaceline/issues/176)

In short, whenever I enter the commit menu using magit (`SPC g s` and then `c c`) my spaceline/modline gets clobbered and does not return until I restart spacemacs.

**Screenshot before**
![spaceline1](https://user-images.githubusercontent.com/452422/116554330-0d4d6180-a8c9-11eb-9044-5fa61d9eccf2.png)

** Screenshot during commit (note same modline appearance is seen until spacemacs restarts)**
![spaceline2](https://user-images.githubusercontent.com/452422/116554396-22c28b80-a8c9-11eb-8055-da71051ea0b0.png)

**My .spacemacs (renamed to spacemacs.txt so I can upload to github)**
[spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/6398697/spacemacs.txt)

#### Reproduction guide :beetle:
- Start Emacs using my .spacemacs as it seems at least some other users are not having this trouble
- `SPC g s`
- `c c`
- Get frustrated as modline disappears

*Observed behaviour:* :eyes: :broken_heart:
spaceline replaced by empty bordered "cells"

*Expected behaviour:* :heart: :smile:
spaceline not clobbered :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. df15f8cc1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python csv auto-completion emacs-lisp git helm
        (deft :variables deft-zetteldeft t)
        (markdown :variables markdown-command "pandoc")
        multiple-cursors org spell-checking syntax-checking
        (ranger :variables ranger-override-dired 'ranger ranger-show-preview t)
        treemacs latex bibtex ess polymode imenu-list
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment] 2021-04-30 05:43
This is an upstream bug of spaceline.
I use doom-modeline and there's no such issue.

**Comment by hhkgrz** [comment] 2021-05-09 05:00
Same problem here, it seems this issue is caused by commits 4836a2569b3c8b959420201c9d2613e03317ef54 and 38f582d785627fe996141d15aa54cdba2c3167a4.

At https://github.com/syl20bnr/spacemacs/blob/38f582d785627fe996141d15aa54cdba2c3167a4/layers/%2Bspacemacs/spacemacs-visual/packages.el#L68, change ':spacediminish ((fci-mode " ⓕ" " f"))' to ':spacediminish (fci-mode " ⓕ" " f")' could make it work.

But not sure if this is an appropriate way to fix this.

Need the experts' help on this.

**Comment by lebensterben** [comment] 2021-05-28 02:10
@hhkgrz 
Can you verify whether it's fixed now?

**Comment by mbertheau** [comment] 2021-05-30 06:46
I still get this:
```
Error during redisplay: (eval (spaceline-ml-main)) signaled (wrong-type-argument symbolp (fci-mode " ⓕ" " f"))
```

**Comment by mbertheau** [comment] 2021-05-30 08:19
I'm getting the following backtrace

![Screenshot from 2021-05-30 15-24-36](https://user-images.githubusercontent.com/133575/120095923-3b9fa600-c0ee-11eb-9604-4c1d118eba49.png)

Tracing a bit through the code, the problem seems to be in here 
```elisp
(defun use-package-handler/:spacediminish (name _keyword arg rest state)
  (debug)
  (let ((body (use-package-process-keywords name rest state)))
    (use-package-concat
     `((when (fboundp 'spacemacs|diminish)
         ,@(if (consp (cadr arg)) ;; e.g. ((MODE1 FOO BAR) (MODE2 BAZ XYZ))
               (mapcar #'(lambda (var) `(spacemacs|diminish ,@var))
                       arg)
             `((spacemacs|diminish ,@arg))))) ;; e.g. (MODE FOO BAR)
     body)))
```

at `(cadr arg)` `arg` is `((fci-mode "..." "..."))`, so the cadr evals to `nil` and consequently the other branch of the `if` is taken.

Thus, in the current implementation, `:spacediminish` supports a "list of patterns above" (see https://github.com/syl20bnr/spacemacs/commit/4836a2569b3c8b959420201c9d2613e03317ef54) only if that list has at least two elements in it.

A proposed fix is in https://github.com/syl20bnr/spacemacs/pull/14810.

**Comment by lebensterben** [comment] 2021-05-31 04:39
Should be fixed in https://github.com/syl20bnr/spacemacs/pull/14810

**Closed** 2021-05-31 04:39 UTC
