### ISSUE TITLE
org-mode: expand-region is broken 

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#12099] opened 2019-03-25 17:03 UTC
#### Description :octocat:
expand-region is broken

#### Reproduction guide :beetle:
- Update to the latest version of magnars/expand-region.el

*Observed behaviour:* :eyes: :broken_heart:
`SPC v` is not working, fails with the following error:

    er--expand-region-1: Symbol’s function definition is void: org-outline-overlay-data

#### Note: ~this is an upstream issue~
upd: it might be not an upstream issue after all, see: https://github.com/syl20bnr/spacemacs/issues/12099#issuecomment-480904298

It looks like the following commit in expand-region.el broke it for Spacemacs: https://github.com/magnars/expand-region.el/commit/1f153a89a188013ac64586988b46418a5485b541

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: improve-clojure-jump-handlers (rev. b7e156e22)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml emacs-lisp lua javascript ag-haskell
     (ag-clojure :variables clojure-enable-clj-refactor t)
     (html :packages
           (not pug-mode slim-mode))
     (markdown :packages
               (not mmm-mode)
               :variables markdown-live-preview-engine 'vmd)
     (shell-scripts :packages
                    (not fish-mode))
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
     docker emoji fasd helm imenu-list restclient search-engine treemacs
     (shell :variables shell-default-shell 'eshell)
     ag-colors ag-dired ag-general ag-lang-tools ag-org ag-mail ag-version-control ag-web)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by agzam** [comment] 2019-03-25 17:14
It looks like this simply can be fixed by adding 
```:after (org)``` after this line
 https://github.com/syl20bnr/spacemacs/blob/master/layers/+spacemacs/spacemacs-editing/packages.el#L100

**Comment by agzam** [comment] 2019-03-26 16:40
Author has removed code causing the issue. Closing this

**Comment by mtourne** [comment] 2019-03-27 23:02
I'm also experiencing this and not sure how to fix it.

**Comment by agzam** [comment] 2019-04-02 19:33
Dammit... it broke again. reopening this

**Comment by flatwhatson** [comment] 2019-04-08 06:50
Hi, I am currently maintaining expand-region, looking into this issue now.

**Comment by flatwhatson** [comment] 2019-04-08 07:06
@agzam I cannot reproduce this issue on a fresh installation of spacemacs (develop branch).  Would you mind re-testing on a clean installation to confirm you're still seeing the problem?

**Comment by agzam** [comment] 2019-04-08 15:35
@flatwhatson I will definitely give it a try. Are you adding org layer btw?

**Comment by flatwhatson** [comment] 2019-04-08 15:38
No I haven't added any layers, just clone and run.

**Comment by flatwhatson** [comment] 2019-04-08 16:29
OK, retesting with the org layer, I can reproduce the issue.  The problem is that `expand-region` is byte-compiled with the built-in org, but then the `org` layer installs a newer version from ELPA which has changed the definition of the `org-save-outline-visibility` macro, leading to the symbol error.

If I delete`~/.emacs.d/elpa/*/develop/expand-region*` spacemacs re-installs `expand-region`, compiles it against the new version of org, and everything works as it should.

I don't think this is really a problem with expand-region, unfortunately I'm not sure how to proceed with actually fixing this issue for spacemacs.  I guess that the installation of a new org needs to trigger recompilation of modules which use it.

**Comment by agzam** [comment] 2019-04-08 17:03
@flatwhatson Thank you very much for testing it. 

@duianto (or someone else) we ruled out that this is **not** an upstream issue. Any ideas how to fix it?

**Comment by duianto** [comment] 2019-04-08 18:24
I have informed the maintainers.

**Comment by rahulcogent** [comment] 2019-04-25 00:19
I also face the same issue while helping one of my colleagues to setup org-jira. I could solve the issue by moving to develop branch commit id 3e37a359b88e7aa6e2f2d238ea7441e60e98a44c, the one I had checked out. Just some additional information, thought might help.

**Comment by agzam** [comment] 2019-04-26 18:48
@rahulcogent I am checking all the commits after that one and there has not been a single commit related to org stuff.

**Comment by flatwhatson** [comment] 2019-04-26 21:13
Probably in the process of changing revisions, a recompilation was triggered.  Anyone who experiences this issue and wants a workaround, just delete `~/.emacs.d/elpa/*/develop/expand-region*` and let spacemacs reinstall it.

**Comment by rahulcogent** [comment] 2019-04-26 21:31
@agzam @flatwhatson Thanks for checking it. I will verify my observation again and if find any more information that can be helpful will post here. Cheers.

**Comment by duianto** [comment] 2019-05-08 18:32
Since flatwhatson mentioned builtin org and compiling https://github.com/syl20bnr/spacemacs/issues/12099#issuecomment-480904298

Maybe this `doom-emacs` commit:
Isolate builtin org at compile time https://github.com/hlissner/doom-emacs/commit/574dae14261d7666d99b5bea73d8d1442fbd8268

could be helpful for finding a solution to this issue.

**Closed** 2020-01-05 06:03 UTC
