### ISSUE TITLE
error: void-function fci-mode preventing package updates

### ISSUE THREAD

**Issue by lunik1** [syl20bnr/spacemacs#3400] opened 2015-10-14 18:58 UTC
Using the line 
```(add-hook 'prog-mode-hook 'fci-mode)```
in my .spacemacs causes the error
```An error occured while installing package (error: (void-function fci-mode))```
when updating packages.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults colors cscope emacs-lisp git org python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 evil-commentary vim-empty-lines xkcd)
```

**Comment by TheBB** [comment] 2015-10-15 12:15
I can't reproduce this. How exactly does your dotfile look with this line? I'm assuming it's in `dotspacemacs/user-config`.

**Comment by lunik1** [comment] 2015-10-15 20:07
I just reproduced this using a fresh spacemacs install and template .spacemacs file with
``` (add-hook 'prog-mode-hook 'fci-mode)```
added to `dotspacemacs/user-init`.

Moving it to `dotspacemacs/user-config` fixes the error but means fci-mode isn't enabled when a file is passed as a command-line argument e.g.
```emacs .spacemacs```

**Comment by TheBB** [comment] 2015-10-16 10:14
You cannot add it to `user-init` since that package isn't ready then. The deficiency regarding `user-config` is noted in #3233. I will close this as a duplicate.

**Closed by TheBB** 2015-10-16 10:14 UTC
