### ISSUE TITLE
kill this buffer takes to *scratch* buffer rather than previous visited buffer

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#6787] opened 2016-08-08 05:47 UTC
So I open two files a.c and b.c and then do SPC b k. I expect to go back to a.c, but instead it takes me to *scratch* buffer.

**Comment by kvaneesh** [comment] 2016-08-08 05:50
a7131896854d2343d75457f1d188b9119098dd84 resetting to the above commit fix the issue

**Comment by TheBB** [comment] 2016-08-08 07:16
I can't reproduce this on latest develop with `SPC b d` (`SPC b k` has been rebound). Please report with `SPC h I` so we get some information to help you out.

**Comment by kvaneesh** [comment] 2016-08-08 13:10
can you try SPC b k. ? . The actual problem was faced in my notmuch private layer, where when we use kill-buffer, we always goes to *scratch* buffer instead of the mail thread view.

**Comment by kvaneesh** [comment] 2016-08-08 13:11
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 309e6eb4bba7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp gtags notmuch helm-git-grep helm-ls-git
      (git :variables magit-revision-insert-related-refs nil magit-revision-show-xref-buttons nil magit-backup-mode nil)
      asm c-c++ kernel-prg qemu-prg eyebrowse
      (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
      rtags go)
`

**Comment by TheBB** [comment] 2016-08-08 14:57
> can you try SPC b k

There's no more `SPC b k` in develop. What is it bound to?

**Comment by kvaneesh** [comment] 2016-08-08 16:02
sorry for the confusion. The problem i am facing was that usage of kill-buffer from my private notmuch layer was switching to *scratch* buffer. I started reverting patches (git bisect doesn't seem to work with spacemacs) and finally narrowed it down to fe60d0fc1e265756585836bd9f476e44fc7526d4 .The commit before that works fine.

The problem is that usage of kill-buffer from my private layer (notmuch) is suppose to jump to mail thread view. After the above commit, it switch to *scratch* buffer. 

NOTE: The above usage of regexp based buffer killing is working as expected, because it killed both a.c and b.c. So as you mentioned that usage is working as expected.

**Comment by kvaneesh** [comment] 2016-08-08 16:12
(push "\\*notmuch-.+\\*" spacemacs-useful-buffers-regexp)

Adding the above to my notmuch private layer fixed the issues for me

**Comment by TheBB** [comment] 2016-08-08 16:48
Okay, we should probably add that ourselves then.

**Comment by Stebalien** [comment] 2016-08-10 03:58
> Okay, we should probably add that ourselves then.

Well, that would go in a notmuch layer but we don't have one (yet #2163).

@kvaneesh so... any chance you've changed your mind about contributing your notmuch layer :grinning:?

**Comment by kvaneesh** [comment] 2016-08-10 10:56
A large part of that private notmuch layer is configuration w.r.t notmuch-saved-search, mail dir directory and smtp server etc.  That is only reason I haven't shared that on github.

**Comment by d12frosted** [comment] 2016-10-14 10:16
It seems to be irrelevant to Spacemacs, but a problem with your config. Since your problem has an answer, I am closing this one. Let us know if you still need help.

**Closed by d12frosted** 2016-10-14 10:16 UTC
Labels: - Bug tracker -, Buffers

**Comment by mpe** [comment] 2017-03-03 10:49
That buffer name regexp doesn't work for me, did it get mucked up by the markdown formatting?

This works for me:

    (push "\\*notmuch-.+\\*" spacemacs-useful-buffers-regexp)
