### ISSUE TITLE
Spacemacs freezes completely when rapid scroll to end of buffer.

### ISSUE THREAD

**Issue by bcowgill** [syl20bnr/spacemacs#5665] opened 2016-04-03 23:57 UTC
#### Description
Spacemacs freezes completely when rapid scroll to end of buffer.
Regular emacs doesn't exhibit this problem.

#### Reproduction guide
- Start Emacs
- Star the vim or emacs tutorial
- Scroll down continually with the down key

*Observed behaviour:*
The editor will reach the end of the buffer, or only partly through the buffer and then freeze completely.
None of the cancel commands will have any effect.
spacemacs must be terminated by kill -15 

*Expected behaviour:*
Editor should remain responsive to the keyboard.

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```

```

**Comment by jramapuram** [comment] 2016-04-06 08:46
Is it similar to this? https://github.com/syl20bnr/spacemacs/issues/5456

**Comment by TheBB** [comment] 2016-08-29 20:13
OP hasn't responded and nobody has reproduced. Since the symptoms look very similar to #5456 I'm closing this.

**Closed by TheBB** 2016-08-29 20:13 UTC
Labels: - Bug tracker -, To be reproduced, Unresponsive
