### ISSUE TITLE
Using multiple layouts, `SPC b b` results in `wrong-type-argument stringp nil`

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#7484] opened 2016-10-19 14:33 UTC
#### Description :octocat:
After using multiple layouts for a few minutes, `SPC b b` results in `Lisp error: (wrong-type-argument stringp nil)`

#### Reproduction guide :beetle:

Unfortunately, I don't have exact set of steps when this error starts, but I do know that this happens only when I create a new layout (`SPC l 2`).

*Observed behaviour:* :eyes: :broken_heart:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  helm-buffers-list--init()
  apply(helm-buffers-list--init nil)
  helm-funcall-with-source(((name . "Buffers") (init . helm-buffers-list--init) (candidates . helm-buffers-list-cache) (keymap keymap (29 . helm-toggle-buffers-details) (67108925 . helm-buffer-diff-persistent) (3 keymap (97 . helm-buffers-toggle-show-hidden-buffers) (100 . helm-buffer-run-kill-persistent) (61 . helm-buffer-run-ediff) (15 . helm-buffer-switch-other-frame) (111 . helm-buffer-switch-other-window)) (24 keymap (19 . helm-buffer-save-persistent) (4 . helm-buffers-run-browse-project)) (19 . helm-buffers-run-multi-occur) (27 keymap (67108896 . helm-buffers-mark-similar-buffers) (97 . helm-mark-all) (109 . helm-toggle-all-marks) (37 . helm-buffer-run-query-replace) (67108901 . helm-buffer-run-query-replace-regexp) (68 . helm-buffer-run-kill-buffers) (85 . helm-buffer-revert-persistent) (61 . helm-buffer-run-ediff-merge) (103 keymap (115 . helm-buffer-run-zgrep))) keymap (tab . helm-execute-persistent-action) (33554440 . describe-key) (17 . ace-jump-helm-line) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #[0 "\306\307\310\311\312\305!\313\"\314$\216\315\302!\210\316\304!\317\211\211\301=\203'�\315\302!\210\320\202]�\321\303\"\211\262\203:�\315A!\210\320\202]�\312!\262\322\300\"\262\323!\203S�\315!\210\202\\�\324\325\"\244\317\266\204\205e�\202�)\207" [(keymap (tab . helm-execute-persistent-action) (33554440 . describe-key) (17 . ace-jump-helm-line) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap ...)) (help keymap (109 . helm-help)) #2 (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 . helm-next-source) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (57 lambda nil ... ...) (56 lambda nil ... ...) (55 lambda nil ... ...) (54 lambda nil ... ...) (53 lambda nil ... ...) (52 lambda nil ... ...) (51 lambda nil ... ...) (50 lambda nil ... ...) (49 lambda nil ... ...) (63 . helm-help) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (24 keymap (57 lambda nil ... ...) (56 lambda nil ... ...) (55 lambda nil ... ...) (54 lambda nil ... ...) (53 lambda nil ... ...) (52 lambda nil ... ...) (51 lambda nil ... ...) (50 lambda nil ... ...) (49 lambda nil ... ...) (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-previous-line) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . "
") (15 . helm-next-source) (10 . helm-next-line) (26 . helm-select-action) (9 . helm-execute-persistent-action) (13 . helm-maybe-exit-minibuffer) (left . helm-previous-source) (right . helm-next-source) (7 . helm-keyboard-quit) (22 . helm-next-page) (27 keymap (8388640 . spacemacs/helm-navigation-transient-state/body) (110 . next-history-element) (112 . previous-history-element) (115 . undefined) (5 . helm-display-all-sources) (1 . helm-show-all-in-this-source-only) (85 . helm-unmark-all) (97 . helm-mark-all) (109 . helm-toggle-all-marks) (41 . helm-next-visible-mark) (40 . helm-prev-visible-mark) (91) (32 . spacemacs/helm-navigation-transient-state/body) (33554454 . helm-scroll-other-window-down) (25 . helm-scroll-other-window-down) (22 . helm-scroll-other-window) (12 . helm-reposition-window-other-window) (62 . helm-end-of-buffer) (60 . helm-beginning-of-buffer) (118 . helm-previous-page)) (next . helm-next-page) (prior . helm-previous-page) ...) 23 helm-yank-text-at-point ((31 . helm-undo-yank-text-at-point)) nil nil make-byte-code 0 "\300\205�\300 \207" vconcat vector [] 1 call-interactively read-key nil t assoc lookup-key commandp mapcar identity last-command-event unread-command-events] 7 nil nil]) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 . helm-next-source) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (57 lambda nil (interactive) (helm-execute-selection-action-at-nth 9)) (56 lambda nil (interactive) (helm-execute-selection-action-at-nth 8)) (55 lambda nil (interactive) (helm-execute-selection-action-at-nth 7)) (54 lambda nil (interactive) (helm-execute-selection-action-at-nth 6)) (53 lambda nil (interactive) (helm-execute-selection-action-at-nth 5)) (52 lambda nil (interactive) (helm-execute-selection-action-at-nth 4)) (51 lambda nil (interactive) (helm-execute-selection-action-at-nth 3)) (50 lambda nil (interactive) (helm-execute-selection-action-at-nth 2)) (49 lambda nil (interactive) (helm-execute-selection-action-at-nth 1)) (63 . helm-help) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (24 keymap (57 lambda nil (interactive) (helm-execute-selection-action-at-nth -9)) (56 lambda nil (interactive) (helm-execute-selection-action-at-nth -8)) (55 lambda nil (interactive) (helm-execute-selection-action-at-nth -7)) (54 lambda nil (interactive) (helm-execute-selection-action-at-nth -6)) (53 lambda nil (interactive) (helm-execute-selection-action-at-nth -5)) (52 lambda nil (interactive) (helm-execute-selection-action-at-nth -4)) (51 lambda nil (interactive) (helm-execute-selection-action-at-nth -3)) (50 lambda nil (interactive) (helm-execute-selection-action-at-nth -2)) (49 lambda nil (interactive) (helm-execute-selection-action-at-nth -1)) (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-previous-line) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . "
") (15 . helm-next-source) (10 . helm-next-line) (26 . helm-select-action) (9 . helm-execute-persistent-action) ...) (action . helm-type-buffer-actions) (persistent-action . helm-buffers-list-persistent-action) (persistent-help . "Show this buffer") (help-message . helm-buffer-help-message) (filtered-candidate-transformer helm-skip-boring-buffers helm-buffers-sort-transformer helm-highlight-buffers helm-fuzzy-highlight-matches) (volatile) (match . helm-buffers-match-function) (mode-line "Buffer(s)" "\\<helm-map>\\[helm-help]:Help \\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend") (header-line . "TAB: Show this buffer (keeping session)") (resume lambda nil (setq helm-buffers-in-project-p nil)) (migemo . nomultimatch) (buffer-list . helm-buffer-list)) helm-buffers-list--init)
  helm-funcall-foreach(init nil)
  helm-initial-setup(nil)
  helm-initialize(nil nil nil (helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found))
  helm-internal((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm-internal ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm(:sources (helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) :buffer "*helm mini*" :ff-transformer-show-only-basename nil :truncate-lines t)
  helm-mini()
  funcall-interactively(helm-mini)
  call-interactively(helm-mini nil nil)
  command-execute(helm-mini)
```

Once this starts, `SPC b b`, `SPC l b` and `C-x b` are broken. Only `C-x C-b` works.

*Expected behaviour:* :heart: :smile:

`SPC b b`, `SPC l b`, `C-x b` should always work.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. b550945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults clojure django emacs-lisp git github
      (go :variables go-use-gometalinter t)
      html javascript markdown
      (org :variables org-enable-github-support t org-enable-bootstrap-support t)
      osx python rust
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      sql syntax-checking version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  helm-buffers-list--init()
  apply(helm-buffers-list--init nil)
  helm-funcall-with-source(((name . "Buffers") (init . helm-buffers-list--init) (candidates . helm-buffers-list-cache) (keymap keymap (29 . helm-toggle-buffers-details) (67108925 . helm-buffer-diff-persistent) (3 keymap (97 . helm-buffers-toggle-show-hidden-buffers) (100 . helm-buffer-run-kill-persistent) (61 . helm-buffer-run-ediff) (15 . helm-buffer-switch-other-frame) (111 . helm-buffer-switch-other-window)) (24 keymap (19 . helm-buffer-save-persistent) (4 . helm-buffers-run-browse-project)) (19 . helm-buffers-run-multi-occur) (27 keymap (67108896 . helm-buffers-mark-similar-buffers) (97 . helm-mark-all) (109 . helm-toggle-all-marks) (37 . helm-buffer-run-query-replace) (67108901 . helm-buffer-run-query-replace-regexp) (68 . helm-buffer-run-kill-buffers) (85 . helm-buffer-revert-persistent) (61 . helm-buffer-run-ediff-merge) (103 keymap (115 . helm-buffer
```

**Comment by bmag** [comment] 2016-10-19 15:22
closing as duplicate of #7270

**Closed by bmag** 2016-10-19 15:22 UTC
Labels: Duplicate ☝
