### ISSUE TITLE
Request for unification: delete entity action

### ISSUE THREAD

**Issue by vibrys** [syl20bnr/spacemacs#4896] opened 2016-01-31 09:40 UTC
Hallo Spacemacs Team.

The delete action affects the following entities and IMHO it would be wonderful if the same keystroke was mapped for ot. Maybe 'd' is good candidate.

* window  -  current is: SPC c. SPC d does the dedication, but dedication is window specific, thus does not need unification and maybe could be moved to 'c' instead?
* buffer - here 'd', which IMHO is fine.
* file  - here 'D".

what do You think about it?
I could probably remap it in my local spacemacs, but maybe having it unified would be more intuitive for many users.

best regards

**Comment by adrsta** [comment] 2016-01-31 13:53
I agree, that has threw me of in the beginning, especially:
SPC b **d**
vs
SPC w **c**

"d" would be nice, also because of correspondence in vim delete action

**Comment by justbur** [comment] 2016-01-31 16:22
Sounds good to me

**Comment by Andre0991** [comment] 2016-01-31 18:59
Good idea :+1: 

I suggest using `w d` for deletion and `w D` for dedication.

**Comment by syl20bnr** [comment] 2016-02-01 06:05
Actually an other solution has been merged:
Closing buffers is now `SPC b c` instead of `SPC b d`. 
`SPC f D` is capitalized because of the destructive nature of the binding.

**Comment by syl20bnr** [comment] 2016-02-01 06:05
I consider this fixed.

**Comment by syl20bnr** [comment] 2016-02-01 06:06
marked as duplicate of #1410

**Comment by d12frosted** [comment] 2016-10-03 09:11
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 09:11 UTC
Labels: Discussion, Duplicate ☝, Fixed in develop, Key Bindings

**Comment by vibrys** [comment] 2016-10-05 19:04
All is fine.
Thank You
