### ISSUE TITLE
Missing preview of entered unicode codepoints (C-q codepoint SPC)

### ISSUE THREAD

**Issue by Qqwy** [syl20bnr/spacemacs#7311] opened 2016-10-07 08:29 UTC
Today I learned [from this tutorial, starts at time with exact explanation of this feature](https://youtu.be/3hwUnhdKWiI?t=4m27s) that you can type C-q, followed by the octal(or, if configured, decimal or hexadecimal) unicode codepoint, followed by non-digit key, to insert the appropriate unicode character.

However, for some reason, these typed codepoints do not show up in the bar at the far bottom (Is it which-key that is in charge of that bar? I am still very new to spacemacs), making it very easy to mistype.

I am not entirely sure if this missing preview (As can be seen in the video, that staple version of emacs does show the typed codepoints) is an issue of Spacemacs or of one of the many packages it works with; please tell me where to take the issue if this is not the correct location for it.

Thank you very much for this amazing editor! :smile:

**Comment by Qqwy** [comment] 2016-10-07 08:31
For completion's sake:

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control elixir erlang haskell idris ruby rust yaml
                 (c-c++
                  (c-set-style "Linux")
                  (c-basic-offset 4)))
```

**Comment by TheBB** [comment] 2016-10-07 08:34
This is reproducible in emacs -Q, therefore it's an Emacs issue, not a Spacemacs issue. Please report upstream.

> Is it which-key that is in charge of that bar?

No, that's the echo area.

**Comment by TheBB** [comment] 2016-10-07 08:49
Looks like `quoted-insert` users `read-quoted-char` in the background, which doesn't echo key presses unless it's called with a prompt.

Dirty workaround follows.

```elisp
(defun read-quoted-char-always-prompt (orig-fn &optional prompt)
  (funcall orig-fn (or prompt "Character code: ")))
(defun quoted-insert-always-prompt (orig-fn arg)
  (prog2 
      (advice-add 'read-quoted-char :around 'read-quoted-char-always-prompt)
      (funcall orig-fn arg)
    (advice-remove 'read-quoted-char 'read-quoted-char-always-prompt)))
(advice-add 'quoted-insert :around 'quoted-insert-always-prompt)
```

**Comment by Miciah** [comment] 2018-07-08 23:29
Looks like @Qqwy reported this upstream as https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24635, which is now fixed on Emacs 25.2 and Emacs 26.1.  Can this issue be either closed or labeled as "Emacs 24.1"?

**Comment by sdwolfz** [comment] 2018-07-09 19:50
Tried this out with 25.3 and 26.1 and it works properly. This can be closed.

**Closed by sdwolfz** 2018-07-09 19:50 UTC
Labels: - Bug tracker -, Should report upstream

**Comment by Qqwy** [comment] 2018-07-11 13:10
Thank you!
