### ISSUE TITLE
Adding contrib layers go or python breaks "SPC f e" group:files-emacs/spacemacs

### ISSUE THREAD

**Issue by horrorvacui** [syl20bnr/spacemacs#802] opened 2015-03-11 00:07 UTC
When I add the contrib layers Go or Python and press SPC f e, the options under group:files-emacs/spacemacs are missing.

**Comment by syl20bnr** [comment] 2015-03-11 01:20
I cannot reproduce it. What is your version of emacs ? Check if you have any `Warning` buffer or if there is any error in the `Message buffer`.

**Comment by horrorvacui** [comment] 2015-03-11 04:20
My emacs version is 24.4.1.
Also, I was wrong to say python layer is to blame. Instead it's just the go layer.
As for errors, I have a single error:

    Warning (initialization): An error occurred while loading `/home/horrorvacui/.emacs.d/init.el'
    
    error: go-oracle-mode is not currently registered as a minor mode

    To ensure normal operation, you should investigate and remove the
    cause of the error in your initialization file.  Start Emacs with
    the `--debug-init' option to view a complete error backtrace.

Strangely, I had an additional error before removing my entire `~/.emacs.d/` directory and starting fresh again as well as removing `~/.spacemacs`. It was to do with a missing *go-mode.el* I think.

**Comment by syl20bnr** [comment] 2015-03-11 17:21
Ok so you still have the error mentioned above ?
Thank you for the report, I think I see the problem.

**Comment by horrorvacui** [comment] 2015-03-12 02:18
I removed references to the company-go because it was responsible for the error about go-mode:

```
Compiling file /home/horrorvacui/.emacs.d/elpa/company-go-20150109.2051/company-go.el at Wed Mar 11 15:02:20 2015
company-go.el:19:13:Error: Cannot open load file: no such file or directory, go-mode
```
The problem still persists so that was unrelated. However, I figured out the problem lies with the 

```emacs-lisp
(load-gopath-file go-path "/src/code.google.com/p/go.tools/cmd/oracle/oracle.el")
(add-hook 'go-mode-hook 'go-oracle-mode)
(spacemacs|diminish go-oracle-mode " O")
```
If oracle.el doesn't exist at the location `/src/code.google.com/p/go.tools/cmd/oracle/oracle.el` then the `error: go-oracle-mode is not currently registered as minor mode` occurs. So I fixed the problem by `go get code.google.com/p/go.tools/cmd/oracle`. So the layer has a requirement on the go tool *oracle* which contains *oracle.el*.

**Comment by Funnnny** [comment] 2015-03-12 03:48
Yeah, the go-oracle should be in your GOPATH. I think we should find another way to do this, maybe have the file in the extension folder. It's not optimal but will fix it.

**Comment by syl20bnr** [comment] 2015-03-12 04:37
I fixed it in: c5b106865751e9cc7f308400b52e44b6b791e429
For the path of `go-oracle` it is ok as long as it is mentioned in the documentation (which is not right now).

**Comment by horrorvacui** [comment] 2015-03-12 04:43
Well looks like you beat me to it. It's fixed thanks.

**Comment by syl20bnr** [comment] 2015-03-12 04:51
Oops, sorry for this.
Your implementation takes not into account that `GO-PATH` can contain multiple paths. Anyway thanks for the PR :+1:

**Comment by horrorvacui** [comment] 2015-03-12 05:01
Thanks for everything and an awesome emacs-vim experience.

**Comment by syl20bnr** [comment] 2015-03-17 04:16
Fixed now in master.

**Closed by syl20bnr** 2015-03-17 04:16 UTC
Labels: bug :-(, Fixed in `develop`, Go
