### ISSUE TITLE
Loading snippets from private/snippets requires yas-reload-all

### ISSUE THREAD

**Issue by kevincolyar** [syl20bnr/spacemacs#1867] opened 2015-06-06 00:00 UTC
Trying to use snippets in my `private/snippets/ruby-mode` requires me to call `yas-reload-all` before the snippets are available.  I'm using `SPC i s` to access the snippets.

**Comment by KenetJervet** [comment] 2015-06-22 12:57
Can confirm this bug. In contrib/auto-completion/package.el, yas-global-mode is activated before the yas-snippet-dirs is set.

**Comment by TheBB** [comment] 2016-01-06 16:07
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/1830.

**Closed by TheBB** 2016-01-06 16:07 UTC
Labels: Beginner friendly, bug :-(, Yasnippet
