### ISSUE TITLE
Spacemacs is broken with Emacs 25.1.1

### ISSUE THREAD

**Issue by maikol-solis** [syl20bnr/spacemacs#7151] opened 2016-09-20 17:09 UTC
I just installed Emacs 25.1.1 in OpenSuse Leap 42.1

`emacs --version
GNU Emacs 25.1.1`

I started as usual and I get this message 

![screenshot_20160920_110301](https://cloud.githubusercontent.com/assets/4078489/18680704/1a3b6c0a-7f22-11e6-87c7-04d44e2609cf.png)

All the spacemacs goodies are gone and nothing works at all. 

I tried `emacs --debug-init` to see where was the problem, and I only get a blank screen with this message 

![screenshot_20160920_110352](https://cloud.githubusercontent.com/assets/4078489/18680747/3c98669a-7f22-11e6-949d-434c8e06b473.png)

I tried deleting the elpa folder in .emacs.d without success.

**Comment by TheBB** [comment] 2016-09-20 17:35
Looks like this Emacs was built without PNG support. You can turn off the Spacemacs banner, but you'd probably be better off getting a build with PNG.

**Comment by bmag** [comment] 2016-09-20 17:36
There is a problem with loading the official startup banner (the Spacemacs logo) on your setup. You can work around it by changing the value of `dotspacemacs-startup-banner` in your dotfile.

The problem is that your Emacs can't handle PNG files, but Spacemacs tries to open the official PNG banner. That is weird, because Spacemacs calls `image-type-available-p` to check if PNG files are supported by Emacs. I don't know if Spacemacs needs to check more aggressively, or if there is a problem with your Emacs build. If you want, you can run `emacs -Q` and open `~/.emacs.d/core/banners/img/spacemacs.png` to see how vanilla Emacs handles this.

**Comment by Evangileon** [comment] 2016-09-20 18:00
I have met with problem when I compiled Emacs `--with-cairo`
What's your configure options? Try to disable cairo support

**Comment by bb010g** [comment] 2016-09-20 20:12
I have the same issue after updating on Gentoo. The `cairo` is set, as usual.

**Comment by TheBB** [comment] 2016-09-20 21:16
I don't know why that is “as usual“. Cairo support is new in Emacs 25 and quite experimental, going by the release notes. I experienced the same issue when I built it with cairo. If OpenSuse or Gentoo ship with cairo enabled by default it sounds suspect to me.

**Comment by maikol-solis** [comment] 2016-09-20 22:27
>  If you want, you can run emacs -Q and open ~/.emacs.d/core/banners/img/spacemacs.png to see how vanilla Emacs handles this.

I did it and got this message 

`Cannot display image: (This Emacs mishandles this image file type)
`

I installed emacs from this repo 

[https://build.opensuse.org/package/show?project=editors&package=emacs](url)

**Comment by bb010g** [comment] 2016-09-20 22:33
@TheBB It's a global flag, so most setups will have it enabled by default if they don't make it explicit. I should probably file an issue on their Bugzilla about it, then.

**Comment by bitstreamout** [comment] 2016-09-21 06:10
>  Looks like this Emacs was built without PNG support. You can turn off the Spacemacs banner,
>  but you'd probably be better off getting a build with PNG.

Hmm ... I cano confirm that, from build log:

[ 1064s] Configured for 'x86_64-suse-linux-gnu'.
[ 1064s] 
[ 1064s]   Where should the build process find the source code?    .
[ 1064s]   What compiler should emacs be built with?               gcc -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -D_GNU_SOURCE -DGDK_DISABLE_DEPRECATION_WARNINGS -DGLIB_DISABLE_DEPRECATION_WARNINGS -pipe -Wno-pointer-sign -Wno-unused-variable -Wno-unused-label -Wno-unprototyped-calls -fno-optimize-sibling-calls -fno-PIE -DSYSTEM_PURESIZE_EXTRA=55000    -DSITELOAD_PURESIZE_EXTRA=10000 
[ 1064s]   Should Emacs use the GNU version of malloc?             yes
[ 1064s]   Should Emacs use a relocating allocator for buffers?    no
[ 1064s]   Should Emacs use mmap(2) for buffer allocation?         yes
[ 1064s]   What window system should Emacs use?                    x11
[ 1064s]   What toolkit should Emacs use?                          GTK3
[ 1064s]   Where do we find X Windows header files?                /usr/include
[ 1064s]   Where do we find X Windows libraries?                   /usr/lib64
[ 1064s]   Does Emacs use -lXaw3d?                                 no
[ 1064s]   Does Emacs use -lXpm?                                   yes
[ 1064s]   Does Emacs use -ljpeg?                                  yes
[ 1064s]   Does Emacs use -ltiff?                                  yes
[ 1064s]   Does Emacs use a gif library?                           yes -lgif
[ 1064s]   Does Emacs use a png library?                           yes -lpng16
[ 1064s]   Does Emacs use -lrsvg-2?                                yes
[ 1064s]   Does Emacs use cairo?                                   yes
[ 1064s]   Does Emacs use imagemagick?                             yes
[ 1064s]   Does Emacs support sound?                               yes
[ 1064s]   Does Emacs use -lgpm?                                   no
[ 1064s]   Does Emacs use -ldbus?                                  yes
[ 1064s]   Does Emacs use -lgconf?                                 yes
[ 1064s]   Does Emacs use GSettings?                               yes
[ 1064s]   Does Emacs use a file notification library?             yes -lglibc (inotify)
[ 1064s]   Does Emacs use access control lists?                    yes -lacl
[ 1064s]   Does Emacs use -lselinux?                               yes
[ 1064s]   Does Emacs use -lgnutls?                                yes
[ 1064s]   Does Emacs use -lxml2?                                  yes
[ 1064s]   Does Emacs use -lfreetype?                              yes
[ 1064s]   Does Emacs use -lm17n-flt?                              yes
[ 1064s]   Does Emacs use -lotf?                                   yes
[ 1064s]   Does Emacs use -lxft?                                   yes
[ 1064s]   Does Emacs directly use zlib?                           yes
[ 1064s]   Does Emacs have dynamic modules support?                yes
[ 1064s]   Does Emacs use toolkit scroll bars?                     yes
[ 1064s]   Does Emacs support Xwidgets (requires gtk3)?            yes

**Comment by bitstreamout** [comment] 2016-09-21 06:42
Could be a problem with the experimental cairo support

**Comment by bitstreamout** [comment] 2016-09-21 07:14
New build 25.1-251.1 should fix this problem ... now also the buildin browser works

**Comment by bitstreamout** [comment] 2016-09-21 12:19
Hmmm ... close ... then reopen,  what does this mean?

**Comment by maikol-solis** [comment] 2016-09-21 13:52
> Hmmm ... close ... then reopen, what does this mean?

Sorry my mistake. I clicked the close button without mean it. 

However, the new emacs build 25.1-251.1 is working flawless, even with `dotspacemacs-startup-banner` enabled. 

![screenshot_20160921_074258](https://cloud.githubusercontent.com/assets/4078489/18713324/2256128e-7fcf-11e6-9247-4fd2c81acd56.png)

**Comment by steve9001** [comment] 2016-09-22 02:37
Relatedly, the README promotes Emacs 24.4 and warns that Emacs 25 is not supported, but following the instructions for installing on OS X causes Emacs 25.1.1 to be installed. Should the README be updated?

**Comment by d12frosted** [comment] 2016-09-22 04:41
@steve9001 yes, README should be updated (at least for macOS). Note that every package manager has it's own pace for updating it's packages versions.

**Comment by sebhtml** [comment] 2016-09-23 16:23
Today, I encountered the problem on Ubuntu 14.04.5, after rebooting for an update.
I was using the emacs package.

I fixed the problem by uninstalling the emacs package, and by building Emacs from source.

I am using Spacemacs v0.105.22, with Emacs 25.1.1 (http://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.gz)


Commands that I used:

```
# Remove Emacs and Spacemacs
sudo apt-get remove `dpkg -l|grep emacs|grep ^ii|awk '{print $2}'`
rm -rf ~/.emacs.d/
rm -rf ~/.spacemacs

# Build Emacs 25.1
sudo apt-get build-dep emacs24
mkdir -p emacs/25.1
wget http://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.gz
tar -xzf emacs-25.1.tar.gz
mkdir ~/emacs-25.1
cd ~/emacs-25.1
./configure --prefix=/home/sboisvert/emacs/25.1/build
make -j 4
make install

# Install Spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
export PATH=/home/sboisvert/emacs/25.1/build/bin:$PATH
emacs
cp ~/dot-files/spacemacs/.spacemacs ~
emacs
```

**Comment by robbyoconnor** [comment] 2016-09-24 01:04
There's a PPA for emacs-snapshots -- I've been running with this and have no issues..

**Comment by d12frosted** [comment] 2016-10-03 10:19
Closing this issue as an issue with solution that must be applied outside of Spacemacs. If you think that we can improve something (like documentation in this case) - let us know. Or even better - send PR 😸

**Closed by d12frosted** 2016-10-03 10:19 UTC
Labels: - Forum -, Build
