### ISSUE TITLE
Cursor automatically gets repositioned in Buffer Menu Mode 

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2667] opened 2015-08-15 15:15 UTC
I typed  `:ls` to get a list of open buffers. In that list (*Buffer Menu Mode*), I navigate to a particular line. But in a couple of seconds the cursor is repositioned to the beginning of the list.

**Comment by syl20bnr** [comment] 2015-08-16 04:59
This is a known bug. I don't think there was a fix for it.
Did you tried the `ibuffer` layer which you can activate with `SPC b B` ? Do you still have the issue with this ?
What's you version of emacs?

**Comment by aviralg** [comment] 2015-08-16 08:08
**OS - Lubuntu 15.04**
**Emacs - 24.5.1** (Compiled Manually)
**WM - XMonad**

I was not aware of `SPC b B`.  I tried `:ls` as I was going through a vim tutorial on handling buffers. 
`SPC b B` seems to work great. Thanks.

**Comment by TheBB** [comment] 2015-08-30 15:42
This is caused by `global-auto-revert-mode`. There's a timer running every five seconds.

**Comment by TheBB** [comment] 2015-08-30 15:56
Actually, this can be solved by customizing the `revert-buffer-function` of that buffer.

```lisp
   (add-hook 'Buffer-menu-mode-hook (lambda () (setq-local revert-buffer-function (lambda (&rest args)))))
```

**Comment by StreakyCobra** [comment] 2015-11-24 21:02
`:ls` is now showing helm-buffers, so the problem of arriving on `buffer-menu` by following some tutorial is solved. I'm marking this issue as fixed in `develop`. If someone really want to use `buffer-menu`, feel free to open a new issue and link this one in it, it will be discussed for integration there.

**Closed** 2016-01-04 08:43 UTC
Labels: bug :-(, Fixed in develop

**Comment by cubranic** [comment] 2017-02-28 23:01
@StreakyCobra: `:ls` only shows `helm-buffers` if one is using the `helm` layer. If at install time the user chooses `ivy` as the completion framework, `:ls` will open the list in the buffer menu mode.

**Comment by StreakyCobra** [comment] 2017-03-01 08:18
@cubranic Sorry I'm not any longer enough into Spacemacs development to be useful here. This is also an old issue, you'll probably get better in visibility by opening a new one.

**Comment by cubranic** [comment] 2017-03-01 12:54
Good point, I'll comment in #7661, since it's still open and has a PR
ready.
