### ISSUE TITLE
ruby-on-rails layer not activating projectile-rails

### ISSUE THREAD

**Issue by mrmargolis** [syl20bnr/spacemacs#2230] opened 2015-07-04 22:07 UTC
projectile-rails does not appear to be working with the new ruby-on-rails layer on develop.  None of the projectile-rails bindings are active when editing files in a Rails project.

 The projectile-rails page says to add 

    (add-hook 'projectile-mode-hook 'projectile-rails-on)

but this causes emacs to complain about projectile-rails-on not being defined.

Is there additional configuration needed for the ruby-on-rails layer to activate when switching to a Rails project?

**Comment by robbyoconnor** [comment] 2015-07-04 23:49
It's weird...I'm not sure why this doesn't work -- tried to fix it and couldn't :(

**Comment by mrmargolis** [comment] 2015-07-05 03:07
This looks related to the discussion in #853   When I load a Ruby file in a Rails project I do see enh-ruby-mode active but projectile-rails is not active.  Seems like the enh-ruby-mode-hook in the ruby-on-rails layer isn't firing properly?

**Comment by syl20bnr** [comment] 2015-07-09 04:54
Should be fixed in develop.

**Comment by syl20bnr** [comment] 2015-07-09 04:55
Duplicate of #2245

**Closed** 2015-09-28 06:53 UTC
Labels: duplicate (-: :-), Fixed in `develop`
