### ISSUE TITLE
red bar after cloning/installing spacemacs on Windows 8

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#3184] opened 2015-09-29 03:19 UTC
```
Found 8 new package(s) to install...
--> fetching new package repository indexes...
--> installing spacemacs-base:helm... [1/8]An error occurred while installing helm (error: (void-variable warning-minimum-level))
--> installing spacemacs:helm-ag... [2/8]An error occurred while installing helm-ag (error: (void-variable warning-minimum-level))
--> installing spacemacs-base:helm-descbinds... [3/8]An error occurred while installing helm-descbinds (error: (void-variable warning-minimum-level))
--> installing spacemacs:helm-make... [4/8]An error occurred while installing helm-make (error: (void-variable warning-minimum-level))
--> installing spacemacs:helm-mode-manager... [5/8]An error occurred while installing helm-mode-manager (error: (void-variable warning-minimum-level))
--> installing spacemacs-base:helm-projectile... [6/8]An error occurred while installing helm-projectile (error: (void-variable warning-minimum-level))
--> installing spacemacs:helm-swoop... [7/8]An error occurred while installing helm-swoop (error: (void-variable warning-minimum-level))
--> installing spacemacs:helm-themes... [8/8]An error occurred while installing helm-themes (error: (void-variable warning-minimum-level))
```

Couldn't figure out how to get backtrace on windows since cmd showed no output with `emacs --debug-init`, can provide backtrace if anyone knows how to get it on windows.

**Comment by hujianxin** [comment] 2015-09-29 05:48
I got the same error on Ubuntu 14.04, what's wrong?

**Comment by robbyoconnor** [comment] 2015-09-29 05:55
Give the output of `SPC hds`?

**Comment by robbyoconnor** [comment] 2015-09-29 05:56
What version of emacs?

**Comment by hujianxin** [comment] 2015-09-29 06:02
@robbyoconnor Emacs 24.3.1

**Comment by syl20bnr** [comment] 2015-09-29 12:58
Duplicate of #3187 (or vice versa)

**Comment by codygman** [comment] 2015-09-29 14:29
Here is my output of SPC hds:

#### System Info
- OS: windows-nt
- Emacs: 24.3.1
- Spacemacs: 0.104.0
- Spacemacs branch: nil (rev. nil)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp version-control)
```

**Comment by codygman** [comment] 2015-09-29 14:29
Ah, followed duplicate issue and see it's because of my older emacs 24.3.

**Comment by TheBB** [comment] 2015-09-30 07:35
As far as I can tell, this shouldn't happen now on 0.104.2. Please reopen if I am mistaken. :-)

**Closed by TheBB** 2015-09-30 07:35 UTC
Labels: 24.3, duplicate (-: :-)
