### ISSUE TITLE
auto-completion help-tooltip t

### ISSUE THREAD

**Issue by dlebrecht** [syl20bnr/spacemacs#4482] opened 2016-01-07 21:50 UTC
if i have set

(auto-completion :variables
                      auto-completion-enable-help-tooltip t)

after the tooltip is displayed i cannot move up in the auto-completion list with C-k and i lose the completion list

**Comment by bmag** [comment] 2016-01-07 22:26
ref #2974

**Comment by StreakyCobra** [comment] 2016-01-07 22:55
This issue is indeed a duplicate of #2974, so closing it :-)

@dlebrecht You can click on the `Subscribe` button there to get informed when there are some news on the issue.

**Closed by StreakyCobra** 2016-01-07 22:55 UTC
