### ISSUE TITLE
Submitting a bug through Spacemacs sometimes generates garbage

### ISSUE THREAD

**Issue by yatesco** [syl20bnr/spacemacs#8558] opened 2017-03-21 10:10 UTC
Submitting bug https://github.com/syl20bnr/spacemacs/issues/8557:
```
#### Description :octocat:
Spacemacs occasionally freezes with CIDER and a connected REPL. Not 100% of the time and most likely to occur after typing '/' after an imported namespace. 

For example, if I have imported 'my.domain :as d' then typing 'd/' might freeze.

Neither 'CTL-G' nor ESC have any effect, only hard quit and restart.
#### Reproduction guide :beetle:
- Start Emacs
- Open a Clojure project
- Jack into a REPL
- in a namespace import another aliased namespace
- evaluate the forms
- create a new function and in that function type 'my-alias/'

*Observed behaviour:* :eyes: :broken_heart:
Occasionally Spacemacs will hard freeze.

*Expected behaviour:* :heart: :smile:
The same as the other 9/10 times when it works and suggests candidates in the aliased name space :-).

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/.yas-snippets")
 themes-megapack search-engine ivy emacs-lisp osx
 (clojure :variables cider-cljs-lein-repl "(do (use 'figwheel-sidecar.repl-api) (start-figwheel!) (cljs-repl))" clojure-align-forms-automatically t cljr-favor-prefix-notation nil)
 org html git javascript markdown
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
`
```
through `SPC-h-I` generated:

``` text
%23%23%23%23%20Description%20:octocat:%0ASpacemacs%20occasionally%20freezes%20with%20CIDER%20and%20a%20connected%20REPL.%20Not%20100%%20of%20the%20time%20and%20most%20likely%20to%20occur%20after%20typing%20'/'%20after%20an%20imported%20namespace.%20%0A%0AFor%20example,%20if%20I%20have%20imported%20'my.domain%20:as%20d'%20then%20typing%20'd/'%20might%20freeze.%0A%0ANeither%20'CTL-G'%20nor%20ESC%20have%20any%20effect,%20only%20hard%20quit%20and%20restart.%0A%23%23%23%23%20Reproduction%20guide%20:beetle:%0A-%20Start%20Emacs%0A-%20Open%20a%20Clojure%20project%0A-%20Jack%20into%20a%20REPL%0A-%20in%20a%20namespace%20import%20another%20aliased%20namespace%0A-%20evaluate%20the%20forms%0A-%20create%20a%20new%20function%20and%20in%20that%20function%20type%20'my-alias/'%0A%0A*Observed%20behaviour:*%20:eyes:%20:broken_heart:%0AOccasionally%20Spacemacs%20will%20hard%20freeze.%0A%0A*Expected%20behaviour:*%20:heart:%20:smile:%0AThe%20same%20as%20the%20other%209/10%20times%20when%20it%20works%20and%20suggests%20candidates%20in%20the%20aliased%20name%20space%20:-).%0A%0A%23%23%23%23%20System%20Info%20:computer:%0A-%20OS:%20darwin%0A-%20Emacs:%2025.1.1%0A-%20Spacemacs:%200.200.7%0A-%20Spacemacs%20branch:%20master%20(rev.%20c2774bc0)%0A-%20Graphic%20display:%20t%0A-%20Distribution:%20spacemacs%0A-%20Editing%20style:%20vim%0A-%20Completion:%20ivy%0A-%20Layers:%0A%60%60%60elisp%0A(html%0A%20(auto-completion%20:variables%20auto-completion-enable-snippets-in-popup%20t%20auto-completion-enable-help-tooltip%20t%20auto-completion-private-snippets-directory%20%22~/.yas-snippets%22)%0A%20themes-megapack%20search-engine%20ivy%20emacs-lisp%20osx%0A%20(clojure%20:variables%20cider-cljs-lein-repl%20%22(do%20(use%20'figwheel-sidecar.repl-api)%20(start-figwheel!)%20(cljs-repl))%22%20clojure-align-forms-automatically%20t%20cljr-favor-prefix-notation%20nil)%0A%20org%20html%20git%20javascript%20markdown%0A%20(shell%20:variables%20shell-default-height%2030%20shell-default-position%20'bottom)%0A%20spell-checking%20syntax-checking%20version-control)%0A%60%60%60%0A-%20System%20configuration%20features:%20JPEG%20RSVG%20NOTIFY%20ACL%20GNUTLS%20LIBXML2%20ZLIB%20TOOLKIT_SCROLL_BARS%20NS%20MODULES%0A%0A%0A%23%23%23%23%20Backtrace%20:paw_prints:%0A%60%60%60%0A%60%60%60
```

**Comment by bmag** [comment] 2017-03-21 16:45
Looks like a duplicate of #8478

**Closed by bmag** 2017-03-21 16:45 UTC
