### ISSUE TITLE
cgywin - strange chars in startup screen and powerline... unicode dependencies missing? 

### ISSUE THREAD

**Issue by joefromct** [syl20bnr/spacemacs#211] opened 2014-12-05 14:43 UTC
Hi, 

I'm seeing some strange characters in the startup screen as well as the powerline running over cygwin... is there something unicode i'm missing?  Where should i start looking to resolve this? 

Thanks for your help,

![spacemacs](https://cloud.githubusercontent.com/assets/3342707/5317244/1b3e2ef8-7c63-11e4-8919-3cc100364c74.jpg)

**Comment by mijoharas** [comment] 2015-01-05 17:38
I have the same issue after installing this on a work computer (that is on windows, also the `emacs-w32.exe` package) for me the value of `locale-coding-system` is `utf-8-unix`, or more concretely:

```
locale-coding-system is a variable defined in `C source code'.
Its value is utf-8-unix

Documentation:
Coding system to use with system messages.
Also used for decoding keyboard input on X Window system.
```

**Comment by mijoharas** [comment] 2015-01-05 17:46
do we think it's unicode or just the font being missing? I've tried installing the font on windows, but I'm not sure if it requires a specific version of the font or anything? (e.g. OTF vs. TTF e.t.c.) in addition there is [this page](https://www.cygwin.com/ml/cygwin-announce/2013-03/msg00019.html) that references the fonts at the bottom, it links to a file in cygwin that says:

```
6. If you don't like the default fonts in the GUI versions of emacs,
   you can change them via the menu items

     Options -> Set Default Font
     Options -> Save Options

   This will set the default font in your ~/.emacs and will apply to
   both emacs-w32 and emacs-X11.  If you want different default fonts
   for the two programs, use the lisp variable `window-system' to
   distinguish between them.

   For example, the following code in ~/.emacs makes DejaVu Sans
   Mono-10 the default font for emacs-w32:

     (if (eq window-system 'w32)
         (add-to-list 'default-frame-alist
                      '(font . "DejaVu Sans Mono-10")))
```
Unfortunately it doesn't say where the fonts live or how to update them.

**Comment by mijoharas** [comment] 2015-01-05 17:52
also, default font is set to Source Code Pro and all seems well from looking at it.

**Comment by mijoharas** [comment] 2015-01-05 17:58
In addition, nothing [here](http://stackoverflow.com/questions/2901541/which-coding-system-should-i-use-in-emacs) seems to help. Any ideas?

**Comment by mijoharas** [comment] 2015-01-06 00:00
Just installed a fresh version on a windows box at home, setting mintty to `UTF-8` had no effect. `emacs-w32` starts a new window for it's process and I think it's that process (and window) that is struggling to render the utf-8 fonts correctly.

Unfortunately I can't find any documentation on how the executable (cygwin's `emacs-w32`) renders the font, but I wonder if the problem is related to [this issue](https://www.cygwin.com/ml/cygwin/2014-09/msg00060.html)? Unfortunately I'm not familar enough with windows to debug everything (which is why I'm using cygwin and emacs in the first place :smile:). I don't suppose you have any ideas?

**Comment by mijoharas** [comment] 2015-01-06 16:36
hmmm... you're right that the alternate build works but I can't use emacs without POSIX extensions as I become much less productive. Thanks anyways, if I ever figure out what's going on I'll let you know but I think I'll probably just live with the messed up unicode for a while.

**Comment by syl20bnr** [comment] 2015-01-06 16:55
I guess you already did it, but just for reference in this thread, it is possible to lower the impact of this issue by setting `dotspacemacs-mode-line-unicode-symbols` to `nil` in the dotfile.

**Comment by syl20bnr** [comment] 2015-01-06 16:57
It is also possible to hide the minor-modes with `SPC t m m` or calling `spacemacs/mode-line-minor-modes-toggle` in `dotspacemacs/config`.

**Comment by mijoharas** [comment] 2015-01-06 17:21
Thanks. hmmm... if I use helm to set the default font with `set-default-font` I get a list like 
![font-problem](https://cloud.githubusercontent.com/assets/4069743/5632541/77f73ee6-95c7-11e4-9cfe-4fd6395609ad.PNG)

As you can see, all the default fonts seem to be iso-stuff and there aren't any utf-8 ones. do you know if this is expected behaviour?

**Comment by syl20bnr** [comment] 2015-01-06 18:09
I got the same list in a ubuntu box, I have even only `iso10646-1`, no `#238`.

We could try to contact the maintainer of the Emacs package for Cygwin.

**Comment by syl20bnr** [comment] 2015-01-06 18:14
@mijoharas  I found this on the ML: https://cygwin.com/ml/cygwin-announce/2014-09/msg00018.html.
Can you post on it ? I can do it if you prefer.

**Comment by mijoharas** [comment] 2015-01-06 18:45
Will do, thanks.

**Comment by mijoharas** [comment] 2015-01-06 18:47
Just to clarify, should I  be emailing kenbrown directly? or emailing the cygwin at cygwin dot com mailing list directly? I'm somewhat unfamiliar with it.

**Comment by syl20bnr** [comment] 2015-01-06 18:49
Cygwin ML. I can do it if you prefer, I want it to work too :-)

**Comment by mijoharas** [comment] 2015-01-06 19:03
OK, if you can do it (as I assume you're more familiar with emacs than me anyways). Thanks again. :smile:

**Comment by syl20bnr** [comment] 2015-01-07 03:16
Fixed in develop, I'll try to make a release tonight.

**Closed** 2015-01-07 04:35 UTC
Labels: question

**Comment by syl20bnr** [comment] 2015-01-07 04:37
Fixed in 0.43.0

**Comment by mijoharas** [comment] 2015-01-07 09:36
Nice, thanks for this. :+1:

**Comment by mijoharas** [comment] 2015-01-30 13:26
This has regressed (I assume since the mode line changes such as [this file](https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs-mode.el)

**Comment by syl20bnr** [comment] 2015-01-30 14:03
@mijoharas add just pushed a commit in `develop` to add support for cygwin.

**Comment by mijoharas** [comment] 2015-01-30 16:46
fixes it for me. Thanks.
