### ISSUE TITLE
Beginners Guide not reachable

### ISSUE THREAD

**Issue by mrimann** [syl20bnr/spacemacs#16204] opened 2023-12-06 23:06 UTC
I've visited the public website several times as a newby to consume information for setting up Spacemacs and browsing the documentation. Somehow I missed a beginners tutorial.

And several days later I was searching for something around spacemacs and accidentally stumbled over a very nice beginners guide that's available at https://develop.spacemacs.org/doc/BEGINNERS_TUTORIAL.html

It's liked from the https://develop.spacemacs.org/ front page - but not from https://spacemacs.org/ front-page. So **there is a beginners tutorial - but it's not linked on the public webiste**

What a pity...

(I think this could be related to https://github.com/syl20bnr/spacemacs/issues/15995)

**Comment by smile13241324** [comment] 2023-12-31 13:09
Sorry this is an issue with the lost of maintainers we have experienced some time ago. Unfortunately I am not able to change the website, for now we push to develop.spacemacs.org which is working well. The old website is only for the master branch which is unmaintained up to now.

@syl20bnr @JAremko do one of you see a chance to have spacemacs.org forward to develop.spacemacs.org? I think this would really be a small change and should fix a lot of confusion I see in the issue page.

Anyway as this is a duplicate of #15995 I am going to close this.

**Closed as completed by smile13241324** 2023-12-31 13:09 UTC
