### ISSUE TITLE
Starting spacemacs in terminal - graphic bug

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#2940] opened 2015-09-08 18:46 UTC
When I start Spacemacs in the terminal with `emacs -nw` I get weird symbols during navigation with `hjkl`. Also the current line is jumping. Does someone have an idea where the problem is coming from?

![selection_002](https://cloud.githubusercontent.com/assets/5929935/9744179/89c988d6-566a-11e5-9ff3-37153711f825.png)

**Comment by TheBB** [comment] 2015-09-08 18:47
Yeah, it's coming from `evil-terminal-cursor-changer`. You can exclude it by adding it to `dotspacemacs-additional-packages`.

**Comment by TheBB** [comment] 2015-09-08 18:49
The upstream report is https://github.com/7696122/evil-terminal-cursor-changer/issues/8.

Closing this as a duplicate of #2707.

**Comment by sebhahn** [comment] 2015-09-08 18:49
wow that was fast! thanks a lot!

**Closed by TheBB** 2015-09-08 18:49 UTC
Labels: duplicate (-: :-), Terminals
