### ISSUE TITLE
XKCD blank buffer after installing of javascript layer.

### ISSUE THREAD

**Issue by KraevRoot** [syl20bnr/spacemacs#8195] opened 2017-01-17 15:38 UTC
When i install xkcd my plugins list is -> (csv ruby helm better-defaults xkcd emacs-lisp)
After installing i run command `SPC-a-x` and xkcd-comics is appear correctly and prompt at command line: Support for json-mode requires installation of layer javascsript, do you want to install it? ( y or n )
1) when i insert y or n - image disappear and it goes out from xkcd to standard command mode;
2) when i push ESC button - all ok, but every new comics i get prompt about installation of JS layer. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript csv ruby helm better-defaults xkcd emacs-lisp)
```

How to fix it?

**Comment by bmag** [comment] 2017-01-17 17:00
> when i insert y or n
Which one do you insert, `y` or `n`? (from your system info I guess you inserted `y` at least once)

> it goes out from xkcd to standard command mode;

What is the active buffer? "Command mode" means "normal state" (the left edge of the mode-line is yellow)?

Does the repeat after restarting Spacemacs? (assuming you don't uninstall `javascript` layer)?

The prompt is caused by lazy installation. You can disable lazy installation by changing the value of `dotspacemacs-enable-lazy-installation` in your dotfile.

**Comment by KraevRoot** [comment] 2017-01-17 19:43
@bmag yes
yes
[https://pp.vk.me/c837623/v837623447/1e5ff/0ocDUwVYTFg.jpg](After `SPC-a-x`)
[https://pp.vk.me/c837623/v837623447/1e5f7/-PtHc9Nrlu8.jpg](Ather `r` - next random comics )

**Comment by bmag** [comment] 2017-01-17 20:33
I wasn't able to repro this bug. Can you post exact steps needed to reproduce the bug?

**Comment by KraevRoot** [comment] 2017-01-18 09:55
on develop branch (rev. c6bf7f7) all is ok

**Comment by d12frosted** [comment] 2017-01-18 12:45
I had [a similar issue](https://github.com/syl20bnr/spacemacs/issues/7280#issuecomment-270478734), but for reasons unknown it's gone.

**Comment by bmag** [comment] 2017-01-18 15:03
So... do we mark it as fixed in develop?

**Comment by d12frosted** [comment] 2017-01-18 15:38
Not sure 😿 But it may be fixed on `develop`, indeed.

@KraevRoot could you please try `develop` branch?

**Comment by bmag** [comment] 2017-01-18 15:40
@d12frosted you missed https://github.com/syl20bnr/spacemacs/issues/8195#issuecomment-273432253, @KraevRoot said all is ok on develop

**Comment by d12frosted** [comment] 2017-01-18 15:40
Oh, my bad. Sorry. Then yes, it's fixed in `develop` 😸

**Closed** 2017-04-02 06:03 UTC
Labels: - Forum -, Fixed in develop, Lazy installation
