### ISSUE TITLE
Can't install magit (among few other packages)

### ISSUE THREAD

**Issue by Kernael** [syl20bnr/spacemacs#2272] opened 2015-07-07 10:59 UTC
Did a fresh resintall of Spacemacs to fix #2176 manually, but I can't seem to install some packages included in `git`, `version-control` and `elixir`, I have the following errors on start :

```
--> installing with-editor... [1/5]An error occurred while installing with-editor (error: (error Package `emacs-24.4' is unavailable))
--> installing git-commit... [2/5]An error occurred while installing git-commit (error: (error Package `emacs-24.4' is unavailable))
--> installing magit-popup... [3/5]An error occurred while installing magit-popup (error: (error Package `emacs-24.4' is unavailable))
--> installing (elixir):alchemist... [4/5]An error occurred while installing alchemist (error: (error Package `emacs-24.4' is unavailable))
--> installing (git):magit... [5/5]An error occurred while installing magit (error: (error Package `emacs-24.4' is unavailable))
```

Found several occurences of this error but was unable to fix it, do you guys have any direction ?

**Comment by cpaulik** [comment] 2015-07-07 11:18
Which emacs version are you using? I have no idea but maybe some packages are only compatible with emacs-24-4 and above?

**Comment by Kernael** [comment] 2015-07-07 11:24
I am using version 24.3.1. From what I found the issue is related to lingering `package.el` files, but if you are right, isn't there a way to fallback to a previous version of the packages ? (I had no problem with using magit before).

**Comment by robbyoconnor** [comment] 2015-07-07 13:01
magit has been updated...so try emacs 24.4 -- There are several ppas available.

**Comment by Kernael** [comment] 2015-07-07 13:53
Did the trick, thank you.

**Comment by TheBB** [comment] 2015-07-07 14:22
You can probably keep this open, re: discussion in gitter. Spacemacs is supposed to support 24.3 so this is still a bug.

**Comment by shaief** [comment] 2015-07-09 08:52
Same here, on Fedora 20 with emacs 24.3.1 which is pretty hard to upgrade...
```
Found 3 new package(s) to install...
--> fetching new package repository indexes...
--> installing with-editor... [1/3]An error occurred while installing with-editor (error: (error Package `emacs-24.4' is unavailable))
--> installing git-commit... [2/3]An error occurred while installing git-commit (error: (error Package `emacs-24.4' is unavailable))
--> installing magit-popup... [3/3]An error occurred while installing magit-popup (error: (error Package `emacs-24.4' is unavailable))
```

**Comment by robbyoconnor** [comment] 2015-07-09 09:02
@shaief -- build from source 24.4 or higher -- I know for a fact this works.

**Comment by shaief** [comment] 2015-07-09 09:09
@robbyoconnor thanks. I keep failing doing it. Do you have a good resource (how to text of compiling emacs 24.4 on fedora 20)?

**Comment by robbyoconnor** [comment] 2015-07-09 09:53
I didn't mean to come off rude -- just am very direct...that said -- google around...there might even be 24.4/24.5 rpms somewhere :)

**Comment by shaief** [comment] 2015-07-09 10:38
That's ok, was explaining myself. There are not such rpms for fedora 20.

**Comment by StreakyCobra** [comment] 2015-11-17 20:18
What is the status of this issue? Has it been solved, or is it still an existing bug with emacs 24.3?

**Comment by nashamri** [comment] 2015-12-12 14:13
I just tried installing spacmacs `0.104.6` on linux mint 17.3 which is based on ubuntu 14.04 which comes with emacs 24.3 by default and the issue is still there. Magit is looking for emacs 24.4 or greater. After upgrading (using this ppa `ppa:andreas-h/emacs`) to 24.5 the issue was resolved.

**Comment by StreakyCobra** [comment] 2015-12-13 10:25
Indeed, [`magit` is requiring emacs 24.4 at least](https://github.com/magit/magit/blob/24b6fb7295c544c4cad6f64653f653c1e1c58406/default.mk#L55). Upstream have already said they [will not support emacs 24.3](https://github.com/magit/magit/issues/2044#issuecomment-120422590), so there is nothing we can do here. For `alchemist` it's also [an upstream requirement](https://github.com/tonini/alchemist.el/blob/2d9c2079c95a0dea0d564576e64dee2e758eea97/README.md#requirements) to have emacs 24.4. If someone is really interested in this, this issue should be reported upstream (if not already), but it's not something that can be addressed by Spacemacs.

These errors being upstream requirements, there is nothing we can do. In the README it's already written that emacs 24.4 is needed for a "full Spacemacs experience", so closing this issue.

**Closed by StreakyCobra** 2015-12-13 10:25 UTC
Labels: 24.3, bug :-(, Git, High Priority, Waiting for response
