### ISSUE TITLE
'.' doesn't repeat with counts.

### ISSUE THREAD

**Issue by newhook** [syl20bnr/spacemacs#6421] opened 2016-06-24 13:04 UTC
#### Description

. (dot) doesn't repeat with counts.
#### Reproduction guide
- Start Emacs
- 2dd
- .

_Observed behaviour:_
2dd deletes two lines. Pressing . deletes one line.

_Expected behaviour:_
2dd deletes two lines. Pressing . should deletes two lines.
#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(go osx auto-completion better-defaults emacs-lisp common-lisp git markdown org scheme
    (shell :variables shell-default-height 30 shell-default-position 'bottom)
    spell-checking syntax-checking version-control)
```

**Comment by TheBB** [comment] 2016-06-24 13:10
Can't reproduce this, works fine here.

**Comment by newhook** [comment] 2016-06-24 13:17
This is a gif of me reproducing the bug in my local environment. The one line deletes are me pressing . and the 2 line deletes are me typing 2dd. This bug is super annoying...

http://s.cust.io/1eZFZ

**Comment by syl20bnr** [comment] 2016-06-24 15:36
You are using a bleeding edge Emacs, this might the cause. Try to reproduce it with `SPC q D evil`.

**Comment by a13ph** [comment] 2016-06-25 13:55
i'm reproducing this as well (on Ubuntu PPA development snapshot of emacs), so @syl20bnr is probably right

**Comment by syl20bnr** [comment] 2016-06-28 01:46
I cannot reproduce it on 24.5.1 so I suggest to report this upstream mentioning emacs 25.1.

**Comment by newhook** [comment] 2016-06-28 11:56
Do you run 24.5.1 on osx?

**Comment by syl20bnr** [comment] 2016-06-28 13:00
Yes I'm on OS X.

**Comment by newhook** [comment] 2016-06-29 11:41
I reverted back to 24.5.1 and it works as expected. Thanks.

**Comment by syl20bnr** [comment] 2016-07-03 15:30
Thank you for the confirmation, reported here: https://bitbucket.org/lyro/evil/issues/683/doesnt-repeat-with-counts-emacs-25

**Comment by Miciah** [comment] 2018-07-08 17:03
https://bitbucket.org/lyro/evil/issues/683/doesnt-repeat-with-counts-emacs-25 moved to https://github.com/emacs-evil/evil/issues/683, which was closed as a duplicate of https://github.com/emacs-evil/evil/issues/731, which was closed as fixed, so it looks like this issue has been fixed upstream.  For what it's worth, I cannot reproduce the reported behavior with Emacs 27.0.50.

**Closed** 2018-07-09 20:23 UTC
Labels: - Bug tracker -, Emacs 25.1, Evil, Fixed upstream
