### ISSUE TITLE
Clojure-mode multiple issues starting with README.org

### ISSUE THREAD

**Issue by rebcabin** [syl20bnr/spacemacs#3001] opened 2015-09-12 17:52 UTC
Reading `~/.emacs.d/contrib/!lang/clojure/README.org`, it advises the following contents for `.lein/profiles.clj`:

    {:user {:plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]
                    [refactor-nrepl "0.3.0-SNAPSHOT"]]
          :dependencies [[alembic "0.3.2"]
                         [org.clojure/tools.nrepl "0.2.7"]]}}

This results in a crash when executing `cider-jack-in`

    Starting nREPL server via lein repl :headless...
    error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Retrieving cider/cider-nrepl/0.9.0-SNAPSHOT/cider-nrepl-0.9.0-20150616.120440-43.pom from clojars
    Retrieving refactor-nrepl/refactor-nrepl/0.3.0-SNAPSHOT/refactor-nrepl-0.3.0-20150401.112429-28.pom from clojars
    Retrieving org/clojure/tools.nrepl/0.2.7/tools.nrepl-0.2.7.pom from central
    Retrieving refactor-nrepl/refactor-nrepl/0.3.0-SNAPSHOT/refactor-nrepl-0.3.0-20150401.112429-28.jar from clojars
    Retrieving cider/cider-nrepl/0.9.0-SNAPSHOT/cider-nrepl-0.9.0-20150616.120440-43.jar from clojars
    Retrieving alembic/alembic/0.3.2/alembic-0.3.2.pom from clojars
    Retrieving lein-as-resource/lein-as-resource/2.5.0/lein-as-resource-2.5.0.pom from clojars
    Retrieving org/flatland/classlojure/0.7.0/classlojure-0.7.0.pom from clojars
    Retrieving org/clojure/tools.nrepl/0.2.7/tools.nrepl-0.2.7.jar from central
    Retrieving org/flatland/classlojure/0.7.0/classlojure-0.7.0.jar from clojars
    Retrieving alembic/alembic/0.3.2/alembic-0.3.2.jar from clojars
    Retrieving lein-as-resource/lein-as-resource/2.5.0/lein-as-resource-2.5.0.jar from clojars
    Error loading refactor-nrepl.ns.clean-ns: clojure.lang.ArityException: Wrong number of args (2) passed to: StringReader, compiling:(abnf.clj:189:28)

A quick online check of current versions prompted me to try the following:

    {:user {:plugins [[cider/cider-nrepl "0.9.1"]
                  [refactor-nrepl "1.1.0"]]
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.7"]]}}

which still has issues.  I know of at least three issues:

1. consider [these samples](https://github.com/limist/literate-programming-examples).  Load the [first one](https://github.com/limist/literate-programming-examples/blob/master/00-just-code-blocks/simple-code-blocks.org).  First, the key prefix for cider-mode, `M-m m`, which is advertised in README.org, doesn't work. It produces `M-m m is undefined` in the emacs minibuffer.

2. Manually running `M-x cider-jack-in` produces dire errors:
```
; CIDER 0.10.0snapshot (package: 20150911.253) (Java 1.8.0_51, Clojure 1.7.0, nREPL 0.2.7)
ERROR: CIDER's version (0.10.0-snapshot) does not match cider-nrepl's version (0.9.1). Things will break!
WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 1.2.0-SNAPSHOT (package: 20150910.1031) and 1.1.0, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.
user> 
```
3. ok, well there appears to be a semi-functional repl, but trying to evaluate any Clojure code block with `C-c C-c` for example
```
#+BEGIN_SRC clojure
#(reduce * (range 1 (inc %)))
#+END_SRC
```
produces `Not connected.` in the emacs minibuffer.  The following attempt to hack it into shape did not work
```
#+BEGIN_SRC emacs-lisp
(setq org-babel-clojure-backend 'cider)
(require 'cider)
#+END_SRC
```
Other org-babel languages like python and C work just fine.  Seems only my clojure support is busted.

**Comment by mbertheau** [comment] 2015-09-12 21:00
It seems like you're using the master branch. Try the develop branch.

Currently, master doesn't deliver on its perceived promise of being a stable version. The reason is that dependencies to other emacs packages are unversioned, and they break API sometimes. develop is usually fine, but not always. No really stable version of spacemacs so far, sorry :)

**Comment by rebcabin** [comment] 2015-09-12 21:07
Well, at least spacemacs is under active development, unlike some of the other "starter kits" that go hot for a while and then are abandoned :)   I will try "develop" and then return here ...

**Comment by robbyoconnor** [comment] 2015-09-12 22:10
spacemacs is very much under development -- a lot of the features are written by community members :) Use `develop` -- it could break at times but it's fixed fast.

**Comment by rebcabin** [comment] 2015-09-13 00:46
Ok, I moved to `develop` and still can't eval org-babel Clojure blocks inline, but now the errors are different. Consider the following Clojure block, which computes `factorial(10)`
```
#+BEGIN_SRC clojure
(reduce * (range 1 10))
#+END_SRC
```
Made sure that `clojure` layer is included in `dotspacemacs-configuration-layers`, trying `C-c C-c` with point in that block in an org-mode buffer produces 

    Cannot open load file: no such file or directory, slime

Easy enough to fix, I think.  Open `.spacemacs` via `M-m f e d` and make sure `slime` is included in `dotspacemacs-configuration-layers`.  Reinitialize via `M-m f e R`, which runs a suite of unit tests, reporting the results in an org-mode buffer (Bravo! btw :+1: ) .  I see

    *** FAIL: slime

Ok, going down one more level in the rabbit hole, I see that the new `layers` directory in `develop` does not have a `slime` subdirectory. I recursively copy the `slime` layer from `master`, where it's named `contrib/slime`, to `develop`, where it looks like it should be named `layer/slime`, and do a cold exit and restart of emacs.  Spacemacs downloads and compiles `slime`,

    (Spacemacs) --> installing slime:slime... [1/1]

but ultimately failing with 

    Error: Symbol's function value is void: add-to-hook

so I am blocked again :(

**Comment by TheBB** [comment] 2015-09-13 06:41
The slime layer was renamed common-lisp. The function add-to-hooks was renamed spacemacs/add-to-hooks in develop, so that's why you can't just copy and paste from the master branch.

With your example I get

> No org-babel-execute function for clojure!

**Comment by sooheon** [comment] 2015-09-13 11:23
RE: org babel clojure, check in your org directory if the newest version of ob-clojure.el is there. The one with cider back end support is somewhat new, and I've had to install it manually to get it working on my setup.

**Comment by rebcabin** [comment] 2015-09-13 13:26
Manually installing ob-clojure.el in my private layer and doing as you suggest gets me back to the `Not connected` error state in all cases trying to eval clojure code blocks, even after manually running `cider-jack-in`.  At least all the `slime` craziness and and nrepl version noise is gone.  

My private layer looks like this:
```
.
|-- extensions
|   |-- ob-C
|   |   `-- ob-C.el
|   `-- ob-clojure
|       `-- ob-clojure.el
|-- extensions.el
`-- packages.el
```

my extensions.el
```
(setq rebcabin-post-extensions
      '(;; post extension names go here
        ob-C
        ob-clojure
        ))
(defun rebcabin/init-ob-C ()
  (use-package ob-C))
(defun rebcabin/init-ob-clojure ()
  (use-package ob-clojure))
```

and the relevant parts of my `.spacemacs` initialization looks like this

```
   dotspacemacs-configuration-layers
   '(rebcabin
     common-lisp
     clojure
     dash
     emacs-lisp
     org
     )
```

```
(defun dotspacemacs/user-init ()
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((C . t)
     (clojure    . t)
     ))
  (require 'ob-clojure)
  (setq org-babel-clojure-backend 'cider)
  )
```

**Comment by bjeanes** [comment] 2015-09-16 10:06
I had a similar problem for a long time. The issue seems to be the CIDER pre-release version. I added the following to my `dotspacemacs/init` function:

``` lisp
  (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
  (add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
  (add-to-list 'package-pinned-packages '(clj-refactor . "melpa-stable") t)
  (add-to-list 'package-pinned-packages '(cljr-helm . "melpa-stable") t)
  (add-to-list 'package-pinned-packages '(ac-cider . "melpa-stable") t)
```

If you do that then delete the existing packages from `~/.emacs.d/elpa/`, they'll reinstall the stable versions and you should get further.

**Comment by sooheon** [comment] 2015-11-01 17:19
@rebcabin There are many small issues inside this main issue. The lein profile recommendation has been updated. `M-m m` not being the clojure leader key is because the buffer you are working with is in org-mode. The major mode leader key `M-m m` depends on the major mode, so unless you have the org layer installed, it should do nothing. The problems with ob-clojure I *have* been able to reproduce, and I share your frustration, but it's an upstream issue, as they occur regardless of spacemacs. This issue as it is should be closed, and a separate issue focused on  getting to the bottom of the org-babel compatibility should be opened. However, it's doubtful that can be fixed within spacemacs' scope.

**Comment by StreakyCobra** [comment] 2015-11-08 18:16
Following @sooheon review, I agree this issue as one entity will probably go nowhere. I close it, but I encourage you @rebcabin to open new issues about the problem that weren't answered by this one :relaxed:

**Closed by StreakyCobra** 2015-11-08 18:16 UTC
Labels: Clojure
