### ISSUE TITLE
git status conflicts with line num

### ISSUE THREAD

**Issue by lufeihaidao** [syl20bnr/spacemacs#1741] opened 2015-05-27 03:44 UTC
![tmp](https://cloud.githubusercontent.com/assets/1731864/7828422/bb934b9c-0465-11e5-90b3-efc56c542384.jpg)

**Comment by person808** [comment] 2015-05-27 03:53
I think this bug is fixed in the `develop` branch. Could you try switch to the branch and see if this behavior still exists?

**Comment by lufeihaidao** [comment] 2015-05-27 04:04
@person808 I switched to dev branch and this problem seems still existing

**Comment by person808** [comment] 2015-05-27 04:07
How did you turn on line numbers?

**Comment by lufeihaidao** [comment] 2015-05-27 04:07
@person808 `SPC t n`

**Comment by person808** [comment] 2015-05-27 05:05
@lufeihaidao Unfortunately, I cannot reproduce on the develop branch. Maybe someone else will.

**Comment by jupl** [comment] 2015-05-27 05:21
Have you tried switching to another theme?

**Comment by lufeihaidao** [comment] 2015-05-27 06:39
@person808 Thank you all the same ~ 

@jupl The theme I use is `zenburn` and I am using terminal. In GUI, git status shows in right column.

**Comment by jupl** [comment] 2015-05-27 06:48
There are quirks in terminal mode. Unfortunately one of them is trying to show both the git gutter and line numbers at the same time. The personal fix for you is to just call `(git-gutter:linum-setup)` so git-gutter in terminal plays nice with line numbers. I think it's difficult to integrate easily because if the function mentioned is called and line numbers are not turned on then the git-gutter does not appear anyway.

**Comment by lufeihaidao** [comment] 2015-05-27 08:06
@jupl bad news 😞

**Comment by syl20bnr** [comment] 2015-05-27 20:20
I thought `git-gutter:linum-setup` was already called if the linum is activated.
@lufeihaidao try adding `(global-linum-mode)` to your `dotspacemacs/config`

**Comment by jupl** [comment] 2015-05-27 21:03
Ah. In my case I'm turning `linum-mode` for source code which is why I'm not using global.

**Comment by syl20bnr** [comment] 2015-05-27 21:06
@jupl should work also with local `linum-mode`.

**Comment by syl20bnr** [comment] 2015-05-27 21:07
Here is the code: https://github.com/syl20bnr/spacemacs/blob/develop/contrib/!tools/git/packages.el#L77-L79

**Comment by jupl** [comment] 2015-05-31 02:25
Strange. For some reason is never getting invoked and I have to call it myself. I'm trying to debug.

**Comment by person808** [comment] 2015-05-31 02:32
I think we would need a hook on linum to check if git-gutter is enabled then call `git-gutter:linum-setup`. Right now, it is only checked at startup, not after the toggle.

**Comment by TheBB** [comment] 2015-08-26 07:40
Since git-gutter is removed, I'm closing this as out of date.

**Closed by TheBB** 2015-08-26 07:40 UTC
Labels: bug :-(, Terminals
