### ISSUE TITLE
Salt layer <enter> key binding

### ISSUE THREAD

**Issue by numkem** [syl20bnr/spacemacs#3369] opened 2015-10-13 14:12 UTC
With the release of 0.104, the salt layer was changed to use salt-mode.

The keybinding for the standard `enter` key has been changed to do a line return and indent by one. While this would work with blocks of codes it doesn't work at all when I just want to add empty lines.

I understand I should probably go back to normal mode and do something like `2o` to insert 2 lines but I feel that is a pretty big step for just inserting empty lines.

Is there a way to change this in the layer itself or at least point me to how to change a keybinding in a mode.

Thank you.

**Comment by TheBB** [comment] 2015-10-16 10:23
I can't reproduce this. I don't know anything about salt files, but I can hit return as much as I like with no issues. Is there some specific file I can test?

**Comment by numkem** [comment] 2015-10-16 14:30
Files needs to finish by `.sls` and they are in a yaml format.

Examples [here](https://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html)

**Comment by StreakyCobra** [comment] 2015-10-26 20:24
I managed to reproduce it and indeed it seems to be an annoying behaviour. Sadly I don't know anything about salt. Pinging the salt-layer's author in case he can help: @beardedprojamz :-)

**Comment by beardedprojamz** [comment] 2015-10-26 20:32
https://github.com/beardedprojamz/salt-mode - I'm happy to accept pull requests - but not currently using spacemacs for my everyday stuff - or writing enough salt to be annoyed. :stuck_out_tongue: It'd probably be something in how the mmm-mode works with the jinja stuff. I definitely doubt it's a spacemacs issue, as the layer just turns the mode on. But, you could also test salt-mode directly with vanilla emacs too.

**Comment by StreakyCobra** [comment] 2015-10-26 20:44
Thanks for the information @beardedprojamz. I didn't knew you weren't using Spacemacs anymore, sorry for bothering you :smile:

@numkem It seems to be an upstream issue, so you can report it there (and contribute maybe :wink:  ). That said I think we can close this issue :smile:

**Comment by beardedprojamz** [comment] 2015-10-26 20:48
I'm pretty flakey, so I might wrap back around at some point. :wink: But definitely a responsive maintainer and will merge any fixes :+1:

**Comment by StreakyCobra** [comment] 2015-11-06 19:07
As it's finally not a spacemacs bug, I'll close this one. All information are there if somebody want to go further with this bug (i.e. contributing upstream :relaxed:)

**Closed by StreakyCobra** 2015-11-06 19:07 UTC
Labels: should report upstream
