### ISSUE TITLE
in haskell-mode: type information truncated

### ISSUE THREAD

**Issue by rubenmoor** [syl20bnr/spacemacs#2489] opened 2015-07-31 13:07 UTC
I couldn't find anything about this issue anywhere, so I don't know whether or not it might be a configuration thing. It might even be specific to my particular setup.

When I do `haskell-process-do-type` I get the type information as expected. However, sometimes it is reduced to a too small, useless string, truncated with "..", e.g. for my symbol named `context`:

    context [ :: ArrowXm .. ]

I use `ghci` with `stack` in a local config as described [here](https://github.com/commercialhaskell/stack/blob/master/.dir-locals.el)

    ((haskell-mode
      . ((haskell-indent-spaces . 4)
         (hindent-style . "johan-tibell")
         (haskell-process-type . ghci)
         (haskell-process-path-ghci . "stack")
         (haskell-process-args-ghci . ("ghci"))))
     (haskell-cabal-mode
      . ((haskell-process-type . ghci)
         (haskell-process-path-ghci . "stack")
         (haskell-process-args-ghci . ("ghci")))))

**Comment by WraithM** [comment] 2015-09-09 16:57
I have the same problem with ghci and cabal.

**Comment by d12frosted** [comment] 2015-09-09 17:04
Hm... could you, please, paste an example of code that leads to this? Cause I tried with some very long names - but it still shows everything.

**Comment by d12frosted** [comment] 2015-09-09 17:09
Just in case. I tried to use following test code:

```
data MyType a b c d e = MyType a b c d e
data Easy0 = Easy0
data Easy1 a = Easy1 a
data Easy2 a b = Easy2 a b
data Easy3 a b c = Easy3 a b c
data Easy4 a b c d = Easy4 a b c d

gen :: MyType Easy0 (Easy1 Easy0) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy4 (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))))
gen = MyType Easy0 (Easy1 Easy0) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy4 (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))) (Easy3 (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0)) (Easy2 (Easy1 Easy0) (Easy1 Easy0))))
```

**Comment by WraithM** [comment] 2015-09-09 17:10
I tried both `SPC m h t` and `M-x haskell-process-do-type`. I get:
```
returnError [ :: (Data.Ty .. ]
```
When it should be:
```
returnError :: (Typeable a, Exception err) 
    => (String -> Maybe Oid -> String -> String -> String -> err)
     -> Field -> String -> Conversion a
```

**Comment by WraithM** [comment] 2015-09-09 17:11
Maybe it's that it's on multiple lines?

**Comment by WraithM** [comment] 2015-09-09 17:12
I'm a total noob to spacemacs and emacs. I started two days ago. I'm mostly a vim user.

**Comment by d12frosted** [comment] 2015-09-09 17:18
Hm. That's strange. Again - works for me. I've tried to call it from other module (so it get's all those `Data.Typeable...`), but it shows full type. OK, will try to test it in different situations later. 

If you have more info about this problem - share it :)

**Comment by WraithM** [comment] 2015-09-09 20:15
I think the problem is only for multiline results. I get a normal response if the type annotation comes out as only one line.
For example:
```
literalColumn :: String -> Literal
```
However, if the type annotation is more than one line in ghci, I get that weird brackets and ellipses result.

Again, total noob question, is this a problem with my "minibuffer" not resizing?

**Comment by d12frosted** [comment] 2015-09-10 06:29
OK. I've figured out what's wrong. 

First of all - you are right about multiline. Internally, `haskell-mode` uses `haskell-mode-message-line` to print message from REPL. 

```lisp
(defun haskell-mode-message-line (str)
  "Message only one line, multiple lines just disturbs the programmer."
  (let ((lines (split-string str "\n" t)))
    (when (and (car lines) (stringp (car lines)))
      (message "%s"
               (concat (car lines)
                       (if (and (cdr lines) (stringp (cadr lines)))
                           (format " [ %s .. ]" (haskell-string-take (haskell-string-trim (cadr lines)) 10))
                         ""))))))
```

So you can't configure this one. But, a lot of `haskell-mode` users set `haskell-process-use-presentation-mode` to `t`, so instead of showing you the result in echo area (as message) it will use separate buffer with this information (buffer can be closed by pressing `q`). You can enable it by setting `:variables` when enabling layer:

```lisp
(d12-haskell :variables
                  haskell-enable-hindent-style "chris-done"
                  haskell-enable-shm-support t
                  haskell-process-type 'stack-ghci
                  haskell-process-use-presentation-mode t)
```

Another thing you can try to use (if you don't like using `presentation-mode`) is to enable `haskell-doc-mode`. So now in echo area you will see full type of expression. But some people find it a bit annoying. To enable this mode just add `(add-hook 'haskell-mode-hook 'haskell-doc-mode)` to `dotspacemacs/user-config`.

**Comment by d12frosted** [comment] 2015-10-07 14:38
@TheBB, shouldn't it be closed?

**Comment by TheBB** [comment] 2015-10-07 14:40
If you say so. I tend to go for the easy ones first, this one had a lot to digest.

**Closed by TheBB** 2015-10-07 14:40 UTC
Labels: Haskell, question

**Comment by d12frosted** [comment] 2015-10-07 14:45
Well, it's not active anymore. And also it's not something on Spacemacs side. So I thought that it's OK to close this one. :smile:
