### ISSUE TITLE
can't set python-shell-interpreter to "ipython3"

### ISSUE THREAD

**Issue by rahiel** [syl20bnr/spacemacs#5988] opened 2016-05-05 13:52 UTC
#### Description
I have `(setq python-shell-interpreter "ipython3")` in `dotspacemacs/user-config` but pressing `C-c C-c` in a python file suggests to start `ipython` instead of `ipython3`. This also changes the variable `python-shell-interpreter` to `ipython`. I have both `ipython` and `ipython3` on my computer.

#### Reproduction guide
- Start Emacs
- Put `(setq python-shell-interpreter "ipython3")` in the `dotspacemacs/user-config` function in `.spacemacs`
- Open a python file, press `C-c C-c`

*Observed behaviour:*
Emacs asks to run python using /usr/bin/ipython -i

*Expected behaviour:*
Emacs should run python using /usr/bin/ipython3 -i

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 better-defaults
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 deft emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking html javascript
 (latex :variables latex-enable-auto-fill t)
 python scheme rust)
```

**Comment by bmag** [comment] 2016-05-05 20:14
I'm able to reproduce the bug.

The command `(setq python-shell-interpreter "ipython")` is executed every time a python file is loaded, because the function `python-setup-shell` is added to `python-mode-hook` [here](https://github.com/syl20bnr/spacemacs/blob/c93e47028ca1600345a9199bccaae78bd9935d62/layers/%2Blang/python/packages.el#L264-L266). Unless @cpaulik knows if there's a reason for this, I think we should call `python-setup-shell` once (in `:init` section of use-package) and remove it from the hook.

**Comment by cpaulik** [comment] 2016-05-05 22:01
@bmag I think you are right. @rahiel As a general thought you might run into less problems in the long run if you manage your python versions with something like `pyenv` instead of relying on the system provided ones.

**Comment by bmag** [comment] 2016-05-06 07:12
@rahiel until #5997 is merged, you can put this in `dotspacemacs/user-config` as a  workaround:
```elisp
(with-eval-after-load 'python
  (remove-hook 'python-mode-hook #'python-setup-shell))
```

**Comment by rahiel** [comment] 2016-05-07 12:36
Thank you @bmag for the quick fix and the workaround!

@cpaulik `pyenv` looks useful, thanks for suggesting it.

**Comment by d12frosted** [comment] 2016-10-03 08:25
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Closed by d12frosted** 2016-10-03 08:25 UTC
Labels: Fixed in develop

**Comment by sohailsomani** [comment] 2017-12-20 13:43
I still need to do this:

```
  (with-eval-after-load 'python
    (add-hook 'python-mode-hook (lambda () (setq python-shell-interpreter "python3"))))
```

**Comment by Rapidice** [comment] 2018-01-09 13:54
Related to this issue, I have added the line  
`(setq python-shell-interpreter "python")`
in my user-config. 
However, everytime I activate a different virtualenv, python-shell-interpreter changes it's value to "ipython" if there is a valid IPython in the virtualenv.
