### ISSUE TITLE
 spacemacs-purpose-popwin :config: Invalid slot name: "#<purpose-conf :mode-purposes>

### ISSUE THREAD

**Issue by chengyi** [syl20bnr/spacemacs#9583] opened 2017-09-14 06:09 UTC
#### Description :octocat:
<Error (use-package): spacemacs-purpose-popwin :config: Invalid slot name: "#<purpose-conf :mode-purposes>", nil

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
report error

*Expected behaviour:* :heart: :smile:
start normal

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 9341e1d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips nil)
 graphviz javascript ivy better-defaults emacs-lisp markdown org lua python
 (colors :variables colors-enable-nyan-cat-progress-bar
         (display-graphic-p))
 git ranger
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t c-c++-enable-clang-format-on-save nil)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 (chinese :variables chinese-enable-youdao-dict t)
 (gtags :disabled-for clojure emacs-lisp javascript latex python shell-scripts)
 deft shell
 (semantic :disabled-for emacs-lisp)
 prow)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by astanzys** [comment] 2017-09-15 12:41
Getting the same issue.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 9341e1d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion themes-megapack clojure emacs-lisp org)
```

**Comment by CeleritasCelery** [comment] 2017-09-15 13:48
Does this error impair any functionality that you know of?

**Comment by bmag** [comment] 2017-09-15 17:37
A backtrace would have been nice. Anyway, caused by #9426. I'll revert that change later today/tomorrow.

**Comment by bmag** [comment] 2017-09-16 15:08
I reverted the change (see https://github.com/syl20bnr/spacemacs/commit/22deb279c35b494e27e2d88dc7d9a9cfd16f9415), so it should be fixed now. The bug was introduced and fixed in develop, so I'm closing the issue.

**Closed by bmag** 2017-09-16 15:08 UTC
Labels: - Bug tracker -, Regression :-(
