### ISSUE TITLE
[REGRESSION] "Fancy title" causes tramp to hang

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#8939] opened 2017-05-21 18:28 UTC
#### Description :octocat:
Commit 8db21403 causes tramp /sudo::/ to hang. Prior to this commit, there was no problem.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f f`
- `/sudo::/`

*Observed behaviour:* :eyes: :broken_heart:
Emacs hangs, you must hit `C-g` many times to break the hang.

*Expected behaviour:* :heart: :smile:
Tramp sudos and shows contents of `/`

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. 8db21403)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by JAremko** [comment] 2017-06-07 07:05
@syl20bnr Can't reproduce on Linux

**Comment by syl20bnr** [comment] 2017-06-10 15:50
I use tramp everyday and I did not encountered it in macOS with Emacs 25. Maybe an Emacs 26 only issue. Also I use helm completion.

Anyone has a clue why fancy title can prevent tramp from working properly ?

**Comment by aaronjensen** [comment] 2017-06-10 15:55
Can you try the exact repro steps with a default spacemacs using ivy and see if it reproduces please? I will try with 25.

**Comment by aaronjensen** [comment] 2017-06-10 17:31
It does repro on emacs 25 and with helm. 

Here's a profile stack where you can clearly see the infinite recursion with ivy:

```
- command-execute                                                 597  97%
 - call-interactively                                             597  97%
  - funcall-interactively                                         597  97%
   - counsel-M-x                                                  494  80%
    - ivy-read                                                    475  77%
     - read-from-minibuffer                                       387  63%
      - redisplay_internal (C function)                           291  47%
       - eval                                                     291  47%
        - spacemacs/title-prepare                                 290  47%
         - let*                                                   290  47%
          - format-spec-make                                      289  47%
           - abbreviate-file-name                                 284  46%
            - file-name-case-insensitive-p                        280  45%
             - tramp-file-name-handler                            278  45%
              - apply                                             278  45%
               - tramp-sh-file-name-handler                       278  45%
                - apply                                           278  45%
                 - tramp-handle-file-name-case-insensitive-p                276  45%
                  - make-nearby-temp-file                         274  44%
                   - temporary-file-directory                     265  43%
                    - tramp-file-name-handler                     265  43%
                     - apply                                      265  43%
                      - tramp-sh-file-name-handler                265  43%
                       - apply                                    265  43%
                        - tramp-handle-temporary-file-directory                265  43%
                         - tramp-get-remote-tmpdir                262  42%
                          - file-directory-p                      260  42%
                           - tramp-file-name-handler                259  42%
                            - apply                               257  42%
                             - tramp-sh-file-name-handler                257  42%
                              - apply                             257  42%
                               - tramp-sh-handle-file-directory-p                257  42%
                                - tramp-run-test                  257  42%
                                 - tramp-get-test-command                257  42%
                                  - tramp-send-command-and-check                257  42%
                                   + tramp-send-command                257  42%
```

The profiler stack from helm is different and I don't see recursion in it, so I'm not sure exactly what's going on with that.

**Comment by yesimon** [comment] 2018-10-22 20:53
I have the same problem bypassed for now via `dotspacemacs-frame-title-format nil` in `dotspacemacs/init`.

**Comment by heartnheart** [comment] 2019-01-25 12:34
It happens to me today with Emacs 27.0.50 on Linux built from master (5961e4fa4), and here are my findings.


If   ``dotspacemacs-frame-title-format`` is set to  ``"%a"`` then `M-x find-file /sudo::/`  will hang. But setting it to default value ``%I@%S`` will solve the problem.

If I don't call function ``abbreviate-file-name`` in function ``spacemacs/title-format``  [line 698](https://github.com/syl20bnr/spacemacs/blob/e8a6bc269065e9a0d68466cccf315a8cefa41877/core/core-dotspacemacs.el#L698), then Tramp won't hang. I can confirm it with ``emacs -Q``

**Comment by aaronjensen** [comment] 2019-01-25 15:01
I also get a hang even if the title format is nil and I enter a wrong password.

**Comment by aaronjensen** [comment] 2019-01-25 15:19
Tracked it down to `global-auto-revert-mode`. If that is enabled (which it is by default in spacemacs) then emacs hangs after entering the wrong password in tramp `/sudo::/`. I couldn't say why just yet, or how to fix it... I can't reproduce on `emacs -Q` either other than a slight hang.

**Comment by cubranic** [comment] 2019-11-07 15:02
Bump... It looks like there is a fix being discussed in @aaronjensen's bug report, but it will go into Emacs master and may be a while before it's released. Any thoughts on implementing a workaround in Spacemacs or even reverting 8db2140?

**Comment by syl20bnr** [comment] 2019-11-09 15:07
We can remove support for `%a` and add a comment to the code pointing to this issue or Emacs bug thread. Would this work ?

**Comment by cubranic** [comment] 2019-12-19 20:41
It would for me, but @aaronjensen is the reporter and has done the most to investigate. :-)

Also, should the "To be reproduced" label be removed, since @heartnheart has done so [above](https://github.com/syl20bnr/spacemacs/issues/8939#issuecomment-457559638)

**Comment by aaronjensen** [comment] 2019-12-19 20:57
Yeah, i'm fine w/ that.

**Comment by aaronjensen** [comment] 2019-12-19 22:24
I should also mention that this is fixed, at least in Emacs 27. It may be in 26 as well, so it may be that this doesn't need to dealt with at all?

**Comment by allentiak** [comment] 2020-06-23 00:13
By reading [the previous comments](https://github.com/syl20bnr/spacemacs/issues/8939#issuecomment-552108520), it seems this could be easily closed.
@syl20bnr Is there a specific pending task for this?

**Comment by allentiak** [comment] 2020-06-23 00:23
If it's something small, maybe I could lend a hand...

**Comment by duianto** [comment] 2020-06-26 10:54
Let's close this since aaronjensen (the issue author) mentioned that it's been fixed.

**Closed by duianto** 2020-06-26 10:54 UTC
Labels: - Bug tracker -, Regression :-(, Tramp
